### ISSUE TITLE
Enhancement: Localizations' problems

### ISSUE THREAD

**Issue by chrismaliszewski** [NPBruce/valkyrie#1000]
Hi. 

Although on a daily basis I use the English version of the app, whenever I switch to Polish I have problems with the translations in the app. What I mean by that is, the texts are not always accurate as they have other connotations in my language. I presume it may be a problem in all languages and may require a change/enhancement to the existing code. 

Two examples. I think both English and Polish versions of the Menu are not clear enough. 
**(')** English 'Start Scenario' I think is not the best choice of words. Why the English version doesn't simply say 'New game'? In Polish, it's even worse... The Polish translation is 'Nowy Scenariusz'. Unfortunately, the word 'Nowy' means 'New' rather than 'Start'. Of course, you can say 'let's start a new scenario' even in Polish but leaving just 'new scenario' is misleading/a bad translation. The current translation suggests that by choosing this option you can _create a new scenario_, rather than _start a new game_. 
Additionally, 'Load Scenario'. Being honest, I again don't like the English version. Why not just simply 'Load Game'? Polish translation is 'Załaduj Scenariusz'. Although 'Load' can be translated to 'Załaduj' and would be ok, but... Both versions' texts suggest that you will load _a scenario_ rather than _a game's state_. This is especially visible when you click on the button and you see 'Select Save', not 'Select Scenario'. 

Causes of the problem: I think (but I may be wrong) the above problems (and probably there are some others) are caused because instead of creating separate lines in Localization.XXX.txt files for a whole phrase (i.e. Menu option), you merge two separate words into one phrase. In general, it should work but as you can see from above **(')** 'Start Scenario' -> 'Nowy Scenariusz' example, not always and it can create a translation mess.

Solution: I'd suggest creating separate lines for phrases instead of merging words. 

Finally, here is a link to an updated Polish version. The current Polish version was missing some new texts from English and I corrected 2 small mistakes in the version: https://drive.google.com/open?id=1rT_3p0tcznLErS57KSm6PbjnJd3N_iUI

What do you think about the idea?

PS. The Polish version still has a problem with the 'Przedmioty' word mentioned in the issue https://github.com/NPBruce/valkyrie/issues/739

**Comment by redwolf2** [comment]
I agree. This could be could be handled very elegant, by us putting more formatted strings in the english translation file. Other languages can then overwrite it.

**Comment by BenRQ** [comment]
Yes I can easily add new texts, but I would need a translation in every language for each.

I see 2 texts to create in your feedback @chrismaliszewski , am I right?
 - Start game
 - Load game

I've also seen your translation proposal for Polish, I will take it at the same time as the rest.

**Comment by chrismaliszewski** [comment]
I think simply going with 'New game' and 'Continue' as the official MoM app does should be fine. If anyone wants to change it, they will give you their propositions.

Here are translations of the 'New game' and 'Continue' to all languages: https://docs.google.com/spreadsheets/d/1V4frBHparJFqeRyQWSZXbFApBSfnfJ6JTu7hzUqR4Eo/edit?usp=sharing
The only problem is Japanese 'Continue' which is a little different than the official text. From what I found, the official the MoM text is rather a translation for 'Continue game'. Can't say exactly.

Cheers.

**Comment by BenRQ** [comment]
Done
