### ISSUE TITLE
Issues with Changing Music / Intro Dialogues

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#1006]
### Description of Problem or Question
There appears to be a bug in 2.1.5 with how music works (that was not there in previous versions).

If you play a custom music track, if another event attempt to play while it is "fading out" it will not play and will default to the default music (or the last playlist you played).

I have attached an example scenario.

### Valkyrie Version
2.1.5

### Attach Save, Quest or Scenario

Example, however this is happening during the intro of "A Strain on Reality" too 
[SoundBug.zip](https://github.com/NPBruce/valkyrie/files/2769499/SoundBug.zip)

**Comment by BenRQ** [comment]
It's fixed.
I'm pretty sure it never worked properly.
