### ISSUE TITLE
unexpected behavior on VAR event call

### ISSUE THREAD

**Issue by antontimmermans** [NPBruce/valkyrie#1008]
### Description of Problem or Question
When processing this Var based event call I expected (hoped) that the cancel option is visible to allow a player not to enter a number and suffer the consequences.
![image](https://user-images.githubusercontent.com/42072372/51425816-81c0d280-1be1-11e9-91aa-b0668eaf7bcb.png)

Running thisThe cancel option is not displayed:
![image](https://user-images.githubusercontent.com/42072372/51425928-4aebbc00-1be3-11e9-8522-875711b3f6d7.png)

Is this correct behavior?
### Valkyrie Version
2.1.5

**Comment by redwolf2** [comment]
Put an event before the event. That's also how the official scenarios do it.

**Comment by antontimmermans** [comment]
@redwolf2 i am not sure if i understand you corectly. Do you mean to group all events under the button {action} place gems under one 'Collection'-event?

**Comment by redwolf2** [comment]
Like so:

![grafik](https://user-images.githubusercontent.com/4141621/51437827-e0e71b80-1ca3-11e9-92e2-a1aaea2ca95c.png)

![grafik](https://user-images.githubusercontent.com/4141621/51437833-e6dcfc80-1ca3-11e9-90a3-db1a99afb084.png)

[EditorScenario1.zip](https://github.com/NPBruce/valkyrie/files/2776456/EditorScenario1.zip)

**Comment by antontimmermans** [comment]
Ah thanks. Now it is clear what you mean.
I have it modeled like that, but I was hoping (expecting) that I could add a cancel option to the number entry dialogue. That would make it look a bit more nice in my opinion. The investigator can check the item and see which skill needs to be rolled and decide not to do it and leave it for another investigator without spending an action. 
I guess that description will have to be put in the 'do you want to pull the crate event'(from your example) including an action button. something like this:
![image](https://user-images.githubusercontent.com/42072372/51439826-02560080-1cc0-11e9-89de-850aff391ff6.png)

![image](https://user-images.githubusercontent.com/42072372/51439834-1568d080-1cc0-11e9-9f98-add114ec12e0.png)

**Comment by antontimmermans** [comment]
@scrubbless @redwolf2 

Thanks for your thoughts and wise words on this subject. You are both right that the scenario story building can handle this in a nice way. I will close this issue.
And maybe if I get inspiration I might spends some word for hints& tips in the tutorial (unless you beat me to it :) ).

**Comment by scrubbless** [comment]
I've been stupidly busy at work, so you may well beat me to it.

I have a bunch of topics to write up.

If you want to suggest a topic and want to write it up yourself or want me to put it in my words please feel free to submit it as an issue here:

https://github.com/scrubbless/MoM2ndTutorial/issues

**Comment by antontimmermans** [comment]
as per suggestion added a doc and a ticket in the tutorial repository . see https://github.com/scrubbless/MoM2ndTutorial/issues/12

closing the issue
