### ISSUE TITLE
Czech translation

### ISSUE THREAD

**Issue by redwolf2** [NPBruce/valkyrie#1011]
Chech translation is missing @Dlaha might help with that See also: https://github.com/NPBruce/valkyrie/pull/1002#issuecomment-456939874

**Comment by ententeak** [comment]
hello, i've made Czech translation, but dont know how to post it here on github, so [here](https://valkyrie.ententeak.cz/Localization.Czech.txt) is my file.

I just have issues with the used Font, where aren't accented symbols like ěščř...
So if its possible to enable for translators to use "custom" fonts (*.ttf) and state them in the localizaton file to avoid this issue...

**Comment by vidimus** [comment]
@scrubbless or @antontimmermans , could you close this issue? It was solved.
