### ISSUE TITLE
Deleting MoM folder will state, that the official MoM app is not installed

### ISSUE THREAD

**Issue by redwolf2** [NPBruce/valkyrie#1015]
### Description of Problem or Question
Delete %AppData%\Roaming\Valkyrie\MoM

You will get this message, even though that is not the case and the import will complete

![grafik](https://user-images.githubusercontent.com/4141621/51721982-126d3780-2054-11e9-88ef-3a63228e1637.png)

### Valkyrie Version
2.2 Test version

**Comment by BenRQ** [comment]
OK I will have a look.

**Comment by BenRQ** [comment]
Fix regression introduced in #656
