### ISSUE TITLE
Question - CAB style event packs

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#1018]
I've been creating some complex and interesting event chains recently. One specific is a fun lock picking puzzle that I'd like to share to the wider community in the future.

I was thinking I could create code snips of each file (events.ini, ui.ini) that could be pasted into other people's scenarios with the relevant images and sounds. However I think the complexities might deter people.

My question is, is it possible to create additional folders (or zips) then reference them easily from your events.ini and ui.ini.

My thinking is I could make a predefined puzzle/event chain then share it so people could add it to their scenarios without having to fully understand how it works.

**Comment by redwolf2** [comment]
Git supports submodules. You can link one git repo to another. Maybe you could build upon that.

https://www.youtube.com/watch?v=8Z4Cmhji_FQ

**Comment by scrubbless** [comment]
I was thinking something along the lines of: Have a folder that contained the mini scenario (event chain) and it's content.

Then the other author just copies that pack into their scenario and references the trigger event of the external event chain in their scenario.

That would then make those events in that chain appear in their list so they can modify the event text if required. Since they may want to change up some bits to tailor it to their scenario.

How is it done - splitting up ini files and subevents  in descent quests?

**Comment by redwolf2** [comment]
That is exaclty what submodules do, they act as a folder inside the repository: Oh, scrubbles updated his puzzle? Let me update my submodule. Update complete. Now let me zip it to a .valkyrie file.

> How is it done - splitting up ini files and subevents in descent quests?
Yes, I would think so.

**Comment by NPBruce** [comment]
You can move any compoent to a custom .ini file (ie: include/extra_events.ini) this could be included in any number of scenarios. You can also package multiple scenarios into the same .valkyrie package if you like with common ini files.

**Comment by scrubbless** [comment]
Awesome, thanks guys. I'll have a play around!
