### ISSUE TITLE
[Windows 10] Valkyrie will not load

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#1021]
### Description of Problem or Question
When I attempt to open Valkyrie (double click the icon from install folder or a shortcut) it flashes up this error and closes:
![image](https://user-images.githubusercontent.com/32058089/51806894-8e939500-2277-11e9-943a-a937af8f269f.png)

It will not launch at all.

Log file attached.

### Valkyrie Version
2.1.5 (2.0.1, 21.4, 2.2 test)

### Attach Save, Quest or Scenario
Log File:
%LOCALAPPDATA%Low\NA\Valkyrie\output_log.txt
[output_log.txt](https://github.com/NPBruce/valkyrie/files/2800532/output_log.txt)

**Comment by redwolf2** [comment]
Please drag and drop that shotcut into Notepad++ and "Save as..." → "shotcut.txt" and copy it here.

**Comment by scrubbless** [comment]
The shortcut is what was in the issue text. The outpu_log.txt is attached

**Comment by BenRQ** [comment]
Not much to work with in the logs.
Can you please share the crash dump ?
You should find it here : .../AppData/Local/Temp/NA/Valkyrie/Crashes/

**Comment by scrubbless** [comment]
[Valkyrie Crash.zip](https://github.com/NPBruce/valkyrie/files/2809397/Valkyrie.Crash.zip)

**Comment by BenRQ** [comment]
Thanks @scrubbless.

I found many thread with the same error " UnityPlayer.dll caused an Access Violation (0xc0000005) ".
It is always related to something in the system environment.

Can you please try the following solutions, step by step, and see if any of those things solve the issue ?

1) disable antivirus : start Valkyrie again (any version)
2) reinstall version 2.1.5 from the .exe (not the zip), start Valkyrie again
3) run Valkyrie 2.1.5 as admin
4) update your graphic card driver, start Valkyrie again
5) rolldown your graphic card driver to an older version, start Valkyrie again

**Comment by scrubbless** [comment]
Thanks @scrubbless.

I found many thread with the same error " UnityPlayer.dll caused an Access Violation (0xc0000005) ".
It is always related to something in the system environment.

Can you please try the following solutions, step by step, and see if any of those things solve the issue ?

disable antivirus : start Valkyrie again (any version) - Done no effect
reinstall version 2.1.5 from the .exe (not the zip), start Valkyrie again - Done no effect
run Valkyrie 2.1.5 as admin - Done no effect
(also ran in compatibility mode)
update your graphic card driver, start Valkyrie again - Done no effect
rolldown your graphic card driver to an older version, start Valkyrie again - Not done this, but not sure why it will help if an upgrade didn't help (I can't never update my GFX card because of Valkyrie!)

**Comment by scrubbless** [comment]
I have followed that error through some threads and there are suggestions that it may be unity. I did install that to try to get to grips with Valkyrie code.

So I will try updating that I guess, a memory test is running at present on that device (30% not a single error, so I suspect it'll pass, since nothing else is complaining).

**Comment by BenRQ** [comment]
It could be interesting to uninstall Unity too.
Somehow Valkyrie may use the wrong dll file.

**Comment by scrubbless** [comment]
Yeh I did that and it didn't help. I am just installing the latest version.

**Comment by scrubbless** [comment]
Memory test completed without error

**Comment by BenRQ** [comment]
:( 

Next step will be more technical.
Can you please try to get logs with this tool ?

https://docs.microsoft.com/en-us/sysinternals/downloads/procmon

We may see something unexpected there.

**Comment by scrubbless** [comment]
It's ok, I work in IT. Not specificly used procmon I. Trouble shooting but should be able to get you some logs from it

**Comment by redwolf2** [comment]
https://forum.unity.com/threads/unity-2018-2-7f1-windows-standalone-crash-on-first-run-unityplayer-dll-caused-an-access-violation.556585/

**Comment by scrubbless** [comment]
Citrix workspace can go fuck itself. I won't be around tonight, but please share one if you have one. Always eager to test new versions!

**Comment by scrubbless** [comment]
It was Citrix workspace... Uninstalled it Valkyrie works like a charm.
