### ISSUE TITLE
[MacOS] Black Start Screen

### ISSUE THREAD

**Issue by redwolf2** [NPBruce/valkyrie#1022]
Testing for MacOS (10.14.2 Mojave), MoM and DrtL at their latest versions according to Steam.

The Beta (2.2.20190125) seems to freeze after the "Made with unity" logo. I've left it running for 5 minutes and no response so far:
<img width="532" alt="captura de pantalla 2019-01-27 a la s 2 59 25 p m" src="https://user-images.githubusercontent.com/2722773/51804837-37c09800-2244-11e9-84d7-440fe5faed8e.png">
For what it's worth, the official release (2.1.5) does work fine:
<img width="688" alt="captura de pantalla 2019-01-27 a la s 3 01 57 p m" src="https://user-images.githubusercontent.com/2722773/51804868-80785100-2244-11e9-9715-cd912c9710b8.png">
EDIT: Thanks to @scrubbless for pointing out where the log is (in macOS is in ~/Library/Logs/Unity/Player.log)
LOG: [Player.log](https://github.com/NPBruce/valkyrie/files/2801101/Player.log)

_Originally posted by @alvaromunoz in https://github.com/NPBruce/valkyrie/issues/1013#issuecomment-457940003_

**Comment by BenRQ** [comment]
related to #980

**Comment by BenRQ** [comment]
Should be fixed, please test with next test release and re open if required.
