### ISSUE TITLE
[Scenario Editor] Empty List in Offline Mode still shows filtered items

### ISSUE THREAD

**Issue by redwolf2** [NPBruce/valkyrie#1024]
### Description of Problem or Question

I downloaded 1 scenario for testing valkyrie-windows-2.2.20190125. Still in offline mode. Although the app says it has filtered out 5 scenarios (I have no idea how 5...), there is nothing displayed. 
![clipboard01](https://user-images.githubusercontent.com/7532602/51864660-378ddd00-23a9-11e9-9927-241b206638e2.jpg)

_Originally posted by @chrismaliszewski in https://github.com/NPBruce/valkyrie/issues/1013#issuecomment-458293039_

### Valkyrie Version

2.2.20190125 Test version

**Comment by BenRQ** [comment]
@chrismaliszewski
Can you please share a screenshot of the filter popup ?

**Comment by chrismaliszewski** [comment]
I was playing around so the numbers are different now:
![image](https://user-images.githubusercontent.com/7532602/51866323-9bb2a000-23ad-11e9-9c2a-54f3a9b9bd9e.png)
![image](https://user-images.githubusercontent.com/7532602/51866308-8fc6de00-23ad-11e9-97b9-f2895242e592.png)
Where is the log file in Windows? I can share it, if you want.

**Comment by chrismaliszewski** [comment]
I'll exaplain you all the process. With scereenshots. Please wait.

**Comment by chrismaliszewski** [comment]
1. Opening the app and clicking Start Scenario.
![image](https://user-images.githubusercontent.com/7532602/51866540-18de1500-23ae-11e9-97e7-20139f6ba9b0.png)
See Offline caption. 
2. Clicking filtering button. Clicking Ok (without changing the filters). 
![image](https://user-images.githubusercontent.com/7532602/51866572-34492000-23ae-11e9-957f-2526a77c62f8.png)
3. Selecting all languages and removing the tick doesn't help.
![image](https://user-images.githubusercontent.com/7532602/51866615-488d1d00-23ae-11e9-800a-9ae0f4572a60.png)
![image](https://user-images.githubusercontent.com/7532602/51866620-4c20a400-23ae-11e9-8e6f-5f11f1a436a3.png)
4. As mentioned in another issue https://github.com/NPBruce/valkyrie/issues/1023, Offline caption disappears after you come back to SE. 
![image](https://user-images.githubusercontent.com/7532602/51866630-55aa0c00-23ae-11e9-9677-c713b157a274.png)

**Comment by BenRQ** [comment]
Related to #1023 , should now be fixed for the black screen part.

This can be closed, as I will investigate 'forever offline mode' in #1025
