### ISSUE TITLE
Stuck in offline mode 

### ISSUE THREAD

**Issue by chrismaliszewski** [NPBruce/valkyrie#1025]
As I mentioned in a few other issues and @scrubbless in his comment https://github.com/NPBruce/valkyrie/issues/1013#issuecomment-457515661 (last dot), the app can switch to 'forever offline mode' and there is no way to make it works again. 

I tried:
1. removing Valkyrie dir in %appdata% and reinitiating it (no success),
2. removing valkyrie-windows-2.2.201901225 catalogue and unzipping it again under a new path (no success),
3. removing %userprofile%\appdata\locallow\NA\Valkyrie (no success),
4. adding the app to firewall exceptions (just in case) (no success),
5. playing with regedit. No success. I removed NA/Valkyrie subkey from it, run the app and it was online. So I restarted the app but it was offline again and removing the subkey doesn't help again. So it was something else but I don't know what exactly.

_Originally posted by @chrismaliszewski in https://github.com/NPBruce/valkyrie/issues/1013#issuecomment-458317617_

**Comment by BenRQ** [comment]
Can you please try again and wait 30 seconds / 1 minute in the menu before entering the scenario explorer ? 
Please keep the focus on the app while waiting.

If this does not solve the problem, I may request a Wireshark capture at some points but probably with another test version as we are in HTTPS right now.

**Comment by chrismaliszewski** [comment]
Yeah, it solves the 'foo' problem, that's opening the app, waiting for ~30s-1m and then clicking Start Scenario. 
Entering SE before creating some kind of connection to the server causes 'foo' and the connection is never established in the session again so a restart is required.

**Comment by BenRQ** [comment]
What do you mean by "foo" ?

**Comment by chrismaliszewski** [comment]
I meant 'fom' - 'forever offline mode', sorry :)

**Comment by chrismaliszewski** [comment]
@BenRQ, I agree with you regarding the proper work of the 'Offline' caption. I still have a question regarding your comment https://github.com/NPBruce/valkyrie/issues/1023#issuecomment-458336711. It's better to discuss it here as it relates to 'switching to online mode after you enter SE too early' matter. 

From what you're saying, I understand that 'Offline/online mode is based on the availability of the quest list' but how many times and when it is checked? I guess it's not just one time when the app opens, right? Because otherwise, the 'Offline' caption wouldn't disappear. 
So, another question is, what happens when another list is loaded? And is the list loaded (downloaded and parsed) or just is a check of its availability done? If the latter is done only, that might be the cause of not displaying the list of scenarios and the black screen. If it's loaded, there might be something wrong here. 

And the last question outside of your comment. Why does it take so much time for the app to determine if someone is off- or online? 
Wouldn't it be better to just check internet availability in the menu (if not, you're offline), then if a user enters SE, only check if the quest file is available (if not, display offline caption then) and repeat the above scenario everytime?

**Comment by BenRQ** [comment]
> From what you're saying, I understand that 'Offline/online mode is based on the availability of the quest list' but how many times and when it is checked? I guess it's not just one time when the app opens, right? 

Download is only done once, after game selection, before the menu is displayed.
It's done in background so user with bad connection don't get stuck for 30 seconds will we wait for a timeout.

>Why does it take so much time for the app to determine if someone is off- or online?

In your case the download finishes after you enter the scenario explorer.
I guess your download speed is slower than mine, that's why I don't see the issue.
In the meantime, the app displays the local quest list.

> Wouldn't it be better to just check internet availability in the menu ?

That's what I'm doing, by download a (still) small text file : the scenario list.
I think it's a good method, as we need it anyway.

Now I need to think of what we can do when the file is downloading, but not yet available.
Probably I can display a better / dynamic text, instead of OFFLINE.
OFFLINE, can be displayed only in case of error.

**Comment by BenRQ** [comment]
@chrismaliszewski  thanks I appreciate your help.
I will try with the vpn tool, do you have a VPN server to propose so I don't spend too much time finding a suitable configuration ?

Regarding your analysis, you are guessing a lot here, and are mixing things up a bit :)

It works like this:
1) file download is starting
2) menu is displayed
3) user enters SE too early,
4) as scenario list is not being downloaded, list of local scenarios is created,

Nothing is interrupted, there was just a display issue for all users offline.
This issue of display has been fixed.

**Comment by chrismaliszewski** [comment]
When you open the app, you will see a list of VPN servers there. Choose any. I usually use Japanese ones as they are fast, but this case you need something slow so check a server's speed listed. Rember one thing: sometimes it's impossible to connect to a certain server so try another one. 

I'm guessing because I don't know the code so I try to interpret how things may work to give the results which I see. 

So you're saying that the display issue of users offline is fixed. But we agreed that I'm not offline. The app sees me as if I was offline because the quest list hasn't been processed yet. And for some reason, the list is not displayed later on when I re-enter SE. I'll wait for the results of your VPN tests. 

If you need me to check something for you, let me know.

**Comment by BenRQ** [comment]
Issue is fixed.
Problem was the list (the C# object) was not updated once the download is finished.
Both offline mode and online mode are now working properly.
