### ISSUE TITLE
Text not available with 2.2

### ISSUE THREAD

**Issue by BenRQ** [NPBruce/valkyrie#1026]
Testing for 2.2 - Android

Issues encountered:

- Import took 5-6 minutes

- When I loaded the scenario list it didn't display images (on poor 4g connection). Went back to main screen and it crashed Valkyrie. App froze up completely had to force quit.

- Missing text on content:
![screenshot_20190125-083105_valkyrie](https://user-images.githubusercontent.com/32058089/51734207-bd451c00-207b-11e9-99db-dd3db34d2e95.jpg)

- Home made scenarios (in your editor folder) no longer show. Means you can't test a scenario with specific expansions only selected.

- Exiting the scenario filter (author, rating etc) causes it to hang for a little while. Twice now I've tried to hit the 'Ok' button a second time (assume I miss pressed) and it started downloading a scenario.

- Missing reference names
![screenshot_20190125-083823_valkyrie](https://user-images.githubusercontent.com/32058089/51734526-b074f800-207c-11e9-996d-3e79bfd52b69.jpg)

![screenshot_20190125-083834_valkyrie](https://user-images.githubusercontent.com/32058089/51734550-b9fe6000-207c-11e9-9150-ca8e8a7a458e.jpg)

![screenshot_20190125-083937_valkyrie](https://user-images.githubusercontent.com/32058089/51734564-c5518b80-207c-11e9-8e1b-8bb9fbc1b2d7.jpg)

![screenshot_20190125-084007_valkyrie](https://user-images.githubusercontent.com/32058089/51734585-d9958880-207c-11e9-84d4-07bb4c5bdfec.jpg)

There are a lot of these.

Note: @BenRQ  during testing you should delete Valkyrie and the Valkyrie folder before installing and testing the new version. Import seems to be a very common issue.

_Originally posted by @scrubbless in https://github.com/NPBruce/valkyrie/issues/1013#issuecomment-457497937_

**Comment by MrTantum** [comment]
I did some testing on my android tablet and had the same problems:

![image](https://user-images.githubusercontent.com/31658807/51938739-262aec00-240e-11e9-83aa-1242769887bd.png)

For some reasons not all texts are corrupted:

![image](https://user-images.githubusercontent.com/31658807/51938751-317e1780-240e-11e9-980d-cd0e76d076ad.png)

**Comment by BenRQ** [comment]
This was not related to import, but to the optimisations on content data.

The bug was here in previous version, but was not visible, because we were always reloading the same content.
Content was loaded before the text was available.

This is now fixed, and optimisations is still available (mostly visible when navigating in menus).

**Comment by BenRQ** [comment]
@MrTantum it's also fixed for Descent of course.
Thanks for report.
