### ISSUE TITLE
2.2: "End Campaign phase"-Button is being cut off 

### ISSUE THREAD

**Issue by MrTantum** [NPBruce/valkyrie#1029]
### Description of Problem or Question
I did some testing on my android tablet (resolution 1920x1200 px, 10.1 inch). One of the buttons in descent campaign screen (shadow rune campaign) seems to be cut off (marked in red):

![image](https://user-images.githubusercontent.com/31658807/51940654-e87c9200-2412-11e9-8004-7988b1fa970d.png)

### Valkyrie Version
2.2
### Attach Save, Quest or Scenario
1. Download Shadow rune campaign, 
2. skip the first mission, 
3. go to town 
4. go back to campaign screen

**Comment by BenRQ** [comment]
Hi 
Can you please share a screenshot of the same screen, with 2.1.5 ?

**Comment by BenRQ** [comment]
This is probably related to #1003

**Comment by BenRQ** [comment]
@MrTantum if you agree, I'll close this ticket as it is a duplicate of #1003

**Comment by MrTantum** [comment]
Yes it's a duplicate.
