### ISSUE TITLE
Rus translation update

### ISSUE THREAD

**Issue by Ssid113** [NPBruce/valkyrie#1031]
[Localization.Russian.txt](https://github.com/NPBruce/valkyrie/files/2814241/Localization.Russian.txt)

Added missing tags. Updated text
I add all the tags, it's easier to track changes and update

**Comment by redwolf2** [comment]
@Ssid113 Be aware, that you don't need to include lines, that don't differ from the english translation. I removed those.

Created a pull request here: https://github.com/NPBruce/valkyrie/pull/1032

**Comment by Ssid113** [comment]
@redwolf2 Ok, i use google sheets. I will change the export to exclude such keys.

**Comment by redwolf2** [comment]
I also found, that a comma ( `,` ) is added to comments

**Comment by Ssid113** [comment]
Thank you for your comment. Corrected. This was due to column combining.
![screenshot_4](https://user-images.githubusercontent.com/20969762/52054645-407bdb80-256e-11e9-931f-2a3c7fb10ca0.png)

Now it works like this
[Localization.Russian.txt](https://github.com/NPBruce/valkyrie/files/2817234/Localization.Russian.txt)

**Comment by BenRQ** [comment]
@redwolf2 Did you include the latest version of this file?
Just want to know if I can take the pull request.

**Comment by redwolf2** [comment]
Not yet, but will now.

**Comment by BenRQ** [comment]
Merged
