### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by redwolf2** [NPBruce/valkyrie#1034]
I've just noticed that my Polish translation for FILTER_TEXT_NUMBER_OF_FILTERED_SCENARIO is wrong. Please correct it to:
FILTER_TEXT_NUMBER_OF_FILTERED_SCENARIO,Odfiltrowano scenariuszy: {0}

_Originally posted by @chrismaliszewski in https://github.com/NPBruce/valkyrie/issues/1033#issuecomment-459601143_

**Comment by BenRQ** [comment]
Done
