### ISSUE TITLE
"Go Offline", even tough already in "Offline Mode"

### ISSUE THREAD

**Issue by redwolf2** [NPBruce/valkyrie#1035]
Start Scenario -> Click 'Go Offline' -> Back -> Start Scenario. There will again be 'Go Offline' although the app is in the offline mode (at least it acts as it is by no showing proper data). So to go back to online you need to click 'Go Offline' -> 'Go Online'. 

## Valkyrie Version

2.2.20190131 

_Originally posted by @chrismaliszewski in https://github.com/NPBruce/valkyrie/issues/1033#issuecomment-459646508_

**Comment by BenRQ** [comment]
Fixed
