### ISSUE TITLE
MoM Data Files for Linux

### ISSUE THREAD

**Issue by Jedevold** [NPBruce/valkyrie#1039]
### Description of Problem or Question
I'm trying to run Valkyrie for MoM on Linux. I'm having trouble finding out how to get the data files from the steam app. Since Steam MoM isn't supported on linux I've tried to install it using the steps on this thread :
 
[https://community.fantasyflightgames.com/topic/227088-linux-support-for-the-app/](url)

The app runs on my computer, but I can't find where the MoM files are located. Any pointers? Is there another way of getting the files?

**Comment by redwolf2** [comment]
Check out this link, it is for descend, but it should be similar:

https://github.com/NPBruce/valkyrie/issues/584#issuecomment-424091717

**Comment by Jedevold** [comment]
That worked! Thanks!
