### ISSUE TITLE
Online Mode/Offline Mode needs translation

### ISSUE THREAD

**Issue by redwolf2** [NPBruce/valkyrie#1040]
Go Online/Offline needs translating. 

POLSKI:

```
Tryb Online
Tryb Offline
```

('tryb' means 'mode'),

GERMAN:

```
Online-Modus
Offline-Modus
```

## Valkyrie Version

2.2.20190131 #1033

_Originally posted by @chrismaliszewski in https://github.com/NPBruce/valkyrie/issues/1033#issuecomment-459646508_

**Comment by Ssid113** [comment]
Did not understand a little what exactly to translate

RUS
1. The text on the button means switching to another mode (not the name of the current mode)
Then the translation will be:
Go Online -> Перейти в Онлайн-режим
Go Offline -> Перейти в Офлайн-режим
2. But if the text on the button corresponding to the current mode:
Online Mode -> Онлайн-режим
Offline Mode -> Офлайн-режим

**Comment by chrismaliszewski** [comment]
@Ssid113, good point. I didn't think about it this way. My previous Polish proposition of captions was bad as it didn't indicate the button can be used to change a mode to another one. 

So, Polish translation will be:
1. Go Online -> Wł. tryb Online 
Go Offline -> Wł. tryb Offline
2. Online Mode -> Tryb Offline
Offline Mode -> Tryb Offline

**Comment by chrismaliszewski** [comment]
@BenRQ, I think @Ssid113 has a point in which I commented. 

Writing "Offline/Online mode" doesn't give a hint to a user that you can click on this text to switch between modes. It'd need an additional indication that it's possible. While 'Go Offline/Online' immediately suggests that 'clicking this thing changes something'. 

At least I see it this way.

**Comment by BenRQ** [comment]
OK so this is the current behaviour.

Please note that you can also have the text "offline" without any actions, if you run Valkyrie while you are disconnected.

**Comment by BenRQ** [comment]
I don't know if we will have tabs in the future.
That's part of the question : what should we have in the future :)

**Comment by chrismaliszewski** [comment]
If being completely offline displays just 'Offline' text it's fine. 
I'll comment about my the future regarding the topic here https://github.com/NPBruce/valkyrie/issues/1037.

**Comment by redwolf2** [comment]
I am ok with both tabs or no tabs.

**Comment by BenRQ** [comment]
I still need some translations here.

We can keep "GO ONLINE" and "GO OFFLINE" as a target for 2.2, and improve the UI in 2.3 with a nice button or something smart.

Text colors:
GO ONLINE would be green (as it is the recommanded mode)
GO OFFLINE would be red.

**Comment by redwolf2** [comment]
English:
GO ONLINE
GO OFFLINE

GERMAN: 
ONLINE GEHEN
OFFLINE GEHEN

**Comment by BenRQ** [comment]
I realize there are 4 texts to translate if we want to make this text clear.

Changing mode : 
`GO_OFFLINE,GO OFFLINE
`GO_ONLINE,GO ONLINE


This is displayed if you go in the scenario explorer before the quest list is downloaded.
`DOWNLOAD_ONGOING,Downloading...

This is displayed if you have a problem of connection.
`OFFLINE_DUE_TO_ERROR,OFFLINE (network error)

**Comment by redwolf2** [comment]
GERMAN:
GO_OFFLINE,OFFLINE GEHEN
GO_ONLINE,ONLINE GEHEN
DOWNLOAD_ONGOING,Lade herunter...
OFFLINE_DUE_TO_ERROR,OFFLINE (Netzwerkfehler)

**Comment by chrismaliszewski** [comment]
PL
GO_OFFLINE, Wł. tryb Online
GO_ONLINE, Wł. tryb Offline
DOWNLOAD_ONGOING,Pobieranie...
OFFLINE_DUE_TO_ERROR,OFFLINE (błąd poł. intern.)

If the last one is too long, you can either use 'błąd poł. int.' or 'błąd sieci' instead.

**Comment by BenRQ** [comment]
@chrismaliszewski you can use full words, I will adapt button size.

"Włączyć tryb Offline" fits fine for example

**Comment by BenRQ** [comment]
OK I've integrated the translations and cleaned up the button a bit.
Looks not that bad I think.
Closing.
