### ISSUE TITLE
Grey play button is confusing

### ISSUE THREAD

**Issue by BenRQ** [NPBruce/valkyrie#1042]
The grey play button is confusing, like it's not available, maybe a green or blue button may be better. On my phone it was really hard to press, but suspect will be fine on a tablet.

![screenshot_20190131-212824_valkyrie](https://user-images.githubusercontent.com/32058089/52086808-bb111f00-259f-11e9-8893-07ea037ccb10.jpg)

_Originally posted by @scrubbless in https://github.com/NPBruce/valkyrie/issues/1033#issuecomment-459514276_

**Comment by BenRQ** [comment]
I'm happy to take and try any proposal on this.
Here is the original file.

![button_play](https://user-images.githubusercontent.com/40794717/52156267-7791e000-2687-11e9-950e-d5b8efb7d9a4.png)


Please keep the aspect ratio.

**Comment by redwolf2** [comment]
![play](https://user-images.githubusercontent.com/4141621/52156497-c8560880-2688-11e9-879c-86ab6b1819cd.png)

**Comment by redwolf2** [comment]
I've seen that and I agree, a "play" button is the most valid symbol to use. The button in the image is more of a "next" button and has some simiarities to a paper plane symbol used for "send".

**Comment by scrubbless** [comment]
Could you just update your grey button to green or blue? I'd do it but on my phone ATM!

**Comment by redwolf2** [comment]
![play2](https://user-images.githubusercontent.com/4141621/52157111-e1f94f00-268c-11e9-92d6-314996ee9bbc.png)
![play3](https://user-images.githubusercontent.com/4141621/52157113-e1f94f00-268c-11e9-8f17-6278cb234a4a.png)

I can anso make a blue variant ... one moment

**Comment by BenRQ** [comment]
![image](https://user-images.githubusercontent.com/40794717/52157240-e5d9a100-268d-11e9-9b43-0561f07dbcd0.png)

![image](https://user-images.githubusercontent.com/40794717/52157259-04d83300-268e-11e9-95c1-b88df3ae2c69.png)

**Comment by BenRQ** [comment]
![image](https://user-images.githubusercontent.com/40794717/52157272-21746b00-268e-11e9-868a-ae3262bf3121.png)

![image](https://user-images.githubusercontent.com/40794717/52157286-3f41d000-268e-11e9-9a65-a3ba1b1c398b.png)

**Comment by BenRQ** [comment]
![image](https://user-images.githubusercontent.com/40794717/52157303-55e82700-268e-11e9-92db-fd00b733afc2.png)

**Comment by redwolf2** [comment]
The halo doesn't look as great as expected the non halo ones are better. I will also recreate a round one.

**Comment by BenRQ** [comment]
Halo is probably to strong.
I think it would be better with a really dim light, like a small shadow.

The green, is to "fluo" for me :P

**Comment by redwolf2** [comment]
![play8](https://user-images.githubusercontent.com/4141621/52157380-f3dbf180-268e-11e9-973c-97975f537868.png)
![play7](https://user-images.githubusercontent.com/4141621/52157381-f4748800-268e-11e9-9fa1-7afd742c1b33.png)

**Comment by BenRQ** [comment]
![image](https://user-images.githubusercontent.com/40794717/52157396-11a95680-268f-11e9-8b18-9e7dfe775b21.png)

![image](https://user-images.githubusercontent.com/40794717/52157404-238af980-268f-11e9-9c92-78fbfea19411.png)

**Comment by redwolf2** [comment]
I like the green one, it pops the best. Here they are with a mild halo.

![play9](https://user-images.githubusercontent.com/4141621/52157509-c2aff100-268f-11e9-87d4-5966111d94d0.png)
![play10](https://user-images.githubusercontent.com/4141621/52157510-c2aff100-268f-11e9-85e2-01ed6339729c.png)

**Comment by BenRQ** [comment]
We won't see the dark halo on black background

**Comment by BenRQ** [comment]
All this is already way better than my awful grey button.
I let you guys vote and agree on one, or propose even more logos.

I need to sleep, I'll take new capture if required tomorrow.

**Comment by redwolf2** [comment]
![play11](https://user-images.githubusercontent.com/4141621/52157591-7a450300-2690-11e9-8d19-9b5072f36d6f.png)
![play12](https://user-images.githubusercontent.com/4141621/52157592-7a450300-2690-11e9-8e0d-d5dd8c73f8f0.png)

ok, no problem.

**Comment by chrismaliszewski** [comment]
Wow, the last green is great, @redwolf2!

**Comment by scrubbless** [comment]
Yeh that's cool, last green one!

**Comment by BenRQ** [comment]
First green : 👍 to vote
![image](https://user-images.githubusercontent.com/40794717/52164058-9a55e000-26eb-11e9-9108-fb08c83fc689.png)

Second green : 👀 to vote
![image](https://user-images.githubusercontent.com/40794717/52164042-6e3a5f00-26eb-11e9-8bff-a81944e2a60f.png)

**Comment by BenRQ** [comment]
I like both 😋

**Comment by scrubbless** [comment]
Second green is sharper.

Can we make the download button like that maybe in blue!?

**Comment by BenRQ** [comment]
There is also the update button

![button_download](https://user-images.githubusercontent.com/40794717/52164382-d5a6dd80-26f0-11e9-9a31-8c7fc870e7e1.png)
![button_update](https://user-images.githubusercontent.com/40794717/52164383-d63f7400-26f0-11e9-9927-d4bfc15bb3fd.png)

**Comment by redwolf2** [comment]
![button_download](https://user-images.githubusercontent.com/4141621/52164812-b5c6e800-26f7-11e9-8802-8f816d036e39.png)

![button_refresh](https://user-images.githubusercontent.com/4141621/52164816-bcedf600-26f7-11e9-93c8-10acebc5afa0.png)

![button_play](https://user-images.githubusercontent.com/4141621/52164817-bf505000-26f7-11e9-8ee6-4b8bdeed803b.png)

**Comment by BenRQ** [comment]
![image](https://user-images.githubusercontent.com/40794717/52166187-3bec2a00-270a-11e9-9dee-21f667c3122d.png)

**Comment by scrubbless** [comment]
Yeh that download arrow is off center :laugh:

**Comment by BenRQ** [comment]
Should I commit and close this then ?

**Comment by scrubbless** [comment]
@redwolf2 does that download arrow look off center to you?

**Comment by chrismaliszewski** [comment]
It's off as the other things are. 

If we want to be precise. 
When you change the size of images to 5cm, the circle instead of having a diameter of 4cm, it has 4.1cm. Because of that, the shapes are in the centre of the circle but off the centre of the image for 0.1cm. 

The confusion is enlarged more with the icons which have different sizes and are placed in a different manner:
-'update' is the widest; it's a reference point here,
-'download' is centred to it; it's ok,
-'play' however is not centred but aligned to the right of the circle but we more focus on it so the 'download' button seems off because of that.

0.1cm off is not a problem nor the alignment is. All looks fine to me and I **really** like the design!

**Comment by scrubbless** [comment]
Haha it looks off in Ben's screenshot too. Maybe I have an eye for alignment.

It's not a problem still looks good, jsut didn't know if it was an easy fix

**Comment by redwolf2** [comment]
Here is a more centered download arrow, it wasn't off by much. I think most of it is due to the swirl creating an optical illusion?!

![button_download](https://user-images.githubusercontent.com/4141621/52170693-4da3f080-274f-11e9-99ef-a6a054ea1a18.png)

**Comment by scrubbless** [comment]
Yeh that looks better and you could be right about the illusion :D

**Comment by BenRQ** [comment]
OK it's merged. Closed.
