### ISSUE TITLE
'Unable to locate MoM' text is too large

### ISSUE THREAD

**Issue by chrismaliszewski** [NPBruce/valkyrie#1043]
I'm right after reinstalling my Windows OS so I don't have Steam MoM yet. 
I've just opened valkyrie-windows-2.2.201900131 and noticed below:
![image](https://user-images.githubusercontent.com/7532602/52160135-06e4d500-2714-11e9-8827-5721abb2f85d.png)
For some reason, the text has become too big. I don't remember this the issue from before. 
It happens in all resolutions, no matter Windowed or not. 

### Valkyrie Version
valkyrie-windows-2.2.201900131

**Comment by BenRQ** [comment]
Fixed with incoming fix of #1047
