### ISSUE TITLE
Spam GameObgect. Leak

### ISSUE THREAD

**Issue by Ssid113** [NPBruce/valkyrie#1044]
### Description of Problem or Question
in the menu choice of scenarios. Spaming UIBG GameObgect.
black square in lower left corner
![screenshot_4](https://user-images.githubusercontent.com/20969762/52162109-f9adf300-26df-11e9-8f3e-11fe8b859981.png)

Noticed spam GameObjects TextSizing. As I understand each text creates an object TextSizing
![screenshot_3](https://user-images.githubusercontent.com/20969762/52119121-2bb04e00-2629-11e9-84b4-29ef4dfac69d.png)
When opening and closing inventory in the middle of a game, the memory used increases by  3~8MB
[OpenCloseInventory.zip](https://github.com/NPBruce/valkyrie/files/2821288/OpenCloseInventory.zip) - this is Profiler.data

For phones and tablets I think this is critical. The longer you play the more memory is used.

### Valkyrie Version
2.2.20190131

**Comment by BenRQ** [comment]
Well spotted, it's now fixed.
There are definitely some optimisations to do still, but that's a first step.
