### ISSUE TITLE
MoM 1.7.1 (826) - broken import on Android

### ISSUE THREAD

**Issue by redwolf2** [NPBruce/valkyrie#1045]
### Description of Problem or Question
The latest update to version 1.7.1 (826) seem to have a new sprite Atlas. Windows does not seem to be affected, there was an [update for it yesterday](https://steamdb.info/app/478980/depots/), I tested.

Obb file affected: main.821.com.fantasyflightgames.mom.obb

See also: https://github.com/NPBruce/valkyrie/issues/964

**1.7.0**

![image](https://user-images.githubusercontent.com/40794717/49552379-8ceec600-f8f3-11e8-96a6-dec565ed72a2.png)

**1.7.1**
![1 7 1](https://user-images.githubusercontent.com/4141621/52164919-6ed9f200-26f9-11e9-904c-dbf8d08f2d83.png)

### Valkyrie Version
2.5.1 (Android)

**Comment by scrubbless** [comment]
It's like they do it on purpose

**Comment by BenRQ** [comment]
We need to find a long term solution for this :( 
There must be a way to get the index of this atlas.

**Comment by redwolf2** [comment]
Maybe we could tune the importer to export every sprite from https://docs.unity3d.com/ScriptReference/U2D.SpriteAtlas.GetSprites.html

**Comment by BenRQ** [comment]
My motivation to work on this is close to zero.

I really want to finish what I have started with the Scenario explorer.
I'll look at this after I've released the next test version.

If someone want to fix this in the meantime here is an example of what needs to be done.
No coding required.

Example :
https://github.com/NPBruce/valkyrie/commit/35842cfaf891b746ec473c8375ff795f8fb9c522

**Comment by BenRQ** [comment]
@redwolf2, yes your proposal would probably make the change a bit less tedious.
But I'm not sure we can even use that function, as we may need an index of the Atlas.
Or do you think it's in the file itself ?

**Comment by redwolf2** [comment]
Release, when done is ok for me. 

I found no meta data, that contains the indices. Maybe this is auto generated code, I am not sure.

**Comment by scrubbless** [comment]
@benrq do you have a latest release we can test?

**Comment by redwolf2** [comment]
Release, when done is ok for me. 

I found no meta data, that contains the indices. Maybe this is auto generated code, I am not sure.

Last option is recreating the tokens without images, just names.

![token](https://user-images.githubusercontent.com/4141621/52178802-e62f8480-27d2-11e9-8a7e-54ca8dd3b56d.png)

![token2](https://user-images.githubus

**Comment by scrubbless** [comment]
But it would still jumble the other tokens, like search, walls etc

**Comment by redwolf2** [comment]
Those do not seem to be affected ATM, but can also be recreated.

**Comment by redwolf2** [comment]
Alright, I got the Character Token, but I need all names of those guys. I will do the default explore, search, etc. token next.

![spriteatlastexture-atlas_features_core group 0 -2048x1024-fmt12_original](https://user-images.githubusercontent.com/4141621/52180778-d91e8f80-27ea-11e9-8673-3f449e3ed643.png)

![spriteatlastexture-atlas_features_core group 0 -2048x1024-fmt12](https://user-images.githubusercontent.com/4141621/52180780-db80e980-27ea-11e9-86a3-516e91951adb.png)

**Comment by BenRQ** [comment]
You don't have this yet ? :)

https://cdn.discordapp.com/attachments/517395720446410782/530821468519530506/49438987_2415020575239019_4873057906787876864_n.png

**Comment by redwolf2** [comment]
![spriteatlastexture-atlas_features_core group 0 -2048x1024-fmt12](https://user-images.githubusercontent.com/4141621/52183013-ee53e800-2803-11e9-873c-039ba8838de7.png)

Got the tokens now, will go for investigator and names.

**Comment by redwolf2** [comment]
![spriteatlastexture-atlas_features_core group 0 -2048x1024-fmt12](https://user-images.githubusercontent.com/4141621/52185181-e9e7f900-281c-11e9-9fa2-2bbb32c3fc40.png)

All currently supported investigators by 2.1.5 mapped

**Comment by redwolf2** [comment]
The above should work. I will test to integrate it. On the next iteration, I want simple icons for male/female, colored token. After that I might add own vectors (old woman, child, boy, nurse, etc.) for the different colored token.

**Comment by redwolf2** [comment]
I created a pull request: https://github.com/NPBruce/valkyrie/pull/1049

**Comment by redwolf2** [comment]
Fixed it. I forgot to remove the {import} dir replacement there.
https://github.com/NPBruce/valkyrie/pull/1052

**Comment by redwolf2** [comment]
Merged
