### ISSUE TITLE
Unclear text/button when Steam folder is not found

### ISSUE THREAD

**Issue by redwolf2** [NPBruce/valkyrie#1047]
the worst thing is that I have MoM on my Steam yet the game doesn't detect it by default:
![image](https://user-images.githubusercontent.com/7532602/52231669-69f68780-291f-11e9-903d-f1c70dc716c9.png)
I have my Steam on C: but the games are on D:. I found that the default games' path is stored here C:\Program Files (x86)\Steam\config\config.vdf in BaseInstallFolder_1. 
Maybe in v2.3, the app could look for the game in other Steam's catalogues :).

I forgot that I can click on the text and find EXE on my own. So I'd suggest either:
A. The text should be different to indicate it immediately as a user may not click on the text and run for help. I.e. "Unable to locate Mansions of Madness, install via Steam or click here and find its EXE file". To make the text shorter replace 'Mansions of Madness' with MoM as people should be able to figure it out.
B. OR, create a clearly visible button/thing to click instead of a text rounded by a rectangle which doesn't seem to be clickable. You could use a style of normal buttons from the app but with red text. It'll be better because of two things: a. it'll look like a button, b. you will unify the look of buttons across the app. 
I think the change could land in v2.2.

_Originally posted by @chrismaliszewski in https://github.com/NPBruce/valkyrie/issues/1046#issuecomment-460394932_

## Valkyrie Version

2.2.20190204

**Comment by BenRQ** [comment]
I think the best solution would be to have an additional button, like an open folder.

**Comment by BenRQ** [comment]
> So the red text will be just message and there will be an additional button on a side for each game?

Yes. I thought this was your proposal in B.

My proposal is the best I can think of right now, but if you have another proposal feel free to share it.
If you can draft it and share a picture it would be better.

**Comment by chrismaliszewski** [comment]
Nothing fancy:
![image](https://user-images.githubusercontent.com/7532602/52312804-d7ceac00-2a10-11e9-82df-128f9bb7c16e.png)
Like I said, I think unifying the UI would be good and giving a text in the button which indicates it's clicable while staying red to inform a user that there's a problem :). The text is too long but I can't think about anything short and simple.

**Comment by chrismaliszewski** [comment]
The above proposal is a merge of my A and B ideas:
A - it has a text which clearly indicates what the button is for,
B - what I meant in B before wasn't want to create an additional button but rather to change the look of the current one so it is the same as the rest of the buttons in the game.

**Comment by redwolf2** [comment]
We could run `steam://appnews/478980/`

**Comment by chrismaliszewski** [comment]
@redwolf2, is this regarding the topic? I think I'm missing something. I don't see the connection.

**Comment by redwolf2** [comment]
I was refering to the "intall via Steam" text, but you are right. I will copy it over there.

**Comment by chrismaliszewski** [comment]
Aaa. Hmm. It gave me an idea:
![image](https://user-images.githubusercontent.com/7532602/52314753-e1f4a880-2a18-11e9-980f-2db9dec908d9.png)
But I don't like it that much for some reason...

**Comment by redwolf2** [comment]
Maybe it could be [done](https://en.wikipedia.org/wiki/Duke_Nukem_Forever) like a [link](https://en.wikipedia.org/wiki/Link_(The_Legend_of_Zelda))

**Comment by chrismaliszewski** [comment]
That's what I'm thinking about the first button. The second one has the same even as the current one has.

**Comment by BenRQ** [comment]
I would need translations for 
`CONTENT_LOCATE,Locate the game`

Here is how I did it in this example for Descent : 

![image](https://user-images.githubusercontent.com/40794717/52541743-edd5c700-2d98-11e9-8468-9fa814d24728.png)

![image](https://user-images.githubusercontent.com/40794717/52541727-a4857780-2d98-11e9-98f9-8008cf41cc8d.png)

![image](https://user-images.githubusercontent.com/40794717/52541849-d8ad6800-2d99-11e9-8098-4d5dc87cd1e3.png)

![image](https://user-images.githubusercontent.com/40794717/52541866-19a57c80-2d9a-11e9-8981-0675c6e908d4.png)

**Comment by chrismaliszewski** [comment]
PL: Zlokalizuj grę

**Comment by redwolf2** [comment]
GERMAN: Spielinstallation finden

**Comment by BenRQ** [comment]
OK it's done, closing.

Other translations can be added on request of course.
