### ISSUE TITLE
Enhancement: 'Selected content' check in Editor

### ISSUE THREAD

**Issue by chrismaliszewski** [NPBruce/valkyrie#1054]
It makes sense that a user may only want to create content for expansions that you have so you have them activated in the app. But, theoretically, you could also want to create a scenario when you don't have them or if you haven't activated them yet. So before creating a scenario for the first time (or if you deactivate an expansion), you will always need to remember to activate them first.

Could you create a piece of code that would check whether the list of expansions selected by a user in the 'select content' corresponds with the 'required expansions' list in the editor and, if not, display a message box with a warning? 
At least people won't be asking questions "why the content I used in the scenario doesn't work?". 

OR

Limit the 'Required expansions' list and choosable content in the editor to the expansions that are selected by a user in the 'Select content' menu. _I presume each element such as tiles & tokens have associated an expansion's name with which it comes; if not, it'd be good to do that because if each element type has a list of associated expansions, there is no need for a 'required expansions' list as it can be created automatically._ 
Additionally, it'd be good to create somewhere in the Editor a button with an explanation of what a user must do to choose elements from other expansions. 

I hope you know what I mean.

_Originally posted by @chrismaliszewski in https://github.com/NPBruce/valkyrie/issues/1048#issuecomment-461244805_

**Comment by BenRQ** [comment]
The editor always loads all content, even the one you don't have.
I think this is better this way, because you may want to add in your scenario some content you don't have: to make your scenario more dynamic for example.

**Comment by chrismaliszewski** [comment]
On the other hand, for what I understood from your comment here https://github.com/NPBruce/valkyrie/issues/1048#issuecomment-461241945, you want to limit a test of the scenario to the expansions that you have selected in the 'Select Content'. Did I understand you wrong, then?

**Comment by BenRQ** [comment]
In other words : 
1) you can use any content while you are creating/editing your scenario 
2) you only have the activated/selected content when testing in the editor (or playing of course)

It means you can test the configuration you want., and you are still able to play with all content in the editor.

**Comment by chrismaliszewski** [comment]
I think I know where a mistake in my thinking is. 

In the beginning, it didn't make sense to me to limit tests to only expansions that you've selected if you are able to choose elements from any expansion as to me both cases, tests and choosing elements in the editor, should be limited or unlimited.

Correct me if I'm wrong. A creator may use tokens and monsters from other expansions (not tiles) but a scenario may still be playable with a basic game as a player may replace elements from the basic game or other way around. So the testing you're referring to is about activating/deactivating expansions to check how a scenario looks like depending on the selected expansions, is that right? 

If yes, sorry for wasting your time and the topic can be closed as there is nothing to do.

**Comment by redwolf2** [comment]
You can always close topics that you opened.
