### ISSUE TITLE
MoM - Monsters being set to Spirits when Physical (and visa versa)

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#1057]
### Description of Problem or Question

I have a lot of feedback on my scenarios where generic monsters that are physical are presenting "Spiritual" attack dialogues. 

For example, a deepone is attacked and it says "Bullets are of no use here, you drop your weapon and plead with the spirit, test Influence".

I've also seen the opposite where I can physically attack Ghosts, here is a screenshot example of this:
![image](https://user-images.githubusercontent.com/32058089/52634275-b3fee080-2ebe-11e9-9e6b-d009b0ae1e36.png)

Here is the Spawn settings:
![image](https://user-images.githubusercontent.com/32058089/52634294-bf520c00-2ebe-11e9-9564-f91d74376614.png)

I have not set any Traits in the Spawn, so I would assume that the Base Monsters trait (a Ghost being "Spirit" would be selected), however it does not seem to be working this way. It would be a lot of work to go through all of my spawns and manually select the monsters trait (assuming that will even fix it).

Also its not intuitive to the authors to have to manually set this, since its not a mandatory field.

I've created a small scenario, that can be used to chain spawn monsters and attempt to recreate the issue.

Its very sporadic, so I suspect that monsters that don't have pool traits selected may be randomly pulling events from the entire attack pool? But I may be wrong.

### Valkyrie Version
2.1.5

### Attach Save, Quest or Scenario
[MonsterTest.zip](https://github.com/NPBruce/valkyrie/files/2855704/MonsterTest.zip)

**Comment by scrubbless** [comment]
Here's an example from the same test scenario, this deep one as an unarmed attack is showing up as a spirit:
![image](https://user-images.githubusercontent.com/32058089/52634946-6d11ea80-2ec0-11e9-8fa7-bbc960e348e3.png)

**Comment by scrubbless** [comment]
The next unarmed attack at the same foe is showing correctly as a physical attack:
![image](https://user-images.githubusercontent.com/32058089/52634979-8155e780-2ec0-11e9-959d-9b934db3efc4.png)

**Comment by scrubbless** [comment]
Same monster, trying to shoot it - this little phasing Deep One is a pest!
![image](https://user-images.githubusercontent.com/32058089/52635143-004b2000-2ec1-11e9-83c0-26a3ec4b1156.png)

(Another Physical Monster, getting a Spiritual Attack)

**Comment by BenRQ** [comment]
I think we can consider it as a bug

**Comment by scrubbless** [comment]
Yeh, it's a needle in a haystack kind of bug.

**Comment by BenRQ** [comment]
I got this bug today, while playing.
This one definitely needs a fix, it's killing all the strategy related to the different attack type.

**Comment by BenRQ** [comment]
Thanks a lot for the demo scenario, it helped me a lot.

The traits of the character was simply not checked so you could get a test for any kind of creatures.
(The type of attack was checked though.)

I'm now checking that the attack type correspond to at least one the traits of the monster.
This may lead to some strange behaviour if some monster are "ghost" and "humanoid" for example, but I suppose this should not the case.

This fix will changed the gameplay quite a lot, for the best hopefully.

**Comment by scrubbless** [comment]
The base monsters should have default traits, which can be overridden by the manual trait selection.

Great work finding this out BenRQ.

@NPBruce could you add some context to this bug, was it actually intentional and can you see any issues with Ben's proposed change?
