### ISSUE TITLE
Editor freezes or crashes when selecting tiles [Android/Fire OS]

### ISSUE THREAD

**Issue by IanMoM** [NPBruce/valkyrie#1058]
### Description of Problem or Question

When selecting image drop down menu for tiles, the editor freezes. I'm using a Kindle Fire with the Playstore android version of MoM. Any ideas how to fix this?

### Valkyrie Version
2.1.5

**Comment by redwolf2** [comment]
What's the name of the obb file you were using? `com.fantasyflightgames.mom/main.821.com.fantasyflightgames.mom.obb` should work.
The app is not heavy tested to use with the editor, because scenario creation is to be expected to be done on the pc side.

**Comment by IanMoM** [comment]
Com.fantasyflightgames.mom/main.808.com
How do I get v.821 - the download link on the wiki only links to v.808?

**Comment by IanMoM** [comment]
Also in the android in game editor I can't move tiles or tokens at all - so they just pile on top of each other. I'm using v.808 as the link from the wiki download page only likes to that not v.821. Where do I find the latest version of the OBB?

**Comment by redwolf2** [comment]
https://www.1clickobbapk.com/

**Comment by IanMoM** [comment]
Ok, I've installed that , and it's still crashing when the tile image is
selected. Must be a memory thing as you suggest - at the moment the editor
is completely unuseable on Android.

Is it possible to create local scenarios on the PC then upload them and
redownload them to android to play?

**Comment by redwolf2** [comment]
Yes, that is possible and the way of choice to do it. The editor inside android is more of a: hey there is also a editor ... check it out ... maybe not on android ... type of thing.

**Comment by redwolf2** [comment]
I will close this, since it is in beta 2.2 and will be in the final release.
