### ISSUE TITLE
Beta test, release 2.2 (first release candidate)

### ISSUE THREAD

**Issue by BenRQ** [NPBruce/valkyrie#1059]
Welcome to the beta test of version 2.2!

I've just released the first version release candidate for 2.2.
It means the scope of the version is now closed, and we will only do bugfixes/translation update until official release.

Please enter one new issue for each problem you see, with as many details as possible regarding the way to reproduce it. Screenshots are very welcome.

Version has been officially pre-released here:
https://github.com/NPBruce/valkyrie/releases/tag/prerelease%2F2.2%2Fv2.2.00b

The changelog can probably be improved.
If you are ready to help on this, please raised you hand :)

**Comment by scrubbless** [comment]
#1065 is a deal breaker for release.

**Comment by scrubbless** [comment]
![image](https://user-images.githubusercontent.com/32058089/52918416-a39b9b00-32ee-11e9-9f48-a941a446c987.png)

I like this prompt for Descent!

**Comment by BenRQ** [comment]
Second beta test release incoming.
Closing this one
