### ISSUE TITLE
Expansions icons in 'Select Content'

### ISSUE THREAD

**Issue by chrismaliszewski** [NPBruce/valkyrie#1061]
WHAT TO DO: Could you extend all of the expansions' names in the 'Select Content' menu by adding the icons associated of each of them, in the same manner, as it's done in the official MoM's app?
![image](https://user-images.githubusercontent.com/7532602/52757854-0977f080-306b-11e9-8f4e-4a215c4b9eea.png)
(see brackets with an icon)

Additionally, in SE would it be possible to add a hover event to expansions' icons which would display the expansion's name?

WHY: Simply put: It'd make it easy for players to know an answer to the question 'which expansion am I missing?'. 
In my case, I wanted to test the version and its filtering system. I don't have any MoM expansion so while having 'Hide scenarios with missing expansions' checked, I wanted to add an expansion in 'Select Content' to make any visible. But... I noticed that there are no expansions' icons in the menu what makes the process hard to test. 

### Valkyrie Version
valkyrie-windows-2.2.00b

**Comment by BenRQ** [comment]
Yes I wanted to do that, with the acronym too.
It's done know for MoM, but I still have the issue with Descent symbols : #1071

Also it's a different font for the expansion acronym so it looks a bit strange, but I think it's good enough.
It would be quite painful to change it to use the same font.

![image](https://user-images.githubusercontent.com/40794717/52918040-d0ea4800-32f2-11e9-8e13-8ba525e57c4a.png)

**Comment by chrismaliszewski** [comment]
The font difference is not a problem at all! 

Is a hover effect in SE possible? It's not necessary and could be created later.

**Comment by chrismaliszewski** [comment]
I had one more idea. It'd be a handy feature. When a user clicks on an expansions icon, he/she either:
a. moves directly to the Select Content's submenu with the expansion, can select it there and by, clicking Back, return to the SE 
or
b. toggles the expansion's activation from SE; it'd require refreshing the scenario's line and all things related to that (i.e. disabling possiblity to play the scenario, https://github.com/NPBruce/valkyrie/issues/1065).

**Comment by BenRQ** [comment]
Expansions icons in 'Select Content' is now implemented.
Closing.

Hover effect and activation link are not.
This will require other tickets.

**Comment by chrismaliszewski** [comment]
Sure, I'll create them.
