### ISSUE TITLE
Bug: Offline mode filtering counter wrong result

### ISSUE THREAD

**Issue by chrismaliszewski** [NPBruce/valkyrie#1062]
### Description of Problem or Question
When a user filters out some scenarios in the online mode, i.e.
![image](https://user-images.githubusercontent.com/7532602/52758019-a33f9d80-306b-11e9-86b6-eabbc9db05f6.png)
and then go offline, the number of scenarios filtered out stays the same although it should change, i.e.
![image](https://user-images.githubusercontent.com/7532602/52758058-c8341080-306b-11e9-9bfe-39dd1d556a4a.png)
(there is nothing here, so the number of filtered out scenarios should be 'all').

### Solution proposal
Either of them:
1. Fixing the counter or...
2. The statement could be removed for Offline mode for now **but** if in the future the filtering of the offilne scenarions will be done, it'll need to reappear. 

### Valkyrie Version
valkyrie-windows-2.2.00b

**Comment by redwolf2** [comment]
This is related to: https://github.com/NPBruce/valkyrie/issues/1028

**Comment by chrismaliszewski** [comment]
To some extent, yes.

**Comment by BenRQ** [comment]
I understand #1028 is adding a filter mode.
Filters are already working in offline mode for languages and expansions

Here this is just a bug with the counter not being refreshed when local quest list is empty.
It's fixed.
