### ISSUE TITLE
Bug: List of Offline scenarios not being rebuilt after downloading or deleting a scenario

### ISSUE THREAD

**Issue by chrismaliszewski** [NPBruce/valkyrie#1063]
### Description of Problem or Question
I didn't have any scenario downloaded at the beginning. 

Scenario:
1. Go to offline mode. There should be any scenario there.
2. Go back to online mode. 
3. Download a scenario.
4. Go to Offline mode. There is still nothing there. 

The list is not being rebuilt after downloading a scenario.

**Even worse**, if you delete a scenario, you have a situation like this:
![image](https://user-images.githubusercontent.com/7532602/52758630-e26eee00-306d-11e9-9bcf-a8abc5e61aa7.png)
(there is a download button)
![image](https://user-images.githubusercontent.com/7532602/52758639-e864cf00-306d-11e9-8045-bfc0fa8124b7.png)
(there is a play button)

**I've just crashed the app** by trying to play the deleted scenario :).

If I restart the app, the scenarios show up in Offline mode correctly.

### Valkyrie Version
valkyrie-windows-2.2.00b

**Comment by BenRQ** [comment]
Fixed
