### ISSUE TITLE
Bug: 'Offline mode' unknown authors

### ISSUE THREAD

**Issue by chrismaliszewski** [NPBruce/valkyrie#1066]
### Description of Problem or Question
Problem: offline mode's sorting by author doesn't work. 

Scenario 1:
1. Create a new scenario in the editor and fill in 'Authors' and 'Single text line for Authors' fields. Save changes.  
![image](https://user-images.githubusercontent.com/7532602/52761161-316d5100-3077-11e9-83f9-2d07bd7d7493.png)
2. Go to SE and switch to Offline mode. 
3. Open Sort menu and select Author.
4. Although you've written all the authors' fields, SE will still show 'Unknown authors' message at the top.
![image](https://user-images.githubusercontent.com/7532602/52761211-67123a00-3077-11e9-8013-002d3fbf3906.png)
![image](https://user-images.githubusercontent.com/7532602/52761244-814c1800-3077-11e9-853e-c80bf83659c4.png)

Scenario 2:
1. Go to SE online mode.
2. Sort by Author Asceding. 
3. Find Miss Fernwood and EtiCarasoft's scenario (it should be the first one, the scenario has a valid author) and download it.
![image](https://user-images.githubusercontent.com/7532602/52761412-2d8dfe80-3078-11e9-859d-92e7486867c1.png)
4. Go Offline.
5. Sort by Author.
6. The scenario is seen as if it didn't have an author field filled in although it has.
![image](https://user-images.githubusercontent.com/7532602/52761473-67f79b80-3078-11e9-943c-ad328689355e.png)

### Valkyrie Version
valkyrie-windows-2.2.00b

**Comment by BenRQ** [comment]
Thanks for the all the details.
It's now fixed.

I've also limited max length so it fits the grey line.

**Comment by chrismaliszewski** [comment]
@BenRQ, it hasn't been fixed. The quest.authors_short part :).

![image](https://user-images.githubusercontent.com/7532602/53038926-bf679280-34e2-11e9-823f-019104035aba.png)

**Comment by BenRQ** [comment]
Yes indeed, don't know how I missed that :( 
It's fixed now.
