### ISSUE TITLE
Lack of max-length of inputs in Editor

### ISSUE THREAD

**Issue by chrismaliszewski** [NPBruce/valkyrie#1067]
Although it's said in the editor that a maximum length of a synopsis is 100 characters, there is no actual limit of the field. I consider this a bug. 

Additionally, other fields also should have a max number of characters set. Otherwise, it breaks SE layout:
![image](https://user-images.githubusercontent.com/7532602/52852492-a2972c00-317d-11e9-8e07-c2b9cedde0fb.png)

and looks bad in a splash screen (especially Authors)
![image](https://user-images.githubusercontent.com/7532602/52852514-b3e03880-317d-11e9-861a-a4246169b8a2.png)

The title should not ever be longer than 1 line so it doesn't cover potential expansions line. I think a list of languages should be moved next to expansions list as per example screenshot problem. The Synopsis should never cover Difficulty nor Duration.

**Comment by redwolf2** [comment]
T̠͟e͇͍͍̟x̯̝͔͞t̖̥̫͙͓̝̕ ͉͖i̘̦͇ṉ̩̤̫͔̹͜s͙̮͘e̫̰͓̱̥͙r̥̠̤͞ti͓͚o̭̬͓̟͢n̦̞̭̫̹̬ͅ ͕̞i͏̥͇̰s̢͕̣ ̪̹͙̫͉̲̤a̟l̦̟̦wá̗̫͕͎͙͍ý͓̤s̴ ͝a̶̮̱̟̫͙ ̯̩̦p̜̣r̗̤͉͝o̖͖̣̤̤̘̣̕b̹͓̞̬̲͕̺l̤͖̲̫e͎̟̤̹͝ͅm̀.̸̮̞̜̖ ͓͍̳̪̟̻͠Tḫ̶̣̤er̳̞̣̥̳e̥̖͎̖̻̼ ̨̻̜̤̻͎̰ͅi̻̖͍̮s͎̱̺̰͈͔̘ ̧̞͖̺̝͙̞͚n̶̩̺͓͎o̥̣̫̬ ̟̯e̜͕̯̮͇̦͡a̹̼̻͙̹s͍̩̞̯̻͖̫y̲̰̥͞ ҉̹͖̭̪͔w̪͘a̭y̧͚͈ ̙̤̥̯̯̹t͍̘̞̳͕̙o̜̹̲͔͡ ͝p͍̺̣̮͢re͎̼̪͉̭̳v͖̕eńt҉̝͈͓̩̪̮̙ ̜͉̜̞ͅa͔̻̠̼̣̻̭l̫̬̥̥͔l͙͇ ̝c̹͔̞̟͇i̩͎̗͇r̺̺̜̰͞c̝̗͎͘u͈͡m͓̻̫͇͔̜͞s̳̖͙ṭ͓̖̘̪͚̫͡a͖̹̪̮̟n̥̜͍̲̼̪̳͢c̺̱͖̪̳̘e̻̼̠̹͙͕s̠̳̼̹̭̻͢.͕̝͉̀ ͚
That said, we could just remove all text above 100 characters. 
And then add and ellipsis (…) at the end

**Comment by chrismaliszewski** [comment]
That should be fine :)

**Comment by BenRQ** [comment]
Yes we need to have something when text is too long.
Added the (...) after 100 characters.
