### ISSUE TITLE
Two tiles image quality lower then others.

### ISSUE THREAD

**Issue by antontimmermans** [NPBruce/valkyrie#1068]
### Description of Problem or Question
The images of the tiles:  'River bend' and 'Out house' from the call of the wild expansion are noticably less sharp then all other tiles. And both lack the grey border on the tile.

### Valkyrie Version
2.2.00b

### Attach Save, Quest or Scenario
Scenario:
Found in the scenario 'a little night music':

**Comment by scrubbless** [comment]
Those two were not in the official app, hence had to be prepackaged.

@Bruce intentional made these poor quality,     to avoid copy right issues

**Comment by chrismaliszewski** [comment]
If someone is interested, I recently read about this software https://topazlabs.com/downloads/ which by AI can enhance low-quality images. 30-day triaI version is free. 

I tried the image tiles and it couldn't make magic but the enhanced images still look a little bit better and sharper than the originals.

Originals:
https://drive.google.com/open?id=1QVNsxMUeL7uh_NrqeZJ3Eo9lpYxbdW7S
https://drive.google.com/open?id=1nJjajkVAJfI2NpYU57poTjbQvzO4j-ML
The enhancement results are published here:
(full resolution results 2016x1008)
https://drive.google.com/open?id=1a2eJLgHQuVQS9QMNP-0_c2A2RyaCv4Ir
https://drive.google.com/open?id=13hYqe3BBvBJoSP_hzJxtC2_9DgEZPGA4
(small resolution, 504x252)
https://drive.google.com/open?id=1nH2lyQuOK6bk7LwIRzyUMnfK1dTfBIsd
https://drive.google.com/open?id=1gTVwoy0yhcuw4KLop9Q6uiJGnxdNcxmH

**Comment by chrismaliszewski** [comment]
Off-topic. Here is a real-life example of this technology. There is a HUGE difference in the quality between the original image and the enhanced image!

Original JPG image (1739x1739, 270KB): 
https://drive.google.com/open?id=1wrkRNjruefBXk7Tvv0nesWVaoFyFjspa
Enhanced JPG (6956x6956, 15MB):
https://drive.google.com/open?id=1fO1M7lCcZRrv4pnd9JGEEiNTr60qPTcP
Enhanced JPG but sized reduced to the original JPG (1739x1739, 309KB):
https://drive.google.com/open?id=1_5DaDflsP7ci1McUtf_Kgh9Vs194yyc3

NOTE: I think I could improve the quality of the original image by some noise reduction, etc. but I wouldn't be able to get back as many details as appeared in the enhanced image!

**Comment by antontimmermans** [comment]
> Those two were not in the official app, hence had to be prepackaged.
> 
> @bruce intentional made these poor quality, to avoid copy right issues

ok.. if that is still the case then this ticket can be closed. Weird though that all other CotW tiles where of high quality and had the usual greay broder around them.

**Comment by scrubbless** [comment]
The other CoTW tiles are contained in the official app. The two you mentioned are not used in any official scenarios

**Comment by antontimmermans** [comment]
ok.. closing the issue

**Comment by redwolf2** [comment]
I also found that even some of the official ones have quality issues. Some wall textures for example differ slightly from the base package ones.
