### ISSUE TITLE
Item text does not fit in text box

### ISSUE THREAD

**Issue by antontimmermans** [NPBruce/valkyrie#1069]
### Description of Problem or Question
the name of the item 'circumstantial evidence' did not fit on/in the black box.

![circomev](https://user-images.githubusercontent.com/42072372/52905432-7db4be80-323a-11e9-87d9-18ba32fd9ca0.jpg)

### Valkyrie Version
2.2.00b
Windows 10 laptop connected to TV at 4k resolution, fullscreen display

### Attach Save, Quest or Scenario
Scenario:
found while playing "a little nightmusic"

**Comment by BenRQ** [comment]
Fixed
