### ISSUE TITLE
Descent icons not properly displayed

### ISSUE THREAD

**Issue by BenRQ** [NPBruce/valkyrie#1071]
I see that the font I have created for Descent expansions symbols is not working as expected.
It looks like symbol width is 0 and all characters are on top of each other.

Does someone know how to create font, and configure a proper width for each character ?

![image](https://user-images.githubusercontent.com/40794717/52919045-5b847480-32fe-11e9-934f-0ea515d9251b.png)

@redwolf2 we still need to add Lieutenant symbols, as discussed (I think it was on Discord).

**Comment by redwolf2** [comment]
I didn't ever tried it, but [FontForge](https://fontforge.github.io) might work.

**Comment by BenRQ** [comment]
OK I was able to fix this with FontForge, thanks for your suggestion @redwolf2 .
It took me a few hours to understand FontForge :)

The vertical alignment is not perfect and character size is a bit small but it's good enough for now.

![image](https://user-images.githubusercontent.com/40794717/52983844-34f13700-33ed-11e9-82cd-3eb3d8c8f588.png)

**Comment by redwolf2** [comment]
It's a crappy tool, but does the job.
