### ISSUE TITLE
Beta test 2.2.01b available

### ISSUE THREAD

**Issue by BenRQ** [NPBruce/valkyrie#1074]
Beta test release 2.2.01b is here :

https://github.com/NPBruce/valkyrie/releases/tag/prerelease%2F2.2%2Fv2.2.01b

Will it be the final version for 2.2 release ?
Thanks for all the tests and feedback !

**Comment by scrubbless** [comment]
As much as I love the HD tokens. Any chance we can get a  black or grey boarder around them (or a shadow under them). They bleed a bit too much into the background as it stands.

**Comment by BenRQ** [comment]
Can you please share a capture to illustrate the issue ?
I'm not sure what you mean by "bleeding into the background".

**Comment by scrubbless** [comment]
They don't stand out imo.

**Comment by BenRQ** [comment]
OK I see. This did not bother me to much, but I haven't played a full scenario yet with the new token.
Do you think this is a must have for 2.2?

**Comment by scrubbless** [comment]
No, enhancement is fine, I'll create an issue and we can get some more feed back

**Comment by redwolf2** [comment]
We could add the same Normal Map to all Token. https://www.youtube.com/watch?v=Up9zttIi_xg

**Comment by BenRQ** [comment]
Next step before release 2.2:
- Discuss and confirm fix of #1077
- Rebase development2.2 on master, and merge onto master (closing branch 2.2)
Hopefully nobody is working on this branch anymore.
- Releasing a test version on master 2.2.02b
- If everything is OK => this will be the official release :)

**Comment by BenRQ** [comment]
> Next step before release 2.2:
> 
>     * Discuss and confirm fix of #1077

Done

>     * Rebase development2.2 on master, and merge onto master (closing branch 2.2)
>       Hopefully nobody is working on this branch anymore.

Done

>     * Releasing a test version on master 2.2.02b

Will be done tomorrow.

In the meantime, I'm closing this issue.
