### ISSUE TITLE
Problems with deleting scenarios in SE

### ISSUE THREAD

**Issue by chrismaliszewski** [NPBruce/valkyrie#1077]
A major issue with deleting scenarios in SE. There are two scenarios that I created to reproduce the issue.

**Comment by chrismaliszewski** [comment]
An update shortly!!!

**Comment by chrismaliszewski** [comment]
The scenario of the problem:
1. Download any scenario. Turn off the app.
2. Go to %appdata%\Valkyrie\Download, copy the scenario file to %appdata%\Valkyrie\MoM\Editor and unzip it. 
3. Open the app. Go to Editor, modify the scenario's name to identify it easily. Go to Main Menu and New game. Below notice the downloaded '22.30h at the bird shop' scenario on the list.
![image](https://user-images.githubusercontent.com/7532602/53042132-74ea1400-34ea-11e9-807a-dd203d8b64f2.png)
4. Click Go offline. Notice two scenarios '22.30h at the bird shop' and '22.30h at the bird shop_local' on the list
![image](https://user-images.githubusercontent.com/7532602/53042206-99de8700-34ea-11e9-8a21-6d7d7b2e6cce.png)
5. Open local scenario and try deleting it. Notice the scenario neither of scenarios is deleted from the list. 6. Go Online. Notice that '22.30h at the bird shop' is deleted from the list here **but** it isn't deleted from disc
![image](https://user-images.githubusercontent.com/7532602/53042361-fd68b480-34ea-11e9-8ec7-a44042781693.png)

As I interpret what I see, there is something wrong with two things:
1. Creating a list of scenarios if you copy a scenario the app outside of the app.
2. Deleting a scenario that was created based on another scenario outside of the app.

**Comment by chrismaliszewski** [comment]
Another scenario which occasionally causes a black screen. Once I had it, other time literally nothing happened.
1. Open app, go to Editor, copy any scenario, open the clone and rename it for easier identification.
2. Go back to Main menu, New game, 'Go Offline', click Play on the local scenario.
3. Click Delete. Black screen.

**Comment by chrismaliszewski** [comment]
There are possibly two problems:
1. wrong way of creating a dictionary,
2. wrong way of deleting things from multiple dictionaries. 
In terms of the 'black screen' issue. It should be checked:
-when the exception happens, 
-how a scenario is deleted from the dictionary,
-if it's possible that two scenarios can be deleted from the dictionary by one operation of deleting a scenario while leaving data in another dictionary so a scenario exists in one list and doesn't in another.

**Comment by BenRQ** [comment]
OK thanks for all the details I will have a look.

**Comment by BenRQ** [comment]
OK I have a fix.
The editor scenario were not supported properly, and directories were not deleted.

The tests and error cases created some side effect on the management of quest list for .valkyrie files.

**Comment by BenRQ** [comment]
In the fix I made for this issue, I made it possible to delete the scenario being edited (the scenarios that are in the /editor directory).
I'm not sure this is such a good idea.

@scrubbless @redwolf2 what do you think ?

**Comment by redwolf2** [comment]
Maybe we could later add a safety dialog "Delete scenario? Yes/No" or add a dialog that says: "Scenarios created in the Editor can only be deleted from the Scenario Editor selection dialog".

**Comment by chrismaliszewski** [comment]
I think deleting scenarios, no matter of a kind, should be possible from a splash screen so there is no need going back to Editor menu. 

I like the first idea of with the dialog. It could be a simple thing:
1. I personally think the Delete button should stand out more and should be red. On the other hand, all Back buttons should be grey as the Delete is now. They don't do anything major/serious/dangerous to be red. But it's a topic for a different discussion.
![image](https://user-images.githubusercontent.com/7532602/53131229-0df35a80-35d1-11e9-99d2-bebdc9da839b.png)
2. Clicking the Delete button causes appearing of the two new buttons:
![image](https://user-images.githubusercontent.com/7532602/53131269-219ec100-35d1-11e9-947b-33207bc0a41d.png)
PSD: [delete_confirmation.zip](https://github.com/NPBruce/valkyrie/files/2886850/delete_confirmation.zip)
The design is plain and simple.

**Comment by BenRQ** [comment]
I agree we should add a confirmation
But for 2.2, we will just remove the delete button.

Let's avoid the big drama of someone losing weeks of work because he thought he was deleting something else.

**Comment by chrismaliszewski** [comment]
Sure. I created a new ticket for the enhancement.

**Comment by BenRQ** [comment]
Fix done.
To make it simple, I do not show the delete button for directories.
I only show it for .valkyrie files.

I will now close this ticket as you have created other tickets for the points we have discussed.
