### ISSUE TITLE
Beta test release 2.2.02b

### ISSUE THREAD

**Issue by BenRQ** [NPBruce/valkyrie#1084]
Beta test release 2.2.02b is here :

https://github.com/NPBruce/valkyrie/releases/tag/prerelease%2F2.2%2Fv2.2.02b

This version is directly coming from the master branch.
It means that if we don't find additional issues in this version, it will be just a change of version number to release it officially.

I recommend running some games and using it as your default version, now that we are so close to release.
Please tell us here if you have played a game with it, so we know how much it has been tested.

**Comment by chrismaliszewski** [comment]
Hi. I ran through 4 scenarios for the basic game in a similar way I'd play a normal game and there were no problems at all. Checked other stuff, no issues found. 👍
