### ISSUE TITLE
Allowing to download a scenario without required expansion

### ISSUE THREAD

**Issue by chrismaliszewski** [NPBruce/valkyrie#1085]
Fixing the issue https://github.com/NPBruce/valkyrie/issues/1065 disabled possibility to download scenarios to which a user doesn't have necessary expansions. Personally, I don't like the idea.

One thing is blocking possibility to play a scenario to which you don't have required expansions, another is blocking download option. 

Yesterday, I wanted to download all existing ~~expansions in case they are deleted in the future but~~ scenarios for the times I buy the necessary expansions to play them. To do that, I first needed to turn on all expansions which I don't have, download scenarios and then turn the expansions off again. It's a very bad resolution!

Could you change it? I presume it should be an easy fix in ifs statements. I presume right now you have something like (pseudo-code):
```
if(areExpansionsMissing()){
   displayStopButton(); <---
} else {
   if(isScenarioDownloaded()){
      displayPlayButton();
   } else {
      displayDownloadButton();
   }
}
```
and there should be an additional if statement in the above marked position:
```
if(areExpansionsMissing()){
   if(isScenarioDownloaded()){
      displayStopButton();
   } else {
      displayDownloadButton();
   }
} else {
   if(isScenarioDownloaded()){
      displayPlayButton();
   } else {
      displayDownloadButton();
   }
}
```

**Comment by BenRQ** [comment]
> Yesterday, I wanted to download all existing expansions in case they are deleted in the future but I buy the expansions to play them.

`Please discard your paranoia card at the end of the turn :)`

More seriously, I think this is not a problem the way it is.
I mean no offence but your use case sound very far stretched to me.

Or maybe I'm missing something here.

**Comment by chrismaliszewski** [comment]
No offence taken. It was just an example of 'why you may want to download everything'. I could've said, I want to have all the scenarios downloaded and would be good enough (as striked above). 

Other points are:
-in the previous version, 2.1.5, it was possible to download scenarios without expansions, so why changing that now? 
-a user sees he/she doesn't have necessary expansions. It should be a choise of a user to download a scenario or not even if he/she won't be able to play it.

**Comment by scrubbless** [comment]
I don't see a problem. If you can't play it why would you download it.

Only use case is if the player wanted to read the scenario description. But it's very corner case and not worth the time to work around.

**Comment by chrismaliszewski** [comment]
> But it's very corner case and not worth the time to work around.
A workaround should be fairly easy if the existing creation of buttons uses if statements as shown above. 

> Also having the ability to download a scenario that you can't play is surely going to be more confusing?
Following this way of thinking, we could say 'having scenarios you can't play shown on a list is a bit confusing' but that's why there is a filter allowing to hide scenarios like that. So if you display scenarios that a user can't play, allow them to download them and let them be unplayable.

**Comment by BenRQ** [comment]
It's not hard to change I confirm.

I just think the current version is good, downloading something that can't be used does not make sense to me.

**Comment by chrismaliszewski** [comment]
Sure. As I said, there is a workaround the problem which I used. 

Let's wait for another opinion.

**Comment by scrubbless** [comment]
A player should know there is content they can unlock if they select content.

But I don't see the need for downloading them. Chances are if they pre download them to play later the scenario will likely get an update and have to be downloaded again.

**Comment by antontimmermans** [comment]
How does FFG do it in the official app:
You can see the scenario title, an image and a teaser text. 
When you want to go one level deeper and select the scenario, you are reminded to get the message to buy (activate) the expansion first.
I am fine with this behavior as it mimics the behavior official app.

**Comment by chrismaliszewski** [comment]
Ok, point taken. The functionality can stay as it is right now then. 

@antontimmermans, I still have a question for you (and others too). I agree that imitating the official app would be a good idea to start with. Later on, it could be even updated to something better. 

Unfortunately... When you look at SE right now:
![image](https://user-images.githubusercontent.com/7532602/53475019-b4f55c00-3ad3-11e9-9e20-1d63a85bf59b.png)
Only one scenario has a teaser text visible. The rest has a scenario's description visible only on a splash-screen after you download a scenario and then click a Play button:
![image](https://user-images.githubusercontent.com/7532602/53475073-df471980-3ad3-11e9-8628-faa05b4e4a23.png)
I am aware that lack of description is related to scenarios not having been updated yet but they also may never be. 

A month ago I created issue https://github.com/NPBruce/valkyrie/issues/1020 which one part is related to creating a possibility to see a scenario's splash screen without a necessity to download a scenario in the first place. The conclusion for this part was: the current data format doesn't allow to do that as the data doesn't contain all information for a splash screen. 

So again, I agree that imitating the official app would be good but I can't agree that the Valkyrie app mimics the behaviour of the official app nor that it works like it at this very moment. To mimic the official app behaviour a user should be able to see **the whole** teaser text, not just part of it, and without the necessity to download a scenario, don't you agree? 
Could you answer here https://github.com/NPBruce/valkyrie/issues/1020 so there is no garbage created here?
