### ISSUE TITLE
Unclickable Investigator Eliminated

### ISSUE THREAD

**Issue by chrismaliszewski** [NPBruce/valkyrie#1089]
A small enhancement request for the future release, although I understand it may not be easy to do.

It'd be good to be able to unclick Investigator Eliminated in case someone clicks it instead of Set Fire. 

I presume clicking the button causes firing a specific event and that's why it's unclickable. Am I right?

**Comment by scrubbless** [comment]
I'd be interested to know how this works actually. Does clicking that button just set a variable, can we use events to "reset" that variable?

**Comment by BenRQ** [comment]
The app does the following :  
1) set #eliminated to 1
2) at the end of the round set #eliminatedprev to 1
3) at the end of the following round if #eliminatedprev  == 1, it triggers the event "Eliminated"

And yes I can make this button clickable again to cancel the action.

**Comment by scrubbless** [comment]
Thanks @BenRQ.

**Comment by chrismaliszewski** [comment]
It'd be good to be able to unclick the button, just in case. @BenRQ, can you set the label 'Your opinion wanted' here too?
