### ISSUE TITLE
2.2 - Darkness tokens showing as secret passage

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#1095]
### Description of Problem or Question

In 2.2 the Darkness tokens are showing as secret passages.

![screenshot_20190224-174838_valkyrie](https://user-images.githubusercontent.com/32058089/53302963-96396000-385c-11e9-9e67-ab128f45b137.jpg)

**Comment by redwolf2** [comment]
We will have to slip the sprite atlas for that too, I will priorize on that.

**Comment by BenRQ** [comment]
Windows works fine for me. (notice small glitch on Esther Locke)
![image](https://user-images.githubusercontent.com/40794717/53304424-487d2180-3875-11e9-8b2e-77eb7c5d0616.png)


Android has some issue with some tokens : 
(capture incoming)

**Comment by redwolf2** [comment]
I added a pull request that should work on both platforms. https://github.com/NPBruce/valkyrie/pull/1097

**Comment by BenRQ** [comment]
Fixed with PR #1097 Thanks @redwolf2
