### ISSUE TITLE
Bechman Token is wrong

### ISSUE THREAD

**Issue by redwolf2** [NPBruce/valkyrie#1100]
### Description of Problem or Question

Thanks @Brotim, for the tip on discord.

![unknown](https://user-images.githubusercontent.com/4141621/53363903-ecca9b00-393d-11e9-8325-e798451f4b6f.png)

### Valkyrie Version
2.2.04

### Pull Request

https://github.com/NPBruce/valkyrie/pull/1099

**Comment by BenRQ** [comment]
Merged in master
