### ISSUE TITLE
Can't install new Android version

### ISSUE THREAD

**Issue by newusergettingnuts** [NPBruce/valkyrie#1103]
### Description of Problem or Question
Apk shows a cant install. I have third party apk switched on. 

### Valkyrie Version

**Comment by BenRQ** [comment]
Hi @newusergettingnuts 

What previous version was installed ?
Did you try to uninstall previous version ?

**Comment by redwolf2** [comment]
Yes, you probably habe to delete the old version manually

**Comment by newusergettingnuts** [comment]
Fixed i deleted old version works fine thanks.

Close thread.
