### ISSUE TITLE
New Scenario - the Miskatonic Museum

### ISSUE THREAD

**Issue by GwanGwanish** [NPBruce/valkyrie#1104]

**Comment by scrubbless** [comment]
Added!

It has not appeared in the lists yet, but I believe it updated every hour now.
I have not yet added it to the stats sheet, ill get that added asap

**Comment by scrubbless** [comment]
I have added this to the stats, you'll be glad to hear you've already had a play. 8/10 rating
![image](https://user-images.githubusercontent.com/32058089/53702248-c785d300-3dfc-11e9-9d10-e290a157713f.png)

**Comment by GwanGwanish** [comment]
I’ll take what I can get. It may end up with a limited audience. Uses
Streets of Arkham assets. I wanted to put to use those nifty museum tiles.

**Comment by scrubbless** [comment]
Streets of Arkham is the most popular expansion, sold out in most places. I think you'll be surprised how many plays you may get.

I personally like making base only scenarios and layering over expansion content. That way I can get as much of the player base as possible but spice things up for people with the expansion.

For example in stress and strain I removed BtT as required and as a result had to add base variations of the Thrall monster. They were custom monsters to acted exactly the same, I just had to change up the sapwlwns to use deepobe hybrids for those without BtT. Players with BtT will get the correct thematic monster.

**Comment by GwanGwanish** [comment]
Yeah, I considered making the Streets of Arkham tiles optional by
programming the app to use them when players enabled the expansion. In the
end, I found myself too pressed for time to identify tiles that matched
thematically, program, etc. Common theme. Don't have the free time that I'd
like to work on these scenarios. First started creating this particular
scenario back in ... maybe last November? Ain't even particularly
complicated.
