### ISSUE TITLE
Synopsis bug: languages change not applied 

### ISSUE THREAD

**Issue by newusergettingnuts** [NPBruce/valkyrie#1106]
### Description of Problem or Question

Problem with multiple language scenarios and synopsis.  If i write a synopsis in a spanish scenario in spanish it also shows spanish in the synopsis line in other formats. If i write a synopsis in english it deletes the spanish..so i guess it seems its coded as the Author line to show the same in all languages selection.

**Comment by BenRQ** [comment]
The local quest list was not refreshed after going into options for changing languages.
It is now fixed.
