### ISSUE TITLE
Add stop button to audio menu entries

### ISSUE THREAD

**Issue by MrTantum** [NPBruce/valkyrie#1108]
### Description of Problem or Question
Testing sounds in editor is currently not really possible because there is no way to stop an audio sample after you have started it.

Would it be possible to show a stop button for audio files which have been started and make the file stop after clicking on it?

![grafik](https://user-images.githubusercontent.com/31658807/54072168-35a41d00-4277-11e9-9485-66e4a118fa66.png)

### Valkyrie Version
2.2

**Comment by BenRQ** [comment]
Seeing the number of likes, I will move this one to high priority on 2.4 :)
