### ISSUE TITLE
Edna Hughes name incorrect in Token

### ISSUE THREAD

**Issue by antontimmermans** [NPBruce/valkyrie#1109]
### Description of Problem or Question

![image](https://user-images.githubusercontent.com/42072372/54077635-66a64100-42bb-11e9-8d3a-8e400f578e26.png)

Her name is Edna Hughes, the token is missing a huge h.

### Valkyrie Version
2.2.04

**Comment by redwolf2** [comment]
Fixed: https://github.com/NPBruce/valkyrie/pull/1099

**Comment by BenRQ** [comment]
Merged in master
