### ISSUE TITLE
NEW: EndInvestigatorTurn Trigger

### ISSUE THREAD

**Issue by antontimmermans** [NPBruce/valkyrie#1110]
### Description of Problem or Question
The trigger **StartRound** gets activated at the start of the round. Investigators do their actions. When pressing End-turn Mythos happens, Monsters happen and then the **EndRound** trigger becomes active, and the the new round starts and StartRound is activated.
Sind EndRound (1) is immediately followed by StartRound(2) the triggers are actually the same from the view of the scenario writer.

What I miss most is a trigger that marks: **EndInvestigatorTurn**.
- for end round messages
- monster spawning that gets active right after mythos and before next round (suprise attacks)

I can also imagine an **EndMythos** but I will create a seperate ticket for that since I miss that one less but can imagine some nice uses for it :). (edit: see #1111)

### Valkyrie Version
2.2.04

**Comment by scrubbless** [comment]
While I agree with your point, there is a subtle use to these. If more than one event triggers from EndRound it will randomly pick one to run. Using EndRound then StartRound guarantees an order of those two events, though you could argue that using one EndRound triggered event with multiple events chaining from it is a more elegant way to guarantee event orders (and make them scalable past two events).

Alsobif EndRound triggers on #round ==2 then technically StartRound will trigger in #round == 3. So it would make it easier to keep track of what rounds you expect things to happen in.

I think the following triggers would be helpful -

* Trigger before mythos events/triggers
* Trigger before horror phase
* Trigger before monster activations

**Comment by scrubbless** [comment]
@npbruce brought up an interesting point on Discord and that EndRound is used for Descent.

**Comment by antontimmermans** [comment]
I know this may not be the most urgent ticket, but if it is not too much trouble, I really would LOVE to get a trigger on **EndInvestigatorTurn**.
In the next scenario, I am making, it would make the flow of events and user experience for the players, so much nicer.
Also in previous scenarios that I created, I could make some easy enhancements that will increase user experience.

**Comment by antontimmermans** [comment]
For completeness: the currently available events are:
![MOMphases](https://user-images.githubusercontent.com/42072372/99073585-790b6e80-25b6-11eb-9cce-55754fe79d89.png)

A scenario writer could use event trigger 'Mythos' to trigger their own event. If any of the `$mythosxxxx` variables are set to 1 to activate default mythos events, the order of handling both events is not guaranteed.
That means that for one player, the Mythos triggered event may come first, and after that, the default mythos event (set by  `$mythosxxxx`). For another player, these events can be triggered the other way around.

Therefore the request for the EndInvestigatorTurn trigger is still valid. That trigger should always come before the mythos trigger:
![MomPhaseRequest](https://user-images.githubusercontent.com/42072372/99074423-04393400-25b8-11eb-8497-adb89bfcf2d6.png)
