### ISSUE TITLE
NEW: EndMythosTrigger

### ISSUE THREAD

**Issue by antontimmermans** [NPBruce/valkyrie#1111]
### Description of Problem or Question
The trigger StartRound gets activated at the start of the round. Investigators do their actions. When pressing End-turn Mythos happens, Monsters happen and then the EndRound trigger becomes active, and the the new round starts and StartRound is activated.
Sind EndRound (1) is immediately followed by StartRound(2) the triggers are actually the same from the view of the scenario writer.

What I miss most is a trigger that marks: EndInvestigatorTurn. but that is described in #1110 

I can also imagine an EndMythos Trigger that gets activated after the mythos and before monster phase:
- For suprise spawing or disappearance of monsters
- for adding specific behavior or effects before monster phase begins (like stting fire or darkness for example)
I have to admit this might be difficult to implement and may influence the 'normal game flow'. Feel free to share your view if this trigger would be usful or not.

### Valkyrie Version
2.2.04

**Comment by scrubbless** [comment]
Agreed, also a similar one before horror would be handy. For the same/similar reasons.

Spawn in monsters like ghosts for horror only and remove for example.

**Comment by antontimmermans** [comment]
You just gave me an idea for my haunted mansion once this trigger comes available :) WOEHAHAHAHAHA

**Comment by scrubbless** [comment]
I'm glad I inspire!

**Comment by antontimmermans** [comment]
sorry.... pressed the wrong one
