### ISSUE TITLE
Trigger = DefeatCustomMonster during Horror Phase

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#1112]
### Description of Problem or Question
There is a strange error when defeating a custom monster (with custom horror/activation events) that has an event that triggers when it is defeated.

I've created a test scenario.

Run the event (place tile, spawn monster). Then end the turn, process the monsters custom activation then select a monster to do the "horror check".

![image](https://user-images.githubusercontent.com/32058089/54284350-b032ac80-4597-11e9-8c46-15d03aa72f5e.png)

In the custom Horror event - damage the monster until it is defeated:
![image](https://user-images.githubusercontent.com/32058089/54284460-df491e00-4597-11e9-8fd5-12639a0b487a.png)

When you click defeat the dialogue disappears, but the event does not run:
![image](https://user-images.githubusercontent.com/32058089/54284493-ed973a00-4597-11e9-92cc-420bd2a16454.png)

When you click "end phase" the event (and the monsters box) pops up.
![image](https://user-images.githubusercontent.com/32058089/54284544-115a8000-4598-11e9-8ef5-dd89c6b4a802.png)

If I set up the scenario with a standard monster it works as I would expect (event pops up during the Horror Phase and I can continue with horror events).

I assume its to do with the custom horror event.

### Valkyrie Version
2.2.004

### Attach Save, Quest or Scenario
[DefeatMonsterBug.zip](https://github.com/NPBruce/valkyrie/files/2961772/DefeatMonsterBug.zip)

**Comment by BenRQ** [comment]
Thanks for the test scenario.

I think I have a fix for this.
I've tested with one monster and multiple monster, and it works in both cases.
