### ISSUE TITLE
Android Test version 2.3.00b

### ISSUE THREAD

**Issue by BenRQ** [NPBruce/valkyrie#1113]
Hi,

I created a first test build with the current scope of 2.3, and a first crashlytics integration.

Crashlytics is a tool that will report crash logs when a crash happen.
It works only for Android ... unfortunately. (I found other crash report system cross platform but they were not for free).

So if you are an android user, please download and try to crash the app to see if it works as expected :)
You can also test the bug fixes and the Horrific journey integration while you are it.

Here is the link to the build: https://we.tl/t-J6LNh8uEuZ

Scope:
* Add crashlytics (with no default configuration)
* #1112  Trigger = DefeatCustomMonster during Horror Phase
* Update to Unity 2018.2.21f1
* Synopsis bug: languages change not applied #1106
* MoM - Monsters being set to Spirits when Physical (and visa versa) #1057
* #1101 Add french translation for HJ
* Trapdoor token + Bechman fix + Edna Hughes fix (#1099)
* Horrific Journeys integration (#1101)

Windows versions and other are coming soon (hopefully this week end).

**Comment by scrubbless** [comment]
I will test this today hopefully

**Comment by scrubbless** [comment]
One issue right off the bat!
![Screenshot_20190315-082512_Package installer](https://user-images.githubusercontent.com/32058089/54418157-fef95700-46fb-11e9-8ff0-2d79c51dfcab.jpg)

**Comment by BenRQ** [comment]
So you can call me as soon as you find a bug :)

I think you can deny it and it will still works.
I don't know why Crashlytics would require that though.

**Comment by scrubbless** [comment]
I did deny it and it did work, but might make people paranoid. Does crashlytics have an SMS feature? There has to be a way to turn off call app permissions.

Import took just under 3 minutes on my Galaxy S7 edge btw. So will a little slow but not the end of the world.

I would recommend putting a warning on the import screen along the lines of 'please keep you screen active during import". As the import can hang if you tab out or let your phone screen sleep.

**Comment by redwolf2** [comment]
READ_PHONE permissions are required to read device serials, that probably the reason Crashlytics needs them.

**Comment by BenRQ** [comment]
After a bit of digging, it's probably because Carshlytics does not set a minSDK.
https://issuetracker.unity3d.com/issues/android-read-phone-state-permission-is-added-in-the-androidmanifest-dot-xml-file-using-latest-26-dot-0-2-sdk

**Comment by scrubbless** [comment]
How are we getting along here? 

I've been testing my scenarios on the android version and all is good from what I can see (other than the phone permissions topic i raised).

Any bugs introduced that are being worked on or any progress with the crashlytics integration?

Just curious if we can push this to live, since it's a relatively small update.

**Comment by BenRQ** [comment]
I don't receive much information yet.
I made some changes already to be able to get the Valkyrie logs with the crash report.

I will now add some logs in most import actions, to know where the crash is happening more or less.

Nothing really blocking an official version release though so I fix we can go live as soon as I'm done with this.
Maybe we should just take one day or two to test the windows version too.

**Comment by BenRQ** [comment]
We also have #1102 where I've done no change yet.

**Comment by scrubbless** [comment]
No worries @BenRQ appreciate you working on it! I'm just getting over excited about incorporating some of the HJ tiles into my scenarios.

**Comment by BenRQ** [comment]
Problem with Android permissions for phone calls is now fixed, it was related to SDK version not set for Crashlytics.

**Comment by BenRQ** [comment]
I will close this issue as I have enough information to prepare next version.
