### ISSUE TITLE
Some timings in the ratings are wrong

### ISSUE THREAD

**Issue by NicolaZee** [NPBruce/valkyrie#1114]
For 'In the Dark' there are a couple of ratings where the timings are clearly too long - over 15 hours.
This is putting off some people from playing the scenario because they believe it will take 6 hours to complete.

**Comment by BenRQ** [comment]
There was two very long playback : 
916 minutes 
1688 minutes 

In both cases it's probably someone leaving the game running for half a day/a full day before returning to it.

I changed both time duration to 300 minutes so it does not break the average time.

**Comment by BenRQ** [comment]
It will take one hour to update.

**Comment by NicolaZee** [comment]
Thanks for this.
It was getting some people worried.

**Comment by BenRQ** [comment]
Yes the game duration is indeed an important factor for scenario selection.
