### ISSUE TITLE
Missing Person Tokens

### ISSUE THREAD

**Issue by FASTNAVi** [NPBruce/valkyrie#1116]
Hi all,

I just today installed and tried new Valkyrie. I have some issue with Person tokens in my scenario Believe or Die. All person tokens with name have only a name on it, instead of picture. The rest seems to me ok.

Thank you for your answers.

**Comment by scrubbless** [comment]
This is intentional, @redwolf is creating his own personal token images so we can have static (non changing) sprite maps in the future.

It doesn't import those tokens anymore.

Once they are all complete they'll be added

**Comment by FASTNAVi** [comment]
Ok, thank you for your answer.
