### ISSUE TITLE
Intro Screen only shows 4 investigators

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#1118]
### Description of Problem or Question
This is extremely minor, but the Investigator Start screen only shows 4 investigators max.

A Stress and Strain supports 6 players (which is when I noticed this), so I am not sure if this is whats causing the issue:
![image](https://user-images.githubusercontent.com/32058089/54677759-7b74a700-4afb-11e9-91a1-d92a2a98cd6e.png)

### Valkyrie Version
2.2.04

**Comment by BenRQ** [comment]
Not reproduced on 2.4.10a.

![image](https://user-images.githubusercontent.com/40794717/94344610-d9534a80-0020-11eb-9893-c8695dd1cd9e.png)

**Comment by mayjak** [comment]
I also can't reproduce this on 2.4.10 on Windows.
Also tried:
- leaving an empty spot between investigators during character selection (ex. select 6, deselect 1 in the middle)
- loading a saved game with 6 investigators.
- french version

Always worked properly for me.
![image](https://user-images.githubusercontent.com/10874335/97080074-164b3680-15f9-11eb-8979-1d1a93c49300.png)

**Comment by scrubbless** [comment]
I think this was fixed by @BenRQ or @Quantumrunner 

Might have been missed in the rollup.

**Comment by scrubbless** [comment]
If not close off 😊
