### ISSUE TITLE
Asking for condition Mesmerized but this is not a base game condition

### ISSUE THREAD

**Issue by antontimmermans** [NPBruce/valkyrie#1119]
### Description of Problem or Question
Issue reported by @powerjeremy in repository of 'Disturbance at the Docks'

> After the starspawn arrived i was asked to do an influence check at one point. If i failed i was to become Mesmerized. I think this is a condition from Beyond the Threshold expansion but this expansion isnt listed as a requirement. I had only selected the base game in the COLLECTION section of the valkyrie app.

### Valkyrie Version
2.2.3

### Attach Save, Quest or Scenario
Found while playing:
https://github.com/antontimmermans/MOMDATD/issues/17

**Comment by BenRQ** [comment]
I got a similar issue with spell being found, even though I don't have the expansion.


Definition of spell was like this:

[QItemAtticSpell]
starting=False
traits=spell
inspect=EventAtticSearchTokenSearched

**Comment by redwolf2** [comment]
This issue seems to be a bug in the official app.

> > We were playing the first core scenario today and a Star Spawn effect instructed us to use a Mesmerized condition, even though I didn't have BTT in my collection. So we can conclude that some BTT stuff has a chance to be included in other scenarios, but also that the collections are a little buggy!
> 
> Hah! We had that happen as well! The DLC map I got played a little buggily. It told me to take Mesmerized (we just did Dazed instead), had a little bug where an explore token wouldn't go away (we revealed the next tile, it just didn't go even when we clicked on it and said to explore), and at one point instead of the usual preform ritual text box popping up we got some text along the lines of "INPUT_ERROR_SOMETHING" (it still let us preform the ritual luckily) 

https://boardgamegeek.com/article/24783981#24783981
