### ISSUE TITLE
Discussion: Investigator Eliminated and Auto Save events firing order

### ISSUE THREAD

**Issue by chrismaliszewski** [NPBruce/valkyrie#1121]
I have a question regarding the general "problem". While testing a new scenario I clicked Investigator Eliminated and continue playing until the scenario resolves the elimination event (') and finishes the game. After that, I wanted to test one more thing with the scenario so I tried to load the Auto Save but... instead of loading the game in the last Investigator Phase before the game ends, as I expected, the game the started right before firing the (') event causing display of the 'The End' screen right after I started it. It can be tested for example with Chapeldown Manor, A Glimpse of the Past or any other scenario with 'Investigator Eliminated' event.

From what I know, the Auto Save is created right at the beginning of a new Investigator Phase. And from what I can see, the event which displays 'The End' screen fires right after the Auto Save. It causes the above-described problem disabling a possibility to play the last turn right before the end differently and maybe also blocks other possibilities. 

**My question is, should Auto Save and firing the 'The End' event be done in that order?** Or maybe it'd a good idea to swap the order? But I'm not sure what kind of issues it might create. This change of order should prevent firing the Auto Save resolving the above problem.

**Comment by scrubbless** [comment]
The auto save couple be a startround trigger. Effectively giving the same behaviour as endround.

**Comment by antontimmermans** [comment]
I am not sure what the relation is between **EventStart** and **StartRound**. 
in **EventStart** the manor and story are chosen.
in **StartRound** all round related events are triggered.

If they are virtually the same then a scenario like Chapeldown Manor might have the strange effect that if you quit directly after start up (auto save in StartRound 1).  Then reload and go through that initialization again, you might end up in a different manor then you originally started with.

If the handling and timing of those two events is not the same then there will likely be no issue and it would make more sense to do auto save at the begin of the StartRound. Side effect is that this is basically an 'undo' option on the game, for when someone just miss-clicked something that has dramatic effects (and also allows for cheating :): select 'yes'... uh oh.. don't like the result, reload.. select 'No'). 

I personally think that the undo option will be appreciated, and i don't mind the misuse possibility that much.

**Comment by scrubbless** [comment]
I see your point, but its very niche. Have you tested this situation?

**Comment by scrubbless** [comment]
Yeh thats a good point, a little niche. Would be interested to see when EventStart sits in the turn order:

Does Event Start replace Start round, or is it tacked on before the turn order so start turn runs, etc.

**Comment by BenRQ** [comment]
The save game is done after start round
```
        game.quest.eManager.EventTriggerType("StartRound");
        SaveManager.Save(0);
```

At the end of start round, we check if the game is ended and we save the current status.

@chrismaliszewski isn't your issue just a test case?
I agree it's not convenient for your test case, but I don't think it's really a problem, the behavior makes sense (to me).

@scrubbless savegame is just after start round event, so it's the same as being in the startround.

@antontimmermans Savegame is not done on first round, but only at the beginning of the next round so you should be fine.

**Comment by chrismaliszewski** [comment]
@BenRQ, I'm not sure what you mean by "test case". 

The scenario I'm talking about is as follows: imagine you're playing a scenario; during the play, the game ends; it doesn't matter why: an investigator's death, (un)successful the end of the scenario etc.; you decide that you want to do something else and change the outcome of the last turn so you load Auto Save; unfortunately, you can't as the app immediately after you load the game displays the 'The end' screen. 

Scenario to replicate "the issue":
1. Start 'A Glimpse of the Past' scenario.
2. Set 'Investigator Eliminated'. 
3. Continue changing Phases until you see the 'The End' screen. 
4. In the Main Menu click Continue and load the Auto Save. 
(it's the shortest way to replicate what I saw in the above-mentioned situation without the necessity to play the whole scenario)

I have a few questions. 
1. I agree with the behaviour you described, it makes sense in general. Unfortunately, it's unclear to me why you check if a game is ended since you save the game no matter if it ends or not in the following turn. Shouldn't you prevent saving if the game ends in the following turn? 
2. Could you say, where the 'game is ended' check is performed? In the StartRound trigger or in the Save method? 
3. What does it mean 'a game is ended' since the game is not ended yet but it'll be in the following turn? Do you predict the end of the game in the next turn using triggers/counters/another method? 

You could give me a link to the piece of code so I'll check the logic myself so you don't spend much time explaining things :).

**Comment by BenRQ** [comment]
Test case means : it's just a case that is not a real life scenario.
I understand you want to do it, but it's a corner case.
I mean the game is not made to allow you to change your last action, through savegame.

> 1) I agree with the behaviour you described, it makes sense in general. Unfortunately, it's unclear to me why you check if a game is ended since you save the game no matter if it ends or not in the following turn. Shouldn't you prevent saving if the game ends in the following turn?
>  Could you say, where the 'game is ended' check is performed? In the StartRound trigger or in the Save method?

The two things are done in different part of code.

` SaveManager.Save(0); `
It is done in the roundControllerMoM.cs once it knows it's a new round, and has triggered the new round event.

`        if (game.quest.vars.GetValue("$end") != 0) 
Ìt is done in the eventManager.cs, for each event end.

Supporting all such corner-case in these parts of code is a path where I would like not to go :)
This is the kind of change that would add unnecessary complexity to the code.

>  What does it mean 'a game is ended' since the game is not ended yet but it'll be in the following turn? Do you predict the end of the game in the next turn using triggers/counters/another method?

The game is ended when $end is set to 1.
Investigator Eliminated set $end to 1 after 1 turn.

**Comment by chrismaliszewski** [comment]
After following the code, the test scenario runs as follows:
1. Trigger StartRound,
2. Save the game,
3. Trigger the event ending the game.

I made a little thinking; switching 1. and 3. may create more mess than benefits. It won't be easy to do what I'd like in this thread. I also agree with you that it's mostly a corner-case which won't be a problem of more than a few - dozen people. 

I'm closing the discussion; there is nothing that can be easily done and it isn't worth the effort. 
Thanks, guys.
