### ISSUE TITLE
Pre-release 2.3.02b

### ISSUE THREAD

**Issue by BenRQ** [NPBruce/valkyrie#1124]
A new version available for tests : 
https://github.com/NPBruce/valkyrie/releases/tag/prerelease%2F2.3%2Fv2.3.02b

This versions provides additional logs with Crashlytics report.
Details on the link.

If no major issue has been found after this week end, we are good to release the 2.3 version.

**Comment by scrubbless** [comment]
Looks good from an initial test play or a scenario.

**Comment by BenRQ** [comment]
Closing.
Release 2.3.03 is now officially available.

**Comment by scrubbless** [comment]
I noticed itnpopnup last night, cheers benrq! I'll announce it on BBG and FFG when I get into the office.
