### ISSUE TITLE
New scenario

### ISSUE THREAD

**Issue by Gruszkomir** [NPBruce/valkyrie#1127]
New scenario. Only in polish for now. 

https://github.com/Gruszkomir/Scenariusze/tree/master/miastowemgleII

**Comment by scrubbless** [comment]
Hi @gruszkomir I have added this, I'll add it to the stats sheet later today.

**Comment by BenRQ** [comment]
@scrubbless you forgot the external=

[MiastoweMgle]
external=https://raw.githubusercontent.com/Gruszkomir/Scenariusze/master/MiastoweMgle/

[miastowemgleII]
https://raw.githubusercontent.com/Gruszkomir/Scenariusze/master/miastowemgleII/

**Comment by BenRQ** [comment]
My script is sending me warning :)

**Comment by scrubbless** [comment]
Fixed, sorry added this on my phone and it's a pain!
