### ISSUE TITLE
Content Language

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#1134]
### Description of Problem or Question
We've had an I interesting issue raised on the BGG forums.

A polish player owns the English base game. When he plays he struggles to match the Polish names of the content in app to the English titles he owns, because the tile orders and names are in English.

It's made me think if there is an elegant way to address this.

Would it be possible to have a language 'override' on each of the expansions in content (and add one for the base game).

Here's my example.

An English speaking gamer owns MoM base, however he invites hit friends over, one if which owns BtT in French. They decide to play in English, but all of the content for BtT is listed in the app as English, therefore the tile names need to be translated by the players as they play.

Having an option would mean that players could override the default to leave MoM base as English but set BtT to French.  It wouldn't happen to your average person as it's a specific setting they would have to set when  adding or changing content.

I realise this is a corner case example, but it doesn't sound beyond the realms of possibility to me :)

What do you all think?

**Comment by EwenDC** [comment]
I don't know the code so don't shoot me if this isn't the case, but... If the scenario creator uses {c:} references for all of the tile, card, and monster names, shouldn't it be simple to just do those FFG name lookups on a different language to the current one?

You could have one language option for the scenario itself and another for the components.

**Comment by scrubbless** [comment]
Thatz the theory yeh :)

**Comment by chrismaliszewski** [comment]
I think the situation may not be that uncommon. I have the same "problem": I'm a Pole but I bought the English version of the MoM game so I can play with the English language people as I live abroad.

Although I also don't know the code standing behind the app, it's doable. It should require a few things: 
1. hash-table/array/object/dictionary (some structure) containing tiles' names for each language (as @EwenDC suggested); I presume it already exists but it may requires some changes in the structure,
2. changes in Select Content's design for language selection purposes,
3. create combo-box for language selection for each scenario,
4. create a machanism to display the correct tile's name.

Regarding 2. and 3., my proposition: 
![image](https://user-images.githubusercontent.com/7532602/55341210-87227f00-54a6-11e9-88cb-925ed7f507c8.png)
PSD: [language_selection.zip](https://github.com/NPBruce/valkyrie/files/3030277/language_selection.zip)
Personally, I think each line should have the same design and placement, therefore I spreaded and streached each line as well as aligned the text to the left and combo boxes to the right. I needed to shorten MoM's 1st Edition expansions' names. 
As for the design, there are two problems related to the combo-box: 
1. I don't know whether in Unity the combo-box is displayed within the scrollable area only or it can be displayed outside of its bounds,
2. the combo-box is too big; the letters and margins should be smaller but I took the list from the Options ' list.

**Comment by chrismaliszewski** [comment]
Although I also don't know the code standing behind the app, it's doable. It should require a few things: 
1. hash-table/array/object/dictionary (some structure) containing tiles' names for each language (as @EwenDC suggested); I presume it already exists but it may requires some changes in the structure,
2. changes in Select Content's design for language selection purposes,
3. create combo-box for language selection for each scenario,
4. create a machanism to display the correct tile's name.

Regarding 2. and 3., my proposition: 
![image](https://user-images.githubusercontent.com/7532602/55341210-87227f00-54a6-11e9-88cb-925ed7f507c8.png)
PSD: [language_selection.zip](https://github.com/NPBruce/valkyrie/files/3030277/language_selection.zip)
Personally, I think each line should have the same design and placement, therefore I spreaded and streached each line as well as aligned the text to the left and combo boxes to the right. I needed to shorten MoM's 1st Edition expansions' names. 
As for the design, there are two problems related to the combo-box: 
1. I don't know whether in Unity the combo-box is displayed within the scrollable area only or it can be displayed outside of its bounds,
2. the combo-box is too big; the letters and margins should be smaller but I took the list from the Options ' list.

**Comment by mayjak** [comment]
I think the easiest thing to add this feature would be:

I would add a "Default" option, which will always simply use the currently used app language.

INI file format:

[MoMPacks]
BtT      # <- "default" language
HJ,English
SoT,Protugese


UI:
Instead of the ComboBox I would reuse this selection list from the editor:
![image](https://user-images.githubusercontent.com/10874335/98816654-47b16800-2429-11eb-9b02-d403bc9cfd6f.png)

It should automatically adjust to all screens, scroll properly etc.

**Comment by Quantumrunner** [comment]
The logic itself sounds fine to me.

But where would you place the button to select the default in the interface? Maybe to the right of the remove button (-)?

![grafik](https://user-images.githubusercontent.com/58113888/98848470-113c1300-2452-11eb-8e7f-151c2ce18f9e.png)

**Comment by mayjak** [comment]
Default would simply be one of the options in the select list.

It's not the editor menu you showed, but the one mentioned by Chris in the Expansion Content menu section:
![image](https://user-images.githubusercontent.com/10874335/98857036-c5dc3180-245e-11eb-9d23-eefe9839f3c8.png)

**Comment by Quantumrunner** [comment]
Ah ok makes sense. I was confused and thought the mission creator was the one who chooses the default.
