### ISSUE TITLE
Installing valkyrie Ubuntu

### ISSUE THREAD

**Issue by LenzoM** [NPBruce/valkyrie#1136]
How is it possible to install Valkyrie on Linux if neither of the two games it was based to (descent and MoMadness) they are not possible to install on Linux?

Thank you!

**Comment by NPBruce** [comment]
Please see the Linux information here:
https://github.com/NPBruce/valkyrie/wiki#linux

You will either need to import on another platform, or get the game data from another platform.

Does this answer your question?

**Comment by LenzoM** [comment]
Okay, so, As I can see I need to get the files from windows: https://github.com/NPBruce/valkyrie/issues/584

But which kind of files? all what I can get from c:\Program Files\Steam\ ?

**Comment by LenzoM** [comment]
Finally I got the

**Comment by LenzoM** [comment]
I extracted the files as it is said in the #584 and still valkyrie says to me that there is unaviable to find where it is collected... I don't know what else I can do...

**Comment by redwolf2** [comment]
Have you tried to import them from command line via the `-import` command?

**Comment by redwolf2** [comment]
I will close this for now. Feel free to commentwith further details and we will reopen it.
