### ISSUE TITLE
portuguese translation: il manuffato conteso

### ISSUE THREAD

**Issue by andrex47** [NPBruce/valkyrie#1138]
Ciao!
I will begin translating this scenario, as usual here is the link for the Google Drive shared folder i will be working on:
https://drive.google.com/drive/folders/1rulIS5wvnRp8lk8AeE07bG1LJsDlmlrM?usp=sharing
any help will be appreciated

**Comment by scrubbless** [comment]
Great thanks @andrex47 

I have permissions into that Repo so i'll take a look at adding the translation.

**Comment by andrex47** [comment]
@scrubbless 
[Localization.Portuguese.txt](https://github.com/NPBruce/valkyrie/files/8508172/Localization.Portuguese.txt)
After two years it was done in 2 days, my bad. Here it is

**Comment by scrubbless** [comment]
Awesome, thanks! Sorry I have only just seen this because @vidimus mentioned. I will get this added.

**Comment by scrubbless** [comment]
It shoud be live now

**Comment by vidimus** [comment]
> It shoud be live now

Hello, @scrubbless
There's a problem with the files and the update is not working. I see the files duplicated with a slightly change on names.

**Comment by vidimus** [comment]
![Screenshot_2022-09-18-14-44-10-38](https://user-images.githubusercontent.com/41538948/190902733-38e53463-9b4c-4e95-8c6d-e0d52d67f8be.jpg)

**Comment by vidimus** [comment]
@scrubbless or @antontimmermans , could you close this issue? It was solved.
