### ISSUE TITLE
Discussion: loading a game if you don't have an expansion turn on anymore

### ISSUE THREAD

**Issue by chrismaliszewski** [NPBruce/valkyrie#1140]
I'd like to discuss something. 

It is impossible to start a scenario if you don't have a required expansion. From what I see and understand, it's mostly to prevent the app crashing. But... it's possible to load a game if you don't have an expansion turned on anymore. 

Scenario: 
1. turn on some expansion needed by a certain scenario (i.e. A Little Night Music as it only has from the 1st edition so it's quick to test),
2. start playing the scenario and save the game,
3. go back to the Main menu and turn of the expansion,
4. load the game.

At least for me, the scenario that I was playing didn't crash after loading although I didn't have the expansion turn on. 

Two questions:
1. Why starting a scenario without a required expansion causes the app's crash but loading a game doesn't?
2. If starting a game w/o required expansion is blocked, shouldn't loading a scenario also be blocked in the situation of such? Or in other words, why block starting a scenario if you don't have required expansion if you allow loading it?

**Comment by scrubbless** [comment]
The Expansion content is contained with a file, the files are loaded into the game when it is started.

The tiles for BtT as an example are added in its own file, if the game calls a file path for that content and the file doesn't exist the scenario crashes.

So for example, if you create a test scenario and don't tick on required expansions then someone plays with but does not select BtT the game will run completely fine until it calls content from that expansion.

This works exactly the same for UI elements, if you create a UI element to display an image, then you later delete that image the game will crash when it attempts to load that UI element (aka the invalid path).

> Two questions:
> 
> Why starting a scenario without a required expansion causes the app's crash but loading a game doesn't?

No idea, it probably doesn't have a checksum to see if content is enabled at the load time. But I suspect when the scenario attempts to add a tile from an expansion thats not selected the game will crash at that point.

> If starting a game w/o required expansion is blocked, shouldn't loading a scenario also be blocked in the situation of such? Or in other words, why block starting a scenario if you don't have required expansion if you allow loading it?

It was probably just not a situation that was planned for and so uncommon that noone raised it as an issue to be fixed at some point (but by no means urgently).

**Comment by NPBruce** [comment]
Save games will always restore previously selected content. You can't change which expansions are in use half way through a scenario for many reasons. Note however that the selected content will update when you move to another scenario (ie: you can add an expansion between scenarios in a campaign).

**Comment by chrismaliszewski** [comment]
> > @chrismaliszewski: Two questions:
> > Why starting a scenario without a required expansion causes the app's crash but loading a game doesn't?
> 
> @scrubbless: No idea, it probably doesn't have a checksum to see if content is enabled at the load time. But I suspect when the scenario attempts to add a tile from an expansion thats not selected the game will crash at that point.
> 

> @NPBruce: Save games will always restore previously selected content. You can't change which expansions are in use half way through a scenario for many reasons. Note however that the selected content will update when you move to another scenario (ie: you can add an expansion between scenarios in a campaign).

That explains a lot. I was worried that there might be something wrong/unplanned. So if it was a conscious decision, everything is fine! Thanks, guys! :) Closing the discussion.
