### ISSUE TITLE
A Glimpse of the Past. Rus translation

### ISSUE THREAD

**Issue by Ssid113** [NPBruce/valkyrie#1141]
Good day!

Now I am completing the translation of the scenario A Glimpse of the Past. It remains to check the errors. Tell me where to put the translation in order to add it to the application?

**Comment by Ssid113** [comment]
@slycozzolino , @scrubbless thanks you.
In addition to the translation itself, there are also pictures with the translation. Folder "Russian" add to the root of the scenario. I also plan to add voice acting in Russian. But it is not so fast.
You can specify my nickname if you want. I did not add my name in the translation.
<details> 
  <summary>Scenario spoiler. This spoiler for the author</summary>
   I had to adapt a riddle "Please Return to Buy my Goods". In Russian translation, it sounds now "Artifacts and Rare Souvenirs from Innsmouth" -> "Артефакты и Редкие Сувениры из Иннсмута" and gem have names and not color. Red -> Ruby etc. The combination is saved for rus version and you don’t need to change it.
</details>

If you suddenly have questions about translation feel free to write ssid113@protonmail.com
The entire translation is stored here: https://docs.google.com/spreadsheets/d/1jJ85V1EzHHktlMmd0EuEYL-qlztVVOQ-5Vkw2LYJeU0

[Russian.zip](https://github.com/NPBruce/valkyrie/files/3060881/Russian.zip)

**Comment by slycozzolino** [comment]
@Ssid113 I can add in the translation file but any images and audio won't work unless an option to use the language as variable. 
@scrubbless Do you know if this option exists or has been requested. If not I believe we need an enhancement request to pass through the language selected in the main menu as a variable.

**Comment by slycozzolino** [comment]
@Ssid113 I can add in the translation file but any images and audio won't work unless there is an option to use the language as variable.
@scrubbless Do you know if this option exists or has been requested. If not I believe we need an enhancement request to pass through the language selected in the main menu as a variable.

**Comment by scrubbless** [comment]
Hi @slycozzolino

The feature to added language specific ui and audio was added in 2.2 (I believe).
 
I added an explanation in the tutorial page 63.

**Comment by slycozzolino** [comment]
I have made the updates and pushed commit 0255958 but its not updating in the scenario menu. Has the process changed?

**Comment by slycozzolino** [comment]
I made updates and pushed my commits but they do not show up in the main menu. Has the process changed?
https://github.com/slycozzolino/valkyrie-store/commit/02559584629de7a36da441d8bca28300f681e8a0

**Comment by slycozzolino** [comment]
Actually I believe the update worked but i do not see the Russian flag symbol. Is this not set automatically based on the localization file?

**Comment by slycozzolino** [comment]
Showing up now
I think it just needed time to refresh. @Ssid113 Please update and test if you don't mind. Once you have your audio ready let me know and i will add it as well.

**Comment by scrubbless** [comment]
The scenario interface updates every hour. If you are prompted to update the scenario it will be your new commit.

**Comment by scrubbless** [comment]
On the quest screen, there are two boxes "synopsis" (100 characters) and author. These two boxes will add more detail to the scenario selection screen.

It's worth filling them in as the author field helps players sort scenarios that you have made.

**Comment by slycozzolino** [comment]
Cool
Updated and pushed
The new selection screen really looks good.

**Comment by redwolf2** [comment]
Ok, then i will close. Discussion can contine or create a new issue for it ;).
