### ISSUE TITLE
Updated polish translation for the editor

### ISSUE THREAD

**Issue by zcaalock** [NPBruce/valkyrie#1142]
i`ve changed the words: snap and free, because it was badly translated and since i spend lot of time in the editor i couldn't stand it anymore. Changed some other words so it makes more sense now.

One of the buttons is too small

the file is here:
[Localization.Polish.txt](https://github.com/NPBruce/valkyrie/files/3063553/Localization.Polish.txt)

![editor](https://user-images.githubusercontent.com/24411061/55875884-78b72000-5b96-11e9-9884-a9ebb64a1ea7.png)

**Comment by redwolf2** [comment]
https://github.com/NPBruce/valkyrie/pull/1155

Merged
