### ISSUE TITLE
Unable to add some monsters

### ISSUE THREAD

**Issue by Bakajao** [NPBruce/valkyrie#1145]
### Description of Problem or Question
Hi all! First, sorry for my poor english. I have a strange issue when I'm editing any quest. I noticed that when I look for the list of monsters to add to spawn, some of them are not available.
In fact, I can´t use monsters corresponding to most expansions of heroes and monsters. Of course, that boxes are added to my collection and the list of required expansions of the quest.ini file, but despite this, I am unable to add them to any scenario. I suspect that they will not be used by random groups either.
On the other hand, I can select the heroes of those expansions to play.
I don´t know what happens.
Thanks for your time and help.

**Comment by scrubbless** [comment]
I'd you don't select the required expansion from the quest screen,   it will cross or the menus.

There is an X next ro each of the expansion menus click that to open up that content. Remember to use variables to block that content from running if you have not selected it as required but want it available for players that own it. 

Alternatively  you can make an expansion  mandatory by clicking the green + on the quest screen and selecting the expansion,  but that will limit the number of players able to play it. 
Doing this will unlock those expansion menus automatically

**Comment by Bakajao** [comment]
Well..If I click in the X next to each of the expansion menus to open up that content, some expansions turns from red cross to white not cross and i can use the content, but others turns from red cross to red without cross line (I can´t get it turns white)

I´ll show you with two images.

![Captura de pantalla (1)](https://user-images.githubusercontent.com/40961911/56158822-718f7800-5fc3-11e9-80d9-4461d3f4d959.png)
Here the two expansions boxes to test.

![Captura de pantalla (3)](https://user-images.githubusercontent.com/40961911/56158857-8704a200-5fc3-11e9-9288-8a41efab87a9.png)
Here one of them is avalaible, but the other always is in red. Can´t use it anymore. If I click the X only remove o put the cross line but still in red.

And always are the same expansion boxes. I tryed to reinstall Valkyrie and reimport RtL files but not fix this issue at all.

**Comment by scrubbless** [comment]
@DelphiDie is this something you can help with. I am not familiar with descent spawns.

**Comment by DelphiDie** [comment]
I'm not exactly sure I can help with this, but I have had inconsistent results when using the graphical editor in the past myself. It's one of the reasons I prefer to edit the quests as text files.

@Bakajao As a workaround I'd suggest you try to edit your spawn events as text files and add the monster types you want to spawn manually.

**Comment by Bakajao** [comment]
Ok...that's what I was doing...I edit text files manually because sometimes is faster.

Thanks for the help...you can close this thread if it seems good.
