### ISSUE TITLE
Button Colours - Bug

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#1146]
### Description of Problem or Question
There is a bug with Button colours, 

If you set the first button to white (or leave it white) then set any other button colours to another colour, it shifts them up one. 

![image](https://user-images.githubusercontent.com/32058089/56294638-4885f900-6123-11e9-90be-5a31d40017b5.png)

Save and Test
![image](https://user-images.githubusercontent.com/32058089/56294582-32783880-6123-11e9-83ab-2ac5e3e1d4f5.png)

When I go back into the editor it shows them differently
![image](https://user-images.githubusercontent.com/32058089/56294789-897e0d80-6123-11e9-8dcd-1b832fafc8fe.png)

I suspect this is happening because adding a colour adds a line of code, but an absence of code is defaulted to white.

I can get around this bug by setting the first button to "silver" but it may be worth fixing none the less:
![image](https://user-images.githubusercontent.com/32058089/56294880-bb8f6f80-6123-11e9-8421-bb113d8eccc6.png)

(Yes I am writing a scenario with difficulty scaling, I will probably present this to players as a UI element though, rather than buttons :D, I really hope it works!)

**Comment by NPBruce** [comment]
Fixed for 2.4
