### ISSUE TITLE
New Scenario in Spanish: La llamada de Innsmouth

### ISSUE THREAD

**Issue by ZombieJuanma** [NPBruce/valkyrie#1147]
### Description of Problem or Question
Hi, Im new and I do not know if I'm doing it right.

I think this is the correct link: https://github.com/ZombieJuanma/EscenariosMoM/tree/master/EditorEscenario3

### Valkyrie Version
v.2.3.03

### Attach Save, Quest or Scenario
Log File:
%LOCALAPPDATA%Low\NA\Valkyrie\output_log.txt
Saves:
%appdata%/Valkyrie/MoM/Save
%appdata%/Valkyrie/D2E/Save
Quest:
%appdata%/Valkyrie/D2E/Editor
Scenario:
%appdata%/Valkyrie/MoM/Editor

**Comment by chrismaliszewski** [comment]
A brief opinion about the scenario. 
1. I didn't find any bug/issues etc.; I'm a little picky about the thing so that's great!
2. I don't speak Spanish so I won't be discussing the plot. 
3. What I didn't like was a corridor system with just one way to run. As a result, you must evade every monster that's on your way relying on your luck or fight them, and there are many of them in the scenario, some of them pretty strong. It'd be great if were more paths to run.

**Comment by ZombieJuanma** [comment]
Hi, thanks for the comments.
I wanted to create a claustrophobic scenario. Having to evade monsters is part of the idea. There are also many weapons scattered around the stage to help.

SPOILERS
If you are killing monsters during the game it is easier. There is only one moment of random appearances of monsters. END SPOILERS

It's my first stage, I want to create more by bringing different sensations. 

Thank you and sorry for my English if something is not understood.

**Comment by scrubbless** [comment]
Could you rename the scenario folder (EditorEscenario3)  , using the default name may cause issues further down the line.

**Comment by ZombieJuanma** [comment]
Ok, but how do I do it? I'm a little clumsy with this program. Do I have to change the name on my computer?

**Comment by scrubbless** [comment]
Yes in %appdata%\valkyrie\mom\editor

Rename the scenario folder, then open valkyrie and create the package again.

**Comment by ZombieJuanma** [comment]
I do not know if I did it correctly. I have renamed the files manually on my PC. Then I have seen your message and I have created a new package and I have replaced it all.

https://github.com/ZombieJuanma/EscenariosMoM/tree/master/LlamadaInnsmouth

**Comment by ZombieJuanma** [comment]
If there is a problem, I can upload everything again with the new name. Sorry but it's my first time with the Github app and I did not understand it well.

**Comment by scrubbless** [comment]
That looks good, I'll add it now.

**Comment by scrubbless** [comment]
Ok its showing now, I've run it through and it works mechanically.

I'll close this off.

Any changes you make to the scenario (bug fixes etc) just upload and overwrite  to the same location (as you have here) then it will automatically  update in valkyrie.

**Comment by ZombieJuanma** [comment]
I just saw the stage in Valkyrie. Thank you :)
