### ISSUE TITLE
Question about donations

### ISSUE THREAD

**Issue by chrismaliszewski** [NPBruce/valkyrie#1148]
Hi. I'd like to ask if it'd be legal should a scenario creator asked for donations as an appreciation of his/her work? I'm not saying about myself; I'm not a creator. It's a general question. 

Sometimes people spend much time to create something, and, on the other hand, some people may like to give their 'thanks'.

The question is, could FFG have a problem of the behaviour of such in terms of licence and copyrights?

**Comment by scrubbless** [comment]
We've had this discussion  before along with one about publishing to the Google play store, both ended up in a consensus opinion of "No'.

Personally I wouldn't want a donation, turning Valkyrie into a way people  can profit in my opinion  will draw FFGs layers attention. 

It could potentially  shut down the project. Similar reasons for not publishing on the play store.

**Comment by chrismaliszewski** [comment]
I see. I tired to find a similar topic by searching words money, donation etc., even closed ones, with no results.

Thx for the answer. Closing the issue if it was already discussed.

**Comment by scrubbless** [comment]
It was on discord, that's probably why you couldn't find it here :)
