### ISSUE TITLE
What happened to Tommy Muldoon and Jim Culver

### ISSUE THREAD

**Issue by antontimmermans** [NPBruce/valkyrie#1152]
### Description of Problem or Question
when playig disturbance at the docs we could not select Tommy Muldoon. In the character selction list we found Jim Culver where you would expect Tommy:
![IMG_1448 7185](https://user-images.githubusercontent.com/42072372/56856053-f29b2780-6952-11e9-86f7-bc644337c12c.jpg)

### Valkyrie Version
2.3.03

### Attach Save, Quest or Scenario
Scenario:
found while playing scenario Disturbance at the Docs

**Comment by redwolf2** [comment]
Have you activated Streets of Arkham?

![grafik](https://user-images.githubusercontent.com/4141621/56856556-bc16da00-695d-11e9-8f9f-b6194e7dc4cc.png)

**Comment by redwolf2** [comment]
Merged
