### ISSUE TITLE
La llamada de Innsmouth - Little changes

### ISSUE THREAD

**Issue by ZombieJuanma** [NPBruce/valkyrie#1154]
Hi, I do not know if I should create a new one issue. I have made little changes to correct some texts.

I also wanted to know how I can see the ratings of the users' scenario. Thank you.

https://github.com/ZombieJuanma/EscenariosMoM/tree/master/LlamadaInnsmouth

**Comment by ZombieJuanma** [comment]
I just saw in Valkyrie that it has been automatically updated.

Anyway, I still have the doubt about the second question.

**Comment by redwolf2** [comment]
It can take up to one hour for the script to register, that a scenario has been updated.

> I also wanted to know how I can see the ratings of the users' scenario. Thank you.

You can find the document here:
https://goo.gl/xgxdMb
