### ISSUE TITLE
Does not work with installation from Amazon appstore

### ISSUE THREAD

**Issue by Frank667** [NPBruce/valkyrie#1156]
### Description of Problem or Question
I installed the latest Version on my Android tablet to use it for Road to Legend. RtL was installed from the Amazon appstore.
I start RtL as requested in the documentation and then I start Valkyrie. This leads me to a screen saying that Valkyrie cannot find RtL and that I should download it from the Google Play Store. I do not have a Google account and no Google Play on my tablet (it has LineageOS installed without any Google apps). Shouldn't Valkyrie find the installation nevertheless?
Or does it rely on some Play Store files, so I won't be able to use it?

Regards,
Frank

### Valkyrie Version
2.3.03

### Attach Save, Quest or Scenario
Log File:
%LOCALAPPDATA%Low\NA\Valkyrie\output_log.txt
Saves:
%appdata%/Valkyrie/MoM/Save
%appdata%/Valkyrie/D2E/Save
Quest:
%appdata%/Valkyrie/D2E/Editor
Scenario:
%appdata%/Valkyrie/MoM/Editor

**Comment by redwolf2** [comment]
Google Playstore supports obb files. The Amazon Store does not. Additional Resources will then be downloaded using AWS Services.

In your case try the guide for fire os.

https://github.com/NPBruce/valkyrie/wiki

**Comment by Frank667** [comment]
Thanks for the explanation. The download from the link was for an older version and timed out anyway. I downloaded the obb from somewhere else and Valkyrie started working!
