### ISSUE TITLE
Bug with a MiGo monster

### ISSUE THREAD

**Issue by ZombieJuanma** [NPBruce/valkyrie#1157]
I discovered that there is a bug in the Horror Phase for the MiGo. You press the button but nothing appears.

**Comment by ZombieJuanma** [comment]
![migobug](https://user-images.githubusercontent.com/49789581/57259735-ed2f9280-7060-11e9-84b7-bb78db1bf879.jpg)
If you try to press the Horror button against a Migo, no message appears.

**Comment by ZombieJuanma** [comment]
Hello @redwolf2 , this bug continues in the last update.

**Comment by redwolf2** [comment]
Thanks for the issue. Might have a look at that, soon.

**Comment by NPBruce** [comment]
I can't reproduce this in english, spanish or portugese. Anyone else have this problem? @ZombieJuanma  does this still occur?

**Comment by ZombieJuanma** [comment]
Yes @NPBruce,  it still happens. And the "Evade" button doesn't work with the Migo monster either.

**Comment by antontimmermans** [comment]
This bug is still present in 2.4.10 confirmed in feedback sheet entry line 7577 (10/25/2020 20:11:23 -CrimsonAlly.valkyrie)
