### ISSUE TITLE
Skeleton Investigator Attacks

### ISSUE THREAD

**Issue by NicolaZee** [NPBruce/valkyrie#1158]
The investigator attacks against Skeletons (from the expansion Streets of Arkham) seem to be wrong.
For instance a spell attack results in a heavy weapon attack.
Apologies if this is an already known issue.

And on a different note can I add labels to issues and if so how?

**Comment by NicolaZee** [comment]
This is not an urgent fix as I found a simple workaround.
I set up a CustomSkeleton monster which uses the Zombie monster as the base.
I doubt if any players will notice the difference.

**Comment by NicolaZee** [comment]
My latest scenario is for the expansion Streets of Arkham.
I've started beta-testing using the Zombie Monster as a stand-in for the Skeleton from Streets of Arkham.
This works fine for initial testing.
But I won't be able to release the scenario until the Skeleton Monster is fixed as players who have Streets of Arkham but not the RM expansion won't be able to play it.

On the plus side I don't really like doing a release.
So if the skeleton monster is not fixed, I don't have to worry about releasing the scenario into the wilds!
Every cloud has a silver lining.
: )

**Comment by NicolaZee** [comment]
Workaround number two.
I set up a CustomMonsterSkeleton and copied the spell attacks from the import text file.
It now works OK.;
So the fix is not urgent.
Where there's a will sometimes there's a way!
: )

**Comment by NPBruce** [comment]
Fixed in 2.4
