### ISSUE TITLE
New Scenario in Spanish: El misterio de la Mansión Coleman

### ISSUE THREAD

**Issue by ZombieJuanma** [NPBruce/valkyrie#1159]
New Scenario in spanish for Mansions of Madness: https://github.com/ZombieJuanma/EscenariosMoM/tree/master/MansionColeman

This scenario has been created to play with the core game. But you can use components of the expansions Recurring Nightmares and Supressed Memories. I have created some options to choose the expansions you have at the beginning of the scenario. But it is necessary to have activated the options of the Valkyrie expansions before starting to play.

**Comment by chrismaliszewski** [comment]
@ZombieJuanma, I don't speak Spanish, so I just checked the playability. 

Comments:
1. Is it possible to go back with the camera to the main board after the certain items are placed off the board? It's annoying to move the camera every time they appear. 
2. I think there is a bug in the dialogue:
![image](https://user-images.githubusercontent.com/7532602/57200798-3392dc00-6fe4-11e9-98b1-1a9a0dd156ba.png)
Shouldn't there be an image of an item? Should it also appear in every round or just once?
3. Same as 1.; the dialogue is a bit annoying as it moves the camera every time it appears. 
4. Is it possible to place more walls around the mansion to close it completely as there are 3 doors uncovered? 
5. Is it possible to deal damage to a monster automatically so a user doesn't need to do it by hand? (the last part of the game)

I think that's all :).

**Comment by ZombieJuanma** [comment]
Hi. The photo with the phrase that you are indicated to me, it appears to me well. It's weird, I do not know why you get the phrase like that.

I have not put more walls because I think that, thinking of the core game, there is no more to put (4 frames and 4 shelves).

* Is it possible to deal with damage to a monster automatically so a user does not need to do it by hand? (the last part of the game)
Sorry, I do not understand this last sentence.

**Comment by ZombieJuanma** [comment]
I have done many tests. I get the correct name of the object and the photo. :S

**Comment by ZombieJuanma** [comment]
I think that when I first uploaded the stage I had that error. But then I made an update and that error is already corrected. Could that be the problem?

**Comment by ZombieJuanma** [comment]
5. Is it possible to deal damage to a monster automatically so a user doesn't need to do it by hand? (the last part of the game)

Okey I already believe that I know what you mean. Well, I'm not an expert in Valkyrie. I do not know if it is possible to do that.

**Comment by chrismaliszewski** [comment]
About the monster damage: it's hard to talk about it w/o spoilers so 
SPOILER ALERT!
*
*
*
You give a player a certain item which can be used to defeat a monster. As I said, I don't speak Spanish but from what I understood, using the item causes the monster having X Damage. As the monster has a big amount of HP you need to use it several times. Each time you need to click a monster, then click X times the damage dealt. It can be a bit annoying. If it was possible to cause the damage automatically. It'd be great. Also, you'd need to remember to create a check if the monster's HP is off to inform a player about it.
*
*
*
SPOILER ENDS

**Comment by chrismaliszewski** [comment]
I think I know what happens with the bug and the camera! I need to confirm it. I'll be back soon.

**Comment by ZombieJuanma** [comment]
About de monster damage: Yes, I have understood you. But I'm not an expert on Valkyrie, I do not know how I could do that automatically.

**Comment by chrismaliszewski** [comment]
@ZombieJuanma, please repeat the scenario after me:
1. Begin the game for the Base version of MoM,
2. Click on the woman on the right side in the shop,
3. Buy any item,
4. Finish the phase,
5. Click Continue.

My questions are: 
1. What happens next to you? Are you moved off the map and do you see the screen of the kind:
![image](https://user-images.githubusercontent.com/7532602/57201259-b7e85d80-6fea-11e9-9a19-80737e85b267.png)
It's EXACTLY the message mentioned above but an item's name in it.
2. Also, tell me, how many times [QItemEquipAlea] should be displayed? Once, twice, as many times as there are items in the queue? 

I presume that all of the items mentioned in [QItemEquipAlea] were displayed to me before I went to the mansion in the scenario mentioned above in this comment. After the queue was emptied, the message box was still being displayed to me for some reason.

**Comment by ZombieJuanma** [comment]
I will check what happens.

**Comment by ZombieJuanma** [comment]
Oh, I’m so sorry. I made a last minute change and I don’t know what happened there. I’m gonna fix it right now.

**Comment by ZombieJuanma** [comment]
I just updated. It shouldn’t happen now.

**Comment by chrismaliszewski** [comment]
Ok, the problem disappeared. I was worried that you removed it completely by mistake but I read your edited post.  

To understand the scenario, it will need to be translated into English :). 

I'm also wondering about something. I'm not sure if it's explained in the scenario but...
<details>
<summary>SPOILER SECTION</summary>
Are there only 2 monsters in the scenario for the Basic version? Or am I just lucky? If there are just 2, why bother placing the Hunting Horror/the one monster which appears in the toilet? Wouldn't it be better to just have the ghost as an enemy in the scenario? 
</details>

**Comment by ZombieJuanma** [comment]
Okey, I don’t know how to put the Spoiler section.

***SPOILERS***






During the game, several Monsters appear. His appearances are random. The Ghost is one of the Alternative endings that I have Created on stage.

**Comment by chrismaliszewski** [comment]
Spoiler is explained here: https://gist.github.com/jbsulli/03df3cdce94ee97937ebda0ffef28287 :)

**Comment by ZombieJuanma** [comment]
I wanted to say that the scenario would be better understood when the dialogue error was fixed. Speaking in terms of gameplay. But if one day you dare to translate it, better ;)

**Comment by ZombieJuanma** [comment]
I just discovered a small mistake. I’m going to correct it right now and update the stage.

**Comment by ZombieJuanma** [comment]
Now its okey. https://github.com/ZombieJuanma/EscenariosMoM/tree/master/MansionColeman

**Comment by scrubbless** [comment]
I'll get this added when I have a free moment later

**Comment by ZombieJuanma** [comment]
> 
> 
> I'll get this added when I have a free moment later

I just saw the stage at Valkyrie. Thank you :)
