### ISSUE TITLE
Valkyrie Examples and Demos scenario crashes

### ISSUE THREAD

**Issue by chrismaliszewski** [NPBruce/valkyrie#1161]
I just wanted to see something in the scenario but as soon as I click 
![image](https://user-images.githubusercontent.com/7532602/57207880-65c42e00-7024-11e9-86aa-4d48576ef147.png)
Example button, the game app crashes. Just in case I turned RN & SM expansions on with the same result.

Will someone update the scenario or should I remove it as it will not be updated?

**Comment by scrubbless** [comment]
I can take a look if @npbruce can't.

**Comment by NPBruce** [comment]
I think this can be removed, however the fact that it is crashing suggests a bug has been introduced into Valkyrie.

**Comment by scrubbless** [comment]
This works fine for me on android, nonissues clicking example or demo v1.1 and v1.2

**Comment by chrismaliszewski** [comment]
Interesting. What about Windows? 

I checked again and something interesting is going on. Interestingly enough, the app may not crash right after clicking Example but after a small while after.

According to output_log:
Warning: Unable to write file: C:\Users\XXX\AppData\Roaming\Valkyrie\MoM\Save\saveAuto.vSave
Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path "C:\Users\XXX\AppData\Local\Temp\Valkyrie\save.ini".
  at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean anonymous, FileOptions options) [0x00000] in <filename unknown>:0 
  at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share) [0x00000] in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream:.ctor (string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
  at System.IO.File.Open (System.String path, FileMode mode, FileAccess access, FileShare share) [0x00000] in <filename unknown>:0 
  at Ionic.Zip.ZipEntry.SetInputAndFigureFileLength (System.IO.Stream& input) [0x00000] in <filename unknown>:0 
  at Ionic.Zip.ZipEntry._WriteEntryData (System.IO.Stream s) [0x00000] in <filename unknown>:0 
  at Ionic.Zip.ZipEntry.Write (System.IO.Stream s) [0x00000] in <filename unknown>:0 
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Although I don't have any problems with other scenarios autosaving.

**Comment by scrubbless** [comment]
I'll test on windows when I get near a windows PC.

**Comment by scrubbless** [comment]
I have tested this on Windows version too and can't reproduce a crash. Have you been tinkering with your install at all? Might be a good idea to do a clean install.

Uninstall, delete Valkyrie from %appdata%, re-install and re-import.

**Comment by chrismaliszewski** [comment]
@scrubbless, I'm using valkyrie-windows-2.3.03. I renamed %appdata%\Valkyrie\ catalogue. 
![image](https://user-images.githubusercontent.com/7532602/57515469-d3df5c80-7366-11e9-9ea2-e6415ffcdd64.png)
imported assets again
![image](https://user-images.githubusercontent.com/7532602/57515493-e6f22c80-7366-11e9-8b2d-1629438798d1.png)
and downloaded the scenanario once more
![image](https://user-images.githubusercontent.com/7532602/57515537-fe311a00-7366-11e9-86a3-fdd1f91130c7.png)

So here is the footage from what I observe: https://drive.google.com/open?id=14IAKEgsc-O3SK3703kbiFbixxn9GwXks
and output_log.txt:
````

Warning: Unable to write file: C:\Users\XXX\AppData\Roaming\Valkyrie\MoM\Save\saveAuto.vSave
Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path "C:\Users\XXX\AppData\Local\Temp\Valkyrie\save.ini".
  at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean anonymous, FileOptions options) [0x00000] in <filename unknown>:0 
  at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share) [0x00000] in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream:.ctor (string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
  at System.IO.File.Open (System.String path, FileMode mode, FileAccess access, FileShare share) [0x00000] in <filename unknown>:0 
  at Ionic.Zip.ZipEntry.SetInputAndFigureFileLength (System.IO.Stream& input) [0x00000] in <filename unknown>:0 
  at Ionic.Zip.ZipEntry._WriteEntryData (System.IO.Stream s) [0x00000] in <filename unknown>:0 
  at Ionic.Zip.ZipEntry.Write (System.IO.Stream s) [0x00000] in <filename unknown>:0 
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)
```

I'll update the app, try again and let you know soon.

**Comment by chrismaliszewski** [comment]
Can someone else try running the scenario to check if it's only me who has this problem?

**Comment by redwolf2** [comment]
I will try today and check it out.

**Comment by scrubbless** [comment]
Rename or delete the entire valkyrie directory (in %appdata%, clean and fresh. I had loads of wierd issues when I dropped files into the download directory and looked into the manifest files in the scenario explorer.

You're better of doing a completely clean install and starting a fresh.

Do you experience the problem on  any other devices?

**Comment by redwolf2** [comment]
I tried it and couldn't reproduce it with v2.3.04 (i am positive v2.3.03 would be the same result). I created a new issue for the scenario deletion problem i mentioned in the last post here: https://github.com/NPBruce/valkyrie/issues/1165

**Comment by chrismaliszewski** [comment]
@scrubbless, previously I did exactly who you've just said:
1. renamed the %appdata%\Valkyrie so the app doesn't see it anymore and needs to create a new one),
2. removed %LOCALAPPDATA%Low\NA\Valkyrie\ directory,
3. unzipped a freshly downloaded valkyrie-windows-2.3.04 file,
4. ran the app, located MoM's EXE (I have it in the uncommon location so I needed to locate it manually), imported assets,
5. downloaded the fresh version of the scenario.

Everything "a completely clean install and starting afresh". Did that again to make 100% sure. The app still crashes. 
Here you have the full [output_log.txt](https://github.com/NPBruce/valkyrie/files/3168028/output_log.txt)

**IMPORTANT**
**Found the reason for the problem.** 
![image](https://user-images.githubusercontent.com/7532602/57555104-6f081e80-73c7-11e9-9627-02c602080ac4.png)

**Guys, important question: do you have BtT expansion turned on?** I didn't. After I turned that in, the app stoped crashing. 

Two possible solutions, the first one preferable:
1. change all tiles in the scenario so the base is only required as indicated by the lack of "expansions required icons" in the first place:
![image](https://user-images.githubusercontent.com/7532602/57555293-fce40980-73c7-11e9-80de-5ad9aa883dad.png)
2. add required expansions information to the scenario.

**Comment by scrubbless** [comment]
I had btt turned on, as soon as I turned it off it crashed.

This is expected because the side hall is a BtT tile and the scenario does not have a 'required expansion'set for BtT.

Nice find @chrismaliszewski, this is not a valkyrie bug, it's a Scenario miss configuration,  I assume since it's very old that required expansions were not a thing?

Is this consistent with your memory of writing this scenario @NpBruce ?

**Comment by redwolf2** [comment]
@chrismaliszewski Great detective work, chris.

**Comment by NPBruce** [comment]
Had a quick look, the issue is with the "Token Spawns for Variables" scenario which wasn't mine, it was added as an assist for the guide. It can be updated or removed as appropriate.

**Comment by scrubbless** [comment]
Turns out that the Tokens and Variables sub-scenario was using a MAD23 tile, i've replaced it with a similar base tile (hall corner). Looks about the same, doesn't require any expansions selected.
