### ISSUE TITLE
pull requests

### ISSUE THREAD

**Issue by zcaalock** [NPBruce/valkyrie#1162]
There are 2 pull requests to merge with master, can someone do it and compile updated version of the installer?

**Comment by redwolf2** [comment]
I think @BenRQ  is a litte busy right now. I don't want to release a version without his concent.

**Comment by BenRQ** [comment]
Hi there,
yes I did not find much time for Valkyrie lately, as I've started a big personal project (company creation).
I don't know when I will be able to work on version 2.4, and I don't know how much time I will have for this.
I still want to help on this project of course, but I'm afraid I will not be as active as I was before.

@redwolf2 it would make sense to release an update of version 2.3 with the two PR I think.
If you have some time to do it, please go ahead.

**Comment by redwolf2** [comment]
No problem Ben, good luck with the project. I will integrate those PRs and create a new version.

**Comment by scrubbless** [comment]
Good luck with the project @BenRQ !

**Comment by BenRQ** [comment]
@redwolf2 @scrubbless 
Thank you guys :)

**Comment by redwolf2** [comment]
2019.1.1f1 broke alot of things. I will fall back to 2018.2.21f1 and try again.

**Comment by redwolf2** [comment]
I created the release https://github.com/NPBruce/valkyrie/releases/tag/v2.3.04
