### ISSUE TITLE
Polish version of A Glimpse of the Past

### ISSUE THREAD

**Issue by chrismaliszewski** [NPBruce/valkyrie#1163]
With @zcaalock we created a Polish version of the scenario including a professional audio reading by Wojtek.

Here is a link to the translation: https://github.com/chrismaliszewski/A_Glimpse_of_the_Past_PL

Also, this file in column D contains issues found in the English translation.

**Comment by chrismaliszewski** [comment]
@slycozzolino

**Comment by chrismaliszewski** [comment]
Does anyone have another kind of contact to @slycozzolino?

**Comment by zcaalock** [comment]
How to upload scenario when original author is not responding?

**Comment by chrismaliszewski** [comment]
@redwolf2, @NPBruce, @scrubbless, can you help somehow?

**Comment by slycozzolino** [comment]
Opps. Missed this email. I'll add it.
Sorry about that.

**Comment by slycozzolino** [comment]
Added and updates made.
As for item 425 all investigators can interact regardless if they have either or non of the items. Think of it like the items are repealing one another like magnets. So the investigators without the items are helping the investigators with the items.

**Comment by chrismaliszewski** [comment]
@slycozzolino, you missed my point. 

"[...] The investigator carrying the Ritual Dagger Common Item and the Cult Sigil Unique Item or in the same space as an investigator with either item can attempt to destroy the pair."

The problem in this sentence is in the middle part:
1. "The investigator carrying the Ritual Dagger Common Item and the Cult Sigil Unique Item..." - this part is clear; if you have both items you can perform the action from point 3.,
2. "...or in the same space as an investigator with either item..." - **here is the problem**. I think what you wanted to say in the sentence was:
```
if( 
   (you have one of the items AND there is an investigator with the other one next to you) 
   OR 
   (you don't have the items AND there is an investigator with both of the items next to you)
   OR
   (you don't have the items AND there are investigators next to you with both items)
){
   you can perform the action from point 3.
}
```
BUT the same sentence can also be read as
```
if(
   (you don't have any of the items AND are in the same space as other investigators with ONLY ONE OF THE ITEMS in their hand (they don't have both items; just 1!))
){ 
   you can perform the action from point 3.
}
```
Do you see that now? The text suggests that it's possible to perform the action with just one item. What's even worse, the scenario allows it to be. You can fire the event with just the sigil without the necessity to have the dagger. So by just using the sigil, you can destroy the dagger too although you don't have it! 
3. "...can attempt to destroy the pair." - the action is clear.

**Comment by slycozzolino** [comment]
Ah I see
I'll update it.

**Comment by chrismaliszewski** [comment]
@slycozzolino, audio doesn't work for some reason.

**Comment by slycozzolino** [comment]
Opps! I didn't see the files. I just opened the translation spreadsheet.
I have uploaded everything.
I updated 425
"An investigator in the same space as the investigator or investigators carrying the Ritual Dagger Common Item and the Cult Sigil Unique Item can attempt to destroy the pair."

**Comment by chrismaliszewski** [comment]
That one also is not good. It doesn't suggest that the investigator carrying the items also can themselves attempt the action.

**Comment by chrismaliszewski** [comment]
Maybe merge them both together: 

The investigator carrying the Ritual Dagger Common Item and the Cult Sigil Unique Item or an investigator in the same space as other investigators carrying both items can attempt to destroy the pair.

What do you think?

**Comment by slycozzolino** [comment]
I don't think it needs it. I thought about adding to the original statement but felt like it became too redundant. It doesn't suggest that they can't do it in which case it would say " in the same space as **another** investigator or investigators".

**Comment by chrismaliszewski** [comment]
Do whatever you find good :). I'll be waiting for the scenario update in Valkyrie and will close the topic soon.

**Comment by slycozzolino** [comment]
It should be up. I'll leave it for now, but try to see if i can find a way to make it more clear without being too long.

**Comment by slycozzolino** [comment]
Thanks for all your work on this.

**Comment by chrismaliszewski** [comment]
My pleasure. Everything works now. I'm closing the topic.
