### ISSUE TITLE
Enhancement: 'Auto sending of statistics' option

### ISSUE THREAD

**Issue by chrismaliszewski** [NPBruce/valkyrie#1167]
Hi. 

Congratulations regarding 1000 recorded play sessions on Valkyrie! :clap:

When I saw the number my first thoughts were "Isn't that too small?", "Certainly there were more plays!", "Maybe they only count the sessions when someone sends they opinion?". 

And I think the latter is the truth, correct me if I'm wrong. 

If so, I think it'd be good to create an option in the Options menu which, if turned on, would allow the app to always send statistics about the sessions regardless of users sending their opinion or not. 
PRO: relevant, additional information about many more sessions which would be helpful to creators,
CON: minor, potentially it'd use users' data if they are playing on a mobile device and they wouldn't like their data to be drained.

By default, the option would be off. To inform users about a new option I'd create a notification of some kind in the main menu next to the Options button which would stay there until a user at least once enter the Options menu. I think I discussed that concept once before:
![image](https://user-images.githubusercontent.com/7532602/58224774-18112a80-7d73-11e9-84a8-f4ae98460d50.png)

Would it be useful?

**Comment by scrubbless** [comment]
> When I saw the number my first thoughts were "Isn't that too small?", "Certainly there were more plays!", "Maybe they only count the sessions when someone sends they opinion?".
> 
> And I think the latter is the truth, correct me if I'm wrong.

No all plays are collected, ts just that we've only been collecting plays since October last year.

**Comment by chrismaliszewski** [comment]
That explains everything 🙂.
