### ISSUE TITLE
New Scenario in Spanish: Desaparición en el bosque

### ISSUE THREAD

**Issue by ZombieJuanma** [NPBruce/valkyrie#1168]
New scenario in spanish for Mansions of Madness: https://github.com/ZombieJuanma/EscenariosMoM/tree/master/DesaparicionBosque

**Comment by scrubbless** [comment]
I've added this scenario and will close this when  it appears in the lists.

I'll also add this to the stats sheet tomorrow.

**Comment by ZombieJuanma** [comment]
Okey, thanks ;)

**Comment by scrubbless** [comment]
Its showing in the list, I've downloaded and launched it successfully.
