### ISSUE TITLE
New Scenario in Spanish: Tras la puerta

### ISSUE THREAD

**Issue by ZombieJuanma** [NPBruce/valkyrie#1171]
New scenario in spanish for Mansions of Madness: https://github.com/ZombieJuanma/EscenariosMoM/tree/master/TrasLaPuerta

**Comment by scrubbless** [comment]
Hi! I'll get this added for you today

**Comment by scrubbless** [comment]
I have added this to the scenario explorer and to the stats spreadsheet.
