### ISSUE TITLE
Storm of Spirits - Agnes Baker

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#1172]
### Description of Problem or Question
The Storm of Spirits spell is not given when Agnes Baker is selected. 

Since it not a unique item we will not think to exclude it like we do for normal unique items. Is there a way to exclude this from random spell rolls when Agnes is in play?

### Valkyrie Version
2.0.4

**Comment by redwolf2** [comment]
Fixed: https://github.com/NPBruce/valkyrie/pull/1178

Not sure if the random spell exclusion works though.
