### ISSUE TITLE
Lock Picking Module - Add it to your scenario!

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#1175]
Hi All,

I have created a Module that you can use to add a Lock picking puzzle into your scenario.

It looks like this!
![image](https://user-images.githubusercontent.com/32058089/60815977-95acc080-a190-11e9-9f4c-307599961675.png)
Its just a simple order puzzle, thematically appropriate (I hope).

Its just a script to copy some lines of code into your Event.ini, ui.ini and localization.english.txt, it also uses some custom images that I made.

Unzip the ScrubblessLockPickModule.zip into your %appdata%\Valkyrie\MoM\Editor\<scenariofolder> then run the RunMe.bat.

Once you've done that, the event chains and UI elements will show up in your scenario. Create a token and point it to "LP_Token". There are a few bits you'll need to edit, but its all explained in the ReadMe.txt contained within the .ZIP.

_If you're worried about the script, edit it to take a look at what its doing. Its just a "type" batch command that will copy the contents of pre-generated files into your scenario files, then delete the files and script._

I wanted to get some feedback before I added this to the guide and made it more widely available. If you lot like it i'll make a more graphical guide and add it to the tutorial.

[ScrubblessLockPickModule.zip](https://github.com/NPBruce/valkyrie/files/3368668/ScrubblessLockPickModule.zip)

**Comment by newusergettingnuts** [comment]
Awesome idea scrubbles! will try it soon.

**Comment by chrismaliszewski** [comment]
@scrubbless, I'd like to test your creation and give you a feedback but I think I am dump :p. Although I've followed the instruction, I have problems. 

I've created a totally new scenario. I've done points 1-4 written in the instruction. Unfortunately, I'm stuck at point 5. Although I see new things in the files, I can't see any of them in the app.
![image](https://user-images.githubusercontent.com/7532602/60900216-23111300-a26c-11e9-8a2b-b2b1991864dc.png)
![image](https://user-images.githubusercontent.com/7532602/60900380-5d7ab000-a26c-11e9-8390-ac9fb66973b8.png)

I tried another scenario made by someone else and the RunMe script works:
![image](https://user-images.githubusercontent.com/7532602/60900718-f01b4f00-a26c-11e9-8b90-84c33663ea8a.png)

Could you check it? Also, could you create an alone scenario where you can test the functionality?

**Comment by scrubbless** [comment]
You ran the script before creating a ui element.

Open the quest.ini file and add this line unde rthe other .ini files:

ui.ini

**Comment by chrismaliszewski** [comment]
Yes, I did run the script before creating a UI element. I partially did the instruction from above and README.txt; I omitted the second part of point 1. **Sorry.**

I started the process over again. 
Created a scenario, added a token (Token0) and an event (Event0, with the trigger EventStart) which adds component Token0. And edited Token0 by adding a button to it which fires EventLP_Token event. 
After staring the scenario and clicking the token, I can see ~~~~~~~~~~ text. 
But right after I click Pick lock, the app crashes. 

Scenario: [EditorScenario1.zip](https://github.com/NPBruce/valkyrie/files/3374009/EditorScenario1.zip)
Output file: [output_log.txt](https://github.com/NPBruce/valkyrie/files/3374001/output_log.txt)
I think the cause of the crash is "Error: Unable to create missing quest component: UIBLACKBG". What is the UIBLACKBG?

**Comment by scrubbless** [comment]
Did you add ui.ini to the quest.inu file?

I suspect that because the ui.ini is not linked that when the event calls the UI elements it crashes.

UIBLACKBG is a ui element that puts up a black background.

**Comment by chrismaliszewski** [comment]
Ok, everything works now. I didn't add ui.ini to the quest.ini file because I thought that after I created a new scenario and added a token, the un.ini file will automatically be added to the quest.ini. My bad, again. 

It'd be good to either:
1. in the instruction write that a user must make sure that ui.ini file is listed in the quest.ini file otherwise the module won't work,
2. write the RunMe.bat script so it checks if the ui.ini file is listed inside quest.ini and, if not, add it to the file. 

I'll shortly edit the RunMe.bat script and try to do the latter.

And shortly I'll write my opinion/ideas about your work :).

**HERE IS THE WORKING SCENARIO WITH THE EXAMPLE OF THE MODULE**
[EditorScenario1.zip](https://github.com/NPBruce/valkyrie/files/3374090/EditorScenario1.zip)

**Comment by scrubbless** [comment]
In the read me file is says to make sure that at least one UI component and one Event have been created before installing the module , this will ensure that the three files are present.

Adding the ui.ini was just a fix for your situation. It would be a problem  if the scenario had no events or dialogue before installation too (aka no events.ini or localisation files linked in quest.ini).

**Comment by chrismaliszewski** [comment]
After playing with the module for a bit I only can say GREAT PIECE OF WORK @scrubbless! 

Pros:
+it should be quite easy to extend it for even higher difficulties if someone wants,
+it is easy to hardcore a solution if needed.

I can't find any cons, to be honest. 

I only have two concerns:
1. creating multiple hardcoded riddles,
2. creating multiple riddles with different BGs; 

But it should be relatively easy to do as you will need to play a little with making copies of events. 

QUESTION: Would it be possible to make the module a bit easier to maintain? What I mean, making many BG is a bit difficult from what I can see as you'll need to make a copy of 4 events do add 1 extra BG. 
I think that if it's possible, it'd good if the order of callback is as follows:
[EventLP_Opener] - displays a comment for players,
[EventLP_Token] - if even needed,
[EventLP_Opener_SetVariables] & [EventLP_START] - at the same time (in one event)
That way, a creator would need to create a copy of just 2-3 events which they would eventually need to do if creating multiple riddles with either hardcoded solutions or BGs

**Comment by scrubbless** [comment]
I was thinking about using the puzzle multiple times and have yet to think of an elegant solution.

> [EventLP_Opener] - displays a comment for players,
> [EventLP_Token] - if even needed,
> [EventLP_Opener_SetVariables] & [EventLP_START] - at the same time (in one event)

I agree some of these events are redundant, I was originally going to make the event a loop, always going back to the Start event and re-running the sequence. The method has is pro's - as its much more adaptable. Then I realised part way through that I was making it more complicated than it needed to be.

I'll try to stream line it a bit.

I could probably do something a little cleverer with the script and get the player to input a variable when running the script. This could then inject whatever the player types (or even a random combination) into the prefix - aka LP_* might become XY_* or whatever.

@NPBruce mentioned about making the file an SLPmodule, when I get some more understanding of this I may be able to work something a bit more usable.

**Comment by scrubbless** [comment]
If you've played "Escape" 4 player, there is a number lock puzzle. That one you use a riddle and a key to decipher the number.

I was wondering if it might be another candidate for a module, this way there could be a lock on a room for example but the player would have to find the code somewhere in the mansion.

![image](https://user-images.githubusercontent.com/32058089/60921612-d12fb380-a292-11e9-9f51-7089b7bd6666.png)

**Comment by newusergettingnuts** [comment]
> If you've played "Escape" 4 player, there is a number lock puzzle. That one you use a riddle and a key to decipher the number.
> 
> I was wondering if it might be another candidate for a module, this way there could be a lock on a room for example but the player would have to find the code somewhere in the mansion.
> 
> ![image](https://user-images.githubusercontent.com/32058089/60921612-d12fb380-a292-11e9-9f51-7089b7bd6666.png) 

in my scneario THe Cult of Cthulhu i use a lock puzzle to end the scenario like the one you refer here. Not with that awesome image but using tha actual puzzles available.

**Comment by scrubbless** [comment]
If it would be more suitable, or something people would like I would be happy to make something up.

I could share the .XCF files too or generate different backgrounds. For example I could make the lock static, then have a set of different backgrounds that could be picked from.

For example, the Lock Picking puzzle above, I just reused the images from Escape and made them a bit more generic.

![image](https://user-images.githubusercontent.com/32058089/60922195-202a1880-a294-11e9-82b3-31922253f9ad.png)

I just use layers in GIMP to lay on flavour, so would be simple enough to cut the lock into its own layer and then impose new backgrounds behind it.

**Comment by chrismaliszewski** [comment]
@scrubbless, I like the idea of yours but there is a small problem. Chests usually have a lock in the centre, not on the side :). It would look strange having a lock like that on a chest. 

I think what creators really and only would need is to set:
1. a comment (which is set in EventLP_Opener),
2. difficulty and solution of a riddle (which is done in EventLP_Opener_SetVariables),
3. UI elements of the BG and pins they want to use which are set in ui.ini file.

1 and 2 should be easy to implement in one event. 
I'm seeing a problem with 3 as UILP_PinX_Pos_Y UI elements are hardcoded in many events. A user who would like to create a custom graphic (i.e. a chest with a lock in the centre) will need to recreate the whole lot right now. 
So, I have a question. Is it possible to use a variable and store in it a name of a UI element written in ui.ini to later use it in the 'add' property? I mean to be used as follows:

[EventLP_SetParams]
operations=comment,=,Opening Event, tailor to situation.,LP_Final_Move_1,=,#rand2 LP_Final_Move_2,=,#rand2 LP_Final_Move_3,=,#rand2 LP_Final_Move_4,=,#rand2 LP_Final_Move_5,=,#rand2 LP_VarsSet,=,1 LP_Difficulty,=,4,
**_UILP_Pin1_Pos_0_,=,CustomPin1Pos0,_UILP_Pin1_Pos_1_,=,CustomPin1Pos1,UILP_Pin2_Pos_0,=,CustomPin2Pos0,UILP_Pin2_Pos_1,=,CustomPin2Pos1**

[EventLP_Pin1_Pos_0]
...
add=_UILP_Pin1_Pos_1_
remove=_UILP_Pin1_Pos_0_

**Comment by scrubbless** [comment]
Unfortunately I don't think I can answer your questions.

As for locks only the picks need to be intractable, the rest if just for show. 

So I could create a background  image UI, that players could just insert their own image into. Then as long at the lock in the image is at a certain point (say, dead center) then the picks would line up.

That means the only interaction to change the default puzzle would be to replace the image in the uilp_background component.

**Comment by chrismaliszewski** [comment]
I'm not sure what you mean by the word "intractable". Did you mean interactive? 

I think it shouldn't be you who creates a BG image. Nor should you force a creator to put a lock in a certain point. 
I think you know what I meant previously but I'll give some examples now. What I'm trying to say is, some creators may like the image 
![image](https://user-images.githubusercontent.com/7532602/60961171-d2e98d80-a30b-11e9-98f2-254d4ad85d33.png)
others 
![image](https://user-images.githubusercontent.com/7532602/60961185-dda42280-a30b-11e9-80a9-448cdf8b9bec.png)
or 
![image](https://user-images.githubusercontent.com/7532602/60961205-e72d8a80-a30b-11e9-97f7-20838893113f.png)
Each of them has a different position of a lock. It may not be possible to put a lock in a point forced by you by design so it will look good. 
The best solution would be creating the module so it allows changing BG and position of the picks. Right now the latter is impossible because EventLP_PinX_Pos_Y events call adding and removing UILP_PinX_Pos_Y UI elements. It isn't that much of a problem if you have only one riddle of the kind as you just need to change BG and picks' positioning in ui.ini. The real issue here is creating 1> riddles of the kind during a game as the only solution to the problem at the moment is copping all events and modifying most of them for new elements. 

That's why I asked if the above idea of mine is possible. 

@scrubbless, if it isn't an easy task to do, what you already have created is great! I think a necessity to put a lock in the bg at a certain point is something that people can live with :). I just wanted to point out what would be the best solution.

**Comment by scrubbless** [comment]
> I'm not sure what you mean by the word "intractable". Did you mean interactive?

Interactive,  yes. Not sure where I got that other word!

I worry that if I make the module too customisable it will case confusion.

I think splitting out the background from the lock would be a good idea. Then give alternate background options, since the player could just rename them to update the aesthetic without manipulating the code.

If a more advanced user wants to make their own, it would be as simple as replacing the background image and then each of the lp_pin_* UI elements with their own images and moving them to the correct coordinates.

The rest of the code would remain intact and work.

**Comment by chrismaliszewski** [comment]
For some reason, I haven't thought about using CTRL+H option :). You're right, replacing UILP_PinX_Pos_Y with UICustomLP_PinX_Pos_Y and other texts for more advanced users shouldn't be a problem. 

So the only thing that might need to be done is either:
A. flattening a code so if a user wants to create multiple riddles they don't have to copy so many functions and looking for "what more should I do" 
**or** 
B. writing in the instruction that you want to create some tips which would explain "how to do sth", i.e.
1. How to create multiple lockpicks riddles? (with information which parts of the code should be copied/changed)
2. How to create different backgrounds for each riddle and where should you change the positioning of the picks?
3. How to set riddle's solution so it isn't random?
4. What should I do to use different picks in multiple riddles?
etc.

The second option should be less time-consuming than modifying your code and will serve the purpose.

**Comment by scrubbless** [comment]
I'll close this off for now. I'll add the code into the guide should anyone want it.

I'll look into a neater module, apparently I should be able to contain all of the module in one self contained file to be added to a scenario. So I'll work on that.
