### ISSUE TITLE
{MADXX} Symbols

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#1176]
The {MAD27} symbol for HJ does not seem to display the symbol, however its in the game files because it shows with tile references.

Does this have a different MAD number?

### Valkyrie Version
2.0.3

**Comment by redwolf2** [comment]
It is missing in the translation file...

https://github.com/NPBruce/valkyrie/blob/master/unity/Assets/StreamingAssets/text/Localization.English.txt

**Comment by redwolf2** [comment]
Fixed: https://github.com/NPBruce/valkyrie/pull/1177

**Comment by redwolf2** [comment]
The character  can be used as a workaround
