### ISSUE TITLE
A Glimpse of the Past. Rus translation Update

### ISSUE THREAD

**Issue by Ssid113** [NPBruce/valkyrie#1180]
[A.Glimpse.of.the.Past.zip](https://github.com/NPBruce/valkyrie/files/3413664/A.Glimpse.of.the.Past.zip)
Good day. @slycozzolino
Pls update scenario. Added voice, synopsys, authors_short

**Comment by vidimus** [comment]
Here is also the Spanish translation for this scenario to add it.
[https://github.com/vidimus/Valkyrie-Mom-scenarios-translations/blob/master/Localization.Spanish.txt](url)

**Comment by slycozzolino** [comment]
Ok ill take care of both of these. Thanks

**Comment by slycozzolino** [comment]
Updates are done.  You should be able to update your scenario with the changes soon.
