### ISSUE TITLE
D2E Shop Issues - missing item, item error, fame behaviour

### ISSUE THREAD

**Issue by Xyphistor** [NPBruce/valkyrie#1189]
### Description of Problem or Question
I'm testing a shopping stage for a campaign.
In the campaign initialisation I setup fame thresholds and party fame, for testing purposes I then show a button to add 20,000 gold at a time... Then you can choose to go to the shop.
The city-style shop has a restock button and a button to increase party fame to/past each threshold in turn, so I can test buying everything...

**First issue: missing items**
The following items do not seem to be present in the D2E shop:
Archaic Scroll (Shadow of Nerekhall)
Jinn's Lamp (Labyrinth of Ruin)
Mapstone (The Trollfens)

I guess Jinn's Lamp and the Mapstone don't work in the app and therefore shouldn't be there, but Archaic Scroll seems legitimate?

**Second issue: item error**
The Act II item 'Blessed Armor' is incorrectly shown as Act I

**Third issue: minimum fame error**
Potentially mostly caused by an error on my part... If you initialise fame like this:
operations=$%fameimpressive,=,2 $%famecelebrated,=,12 $%fameheroic,=,22 $%famelegendary,=,32 $%fame,=,0
then I have noticed that Valkyrie won't go anywhere near a shop - my call to the shopSubfolder/quest.ini just causes Valkyrie to stop (not crash, but Menu->Main Menu does nothing) without triggering the 'EventStart' trigger opening event within that subfolder quest...

That might be because at that point fame is indetermined - it could be Insignificant or Noteworthy and the app can't tell since those thresholds aren't set?
As I said, mostly user error but an interesting failure mechanism I thought was worth reporting :)

### Valkyrie Version
2.3.04

**Comment by Xyphistor** [comment]
In general I think there's something weird going on with shop items.
I don't think the minfame/maxfame is working - if I go into my shop with fame=2, when the insignificant threshold is 0 and noteworthy is 10, I only see one item (Magic Staff). That's the only item with a maxfame of insignificant...
If I then increase fame by 10 with my button in the shop, it breaks Valkyrie - I'm not sure it's finding any Noteworthy items...
If I get my fame up to the Heroic level, I can only buy 14 items - all the ones with maxfame set to Heroic... minfame doesn't seem to affect anything?

**Comment by NPBruce** [comment]
First issue:

This is from RtL data, I'm inclinded to leave it as-is.

Second issue:

Fixed in 2.4

**Comment by NPBruce** [comment]
Third issue:

Definately 2 bugs here that I have found and now looks better. Building as 2.4.01 now.

**Comment by DelphiDie** [comment]
Just to add to this: Archaic scroll is unavailable, because you have to return the card after using it, but there is no way to tell the game you used it, and to remove it from inventory in RtL. It might theoretically be possible to do this in Valkyrie by using the MoM item inspect mechanic, but this would feel out of place in the Descent module.
