### ISSUE TITLE
A glimpse of the past. Spanish translation update.

### ISSUE THREAD

**Issue by vidimus** [NPBruce/valkyrie#1192]
Hello,  @slycozzolino

I've updated my Spanish translation correcting some typos and adding the two in-game clues pictures with text already translated.

Please, update the files for the scenario. Thanks.

![cross](https://user-images.githubusercontent.com/41538948/62903019-afc65980-bd61-11e9-8b52-5ecb3f169b62.jpg)
![note](https://user-images.githubusercontent.com/41538948/62903020-b05ef000-bd61-11e9-9ec8-c609dadb9233.png)
[Uploading Localization.Spanish.txt…]()

https://github.com/vidimus/Valkyrie-Mom-scenarios-translations/blob/master/Localization.Spanish.txt

**Comment by slycozzolino** [comment]
Sorry for the delay.
Updated.

**Comment by slycozzolino** [comment]
I added the pictures, but I am unable to access the updated localization file. It just links back to this ticket. Could you provide a new link?

**Comment by vidimus** [comment]
Here's the file:
[https://github.com/vidimus/Valkyrie-Mom-scenarios-translations/blob/master/Localization.Spanish.txt](url)

**Comment by slycozzolino** [comment]
Thanks.
Uploaded.

**Comment by vidimus** [comment]
Hello, again, @slycozzolino .

I've updated the translation (minor corrections were made) and also the note picture (it was poorly translated and made one of the puzzles incomprehensible),

Files are here:
[https://github.com/vidimus/Valkyrie-Mom-scenarios-translations/blob/master/Localization.Spanish.txt](url)
[](https://github.com/vidimus/Valkyrie-Mom-scenarios-translations/blob/master/note.spanish.png
)
Thanks!

**Comment by slycozzolino** [comment]
Thanks. I will update it.

**Comment by slycozzolino** [comment]
Done

**Comment by vidimus** [comment]
Hello, @slycozzolino.
I've revamped my translation from "A glimpse of the past". Could you please update the scenario with the new translation?
The file is this:
[Localization.Spanish.txt](https://github.com/NPBruce/valkyrie/files/4770670/Localization.Spanish.txt)

**Comment by slycozzolino** [comment]
Updated
