### ISSUE TITLE
Create Package not putting files on desktop

### ISSUE THREAD

**Issue by jlederer2** [NPBruce/valkyrie#1195]
### Description of Problem or Question
Tried updating my scenario, A Little Night Music, today, but when I press "Create Package" in the editor, nothing happens.  No error, no files/folders placed on desktop.

I manually zipped the files, renamed to .Valkyrie, and uploaded to my repository on GitHub.  I incremented the version number (GUID?) in the existing copy of ALittleNightMusic.ini which I had, since I didn't know how to create that file manually.

Unfortunately, my scenario doesn't show the download icon in the scenario explorer, so it seems that Valkyrie is not recognizing that I have uploaded a new version on GitHub.

### Valkyrie Version
2.4.03

### Attach Save, Quest or Scenario
Log File:
%LOCALAPPDATA%Low\NA\Valkyrie\output_log.txt
Saves:
%appdata%/Valkyrie/MoM/Save
%appdata%/Valkyrie/D2E/Save
Quest:
%appdata%/Valkyrie/D2E/Editor
Scenario:
%appdata%/Valkyrie/MoM/Editor

**Comment by jlederer2** [comment]
Forgot - I'm on Windows 10, 64-bit.  I even tried running Valkyrie as an administrator, but Create Package is still not putting the files on my desktop.

**Comment by NPBruce** [comment]
I can't reproduce this.

Can you please upload a zip of the files you are trying to package?

**Comment by jlederer2** [comment]
Solved.  It was Windows Defender "Controlled Folder Access" being turned-on.  I turned it off and the Create Package function is working properly again.  Sorry :-)
