### ISSUE TITLE
Loading old scenario

### ISSUE THREAD

**Issue by mamantins** [NPBruce/valkyrie#1196]
Dear all,

I have a real stupid question.
I never ask myself how to do it, until... My computer fails. >_<

I still have access to the harddisk, how can I move a scenario from a computer to another? Is it possible? Did I loose all the progress?

Thanks a lot for your feedback.

Regards.
Mam's.

**Comment by NPBruce** [comment]
Everything is in %AppData%\Valkyrie.

This should be users\\<username\>\Roaming\Valkyrie

There are saves, downloaded content and editor content there. Just copy to your new location to get it back.

**Comment by mamantins** [comment]
Ok!
Thanks a lot!
