### ISSUE TITLE
'NoMorale' will not trigger an event

### ISSUE THREAD

**Issue by Liquidlogic1** [NPBruce/valkyrie#12]
I tried to create a 'lose' event (EventLose) with the NoMorale as a trigger, but the event will not occur when Morale = 0.

**Comment by NPBruce** [comment]
Can you please provide your quest ini file from the %AppData%/Valkyrie directory?  Ideally also the game log after this fault occurs.

**Comment by Liquidlogic1** [comment]
Here's the Quest.ini.   
https://www.dropbox.com/s/jmcp53flln7myh9/quest.ini?dl=0

 I didnt get a game log or fault. The event just wouldnt occur when I satisfied the NoMorale trigger condition.  

By the way, I posted a link to a Quest creation tutorial I made on BGG.  Here's the dropbox  link of that  file if you'd like to have a look:  https://www.dropbox.com/s/sazbz9gqw8swhx4/Valkyrie%202%20Room%20Quest%20Creation%20Tutorial.rtf?dl=0

**Comment by NPBruce** [comment]
You can upload files direct to this issue.  I have also made you a collaborator so you can edit the wiki here for documentation.

**Comment by NPBruce** [comment]
Works for me, however it should be noted that it doesn't trigger until morale drops below 0 (as per RtL).  I have clarified the documentation.  Also note that the event should be EventEndLose so that it triggers the end of the quest.

Reopen if you still have a problem.
