### ISSUE TITLE
Dynamic size of text frames

### ISSUE THREAD

**Issue by Sadgit-HL** [NPBruce/valkyrie#120]
Size of text frames for Events should be dynamic to roughly fit the displayed text.

**Comment by NPBruce** [comment]
It scales up but not down.  I can make the minimum size smaller but I like most dialogs being a consistant size.  If you write a lot of text it will get bigger.

Currently the minimum is 8 lines, perhaps this should go down to 5 or 6?  Thoughts?

**Comment by Sadgit-HL** [comment]
Many Events that I am using have only a single line of text.  At the moment often large parts of the map are hidden by empty parts of the text box. I do not like that. I understand that it might be nice to have a consistant text box size, however map visibility is more important in my opinion.

**Comment by NPBruce** [comment]
I have reduced it to 4 for the next release.  This allows:

Perform the following actions:

Do something

To fix nicely in  the new standard size.

**Comment by Sadgit-HL** [comment]
Great, thx
