### ISSUE TITLE
Scenario explorer, not showing any scenarios

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#1203]
![Screenshot_20190826-211703_Valkyrie](https://user-images.githubusercontent.com/32058089/63720373-ed89ae80-c846-11e9-8bdd-f2ac82c3eb89.jpg)
### Description of Problem or Question
The scenario explorer is not showing any scenarios in "online mode" have an internet connection.

### Valkyrie Version
2.4.02 - Android (bit suspect its windows too.

**Comment by NPBruce** [comment]
I can't reproduce this, perhaps there was a temporary server issue? Can you please try again?

**Comment by scrubbless** [comment]
Ita not working on my android phone, not had a chance to test windows yet.

Still a problem for me this morning.

**Comment by scrubbless** [comment]
Must be an issue with the previous version ok n.

2.4.02

Just uninstalled it, then deleted Valkyrie directory.  

Installed 2.4.04 and it works.

**Comment by scrubbless** [comment]
Same issue in 2.4.02 on windows:
![image](https://user-images.githubusercontent.com/32058089/63754008-0d06f280-c8ac-11e9-9124-2c9ca1ea1370.png)

**Comment by scrubbless** [comment]
A flat upgrade to 2.4.04 fixed the issue, seems to be a problem with 2.4.02. Did not delete the Valkyrie folder on windows.

![image](https://user-images.githubusercontent.com/32058089/63754218-666f2180-c8ac-11e9-89d4-4a7b19790530.png)

**Comment by NPBruce** [comment]
2.4.04 had a quest format bump. I haven't looked into how this works in the new system, but looks like it is going scorched earth.

This will be addressed with 2.5 anyway with #956
