### ISSUE TITLE
Feature request: Defeated monster confirmation

### ISSUE THREAD

**Issue by Xyphistor** [NPBruce/valkyrie#1206]
### Feature Request
Is it possible to add a confirm/cancel dialog when instructing the app that a monster group is defeated? This is the default behaviour in Road to Legend.

**Comment by NPBruce** [comment]
The general idea is that these additional confirmations are removed as Valkyrie has an Undo button. Most feedback I have to date is that this is preferred.

It would be possible to have it as a toggled option, but this will not be a high priority for me.

**Comment by Xyphistor** [comment]
My bad, completely forgot about the Undo button... That's definitely preferable, ignore this feature request!
