### ISSUE TITLE
Revamp Splash Screen

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#1208]
### Description of Problem or Question
I assume it would be possible to import the App splash screen images and place them as a background to the main screen? It would require moving some of the text and buttons but I think it would be worth it for the good initial impression.

Something like this maybe?

MoM2
![image](https://user-images.githubusercontent.com/32058089/64418054-2ff68b00-d092-11e9-82d5-f1252aa9d5a5.png)

Descent
![image](https://user-images.githubusercontent.com/32058089/64418956-d42d0180-d093-11e9-861e-944ba0166345.png)

I could find the images as .dds files for MoM in:
C:\Users\username\AppData\Roaming\Valkyrie\MoM\import\img\

But couldn't find the Descent splash, in its similar directory. But I assume it has to be in the content files somewhere.

**Comment by scrubbless** [comment]
Some options if we don't want to use the official artwork:
(Using Royalty Free Art)

MoM2:
![Splash](https://user-images.githubusercontent.com/32058089/64495342-a06afb00-d290-11e9-82b3-93752915817d.png)

Descent:
![Descent](https://user-images.githubusercontent.com/32058089/64495338-95b06600-d290-11e9-957d-1ed5b1ad1d81.png)

**Comment by BenRQ** [comment]
I really like the Royalty free for Descent.

For MoM, I like the design and color, also the evil crow :)
Just to mansion looks more like a castle IMO.

**Comment by scrubbless** [comment]
I agree, I liked the whole thing except the castle aspect. But looks pretty cool and it's hard to get clearly defined royalty free stuff without paying for stock.

**Comment by antontimmermans** [comment]
For MOM splashscreen there are some nice ones on https://wallpapercave.com/haunted-house-background. Examples (high-ress downloads available on the site):
![image](https://user-images.githubusercontent.com/42072372/65148043-b068a480-da1f-11e9-8551-0535ad729a71.png)
![image](https://user-images.githubusercontent.com/42072372/65148102-d0986380-da1f-11e9-8c43-6c2bafe861fc.png)
![image](https://user-images.githubusercontent.com/42072372/65148126-e1e17000-da1f-11e9-976a-0b0a62387d67.png)
And more...

The site suggests that all images are free of copyrights: They use the strategy that anyone can upload as long as it complies to police and rules.... and it will stay on the site as long a s nobody complaints.

**Comment by BenRQ** [comment]
The second mansion is the best IMO.
Nice find @antontimmermans :)

**Comment by Quantumrunner** [comment]
If the images from  https://wallpapercave.com are ok I would prefer this one for descent:

![grafik](https://user-images.githubusercontent.com/58113888/97088380-a5277580-1630-11eb-978c-ed41e961201b.png)


https://wallpapercave.com/w/uwp10758

**Comment by scrubbless** [comment]
That's very nice

**Comment by Quantumrunner** [comment]
I'm really not sure about the licensing situation here.

It seems nearly impossible to find the original source of the images even when using search engines like this one:
https://tineye.com/search/3112d12ff7139e601fe5bfe24d02a057ec61f6ef?sort=crawl_date&order=asc&page=2

**Comment by NPBruce** [comment]
I don't want to merge anything that doesn't have clear permission. Legally no licensing information means it cannot be used.

**Comment by BenRQ** [comment]
That's the original on the page of the author (checked the magic card there to see the name)
https://www.deviantart.com/sandara/art/Temeraire-66213180

Doesn't seem to be free of right though so we can't use it.
