### ISSUE TITLE
Scenario Arkham Crime Wave to be Published

### ISSUE THREAD

**Issue by NicolaZee** [NPBruce/valkyrie#1209]
Please can my new scenario Arkham Crime Wave be published?

It resides in the ArkhamCrimeWave folder in my GitHub Folder: https://github.com/NicolaZee/PublishedScenarios

Thanks in advance.

This version is Version 1.0 for release.  There is a feedback review of a very early test version. As it is a review of the scenario several months before it was ready to be released please can this feedback be deleted before publishing the release version.

**Comment by scrubbless** [comment]
Oooh new scenario! I'll add it as soon as o get a moment.

**Comment by scrubbless** [comment]
Ok, I've added it. I'll update the stats sheet later tonight.

**Comment by scrubbless** [comment]
It's up,

I like the ui elements when people talk! Would you mind if I used that idea?

**Comment by NicolaZee** [comment]
Imitation is the sincerest form of flattery.
I am inspired by others all the time.
The sharing of ideas is what makes Valkyrie as great as it is!
