### ISSUE TITLE
Shop Bug

### ISSUE THREAD

**Issue by AntonioFico** [NPBruce/valkyrie#1211]
### Description of Problem or Question

Shop find only three "Act1" object in D2E. Why?
![1](https://user-images.githubusercontent.com/55914827/65879699-ad12d880-e390-11e9-9e90-2712ade8cc80.jpg)
![2](https://user-images.githubusercontent.com/55914827/65879714-b4d27d00-e390-11e9-9958-1b1f0a473fde.jpg)

### Attach Save, Quest or Scenario
Log File:
%LOCALAPPDATA%Low\NA\Valkyrie\output_log.txt
Saves:
%appdata%/Valkyrie/MoM/Save
%appdata%/Valkyrie/D2E/Save
Quest:
%appdata%/Valkyrie/D2E/Editor
Scenario:
%appdata%/Valkyrie/MoM/Editor

**Comment by NPBruce** [comment]
This looks like a campaign issue rather than valkyrie, if there is no item available that matches the criteria you will get this.

Please attach a save game for confirmation.

**Comment by DelphiDie** [comment]
Hello Antonio,
it looks like you did some modifications to the shadow rune campaign, specifically the file "other.ini" in the subfolder "CP". Could you post the content of your version of this file? I could then try to reproduce the problem.

**Comment by AntonioFico** [comment]
How can i attach my files?

**Comment by AntonioFico** [comment]
Where do i find a saved game?

**Comment by AntonioFico** [comment]
When i found these problems i try to construct item for each object and then select it with some event but is too complicated...

i've not "Others.ini" in my campaign phase..

What is the Algorithm of chosing item in the shop?
 
[Localization.Italian.txt](https://github.com/NPBruce/valkyrie/files/3676118/Localization.Italian.txt)


[CampaignPhase.zip](https://github.com/NPBruce/valkyrie/files/3676137/CampaignPhase.zip)

**Comment by AntonioFico** [comment]
I found the saved game ".vSave" format... it is in this zip file.

Many thanks friends...

See you soon

Have a nice day

[SavedGame.zip](https://github.com/NPBruce/valkyrie/files/3676173/SavedGame.zip)

**Comment by DelphiDie** [comment]
Unfortunately I don't speak italian, so I'm not 100% sure what your events are trying to do. But adding items to the shop requires 2 things:

1. A place where an item is defined like your items.ini file.

Example:

```
[QItemExampleAct1]
itemname=QItemExampleAct1
starting=False
traitpool=act1

[QItemExampleAct2]
itemname=QItemExampleAct2
starting=False
traitpool=act2
```
2. An instance where the pre defined item is added to an event (Afaik if more than 1 item is added, Valkyrie will automatically create the shopping window).

Example:

```
[EventShop]
display=false
buttons=1
event1=EventContinue
add=QItemExampleAct1 QItemExampleAct2
```

The above code will produce random items, which fit the traitpools that are defined, and allowed by the current fame level of the heroes.

My interpretation of your file is, that you are trying to define a [QItem] entry for every single item in the game. While this is possible, I'm not entirely sure what you are trying to do with them. You seem to use a random number to decide whether a specific item is available at different fame levels.

Could you perhaps try to explain what you exactly intend to do?

**Comment by AntonioFico** [comment]
Yes DelphiDie but when i try ti add four (4) act1 object It Will show only three object and Will show only the same type...Also of fame Is at legendary level...try It yourself...

**Comment by AntonioFico** [comment]
I want to open shop showing only act1 objects

**Comment by NPBruce** [comment]
The save game does not match the images above. QItems only go up to 3 and the log doesn't have the errors.

**Comment by AntonioFico** [comment]
Yes NPBruce but Is only EN example...It Is not dependent on the "scenario" when i select more than three act1 object Valkyrie always show me only the three illustratore...and no others... No more (of i create 5 or 6 object form del QItem3 It dosen't find any object) and no other type...i tried in several ways...

**Comment by NPBruce** [comment]
Please attach a save of the actual fault so that I can determine where it has gone wrong.

**Comment by AntonioFico** [comment]
I post you some screenshot about:
- Resulting shop
- Log
- Event showing shop

And I will send you all the scenario.

Note: it always show only the same three act1 object...in the previous scenario as in the present one

![Shop](https://user-images.githubusercontent.com/55914827/66004292-bdb67200-e4a8-11e9-9377-1fcd0c4ecc4a.jpg)
![Log](https://user-images.githubusercontent.com/55914827/66004298-bee79f00-e4a8-11e9-99c6-65f2a503968f.jpg)
![Event](https://user-images.githubusercontent.com/55914827/66004302-c0b16280-e4a8-11e9-8c4b-dfb9306d5c99.png)
[Scenario.zip](https://github.com/NPBruce/valkyrie/files/3678662/Scenario.zip)
 

Help me....please

**Comment by NPBruce** [comment]
OK the problem is you have set $%famelegendary,=,0 and fame to 30, meaning you want only the best possible items, yet you are also restricting to act1.

Without a lot of expansions there just aren't many cards that match this.

I strongly recomment not using act1/2 for items at all. RtL doesn't do that, it uses the fame rating to rescale how good each item is for RtL and ignores the act entirely.

If you are interested you can see how items are rated here:

https://github.com/NPBruce/valkyrie/blob/master/unity/Assets/StreamingAssets/content/D2E/base/items.ini
