### ISSUE TITLE
Question - Max / Min Camera

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#1217]
### Description of Problem or Question
I am trying to understand what Max Camera actually does. I was hoping that it would automatically zoom the camera out, however it just doesn't seem to do that. 

When I set this, the camera just locks in position and ignores the next even that moves the camera.
![image](https://user-images.githubusercontent.com/32058089/67022973-f2a60400-f0f9-11e9-849b-ebf06e53155f.png)

The Wiki doesn't really elaborate on how this works or is used.
https://github.com/NPBruce/valkyrie/wiki/QuestIniEvent#mincam

Is there a way that I can zoom the camera out for an event? For example when placing more than 4 tiles.

### Valkyrie Version
2.4.06

**Comment by scrubbless** [comment]
Does this simply control the the Top/Right and Bottom/Left boundaries that the camera can move to?


                                       ___
                                           |




|__

**Comment by NPBruce** [comment]
"If set true the position of this event will be used to set a maximum (top/right) camera limit."

This is a position that the camera can't go past, so the user doesn't scoll into the abyss. Happy to accept a better description.

**Comment by scrubbless** [comment]
Ok thanks, yeh I see what was meant by that now. 

Is there a way to scroll the camera out on an event?

**Comment by NPBruce** [comment]
The zoom cannot be changed (there is a feature request for this somewhere).

**Comment by scrubbless** [comment]
Not a problem, thanks for the quick reply
