### ISSUE TITLE
{rnd:hero} in UI text doesn't function - Is it a bug?

### ISSUE THREAD

**Issue by AntonioFico** [NPBruce/valkyrie#1219]
### Description of Problem or Question
Excuseme if I bother you,

I insert {rnd:hero} to add some interactive character to an UI text but dosen't appear an hero name as during event: is it a bug or an expected behavior?

Many thanks

**Comment by scrubbless** [comment]
The ability to put {var:variable} was only added to UIs pretty recently, not sure what is identified for that.

**Comment by NPBruce** [comment]
Sounds like a bug, can you please provide a specific example (preferably with a save)?

**Comment by scrubbless** [comment]
Maybe it's because the function has to select a hero, usually done in an event dialogue.

A work around would be to call the hero in an event, then call the name from the event.

{c:EventName}

**Comment by AntonioFico** [comment]
NPBruce: do you want the game, the quest file or a screen shot?

scrubbles: I try it...many thanks

**Comment by AntonioFico** [comment]
For scrubbles: it function but before I must use a {rnd:hero} function in an event text showing an unwanted dialog box

**Comment by scrubbless** [comment]
Open the event.ini and change the visible=true tag on the event to visible=false.

**Comment by AntonioFico** [comment]
Great! 
I did not think about it!

Many Thanks Scrubbles!

**Comment by scrubbless** [comment]
Did you manage to do what you needed @AntonioFico?

@NPBruce will need an example of the error to test on.

Run your scenario then hit Save, then zip your scenario in the following directory:
%appdata%/Valkyrie/MoM/Editor
And pick up the save from:
%appdata%/Valkyrie/MoM/Save

Attach both of the files here.

The other option is to create a small example scenario to explain the bug, for example an even with a "StartEvent" trigger then place your UI with the {rnd:hero} function inside it. Zip that example scenario up from %appdata%/Valkyrie/MoM/Editor and then post it here. That way @NPBruce can simply run it and see right away the error and it'll make debugging a bit easier.

**Comment by scrubbless** [comment]
I'll close this off for now, it seems like you have a solution.
