### ISSUE TITLE
Looking for authors to translate their scenarios to Spanish language

### ISSUE THREAD

**Issue by keros17** [NPBruce/valkyrie#1223]
Hi,

I'm looking for scenario authors, mostly italian and english ones (the easiest for a spanish talker) to translate their campaigns/scenarios to spanish language and then upload it to increase the number of castilian ones in Valkyrie

If you are interested contact me or post on the issue so we can talk about it.

Thanks ;)

**Comment by scrubbless** [comment]
We've discussed translations of my scenarios. I'll share links to excel files for translations once I have exported them. 

Thanks @keros17 !

**Comment by NicolaZee** [comment]
I'm happy for you to translate Arkham Crime Wave to Spanish once the scenario has had several more plays recorded.
Currently there are only 19 plays recorded and a couple of comments are fairly negative,

**Comment by keros17** [comment]
Oh thanks. I was looking for authors interested in someone who translate their scenarios but the point was increase the spanish language scenarios to play so... If you as author wanna do it in a while it's perfect.

Thanks for the quick answer ^^

**Comment by antontimmermans** [comment]
Although I do speak some Spanish, but definitely not enough to make a proper translation. If you choose one of my scenarios for translation I will help you get started. I would love to see my scenarios translated into the language of my favorite holiday country :)

In case you want to do translations for "Chapel Down Manor", you can drop a ticket in https://github.com/antontimmermans/MOMCDM and we will get things started.

Same for "Disturbance at the Docks", but then in https://github.com/antontimmermans/MOMDATD

**Comment by keros17** [comment]
Hello anton,

thanks a lot for your help. I am alone with the translations for the moment so I must wait other people to join me and then we can manage different translations simultanously.

I will keep the contact with you and when I have the option I will tell you ^^

**Comment by matBonet** [comment]
Hello everyone, I am also interested into helping with translations, in my case from english/spanish/italian/french into brazilian portuguese. @keros17 could you send the links for me aswell?

Cheers

**Comment by keros17** [comment]
Hi mat,

I'm sorry but I can't. You have to contact to the author of each scenario and get access threw them to the translations (yes one by one).

That's why I wrote this issue. If you want to translate into brazilian open an issue on the main page asking for it and wait for the authors to answer you. 

Sorry but it's the only way =(

**Comment by antontimmermans** [comment]
A sheet with some (draft) google translations for the chapel down manor scenario is available for translations. Using this sheet, you don't need to have knowledge of Valkyrie.
Details can be found in https://github.com/antontimmermans/MOMCDM/issues/10

**Comment by vidimus** [comment]
I'm not a very active user lately, but I want to go on translating some scenarios into Spanish. I've finished "Il Rapimento" weeks ago, but I've not edited some pictures needed for the scenario. I hope I will during these days.
I've already got some lines translated from "Disturbance at the docks", so I can go on with it.

**Comment by keros17** [comment]
If you want to help with the translation (I just start with a very busy period of work in my job and slow down on it) I can try to contact with the owner of the campaign mode of MoM in Valkyrie and ask him to add you to the sheet

**Comment by antontimmermans** [comment]
A sheet with some (draft) google translations for the Disturbance at the Docks scenario is now also available for translations. Using this sheet, you don't need to have knowledge of Valkyrie.
Details can be found in https://github.com/antontimmermans/MOMDATD/issues/22

**Comment by keros17** [comment]
Sorry, I didn't see it xD

**Comment by scrubbless** [comment]
I've created a folder with google sheet(s) that require translation.

https://drive.google.com/folderview?id=1ktVuKAvWtAT7H0lcpEhyJUojoHLeEi7D

I will add files for translation as and when they are ready. Please create a column for the language you want to translate.

**Comment by vidimus** [comment]
> I've created a folder with google sheet(s) that require translation.
> 
> https://drive.google.com/folderview?id=1ktVuKAvWtAT7H0lcpEhyJUojoHLeEi7D
> 
> I will add files for translation as and when they are ready. Please create a column for the language you want to translate.

Hello.
I've translated a part of the text. There are about 400 text entries left. I got some doubts about some terms, so I will contact you privately to solve them.

**Comment by EtiCarasoft** [comment]
Hi @keros17 i participated in the translation of "The Truth" I can help you here. 
I found @scrubbless way amazing!! supper useful excel way. Can we help there?

**Comment by keros17** [comment]
Hola Joan,

em sembla que només has de ficar-te a l'enllaç que tens a sobre i demanar permís per a editar i podràs modificar el que vulguis i que quedi guarda't al word.

He rebaixat una mica el que podia fer per temes de feina però tot ajut serà benvingut ;)

**Comment by EtiCarasoft** [comment]
Perfecte!!
@scrubbless in spanish we use accent símbols. It will be necessary to insert has a text symbol "text with simbol in here".

**Comment by vidimus** [comment]
Chapel Down Manor scenario is finished. If you see any mistake, please tell me to correct it. Any feedback is welcome!

**Comment by vidimus** [comment]
Disturbance at the docks Spanish translation is ready. It needs some review to be send it to the author.
