### ISSUE TITLE
New Scenario - The Alpine Pass

### ISSUE THREAD

**Issue by GwanGwanish** [NPBruce/valkyrie#1224]

**Comment by scrubbless** [comment]
Sorry for the delay on this, has been a busy weekend! I'll add this now.

**Comment by scrubbless** [comment]
Ok it has been added to the manifest and spreadsheet:
![image](https://user-images.githubusercontent.com/32058089/69044631-245a0580-09ed-11ea-8794-06f117fe5cd2.png)

**Comment by GwanGwanish** [comment]
No problem.

Thanks!
