### ISSUE TITLE
Valkyrie not downloading or updating scenenarios

### ISSUE THREAD

**Issue by unilhexio** [NPBruce/valkyrie#1226]
Hi, from some weeks ago, I'm having problems downloading scenarios. The list of available scenarios is updated but when I try to download any of them, the screen only shows a message "Downloading package" and never ends.

I have Valkyrie updated and I have tried this in two differents computers. The problem is exactly the same in both of them.

Updating: it is related with my internet connection. Not very sure about what to do.

**Comment by scrubbless** [comment]
Check your windows firewall is not blocking the Valkyrie app from accessing the internet or downloading files.

Try turning off windows defender and the windows firewall and try again.

**Comment by unilhexio** [comment]
Thank you, scrubbless. I tried disabling windows firewall and defender too. I didn't work. Then I talked to my internet provider and they say that it may be related with CGNAT configuration.

**Comment by scrubbless** [comment]
Did your ISP fix it? CGNAT is carrier grade network address translation, so not something you can fix.

Very odd.

**Comment by unilhexio** [comment]
You're right, they changed CGNAT but it didn't do anything with this. I've tried with my cell phone data and it works with no problem, but when I connect to my optic fiber provider, then it happens the same "downloading" all the time...
The have opened an issue... Thanks, anyway!

**Comment by scrubbless** [comment]
Very strange, I assume you're not blocking any ports outgoing? I wonder if it's a content filter on the ISPs end.

**Comment by unilhexio** [comment]
No, I even disabled the windows firewall. Regarding to ISP, how could it be solved?

**Comment by scrubbless** [comment]
Have you checked your router firewall? 
You could also try a VPN, to tunnel out of your internet connection and hopefully bypass ny content filters.

Who is your ISP? It is a little strange that they are blocking or filtering your content.

Valkyrie is just the front end, when it collects the Scenario files it is simply making a HTTPS request to download a few files, a .ZIP file and .INI files. Commonly the scenarios are hosted on GitHub, which is a reputable site.

**Comment by unilhexio** [comment]
Yes, I disabled the firewall, windows defender... everything! My ISP is Masmovil-Pepephone (Spain). It is really strange, because I had this provider before (in another city) and I didn't have any problem. Evenmore, I have the same problem in two different computers so I discard that the problem would be any Windows configuration. I can download adn install Valkyrie, the scenario list is downloaded and then, when I try to download any of them... nothing (the secenarios icons are not downloaded neither).

Well, I'm downloading the scenarios by my 4G phone data or by coffe-shop free WiFis, for the moment.

**Comment by redwolf2** [comment]
Maybe it is your DNS server. You could try to change to Googles.
https://www.wikihow.com/Change-Your-Windows-DNS

**Comment by scrubbless** [comment]
That's  good idea, in your ethernet settings got to properties then ipv4 settings.

You can set you DNS servers manually. Try 8.8.8.8 for now, that's Google DNS.

**Comment by unilhexio** [comment]
Good idea, I will try it. Many thanks!

**Comment by unilhexio** [comment]
I was about to change my DNS... but now it seems to be solved, with no changes, Valkyrie is working normally after one month. I don't know what is happening with this...

**Comment by scrubbless** [comment]
It sounds ISP related, a networking issue of some kind or a content filter
