### ISSUE TITLE
Bug scenario items...

### ISSUE THREAD

**Issue by VartNabh** [NPBruce/valkyrie#1227]
### Bug scenario items...

Hello, I'm new here ...

I have a problem when I put an item in my scenario ...

Even by adding the right code in {c:QItemX} for example, when I test the scenario, the item completely changes to another that I haven't even added.

I don't know if this issue was reported here, or started due to the import of the new version of MoM into steam ...

Any solution?

Tys

**Comment by scrubbless** [comment]
If you select an item but have the category (aka weapon) it will randomly select an item from that category, excluding the item you select.

To get a static item that you select hit the red - next to the category (probably weapons in your situation).

**Comment by VartNabh** [comment]
Tys man, it worked here...

**Comment by scrubbless** [comment]
Happy to help, feel free to PM me on BGG (scrubbless) or @tag me on github if you need any help.
