### ISSUE TITLE
how can i load scenarios?

### ISSUE THREAD

**Issue by Dioscuri93** [NPBruce/valkyrie#1232]
Good morning, i've translate an scenario in Italian, now i want to load this scenario, in this way the other italian players enjoy too.
Then, how can i load this scenario?

**Comment by NPBruce** [comment]
Which scenario? Have you contacted the author? It is strongly recommended that translators collaborate with the scenario author, who will be able to work with you to include your work.

**Comment by Dioscuri93** [comment]
Exotic material, I don't know how can i contact the author.

Il gio 19 dic 2019, 20:54 NPBruce <notifications@github.com> ha scritto:

**Comment by scrubbless** [comment]
Can you post the localisation.italian.txt here please. I can add this to Exotic Materials (or Npbruce can).

**Comment by NPBruce** [comment]
Yep, I am the author and can add this.

**Comment by Dioscuri93** [comment]
Ok, but, where can i found the text file? 😅

Il ven 20 dic 2019, 01:14 NPBruce <notifications@github.com> ha scritto:

**Comment by NPBruce** [comment]
Probably easiest to use the editor to package the scenario, then post the whole package here.

**Comment by Dioscuri93** [comment]
Ehm, please, can you explain me step by step?
In scenario folder i found
Editorscenario.ini
Editorscenario.valkyrie
Emlogo.jpg

Il ven 20 dic 2019, 09:44 NPBruce <notifications@github.com> ha scritto:

**Comment by NPBruce** [comment]
I need the editorscenario.valkyrie file, you may need to add it to a zip to upload here. You can join the discord for general help with use and explanation, that will be much easier.

https://discordapp.com/invite/yrVeSVt

**Comment by Dioscuri93** [comment]
Give me a feedback👍

Il giorno ven 20 dic 2019 alle ore 10:10 NPBruce <notifications@github.com>
ha scritto:

**Comment by scrubbless** [comment]
Open the scenario in the Valkyrie editor, in the top right click "tools" then clock "Create package".

That will create a zip of your scenario on your desktop (in a new folder). Just zip that folder up (right click add to zip/compress). Open a reply on this github issue and drag (or select attachment), click your zipped scenario and attach it to these forums.

**Comment by Dioscuri93** [comment]
[EditorScenario23.zip](https://github.com/NPBruce/valkyrie/files/3988099/EditorScenario23.zip)

Pls give me a feedback 👍

**Comment by NPBruce** [comment]
Done.

**Comment by Dioscuri93** [comment]
But, did you upload the scenario?

Il sab 21 dic 2019, 10:41 NPBruce <notifications@github.com> ha scritto:

**Comment by NPBruce** [comment]
Yes, are you not able to see the update?

**Comment by Dioscuri93** [comment]
No no, i tried with PC and tablet but nothing😭

Il sab 28 dic 2019, 12:06 NPBruce <notifications@github.com> ha scritto:

**Comment by Dioscuri93** [comment]
Filtrars Is the problem, when i select the italian language the scenario
does not appear, i think because the italian flag Is missing. What do you
think?

Il sab 28 dic 2019, 12:20 Calogero Vassallo <vassallocalogero93@gmail.com>
ha scritto:
