### ISSUE TITLE
New Descent Scenario: City of the Dead

### ISSUE THREAD

**Issue by Quantumrunner** [NPBruce/valkyrie#1233]
I have finally been able to finish a new descent scenario. It's a single encounter.

https://github.com/Quantumrunner/ValkyrieCityOfTheDead

Could you please add it to the mission list?

Just as the shadow rune campaign it will get some minor changes (undead tags) if the a valkyrie update will be released someday.

I'll add more infos on BoardGameGeek as soon as the scenario is available in Valkyrie.

**Comment by scrubbless** [comment]
I'll get this added shortly

**Comment by Quantumrunner** [comment]
Looks good thank you.
