### ISSUE TITLE
Request to add new quest

### ISSUE THREAD

**Issue by Drake3** [NPBruce/valkyrie#1234]
### Description of Problem or Question
Please add the following quest to the list:
https://github.com/Drake3/MOM/tree/master/Cabin_in_the_Woods

Thank you!

### Attach Save, Quest or Scenario
https://github.com/Drake3/MOM/tree/master/Cabin_in_the_Woods

**Comment by scrubbless** [comment]
Awesome, I'll get thos added for you asap

**Comment by scrubbless** [comment]
Hi @Drake3 
The scenario has not been packaged, so I cant link it yet.

Inside the editor you will need to create a package from "Tools" > "Create Package".

Upload the .ini file and the .zip file to github (maybe just create a folder in your MoM repo) and send me the link.

**Comment by Drake3** [comment]
Thanks for the information. I was pressing this button a lot, but it never creates anything at least not at a place where I can find it. The manual is kinda fishy about where the file should be located. I guess in the scenario directory, but there it does not show.  Any other tips what could have gone wrong?

**Comment by scrubbless** [comment]
It drops the file on the desktop for windows. Unsure on linux, @redwolf2 may know.

**Comment by Drake3** [comment]
OMG. I got like 20 folders on the desktop.  Now try this one:
https://github.com/Drake3/MOM/tree/master/CabinInTheWoods

**Comment by scrubbless** [comment]
Adding the scenario appears to have broken the manifest. I've rolled back the change for now to try to fix that. May need to look into this more before adding the scenario as I am  ot sure if it's a wider issue.

**Comment by scrubbless** [comment]
Ok I have found out what the issue is.

Your quest.ini files default language is german, but the scenario only contains an english localisation file. The Scenario Explorer scans the localisation file to gather some information and is crashing because the german file its expecting to find is not present.

**Comment by scrubbless** [comment]
@Drake3 Can you please set your app language to English, then open the editor and create a new package.

Send me the link and I'll take a look to make sure the issue is corrected. If it's not I can talk you through the fix in the .ini files directly.

**Comment by Drake3** [comment]
Ok, turns out if you build the package with the right language on, it doesnt fix the quest.ini. Manually changed the file and rebuild the package. Hope its fine now:
https://github.com/Drake3/MOM/tree/master/CabinInTheWoods

**Comment by scrubbless** [comment]
Did you change the default language in the quest.ini prior to creating the package or after?

It's just a different quest.ini is also contained within the scenarui.valkyrie file. I suspect it will be fine now but just want to check.

**Comment by scrubbless** [comment]
Hi @Drake3 

The scenario is showing the Scenario Explorer now:
![image](https://user-images.githubusercontent.com/32058089/71977480-cab5d080-3210-11ea-8448-7de057add040.png)

It also downloads and runs:
![image](https://user-images.githubusercontent.com/32058089/71977520-e4efae80-3210-11ea-960a-510b9637fefb.png)

**Comment by scrubbless** [comment]
Just an early observation:

The Investigator icon does not get removed after you are told to place them.
![image](https://user-images.githubusercontent.com/32058089/71977578-0cdf1200-3211-11ea-8ac3-7568a97220f0.png)

**Comment by Drake3** [comment]
If I do an update, is it sufficient if I just replace the files on github or do I need to ask one of you guys to do it?
