### ISSUE TITLE
Missing translation file in quest crashes the scenario explorer

### ISSUE THREAD

**Issue by BenRQ** [NPBruce/valkyrie#1236]
As reported while trying to integrate a new scenario:

Your quest.ini files default language is german, but the scenario only contains an english localisation file. The Scenario Explorer scans the localisation file to gather some information and is crashing because the german file its expecting to find is not present.

_Originally posted by @scrubbless in https://github.com/NPBruce/valkyrie/issues/1234#issuecomment-571830963_

**Comment by redwolf2** [comment]
Fixed https://github.com/NPBruce/valkyrie/issues/1234#issuecomment-571903189
