### ISSUE TITLE
Unable to continue saved game (file attached)

### ISSUE THREAD

**Issue by mkhaar** [NPBruce/valkyrie#1237]
### Description of Problem or Question

After having been playing the attached save and deciding to load it a different day, it never seems to properly load. The screen turns black, main menu music stops and scenario music plays. The only option is to force close the app. Tested both on Android and PC.

### Valkyrie Version

Release v2.4.06 for Android (original playthrough) and also testing loading on PC, same version. 

### Attach Save, Quest or Scenario

Scenario: La llamada de Insmouth (Spanish one available on the app)
Saves: Linking it due to file size limit https://1drv.ms/u/s!Ai0W644ASh1u3qhlaoX9bvJdaNcvnw?e=ab10Ed

**Comment by BenRQ** [comment]
There was an issue in writing the save file it seems. Difficult to say what was the reason though ... Maybe full disk space ?
Here is the fixed savefile, so the monsters can eat you and finish diner: https://we.tl/t-xcbZklF2Mj

:)
