### ISSUE TITLE
Newbe Questions

### ISSUE THREAD

**Issue by Drake3** [NPBruce/valkyrie#1238]
Sorry if I spam this forum, but I have to simple questions and did not find any other way to ask them:

1) How is the comment that somebody leaves at the end of the scenario brought to the scenario developers attention?

2) What's the procedure for making an update to a puplished scenario?

Thanks for helping out.

**Comment by scrubbless** [comment]
1. The feedback is logged in a spreadsheet and then referenced in this spreadsheet:

https://goo.gl/xgxdMb

2. When you create a scenario you use the "Create package" button to generate a .ini file and .valkyrie file that are then published to a web server (aka a github repository).

The author can then make any changes to their scenario as they did first creating a the scenario, and create a new package. they then upload this and overwrite their previously published scenario.

**Comment by antontimmermans** [comment]
FYI: For scenario writer- or developer questions like this, you can also join the "Valkyrie app" channel on Discord.

**Comment by scrubbless** [comment]
@Drake3 has that answered your question or did you need some more information?

I'll close this Issue if you've got what you need :)

**Comment by scrubbless** [comment]
Closing this off as it's been 2 weeks with no response. Please feel free to continue commenting on this while closed I'll get an email notification.
