### ISSUE TITLE
New Descent Scenario: Bow before your king

### ISSUE THREAD

**Issue by Quantumrunner** [NPBruce/valkyrie#1239]
I have created another Descent mission:

https://github.com/Quantumrunner/ValkyrieBowBeforeYourKing

@scrubbless Could you please add it to the mission list?

**Comment by scrubbless** [comment]
Ok added should be there within the hour.

I'll add to the stats when I get to a PC :)

**Comment by BenRQ** [comment]
@scrubbless there is a tiny mistake in your change.
Proposed fix is here: https://github.com/NPBruce/valkyrie-store/pull/6

**Comment by Quantumrunner** [comment]
Thanks! I was already wondering why the scenario was not yet visible.

**Comment by scrubbless** [comment]
I missed the external again didn't I?

**Comment by scrubbless** [comment]
I need better QA! Haha. Fixed

**Comment by BenRQ** [comment]
I launched the script manually, it should appear now.

**Comment by scrubbless** [comment]
It's showing, thanks Ben.

**Comment by scrubbless** [comment]
@Quantumrunner I would recommend announcing you new scenario on BGG

**Comment by Quantumrunner** [comment]
I just did. I have added the infos to the already existing thread for "City of the dead":

https://boardgamegeek.com/thread/2334396/valkyrie-mission-city-dead
