### ISSUE TITLE
Portuguese/Brazil Translation

### ISSUE THREAD

**Issue by schena** [NPBruce/valkyrie#1242]
correct some things and add other portuguese translations
Put on ...Valkyrie\valkyrie_Data\StreamingAssets\text
[Localization.Portuguese.txt](https://github.com/NPBruce/valkyrie/files/4117398/Localization.Portuguese.txt)

**Comment by redwolf2** [comment]
I added a pull request https://github.com/NPBruce/valkyrie/pull/1243

**Comment by BenRQ** [comment]
Merged and delivered in 2.4.07
