### ISSUE TITLE
UI with vartext autoupdate possible

### ISSUE THREAD

**Issue by Niederboa** [NPBruce/valkyrie#1245]
Hi all.
Sorry, maybe it is already solved, but i can not find the information i need. And my english is not the best, hopefully it is understandable.

I'm trying to create a kind of combination lock with UI-Elements.
I have Two buttons (previous/next) and the actual "Number" for each position of the Lock.

The UI-Text writes the actual number, with {var:<variable>}. 
All fine, but, if i press a Button, i can change the value of the variable (in the log), but the Text is not updating. How can i, lets say, reread the value of the variable into the UI-Element?

Thank you a lot!

**Comment by Niederboa** [comment]
Well, after some additional tests, I know it would work with separate ui elements, for each number, but the update of the {var:<variable>} would be much more comfortable.

**Comment by scrubbless** [comment]
You need to remove the UI that contains the variable then place it again.

I usually do this in an event loop.

I have a module that has a custom lock pick puzzle that I can share. I'll attach an example scenario so you can inspect the code when I get to my computer.

**Comment by Niederboa** [comment]
I tried, but did not work for me, in the actual android version.
But, if it works for others, this topic can be closed, and I'll try further, and check the escape scenario. Maybe, I just do not see my mistake.

**Comment by scrubbless** [comment]
You must remove the UI in one event then add it again in a different event. I've found if you remove and add a ui in the same event it doesn't do anything.

**Comment by scrubbless** [comment]
@Niederboa did you have any luck with removing the UI in one event and then adding it in another?
