### ISSUE TITLE
New Mansions of Madness scenario "Saviors" - please link

### ISSUE THREAD

**Issue by ChinaMajesty** [NPBruce/valkyrie#1247]
### Description of Problem or Question
I have created a new (and my first) MoM scenario using Valkyrie and would like to share it out to the community.

https://github.com/ChinaMajesty/ChinaMajesty/tree/master

**Comment by scrubbless** [comment]
@ChinaMajesty 

I can't add this as the scenario name is 'EditorScenario13'.

Can you rename the folder "EditorScenario13" in %appdata%\valkyrie\MoM\Editor. Then create a new package from the editor and re-upload.

The folder name can not contain any spaces.

**Comment by ChinaMajesty** [comment]
I have changed the repository to "Saviors" and created a new package.
https://github.com/ChinaMajesty/Saviors

Thank you for looking at this!

**Comment by scrubbless** [comment]
Have you comitted the changes to the repo? It's empty for me

**Comment by jlederer2** [comment]
Looks like it's there as of 4 hours ago.

**Comment by scrubbless** [comment]
Oh yes, sorry I noticed and added it. I'll add to the  stats later today.
