### ISSUE TITLE
2.4.07a Pre-Release. Android blank screen

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#1250]
### Description of Problem or Question
When loading Valkyrie it prompt for storage permissions the first time, then goes to a blank screen.

Subsequent times it's run it shows the unity splash and then goes to a blank screen.

I am on a Samsung Galaxy S9+

### Valkyrie Version
2.4.0.7a Pre-Release

**Comment by redwolf2** [comment]
Have you allowed Storage Permissions? You can also set them under Settings > Apps > Valyrie

**Comment by scrubbless** [comment]
Yes, I said the exact same thing to someone on discord with the same issue haha.

It has permissions, it prompted and I check the app settings too.

**Comment by scrubbless** [comment]
Yes, I said the exact same thing to someone on discord with the same issue haha.

It has permissions, it prompted and I check the app settings too.

**Comment by Quantumrunner** [comment]
I still could not reproduce this. The release works fine for me on Lenovo Viva Tab Tablet and Lenovo Z Smartphone.

**Comment by scrubbless** [comment]
Galaxy S9+ here not working.

Unity logo appears
![Screenshot_20200215-190824_Valkyrie](https://user-images.githubusercontent.com/32058089/74593772-d9b94b00-5026-11ea-8af4-79126dd7ef8b.jpg)

Then goes to a black screen
![Screenshot_20200215-190831_Valkyrie](https://user-images.githubusercontent.com/32058089/74593775-e3db4980-5026-11ea-8d4f-b66c75735a98.jpg)



Someone else reported the same issue and it spontaneously cleared up. The app has storage permissions.
![Screenshot_20200215-191204_Permission controller](https://user-images.githubusercontent.com/32058089/74593800-12f1bb00-5027-11ea-9141-eb50da9ccec3.jpg)

**Comment by scrubbless** [comment]
![Screenshot_20200215-191007_Discord](https://user-images.githubusercontent.com/32058089/74593815-416f9600-5027-11ea-8954-34cba478f85d.jpg)

**Comment by scrubbless** [comment]
Could anything have been missed on the build? I remember reading that android required a module or a plug in?

**Comment by Quantumrunner** [comment]
Nope. The wiki does not mention anything special except for:
- Android Studio
- Android build tools 28.0.3
- Open JDK 1.8.0 212-3 

And this is installed on my build machine.

But I'm gonna check the build logs again if I can find anything.

**Comment by scrubbless** [comment]
Just tossing around ideas :)

**Comment by Quantumrunner** [comment]
Could be a signing problem:

>>> Signer
      X.509, O=Valkyrie Project, CN=Valkyrie Project
      [certificate is valid from 10/22/18 10:09 PM to 2/22/18 11:09 PM]
      [Invalid certificate chain: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target]

**Comment by Quantumrunner** [comment]
@BenRQ  gave me access to the Valkyrie Crashyltics logs (which are now part of firebase) which contains this error:

![grafik](https://user-images.githubusercontent.com/58113888/74595807-645d7280-5046-11ea-893d-55300b4ba10c.png)


```
Non-fatal Exception: java.lang.Exception
UnauthorizedAccessException : Access to the path "/storage/emulated/0/Android/obb/com.fantasyflightgames.rtl" is denied.
```

For some reason the app is not able to read the data from the other apps.

**Comment by dewinduvae** [comment]
Same problem. Bu I have build 2.4.06 screen just goest blank. Tried uninstalling an reinstalling ad it doesn't fix the issue

**Comment by Quantumrunner** [comment]
Did you open the official apps at least once?
Do you have both apps installed?
Did you try scrubbles workaround (https://github.com/NPBruce/valkyrie/issues/1250#issuecomment-586632118)?

**Comment by dewinduvae** [comment]
I'm going to go through the list of what I've tried to see if anything would fix the black issue. I am not a programer and I'm not sure what might be helpful but I'm hoping that something in this list does help
I have a galaxy S10+
1) valkyrie open without any other app open that I can see (black)
2) valkyrie open at the same time as Madness2 app (black)
3) restart phone. Open Madness2. Close once I see no updates. Open Valkyrie (black)
4) start valkyrie and leave ipen for an hour, roughly (black)
5) double check storage permission. (Matches image on the github thread exactly aside from language)
6) reinstall the app using latest saved apk on my phone (Valkyrie-android-2.4.06.apk) (black)
7) go through steps 1-3 again incase something changed (black)
8) backup and delete editor scenarios and open valkyrie (black)
9) reinstall and open valkyrie at this point (black)

**Comment by Quantumrunner** [comment]
Very weird.

I can find your errors in the firebase error logs:

![grafik](https://user-images.githubusercontent.com/58113888/77150931-392ad080-6a95-11ea-80c3-f3846fe86fa6.png)

It was the same error all the time (13 times).

This definetely is something regarding the import step. Looks like it is trying to find files from Descent (`content/D2E`) which it does not find. @dewinduvae  You did not have the descent app installed at all did you?

@NPBruce  Did anything from 2.4.05 to 2.4.06 change in the import logic?

**Comment by dewinduvae** [comment]
@Quantumrunner no, I've never had the descent app installed on this device.

**Comment by scrubbless** [comment]
Just an FYI seems to work fine on Windows for me. 
Just android that goes to a blank screen when opening.

I have noticed a similar issue with apps that try to load "Google Play Games" when there is intermitant internet connectivity (for example Clash of Clans). But I have a solid and stable WiFi connection when opening this Valkyrie. 

To reproduce, I would recommend. Uninstalling Valkyrie, then delete the Valkyrie Directory from the root of internal storage (this will clear all content etc). 
Then install from scratch.

I wonder if its an issue accessing the internal memory to create the Valkyrie folder and content?

**Comment by dewinduvae** [comment]
I have now tried to reproduce the error without success.
I have:
1) deleted valkyrie at root level.
2)installed the alpha 2.4.06.apk
3)deleted at root level an installed 2.4.07.apk
4)installed path to glory and imported
5)deleted the Descent folder in valkyrie

I have not yet gotten a blank screen while starting up.
I can say that I deleted valkyrie at root level between steps 9&10 in my earlier list and that I've never done that as a part of updating valkyrie before.
Also, I'm fairly sure I've updated valkyrie while on the train (atrocious WiFi) at some point earlier in the year

**Comment by scrubbless** [comment]
Have you got MoM2 installed?

**Comment by dewinduvae** [comment]
Yes, MoM2 was refered to as Madness2 in the list.

**Comment by scrubbless** [comment]
Ok this seems to be just the S9+ or maybe an OS version. 
I installed it on BlueStacks (an android emulator) and it works fine.

Very strange, i'll dig out some old phones and see if I can reproduce the error on them.

**Comment by scrubbless** [comment]
HTC One M8 works fine
Galaxy S7 works fine too.

I am wonder if it's a resolution thing? With the larger screen?

**Comment by Quantumrunner** [comment]
I think this is because on the newer android version checking for the data of other apps somehow fails.

The error from your tries I have found in the logs where quite clear:

https://github.com/NPBruce/valkyrie/issues/1250#issuecomment-586645057

**Comment by scrubbless** [comment]
Odd I'll try reinstalling it.

**Comment by scrubbless** [comment]
Uninstalled MoM2 it loaded fine. Reinstalled MoM2 from play store, black screen again.

Not really sure where to go from here.

**Comment by Quantumrunner** [comment]
Me neither. :(

I can see the error in the logs again (if this was your device this afternoon?):

![grafik](https://user-images.githubusercontent.com/58113888/77693363-7ff25c00-6fa8-11ea-8b7c-e34fcf77695f.png)

The current error will take some time until it is visible in the logs.

**Comment by scrubbless** [comment]
The app has full storage permissions read and write.

I can see and open the folder referenced.
![Screenshot_20200326-203041_My Files](https://user-images.githubusercontent.com/32058089/77693860-f5f2c500-6fa0-11ea-92f0-0e3456ea5565.jpg)
![Screenshot_20200326-203129_My Files](https://user-images.githubusercontent.com/32058089/77693870-fa1ee280-6fa0-11ea-948d-3ff136448d8d.jpg)

**Comment by scrubbless** [comment]
Any thoughts @NPBruce @redwolf2 @BenRQ ?

**Comment by BenRQ** [comment]
Yes I think this is thanks to this new feature in Android 10: "Scoped storage"

There is an easy workaround though but it requires a new build.
https://forum.unity.com/threads/android-10-and-scoped-storage-missed-features-in-unity-2019.749333/

I don't have a android 10 phone device at home to test this though.

**Comment by Quantumrunner** [comment]
I'll try to add this to the manifest of the 2.4.07a version.

**Comment by scrubbless** [comment]
Cheers @BenRQ 
Happy to test whenever a test release is available.

**Comment by Quantumrunner** [comment]
I have added the workaround property to the [manifest file](https://github.com/Quantumrunner/valkyrie/commit/eec661f993e5481a363030f9d618fb5794275e16). I hope this was the correct one because there are multiple manifest files in the solution. Looks like one for each plugin used?

@scrubbless Please give it a try. I have overwritten the files in the release:

https://github.com/Quantumrunner/valkyrie/releases/tag/prerelease%2F2.4%2Fv2.4.07a

**Comment by scrubbless** [comment]
Well down guys, you cracked it. It's working on the new build!

@BenRQ @Quantumrunner

**Comment by Thorsz** [comment]
Hi,  I'm getting the same issue with 2.51
