### ISSUE TITLE
New scenario

### ISSUE THREAD

**Issue by Mudiver77** [NPBruce/valkyrie#1251]
Hello,

I'm trying to create my first scenario on Valkyrie. I'm following this awesome guide : https://docs.google.com/document/d/1Gi5gTwKkw84Px0Lvk-bJ3Aml_vF3ZoljjB6a8FjWGt8/edit#

A step says that I have to create an issue to request that my scenario be linked to the Valkyrie Application. I'm note sure I quite understood it but here is the link.

https://github.com/Mudiver77/Scenarios

Many thanks in advance ... And sorry if that's not the way.

**Comment by scrubbless** [comment]
Thanks! I need to update some bits in the guide and add more.

You've done it correctly. Post here with a link to your packaged scenario. I'll add it now. Should be live in under an hour (the Google scrips to publish run on intervals).

**Comment by scrubbless** [comment]
Sorry within an hour of now, I apparently didn't ckic commit

**Comment by Mudiver77** [comment]
Nice! Thank you very much !

**Comment by scrubbless** [comment]
The scenario is live, but you didnt change the Valkyrie language when you wrote it so it's showing as English, but you've not written it as such.

**Comment by Mudiver77** [comment]
Thanks !
Yeah i noticed ... I will try to change that right away.

Le dim. 16 févr. 2020 à 09:52, scrubbless <notifications@github.com> a
écrit :

**Comment by scrubbless** [comment]
I am not sure if you could do it in the editor, you may be able to change the app language and then repackage. But I think the default language is set on creation.

You may have to do it the manual way in the code. :)

**Comment by Mudiver77** [comment]
Yeah, I went to the editor, changed the language, repackaged it, but it did
not work ...
How can I change that now ?

Le dim. 16 févr. 2020 à 10:01, scrubbless <notifications@github.com> a
écrit :

**Comment by scrubbless** [comment]
I edited my earlier post, but see you're working through email, here it is.


You will have to change the default language in the quest.ini.

And maybe edit the name of your localisation file. I'd need to have a look at the files to advise.
Do you have a repo with your unpackaged scenario? If so could you show me the path so I can look at the .ini files.

I think you'll need to do this:

Open your scenario folder in
%appdata%\valkyrie\MoM\editor<yourscenario>

Rename the Localisation.English.txt file to whichever language you are have written the scenario in. I.e. localisation.Spanish.txt.

Then open the quests.ini and change the entry for localisation.english.txt to the language above i.e. localisation.Spanish.txt

Then change the default language of the scenario.

I.e.
default=Spanish

**Comment by Mudiver77** [comment]
I followed your instructions and it's still not changing the language.
The only link I can provide you is this one, I don't have a repo with an
unpackaged scenario. But I found everything you told me to edit, and did
so, but there's still a U.K flag on my scenario in the app
https://github.com/Mudiver77/Scenarios/blob/master/RituelsImpies/RituelsImpies.ini




Le dim. 16 févr. 2020 à 10:22, scrubbless <notifications@github.com> a
écrit :

**Comment by scrubbless** [comment]
Your changes appear to have broken the scenario. The manifest can't pick up the data from your ini files so it's stopped displaying the scenario list!

I've just removed your scenario for now.

I have a copy of your scenario on my phoneif I get some time later I'll have a look at converting the language for you and send you the updated files.

**Comment by Mudiver77** [comment]
Yeah I noticed, I deleted everything, will come back at it later. Don't
worry about it.

Le dim. 16 févr. 2020 à 11:25, scrubbless <notifications@github.com> a
écrit :

**Comment by Mudiver77** [comment]
I reuploaded everything on Github but I think it's still completely broken.
Here are some screenshots of what I did following the instructions you gave
me, if it can help in any way, which I doubt.

I'm really sorry for the disturbance, if that's too much trouble, I'll just
forget about it and leave you be !

**Comment by scrubbless** [comment]
I am out today but I'd be happy to help you fix it when I have some time later :)

**Comment by Mudiver77** [comment]
This is very, very nice of you. Thank you very much.
Here is the link to the scenario I re-uploaded yesterday after the "bug"
:   https://github.com/Mudiver77/Scenarios

To be honest I have absolutely no idea of what to do right now in order to
fix this mess

Le dim. 16 févr. 2020 à 12:16, scrubbless <notifications@github.com> a
écrit :

**Comment by scrubbless** [comment]
Ok I have work out the issue.

You need to change the default language in the Quest.ini and then the localisation.english.txt to localisation.french.txt.

But also need to change the language inside the localisation file to French otherwise it just creates a new file.
![image](https://user-images.githubusercontent.com/32058089/74659229-d9869000-518b-11ea-95bd-8a81aed147a8.png)
to french
![image](https://user-images.githubusercontent.com/32058089/74659209-d2f81880-518b-11ea-8e29-a2bd9eede69a.png)

Here are the files, if you'd pefer just to copy them over:
[Localization.French.txt](https://github.com/NPBruce/valkyrie/files/4214060/Localization.French.txt)

You'll need to delete the .txt off the end as it won't let me upload a .ini
[quest.ini.txt](https://github.com/NPBruce/valkyrie/files/4214063/quest.ini.txt)

Or here is the fixed scenario as a zip file, just extract it to you Editor folder
[RituelsImpies.zip](https://github.com/NPBruce/valkyrie/files/4214067/RituelsImpies.zip)

**Comment by Mudiver77** [comment]
Thank you again so much i_i
I extracted the zip into the editor folder, I did not want to fail and
cause another mess !
I also pushed this corrected version into my Github

Le lun. 17 févr. 2020 à 14:47, scrubbless <notifications@github.com> a
écrit :

**Comment by scrubbless** [comment]
Hi @Mudiver77 

You'll need to extract the zip to your %appdata%\valkyrie\mom\editor folder and use it to publish a new scenario. The publish the package that is created

**Comment by Mudiver77** [comment]
Jeez, I'm sorry, I'm so dense ...
It's done !

**Comment by Mudiver77** [comment]
Yikes, sorry, I'm just too dense.
It's done !

**Comment by scrubbless** [comment]
Not at all, it's new ground. Don't worry about it!

**Comment by scrubbless** [comment]
Ok published again! Let's see how this goes

**Comment by scrubbless** [comment]
Ok looks good, it's showing in the lists and is the correct language! I'll close this issue off.

**Comment by scrubbless** [comment]
@Mudiver77 have you made the repo private or deleted it? Your scenario repository is no longer assessable. I get a 404 and it's generating errors in Valkyrie.

I've removed it from the manifest list for now to avoid it causing problems.

**Comment by scrubbless** [comment]
It's been a week so assume you just don't want it published any more. Please reopen the case or open a new case to publish it again.

I'll remove it from the stats sheet also as to not confuse anyone.
