### ISSUE TITLE
Pre-Release: 2.4.07c

### ISSUE THREAD

**Issue by Quantumrunner** [NPBruce/valkyrie#1252]
I have created a Pre-Release Version for a new Valkyrie Release containing the following changes.

https://github.com/Quantumrunner/valkyrie/releases/tag/prerelease%2F2.4%2Fv2.4.07c

Testing would be highly apprecciated.

# Changelog:

* #1244 SOA - Minor Misspellings Person Tokens 
* #1243 Portuguese lang update
* #1228 Added "undead" trait to all undead monsters and "monster" trait to all monster
* #1225 Mad28: Path Of The Serpent
* #823 Improving the usability of random monster groups
* #1250 2.4.07a Pre-Release. Android blank screen
* #1265 New Feature: Turn off default music when starting a quest

**Comment by jlederer2** [comment]
Checked the PoTS tiles.  All present and accounted for...except that the Campsite which is on the reverse of "Hall Chamber 2" is missing - Hall Chamber 2 is "linked" to an older Campsite tile from a previous expansion (not sure which) instead.

**Comment by jlederer2** [comment]
Added all of the new items (not spells) and made them starting items.  None of the pictures showed up in the starting items list when I ran the scenario.

**Comment by jlederer2** [comment]
All common and unique items present and accounted-for, as are new spells and tokens (I did not check the person tokens)...once I remembered to add the new expansion under "Select Content" in Valkyrie :-)

**Comment by scrubbless** [comment]
> Checked the PoTS tiles. All present and accounted for...except that the Campsite which is on the reverse of "Hall Chamber 2" is missing - Hall Chamber 2 is "linked" to an older Campsite tile from a previous expansion (not sure which) instead.

There is a camp on CoTW probably that one.

**Comment by scrubbless** [comment]
Sadly the trigger for defeatedSpawns does not work in MoM.

Here is an Example, that spawns a monster and has two events that display text, one that triggers when the spawn is defeated and the other using the "unqiue" of the spawn option. Neither events run.
[TestSpawn.zip](https://github.com/NPBruce/valkyrie/files/4415235/TestSpawn.zip)

Monster spawned
![image](https://user-images.githubusercontent.com/32058089/78139764-e8b25c00-7420-11ea-86a6-01bbc39a5eb6.png)

Defeated monster, no diaglogue
![image](https://user-images.githubusercontent.com/32058089/78139910-1d261800-7421-11ea-88ed-0f7e502c75fe.png)

**Comment by Quantumrunner** [comment]
Yep I can reproduce this. I'll need to debug this to find out why it's not working.

**Comment by Quantumrunner** [comment]
Already found it. The update was only done for the Descent logic and not for the MoM logic.

But before I build it again and release it one question:

Can a spawn ever be unique? Or does the unique trigger for the spawns not make any sense at all because it does not exist?

**Comment by scrubbless** [comment]
Unique has no function in MOM. Monsters are individual entities not groups.

**Comment by Quantumrunner** [comment]
Ok then I'll try to remove the "Unique" stuff from the MoM UI completely.

**Comment by Quantumrunner** [comment]
All done. I have created a new release. See first updated post.

**Comment by scrubbless** [comment]
Just ran a couple of scenarios through and they work. Will have a play around in the editor tomorrow and retest that spawn trigger (which I am looking forward to! Should be very helpful and save creating a ton of custom monsters).

**Comment by scrubbless** [comment]
The DefeatedSpawn trigger works now, well done @Quantumrunner 

Spawn monster:
![image](https://user-images.githubusercontent.com/32058089/78276559-1c69b080-750b-11ea-986d-53036f72c1d5.png)

Defeat monster
![image](https://user-images.githubusercontent.com/32058089/78276584-24c1eb80-750b-11ea-8c01-fa5bcc8ba560.png)

**Comment by scrubbless** [comment]
@NPBruce @BenRQ 
Would you guys have any objections to publishing this?

**Comment by Quantumrunner** [comment]
Added new release 2.4.07c to add logic for disabling default music (#1265)

**Comment by BenRQ** [comment]
Official version 2.4.07 has been released, thanks again @Quantumrunner @redwolf2 for the work on this !
https://github.com/NPBruce/valkyrie/releases/tag/release%2F2.4%2Fv2.4.07

**Comment by jlederer2** [comment]
Thanks to everyone who helped!

Jim Lederer
248-482-3668

**Comment by scrubbless** [comment]
Thanks guys! Really appreciate it. Looking forward to updating my scenario POS placeholder events with actual content now.

Though does mean I have to revisit my old scenarios to exclude PoS items from some of the drops !

Also thanks for those that help test.
