### ISSUE TITLE
First Encounter: Castle Daerion

### ISSUE THREAD

**Issue by juakinaki** [NPBruce/valkyrie#1253]
Hi!! Thanks for this great job. Yesterday I started Shadow Rune and it was amazing. I would like comment a possible bug. I was playing the first encounter of Castle Daerion , when I lighted the last beacon (Condition Victory), Valkyrie said me that I had won this encounter and I had to note information about gold, villagers, health, etc.. for the next encounter. The trouble is that it doesn't transition to the second encounter,  Valkyrie continue with the first encounter when I already won. For change to the second encounter I have to continue playing I told to the aplication that any villagers is alive. Then Valkyrie told me that I lost the encounter and It changed to the second encounter

### Valkyrie Version 2.4.0
[output_log.txt](https://github.com/NPBruce/valkyrie/files/4209622/output_log.txt)
6

**Comment by Quantumrunner** [comment]
This can be closed for now. We discussed this on [boardgamegeek](https://boardgamegeek.com/thread/1754892/article/34066968#34066968).

> Thanks for the answer. In this case, it isnt ver important because I simulate that failed the mission and I continued with the second chapter. Mayte I lost some gold but that is irrelevant.In fact, I win the second encounter because I saved three villagers. Then I continued with cardinale suplice misión and it worked perfect.

I hope there won't be any more blockers.
