### ISSUE TITLE
Custom audio and music problems

### ISSUE THREAD

**Issue by mursuliini** [NPBruce/valkyrie#1255]
### Description of Problem or Question
Atmosphere music starts automatically on the first event of my Custom Scenario. All added music or audio files play on top of Atmosphere 1. How can I disable all default sounds/music? 

Second problem: My custom audio files don't play at all. If I select them for the introduction text event it still only plays Atmosphere 1 (which I never even selected for any event).

### Valkyrie Version

2.4

**Comment by redwolf2** [comment]
What did you do to fix your problem?
