### ISSUE TITLE
No real issue, just wanted to reach out to NPBruce and couldn't find a contact

### ISSUE THREAD

**Issue by absrdst** [NPBruce/valkyrie#1257]
### Description of Problem or Question

Hello! I'm sorry to be using this to try to reach out, but I just can't seem to find another way.

I would like to speak to @NPBruce about something regarding his game Valkyrie, and potentially working on something. Anyone know how?

**Comment by redwolf2** [comment]
We have a Discord. He is quite active there.

https://discordapp.com/invite/yrVeSVt

**Comment by NPBruce** [comment]
For a casual conversion discord is best.
