### ISSUE TITLE
Please upload 'In the Dark (5.0)' from a new folder

### ISSUE THREAD

**Issue by NicolaZee** [NPBruce/valkyrie#1258]
As part of a major rewrite of 'In the Dark' version 5 is now stored in the following Github folder.

https://github.com/NicolaZee/PublishedScenarios/tree/master/InTheDark

Please can the location in the manifest be edited so that it loads the scenario from the new folder?

Thanks in advance.

**Comment by scrubbless** [comment]
I've updated this, sorry for the delay!
