### ISSUE TITLE
Double :: in some editor fields

### ISSUE THREAD

**Issue by antontimmermans** [NPBruce/valkyrie#1261]
### Description of Problem or Question

Minor cosmetic issue: 
In editor screen the texts Min Duration, Max Duration and Difficulty have a double **::**
![image](https://user-images.githubusercontent.com/42072372/76834110-e058ff00-682c-11ea-9212-30039bb501ed.png)

### Valkyrie Version
2.4.06

**Comment by BenRQ** [comment]
Will be in 2.4.10
