### ISSUE TITLE
Question: Is it possible to make custom Mythos events?

### ISSUE THREAD

**Issue by bbstucco** [NPBruce/valkyrie#1264]
### Description of Problem or Question

Is it possible to make custom Mythos events?

### Attach Save, Quest or Scenario
Log File:
%LOCALAPPDATA%Low\NA\Valkyrie\output_log.txt
Saves:
%appdata%/Valkyrie/MoM/Save
%appdata%/Valkyrie/D2E/Save
Quest:
%appdata%/Valkyrie/D2E/Editor
Scenario:
%appdata%/Valkyrie/MoM/Editor

**Comment by scrubbless** [comment]
Yes it is.

Instead of enabling $mythosX just creat an event with the trigger "Mythos"

That event wi run at the mythos phase.

Personally I use one event for mythos events and then put all of my mythos events under it with a random order.

**Comment by scrubbless** [comment]
I will close this issue for now, feel free to respond if you need any more assistance or an example.
