### ISSUE TITLE
Add new Scenario

### ISSUE THREAD

**Issue by Drake3** [NPBruce/valkyrie#1266]
Guys,

I have a second scenario ready for upload. The files can be found here:

https://github.com/Drake3/MOM/tree/master/Main_Street_Market

I hope everything is in order. Let me know if something needs fixing.

Thanks a lot!

**Comment by scrubbless** [comment]
Sorry I completely missed this, i'll get his added today :)

**Comment by scrubbless** [comment]
Apparently I added it the other day 🤣 but just forgot to comment here or close the issue.
