### ISSUE TITLE
Do we need to download a new version of Valkyrie to get the Path of the Serpent material?

### ISSUE THREAD

**Issue by bbstucco** [NPBruce/valkyrie#1267]
### Description of Problem or Question

I see where it has been said that Path of the Serpent has been added to Valyrie. I do not see it, even when I reimport content. Do I need to download an entirely new version of Valkyrie?

Thanks!

### Attach Save, Quest or Scenario
Log File:
%LOCALAPPDATA%Low\NA\Valkyrie\output_log.txt
Saves:
%appdata%/Valkyrie/MoM/Save
%appdata%/Valkyrie/D2E/Save
Quest:
%appdata%/Valkyrie/D2E/Editor
Scenario:
%appdata%/Valkyrie/MoM/Editor

**Comment by scrubbless** [comment]
Path of the Serpent content has been added to Valkyrie in Beta, but has not yet been released. It is awaiting review, but has tested well thus far.

**Comment by bbstucco** [comment]
That's great! Will we need a new version when it's ready, or will it simply add when we next to do Reimport Content?

**Comment by scrubbless** [comment]
A new version of Valkyrie will be released and you will have to install that version on your device. You may need to reimport data from the official app, depends when you last did that.

**Comment by scrubbless** [comment]
I'll close this off for now, more information to follow on the new version :)
