### ISSUE TITLE
Insalled on IMac with Sierra - not working

### ISSUE THREAD

**Issue by eimerich** [NPBruce/valkyrie#1269]
### Description of Problem or Question
Hi I've just dowloaded the latest version on Valkyrie on my IMac with Sierra. When I try to launch the app (Mansions of Madness from Steam is already present), I receive the message: "Impossible to open the application Valkyrie.app".
I don't know why
Can you help? 
Thanks a lot.

### Valkyrie Version
2.4.06

**Comment by BenRQ** [comment]
Hi,

Please check the answer in this closed issue:
https://github.com/NPBruce/valkyrie/issues/1214#issuecomment-555707105
