### ISSUE TITLE
Lost City X'Ghonol - a quest for Descent

### ISSUE THREAD

**Issue by brunothesatellite** [NPBruce/valkyrie#1270]
### Description of Problem or Question
Hi I'd like to add a new quest for Descent in the Valkyrie listing.
The quest is hosted in this github repository: https://github.com/brunothesatellite/xghonol

### Valkyrie Version
2.4.06

### Attach Save, Quest or Scenario
Quest editor files:
https://github.com/brunothesatellite/xghonol/tree/master/xghonol-beta-editor
Quest package:
https://github.com/brunothesatellite/xghonol/tree/master/xghonol-beta

Cheers,
Bruno
brunothesatellite@gmail.com

**Comment by scrubbless** [comment]
Hi Bruno, i've added the scenario the the manifest, should we it in the list with in the hour :), I have also added it to the stats sheet but it won't a rating until its had feedback.

I am curious about the "beta" denotion in the folder name, is the Quest completed?

**Comment by brunothesatellite** [comment]
> I am curious about the "beta" denotion in the folder name, is the Quest completed?

Hi, thanks for the add. Don't worry for the '-beta' in the quest folder name, I just forgot to remove it. The quest is totally completed and I tested it with my friends so it should be fine.

**Comment by scrubbless** [comment]
Not a problem at all, just be aware that the path there is absolute so if you change the name in a later release it will most likely break the quest listings!
