### ISSUE TITLE
question publication scenarios

### ISSUE THREAD

**Issue by Ceraludo65** [NPBruce/valkyrie#1271]
Bonjour
J'ai 2 scenarios à publier en français sur valkyrie pour MoM. Pouvez-vous me donner la procédure pour partager mes créations?
Merci
Ceraludo65 

### Attach Save, Quest or Scenario
Log File:
%LOCALAPPDATA%Low\NA\Valkyrie\output_log.txt
Saves:
%appdata%/Valkyrie/MoM/Save
%appdata%/Valkyrie/D2E/Save
Quest:
%appdata%/Valkyrie/D2E/Editor
Scenario:
%appdata%/Valkyrie/MoM/Editor

**Comment by BenRQ** [comment]
Salut @Ceraludo65
Tu dois créer un nouveau repository sur Github avec ton/tes scénarios.
Tu peux prendre l'exemple de Scrubbless ici qui gère ses différents scénarios ici: https://github.com/scrubbless/PublishedScenarios

Si tu veux que je te guide plus précisement, n'hésite pas à venir me voir sur le discord de l'application: https://discordapp.com/invite/yrVeSVt

**Comment by Ceraludo65** [comment]
Merci BenRQ
Je viens de publier mon premier scenario "L'étrange maison dans le
brouillard". Merci d'être indulgent😉
Petite question : voilà plusieurs jours que le logiciel Valkyrie me refuse
l'accès aux scenarios publié avec le message "MODE HORS LIGNE (erreur
réseau)". Sais-tu pourquoi?

**Comment by BenRQ** [comment]
Alors, deux petites choses à changer:
1) est ce que tu peux éviter les espaces dans le nom du dossier? Cela évitera les erreurs lors de l'ajout de ton scénario dans la liste.

2) Ensuite est ce que tu peux renommer le dossier dans lequel tu édites ton scénario et générer à nouveau un package?
Cela permettra de générer un nouveau package avec un nom "unique" (les fichier . valkyrie et les .ini).
Et c'est ce qui identifiera ton scénario et te permettra de retrouver les retours des joueurs quand ils te laisseront des commentaires.

Quand tu auras fait ça, tu pourras créer une nouvelle "issue" pour demander l'ajout de ton scénario dans la liste. Il faudra indiquer l'URL.


> Petite question : voilà plusieurs jours que le logiciel Valkyrie me refuse
> l'accès aux scenarios publié avec le message "MODE HORS LIGNE (erreur
> réseau)". Sais-tu pourquoi?

Il y a des chances que ton application n'ait pas accès à internet.
Tu es sur Android, Windows, iOS?

**Comment by BenRQ** [comment]
@Ceraludo65 Est ce qu'on peut publier ?
Je vais utiliser cet URL:
https://github.com/Ceraludo65/Scenario-publie/tree/master/maisonbrouillard

**Comment by Ceraludo65** [comment]
Salut BenRQ
Tu peux publier sans problème
a+

**Comment by Ceraludo65** [comment]
Au fait, j'ai toujours un problème pour avoir accès à internet avec
Valkyrie sous windows ( "MODE HORS LIGNE (erreur
réseau)"). Est-ce que tu aurais une astuce?

**Comment by BenRQ** [comment]
Hi @scrubbless can you please publish this scenario when you have some time ?

Here is the link:
https://github.com/Ceraludo65/Scenario-publie/tree/master/maisonbrouillard

I've done a quick test and everything looks good.

**Comment by BenRQ** [comment]
@Ceraludo65 

J'ai fait un test rapide (sans lire les textes pour ne pas me spoiler). Le scénario à l'air de bien fonctionner avec pas mal d'élément de jeu, c'est cool :)

Je vois juste un petit problème sur la fin: les monstres couvrent l'image que tu affiches, voir l'image ci dessous.
Tu devrais peut-être tuer les monstres dans cet event pour qu'on voit l'image complète?

Et il faudrait un tout dernier bouton dans cet écran pour terminer le scénario: ce bouton mettrait la variable $end à 1.

C'est ce qui permettra aux joueurs de te laisser un petit message.

![image](https://user-images.githubusercontent.com/40794717/80404240-30fa5800-88c1-11ea-8db8-d581c1f4e5b2.png)

> j'ai toujours un problème pour avoir accès à internet avec Valkyrie sous windows

Je vois pas trop, à part un problème de firewall peut-être ?
Si tu me contactes sur Discord, je pourrais sûrement t'aider.

**Comment by scrubbless** [comment]
Hi @BenRQ 

I'll get that added now.

**Comment by BenRQ** [comment]
Thank you Scrubbless I can see the scenario :)

**Comment by BenRQ** [comment]
@Ceraludo65 ton scénario est publié!

Si tu veux mettre à jour ton scénario pour les joueurs, tu n'as qu'à remplacer ton fichier sur github avec la dernière version.

**Comment by Ceraludo65** [comment]
Ok merci BenRQ

**Comment by BenRQ** [comment]
@Ceraludo65 si tu rajoutes le $end comme indiqué, tu pourras retrouver les commentaires des joueurs ici : https://docs.google.com/spreadsheets/d/1OsevlouIvR0DRYhGIS41PU9lBLB8VYgJvyj9KsHcAik/edit#gid=517646170
