### ISSUE TITLE
Missing temple wall tokens in MoM Valkyrie 2.4.07

### ISSUE THREAD

**Issue by Litas-86** [NPBruce/valkyrie#1274]
The temple wall tokens from The Path of the Serpent are missing in this update.

Valkyrie Version: 2.4.07

**Comment by scrubbless** [comment]
Can confirm, not showing in PotS tab (nor unfiltered with all content selected):
![image](https://user-images.githubusercontent.com/32058089/79802239-867db480-8357-11ea-9419-ce479a19a901.png)

**Comment by redwolf2** [comment]
I will check that out this evening.

**Comment by redwolf2** [comment]
Sry for the delay. The temple wall token is not part of the current MOM assets (it dont seem to be used in any scenario ATM). I will have to recreate it.

**Comment by scrubbless** [comment]
That's odd,  sure it's used in all three scenarios.

**Comment by redwolf2** [comment]
My guess is, they directly use the graphics from the original tile, like Tile_Verdant_Chamber_MAD28 for the wall with vines.

**Comment by BenRQ** [comment]
It's now merged, soon to be released
