### ISSUE TITLE
New Scenario

### ISSUE THREAD

**Issue by flopez86** [NPBruce/valkyrie#1275]
Hi there, I'm not a coder, I try to did my first sceario! Hope it will be fine, even if I couldn't link an image during the entrance!
Thanks
Fabio

### Description of Problem or Question
https://github.com/flopez86/HolyMansionScenario

### Attach Save, Quest or Scenario
Log File:
%LOCALAPPDATA%Low\NA\Valkyrie\output_log.txt
Saves:
%appdata%/Valkyrie/MoM/Save
%appdata%/Valkyrie/D2E/Save
Quest:
%appdata%/Valkyrie/D2E/Editor
Scenario:
%appdata%/Valkyrie/MoM/Editor

**Comment by scrubbless** [comment]
Hi @flopez86, 

I can't publish your scenario as it is, unfortunatly the scenario name is the default "EditorSenario1" which is in use.
![image](https://user-images.githubusercontent.com/32058089/80216717-650e1880-8636-11ea-8e26-d1b70f98215e.png)

You will need to change the name of this (cannot include spaces).

The easiest way to do this is open the Valkyrie Editor folder:

%appdata%\Valkyrie\MoM\Editor\

In there you'll see the scenario folder "EditorScenario1" or "Scenario1". Just rename that folder to something else without spaces.

Then open the scenario in Valkyrie Editor and repackage it. You'll notice the folder name, .ini and .valkyrie files will have a new name. Remove this version from your GitHub and copy in the new one, then let me know :)

**Comment by flopez86** [comment]
Hi,
thanks for your kind reply. It's my first project =)!
I found the folder now I try to correct everything!
Thanks

Fabio

**Comment by scrubbless** [comment]
No worries, shout if you need some help :)

**Comment by flopez86** [comment]
So, I should have changed it,
I'm not sure if I have to post this link
https://github.com/flopez86/HolyMansionScenario

Or the other one
https://github.com/flopez86/HolyMansionScenario/tree/master/HolyMansion

Hope this fine it worked well!
Thanks again =)
If this time works, I'll ask many questions to improve 
Fabio

**Comment by scrubbless** [comment]
Thats great, thanks @flopez86 !

I've added this to the manifest, you should see it in the lists within the hour.
I'll also add it to the stats sheet when I get some time, its on the administration tab for now as a reminder to add fully.

I'll close this off for now, please feel free to post any questions or reponses on this issue if required.
