### ISSUE TITLE
Save Location of Quest Editor Files for Mac

### ISSUE THREAD

**Issue by CalvinoBalvarino** [NPBruce/valkyrie#1276]
This isn't really a problem, but where do the Quest Editor Files save for Valkyrie on a Mac? I know for PC they're located in Local App Data, but I am not sure where to find them on MacOS. Sorry for the simple question, just haven't been able to find it myself. Thanks in advance!

Valkyrie Version 2.0.47

**Comment by NPBruce** [comment]
Try either ~/.config/NA/Valkyrie or ~/.config/Valkyrie

**Comment by CalvinoBalvarino** [comment]
I’ve tried looking there already, but to no avail. 

Essentially gone down these files paths:

MacHD/users/(myname)/library(hidden folder and normal)/application support

MacHD/users/(myname)/library(hidden folder and normal)/caches

MacHD/users/(myname)/library(hidden folder and normal)/preferences


The only file oath to yield and Valkyrie data is: 

MacHD/users/(myname)/library(hidden folder)/saved application state

which yielded saved game data not quest editor data. 

Any other ideas?

**Comment by NPBruce** [comment]
Did you find .config? '.' directories are hidden by default on unix systems, I'm not sure how to get to it on MacOS. Also save game data is in the same place as editor data, what did you find in saved application state?

**Comment by CalvinoBalvarino** [comment]
I was unable to find the .config on my Mac. 

The saved Application State has 3 files: 2 .data files and a .plist

On my pc, i haven’t saved a game file yet, but my editor file saves as “EditorQuest#”

**Comment by NPBruce** [comment]
You haven't found the save games. Try again to find ~/.config, it should exist on your system (I have never used MacOS, so I can't help much more).

**Comment by EtiCarasoft** [comment]
I had the same problem I founded it by Player.log:

/Users/"yourUserHERE"/.config/Valkyrie/MoM/Editor/"YOURSCENARIOHERE(wrong_name=escenarioeditor1)"/"documentshere"

**Comment by CalvinoBalvarino** [comment]
Hey y’all. I never was able to find the files, but I do appreciate your time and help anyway!

**Comment by MatthewThornton** [comment]
In case anyone is still wondering how to do this. 

You have to view hidden files on a Mac. Command + Shift + . (full stop/period)

1. Use Finder, go to /users/"yourUserName"/
2. Command + Shift + . (full stop/period)
3. You will now see a darker greyed out files and folders. Go to .config

<img width="449" alt="Screen Shot 2021-04-09 at 9 18 33 AM" src="https://user-images.githubusercontent.com/973184/114211395-6ef75d00-9915-11eb-833c-5ceeac6641d4.png">
