### ISSUE TITLE
Chapel Down Manor - Localized to Portuguese

### ISSUE THREAD

**Issue by Revokee** [NPBruce/valkyrie#1277]
Here is the file for Chapel Down Manor from Anton Timmermans (not sure what is his github account)

[Localization.Portuguese.txt](https://github.com/NPBruce/valkyrie/files/4566434/Localization.Portuguese.txt)

I'll add the voices as soon as possible.

**Comment by antontimmermans** [comment]
Thank you very much for the translation.

The progress of the translation file integration will be recorded on that ticket.

This ticket may be closed.
