### ISSUE TITLE
Update Old Scenario

### ISSUE THREAD

**Issue by mamantins** [NPBruce/valkyrie#1278]
Dear all,

someone here wake me up. (^_^)
I have a translation to add on my scenario. (How to Create scenario)
I guess I succeed most of the steps.

But before to go further I have some questions:
-  A year ago, I saved all my scenario assets in external harddrive then I change my PC! Means, I have "lost" the scenario in Valkyrie application. It was build with Valkyrie Version 1.6.1
How can I load it back in? ==> Maybe I just found it, by copying my scenario from the app.

- How can I had a "review request" at the end of the scenario?

Thanks a lot for your help!

Mam's

**Comment by NPBruce** [comment]
If the scenario lost is published you can copy it in Valkyrie, if not dump it in %appdata\valkyrie\MoM\Editor

The review is automatic for published scenarios.

**Comment by scrubbless** [comment]
To get feedback you have to end the scenario correctly. I've not checked your scenario but make sure that you have an event after it finishes that sets the $end variable to 1 this will cleanly end the scenario and prompt the players with the feedback screen.

**Comment by mamantins** [comment]
Seams the scenario does not end properly.
i will correct it tomorrow. :)
Thanks for the help.
Mam's
