### ISSUE TITLE
MoM scenario "L'étrange maison perdue dans le brouillard": Looking for the author.

### ISSUE THREAD

**Issue by vidimus** [NPBruce/valkyrie#1280]
Hello.

I would like to contact with the creator of this scenario in order to make a few comments and a request for a future translation into Spanish.

**Comment by BenRQ** [comment]
@Ceraludo65 that's for you, someone wants to translate your scenario.

**Comment by vidimus** [comment]
Thanks, @BenRQ 
I will try to contact him on his repository.
I close this issue.
