### ISSUE TITLE
Doubts Valkyrie Statistics

### ISSUE THREAD

**Issue by DaniMassaro** [NPBruce/valkyrie#1286]
Hi. A couple of weeks ago I created a game of Mansions of Madness for Valkyrie (Sucesos Paranormales) and successfully uploaded.

In the statistics, opinions, etc. web document (https://docs.google.com/spreadsheets/d/1OsevlouIvR0DRYhGIS41PU9lBLB8VYgJvyj9KsHcAik/htmlview#) my game does not appear in the General Graphs section. Why?
And in the Document Administration section it appears in the right column.
I do not know why some parts appear to the left with Yes and others to the right, most of them with No. My game goes to the right but does not say No or Yes. I do not know why.

Thanks in advance.

**Comment by scrubbless** [comment]
Hi @DaniMassaro , this document is manually maintained. I have added the scenario to the sheet, but I have not added it to the ratings list, when I added it to the sheet it didn't have any ratings (0 ratings give a null error which breaks the chart).

I review it occasionally but not had a chance yet! I'll take a look later today and get it added. The rating will still show in the scenario explorer so the rating is visible to players in app 

From a quick glance I can see that the scenario has 11 pays and a respectable 4/5 rating!

**Comment by DaniMassaro** [comment]
I can see the individual comments (spoilers) but not my game in General Graphs. I hope to appear soon on it!

I thought it was automatically maintained and had done something wrong in creating the game.

Thank you so much for everything!

**Comment by scrubbless** [comment]
Not a problem, no it's just little ole me here typing away! I'll close this case down and get your stats added tomorrow (ran out of time today!)
