### ISSUE TITLE
New Scenario for Descent

### ISSUE THREAD

**Issue by GabroDonuts** [NPBruce/valkyrie#1287]
Hello guys, i've created a new scenario for Descent.

Name: Il grano di Torlomeke

Link: https://github.com/GabroDonuts/IlGranodiTorlomeke

Could you please add it to the mission list?

**Comment by scrubbless** [comment]
Hi @GabroDonuts 

I can't publish a mission that has the generic name (EditorScenario)

![image](https://user-images.githubusercontent.com/32058089/82425781-e6fb3100-9a7e-11ea-9161-bb14ebbe8af4.png)

Its quite straightforward to fix this.

Open:
%AppData%\Valkyrie\D2E\Editor

Rename your scenario folder (it cannot contain spaces).

Create the package again, and commit it to your repository.

**Comment by GabroDonuts** [comment]
How can i do it on a mac?

**Comment by scrubbless** [comment]
I am not sure what the path is for MAC I'm afraid.

@redwolf2 @NPBruce 

Do you know the location?

**Comment by NPBruce** [comment]
~/.config/NA/Valkyrie

**Comment by GabroDonuts** [comment]
ok, thanks. 
I fixed it. It should be ok now. 
https://github.com/GabroDonuts/IlGranodiTorlomeke

**Comment by GabroDonuts** [comment]
I've updated my file. Sorry! Could you please upload the new one?

https://github.com/GabroDonuts/IlGranodiTorlomeke

**Comment by scrubbless** [comment]
Once it is linked, as long as you don't change the scenario name (e.g. the path to the .ini / .valkyrie files) it will automatically show with an update to players. It can take up to 1 hour for the Scenario Explorer to show that a scenario needs updating if its downloaded.

**Comment by scrubbless** [comment]
I will close this issue off, but please feel free to reply to the post and @ mention me (i'll get an email notification).
