### ISSUE TITLE
A Glimpse in the Past in Portuguese - Update

### ISSUE THREAD

**Issue by Revokee** [NPBruce/valkyrie#1289]
A Glimpse in the Past had localization issues, at least 40% of the quest was not localized.

The BR Team jumped in, reviewed the old localization and did the remaining 40%

Here is the file: 
[Localization.Portuguese.txt](https://github.com/NPBruce/valkyrie/files/4662304/Localization.Portuguese.txt)

Does anyone knows how can we find SlyCozz?

Thanks!

**Comment by scrubbless** [comment]
@slycozzolino would you be willing and able to add this translation?

@Revokee the repo that this scenario is hosted on is here:
https://github.com/slycozzolino/valkyrie-store/tree/master/MoM/A_Glimpse_of_the_Past

Its a forked version of the main Valkyrie store.

**Comment by Revokee** [comment]
Hmm I cannot open issues there.

@slycozzolino Could you please help us?

**Comment by slycozzolino** [comment]
Hey
Sorry i missed these emails. Updating now.

**Comment by vidimus** [comment]
@Revokee I think you should close this issue, don't you?

**Comment by vidimus** [comment]
@scrubbless this issue was solved long time ago, and it looks lije @Revokee is missing.
