### ISSUE TITLE
In Places Unseen in Portuguese

### ISSUE THREAD

**Issue by Revokee** [NPBruce/valkyrie#1290]
In Places Unseen was localized.

File: [Localization.Portuguese.txt](https://github.com/NPBruce/valkyrie/files/4663028/Localization.Portuguese.txt)

**Comment by scrubbless** [comment]
@LordPyrex 

Are you happy for me to commit this translation and update your scenario to 2.4.007 format?

**Comment by LordPyrex** [comment]
Sure, I've considered the format update. It's been awhile since I've updated it.

**Comment by scrubbless** [comment]
Great, thanks @LordPyrex 

I've added added the Portuguese translation and updated the format to 13. If there are any issues let me know and i'll roll it back :)

**Comment by scrubbless** [comment]
@LordPyrex if you do want to make any changes or updates, feel free to post an issue with the new scenario file and i'll update the repo for you. Otherwise you can host it yourself on your GutHub and i'll remove this version and link yours in the manifest :)

**Comment by scrubbless** [comment]
Sorry this is my mistake, I thought it was hosted within the Valkyrie store, it looks like @LordPyrex hosts this himself.

The manifest references:
external=https://raw.githubusercontent.com/LordPyrex/valkyrie/master/InPlacesUnseen/

@LordPyrex I have added the Portuguese translation and created a package for format 13:
[InPlacesUnseen.zip](https://github.com/NPBruce/valkyrie/files/4667687/InPlacesUnseen.zip)

Could you either publish this to your repo above, or add the Portuguese localisation file for your publication?

**Comment by LordPyrex** [comment]
Will do, thank you. I forgot that it was in my repo. I'll add the language
file this afternoon.

**Comment by LordPyrex** [comment]
I've updated the files and they appear to be working on my end. Closing this thread, please reopen/let me know if there are any other changes that need made on my end,

**Comment by scrubbless** [comment]
Showing for me too and can see the translation
