### ISSUE TITLE
Zadoc Allen -> Zadok Allen

### ISSUE THREAD

**Issue by antontimmermans** [NPBruce/valkyrie#1293]
Both Token name and name on the token spell Zadok's name with a c
it should be with a k:

the name should be: **Zadok Allen**

**Comment by redwolf2** [comment]
I did the changes

![zadok_allen_token](https://user-images.githubusercontent.com/4141621/82733470-53db2900-9d14-11ea-96e2-2da6b3524461.png)

**Comment by BenRQ** [comment]
Merged
