### ISSUE TITLE
Valkyrie 2.4.08 Major performance issues and missions don't load

### ISSUE THREAD

**Issue by Quantumrunner** [NPBruce/valkyrie#1295]
### Description of Problem or Question
Valkyrie 2.4.08 is completely broken. Performance is horrible (both in Descent and MoM mode) and starting any missions is not possible (both in Descent and MoM). This happens when I start a MoM mission:

![grafik](https://user-images.githubusercontent.com/58113888/82750689-00b7b380-9db2-11ea-9505-620e0acf5829.png)

### Valkyrie Version
2.4.08

### Attach Save, Quest or Scenario
Tried this in Windows 10.
Can be reproduced with any scenario.

**Comment by BenRQ** [comment]
Fix available in v2.4.09
