### ISSUE TITLE
New Scenario: Smugglers Point

### ISSUE THREAD

**Issue by antontimmermans** [NPBruce/valkyrie#1296]
New scenario: "Smugglers Point"

It is a relative simple scenario intended to get acquainted with Valkyrie tokens, items, inventory puzzles. It is playable with 1-3 investigators.

Repository for this scenario is located at:
https://github.com/antontimmermans/MOMSP

**Comment by scrubbless** [comment]
Sorry for the delay Anton not been checking GitHub today.

I've added the scenario, it should be in the lists within the hour.
