### ISSUE TITLE
Offline (network error)

### ISSUE THREAD

**Issue by janinko** [NPBruce/valkyrie#1297]
### Description of Problem or Question
There is problem on Fedora 32 getting online cause by:
`Curl error 77: Error reading ca cert file from /etc/ssl/certs/ca-certificates.crt`
When I created symlink to /etc/ssl/certs/ca-bundle.crt it worked:
`sudo ln -s  ca-bundle.crt /etc/ssl/certs/ca-certificates.crt`

### Valkyrie Version
2.4.08

**Comment by BenRQ** [comment]
Hi @janinko ,

thanks for sharing this solution.

Do you think there is anything we should/can do on Valkyrie side?
It looks like a known issue on Fedora or unity: https://forum.unity.com/threads/issues-with-unity-hub-on-fedora-30.767687/

**Comment by janinko** [comment]
Sorry no idea if something can be done on Valkyrie side or not.

**Comment by BenRQ** [comment]
OK thanks for the solution then :)
Closing this one.
