### ISSUE TITLE
New Scenario

### ISSUE THREAD

**Issue by strategywizard** [NPBruce/valkyrie#1298]
I think this is the correct link I am supposed to copy.

https://github.com/strategywizard/Searching-for-a-Friend

Also, I can't figure out how to add a thumbnail image for the scenario.  Where would I save the image so it can be accessed in the Valkyrie scenario editor?

Thank you!

**Comment by scrubbless** [comment]
I'll take a look tomorrow, sorry for the tardiness!

**Comment by strategywizard** [comment]
Thank you!

**Comment by scrubbless** [comment]
Hi @strategywizard 

Youc an save the image in %appdata%\Valkyrie\MoM\Editor\EditorScenario1

On that subject, your scenario has the generic auto generated name so I am unable to publish it as it stands.

To fix this just rename "EditorScenario1" (the name cannot contain spaces) in the location above (%appdata%\Valkyrie\MoM\Editor\), once you've done that open up Valkyrie and open your scenario in the Editor and use the tool to "Create Package". You'll notice that he exported scenario folder now has your scenarios new name. 

Move that to your local GitHub repo to publish as you have with this one.

**Comment by scrubbless** [comment]
I've updated the "Publishing your scenario" section of the guide to better explain how to do this.
https://docs.google.com/document/d/1Gi5gTwKkw84Px0Lvk-bJ3Aml_vF3ZoljjB6a8FjWGt8/edit#heading=h.5cpbiphzxju0

**Comment by strategywizard** [comment]
Thanks for the help, but I just can't find that folder to save my life.  I've searched in my C drive for %appdata% (my view options show "hidden items" checked), EditorScenario1, and other ways, but I just can't seem to find it.  Where exactly is this folder located?  I feel like I must be missing something obvious, but I can't figure out what that might be . . . .  Sorry for being so clueless on the matter (pun not intended).

**Comment by scrubbless** [comment]
Just type %appdata% into your windows explorer, its a windows shortcut name for your roaming profile.

c:\users\<username>\appdata\roaming\valkyrie\MoM\Editor

**Comment by strategywizard** [comment]
Ok, I think I got it.  Thanks for making it easy for a noob!

Here is the new link.  Let me know if I need to do anything else for this to be publishable.

https://github.com/strategywizard/Searching-for-a-Friend

**Comment by strategywizard** [comment]
I just tried pushing a revised version, "SearchingForAFriendRev1," into the repository.  Let me know if I did anything wrong, but that should be the one ready to be added to Valkyrie.

**Comment by scrubbless** [comment]
Happy to help I can see an update to the repo for that time.

Test looks good, I'll publish this when I'm free tonight!

**Comment by strategywizard** [comment]
Awesome, thanks!

**Comment by scrubbless** [comment]
Ok added, sorry for the delay :)

**Comment by strategywizard** [comment]
Thanks!
I didn't notice the scenario when I looked in the scenarios in Valkyrie.  How long should it take before it shows up?  Or did I just miss it?

 

    On Thursday, May 28, 2020, 06:10:52 PM CDT, scrubbless <notifications@github.com> wrote:  
 
 


Closed #1298.

**Comment by strategywizard** [comment]
Ah, I just re-imported content and it was there.  Thank a bunch!
 

    On Thursday, May 28, 2020, 06:10:52 PM CDT, scrubbless <notifications@github.com> wrote:  
 
 


Closed #1298.

**Comment by scrubbless** [comment]
Its showing on my list, had to set the order to "last updated" as the scenario has no rating yet.
![image](https://user-images.githubusercontent.com/32058089/83259741-7eaffc00-a1b0-11ea-8218-d14d50348c58.png)
