### ISSUE TITLE
Download from google play/steam

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#13]
I have written a system to import data from an RtL install, but we should have a way to download the needed data within valkyrie.  Ideally if we can pull the apk from google play that should work.

**Comment by brunoqc** [comment]
It's not clear from the README that I can install the required app from Steam.

**Comment by NPBruce** [comment]
Updated the readme.

**Comment by NPBruce** [comment]
It looks like we can have a dummy google account to fetch the APK, but this isn't helpful as the data we need is in the supporting obb file.  We can also get this, however I have started writing an importer for this file and found that the format is a bit different to the windows and apk unity .assets files.

Firstly the some files are split into chunks and there are a lot of untyped 1MB files.  I will play around a bit, but unfortunately it looks like the existing tools (UABE, Unity Studio) don't handle this properly.

**Comment by NPBruce** [comment]
If anyone has info/examples on reading unity obb packaged assets and/or downloading obb files from google play (or amazon) that would be great.

**Comment by jonathonf** [comment]
Be careful of TOS here. Copying content that you already have access to (e.g. from the Steam download or existing on-device APK) is very different to obtaining the content directly. WRT Play, you're also likely breaking TOS if you're using a dummy account across multiple devices (as well as likely hitting API limits). If you're doing a Play download you should be using an on-device account.

The majority of third-party front-ends for existing content require the user to obtain the copyrighted content separately - see the various [SCUMMVM](https://www.scummvm.org/) implementations, [Settlers RTRR](https://www.siedler25.org/), [FreeSerf](https://github.com/freeserf/freeserf), [OpenRA](http://www.openra.net/)... so I wouldn't see a similar requirement as a negative for Valkyrie.

**Comment by redwolf2** [comment]
Is this in the current scope or can this be closed?

**Comment by NPBruce** [comment]
It would have been nice, but I've given up.
