### ISSUE TITLE
Tome of Horrors - Identification

### ISSUE THREAD

**Issue by strategywizard** [NPBruce/valkyrie#1301]
The Tome of Horrors item in Mansions of Madness doesn't fall under the "Tome" category.  Instead, it is considered equipment.  I am resurrecting this issue, because my card actually shows the "Tome" identification as seen in the image below.  I bought my copy of this expansion late last year, so I suspect this is intended to be classified as such.  If I am being a nuisance, I heartily apologize.  But there are so few items classified this way, it seems that it would be helpful to add this item into that category.

Thanks!

Valkyrie Version 2.4.07

![Tome Of Horrors](https://user-images.githubusercontent.com/65921164/83081304-fa416a00-a045-11ea-8345-91db1aae0047.jpg)

**Comment by redwolf2** [comment]
Dublicate of https://github.com/NPBruce/valkyrie/issues/1300
