### ISSUE TITLE
How to View Comments on My Scenario

### ISSUE THREAD

**Issue by strategywizard** [NPBruce/valkyrie#1305]
### Description of Problem or Question

I see that 3 people have reviewed my scenario "Search for a Friend" when I browse the scenarios in online mode.  But how can I see what comments they might have left?  I would like to see what criticisms might have been made.

Also, if I wanted to update it the scenario in the future, how do I do that?  Do I just create a new package with the edits, push it to GitHub, and post an issue for updating the scenario?

Thanks in advance!

### Valkyrie Version

2.4.09

**Comment by scrubbless** [comment]
You can view the feedback in the "(Spoilers) Feedback" tab of this spreadsheet:
https://docs.google.com/spreadsheets/d/1OsevlouIvR0DRYhGIS41PU9lBLB8VYgJvyj9KsHcAik/

I maintain a BGG post about Valkyrie here, some authors use it as a place to advertise their scenarios to the community:
https://boardgamegeek.com/thread/2100734/valkyrie-home-brew-scenarios-statistics-announceme

**Comment by scrubbless** [comment]
> Also, if I wanted to update it the scenario in the future, how do I do that? Do I just create a new package with the edits, push it to GitHub, and post an issue for updating the scenario?

Just create your new scenario package as you did when publishing, then add it to your repo overwriting the old files. Commit the changes to your repo and the scenario will update in the lists automagically.

As long as the path you provided originally (to the .ini file) is the same for the new version, Valkyrie checks the version number of the scenario and sees that its change and requires an update.

**Comment by strategywizard** [comment]
I just tried it, but I must have done something wrong.  Now my scenario image isn't appearing, and it doesn't show the update to the "Description" text I made where I mention that I made an update based on a user comment.  I pushed the new package into the original repository location, now called SearchForAFriendUpdate1, but perhaps that wasn't enough?

**Comment by scrubbless** [comment]
You've over thought this :)

Your last folder was called 'SearchingForAFriendRev1' you have to keep all the names and paths the same.

Your change will have broken the Valkyrie scenario list because your scenario is not reachable at its previous path.

I'll update the manifest to this new location, but in the future, do not change the folder or repo names when making updates as it will cause problems.

**Comment by strategywizard** [comment]
Yeah, I'm a little in over my head in all this, so I appreciate you taking the time to make it easy for me.

Just to make sure I've got this, all I have to do are these steps:

1. Create a new package in Valkyrie with my edits.
2. Drag the package into the repo folder on my desktop, saving over the previous file.
3. Use the GitHub Desktop App to commit, and then push the new package to the GitHub website.

And that's all I have to do, as long as the folder name is identical?  If so, that's easier than I thought!

I did some dumb tinkering around, and the 3 reviews that were connected to my scenario are now gone.  But it seems that everything is in working order.

Sorry for all of the headache, and thank you for the help.

**Comment by scrubbless** [comment]
Yep that's it :)

When a scenario is published all we really do is tell Valkyrie the path to the <scenario name>.ini file. When you select the scenario for download that.

Since the path contains the repo name and the .ini file name they can't change.

**Comment by strategywizard** [comment]
That's great news.  Hopefully this will be my last question.

Are the 3 reviews that were applied to my scenario never going to be linked to it again since I made that error?

**Comment by scrubbless** [comment]
I will update the raw data to update the name.

**Comment by strategywizard** [comment]
Thanks a bunch!

**Comment by strategywizard** [comment]
Scrubbless, I have yet another problem that I hope you can help me on.  I just followed the process above to update my scenario.  However, it doesn't appear to show the changes when "online."  But when I go offline, I have two separate entries of my scenario.  One shows the new edits that I made, and one shows the old version that is currently available online.  What could be causing this?

**Comment by strategywizard** [comment]
Update: I just checked the online version, and it now shows the correct title and edits.  Not sure what happened there.  Did it just take time for the changes to show up in the online version?

**Comment by scrubbless** [comment]
Hi @strategywizard 

The scenario list is generated seperatly using Google APIs. Basically the script periodically (every hour ish) scans the quest.ini file of each scenario to gather the author, scenario brief, difficulty and duration.

Therefore you have to wait for that script to run before seeing changes in the scenario list, prompting for download again.

However, if you have not yet downloaded a scenario (or delete one you already have from the online menu), then download it, the version that's downloaded will be the latest.

The reason you see who copies of the scenario is when you go offline, it will show any scenarios you downloaded in the scenario list AND any that you have in your editor folder. This is how you can test your scenarioes in progress 'as a player', without publishing.

**Comment by strategywizard** [comment]
Ok, that cleared things up.  Thank you for the information!
