### ISSUE TITLE
New scenario

### ISSUE THREAD

**Issue by strategywizard** [NPBruce/valkyrie#1306]
### Description of Problem or Question

Here is the link to the new scenario.  Thanks, guys!

https://github.com/strategywizard/ExpeditionToTerrorRepository

**Comment by scrubbless** [comment]
Just seen this, I'll get it added soon!

**Comment by scrubbless** [comment]
I've added the scenario to the manifest, so it should be visible within the hour.

**Comment by strategywizard** [comment]
Thank you!
