### ISSUE TITLE
Valkyrie Issue Templates

### ISSUE THREAD

**Issue by Quantumrunner** [NPBruce/valkyrie#1308]
Hello everyone,

I have created some [github issue templates](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository) to streamline issue creation for Valkyrie.

### Issue selection

![grafik](https://user-images.githubusercontent.com/58113888/84388166-68fcf680-abf4-11ea-8f5f-25397a092bdb.png)

### Issue markdown

![grafik](https://user-images.githubusercontent.com/58113888/84388604-2ab40700-abf5-11ea-8f96-5e1f9af15cba.png)

### Final issue

![grafik](https://user-images.githubusercontent.com/58113888/84387618-972e0680-abf3-11ea-88b3-86034f9bfb3f.png)

This streamlines the issue experience and points the users towards a clearer direction what kind of issue they want to add and what information is needed.

Currently I came up with four common issue categories:

1. Feature
2. Bug
3. New Scenario
4. Scenario Translation
5. Question

You can try them [here](https://github.com/Quantumrunner/ValkyrieIssueTemplateTest/issues/new/choose) (feel free to open some issues, I'll delete the repo later anyway) and the code is [here](https://github.com/Quantumrunner/ValkyrieIssueTemplateTest/tree/master/.github/ISSUE_TEMPLATE).

**What do you think of that? Are there maybe more common categories that could be used?**

**Comment by NPBruce** [comment]
Another common one is just question, though maybe you can just broaden the definition of bug?

**Comment by Quantumrunner** [comment]
Ah yes that's definitely missing. I'd prefer to have it's own category for Question because of the auto tagging feature.

**Comment by Quantumrunner** [comment]
@scrubbless  @redwolf2 Any ideas regarding this stuff?

What do you think of automtically setting the title. Do you think there would be too many user who forget to update it when creating the ticket?

I think starting with the topic in brackets (e.g. [Bug]) makes the issue list much cleaner. See [this](https://github.com/Zettlr/Zettlr/issues) as an example.

**Comment by BenRQ** [comment]
It's done ! Thanks @Quantumrunner

**Comment by scrubbless** [comment]
Unlike it! Very nice
