### ISSUE TITLE
New Scenario

### ISSUE THREAD

**Issue by Revokee** [NPBruce/valkyrie#1310]
Hi - I finished my first scenario.

For now is in Portuguese only, but English should follow in two weeks.

https://github.com/Revokee/MOMTC

**Comment by scrubbless** [comment]
Sorry, I've not been checking the issue log. I'll add this momentarily.

**Comment by scrubbless** [comment]
Hi @Revokee 
I cant add a scenario that has a folder or name with spaces or special characters. I suspect the unicode accented characters are causing an issue. Note the path to your raw .ini file

https://raw.githubusercontent.com/Revokee/MOMTC/master/EditorCen%C3%A1rio8.ini

Can you rename it removing unicode so there is a valid path to the file.

I would recommend deleting the packaged scenario from your repo, the rename the scenario folder in %appdata% and creating a new package to upload.

Link me the new path here and I'll add it.

**Comment by Revokee** [comment]
Done, the files are updated in the same repository.

**Comment by scrubbless** [comment]
My apologies, I forgot to close this it seems. The scenario is live and showing in the stats
