### ISSUE TITLE
The Lair of Rlim Shaikorth : Polish translation

### ISSUE THREAD

**Issue by Litas-86** [NPBruce/valkyrie#1312]
@sodapaps
Hi.
I've made a polish translation of The Lair of Rlim Shaikorth.
Waiting for your reply. I post the files here.
![dead](https://user-images.githubusercontent.com/57891868/85127707-412f1380-b230-11ea-996f-0c761d82a1cf.png)
![lie](https://user-images.githubusercontent.com/57891868/85127708-42604080-b230-11ea-8843-5670984ea3b4.png)
![must](https://user-images.githubusercontent.com/57891868/85127711-42f8d700-b230-11ea-8f83-0445210b6448.png)
![the](https://user-images.githubusercontent.com/57891868/85127713-43916d80-b230-11ea-9ea2-87e8860ec703.png)
[Localization.Polish.txt](https://github.com/NPBruce/valkyrie/files/4804297/Localization.Polish.txt)

**Comment by vidimus** [comment]
@Litas-86 Hello, where did you get the pictures and the fonts from? I've finished the Spanish translation and the only remaining thing is the paper clips.

**Comment by Litas-86** [comment]
@vidimus I took the original pictures from the scenario folder in Valkyrie editor, took another one that is a newspaper from some free stock images page and overlayed them with polish text in gimp.

**Comment by vidimus** [comment]
Hello, @Litas-86 , thanks for replaying. 
And the letter font?

**Comment by Litas-86** [comment]
@vidimus I've painted it by hand using brush tool since it was my first time with gimp :) now I know a little bit more and maybe I would use textfield with some kind of font.

**Comment by vidimus** [comment]
Uf, I think I would try to find a letter font better. I've already got the paperclips and the background as you suggested. Let's see if @sodapaps reads this and update your translation (and therefore, mine).

**Comment by vidimus** [comment]
I finally did them. Not so pro as you, @Litas-86
One example:
![the](https://user-images.githubusercontent.com/41538948/89840435-8b69ac80-db70-11ea-9257-0d7625e85e13.png)

(Let's mention him again: @sodapaps )

**Comment by sodapaps** [comment]
I am so sorry. 2 months ago I had a bone marrow transplant and have been
doing fairly well, but now the last month ive been in and out of the
hospital. I'm not ignoring you just having a difficult time getting to this.

**Comment by Litas-86** [comment]
@sodapaps  I totally understand, no hard feelings. Hope you'll get well soon and have some spare free time. Take care and we'll wait patiently for hearing from you.

**Comment by vidimus** [comment]
@sodapaps No need to apologize at all. It was far from my intention to make you feel unconfortable.
I hope everything will be fine. As @Litas-86 said , we will wait.
Best wishes.

**Comment by vidimus** [comment]
@Sodapaps, Spanish translation is also complete right now.

https://github.com/vidimus/Valkyrie-Mom-scenarios-translations/issues/24#issue-668217407

I wish you could upload it soon (that would be a great new about you!).

**Comment by vidimus** [comment]
Hello, @sodapaps , how are you going? Hope that everything goes fine. Waiting for any news from you.

Best wishes!

**Comment by vidimus** [comment]
Hello, @sodapaps and @Litas-86 
What if I create the valkyrie package with both translations in and post it here? This way, the only thing to do is just replace the file in the repository.

What do you think?

**Comment by sodapaps** [comment]
Again, I apologize. I just got home from the hospital yesterday. Perhaps
today I can look att it, though truth be told, I haven't used Valkyrie in a
long time. Is there a way to give you editing rights to the level and you
can just do it?

**Comment by vidimus** [comment]
> Again, I apologize. I just got home from the hospital yesterday. Perhaps today I can look att it, though truth be told, I haven't used Valkyrie in a long time. Is there a way to give you editing rights to the level and you can just do it?

Hello, @sodapaps 
Happy to have some news from you. First, thanks and best wishes for you.

Second, I've commented your situation to @scrubbless and he's kindly accepted to help us in this issue. You only need to add Scrubbles as a contributor to your repository. With that, he will be able to maintain your scenario and its updates.

**Comment by scrubbless** [comment]
@sodapaps , hope you are feeling well. I'd be honoured to assist in maintaining your scenario if you would allow me. I took a huge amount of inspiration from this scenario and truly is the scenario that put me on the path to working with Valkyrie.

Thanks for the recommendation @vidimus

**Comment by sodapaps** [comment]
I would appreciate that. I know people enjoy the scenario, and I just don't
have the time to maintain it.

**Comment by sodapaps** [comment]
Ok. I added scrubbless to my github repository as a collaborator. Please
let me know if it works.

**Comment by scrubbless** [comment]
Got the invitation thanks. I can commit to your repo to add the translations. I'll honour the scenario as is, but if any game breaking bugs appear I am happy to fix them

**Comment by scrubbless** [comment]
@vidimus  @Litas-86 

Do you have a translated image for the clues splash screen?

**Comment by Litas-86** [comment]
@scrubbless I have everything. When I'll have time I'll make another proof read since it was my first translation, and then I'll upload it to my github and pm you a link. Will this be ok?

**Comment by scrubbless** [comment]
That's fine, shall I publish this in the mean time?

**Comment by Litas-86** [comment]
It waited for so long it can wait few days more ;) I'll try to make everything as quick as possible. I hope that maybe tomorrow it will be ready.

**Comment by scrubbless** [comment]
No worries at all, I am just most of the way through the prep work is all and have the spanish ;).

I'll wait for the definitive version :D

**Comment by scrubbless** [comment]
I have updated the scenario with both Polish and Spanish translations. It should show in the SE within the hour, however if you want to test this out, just delete the downloaded copy you have of the scenario and redownload it.
