### ISSUE TITLE
Torch Common Item in not Base Set

### ISSUE THREAD

**Issue by antontimmermans** [NPBruce/valkyrie#1313]
### Description of Problem or Question
The Torch Common Item is not appearing in the base set of Base set common items (Light Source, Heavy weapon)

It is likely that this broke with the addition of PotS. That expansion adds more torches to the game, but the base already had 1 torch common item.

### Valkyrie Version
2.4.09

### Attach Save, Quest or Scenario
n.a.

**Comment by mayjak** [comment]
Pretty much the same bug as #1422 . Something to note here is it should probably combine the count from different sets. Fix coming soon.

**Comment by mayjak** [comment]
Reference screen:
![image](https://user-images.githubusercontent.com/10874335/103277272-f05f5b00-49c8-11eb-8e96-2f669c5e070c.png)
