### ISSUE TITLE
Editormission1

### ISSUE THREAD

**Issue by JeanPierre48** [NPBruce/valkyrie#1316]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [ ] Mansions of Madness
- [x ] Descent

### Please enter the GitHub Url to your scenario here
https://github.com/JeanPierre48/BotwQuest1/tree/master/Editormission1
Sorry for the name of the folder, it's first time for me.  This scenario is made from descent extension box : Bonds of the Wild.
I hope you like it and if you think it's a good one , please insert it in the mission list. Thank you.

**Comment by Quantumrunner** [comment]
You will need to rename Editormission1 to the name of your scenario. Otherwise the scenario can not be added to Valkyrie.

Rename the folder locally and reupload it to Github again.

**Comment by Quantumrunner** [comment]
@JeanPierre48 still waiting for your changes so that the quest can go live. :)

**Comment by scrubbless** [comment]
Hi @JeanPierre48 ,
As @Quantumrunner  has mentioned, the scenario cannot be named to the default (editormission1) the name needs to be unique with no spaces in the filename or repository.

Rename the scenario folder in 
%appdata%\valkyrie\de2\Editor\

When you create the package, you'll notice the scenario name including .in and .Valkyrie files have a different name.

**Comment by vidimus** [comment]
I'm curious about this scenario. Why has it not finally been released? Two closed issues by the author but I can see the scenario anywhere.

**Comment by scrubbless** [comment]
We can't publish missions or scenarios with the generic file names, until the author changes the filename we can't publish it.
