### ISSUE TITLE
[Bug] Problem creating package with Spanish translation added

### ISSUE THREAD

**Issue by jlederer2** [NPBruce/valkyrie#1317]
### Description 
After adding a Spanish localization file to my scenario (and updating quest.ini), I attempt to create a package.  The package is created, but in the process a 2nd copy of Localization.Spanish.txt is created in the MoM editor/ALittleNightMusic directory, and is placed into the .valkyrie file.  After I upload the scenario files to GitHub, the scenario shows-up in the Valkyrie scenario list with a black box where the Spanish flag should be, and when running the scenario with MoM set to Spanish, the English text shows-up.

### Scenario 
ALittleNightMusic

### Steps to reproduce the behavior:
See above

### Expected Behavior
Did not expect 2nd copy of Localization.Spanish.txt to be created, nor placed in the .Valkyrie file.  Expected the Spanish text to appear when running the scenario, with MoM set to Spanish via Options

### Scenario:
[ALittleNightMusic.zip](https://github.com/NPBruce/valkyrie/files/4822781/ALittleNightMusic.zip)
### LogFile
[output_log.txt](https://github.com/NPBruce/valkyrie/files/4822773/output_log.txt)

### Desktop
 - OS: Windows 10
 - Browser N/A (Edge)
 - Version Home

### Context / Comments
I didn't think it was possible to have two copies of the same file with the same name in the same directory (or in the same directory in a zip file for that matter).  I used powershell and found that there are two files in the directory, but they don't actually have the same name...the new one which is created is named Localization.Spanish[].txt, where the [] is a little box that looks like what is typically displayed when there is a non-displayable character in a document.

Does Valkyrie attempt to "read" or "process" the localization file in some fashion during packaging, or does it just "zip-up" the contents of the scenario directory without reading the contents of the files?  If it is reading the file, perhaps it is getting confused by some special character that is included in the Spanish language translation file?  I don't know why it would create a new file with (nearly) identical name during this process.  Another possibility is that this is some kind of Windows 10 issue with localization or processing of files created on a computer running a different (i.e. Spanish) version of Windows, or whatever OS/language set-up Vidi M (who did the translation) is using.  When I received the file from Vidi M., I noticed that the file properties indicated that the file "came from a different computer" and that the file "might be blocked by Windows to protect my computer" - never saw that in properties before (especially strange to see this for a text file!).

**Comment by jlederer2** [comment]
@vidimus

**Comment by NPBruce** [comment]
There are two different things, saving and creating a package. Creating the package just zips up the content, but saving does recreate the files. I suspect that is where this is being created.

The language files should have a first line that identifies which language they provide, if this has noise in it, then a new "spanishish" language will be defined and saved.

Double check the language identifier in the file.

**Comment by jlederer2** [comment]
**Thank you** - I think you have caught it.  It looks like there may be invisible "bad" characters in the file (there was something on the end of the 1st line of the file and some other lines too.  Probably an artifact of how Vidi M. created the translation in Excel or whatever, or perhaps Vidi M. is using Linux and line-ending characters are different than Windows.  I'll ask him to recreate the file without these invisible "noise" characters.

**Comment by vidimus** [comment]
Ok, I will create again the Localization.txt file

**Comment by vidimus** [comment]
I've posted the file on @jlederer2 's repository.
I tried with the scenario editor and it seems to work properly.
Thanks for all and sorry for the inconvenience.

**Comment by vidimus** [comment]
> When I received the file from Vidi M., I noticed that the file properties indicated that the file "came from a different computer" and that the file "might be blocked by Windows to protect my computer" - never saw that in properties before (especially strange to see this for a text file!).

I passed over this comment. It's so weird...
I'm using W10, Google spreadsheet and notepad++.
First time I've got this problems with a Localization.txt.

**Comment by jlederer2** [comment]
Revised file incorporated - problem solved!
