### ISSUE TITLE
New Scenario -  The Ritual

### ISSUE THREAD

**Issue by ColinBaumgartner** [NPBruce/valkyrie#1322]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

https://github.com/ColinBaumgartner/MOM-Scenarios/tree/master/TheRitualScenario

Big thanks to Scrubbless for taking the time to write such a helpful guide.

**Comment by scrubbless** [comment]
Added, it should be live within the hour.

**Comment by ColinBaumgartner** [comment]
Thanks.  I appreciate you.  Your guide really helped me figure out Valkyrie.  

Cheers, 
Colin

**Comment by scrubbless** [comment]
You're very welcome, I am glad it was of help!
