### ISSUE TITLE
[Scenario] Demonios entre los Wilson

### ISSUE THREAD

**Issue by FJReina21** [NPBruce/valkyrie#1325]
Hello everyone!
I just finished creating my first scenario for MoM. For now it's only in Spanish, but I'm working on the translation into English!
Thank you for your time,
F. J.

### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [X ] Mansions of Madness
- [ ] Descent

### Please enter the GitHub Url to your scenario here
https://github.com/FJReina21/Stories/tree/master/DemoniosEntreLosWilson

**Comment by scrubbless** [comment]
I have published this, it should be live within the hour
