### ISSUE TITLE
[Scenario] Losing my Religion

### ISSUE THREAD

**Issue by abedgregio** [NPBruce/valkyrie#1327]
Hi guys,

Could you add this new MoM scenario to Valkyrie, please? Although it is supposed to be the first part of a three-episodes history, the scenario is completely standalone. I apologize in advance for grammar/spelling mistakes (not native English speaker) and for any eventual bug in the game. Scrubbless kindly ran the scenario several times and provided plenty of bug fixes and suggestions that actually made the game playable (thanks for that, my friend!). 

Cheers!

Andre

### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

### Please enter the GitHub Url to your scenario here
https://github.com/abedgregio/MoM/tree/master/LosingMyReligion_P1

**Comment by scrubbless** [comment]
Hi Andre ( @abedgregio )

I have published the scenario, it should be live within the hour.

I'll add it to the stats, however it won't show in the scoring until it has had at least one play.
