### ISSUE TITLE
[Scenario] Expedition to Answers

### ISSUE THREAD

**Issue by strategywizard** [NPBruce/valkyrie#1328]
- [x] Please ensure you have renamed your scenario folder so that it does **not** equal the default mission name **EditorQuest1.valkyrie** or **EditorQuest1.ini**.
  - [x] Please replace **YourScenarioName** in the Issue-Title with your scenario name
 -  [x] Please check the checkboxes below so we know if the mission is a Mansions of Madness or Descent mission.
 -  [x] Please enter the GitHub Url below and ensure the github project is public.
-->https://github.com/strategywizard/ExpeditionToAnswersRepository

### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [x] Mansions of Madness
- [ ] Descent

### Please enter the GitHub Url to your scenario here
https://github.com/strategywizard/ExpeditionToAnswersRepository

**Comment by scrubbless** [comment]
I've added the scenario to the manifest it should be live within the hour.
