### ISSUE TITLE
NewScenario:ALEtatSauvage

### ISSUE THREAD

**Issue by JeanPierre48** [NPBruce/valkyrie#1330]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [ ] Mansions of Madness
- [X] Descent

### Please enter the GitHub Url to your scenario here
https://github.com/JeanPierre48/Sauvage/ALEtatSauvage

**Comment by JeanPierre48** [comment]
Hello, I changed folder and scenario names. Hope it's ok now. The scenario includes the two quests of the package. Thank you

**Comment by vidimus** [comment]
I've checked it and the repo address is this: https://github.com/JeanPierre48/BotwQuest1/tree/master/ALEtatSauvage
