### ISSUE TITLE
[Bug] Agent Craven Token Bitmap slightly shifted

### ISSUE THREAD

**Issue by antontimmermans** [NPBruce/valkyrie#1331]
Minor graphical issue: The bitmap of the Agent Craven Token is slightly shifted. On the right side, the brown edge is flattened. On the left side, you see the small part of the edge that is missing on the right side. (see also attached image)

### Expected behavior
Correct graphics

### Screenshots
![image](https://user-images.githubusercontent.com/42072372/87300942-08bce580-c50f-11ea-9ea6-f79961e238a5.png)

### Valkyrie Version
2.4.09

### Desktop
 - OS: Windows
 - Browser: Chrome
 - Version 10

**Comment by redwolf2** [comment]
I made the changes: https://github.com/NPBruce/valkyrie/pull/1343

**Comment by BenRQ** [comment]
Will be in 2.4.10
