### ISSUE TITLE
[Feature] Please add Korean

### ISSUE THREAD

**Issue by cheeseguyhcl** [NPBruce/valkyrie#1332]
## Describe the solution you'd like

I made a Korean version of Valkyrie.
Please add Korean officially For Korean users

## Additional context

![EcUiINdUMAAIaLX](https://user-images.githubusercontent.com/67976711/87315146-113d0c80-c55f-11ea-90d6-253723204577.jpg)

[Localization.Korean.txt](https://github.com/NPBruce/valkyrie/files/4913047/Localization.Korean.txt)

Please let me know if you need anything more

**Comment by BenRQ** [comment]
Korean added in version 2.4.10

If you want, you can now translate scenarios by sending Localization.Korean.txt to scenarios authors, so they can integrate in their scenarios.
