### ISSUE TITLE
[Translation] Demonios entre los Wilson

### ISSUE THREAD

**Issue by FJReina21** [NPBruce/valkyrie#1333]
Good evening! I just finished my English translation for my first scenario, Demonios entre los Wilson. Hope you like it!

### What kind of translation do you want to add (mark with an X, e.g. [X] Descent)?
- [X ] Mansions of Madness
- [ ] Descent

https://github.com/FJReina21/Stories/tree/master/DemoniosEntreLosWilson

[Localization.English.txt](https://github.com/NPBruce/valkyrie/files/4934564/Localization.English.txt)

**Comment by vidimus** [comment]
@FJReina21 , hola, eres tú mismo el que tiene que añadir la traducción a tu escenario. En la guía de Valkyrie explica cómo hacerlo. Si tienes alguna duda, pregunta.

Y gracias por crear un escenario para Mansiones.
