### ISSUE TITLE
[Bug] more expansions but fewer scenarios

### ISSUE THREAD

**Issue by kozka** [NPBruce/valkyrie#1335]
# Describe the bug
more expansions but fewer scenarios.
no expansions in my collection and with the filter only in Spanish.
I get 49 scenarios, if I add the expansions I have.
47 appear? If I add more expansions to the logic, is that more scenarios appear, right?

### Steps to reproduce the behavior:
take away the expansions. and list scenarios.
put expansions and list scenarios
.with the expansions more scenarios should appear but it is not.

### Valkyrie Version
2.4.09

**Comment by vidimus** [comment]
Do you mean the message up left on the scenarios selection screen? Because that it's the number of scenarios filtered, in other words, the ones that are not showed because they don't match the selection criteria (and not the scenarios available).

**Comment by kozka** [comment]
ok, but not very intuitive.
normal would not be
example:
They are listed below 4/25 according to their filters.
putting 21 is very rare

but well ok
