### ISSUE TITLE
[Translation] Stress and Strain (V3.6)

### ISSUE THREAD

**Issue by Revokee** [NPBruce/valkyrie#1337]
### What kind of translation do you want to add (mark with an X, e.g. [X] Descent)?
- [x] Mansions of Madness
- [ ] Descent

https://raw.githubusercontent.com/scrubbless/PublishedScenarios/master/Stressandstrain/

[Localization.Portuguese.txt](https://github.com/NPBruce/valkyrie/files/5011598/Localization.Portuguese.txt)

Additionally - this scenario has images that needs to be localized. The BR Community also created a file to map this information. @scrubbless would you be able to copy and paste the texts in the spreadsheet below and create the Portuguese version for it?
[Image Translations.xlsx](https://github.com/NPBruce/valkyrie/files/5011596/Image.Translations.xlsx)

**Comment by scrubbless** [comment]
Hi @Revokee 

I can generate the translated images, i'll try to take a look at this during this week.

**Comment by scrubbless** [comment]
Ok I have translated the images and added your localisation. Thanks @Revokee  (and BR community)
