### ISSUE TITLE
[Translation] The Stand

### ISSUE THREAD

**Issue by Revokee** [NPBruce/valkyrie#1338]
### What kind of translation do you want to add (mark with an X, e.g. [X] Descent)?
- [x] Mansions of Madness
- [ ] Descent

https://raw.githubusercontent.com/GwanGwanish/Mansions2/master/TheStand/

[Localization.Portuguese.txt](https://github.com/NPBruce/valkyrie/files/5011605/Localization.Portuguese.txt)

@GwanGwanish

**Comment by vidimus** [comment]
@Revokee , I see you are still waiting. I usually contact with @GwanGwanish using the BGG. Try there.

**Comment by GwanGwanish** [comment]
Indeed, I only periodically check my accounts. I'm not sure exactly what is
being asked of me here? I tried to check how "The Stand" was currently
listed on Valkyrie, but there is a network error at the moment. Do you need
me to add the Portuguese option? I thought I had already added it, but
maybe I am thinking of one of my other scenarios.

**Comment by GwanGwanish** [comment]
Got it - I see I still need to add this one. Will do so when I have a
moment.

Thanks!

**Comment by GwanGwanish** [comment]
I updated Valkyrie with the portuguese addition. I will check later to see
that it uploaded correctly.

Thanks!

**Comment by vidimus** [comment]
Parabems, @Revokee , another scenario translated into Portuguese is already available. Well done!
