### ISSUE TITLE
[Scenario] Five Crimes at Crimson Alley

### ISSUE THREAD

**Issue by antontimmermans** [NPBruce/valkyrie#1339]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [ X] Mansions of Madness
- [ ] Descent

### Please enter the GitHub Url to your scenario here
https://github.com/antontimmermans/MOMFCCA

**Comment by vidimus** [comment]
@antontimmermans remember two things:
- To close this issue.
- To write to me when you finish tunning the scenario to start the Spanish translation (I hope that would happens before I finnish my holidays).

**Comment by scrubbless** [comment]
I published this, didn't I Anton? (@antontimmermans)

**Comment by vidimus** [comment]
Yes, you did!

**Comment by antontimmermans** [comment]
Yes, it is published and played a couple of times already. Thank you.

So far getting nice reviews. It is not in your Statistics overview yet. but based on your slide, I built my own statistic view. So for me, that is not really an issue.
I will close the issue

**Comment by antontimmermans** [comment]
> @antontimmermans, please remember two things:
> 
> * To close this issue.
> * To write to me when you finish tunning the scenario to start the Spanish translation (I hope that would happens before I finnish my holidays).

I am fine-tuning as we speak. I will have it available today. I will also prepare a translation file for your convenience.

**Comment by scrubbless** [comment]
I've updated my stats now @antontimmermans , had some issues with it I needed to fix too.
