### ISSUE TITLE
Add numerical system to flags

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#134]
Currently flags are Boolean only. If they were floats we could add, set and test for them.

Set:
* Abs/relative Another flag
* Abs/relative static value
* Abs/relative random value (limit)

Any unset flag would be 0.

Flags should be displayable in event windows.

Also perhaps they should be renamed.

Tests could be:
* Non zero
* =, >, <, >=, <= static_x
* =, >, <, >=, <= flag2

Round number would become a flag, removing all the extra triggers (use generic trigger + round flag).

Hero count becomes 1 flag.

Threat becomes a flag, remove custom things.

**Comment by NPBruce** [comment]
This can also replace delayed events.

**Comment by NPBruce** [comment]
I don't want the operations for set and equals to be "==" and "=" because this is likely to confuse non programmers.  Ideas?

**Comment by NPBruce** [comment]
I am going with =/==, and in the editor they will be in different sections (Test or Assign).

**Comment by Sadgit-HL** [comment]
Sounds great!

**Comment by NPBruce** [comment]
https://github.com/NPBruce/valkyrie/wiki/QuestIniEvent080#conditions
https://github.com/NPBruce/valkyrie/wiki/QuestIniEvent080#operations
