### ISSUE TITLE
[Bug] No More Reviews Showing Up in Valkyrie Statistics Sheet

### ISSUE THREAD

**Issue by strategywizard** [NPBruce/valkyrie#1340]
No more reviews are appearing after the 6,000 mark in the Valkyrie Statistics Sheet.

I just noticed that my new scenario Expedition to Answers has received 2 reviews, but they aren't visible in the sheet as they occurred after the 6,000 reviews that are currently visible.

**Comment by vidimus** [comment]
I've already notified to @scrubbless, but he's a bit busy at this moment.
 
I have seen the problem about the review information. Line 6001 is importing raw data not from 6001 as it should be but from 8501. Same happens to all the lines beneath. I guess it happens something similar with other statistics tabs.

**Comment by scrubbless** [comment]
Hi @vidimus this is my fault, I tried to update it on my phone and messed it up. I'll take a look when I have some free time this evening

**Comment by vidimus** [comment]
I saw today that stats are updated. Hurray!

**Comment by scrubbless** [comment]
Sorry for the delay, it's been a busy couple of weeks!
