### ISSUE TITLE
[Scenario] El Legado de los Wilson // The Wilsons' Legacy

### ISSUE THREAD

**Issue by FJReina21** [NPBruce/valkyrie#1341]
Hi everyone!
I just finished my second scenario El Legado de los Wilson, in both Spanish and English, so I request that you upload it to Valkyrie whenever you can. Thank you!

### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

### Please enter the GitHub Url to your scenario here
https://github.com/FJReina21/Stories/tree/master/ElLegadoDeLosWilson

**Comment by vidimus** [comment]
@scrubbless can you add this scenario to the Valkyrie manifest?

**Comment by scrubbless** [comment]
I have added this to the manifest, sorry for the delay (I have just moved house, so like has been chaos!)

It should be listed within the next hour.
