### ISSUE TITLE
[Bug] App doesn't work on Mac OS Big Sur Beta

### ISSUE THREAD

**Issue by ikikito** [NPBruce/valkyrie#1342]
The App just bounce a couple of times before showing an error message. 

System Log:
Aug  5 11:40:51 com.apple.xpc.launchd[1] (application.unity.NA.Valkyrie.468942.468956[1193]): Could not find and/or execute program specified by service: 13: Permission denied: /Applications/Valkyrie.app/Contents/MacOS/Valkyrie
Aug  5 11:40:51 com.apple.xpc.launchd[1] (application.unity.NA.Valkyrie.468942.468956[1193]): Service setup event to handle failure and will not launch until it fires.
Aug  5 11:40:51 com.apple.xpc.launchd[1] (application.unity.NA.Valkyrie.468942.468956[1193]): Service exited with abnormal code: 78
Aug  5 11:42:50 com.apple.xpc.launchd[1]: Coalition Cache Hit: app<application.unity.NA.Valkyrie.468942.468956(501)> [974]

<img width="313" alt="Captura de pantalla 2020-08-05 a las 11 41 15" src="https://user-images.githubusercontent.com/69241437/89397883-b4251880-d710-11ea-9143-e3b64e17e25e.png">

**Comment by redwolf2** [comment]
> 13: Permission denied

> Also make sure, you have folder permissions. Move your Valkyrie download to the folder Applications inside the Finder app. Then run `chmod +x /Applications/Valkyrie.app/Contents/MacOS/Valkyrie` in the Terminal app.
> https://github.com/NPBruce/valkyrie/wiki
