### ISSUE TITLE
Mansions of Madness 2nd Edition Quest Publish

### ISSUE THREAD

**Issue by blueadamantine** [NPBruce/valkyrie#1344]
Hello everyone!
I just finished creating my first scenario for MoM2. I'm posting it in Italian and English. Feel free to contact me if you need it.

What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
[ x ] Mansions of Madness
[    ] Descent

Please enter the GitHub Url to your scenario here
ITA [https://github.com/blueadamantine/mom2-ultimacena](url)
ENG [https://github.com/blueadamantine/mom2-thelastsupper](url)

**Comment by vidimus** [comment]
Hello / Hola, @blueadamantine 

Creo que tienes que subir los archivos sin comprimir a tu repositorio y después enlazarlos aquí. Y no olvides editar este mensaje para indicar si es un escenario de Mansiones o una aventura para Descent.

--------------------------------------

I think you need to upload the files unzipped to your Github repository and then link them here. And don¡t forget to edit your post to mark this as a Descent quest or a Mansions of Madness scenario.

**Comment by blueadamantine** [comment]
Hi! Thanks for responding.

I'm sorry for the various mistakes. This is my first time making a scenario and asking to publish it.

I thought I've already linked the unzipped files to my repository here. If I did it wrong, can you tell me how to do it?

Also, how must I edit my post to mark it as a Descent quest or a Mansions of Madness scenario?

I've created the package using the editor, but I don't know how to send them here. It won't attach them to the post.

**Comment by vidimus** [comment]
Hello again, @blueadamantine 

Take a look to this post, from a previous scenario (currently available):

https://github.com/NPBruce/valkyrie/issues/1325

As you can see clicking on the link posted by the author, he only linked the repository. And in his repository, this are the files:
DemoniosEntreLosWilson.ini
DemoniosEntreLosWilson.valkyrie
Localization.English.txt
Localization.Spanish.txt
a.jpg

Only the ,jpg (the picture for the scenario cover and description), the .ini file (with the stats) and the .valkyrie file are needed. There are created automatically when you, using the editor, select the option "create a package". That's all you need to upload to your repository (simply adding the files clicking on the right bottom).

Anyway, I will mention @scrubbless to see if I'm right. Probably he can help you better than I.

**Comment by blueadamantine** [comment]
Thank you very much.

In the meantime, I've edited the main post taking the one you sent as a reference, but the link I posted seems to not work. What am I doing wrong?

**Comment by vidimus** [comment]
Hello, @blueadamantine 

Your repository address is this:
https://github.com/blueadamantine/mom2-ultimacena

**Comment by blueadamantine** [comment]
Thanks a lot!

**Comment by scrubbless** [comment]
I'll take a look at this soon

**Comment by scrubbless** [comment]
Ok, published. It should be in the list within the hour

**Comment by scrubbless** [comment]
Doesn't seem like the path, I just downloaded the scenario and could run it locally, I am not sure why the manifest will not show it.

@BenRQ  can you see any errors in your google scripts?
@NPBruce  is there anything your expert eye can pick out that may be wrong?

**Comment by BenRQ** [comment]
Hi @scrubbless @blueadamantine 

Problem is reported by the online grabber script which fails to download the previous scenario.
It has been blocked for the last 5 days.

> Fetch error (try 0) while trying to access below URL:
> https://raw.githubusercontent.com/FJReina21/Stories/master/ElLegadoDeLosWilson/ElLegadoDeLosWilson.ini
> Error description:
> Exception: Request failed for https://raw.githubusercontent.com returned 
> code 404. Truncated server response: 404: Not Found (use muteHttpExceptions 
> option to examine full response)

I see content is no more available in this URL: https://github.com/FJReina21/Stories/tree/master/ElLegadoDeLosWilson
So we should probably remove that one.

@scrubbless  we usually get an email alert on this kind of issue, but I don't know why the forward configuration is not active anymore.
Information was only available in the valkyrie mailbox.

**Comment by scrubbless** [comment]
Ok I've removed that thanks Ben. I'll try to keep an eye on the Valkyrie mailbox a bit more.

**Comment by scrubbless** [comment]
@blueadamantine your scenario should be live within the hour.
