### ISSUE TITLE
[Bug] Editor does not clean-up Colored text from UI items

### ISSUE THREAD

**Issue by antontimmermans** [NPBruce/valkyrie#1346]
A UI item with a colored action symbol does not clean up properly up-on loading the scenario in the editor and will always remain visible on top.

It functions properly in play mode (not visible/displayed when called, cleaned up when removed), but when you return to the editor, it is again continuously visible.

Test scenario created:
[EditorScenario1.zip](https://github.com/NPBruce/valkyrie/files/5113870/EditorScenario1.zip)

### Steps to reproduce the behavior:
1. Load the atte=ached editor in the valkyrie editor, and it is immediately visible.

### Expected behavior
No traces of any UI items should remain visible after loading the scenario, only upon selecting the item

### LogFile
[output_log.txt](https://github.com/NPBruce/valkyrie/files/5113872/output_log.txt)

### Screenshots

![image](https://user-images.githubusercontent.com/42072372/90977214-f1c4d680-e543-11ea-816c-7eb5beee1dbb.png)

### Valkyrie Version
2.4.09

### Desktop
 - OS: Windows 10
 - Browser:

 Chrome

**Comment by BenRQ** [comment]
I think I fixed it, would be good to test it though in other conditions.

**Comment by BenRQ** [comment]
will be in 2.4.10, please reopen if you not fixed properly
