### ISSUE TITLE
[Feature] Extinguish Fire option in Pop-up during Mythos

### ISSUE THREAD

**Issue by antontimmermans** [NPBruce/valkyrie#1348]
## Is your feature request related to a problem? Please describe.**
In the feedback on my scenarios, the comment indicates that it is not clear to new players using Valkyrie how to clear the fire. The FFG app also provides this option in the phase where the 'fire spreads'. A payer can choose the option 'fire spreads' or 'fire  extinguished. Since this option s not shown in the current Valkyrie app (2.4.09), new players automatically assume that it is a scenario bug.

## Describe the solution you'd like
Add the option to extinguish the fire in the message where the fire spreads text is displayed during mythos phase. (see Blue marker in the image below)
![ExtinguishFire](https://user-images.githubusercontent.com/42072372/91656580-298acb80-eaba-11ea-8645-76660af6c591.png)

## Describe alternatives you've considered
The alternative to clear the fire is to use the current mechanism with the Set button in the current game menu (see the red marker in the attached image. The text color of that button could turn red when `$fire == 1` and default white when `$fire == 0`. This would also alert players where to look in the interface, but I find the addition of the button more clear and intuitive since it mimics the FFG behavior better.
Optionally you could do both: Add the extinguish fire button in the event message AND color the Set button depending on the status of the `$fire` variable.

**Comment by mayjak** [comment]
I added the 2nd button to clear the fire in mythos phase.

**Comment by antontimmermans** [comment]
Thanks for implementing this one.

That button would also need translations. 

You could either re-use the translated text from the menu option to set and clear fire (bottom left of the screen). The text there says "clear fire". The valkyrie localization files will likely have the correct translation for it in all languages.
OR
The official FFG app uses the term "Fire Extinguished". Maybe you can reuse that term from FFG's localization files although I don't know how that works or if it is possible.
OR
Google translate will probably give you OK results for "Fire Extinguished". But the translation channels in Discord may give you better suggestions.

FYI: Google translated gives:
- German: Feuer gelöscht
- French:  Feu éteint
- Spanish: Fuego extinguido
- Portuguese: Fogo extinto
- Polish: Pożar ugaszony
- Italian: Fuoco spento
- Chinese: 灭火 (<- I assume that Valkyrie uses simplified Chinese, traditional Chinese would be 滅火)
- Korean: 화재 진압
- Russian: пожар потушен
