### ISSUE TITLE
[Scenario] O resgate sombrio

### ISSUE THREAD

**Issue by Bigdadd1** [NPBruce/valkyrie#1349]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

### Please enter the GitHub Url to your scenario here
https://github.com/Bigdadd1/mapa_mom_oresgatesombrio

**Comment by scrubbless** [comment]
Scenario has been added, should be listed within the hour
