### ISSUE TITLE
[Bug] DefeatedMonster<xxx> triggered event in Monster Phase not correctly handled

### ISSUE THREAD

**Issue by antontimmermans** [NPBruce/valkyrie#1352]
### Describe the bug
The bug was initially found on scenario Disturbance at the Docks. A player was attacked by a Monster, but the damage from the monster backfired back on the monster, killing it in the process. When that monster is killed, an event is activated by  DefeatedMonster<xxx> trigger. This should display a message to hand out a quest item and increase a variable by 1. A second monster (of a different type) was present at the moment the first one died.
The second monsters' activation prevented the message from being displayed. The variable is increased by 1, so the event is triggered, but the message was lost.

### Scenario
Found in Disturbance at the Docks, **but all scenarios that use the DefeatedMonster<xxx> trigger are affected.**

### Steps to reproduce the behavior:
1.  Quick to reproduce with Disturbance at the docks: From the start position, move one tile to the right (east street) 
2. Click on the explore button to open the door -> A cultist spawns
3. Click a couple of times on "next round" until another (random) monster spawns)
4. Then Kill cultist **in the Monster Phase!!!**

### Expected behavior
DefeatedMonsterCultist trigger activates an event that displays a message handing out a quest item (with a continue button). The variable GrotesqueStonesFound increases by one.

What actually happens is that the second monster's activation prevents the message from being displayed. The Event trigger is called because, in the Log function, you can actually see the variable GrotesqueStonesFound increase 1.

### Valkyrie Version
2.4.09

### Desktop
 - OS: Windows
 - Browser n.a.
 - Version n.a.

**Comment by NicolaZee** [comment]
I knocked together a quick test scenario to confirm this bug is happening.
Please note it only occurs in the Monster Phase and not the Investigator Phase,

**Comment by BenRQ** [comment]
@NicolaZee Can you please share your test scenario to make it easier to investigate and fix the issue?

**Comment by NicolaZee** [comment]
Happy to oblige.

[DefeatedMonsterExample.zip](https://github.com/NPBruce/valkyrie/files/5260405/DefeatedMonsterExample.zip)

**Comment by BenRQ** [comment]
Related to #982 .
I have a fix, but I think it's good to test this more.
Maybe with event without text, just audio or any other specific cases.

**Comment by BenRQ** [comment]
If you have some time for a test, here is a pre release : 
https://github.com/NPBruce/valkyrie/releases/tag/prerelease%2F2.4%2Fv2.4.10a

**Comment by NicolaZee** [comment]
I've given it a quick test and it seems to be OK.
I will try to fit in a game or two of Mansions this week but I am playing the game much less than I used to.
Hopefully antontimmermans  will give it a more thorough test as it is affecting his scenario.
:)

**Comment by antontimmermans** [comment]
I have tried to make it go wrong but was unsuccessful :)

Well done, and thank you

**Comment by scrubbless** [comment]
I'll close this up then?
