### ISSUE TITLE
[Bug] Scenario "Holy Mansion" Labeled as Incorrect Language

### ISSUE THREAD

**Issue by strategywizard** [NPBruce/valkyrie#1353]
The scenario "Holy Mansion" is labeled as English, but the actual text is in another language.  I don't know if this is intentional for some reason, but I assume it is an error of some sort.

If this wasn't the right place to post this, I apologize.  But this scenario has been sitting in the English section for a LONG time, and I thought it would be helpful to point this out since it appears nobody is playing it since it's not in the correct language category.

**Comment by vidimus** [comment]
It's something that the author must change. The scenario is actually in Italian. Let's see if @flopez86 can read this and fix it.

**Comment by vidimus** [comment]
https://github.com/flopez86/HolyMansionScenario/issues/1#issuecomment-695986183

**Comment by vidimus** [comment]
I will create a Valkyrie package fixing this issue, and at the same time, adding the Spanish translation. In a few days I will send it to @flopez86

**Comment by vidimus** [comment]
Package sent to author. It should solve the problem with the wrong language flag. Now it shall appear in Italian and Spanish, but not in English.

**Comment by vidimus** [comment]
Fixed, @strategywizard . You can close this issue now.
