### ISSUE TITLE
[Scenario] Santuário das Mazelas

### ISSUE THREAD

**Issue by Bigdadd1** [NPBruce/valkyrie#1354]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

### Please enter the GitHub Url to your scenario here
https://github.com/Bigdadd1/santuariodamazela

**Comment by scrubbless** [comment]
Have you renamed your repo? The link above is a dead link.

I can see this in your GitHub, is this it?
https://github.com/Bigdadd1/mapa_mom_oresgatesombrio

**Comment by Bigdadd1** [comment]
sry, I thought that I had to create another repository. I transferred the
new scenario to the original folder that you previous mentioned:
https://github.com/Bigdadd1/mapa_mom_oresgatesombrio

Hope it is right!

Em ter., 8 de set. de 2020 às 03:35, scrubbless <notifications@github.com>
escreveu:

**Comment by scrubbless** [comment]
Hi @Bigdadd1 

We can't upload scenarios that have spaces in their folder paths. The easiest way to fix this is to open:
%appdata%\valkyrie\mom\editor

Find your scenario and rename it to a name that does not contain any spaces of special characters (avoid accents too please).

Once renamed, open Valkyrie editor, enter your scenario and create a package. Upload your new package to your GitHub.

**Comment by Bigdadd1** [comment]
I did not know that, sry. Uploaded again, now fixed special characters and
spaces.

Em ter., 8 de set. de 2020 às 08:41, scrubbless <notifications@github.com>
escreveu:

**Comment by scrubbless** [comment]
Great, thanks @Bigdadd1 

The scenario has been added, it should be listed within the hour.

**Comment by Bigdadd1** [comment]
thank you for creating a amazing software and let us enjoy even more MoM!!

Em ter., 8 de set. de 2020 às 09:52, scrubbless <notifications@github.com>
escreveu:
