### ISSUE TITLE
[Scenario] El legado de los Wilsons

### ISSUE THREAD

**Issue by FJReina21** [NPBruce/valkyrie#1355]
Good evening everyone! I realized I accidentally deleted the .valkyrie file for this scenario, so I uploaded it again but it won't show up on the app. I believe it needs to be relinked or something like that, so, if you have the time and don't mind it, I'd like you to help me out. Thanks!

### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

### Please enter the GitHub Url to your scenario here
https://github.com/FJReina21/Stories/tree/master/ElLegadoDeLosWilson

**Comment by scrubbless** [comment]
Hi @FJReina21 

We had to delist the scenario for that reason. Without the Valkyrie file the Sceanrio explorer crashes, since it can't look up the required information. As a result it prevents any new scenarios from being added.

I can relist this for you.

**Comment by scrubbless** [comment]
Ok this should be back up within the hour
