### ISSUE TITLE
Valkyrie dies when playtest places Bandstand tile

### ISSUE THREAD

**Issue by rnoelle** [NPBruce/valkyrie#1356]
### Description of Problem or Question
In "Save and Test" mode of the scenario editor, when the event placing the SOA bandstand tile runs, the app exits suddenly. The event works if the tile is not a component, or if a different tile is selected. The only other tile in play is the Fleamarket.

I've tried reimporting as well, with no improvement. Yard1MAD25 also triggers the crash, but Conservatory does not. 

### Valkyrie Version
2.4.09

### Attach Save, Quest or Scenario
Log File:
[output_log.txt](https://github.com/NPBruce/valkyrie/files/5245608/output_log.txt)
Scenario:
[EditorScenario1.zip](https://github.com/NPBruce/valkyrie/files/5245598/EditorScenario1.zip)

**Comment by rnoelle** [comment]
My fault - I didn't realize you had to select the expansions in use in addition to importing content.

**Comment by scrubbless** [comment]
You can also use the #soa variable to control when to place Streets if Arkham tiles. So you can make a base only scenario but include optional expansion content as a branching set up

**Comment by vidimus** [comment]
@rnoelle what happened to this scenario? Did you finally managed to finish it?

**Comment by vidimus** [comment]
@rnoelle I guess the answer would be "no".
