### ISSUE TITLE
New Scenario: El huésped del 31 de octubre

### ISSUE THREAD

**Issue by DaniMassaro** [NPBruce/valkyrie#1357]
Hello!

I would like to publish my second scenario.

https://github.com/DaniMassaro/MoM31O
https://github.com/DaniMassaro/MoM31O/tree/master/El%20inquilino%20del%2031%20de%20octubre

Thank you.

### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [x ] Mansions of Madness
- [ ] Descent

**Comment by scrubbless** [comment]
I am unable to link a scenario where any of the path has sides. Notice the concert to %20, this breaks the path in Valkyrie.

Can you publish this again after removing the spaces, special characters and accented characters please :)

**Comment by DaniMassaro** [comment]
Ok, I think it's ok now.

https://github.com/DaniMassaro/MoMi31O
https://github.com/DaniMassaro/MoMi31O/tree/master/ElInquilinoDel31deOctubre

Thank you.

**Comment by DaniMassaro** [comment]
Ok, I think it's ok now.

https://github.com/DaniMassaro/MoMhuesped31Oct/tree/master/ElHuespedDel31deOctubre

I changed the name of the Scenario.

Thank you.

**Comment by scrubbless** [comment]
This is now listed
