### ISSUE TITLE
Color change when moving between mythos/investigator phase.

### ISSUE THREAD

**Issue by zaki850** [NPBruce/valkyrie#136]
There is no intermission / confirmation screen when you want to end mythos or investigator phase and move to the next phase - makes it easy to misclick, whereas in original app you can still stop moving to the next phase, even if someone clicked too quick - before all actions were completed.

**Comment by NPBruce** [comment]
I have removed most confirmations, and instead there is an undo.  I do thing that perhaps this transition could be clearer, I will give it some thought.

**Comment by redwolf2** [comment]
An undo option is IMO the better solution. Less interaction with the app is better, because it let you focus more on the boardgame.

**Comment by NPBruce** [comment]
Plan is to use colour to make it clearer, later animation can be used (#430)

**Comment by zaki850** [comment]
Sounds good!
