### ISSUE TITLE
[Scenario] Azathoth's Sacrament

### ISSUE THREAD

**Issue by DomeAcolyte** [NPBruce/valkyrie#1361]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [ X] Mansions of Madness
- [ ] Descent

### Please enter the GitHub Url to your scenario here

https://github.com/DomeAcolyte/Azathoths-Sacrament

**Comment by scrubbless** [comment]
Sorry I've only just seen this. I'll get this up asap

**Comment by scrubbless** [comment]
I am not sure if this will list (or if it will break the Scenario List). 
The path has an apostrophe in it (Azathoth'sSacrament).  It's not converted it into html so may be ok. 

Will close this if it works, otherwise I'll repond here.

**Comment by DomeAcolyte** [comment]
Great, thanks. :)

**Comment by scrubbless** [comment]
The scenario has listed successfully, I'll close this off :)
