### ISSUE TITLE
New Scenario: Crypt Dragon

### ISSUE THREAD

**Issue by MatthewThornton** [NPBruce/valkyrie#1362]
Name:  Crypt  Dragon

Link
https://github.com/MatthewThornton/Valkyrie_Crypt_Dragon

Please  add to  mission list.

**Comment by vidimus** [comment]
Hello, @MatthewThornton 

I saw you didn't change the name to your scenario. You can't use a generic one like "editorquest1.valkyrie".

One step you must mandatorily do is to change the name, i.e., cryptdragon.valkyrie, on your repository (avoid any special character on the name).

Another step is to label this scenario either MoM or Descent (I guess it's a Descent quest).

@scrubbless , is there anything else he must do?

**Comment by Quantumrunner** [comment]
@MatthewThornton Still waiting to play your Scenario. Please update the name as vidimus described otherwise it will not be possible to upload it.

Don't let it get lost like this one: https://github.com/NPBruce/valkyrie/issues/1316

**Comment by scrubbless** [comment]
I'll add this one it has a supported name :)

**Comment by vidimus** [comment]
What did it happen at the end? Would it be added or not?

**Comment by Quantumrunner** [comment]
Without any changes from the author this won't be possible. This would be the second descent mission that can't be added because the author abandoned his scenario. :(

**Comment by vidimus** [comment]
So sad...

**Comment by scrubbless** [comment]
Yeh, it's just out of reach. If you want to play it, you can download the contents of the repo and paste it into your de\download folder to play "offline"

**Comment by scrubbless** [comment]
Hi @MatthewThornton 

I can't publish this with the current path, @vidimus  posted how to fix this above. 

If you are unsure and would like me to fix this for you, please feel free to give me contributer access to you repo. I would happily help maintain the scenario for you, such as adding translations help fix game breaking bugs.

**Comment by scrubbless** [comment]
I'll close this issue down for now. @MatthewThornton  if you would like this added, please perform the steps above and reopen this issue.
