### ISSUE TITLE
[Scenario] Azathoth's Sacrament (Update)

### ISSUE THREAD

**Issue by DomeAcolyte** [NPBruce/valkyrie#1364]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [x ] Mansions of Madness
- [ ] Descent

### Please enter the GitHub Url to your scenario here
https://github.com/DomeAcolyte/Azathoth-s-Sacrament

**Comment by DomeAcolyte** [comment]
I've done some bug fixes, smoothed out the gameplay and added some more flavour text.

**Comment by scrubbless** [comment]
I was just about to mention this. Just noticed that you deleted the old path,this caused script errors that could break Valkyrie.

When updating scenarios you should just upload identically named files, Valkyrie has its own version system so you don't need to rename. This will ensure all stats/ratings are correctly linked to your scenario.

**Comment by scrubbless** [comment]
Iveed updated the new path, so this version should be active now
