### ISSUE TITLE
[Scenario] Horror Haunts Merinda

### ISSUE THREAD

**Issue by Drake3** [NPBruce/valkyrie#1366]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [x] Mansions of Madness
- [ ] Descent

### Please enter the GitHub Url to your scenario here
https://github.com/Drake3/MOM/tree/master/Horror_Haunts_Merinda

Thanks for uploading.

**Comment by scrubbless** [comment]
Added should be listed within the hour
