### ISSUE TITLE
[Scenario] Lair of the Wyrm

### ISSUE THREAD

**Issue by Quantumrunner** [NPBruce/valkyrie#1367]
I have created a new Descent campaign based on the original Lair of the Wyrm campaign.

### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [ ] Mansions of Madness
- [x] Descent

### Please enter the GitHub Url to your scenario here
https://github.com/ValkDes/ValkyrieLOTW

@scrubbless Can you please add it to the mission list?

**Comment by scrubbless** [comment]
Added, should be listed within the hour @Quantumrunner
