### ISSUE TITLE
[Scenario] Heranças Familiares

### ISSUE THREAD

**Issue by Bigdadd1** [NPBruce/valkyrie#1368]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

### Please enter the GitHub Url to your scenario here
https://github.com/Bigdadd1/mapa_mom_oresgatesombrio/tree/master/Herancasfamiliares

**Comment by scrubbless** [comment]
I cant add a scenario path that has special characters or spaces in, they convert to %'s in the path and breaks the link. Can you rename scenario folder to something using standard characters (no spaces, special characters or scented characters), then create the package from the editor again, delete the old and upload the new.

**Comment by scrubbless** [comment]
Added to manifest, should be there within the hour :)
