### ISSUE TITLE
Sounds?

### ISSUE THREAD

**Issue by zaki850** [NPBruce/valkyrie#137]
Not an issue, but is there any plan or chance to add sounds? I keep the original app running in the background, so the music is there, but the absence of sounds makes it a bit dry. (not that there are any sounds in other board games, but sound effects when solving a puzzle or when monster appeared are building the atmosphere)

**Comment by NPBruce** [comment]
See #73, #74

**Comment by zaki850** [comment]
Great stuff, thanks!
