### ISSUE TITLE
[Translation] Disturbance at the Docks v2.0 (Korean)

### ISSUE THREAD

**Issue by cheeseguyhcl** [NPBruce/valkyrie#1371]
Hello, I am working on a Korean translation of an English scenario. Currently, we have translated and tested 4 scenarios. I will continue to upload. Thank you.

### What kind of translation do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

### Scenario name or url

Disturbance at the Docks v2.0
https://github.com/antontimmermans/MOMDATD

### Translation File

[Localization.Korean.txt](https://github.com/NPBruce/valkyrie/files/5433535/Localization.Korean.txt)

**Comment by antontimmermans** [comment]
@cheeseguyhcl thank you very much for your translation. It is integrated into version 2.0e which is now available.

**Comment by cheeseguyhcl** [comment]
> @cheeseguyhcl thank you very much for your translation. It is integrated into version 2.0e which is now available.
> 
> **This ticket may be closed**

Thank you!

**Comment by cheeseguyhcl** [comment]
> @cheeseguyhcl thank you very much for your translation. It is integrated into version 2.0e which is now available.
> 
> **This ticket may be closed**

Could you possibly make the English voice heard in Korean?

**Comment by antontimmermans** [comment]
That is possible.

Normally, I remove the English voiceover if it is played in another language to avoid confusion. Personally, I find it very confusing to hear one language and read another.

**Comment by cheeseguyhcl** [comment]
> That is possible.
> 
> Normally, I remove the English voiceover if it is played in another language to avoid confusion. Personally, I find it very confusing to hear one language and read another.

If you think so you don't have to
 I just wanted to tell the players a beep sound.

**Comment by antontimmermans** [comment]
> > That is possible.
> > Normally, I remove the English voiceover if it is played in another language to avoid confusion. Personally, I find it very confusing to hear one language and read another.
> 
> If you think so you don't have to
> I just wanted to tell the players a beep sound.

This ticket could solve the problem, people can then switch the scenario default language audio on/off. 
https://github.com/NPBruce/valkyrie/issues/1381

Let's hope it gets implemented in the next version of Valkyrie.
