### ISSUE TITLE
[Translation] Exotic Material(Korean)

### ISSUE THREAD

**Issue by cheeseguyhcl** [NPBruce/valkyrie#1372]
### What kind of translation do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

### Scenario name or url
Exotic Material

### Translation File
[Localization.Korean.txt](https://github.com/NPBruce/valkyrie/files/5433591/Localization.Korean.txt)

**Comment by vidimus** [comment]
@NPBruce , is this scenario yours?

**Comment by cheeseguyhcl** [comment]
> @NPBruce , is this scenario yours?

No, I only translated

**Comment by vidimus** [comment]
> > @NPBruce , is this scenario yours?
> 
> No, I only translated

I was mentioning to NpBruce because I think he is the author, to see if he can upload your translation, @cheeseguyhcl .

**Comment by NPBruce** [comment]
Done, sorry for the delay.

**Comment by cheeseguyhcl** [comment]
thankyou guys!
