### ISSUE TITLE
[Translation] Smugglers Point (Korean)

### ISSUE THREAD

**Issue by cheeseguyhcl** [NPBruce/valkyrie#1373]
### What kind of translation do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

### Scenario name or url
Smugglers Point

### Translation File
[Localization.Korean.txt](https://github.com/NPBruce/valkyrie/files/5433672/Localization.Korean.txt)

**Comment by antontimmermans** [comment]
Thank you very much for the Korean translation. The text is integrated into the scenario and released with version 1.3f.

This ticket may be closed.

**Comment by cheeseguyhcl** [comment]
> Thank you very much for the Korean translation. The text is integrated into the scenario and released with version 1.3f.
> 
> This ticket may be closed.

Thank you!
