### ISSUE TITLE
[Translation] En la pajarería a las 22.30 h (Korean)

### ISSUE THREAD

**Issue by cheeseguyhcl** [NPBruce/valkyrie#1374]
translating more scenarios. When I finish testing, I'll upload it.

### What kind of translation do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

### Scenario name or url
 En la pajarería a las 22.30 h

### Translation File
[Localization.Korean.txt](https://github.com/NPBruce/valkyrie/files/5433768/Localization.Korean.txt)

**Comment by vidimus** [comment]
Wow, great work translating so many scenarios into Korean. Congratulations!

**Comment by cheeseguyhcl** [comment]
I want to show you guys a scenario made in Korea. I'll upload it when it's ready.

**Comment by vidimus** [comment]
> I want to show you guys a scenario made in Korea. I'll upload it when it's ready.

Awesome. Willing to give it a try! 

I've sent a message to this scenario author to notice him about your translation. He was delighted with the translation!

**Comment by EtiCarasoft** [comment]
Thanks for the Translation, We're so glad! I uploaded the translation this morning.

**Comment by cheeseguyhcl** [comment]
> Thanks for the Translation, We're so glad! I uploaded the translation this morning.

Wow Very quick update Thank you!
The next scenario is also ready to be translated.
I'm looking forward to it!

**Comment by vidimus** [comment]
@cheeseguyhcl Congrats! You can now close this issue, if you don't mind.
