### ISSUE TITLE
[Translation] Five Crimes at Crimson Alley v1.3 (Russian)

### ISSUE THREAD

**Issue by AVAvovan** [NPBruce/valkyrie#1377]
### What kind of translation do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

### Scenario name or url
https://github.com/antontimmermans/MOMFCCA

### Translation File
[Localization.Russian.txt](https://github.com/NPBruce/valkyrie/files/5468874/Localization.Russian.txt)

**Comment by antontimmermans** [comment]
Thank you very much for your Russian Translation. The text is integrated into version 1.3d of the scenario. 

This ticket can be closed.
