### ISSUE TITLE
[EditorQuest1.ini] Artefatos Roubados

### ISSUE THREAD

**Issue by rafagoute** [NPBruce/valkyrie#1390]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [x ] Mansions of Madness

- [ ] Descent

**Comment by scrubbless** [comment]
Hi @rafagoute usually we do not publish scenarios and quests that appear to have the default names, however looking at the path I think we'll be ok in this instance. I've added this to the manifest so it should be available within the hour.

> https://raw.githubusercontent.com/rafagoute/Artefaros-Roubados/main/**EditorQuest1.ini**.ini

When publishing future scenarios can you rename the scenario folder from Editor1 (in %appdata%\Valkyrie\MoM\Editor) to a different name (avoiding spaces, accented characters and special characters). Usually its best to use the scenario name (without spaces) as it give a good indication on the statistics and manifiest which scenario belongs to which reviews.

**Comment by scrubbless** [comment]
This would not work, the scripts don't work with the path you provided.

Could you please rename your scenario and provide me with it's new path.

**Comment by rafagoute** [comment]
https://github.com/rafagoute/ArtefatosRoubados

**Comment by scrubbless** [comment]
Thanks, I've added the updated path, it should be available within the hour
