### ISSUE TITLE
[Testing] Pre-Release 2.4.11a

### ISSUE THREAD

**Issue by Quantumrunner** [NPBruce/valkyrie#1393]
# Description of Problem or Question
I did some testing of the new pre-release version and have the following findings so far:

## #1134:  Cancel button missing in Language selection of select content menu
The dialog that opens when clicking at a language in the select content menu does not have a cancel button. Normally a cancel button is at the bottom center of a dialog.

Possible solution for language selection:
![grafik](https://user-images.githubusercontent.com/58113888/99296917-ca7e5c80-2847-11eb-86b3-4936a36a715e.png)

## #817: Interface for Button conditions
As much as I love the new button condition feature I think an interface is needed here. Otherwise a lot of content creators will not even find this new feature. Apart from that the feature works fine.

### Some ideas how an interface for this could look like:
Add a new button next to the buttons to activate the conditions:
![grafik](https://user-images.githubusercontent.com/58113888/99297483-9d7e7980-2848-11eb-8346-8862ac8abb23.png)

When a condition buttons is clicked open a dialog where the conditions can be added:
![grafik](https://user-images.githubusercontent.com/58113888/99298049-678dc500-2849-11eb-8d6c-055453e53958.png)

When a new condition is being added in the dialog open another dialog which looks the same as the normal condition selection dialog:
![grafik](https://user-images.githubusercontent.com/58113888/99297749-f817d580-2848-11eb-996a-ddfce3c1970f.png)

## Menu background image
Not sure if this is just my resolution but for Descent and Mansions of Madness the buttons are blocking parts of the new main menu image:

![grafik](https://user-images.githubusercontent.com/58113888/99298378-ed117500-2849-11eb-9445-2ceb9f2ecbe9.png)

![grafik](https://user-images.githubusercontent.com/58113888/99298333-d9fea500-2849-11eb-8c00-72052cb1f23e.png)

![grafik](https://user-images.githubusercontent.com/58113888/99298472-0a464380-284a-11eb-85e9-064cd714e1ee.png)

Maybe move the buttons a little bit more to the left?

# Valkyrie Version
2.4.11a

**Comment by mayjak** [comment]
Actually I removed that cancel button myself, because I couldn't find a quick way of closing this one dialog, but it was late at night already. I'll check again :)

**Comment by mayjak** [comment]
For menu backgrounds it basically depends on your resolution. I agree it looks better on 16:9 than 16:10, I'll check what I can do.

**Comment by mayjak** [comment]
@Quantumrunner I updated the build with fixes for everything except for conditional logic UI.

**Comment by Quantumrunner** [comment]
Thanks! Main Menu und cancel button are working fine now.

I think you forgot #1386 in the change log.

**Comment by scrubbless** [comment]
How will #817 function if the test does not succeed? Will it grey the button or hide the option?

In descent I can imagine greying the button would be best. But would it be possible for it to optionally hide the button as an option?

In MoM you don't want to always let on that there are additional dialogues, and unlock then as clues are found.

**Comment by Quantumrunner** [comment]
@scrubbless You will be able to hide or disable the buttons:

Check this post for details:
https://github.com/NPBruce/valkyrie/issues/817#issuecomment-720070663
