### ISSUE TITLE
[Bug] 2.4.11a Music/Audio Selection in event editor (2 issues)

### ISSUE THREAD

**Issue by antontimmermans** [NPBruce/valkyrie#1396]
### Describe the bug
1. the Music selection box seems to overlap the audio selection box a little:

![image](https://user-images.githubusercontent.com/42072372/99407924-eb9a8800-28ef-11eb-9c69-61cf72e797ba.png)

2. After selecting Audio in the audio field, you can only replace it with another audio selection, you cannot 'unselect it' by selecting audio {NONE}

### Scenario
any.

### Steps to reproduce the behavior:
1. Select Components
2. Select events
3. Select any event, or create a new one
4. select any Audio in the audio field
5. try to remove that audio

### Valkyrie Version
2.4.11a

### Desktop
 - OS: Windows 10
 - Browser: Chrome

**Comment by mayjak** [comment]
Thank you, both issues are fixed and will be included in the next pre-release build.

**Comment by antontimmermans** [comment]
@mayjak the audio field problem including miss align graphics is also on other pages:

-  Token editor page
- Monster spawn page

I hope your fix also covers those
