### ISSUE TITLE
[Translation] Exotic Material - Localization Portuguese

### ISSUE THREAD

**Issue by Bigdadd1** [NPBruce/valkyrie#1397]
### What kind of translation do you want to add (mark with an X, e.g. [X] Descent)?
- [x] Mansions of Madness
- [ ] Descent

### Localization.Portuguese.txt
[Localization.Portuguese.txt](https://github.com/NPBruce/valkyrie/files/5557233/Localization.Portuguese.txt)

**Comment by NPBruce** [comment]
Done.
