### ISSUE TITLE
[Bug] 2.4.11a minor graphical issues in editor

### ISSUE THREAD

**Issue by antontimmermans** [NPBruce/valkyrie#1398]
### Describe the bug

**(1)** Some graphical issues on the first field you see when you load a scenario in the editor:
**(1a)** Min investigator and Min Duration field boxes:
![image](https://user-images.githubusercontent.com/42072372/99555424-98443a80-29c0-11eb-9b61-3556882117aa.png)

**(1b)** Secretly a new feature request from me :) can you make the image field a little bigger?. (FYI, it was already this small in 2.4.10
![image](https://user-images.githubusercontent.com/42072372/99555880-17397300-29c1-11eb-86b5-b2bd30848830.png)

**(2)** In the event editing page (components, add a new event)
**(2a)** Adding test conditions the green [+] box's right side is not correct
![image](https://user-images.githubusercontent.com/42072372/99556474-d857ed00-29c1-11eb-8956-b3281002fad3.png)

**(3)** QuestItem editing page
**(3a)** Miss aligned graphics  on [+] box of the traits field:
![image](https://user-images.githubusercontent.com/42072372/99557499-0ee23780-29c3-11eb-9f84-7784b5cb06e2.png)
**(3b)** same problem on the [+] box of the test field after adding a test.
![image](https://user-images.githubusercontent.com/42072372/99557708-451fb700-29c3-11eb-88b0-bca81c878066.png)

**(4)** Spawn monster
**(4a)** Health field graphics misaligned
![image](https://user-images.githubusercontent.com/42072372/99568100-4f47b280-29cf-11eb-827c-aa6bb0388eaa.png)
(4b) [+] button on test field
![image](https://user-images.githubusercontent.com/42072372/99568338-9635a800-29cf-11eb-8394-1e7cd0773ab0.png)

**(5)** Puzzle page
**(5b)** [+] button on test field

**(6)** custom monster page
**(6a)** health field
![image](https://user-images.githubusercontent.com/42072372/99568829-28d64700-29d0-11eb-923f-066cd3a6739f.png)

**(7)** UI Page
**(7a)** X-Position field
![image](https://user-images.githubusercontent.com/42072372/99569286-b6b23200-29d0-11eb-8050-6a8e0886bad5.png)
**(7b)** Text size field
**(7c)** [+] on test field

### Valkyrie Version
2.4.11.a

**Comment by mayjak** [comment]
Fixed in the next pre-release build.
