### ISSUE TITLE
[Bug] 2.4.11a New contitional Button 'Hide' option selecties wrong event.

### ISSUE THREAD

**Issue by antontimmermans** [NPBruce/valkyrie#1399]
### Describe the bug
Test code used:
```
[EventButtonTest]
buttons=5
event1=
buttoncolor1="gray"
event2=
buttoncolor2="green"
event3=Event3
event3Condition=VarOperation:testvar,==,1 VarTestsLogicalOperator:OR VarOperation:testvar,>,3 
event3ConditionAction=hide
event4=Event4
event5=Event5
```
The hiding and unhiding of button3 worked nicely depending on the value of testvar. 
When the button was hidden the Event5 could not be selected, and when clicking the button linked to event4, the event linked to event3 is called. 

Note: when using ConditionAction Disable, everything works perfectly

### Valkyrie Version
2.4.11a

**Comment by mayjak** [comment]
Fixed. This will be released in the next prerelease build this weekend.
