### ISSUE TITLE
[Bug] Incorrect traits on Dark Minotaur

### ISSUE THREAD

**Issue by Xyphistor** [NPBruce/valkyrie#1404]
Descent monster type Dark Minotaur has:
traits=melee cursed civilized small

Here: valkyrie/unity/Assets/StreamingAssets/content/D2E/h&m/soe/monsters.ini
https://github.com/NPBruce/valkyrie/blob/ff574fb760e51bb86004b7208dcce9c7a6790625/unity/Assets/StreamingAssets/content/D2E/h%26m/soe/monsters.ini

It should be 'dark' not 'cursed', so:
traits=melee civilized dark small

**Comment by Xyphistor** [comment]
It also looks odd that it has:
info={ffg:DARK_MINOTAUR_INSTRUCTION}

Where all other monsters seem to have INSTRUCTION_MONSTERNAME... Not sure where to check to see if this is valid or not...

**Comment by NPBruce** [comment]
In the imported Localization_en.txt, it is correct. There are quite a few strange keys like this, which is why they are all manually specified for every monster.
