### ISSUE TITLE
New scenario - El Secreto de BlackWood

### ISSUE THREAD

**Issue by TitoMochilo** [NPBruce/valkyrie#1405]
Hi!
I'd be grateful if you make available my first made scenario.
It's my first time using github. If something wrong or missing, please keep me know.

### Valkyrie Version
It's saved with Valkyrie 2.5.0

###Scenario

https://github.com/TitoMochilo/MOMBlackWoodsSecrets

Thanks!

**Comment by vidimus** [comment]
Wow, what a great new. I had the honour of testing it when it was a beta and I was clearly impressed. I'm glad you finally release it.

**Comment by TitoMochilo** [comment]
Ok. Thanks@scrubbless! I'm going to delete and create a new repository. I hope that will fix it. Sorry for bothering you.  

https://github.com/TitoMochilo/MOMScenarioBlackWoodSecret

**Comment by scrubbless** [comment]
Thanks @TitoMochilo 

I've added this to the manifest, it can take up to an hour to appear in the scenario list as the scripts that generate the list run on a schedule.
