### ISSUE TITLE
[Bug] MoM: Save game goes to a black screen

### ISSUE THREAD

**Issue by vidimus** [NPBruce/valkyrie#1407]
### Steps to reproduce the behavior:
1. Play a scenario.
2. Main Menu-->Save a game
3. Go to main screen--->click on continue
4. Select a saved game
5. See error-->black screen

### Expected behavior: load and continue the game

Log File:
[output_log.txt](https://github.com/NPBruce/valkyrie/files/5644340/output_log.txt)

Saves:

[save1.zip](https://github.com/NPBruce/valkyrie/files/5644343/save1.zip)

### Screenshots
![saved game black screen](https://user-images.githubusercontent.com/41538948/101194630-88825280-365e-11eb-9342-d89a26ae561d.png)

### Desktop
 - OS: Windows 7
 - Browser Chrome
 - Version [Versión 87.0.4280.88 (Build oficial) (64 bits)]

**Comment by mayjak** [comment]
I'll release a hotfix in the next hour.
