### ISSUE TITLE
[Translation] Horror Haunts a Cabin in the Woods (v2.16) (Russian)

### ISSUE THREAD

**Issue by AVAvovan** [NPBruce/valkyrie#1409]
### What kind of translation do you want to add (mark with an X, e.g. [X] Descent)?
- [ X] Mansions of Madness
- [ ] Descent

### Scenario name or url
Horror Haunts a Cabin in the Woods
https://github.com/Drake3

### Translation File
[Localization.Russian.txt](https://github.com/NPBruce/valkyrie/files/5647170/Localization.Russian.txt)

**Comment by vidimus** [comment]
Nice to see more scenarios published in other languages. Well done!

**Comment by AVAvovan** [comment]
Thank you! It's a pity that russian community not comparable with spanish one. You guys doing very well since Arkham Horror Spanish League.

**Comment by vidimus** [comment]
> Thank you! It's a pity that russian community not comparable with spanish one. You guys doing very well since Arkham Horror Spanish League.

I think you are doing quite well too. Many times is a synergic matter: More content available in your mother language wlll attract more people and it's more likely they create new content. So keep working!

@Drake3, this issue is about your scenario!

**Comment by Drake3** [comment]
Finishing up German Translation as well and then will put both of them online. Hope to be done this week.

**Comment by AVAvovan** [comment]
Thank you.
