### ISSUE TITLE
Triggers for a 'unique' set Monster and a 'UniqueMonster' of the same name are the same

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#141]
Also should probably change UniqueMonster to something else to avoid confusion.

**Comment by Sadgit-HL** [comment]
Exactly what we are struggling with at the moment! Actually we did not find a way to trigger events based on the defeat of a "UniqueMonster" we defined. Is this possible in the current version?
It is  crucial for us to be able to define e.g. a Lieutenant's behavior and couple that with a trigger such as a win condition in many quests.

**Comment by NPBruce** [comment]
It should work, but the current version of the editor won't prompt you (have to add manually).  The new version will have it selectable (already done).  If your unique has a different item name than the base type there is also no issue.

PS: Lieutenants have been added to 0.8.0.

**Comment by Sadgit-HL** [comment]
OK, maybe we got confused with the "unique" double definition. I tested some things and here is what we have so far. As far as I can see this triggers the EventWon if "Defeated" is selected from monster group icon. It does not trigger if "Unique Defeated" is selected. Any ideas?

[MonsterMauler2hero]
xposition=4
yposition=0
text="Place the master Ettin as shown, ignoring group limits. This is Mauler. \nMauler has 4 additional Health."
event1=MonsterGoblins
button1="Confirm"
flags=#2hero
monster=UniqueMonsterEttinMauler2heroes
placement2=MPlaceMauler
unique=true
uniquetitle="Mauler"
uniquetext="Mauler has 4 additional Health.\n\nMauler spends {surge} in the following order:\n{surge}: +X {heart}.\n\nThrow: Place the hero as far as possible away from Mauler in direction of the entrance."

[UniqueMonsterEttinMauler2heroes]
base=MonsterEttin
name=Mauler
info=
activation=EttinHeal EttinAttack EttinThrow
health=12

[EventWon]
text="<i>Mauler collapses to his knees, one of his heads emitting a grumbling wail.  The other head stuggles to speak: "Though we may die, we are but servants of the almighty Overlord. Our master will be triumphant in the end! Arhynn will fall!" The both heads grow silent and the beast topples over.</i>\n\nYou win!"
event1=EventEndCampaignPhaseWonGoblinsEscaped0 EventEndCampaignPhaseWonGoblinsEscaped1 EventEndCampaignPhaseWonGoblinsEscaped2 EventEndCampaignPhaseWonGoblinsEscaped3 EventEndCampaignPhaseWonGoblinsEscaped4
button1="Confirm"
trigger=DefeatedUniqueMonsterEttinMauler2heroes

**Comment by NPBruce** [comment]
It should trigger on both.  DefeatedUniqueUniqueMonsterEttinMauler2heroes should trigger on the defeated unique bit.

Having said that both types of unique aren't meant to be used together (but it *should* work).  You can have a monster than is normal *except* for some extra ability and can be individually defeated (unique=true), or you can have an entirely unique monster (can replace everything) in UniqueMonsterMyMonster.

**Comment by NPBruce** [comment]
I will test these combinations when I get a chance.

**Comment by Sadgit-HL** [comment]
However, it would be great to be able to define a new monstertype with [UniqueMonster] to be able to define custom activations for the minions and then add a unique monster to that group.

**Comment by Sadgit-HL** [comment]
I figured it out. It works as intended. Although it would be great to clear up the confusion with the definition of "unique".

**Comment by NPBruce** [comment]
Yep that was the idea behind this issue!

**Comment by NPBruce** [comment]
Changed UniqueMonster to CustomMonster.  Monster also changed to Spawn.
