### ISSUE TITLE
[Translation] Smugglers Point v1.4 (Russian)

### ISSUE THREAD

**Issue by ERROK51** [NPBruce/valkyrie#1410]
@antontimmermans

### What kind of translation do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

### Scenario name or url
Smugglers Point

### Translation File
[Localization.Russian.txt](https://github.com/NPBruce/valkyrie/files/5659976/Localization.Russian.txt)

**Comment by antontimmermans** [comment]
Thank you for this translation I will add it as soon as possible.

I could add your name to the credits: "Translation: ERROK51", but what I need from you is: 
1. confirmation that the name you want in the credits is ERROK51
2. Translate the word "Translation:" to Russian.

is this ok?:
Перевод : _ERROK51_

**Comment by antontimmermans** [comment]
For convenience, I added your translation to the google sheet (column I): https://docs.google.com/spreadsheets/d/1N7ajYnd3xvQUqWLn0hhqlfw_OXUY5n4sLTCyi2SEfw4/edit#gid=0

If you want to make updates to the translation, you can also use this sheet. When you are satisfied with the update you can notify me (for example on Discord or on the Smuggler's Point Github: https://github.com/antontimmermans/MOMSP)

**Comment by ERROK51** [comment]
> 
> 
> Thank you for this translation I will add it as soon as possible.
> 
> I could add your name to the credits: "Translation: ERROK51", but what I need from you is:
> 
>     1. confirmation that the name you want in the credits is ERROK51
> 
>     2. Translate the word "Translation:" to Russian.
> 
> 
> is this ok?:
> Перевод : _ERROK51_
Yes, great! I corrected the nickname in the Google sheet.

**Comment by antontimmermans** [comment]
Translations are integrated and released.
This ticket may be closed

**Comment by ERROK51** [comment]
> 
> 
> Translations are integrated and released.
> This ticket may be closed

Thanks!
