### ISSUE TITLE
[Translation] Horror Haunts a Cabin in the Woods (v2.16) (Korean)

### ISSUE THREAD

**Issue by cheeseguyhcl** [NPBruce/valkyrie#1411]
### What kind of translation do you want to add (mark with an X, e.g. [X] Descent)?
- [x] Mansions of Madness
- [ ] Descent

### Translation File
[Localization.Korean.txt](https://github.com/NPBruce/valkyrie/files/5665972/Localization.Korean.txt)

**Comment by vidimus** [comment]
@Drake3 , this one is yours!

**Comment by Drake3** [comment]
Localization is added to the Scenario. Thanks a lot @cheeseguyhcl

**Comment by Drake3** [comment]
Thanks for the info,

do you understand what that comment means:

También al leer el libro impío nos daba el hechizo pero llegamos al
nivel 10 y a pesar de decirnos que se podía seguir leyendo nos daba el
hechizo una y otra vez.



Am 10.12.2020 um 16:34 schrieb vidimus:

**Comment by vidimus** [comment]
> Thanks for the info, do you understand what that comment means: También al leer el libro impío nos daba el hechizo pero llegamos al nivel 10 y a pesar de decirnos que se podía seguir leyendo nos daba el hechizo una y otra vez. 

Hello, @Drake3 
Yes, according to this message, after reading the Unholy Book, they gained a Spell, but after reaching the level 10, even if the text displayed a message saying that they could continue reading, they received again and again the same Spell (an endless loop getting all the time the Spell).

**Comment by vidimus** [comment]
Ok, I've tested the scenario. They have poorly explained the bug. When you read the Old Diary, you make a lore test. After passing it and getting the Spell, you get a message tell in you to put back the Diary for a further study. After that, if you exam the Old Diary again, all the process is repeated unchanged: you make the test, get the Spell and read a message requesting a further study of the Diary.

**Comment by cheeseguyhcl** [comment]
Thanks!

**Comment by Drake3** [comment]
Ok, found that as well. Its not really a bug. You are allowed to study
it multiple times, but you need one more hit on the lore test each time.
So theoretically you can get 5 spells that way on easy, 4 on medium and
3 on hard. But it also gives 3 horrors every time you use it. They must
have done something wrong to get 10 spells.

Am 10.12.2020 um 19:07 schrieb vidimus:
