### ISSUE TITLE
[Translation] Footsteps in the Dark (Korean) 

### ISSUE THREAD

**Issue by cheeseguyhcl** [NPBruce/valkyrie#1412]
### What kind of translation do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

### Translation File
[Localization.Korean.txt](https://github.com/NPBruce/valkyrie/files/5666025/Localization.Korean.txt)

**Comment by vidimus** [comment]
@GwanGwanish, this issue requires your attention!

**Comment by vidimus** [comment]
@cheeseguyhcl I've sent a message to Gwan on Board Game Geek. I hope he will read it soon.

**Comment by cheeseguyhcl** [comment]
> @cheeseguyhcl I've sent a message to Gwan on Board Game Geek. I hope he will read it soon.

Thank you!

**Comment by cheeseguyhcl** [comment]
I seen the korean updates. Thank you guys!
