### ISSUE TITLE
[Translation] Five Crimes at Crimson Alley (Korean)

### ISSUE THREAD

**Issue by cheeseguyhcl** [NPBruce/valkyrie#1413]
### What kind of translation do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

### Translation File
[Localization.Korean.txt](https://github.com/NPBruce/valkyrie/files/5666029/Localization.Korean.txt)

**Comment by vidimus** [comment]
@antontimmermans , this one is for you.

**Comment by antontimmermans** [comment]
Integrated the Korean Text and Released it.
I also added the translation to the Translation support sheet on googledocs for convenience: https://docs.google.com/spreadsheets/d/1xcN5kll0L8am_Ko-hGJO-ngjUGA6vJ3sK1w6h2_pI-0/edit#gid=0

Any updates to the text can be done in the Google sheet and when you are satisfied, you can contact me for an update via discord or https://github.com/antontimmermans/MOMFCCA

This ticket can be closed

**Comment by cheeseguyhcl** [comment]
Thank you!
