### ISSUE TITLE
[Scenario] Drácula

### ISSUE THREAD

**Issue by Diesdooi** [NPBruce/valkyrie#1415]
<!--
  Thank you for proposing a new scenario! To streamline our all efforts, please
  first read this short paragraph. If you can check all the boxes below, go for
  it and propose the new scenario!

  - [ ] Please ensure you have renamed your scenario folder so that it does **not** equal the default mission name **EditorQuest1.valkyrie** or **EditorQuest1.ini**.
  - [ ] Please replace **YourScenarioName** in the Issue-Title with your scenario name
 -  [ ] Please check the checkboxes below so we know if the mission is a Mansions of Madness or Descent mission.
 -  [ ] Please enter the GitHub Url below and ensure the github project is public.

### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [X ] Mansions of Madness
- [ ] Descent

https://github.com/Diesdooi/CenarioDracula

The scenario is in Portuguese.

**Comment by scrubbless** [comment]
Hi @Diesdooi 

Your repo only contains the . Valkyrie file. We require all of the files created when using the "create package" option in the Valkyrie editor.

Please use the "create package" option in the editor and copy the whole of the scenario folder (from appdata) to you Got repo.

**Comment by Diesdooi** [comment]
Hi,

I have edited my issue with the new link:

https://github.com/Diesdooi/CenarioDracula

Thanks

**Comment by scrubbless** [comment]
I've added this should be in the list within the hour
