### ISSUE TITLE
New Scenario, "The Unspeakable One"

### ISSUE THREAD

**Issue by strategywizard** [NPBruce/valkyrie#1418]
New scenario for:

Mansions of Madness

https://github.com/strategywizard/Unspeakable-One-Repository

**Comment by scrubbless** [comment]
My apologies, I've just seen this. I'll add now

**Comment by scrubbless** [comment]
Hi @strategywizard  

I am unable to add scenarios which have spaces in the path.

This is the path to your scenario, the web translation of the spaces messes up the path.
https://raw.githubusercontent.com/strategywizard/Unspeakable-One-Repository/main/The%20Unspeakable%20One/The%20Unspeakable%20One.ini

Can you please rename your scenario and republish to your repo.

The best way would be to edit the scenario name in %appdata% to a name without spaces and then create the package again from the editor.

**Comment by strategywizard** [comment]
> Hi @strategywizard
> 
> I am unable to add scenarios which have spaces in the path.
> 
> This is the path to your scenario, the web translation of the spaces messes up the path.
> https://raw.githubusercontent.com/strategywizard/Unspeakable-One-Repository/main/The%20Unspeakable%20One/The%20Unspeakable%20One.ini
> 
> Can you please rename your scenario and republish to your repo.
> 
> The best way would be to edit the scenario name in %appdata% to a name without spaces and then create the package again from the editor.

Ah, I forgot about that!  It should be fixed now.  Let me know if there are any other issues.  Thanks!

**Comment by scrubbless** [comment]
Ok this has been added. It should be listed within the hour.

I'll try to update the stats sheet tomorrow with this )and all the others pending)
