### ISSUE TITLE
[Question] "El huésped del 31 de octubre" is not in General Graphs (Valkyrie)

### ISSUE THREAD

**Issue by DaniMassaro** [NPBruce/valkyrie#1419]
The scenario "El huésped del 31 de octubre" is not on the list "General Graphs" on the page "Valkyrie Homebrew Statistics". Is there any problem?

Thanks a lot.

**Comment by scrubbless** [comment]
My apologies, I've not yet updated the spreadsheet. 
I'll try to do this tomorrow 🤞

**Comment by DaniMassaro** [comment]
Thank you.

**Comment by scrubbless** [comment]
I've updated these, i'll update the BGG thread another day, its late now :D
