### ISSUE TITLE
[Scenario] Manor of Ravens campaign (Descent)

### ISSUE THREAD

**Issue by Quantumrunner** [NPBruce/valkyrie#1421]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [ ] Mansions of Madness
- [x] Descent

### Please enter the GitHub Url to your scenario here

https://github.com/ValkDes/ValkyrieMoR

@scrubbless Can you please add it to the mission list?

**Comment by scrubbless** [comment]
I've added this, should be listed within the hour
