### ISSUE TITLE
[Bug] Multiple of the same tile entries make tiles disappear from Valkyrie Editor UI

### ISSUE THREAD

**Issue by Quantumrunner** [NPBruce/valkyrie#1422]
### Describe the bug
Three tiles are missing from the **Descent** expansion **The Chains of Rust** (TCTR): 78A+B, 79A+B and a new entrance. These three tiles already exist in the Mists of Bilehall (MOB) expansion.

These three tiles would need to be added to the tiles.ini of the chains that rust (`valkyrie_Data\StreamingAssets\content\D2E\boxed\tctr`). Otherwise you will not be able to use these tiles if only TCTR has been enabled in Valkyries select content section.

If the files are added the following problem occurs:

**If these entries are added in the file and you reimport all Descent Valkyrie content the entry disappears from the MOB **and** the TCTR tile selection.**

### Steps to reproduce the behavior:
1. Rename this file ([tiles.ini.txt](https://github.com/NPBruce/valkyrie/files/5743007/tiles.ini.txt)) to `tiles.ini`.
1. Replace `tiles.ini` at `valkyrie_Data\StreamingAssets\content\D2E\boxed\tctr` with the file from step 1. 
2. Open Valkyrie
3. Copy `079B.png` from `valkyrie_Data\StreamingAssets\content\D2E\boxed\mob\img` to `valkyrie_Data\StreamingAssets\content\D2E\boxed\tctr\img`. You have to do this step because 079B seems to be missing from the **Road To Legend** import. Instead you could also check if the file may be available nowdays.
3. Click `Reimport content` for Descent.
3. Open Valkyrie Editor and add a new tile.
4. Check the MOB and TCTR section if the tiles 78A+B, 79A+B and the swamp entrance are available.

### Expected behavior
1. The tiles should appear in the tile selection screen of at least one of the expansion (better in both).
2. The tiles should be available (the app should not crash as it usually does when a tile from a missing expansion is used) in play mode when at least one of the expansions is selected.

### Screenshots
![grafik](https://user-images.githubusercontent.com/58113888/103150394-10e2a780-4774-11eb-8a20-942c9288bcb7.png)

![grafik](https://user-images.githubusercontent.com/58113888/103150399-20fa8700-4774-11eb-869f-603abd7504db.png)

### Valkyrie Version
2.5.1

### Desktop
 - OS: Windows 10

### Additional information

The missing tile entries are:

```
[TileSide78A]
name="78A"
top=164
left=164
image="{import}/img/078A"
traits=outside swamp
reverse=TileSide78B

[TileSide78B]
name="78B"
top=164
left=164
image="{import}/img/078B"
traits=inside
reverse=TileSide78A

[TileSide79A]
name="79A"
top=151
left=151
image="{import}/img/079A"
traits=outside
reverse=TileSide79B

[TileSide79B]
name="79B"
top=72
left=72
pps=72
image="img/079B"
traits=inside
reverse=TileSide79A

[TileSideEntranceSwampA]
name="EntranceSwampA"
top=36
left=23
image="{import}/img/Entrance05"
traits=outside swamp
reverse=TileSideEntranceSwampB

[TileSideEntranceSwampB]
name="EntranceSwampB"
top=36
left=23
image="{import}/img/Entrance06"
```

**Comment by mayjak** [comment]
This happens, because when you select an expansion (let's say MoB) it excludes all the other expansions, TCTR included. That means the tile is on the excluded list. If you then click the X near TCTR - the tile will appear.

![image](https://user-images.githubusercontent.com/10874335/103252101-9dab8200-497b-11eb-8b69-2f941d5f48cd.png)
![image](https://user-images.githubusercontent.com/10874335/103252110-a603bd00-497b-11eb-9c93-c9e302d295a4.png)

Fix incoming soon.
