### ISSUE TITLE
[Bug] conditional disabling text on token with one option gives extra button

### ISSUE THREAD

**Issue by antontimmermans** [NPBruce/valkyrie#1423]
### Description
When a token has 1 button with text that is conditionally displayed depending on a variable, It adds an extra continue button:
![image](https://user-images.githubusercontent.com/42072372/103174585-af016b00-4863-11eb-9af8-89f3e21ae26c.png)

when the condition is met, the extra button disappears again:
![image](https://user-images.githubusercontent.com/42072372/103174606-d1938400-4863-11eb-8c7d-8eca371ca1ac.png)

If the same method is used in an event, no additional button is added.

### Steps to reproduce the behavior:

Code used:
```
[TokenCellarBaseHatchExplore]
xposition=12.25
yposition=14
operations=MoveOneSpaceAllowed,=,1
buttons=1
event1=EventCellarBaseHatchExplore
event1Condition=VarOperation:BrassKeyAvailable,==,1 
type=TokenExplore

```

### Expected behavior
Do not add an additional {continue]-button if the display condition of the one remaining button is not met. (just like with events).
The application already adds the [cancel]-button on a token, so the extra [continue]-button is not nieeded

### LogFile
n.a.

### Valkyrie Version
2.5.1

### Desktop
 - OS: Windows
 - Browser Chrome
 - Version 10

**Comment by Quantumrunner** [comment]
The continue button is a fallback @estarriol has added to ensure that the event still can be closed somehow. 

But for tokens this fallback is not necessary and should therefore not be used because tokens always have a cancel button.
