### ISSUE TITLE
[Feature] Make Vertical allignment default for new UI elements

### ISSUE THREAD

**Issue by antontimmermans** [NPBruce/valkyrie#1426]
## Is your feature request related to a problem? Please describe.**
When creating a new UI element, the default is Horizontal alignment. However, the horizontal alignment does not scale nicely with screen sizes and ratios. Especially if you add multiple overlapping elements for a homebrewed puzzle for example.

## Describe the solution you'd like
In my experience, the vertical alignment works perfectly with the various screen sizes/rations. To make life less confusing for new scenario writers (and my life easier so I don't have to change it every time) it would be nice if the default setting for new UI elements would be set to **vertical alignment**

![image](https://user-images.githubusercontent.com/42072372/103461532-4dd40e80-4d1f-11eb-9cd2-e1ad371a2dae.png)

`vunits=True`

**Comment by NPBruce** [comment]
This is always going to be tricky for authors to understand the scaling and work for everyone. Locking the aspect to 16x9 and using black bars might be a better approach.

**Comment by antontimmermans** [comment]
True, UI will never be easy. but fixing it to 16x9 will not make it much easier. 
In a UI like this: (**WARNING SPOILER**)

![image](https://user-images.githubusercontent.com/42072372/103478110-c50fae00-4dc4-11eb-9d16-2f667457af2e.png)

Positioning requires a lot of patience, trial, and error. The background + ritual circle is 1 image. Each candle, the flames on the candles, the book (...and all components that follow after this event), are separate UI components.

To position these:
1. I place a transparent sheet over my screen,
2. Mark the rough location of the elements
3. Place the smaller UI elements (guessed)
4. Run the scenario (test function) to see the result
5. move the smaller items in steps of 0,01 or 0.005 to move them to the correct position
6. repeat steps 4 & 5 a lot of times until it is done.

This is even more difficult when the images are positioned on the left side of the screen since the UI editor window is placed in that position.
What would help is a separate editor to move and position UI elements, where you
- that can toggle a transparent grid to support positioning.
- can select which items to visualize 
- position the UI elements with a mouse click,
- move them up, down, left, and right with [+}, [-] buttons for each direction
- set the size of the elements.


But that would be really a lot of work to create. Until then, I am happy enough with the default alignment to vertical, and in hope people read the section on UI placement in the Manual.
