### ISSUE TITLE
[Bug] Polish translation in app - minor issues

### ISSUE THREAD

**Issue by Hacai666** [NPBruce/valkyrie#1428]
### Describe the bug
There are some missing or wrong Polish translations in the app.

### Scenario

1. During the scenario download the text is wrong, it should be "Pobieranie pakietu..."
2. On the scenario selection screen there are some missing translations:
a) Average duration -> Średni czas trwania
b) Average win ratio -> Średnia ilość wygranych
c) xxx user reviews -> xxx ocen graczy

### Screenshots
1. 
![image](https://user-images.githubusercontent.com/42844499/103482842-79203180-4de3-11eb-8975-9b1bc231fd62.png)

2.
![image](https://user-images.githubusercontent.com/42844499/103482942-28f59f00-4de4-11eb-880a-e409f6368750.png)

### Valkyrie Version

2.5.1

### Desktop
 - OS: Windows 10
 - Browser: Chrome

**Comment by siepa3** [comment]
Some of this is addressed in PR https://github.com/NPBruce/valkyrie/pull/1427
Maybe we should consolidate the effort?

**Comment by Hacai666** [comment]
Sure, we can consolidate :)
