### ISSUE TITLE
Valkyrie crashes when loading a scenario

### ISSUE THREAD

**Issue by zaki850** [NPBruce/valkyrie#143]
After saving Lynch scenario and loading it the next day, either one of the two issues happen:
- Valkyrie crashes altogether 
- you cannot progress the scenario, i.e. after clicking on hints or explore tokens, nothing happens

Apart from that:
- Shoggoth's horror check does not work

**Comment by NPBruce** [comment]
Can you please provide a save game with this problem from %appData%\Valkyrie\Save?

**Comment by NPBruce** [comment]
Splitting the Shoggoth issue as #145

**Comment by NPBruce** [comment]
Can't reproduce and no save provided, reopen if you have additional information.

**Comment by zaki850** [comment]
[savemom.zip](https://github.com/NPBruce/valkyrie/files/936243/savemom.zip)

Save uploaded.

**Comment by zaki850** [comment]
I uploaded the save game. Sorry it took so long.

**Comment by NPBruce** [comment]
As this is a save from 0.7 and the save game system had significant changes in 0.8 I am going to leave this closed.  Please open a new issue if you encounter this again.
