### ISSUE TITLE
[Bug] Valkyrie Crashed

### ISSUE THREAD

**Issue by antontimmermans** [NPBruce/valkyrie#1431]
### Describe the bug
During playtesting of a new scenario, the Valkyrie app crashed. 
Prior to this playtest, I had many many click-throughs of the scenario and there was not a problem. This playtest,  I started the scenario not from the editor but from the new game menu (offline).
I also attached the crash dump to this issue.

The crash happened in the mythos phase. but I guess that is irrelevant, we had many mythos phases before.

### Scenario
New scenario 'Possessed'-> can be made available for test purposes on request

### Steps to reproduce the behavior:
?

### Expected behavior
not crash.

### Valkyrie Version
2.5.1

### Desktop
 - OS: Windows
 - Browser chrome
 - Version 10

**Comment by antontimmermans** [comment]
[Crashes.zip](https://github.com/NPBruce/valkyrie/files/5791842/Crashes.zip)
[output_log.txt](https://github.com/NPBruce/valkyrie/files/5791845/output_log.txt)

**Comment by mayjak** [comment]
Unfortunately it looks like an out of memory error during screenshot resize when Valkyrie autosaved your game on round start. OOM issues rarely fail on the exact logic that causes it, but I added changed the screenshot resize logic to use the GPU and less memory anyway.

The real fix would be to analyze Valkyrie memory usage with a memory profiler and fix leaks/circular references..

**Comment by antontimmermans** [comment]
The crash during autosave triggered me. I could load the auto-savegame without issues. I safeguarded the autosave. I can share it on request.

The last thing that happened was a Mythos phase event:
![image](https://user-images.githubusercontent.com/42072372/104181400-ffa1c800-540e-11eb-860e-56f89ebd35aa.png)

To be more precise: the investigator's turn just started.
I also checked the variables <ctrl><Alt>D. I did not see anything strange there either

**Comment by mayjak** [comment]
@antontimmermans are you sure it was not the autosave from the beginning of the previous turn? It crashed while preparing the screenshot for the autosave, so nothing was written to the disk at this point.

**Comment by antontimmermans** [comment]
I do not know exactly when the autosave is made but in sequence, this is what happened:

1. The Investigator round ended.
2. An event was triggered by EndInvestogatorTurn. This event determines via random selection to either set default mythos handling off (all $mythosxxxx variables=0) or to set (all $mythosFlavor=1) for default mythos events. In this case, the latter happened, the default Flavor mythos was selected.
3. Then monster activation phase was handled without issues
4. I cannot recall what happened in the horror phase tbh...
5. but the moment that we saw the investigation phase kick in (hearing the sound that is played at the start of that phase), the app crashed.
6. Then, 5 days later I was triggered by your remark of the autosave, I started the game by loading the autosave and inspected the log and the variables (ctrl+Alt+D). The screenshot above is from the variables of that autosave.

I there anything else I can do to support the investigation?

**Comment by mayjak** [comment]
Yeah. That checks out. Autosave is done right after the investigator turn starts so it explains the sound. Anyway, that would be it for now. I improved the image resize logic which took more memory than necessary and I'll need to spend some time with a memory profiler. I have all I need for now, thank you :)

**Comment by antontimmermans** [comment]
Crashed again
[Uploading Crash2.zip…]()

**Comment by mayjak** [comment]
It seems 2.5.2 fixed the issue. Please report back if it turns out not to be fixed properly.
