### ISSUE TITLE
[Scenario] O Mal que Nunca Dorme

### ISSUE THREAD

**Issue by Diesdooi** [NPBruce/valkyrie#1436]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [X ] Mansions of Madness
- [ ] Descent

https://github.com/Diesdooi/CenarioOMalQueNuncaDorme

The scenario is in PORTUGUESE.

**Comment by vidimus** [comment]
@Diesdooi, I think you must remove the blank spaces on the scenario name in order to be published.

**Comment by Diesdooi** [comment]
Thanks, @vidimus . I removed the spaces.

**Comment by vidimus** [comment]
@scrubbless

**Comment by scrubbless** [comment]
This has been published, should be there within an hour
