### ISSUE TITLE
New Scenario "Un temblor en la noche"

### ISSUE THREAD

**Issue by RealPolux** [NPBruce/valkyrie#1439]
New scenario for Mansions of Madness (Language spanish)

It's the first time I'm doing this, hope everything it's all right

https://github.com/RealPolux/TemblorNocheScenario

**Comment by vidimus** [comment]
@RealPolux el enlace no funciona. ¿Has puesto el repostorio como público?
_------_----------
Link is not working. Did you set your repository as public?

**Comment by RealPolux** [comment]
Ooops perdon, ya debería de poderse ver!
----
Oppps Sorry, It should works now!

**Comment by vidimus** [comment]
El nombre del archivo ini no coincide con el del archivo valkyrie, @RealPolux .

**Comment by RealPolux** [comment]
Vale, a ver si ahora está todo correcto!

**Comment by vidimus** [comment]
@scrubbless I think it's now ready.

**Comment by vidimus** [comment]
@scrubbless, this scenario is also waiting to be added to the app.

**Comment by scrubbless** [comment]
I have added this, should be listed within the hour

**Comment by scrubbless** [comment]
I made a mistake adding this, it should be listed within an hour
