### ISSUE TITLE
[Bug] Music not playing correctly when loading a game

### ISSUE THREAD

**Issue by Quantumrunner** [NPBruce/valkyrie#1440]
### Describe the bug
The main menu music starts playing instead of the correct music when you load a game.

Looks like the app is currently not saving the music state correctly and therefore uses the fallback to the main menu music when loading a game.

### Steps to reproduce the behavior:
1. Start a scenario.
2. Save the scenario
3. Reload the scenario
4. Minimize the app
5. Go back to the app

### Expected behavior
The correct music should play when loading a game (or at least no music). Not the main menu music.

### Valkyrie Version
2.5.1

### Desktop
 - OS: Windows 10

### Additional context
Theoretically just by analyzing the code the music starts when:
- you load the game
- a component that has music selected in the editor is triggered (event, etc)
Default quest music starts when:
- you change the quest
- you load the game and there is no other music playing when saving
- quest start event triggers (before "EventStart")
- you enter the main menu
- currently playing music ends in some conditions (I need to analyze this a bit more later).

**Comment by mayjak** [comment]
Technically right now it saves the currently played music and then plays default music in loop when the loaded track ends. But loading the game still needs to preserve music state properly.
