### ISSUE TITLE
New Scenario "La mansión de los sacrificios"

### ISSUE THREAD

**Issue by mmartinez3982** [NPBruce/valkyrie#1441]
### Description of Problem or Question
Hello, I would like this quest to be added to quest listing:
https://github.com/mmartinez3982/MAD_Map001

It's my very first quest and I would like to test it on my mobile with my friends. I'll correct the mistakes I find.

It's entirely in Spanish (my native language) but I'll probably translate it into English as soon as I am able to try it and check that everything is fine and of quality enough  to be played. I started this development one year ago and I decided to finish it now. Hope you upload and publish it.
Thanks in advance.

### Valkyrie Version
2.5.1

**Comment by vidimus** [comment]
@mmartinez3982 Edita el nombre del archivo. No se pueden poner nombres genéricos tipo "editorescenario1", ni usar acentos o caracteres especiales.
Renómbralo por ejemplo a "mansionsacrificios.valkyrie" e igual nombre en el .ini

**Comment by mmartinez3982** [comment]
@vidimus hecho

**Comment by vidimus** [comment]
> @vidimus hecho
Estupendo, gracias. A ver si scrubbless lee esto y sube tu escenario al servidor.

--------------------------------

Fine, thanks. @scrubbless, another scenario ready to be added to valkyrie.

**Comment by scrubbless** [comment]
Added, should be there within the hour
