### ISSUE TITLE
[Feature] Add 1ED conversion kit unique items to a separate expansion

### ISSUE THREAD

**Issue by mayjak** [NPBruce/valkyrie#1443]
FFG stopped shipping the 1st edition conversion kit with the base box. You need to print it yourself:
https://images-cdn.fantasyflightgames.com/filer_public/df/ef/dfef9919-aff8-41fd-bbc2-c0c97e905ad3/conversion_kit_investigator_cards.pdf
https://images-cdn.fantasyflightgames.com/filer_public/35/ac/35aca0a7-197b-41a8-a7e9-73bdf1ac1d49/conversion_kit_monsters_tokens.pdf
https://images-cdn.fantasyflightgames.com/filer_public/36/83/36839eb5-028a-4d57-883a-330effbbd60a/conversion_kit_unique_item_cards.pdf

It's also true for some non-english publishers, like the Polish one:
http://galakta.pl/download/MAD20_Zestaw_konw_Przedmioty(2).pdf

I saw someone complaining that a scenario required a unique item that didn't exist in the base box. It was there in mine, but the unfortunate thing is that "Duke" and "Flux Stabilizer" have the core game "tentacle" expansion symbol, not the 1st ed conversion "key" one.

## Is your feature request related to a problem? Please describe.**
- Scenario creators don't always know if the item is included in the base game or not as it's listed in the editor under Core. 
- Users are required to find a card that's not in the base box (they can print it, but it's probably not something you want to realize halfway during the game :) ).

## Describe the solution you'd like
Move the unique cards to a new "MoM1E-UniqueCards" expansion. However, this will crash Valkyrie for older scenarios, but is more informative to the scenario creators. Possibly make that expansion always preselected when you install/update to avoid the crashing issue.

## Describe alternatives you've considered
Add an empty "MoM1E-UniqueCards" expansion. That way content creators can mark it as required, but the cards physically stay in the base expansion so it does not affect existing scenarios.

## Additional context
Cheap move on FFG part :(

**Comment by NPBruce** [comment]
It is worth pointing out that these items are required by their conversion kit investigators. This means that a scenario shouldn't be using them at all, because there would be a duplicate issue.
