### ISSUE TITLE
[Feature] Increase translation recursion limit

### ISSUE THREAD

**Issue by antontimmermans** [NPBruce/valkyrie#1449]
## Related problem**
For ease of making translations, I use a lot of 'macros' in the localization file. In one case I seemed to bump into a limit.

The ouput.log file reported:
`ERROR Recursive loop limit reached translating {qst:EventBathroomBasePlaceTile.text}. Dictionary entry must be fixed.`

The affected code it was referring to is:
`EventBathroomBasePlaceTile.text,"{qst:BATHROOMPLACETILE}\n\n{qst:PLACE1TILE:{tl1}:{c:TileBathroomBase}} {qst:ADDDARKNESS}\n{qst:DISCARDUNIQUE:{wht}:{c:QItemBrassKey}}."`
This results in:
![Knipsel1](https://user-images.githubusercontent.com/42072372/106880457-aca0f500-66dc-11eb-80af-312c08d5fb78.PNG)

The involved macros are:
```
COFF,</color>
CCYAN,<color=Cyan>
PLACE1TILE,Place the {qst:CCYAN}{tl1}{qst:COFF} tile as indicated
ADDDARKNESS,and add {qst:CCYAN}Darkness Tokens{qst:COFF} to each space.
DISCARDUNIQUE,Discard the {qst:CCYAN}{wht} Unique Item{qst:COFF}
BATHROOMPLACETILE,The heavy padlock unlocks easily with the {c:QItemBrassKey} and you push open the hatch. You find yourself in the hallway, somewhere on the ground floor.
```
If I change the affected test to NOT use the {qst:ADDDARKNESS} but type its full text instead then it seems to process all properly. The resulting text looks then like:
`EventBathroomBasePlaceTile.text,"{qst:BATHROOMPLACETILE}\n\n{qst:PLACE1TILE:{tl1}:{c:TileBathroomBase}} and add {qst:CCYAN}Darkness Tokens{qst:COFF} to each space.\n{qst:DISCARDUNIQUE:{wht}:{c:QItemBrassKey}}."`
which outputs into:
![Knipsel2](https://user-images.githubusercontent.com/42072372/106880820-1e793e80-66dd-11eb-89ba-7ea1c08fdfdb.PNG)

## Describe the solution you'd like
I request to increase the recursion limit on translation so that it can handle also a little more complex string translations.

## Describe alternatives you've considered
I can work around this issue and use fewer text references or component references. This will lead to more work for people who wish to translate the scenario into another language.

**Comment by mayjak** [comment]
Bumping up to 20 from 10.
