### ISSUE TITLE
[Feature] Max number of players indicator

### ISSUE THREAD

**Issue by Hacai666** [NPBruce/valkyrie#1450]
## Is your feature request related to a problem? Please describe.**
When my friends come over to play Mansions of Madness scenario, I don't always know from the beginning for up to how many players a scenario can be played. The information only appears on the investigator selection screen. This is a problem, because some scenarios are for 3, 4, 5 or even 8 players and it would be good to know from the beginning how much people can play.

## Describe the solution you'd like
It would be nice to have an information about the maximum amount of players that can play a scenario already on the scenario selection screen.

Maybe it could be done by moving the difficulty and average win ratio info more to the left. Then there would be a place for the maximum players information.

![image](https://user-images.githubusercontent.com/42844499/107115598-0e449900-686e-11eb-937a-b313f81f44fc.png)

Also, it would be nice to have an additional sort criteria for the list by maximum player amount (ascending or descending)

![image](https://user-images.githubusercontent.com/42844499/107115702-bfe3ca00-686e-11eb-98e2-97b069c19014.png)

## Describe alternatives you've considered
If You have any interesting alternatives for this idea, please comment this issue :)

## Additional context
--

**Comment by vidimus** [comment]
And minimum too!

**Comment by BenRQ** [comment]
I agree this is a much welcome feature.

Please note that the text placement is done based on the size of text in **all languages**.
So your proposal is good for texts in English but not possible for French, German or other languages.

I would recommend increasing size of paper clip for each scenario to add this info.

**Comment by Hacai666** [comment]
> I would recommend increasing size of paper clip for each scenario to add this info.

I agree, I think that this would be the best solution.

**Comment by mayjak** [comment]
I think there's just enough space below the flags:
![image](https://user-images.githubusercontent.com/10874335/107864347-9d981080-6e5b-11eb-946f-68405fd5ef52.png)

It works even for longer titles as it's on the same line as "missing expansions".

**Comment by mayjak** [comment]
![image](https://user-images.githubusercontent.com/10874335/107864358-bdc7cf80-6e5b-11eb-8c3e-16b23c18b490.png)

**Comment by Hacai666** [comment]
> I think there's just enough space below the flags:
> ![image](https://user-images.githubusercontent.com/10874335/107864347-9d981080-6e5b-11eb-946f-68405fd5ef52.png)
> 
> It works even for longer titles as it's on the same line as "missing expansions".

Yep, also very good idea :)

**Comment by vidimus** [comment]
Brilliant!
