### ISSUE TITLE
[Scenario] Possessed

### ISSUE THREAD

**Issue by antontimmermans** [NPBruce/valkyrie#1453]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [x] Mansions of Madness
- [ ] Descent

**NOTE**: created with 2.5.2b

### Please enter the GitHub Url to your scenario here
https://github.com/antontimmermans/MOMPOS

**Comment by antontimmermans** [comment]
@scrubbless can you please add this to the scenario lists?

**Comment by scrubbless** [comment]
Added! You can add it to the stats sheet yourself Anton 😂
