### ISSUE TITLE
[Bug] filter doesn't work propertly

### ISSUE THREAD

**Issue by HenryTmartin2** [NPBruce/valkyrie#1455]
### Describe the bug
In latest release 2.5.2. If you select all or a few Boxed Expansions and no select conversion kit , then in select filters select a language (Spanish in my case)and if you click on Hide scenarios with missing expansions. You can not see any scenarios. If you don't click in this option, then appears scenarios but you cannot download it because you don't select the conversion kit.

### Steps to reproduce the behavior:
1. Go to Select content
2. Click on Boxed expansions
3. Select  all of then
4. Back to the main menu
5. Select New Game
6. Select filters
7. chose the language
8. Click on Hide scenarios with missing expansions
9. On left top appears 87 scenarios but no appears anything in the main window.
10. Go to Filters
11. unselect the option Hide scenarios with missing expansions
12. Click Ok
13. Now appears scenarios but all of then are forbiden for me because I haven't the kit conversion.
14. If I select the kit conversion I can see the scenarios and donwload it

### Valkyrie Version
2.5.2

### Desktop
 - OS: Windows 10

### Smartphone
 - Device: Smartphone
 - OS: Android 12

**Comment by BenRQ** [comment]
Reproduced in 2.5.2

**Comment by HenryTmartin2** [comment]
Ok. Good to know that it is not me. 🙂

So we will a new version soon, right?
Thanks in advance
Henry

**Comment by mayjak** [comment]
Well it is as intended. FFG is not shipping the conversion kit with the base game anymore (shame). We discussed this on Discord and decided that all "old" scenarios should have the Conversion Kit as a required expansion. The authors can "opt-out" of the conversion kit if they're not using it or the user can select the conversion kit if they have it (which will be like 90% of our users).

I'll revisit on how to do it better as I'm pretty sure only a handful of scenarios are using those few items/person tokens.

**Comment by mayjak** [comment]
Fixed in 2.5.3 release
