### ISSUE TITLE
[Scenario] Acaso do Deuses Antigos

### ISSUE THREAD

**Issue by malkavk** [NPBruce/valkyrie#1456]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

### Please enter the GitHub Url to your scenario here

https://github.com/malkavk/AcasoDosDeuses

**Comment by vidimus** [comment]
@scrubbless , could you please add this one to Valkyrie?

**Comment by malkavk** [comment]
There are some modifications on project structure and file names. I will close this issue and open another with new updates.
