### ISSUE TITLE
[Translation] Stress and Strain

### ISSUE THREAD

**Issue by andrex47** [NPBruce/valkyrie#1461]
### What kind of translation do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

### Stress and Strain

[Localization.Portuguese.txt](https://github.com/NPBruce/valkyrie/files/6003167/Localization.Portuguese.txt)
here is the updated file, and we have recorded our translated of the intro for this scenario which can be acessed here: https://drive.google.com/file/d/1gEhjYTDgG-1_p5_2fx1gHmRBaV_dLufj/view?usp=sharing
Please update @scrubbless  :D

**Comment by scrubbless** [comment]
Awesome, thank you. I'll get this updated with the changes and intro now!

**Comment by scrubbless** [comment]
Can you let me know who you would like to add to the credits? Voice actor/translators. I'll add it to the "Authors" section of the scenario in each language.

**Comment by scrubbless** [comment]
I have updated this and added the voice over, thank you for your hard work!
