### ISSUE TITLE
[Translation] Saviors

### ISSUE THREAD

**Issue by andrex47** [NPBruce/valkyrie#1463]
### What kind of translation do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

Saviors

### Translation File
[Localization.Portuguese.txt](https://github.com/NPBruce/valkyrie/files/6003374/Localization.Portuguese.txt)

**Comment by vidimus** [comment]
Good luck with this one, @ChinaMajesty is not answering. Spanish translation is finished and waiting from April'20

**Comment by andrex47** [comment]
good, i opened this issue just for registering it, i worked with him on this translation, and i already accepted the fact that the author may be gone for good, i shared this file and made a video tutorial on the brazilian board game portal to teach people how they have their scenario translated, if you already have both files i will close the issue
