### ISSUE TITLE
[Scenario] Acaso dos Deuses Antigos - PRÓLOGO

### ISSUE THREAD

**Issue by malkavk** [NPBruce/valkyrie#1464]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

### Please enter the GitHub Url to your scenario here
https://github.com/malkavk/AcasoDosDeusesAntigos-PROLOGO

**Comment by scrubbless** [comment]
I've added this
