### ISSUE TITLE
How to submit PotS tile and rooms translations to portuguese

### ISSUE THREAD

**Issue by malkavk** [NPBruce/valkyrie#1466]
### Description of Problem or Question

PotS tile and rooms translations to Portuguese are absent, but I located the correct file and done this translation (for rooms and tiles names). Could you replace the file (I'm sending attached to this issue) or how should I proceed?

### Valkyrie Version
2.5.3

### Localization file
[Localization_pt.txt](https://github.com/NPBruce/valkyrie/files/6047450/Localization_pt.txt)

**Comment by NPBruce** [comment]
This is actually an FFG problem, we don't have a way to add this. Can you try sending it to FFG?

**Comment by malkavk** [comment]
I sent the problem to FFG. They sent some screenshots with correct text (I confirmed on my local version).
Tiles, items, monsters, everything seems to be ok.

**Comment by malkavk** [comment]
FFG released an update and this problem was solved. 

But problem on bug #1465 remains.
