### ISSUE TITLE
[NEW SCENARIO] Issue-Memórias Corrompidas

### ISSUE THREAD

**Issue by WagnerMD** [NPBruce/valkyrie#1468]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [x ] Mansions of Madness
- [ ] Descent

### Please enter the GitHub Url to your scenario here
https://github.com/WagnerMD/MoMCenarios/tree/main/Mem%C3%B3riasCorrompidas

**Comment by vidimus** [comment]
The link is not working, @WagnerMD. It says "page not found".

Did you set your repository to "public"?

**Comment by WagnerMD** [comment]
Now it´s public, sorry...

**Comment by malkavk** [comment]
@WagnerMD, the files were sent unzipped. Use the package generation tool. Leave in the project only the cover image, .ini and .valkyrie files.

**Comment by WagnerMD** [comment]
https://github.com/WagnerMD/MemoriasCorrompidas

Now i hope it´s work xD

**Comment by malkavk** [comment]
@WagnerMD, não creio que aceitem nesse formato.

Lá no editor de cenário abra o teu cenário. Na parte de ferramentas tem o botão para "Criar pacote". Ele vai gerar (normalmente no desktop) uma pasta contendo o arquivo MemoriasCorrompidas.ini, o arquivo MemoriasCorrompidas.valkyrie e a imagem da capa 1.jpg. 

São esses 3 arquivos que vocês precisa fazer o upload.

Faz alguns dias que mandei um cenário meu e já está no ar. Olha esse link, para ver os arquivos necessários (o arquivo README.md é só a descrição do projeto, mas pode ser removido): https://github.com/malkavk/AcasoDosDeusesAntigos-PROLOGO.

Quando alguém manda baixar um cenário, se baixa apenas o .valkyrie. Os outros dois arquivos são baixados para mostrar naquela lista. Então são apenas esses 3 arquivos. A forma como você colocou é usado apenas durante a edição.

As instruções estão certinhas nesse link: https://github.com/NPBruce/valkyrie/wiki/QuestPublish.

**Comment by WagnerMD** [comment]
https://github.com/WagnerMD/MoMMemoriasCorrompidas/tree/main/Mem%C3%B3riasCorrompidas

FINALMENTE compreendi 
MUITO obrigado pela ajuda e me desculpe todo o transtorno, é a minha primeira vez hahaha
otima semana

**Comment by WagnerMD** [comment]
https://github.com/WagnerMD/MoMMemoriasCorrompidas/tree/main/Mem%C3%B3riasCorrompidas

Now it´s OK... thanks for the help

**Comment by scrubbless** [comment]
Hi @WagnerMD 

The scenario path has spaces or special characters in it that are not compatible with valkyrie (notice %C3 and %B3 in your scenario path). Can you rename the scenario using non accented characters, reupload and relink it please.

Once the path is fixed I'll add the scenario.

**Comment by scrubbless** [comment]
Ok it has been added, this will show in the list within the hour.
