### ISSUE TITLE
[Question] Where can editors see reviews?

### ISSUE THREAD

**Issue by malkavk** [NPBruce/valkyrie#1469]
### Description of Problem or Question
Where can editors see posted reviews?
On the quest selection list, we can see the quantity of reviews and notes, but where can we see the texts of these reviews?

### Valkyrie Version
2.5.3

**Comment by vidimus** [comment]
https://docs.google.com/spreadsheets/d/1OsevlouIvR0DRYhGIS41PU9lBLB8VYgJvyj9KsHcAik/htmlview#gid=1035295975

"(Spoilers) Reviews information" tab

**Comment by malkavk** [comment]
Thx
