### ISSUE TITLE
[Translation] Affairs of Wizards (Spanish translation)

### ISSUE THREAD

**Issue by vidimus** [NPBruce/valkyrie#1471]
### What kind of translation do you want to add (mark with an X, e.g. [X] Descent)?
- [ ] Mansions of Madness
- [X ] Descent

### Affairs of Wizards
[https://github.com/NPBruce/valkyrie-store/tree/master/D2E/affairsofwizards](url)
@NPBruce 

### 
[Localization.Spanish.txt](https://github.com/NPBruce/valkyrie/files/6133469/Localization.Spanish.txt)

**Comment by NPBruce** [comment]
Done.
