### ISSUE TITLE
[Translation] O Resgate Sombrio!(Korean)

### ISSUE THREAD

**Issue by cheeseguyhcl** [NPBruce/valkyrie#1472]
### What kind of translation do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

### Scenario name or url
O Resgate Sombrio!
https://github.com/Bigdadd1/mapa_mom_oresgatesombrio/tree/master/ResgateSombrio

### Translation File
[Localization.Korean.txt](https://github.com/NPBruce/valkyrie/files/6134780/Localization.Korean.txt)

**Comment by vidimus** [comment]
I've sent a message to the author to notice him this translation, @cheeseguyhcl

**Comment by vidimus** [comment]
@cheeseguyhcl  scenario updated!

**Comment by cheeseguyhcl** [comment]
thank you!
