### ISSUE TITLE
[Translation] La Casa Infestata(Korean)

### ISSUE THREAD

**Issue by cheeseguyhcl** [NPBruce/valkyrie#1473]
### What kind of translation do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

### Scenario name or url
La Casa Infestata

### Translation File

[Localization.Korean.txt](https://github.com/NPBruce/valkyrie/files/6134787/Localization.Korean.txt)

**Comment by vidimus** [comment]
I've sent a message to the author to notice him this translation, @cheeseguyhcl

**Comment by vidimus** [comment]
Korean translation is now online. You can close this issue, @cheeseguyhcl

**Comment by cheeseguyhcl** [comment]
ok thank you!
