### ISSUE TITLE
[Translation] L'Ultima Cena(Korean)

### ISSUE THREAD

**Issue by cheeseguyhcl** [NPBruce/valkyrie#1474]
### What kind of translation do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

### Scenario name or url
L'Ultima Cena

### Translation File
[Localization.Korean.txt](https://github.com/NPBruce/valkyrie/files/6134796/Localization.Korean.txt)

**Comment by scrubbless** [comment]
Hi @blueadamantine I believe this is yours

**Comment by blueadamantine** [comment]
> Hi @blueadamantine I believe this is yours

Yes, it is. Thanks, @scrubbless.

**Comment by blueadamantine** [comment]
@cheeseguyhcl Thank you so much for translating my scenario! I'm pleasingly surprised. :smiley: I've updated the scenario with your translation.

**Comment by cheeseguyhcl** [comment]
> @cheeseguyhcl Thank you so much for translating my scenario! I'm pleasingly surprised. 😃 I've updated the scenario with your translation.

Hi! not yet been updated😭 check Please

**Comment by blueadamantine** [comment]
Sorry, I forgot to update the quest file, but I remedied it. I've having some issues because Valkyrie is being updated and it's messing some things up. Vidimus and me are working on that. Thanks for your patience.

**Comment by vidimus** [comment]
![Screenshot_2021-03-30-16-18-09-92_21bd9e02371ed2328b4f345f7a47735e](https://user-images.githubusercontent.com/41538948/113004359-d96d0800-9173-11eb-8fd7-c344a9fe169c.jpg)
![Screenshot_2021-03-30-16-17-26-77_21bd9e02371ed2328b4f345f7a47735e](https://user-images.githubusercontent.com/41538948/113004371-da9e3500-9173-11eb-8f70-482b8df6a4f2.jpg)
@cheeseguyhcl , it's up. Please, check it to be sure it's working fine
