### ISSUE TITLE
[Translation] The Stand(Korean)

### ISSUE THREAD

**Issue by cheeseguyhcl** [NPBruce/valkyrie#1476]
### What kind of translation do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

### Scenario name or url
The Stand
https://raw.githubusercontent.com/GwanGwanish/Mansions2/master/TheStand/

### Translation File
[Localization.Korean.txt](https://github.com/NPBruce/valkyrie/files/6134986/Localization.Korean.txt)

**Comment by scrubbless** [comment]
Hi @GwanGwanish one for you :)

**Comment by vidimus** [comment]
> Hi @GwanGwanish one for you :)

I've sent him a message here and another on the BGG, but he seems to be offline. There's another scenario with a pending Korean update (Footsteps in the Dark).

**Comment by vidimus** [comment]
Gwan has answered on the bgg. He will take a look to the translations, he said.

**Comment by vidimus** [comment]
It looks he skipped this one. The other scenario has been updated.

**Comment by vidimus** [comment]
@cheeseguyhcl , Gwan has just update the scenario with the translation. You could close this issue.

**Comment by cheeseguyhcl** [comment]
thank you!
