### ISSUE TITLE
[Translation] Believe or Die - A Search for Ashcan Pete(Korean)

### ISSUE THREAD

**Issue by cheeseguyhcl** [NPBruce/valkyrie#1477]
### What kind of translation do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

### Scenario name or url
Believe or Die - A Search for Ashcan Pete
https://github.com/FASTNAVi/Believe_or_Die_1/issues/1

### Translation File
[Localization.Korean.txt](https://github.com/NPBruce/valkyrie/files/6135417/Localization.Korean.txt)

**Comment by vidimus** [comment]
@FASTNAVY

**Comment by vidimus** [comment]
I've sent to the author a message on discord.

**Comment by FASTNAVi** [comment]
It is done.

**Comment by cheeseguyhcl** [comment]
thanks guys!
