### ISSUE TITLE
[Translation] MutantMadness

### ISSUE THREAD

**Issue by Crosisdepurger** [NPBruce/valkyrie#1478]
### What kind of translation do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

Mutant Madness
https://github.com/Crosisdepurger/Mansios

### Translation File
[Localization.Spanish.txt](https://github.com/NPBruce/valkyrie/files/6141557/Localization.Spanish.txt)

**Comment by vidimus** [comment]
@Crosisdepurger You can close this one, the translation has been upload.
