### ISSUE TITLE
[Scenario] Claustrofobia

### ISSUE THREAD

**Issue by Diesdooi** [NPBruce/valkyrie#1482]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

https://github.com/Diesdooi/Claustrofobia

The scenario is in Portuguese

**Comment by vidimus** [comment]
@scrubbless

**Comment by scrubbless** [comment]
Hi @Diesdooi the scenario name contains accented characters that aren't available in web format. This prevents the path from being accessible by valkyrie.

Notice %C3 etc:
https://github.com/Diesdooi/AteoUltimoCentavo/blob/main/Ateo%C3%9AltimoCentavo.ini

Can you please rename your scenario folder in %appdata% to a name without accents or spaces, create a new package and publish to GitHub.

Once the path is fixed I should be able to publish this to the scenario explorer.

**Comment by Diesdooi** [comment]
@scrubbless I decided to give a new name to my scenario, ok?

**Comment by vidimus** [comment]
> @scrubbless I decided to give a new name to my scenario, ok?

I think now it's fine, isn't it, @scrubbless ?

**Comment by scrubbless** [comment]
Looks good to me, I've added this. Should be with you within the hour
