### ISSUE TITLE
[Feature] Custom tile sets

### ISSUE THREAD

**Issue by lhassell** [NPBruce/valkyrie#1483]
## Is your feature request related to a problem? Please describe.**
I would like to implement a system to allow creating new tile sets for the game. For example, an Egyptian-themed tomb setting, or maybe an Antarctic base. Creating the tiles themselves would not be terribly difficult, and I think I even have a hand on how to create the appropriate tiles.ini file. The difficulty is not having a method to have Valkyrie recognize the new content.

## Describe the solution you'd like
A system, similar to the Editor, that would allow a tile set to be created and packaged, either to include in an adventure, or possibly even separately to be available for other adventures.

## Describe alternatives you've considered
I don't know of any alternatives to this that are available. 

## Additional context
Because I see this as coming up in the discussion, the new tiles could either be self-printed (I did this myself for the Suppressed Memories tiles), or alternatively could be used in a virtual tabletop or other video device.

**Comment by NPBruce** [comment]
You mention creating a tiles.ini, you can use this to create a custom expansion which will do exactly what you want. There are only two missing features.

1: A graphical expansion editor. Honestly I can't see this being worthwhile. It isn't too hard to set it up by hand and the effort to create a robust editor is not reasonable for the gain.

2: A method to distribute custom expansions. This could be helpful if there is a published custom expansion that multiple people are printing, but this isn't something I've seen yet (at least for MoM, it is more of a thing for D2E). #519 is to support this, but hasn't seen enough interest to progress so far.

I'm going to close this as not going to implement (but will reference it in #519). Let me know if I have misunderstood.
