### ISSUE TITLE
New Quest Ready for Publish

### ISSUE THREAD

**Issue by MatthewThornton** [NPBruce/valkyrie#1486]
Descent Quest ready for publish.

https://github.com/MatthewThornton/Valkyrie_Goblin_Raid

**Comment by vidimus** [comment]
@MatthewThornton Your previous quest wasn't published (Vault dragon treasure) because you didn't change the file names. Would you mind to fix that issue in order to have it published?

**Comment by vidimus** [comment]
@scrubbless

**Comment by scrubbless** [comment]
I've added this to the manifest, should be listed within the hour
