### ISSUE TITLE
[New] A custom quest for Descent 2nd edition (in French)

### ISSUE THREAD

**Issue by BenoitLeoutre** [NPBruce/valkyrie#1490]
### Description of Problem or Question

Valkyrie Version : 

Hello there,

I tried to follow the tutorials and managed to package a small independent quest for Descent, in order to expand the french resources. Would it be possible to look at it ?

The ini file is here : 
https://easyupload.io/aga4an

The valkyrie file is here : 
https://easyupload.io/788jct

Let me know if I failed somewhere or if it isn't the proper way to submit a new quest.

Best regards,

**Comment by NPBruce** [comment]
Hi, you need to have the .valkyrie, .ini and thumbnail (if you have one) all in the same directly linkable location. This can be done with github, just create a repository and add the files. Doing it this way means that you can then update your project at any time without raising an issue.

**Comment by vidimus** [comment]
@BenoitLeoutre : plus, you need to change the file name. Names such as Editorcenario1.valkyrie are not allowed.
Rename the file with the scenario title, i.e., but please, do not use special characters like ê, ç or ñ

**Comment by BenoitLeoutre** [comment]
Well, I tried to correct it, and here it is : https://github.com/BenoitLeoutre/FestivalDeSang

Is it better ?

**Comment by vidimus** [comment]
> Well, I tried to correct it, and here it is : https://github.com/BenoitLeoutre/FestivalDeSang
> 
> Is it better ?

I think it is.  @scrubbless, is everything OK for publishing this Descent'quest?

By the way, I had a look to your quest and it looks great. Could I make the Spanish translation of your scenario? Not right now, but after you get some feedback or make any fixes (a couple of weeks?)

**Comment by scrubbless** [comment]
I believe so, I'll add it now

**Comment by BenoitLeoutre** [comment]
> > Well, I tried to correct it, and here it is : https://github.com/BenoitLeoutre/FestivalDeSang
> > Is it better ?
> 
> I think it is. @scrubbless, is everything OK for publishing this Descent'quest?
> 
> By the way, I had a look to your quest and it looks great. Could I make the Spanish translation of your scenario? Not right now, but after you get some feedback or make any fixes (a couple of weeks?)

Yes, of course I can, I would be honoured. Best regards,
