### ISSUE TITLE
[Bug] Empty texts when default language is not english

### ISSUE THREAD

**Issue by Quantumrunner** [NPBruce/valkyrie#1492]
### Describe the bug
There is a problem with language selection. I just started the scenario Festival De Sang for Descent while having english language set as UI language for Valkyrie. All text in the scenario where empty.

The texts are shown correctly when switching to French UI language.

### Scenario
Festival de Sang (Descent)

### Steps to reproduce the behavior:
1. Set UI language in Valkyrie to english.
2. Start a scenario which has only non english texts (e.g. _Festival de Sang_ for Descent).

### Expected behavior
The default language of a quest should always be used if the currentl selected language is not available.

### Screenshots
![grafik](https://user-images.githubusercontent.com/58113888/115961231-cd2b5f00-a515-11eb-8c43-e43367452ded.png)

### Valkyrie Version
2.5.5

**Comment by vidimus** [comment]
It happens the same in "Claustrofobia",  a MoM scenario that it's in Portuguese
