### ISSUE TITLE
[Scenario] Scape Mansion

### ISSUE THREAD

**Issue by davidfraj** [NPBruce/valkyrie#1494]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

### Please enter the GitHub Url to your scenario here
https://github.com/davidfraj/scapeMansion

**Comment by vidimus** [comment]
Great, a escape room in Spanish! 

@scrubbless , would you mind to add this one to Valkyrie?

**Comment by scrubbless** [comment]
Added to the manifest, should be listed within the hour
