### ISSUE TITLE
[Scenario] Bleu Cauchemars

### ISSUE THREAD

**Issue by Dokadilike** [NPBruce/valkyrie#1495]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
A Mansion of Madness Mission.

### Please enter the GitHub Url to your scenario here
BleuCauchemarScenario/BleuCauchemar.valkyrie

**Comment by Dokadilike** [comment]
https://github.com/Dokadilike/BleuCauchemars/blob/18dece67fb1d55f0aeec63aeb58133a953cefabb/BleuCauchemarScenario/BleuCauchemar.valkyrie

**Comment by scrubbless** [comment]
I've added this to the manifest, should be listed within the hour

**Comment by vidimus** [comment]
It's not on the scenario list, @Dokadilike 
Did you change the scenario files after they were published? Because I see them on your repository but not on Valkyrie

**Comment by Dokadilike** [comment]
Huh I don't know 😭 I don't understand anything, I'm trying to do my best
to publish it but it seems like I'll never do it right...

**Comment by scrubbless** [comment]
That's odd, the path looks correct to me

**Comment by Dokadilike** [comment]
I'm so sorry for my incompetence 😭

**Comment by BenRQ** [comment]
@scrubbless it's missing the  "external=" before the link.

I got an alert from the google script.

**Comment by scrubbless** [comment]
🤦‍♂️
Sorry my bad
