### ISSUE TITLE
[Bug] OMalqueNuncaDorme removed from manifest, due to unavailability

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#1496]
I have removed OMalqueNuncaDorme from the manifest @diesdooi, it is giving a 404 error. I can only assume that you've either deleted/renamed your repo or have made it private. 

Please restore this scenario or send me a working link and I'll read it.

Entry removed:

[OMalqueNuncaDorme]
external=https://raw.githubusercontent.com/Diesdooi/CenarioOMalQueNuncaDorme/main/

**Comment by scrubbless** [comment]
Closing this off, but please feel free to reply here or create a new issue when you'd like the scenario restored

**Comment by scrubbless** [comment]
Just looked a bit more into this and it looks like the Valkyrie and ini files no longer exist in the repo.

![image](https://user-images.githubusercontent.com/32058089/117138626-32e3da80-ada3-11eb-80cd-850a0e840019.png)

**Comment by Diesdooi** [comment]
Hello Scrubbles. I am trying update a new version of spanish translation made by Vidimus (with audios) bit a have a problem. Aparently i cant upload files biggers than 25mb to the github repository (and this file, with spanish Voice, is 40mb). Van you help me?

Obter o Outlook para Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by vidimus** [comment]
@Diesdooi What about compressing the audios lowering the quality? Some of the ambiance sounds are quite heavy and I think they can be easily edited to ligthen them.

**Comment by scrubbless** [comment]
This is confusing, a strain on reality is 72mb in size.
How are you uploading?

**Comment by scrubbless** [comment]
I suspect itay be a size limit on the web interface, but there isn't such a limit with git push commands or the GitHub desktop interface.

**Comment by vidimus** [comment]
> I suspect it may be a size limit on the web interface, but there isn't such a limit with git push commands or the GitHub desktop interface.

I tried with the GithubDesktop and as you commented, I was able to upload the file without any problem, with its 47Mb

The files are here:
https://github.com/vidimus/Valkyrie-Mom-scenarios-translations/tree/master/OMalqueNuncaDorme

**Comment by Diesdooi** [comment]
Okay, its done. How Scrbbless said, the limit of 25mb is for the browser version.

I've created this new link, with the files:

https://github.com/Diesdooi/O-Mal-Que-Nunca-Dorme-revisto

@scrubbless can you please syncronize it?

**Comment by scrubbless** [comment]
I'll add now, but in the future don't rename the scenario or repository when updating and it will update automatically in the lists.

(Doesn't matter this time as I need to reads anyway).

**Comment by scrubbless** [comment]
Readded
