### ISSUE TITLE
[Scenario] El baile de máscaras de la baronesa

### ISSUE THREAD

**Issue by Anxelog** [NPBruce/valkyrie#1501]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [ x] Mansions of Madness
- [ ] Descent

### What expansions does the scenario require?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [x ] Beyond the Threshold (BtT)
- [x ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### What expansions can the scenario optionally use?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### Please enter the GitHub Url to your scenario here
https://github.com/Anxelog/bailemascarasbaronesa.git

**Comment by vidimus** [comment]
@Anxelog the repository is not accesible. Did you change the options for making the repository public?

**Comment by Anxelog** [comment]
@vidimus Había subido mal los archivos. A ver ahora.

**Comment by vidimus** [comment]
@Anxelog Now it seems to be OK. @scrubbless could you add this one, please?

_---------

Parece que ahora sí que está bien.

**Comment by vidimus** [comment]
@Anxelog He mirado el escenario y hay un problema con los textos. Sólo aparecen algunas frases y el archivo Localization.Spanish.txt, que contiene el texto del escenario tiene muy pocas entradas, apenas unas 20.
Al poner el escenario sale esto:
![Screenshot_2021-06-13-19-47-08-15_21bd9e02371ed2328b4f345f7a47735e](https://user-images.githubusercontent.com/41538948/121844013-92f36800-cce3-11eb-8c3b-9eac8cea1553.jpg)
![Screenshot_2021-06-13-19-47-27-16_21bd9e02371ed2328b4f345f7a47735e](https://user-images.githubusercontent.com/41538948/121844017-938bfe80-cce3-11eb-89ec-6f8eaac8505c.jpg)
![Screenshot_2021-06-13-19-54-00-27_21bd9e02371ed2328b4f345f7a47735e](https://user-images.githubusercontent.com/41538948/121844022-94bd2b80-cce3-11eb-9769-83becb052c94.jpg)
![Screenshot_2021-06-13-19-55-02-66_21bd9e02371ed2328b4f345f7a47735e](https://user-images.githubusercontent.com/41538948/121844029-95ee5880-cce3-11eb-89a9-604afc1887b7.jpg)
![Screenshot_2021-06-13-19-53-11-81_21bd9e02371ed2328b4f345f7a47735e](https://user-images.githubusercontent.com/41538948/121844037-9850b280-cce3-11eb-8619-fe709ccdd2bc.jpg)

Prueba a hacer otra vez el paquete del escenario y súbelo al repositorio.

**Comment by Anxelog** [comment]
Recibido, Vidimus. Y muchas gracias por tu trabajo.

vidimus ***@***.***> escreveu no dia segunda, 14/06/2021 à(s)
07:39:

**Comment by Anxelog** [comment]
Problema corregido. Explico lo que ocurrió, por si es de utilidad. Al crear el escenario algunas veces tenía la aplicación Valkyrie en Inglés (al usarla como jugador, a veces la prefiero en Inglés) y otras en Español, de modo que fueron creados dos archivos Localization y la información se repartió entre ambos.

La solución, que entenderás tú mejor que yo, ha sido pasar todo lo almacenado en el archivo de Localization en Inglés al de Localization en Español.

Vidimus, aprovecho para agradecerte encarecidamente las horas que tú e imagino que bastantes otras personas dedicáis a que Valkyrie funcione tan bien. Son muchas horas de entretenimiento de primera calidad y asequible las que posibilita vuestro esfuerzo. Por mi parte, este verano intentaré elaborar un escenario un poco más sesudo que este, que inicialmente sólo era un trasteo para familiarizarme con el editor, pero que a mí y mi grupo nos pareció que quedó lo suficientemente bien como para compartirlo.

Un abrazo.

Ánxelo

**Comment by scrubbless** [comment]
I'll add this, sorry for the delay.

I like the new question form for adding scenarios btw!

**Comment by scrubbless** [comment]
Added, this should be listed within the hour.

**Comment by scrubbless** [comment]
I've rolled this back for the short term, just to see if its causing the issues with the SE reported in #1502

**Comment by vidimus** [comment]
> I've rolled this back for the short term, just to see if its causing the issues with the SE reported in #1502

Scenario list is now showed

**Comment by mayjak** [comment]
That's because the new scenario's default language is English in the ini, but it doesn't support English language.

The scenario list tries to use the user's language and falls back to scenario's default if the user's language is not supported. It won't try to find anything else. Fixing the ini file should fix the problem for now. I'll try to properly fix it with the next release.

**Comment by vidimus** [comment]
> That's because the new scenario's default language is English in the ini, but it doesn't support English language.
> 
> The scenario list tries to use the user's language and falls back to scenario's default if the user's language is not supported. It won't try to find anything else. Fixing the ini file should fix the problem for now. I'll try to properly fix it with the next release.

In this case (and at least twice before with Italian authors) is because the author switch between English and Spanish, depending if he/she is going to play or to use the editor, so the editor creates a different localization.txt if they forget to set back to the language they use first time when  the scenario was created.

**Comment by vidimus** [comment]
@Anxelog You need to create the package again to generate a valid .ini file, because just copy pasting the missing text did not fix the problem.

**Comment by Anxelog** [comment]
First of all, I apologise for the troubles caused. I think the problem of language incoherence among the package files is now solved. Check it out, please!

You all do a wonderful job, by the way.

**Comment by mayjak** [comment]
@Anxelog  @scrubbless Thank you, both the .ini and .valkyrie files look good now. I think it's good to go.

**Comment by vidimus** [comment]
> @Anxelog @scrubbless Thank you, both the .ini and .valkyrie files look good now. I think it's good to go.

@scrubbless Can you add the scenario to Valkyrie?

**Comment by scrubbless** [comment]
I've added and looks fine now. Thanks

**Comment by antontimmermans** [comment]
Added scenario to statistics overview https://docs.google.com/spreadsheets/d/1BXDqQ4lpS3pG5SvwlRhkNtvw-xbmTH1E6c72tXuvpF8/edit?usp=sharing
