### ISSUE TITLE
[Scenario Update] El baile de máscaras de la baronesa

### ISSUE THREAD

**Issue by Anxelog** [NPBruce/valkyrie#1504]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [ x] Mansions of Madness
- [ ] Descent

### What expansions does the scenario require?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [x ] Beyond the Threshold (BtT)
- [ x] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### What expansions can the scenario optionally use?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### Please enter the GitHub Url to your scenario here
https://github.com/Anxelog/bailemascarasbaronesa

Guys, it's an update and not a new scenario.

**Comment by vidimus** [comment]
@Anxelog there's no need to open a new issue for updating. Files are automaticaly update when you upload the new version of you scenario

**Comment by Anxelog** [comment]
Got it! Sorry about that. I close this issue immediately
