### ISSUE TITLE
[Question] Compatibility with different Android versions

### ISSUE THREAD

**Issue by rubencolmenarejo** [NPBruce/valkyrie#1506]
Hi,

I have an old Android tablet. I think with Android 4.1 version.

Where may I check the compatibility of Valkyrie with the Android versions?

When I try to install the apk file there is an error and the packet is not installed.

### Description of Problem or Question
The apk file is not installed. there is no error about it.

### Valkyrie Version
2.5.6 

Thanks in advance.
rubenC

**Comment by NPBruce** [comment]
Sorry, looks like unity needs Android 4.4, I don't think this is fixable.
