### ISSUE TITLE
Infección (New Scenario)

### ISSUE THREAD

**Issue by DaniMassaro** [NPBruce/valkyrie#1508]
Hello!

I would like to publish my third scenario.

Thank you.

### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [x ] Mansions of Madness
- [ ] Descent

### What expansions does the scenario require?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### What expansions can the scenario optionally use?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### Please enter the GitHub Url to your scenario here
https://github.com/DaniMassaro/Infeccion/tree/master/Infecci%C3%B3n

**Comment by vidimus** [comment]
@DaniMassaro, please, change the valkyrie file name. No special characters are allowed. In this case, set infeccion.valkyrie instead of infección.valkyrie.
_-----------------
@DaniMassaro, tienes que quitar el acento en el nombre del archivo. No se admiten los caractered especiales. Cambia infección.valkyrie por infeccion.valkyrie

**Comment by DaniMassaro** [comment]
https://github.com/DaniMassaro/Infeccion/tree/master/Infeccion

Changed! I hope it works correctly now. Thank you vidimus!

**Comment by vidimus** [comment]
> https://github.com/DaniMassaro/Infeccion/tree/master/Infeccion
> 
> Changed! I hope it works correctly now. Thank you vidimus!

Yw, @DaniMassaro 

@scrubbless could you please add this scenario to Valkyrie?

**Comment by antontimmermans** [comment]
Scenario added to Manifest, should be downloadable in about 1 hr.

**Comment by antontimmermans** [comment]
Scenario added to the statistics and dashboard sheets. Issue can be closed

**Comment by DaniMassaro** [comment]
Thank you!
