### ISSUE TITLE
[Question] What is the purpose of "hidden" property of a scenario?

### ISSUE THREAD

**Issue by malkavk** [NPBruce/valkyrie#1509]
### Description of Problem or Question

Creating a new scenario, second property is "hidden". What is its purpose and how to use it to improve a scenario? Is there some tutorial/documentation/address explaining it?

### Valkyrie Version

2.5.6

**Comment by NPBruce** [comment]
https://github.com/NPBruce/valkyrie/wiki/QuestIniQuest#hidden

It prevents the scenario from being shown to players. This is for a two part scenario or campaign. You can move scenarios into subdirectories to package them together, and have one scenario start another in an event. The investigators cary over.
