### ISSUE TITLE
[Scenario] El Elegido

### ISSUE THREAD

**Issue by Yosoymesmer** [NPBruce/valkyrie#1510]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

### What expansions does the scenario require?
- [ ] Conversion Kit (CK)
- [X] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### What expansions can the scenario optionally use?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### Please enter the GitHub Url to your scenario here

https://github.com/Yosoymesmer/MdlL_El_elegido

**Comment by vidimus** [comment]
@antontimmermans,  could you add this one to Valkyrie? Thanks

**Comment by antontimmermans** [comment]
Scenario added to the Manifest. Should be downloadable within max 1 hr

**Comment by antontimmermans** [comment]
Scenario added to the Analysis sheets. Issue can be closed

**Comment by Yosoymesmer** [comment]
> Scenario added to the Analysis sheets. Issue can be closed

Thanks!
