### ISSUE TITLE
[Scenario] Horror Haunts Vanderbilt Mansion

### ISSUE THREAD

**Issue by Drake3** [NPBruce/valkyrie#1511]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [ x] Mansions of Madness
- [ ] Descent

### What expansions does the scenario require?
- [x] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### What expansions can the scenario optionally use?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### Please enter the GitHub Url to your scenario here
https://github.com/Drake3/MOM/tree/master/Vanderbilt_Mansion

**Comment by antontimmermans** [comment]
Added to manifest. Should be downloadable in ~1 hr

**Comment by antontimmermans** [comment]
Added Scenario to analytics sheets... issue can be closed
