### ISSUE TITLE
[Feature] If a scenario includes a tile from a downloaded package and the package is not installed, Valkyrie crashes before checking the #variable

### ISSUE THREAD

**Issue by NicolaZee** [NPBruce/valkyrie#1512]
### Description of the Issue
With the standard expansions, if a tile is included in a scenario from an expansion that is not one of the scenario required expansions, a crash is prevented by checking the expansion flag.  For example, if a scenario only requires the base scenario, it is possible to include as an optional variation a tile from say Streets of Arkham.   If the user has the SoA expansion, the SoA tile will be displayed if the #SoA flag is set.

With the package Terror along the Nile, if the package is not installed, Valkyrie immediately crashes on loading the scenario and this occurs BEFORE the Tatn flag is checked. 

### Steps to reproduce the Issue:
Download the Terror Along the Nile package.
Add any base tile and display it as part of start-up.
Add a any TatN tile but do not display it as part of the scenario
Remove the TatN package.
Run the scenario and Valkyrie crashes.

### Expected behavior
The way Valkyrie works for user made expansions should be the same as for the standard expansions.
It should be possible to include user created packages and check if the package has been installed.

### A possible fix
One possible workaround is to have two blank default images.  A blank small tile and a blank medium tile.  If a tile is not found, then default to the appropriate blank tile image.  In theory, the user will never see the blank tiles but if they do it is not a big issue and it is better than having Valkyrie crash.

**Comment by NPBruce** [comment]
I can't reproduce this, can you attach a scenario which demonstrates the problem?

**Comment by NicolaZee** [comment]
The scenario does crash in the editor if a tile is included from tatn and tatn is not installed.

When trying to work out what was happening, I then got very confused and set the Tatn expansion as a required expansion.
After removing the tatn from the list of required expansions and running it from normal mode it worked OK.
And I still don't know if it should crash in the editor but as it is now working when run I'm not going to worry about it.
So. I'm going to close the call.

I am, though, going to raise a request for Valkyrie not to crash if a tile cannot be found.
