### ISSUE TITLE
Unable to install on Android

### ISSUE THREAD

**Issue by shawnablue** [NPBruce/valkyrie#1514]
I have an Android tablet. I understand I have to run the main MoM app, which I did. I enabled installation from unknown sources. But when I try to run the .apk, I just get "app not installed." 

I've never had Valkyrie installed before.

### Valkyrie Version
Most recent

### Attach Save, Quest or Scenario
Log File:
%LOCALAPPDATA%Low\NA\Valkyrie\output_log.txt
Saves:
%appdata%/Valkyrie/MoM/Save
%appdata%/Valkyrie/D2E/Save
Quest:
%appdata%/Valkyrie/D2E/Editor
Scenario:
%appdata%/Valkyrie/MoM/Editor

**Comment by NPBruce** [comment]
What android version do you have? 11 is not supported.

**Comment by shawnablue** [comment]
Definitely not 11, it's an older tablet.

**Comment by friggeninternet** [comment]
I'm having the same issue with an ASUS tablet

**Comment by Quantumrunner** [comment]
Closed. Issue has been fixed in Release https://github.com/NPBruce/valkyrie/releases/tag/release%2F2.6%2F2.6.0a.
