### ISSUE TITLE
[Scenario] The Encroaching Dread (DomeAcolyte)

### ISSUE THREAD

**Issue by vidimus** [NPBruce/valkyrie#1517]
-->

### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [ X] Mansions of Madness
- [ ] Descent

### What expansions does the scenario require?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [X ] Beyond the Threshold (BtT)
- [X ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [X ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### What expansions can the scenario optionally use?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### Please enter the GitHub Url to your scenario here
https://github.com/vidimus/DomeAcolyte/tree/main/Lost_chronicles_02
+++++++++++++++++++++++++++++++++++++++++++++++++

Here's one of the scenarios created by DomeAcolyte for his twitch channel (https://www.twitch.tv/domeacolyte). The author has generously given me permission to publish it on Valkyrie's Github (and to maintain it as well). DomeAcolyte has already published one scenario: Azathoth's Sacrament.

The scenario is available in English and Spanish (thanks to Xavi for translating it into Spanish),

**Comment by vidimus** [comment]
@antontimmermans

**Comment by antontimmermans** [comment]
Please move the repository to a location without %20 in the name or path.

**Comment by vidimus** [comment]
> Please move the repository to a location without %20 in the name or path.

Sorry, @antontimmermans ,I forgot that. Done (updated the link above).

**Comment by antontimmermans** [comment]
Added to Manifest

**Comment by vidimus** [comment]
> Added to Manifest

Thanks!

**Comment by antontimmermans** [comment]
added to statistics sheets
