### ISSUE TITLE
[Scenario] Conversa de Bêbado

### ISSUE THREAD

**Issue by malkavk** [NPBruce/valkyrie#1520]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

### What expansions does the scenario require?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### What expansions can the scenario optionally use?
- [ ] Conversion Kit (CK)
- [X] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [x] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### Please enter the GitHub Url to your scenario here
https://github.com/malkavk/ConversaDeBebado

**Comment by vidimus** [comment]
@antontimmermans

**Comment by antontimmermans** [comment]
Added to manifest and statistics sheet

**Comment by vidimus** [comment]
@malkavk, the scenario is not working properly. I see blank text boxes when I play it. Only setting language into Portuguese allows me to see the test. Did you use the last Valkyrie version to create the package? Because this issue was something that happened in the previous Valkyrie version.

**Comment by malkavk** [comment]
I'm using 2.5.6. Is there any workaround that I could do to solve this issue?

**Comment by vidimus** [comment]
The package itself is a bit akward. Is this intended?
![IMG_20210824_212919](https://user-images.githubusercontent.com/41538948/130678219-1223b278-ee9e-44c7-88f8-9003f2159ccb.jpg)
It's like having multiple versions of the same scenario, all the folders have the same files, but no identical.
![Screenshot_2021-08-24-21-29-46-71_db51e592e420a9871f4a37915a68789b](https://user-images.githubusercontent.com/41538948/130678388-aea0de02-9509-4b3c-ba17-0adae364b4ca.jpg)

**Comment by malkavk** [comment]
Yes, it is.
Each subdirectory is a map variation. All tiles are the same for each variation, but location of tiles and tokens are different.
I tried have just one language file (all language files may be identical), while map changes.
Root quest is just for random selection of game map.

**Comment by vidimus** [comment]
> @vidimus and @antontimmermans,
> 
> Using English (this and only this language) as default language no problems happen. But with other languages it happens.

I tried in English and the same problem as in Spanish. I've seen you've updated the scenario, @malkavk , but in my case, the problem is still there.

**Comment by malkavk** [comment]
Please, use these files to test.

https://github.com/malkavk/ConversaDeBebado-Test

Unzip then to Valkyrie editor directory.

I prepared 2 test environments.
The files are almost the same:
- In ConversaDeBebado-EN:
     - The quest.ini files were edited by changing the default language to English and changing Localization.Portuguese.txt to Localization.English.txt
    - The Localization.Portuguese.txt files were renamed to Localization.English.txt, the language (in the first line) was changed to English and the mission name was changed to ConversaDeBebado-EN
- In ConversaDeBebado-PT:
     - Localization.Portuguese.txt was edited to rename the mission to ConversaDeBebado-PT

I propose these tests:
1. Set Valkyrie language to English and open both scenarios (it is expected that only ConversaDeBebado-EN is displayed correctly); 
2. Set Valkyrie language to Portuguese and open both scenarios (it is expected that both scenarios are displayed correctly);
3. Set Valkyrie to any other language and open both scenarios (it is expeted that only ConversaDeBebado-EN is displayed correctly).

**Comment by vidimus** [comment]
Now it seems to be OK, text is shown (in Portuguese).

**Comment by vidimus** [comment]
@malkavk I think you can close now this issue.
