### ISSUE TITLE
[Scenario] Deep Ones Among Us (DomeAcolyte)

### ISSUE THREAD

**Issue by vidimus** [NPBruce/valkyrie#1521]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [] Descent

### What expansions does the scenario require?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [X] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [X] Streets of Arkham (SoA)
- [X] Sunctum of Twilight (SoT)
- [X] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### What expansions can the scenario optionally use?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### Please enter the GitHub Url to your scenario here
https://github.com/vidimus/DomeAcolyte/tree/main/Lost_chronicles_03

-------------------------------------------------------------------
Another scenario from DomeAcolyte (https://www.twitch.tv/domeacolyte)

(Description from the creator discord channel):

Deep Ones Among Us is a sequel to Hidden Depths, which pays homage to Among Us. It's a game of social deduction which will require you to be confident enough to yell accusations at your fellow players.

**Comment by antontimmermans** [comment]
Added to Manifest and Statistics sheets

**Comment by vidimus** [comment]
@antontimmermans, could you check the manifest? The scenarios is not visible yet.

**Comment by antontimmermans** [comment]
I cannot see what is wrong with the manifest for this scenario. It looks similar to the other scenario from this author.
@scrubbless @BenRQ can either one of you take a look, please?

**Comment by vidimus** [comment]
![Screenshot_2021-08-24-16-41-27-25_21bd9e02371ed2328b4f345f7a47735e](https://user-images.githubusercontent.com/41538948/130637384-75104c3a-cd5c-4cb3-891a-a79479a17aba.jpg)
It's now on. I close this issue. Thanks again, @antontimmermans
