### ISSUE TITLE
[Scenario] The Coven of Antoine Manor (DomeAcolyte)

### ISSUE THREAD

**Issue by vidimus** [NPBruce/valkyrie#1524]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

### What expansions does the scenario require?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### What expansions can the scenario optionally use?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### Please enter the GitHub Url to your scenario here
https://github.com/vidimus/DomeAcolyte/tree/main/Lost_chronicles_04

---------------------------------------------------------------------------------------------------------------

Another scenario from DomeAcolyte (https://www.twitch.tv/domeacolyte)

(Description from the creator discord channel):

The Coven of Antoine Manor is a game of deductive reasoning, in which you're kidnapped by a witch, and must identify your foe, amongst fellow captives. The game changes each time, giving room for replay, and it only uses base game components, so it's great for playing it!

**Comment by antontimmermans** [comment]
added to manifest and statistics sheet

**Comment by vidimus** [comment]
Thanks, @antontimmermans!
