### ISSUE TITLE
[Scenario] Curse of Set (Nicola Zee)

### ISSUE THREAD

**Issue by NicolaZee** [NPBruce/valkyrie#1525]
Mansions of Madness Scenario

### Expansions the scenario requires
- Streets of Arkham (SoA)
- Path of the Serpent (PotS)

### Expansions the scenario can optionally use
- Curse of Set

### GitHub Url
https://github.com/NicolaZee/PublishedScenarios/tree/master/CurseOfSet

**Comment by scrubbless** [comment]
Ohh shiney! I'll add this now

**Comment by scrubbless** [comment]
I've added this to the manifest, @antontimmermans could you add this to the stats sheet, im not sure how to add to yours :)

**Comment by NicolaZee** [comment]
Thanks for the quick response.

**Comment by antontimmermans** [comment]
added to statistics
