### ISSUE TITLE
[Scenario] UPDATE Un Temblor en la Noche

### ISSUE THREAD

**Issue by RealPolux** [NPBruce/valkyrie#1529]
I've done an update to this scenario for Mansions of Madness. Hope you can play it now.

What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
[x ] Mansions of Madness
 Descent

What expansions does the scenario require?
 Conversion Kit (CK)
 First Edition (MoM1E) - Also Recurring Nightmares
 Fatal Alchemy (FA) - Also Suppressed Memories
 Call of the Wild (CotW) - Also Suppressed Memories
[x ] Beyond the Threshold (BtT)
[x ] Streets of Arkham (SoA)
[x ]  Sunctum of Twilight (SoT)
 [x ] Horrific Journeys (HJ)
 Path of the Serpent (PotS)

What expansions can the scenario optionally use?
 Conversion Kit (CK)
 First Edition (MoM1E) - Also Recurring Nightmares
 Fatal Alchemy (FA) - Also Suppressed Memories
 Call of the Wild (CotW) - Also Suppressed Memories
 Beyond the Threshold (BtT)
 Streets of Arkham (SoA)
 Sunctum of Twilight (SoT)
 Horrific Journeys (HJ)
 Path of the Serpent (PotS)

https://github.com/RealPolux/TemblorNocheScenario

**Comment by vidimus** [comment]
@RealPolux, you only need to replace the files with the new ones. It's an automatized process, so there's no need to post an issue here.

If you just want to announce the update, those things are usually published on the scenario depository (as a change log or something similar).

**Comment by RealPolux** [comment]
Closed
