### ISSUE TITLE
The first hero on the hero selection screen is missing in Descent in v0.81

### ISSUE THREAD

**Issue by Sadgit-HL** [NPBruce/valkyrie#153]

**Comment by NPBruce** [comment]
Not sure I understand.  I can't see anything obviously wrong can you please provide more detail? Perhaps a screen shot?

**Comment by Sadgit-HL** [comment]
![bug](https://cloud.githubusercontent.com/assets/26650531/24494737/4ebf3f9a-1533-11e7-8c64-7c6f0cff1a7f.jpg)

**Comment by NPBruce** [comment]
It's always been like that, the empty selection is to clear the spot.

You can reopen if I have misunderstood.

**Comment by Sadgit-HL** [comment]
Ah sorry, did not know that.
