### ISSUE TITLE
[Question]  Does selecting a custom monster during a spawn keep the expansion of the base monster?

### ISSUE THREAD

**Issue by AntonioFico** [NPBruce/valkyrie#1530]
### Description of Problem or Question
I've a question.

Does selecting a custom monster take into account the expansion of the base monster?

For example: I defined 10 custom monsters 3 based on monsters in the expansions. If I have monsters selected via traits, will the 3 monsters based on unselected expansions also appear?

### Valkyrie Version
2.5.6

**Comment by vidimus** [comment]
I have a very limited knowledge of the editor, so maybe it could be done in a different way.

 I think you must set a variable for each monster, to link them to a specific expansion. Then, create a check test with those variables, so the monster will not appear if the variable doesn't match the test.

**Comment by AntonioFico** [comment]
Yes you're right: custom monster dosen't spawn in normal way so they are all excluded from normal gaming.
