### ISSUE TITLE
[New Scenario] Los Vestigios del Odio

### ISSUE THREAD

**Issue by RealPolux** [NPBruce/valkyrie#1531]
New scenario for MoM, hope you enjoy it!
Nuevo escenario para Mansiones, espero que os guste.

 ### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [x] Mansions of Madness
- [ ] Descent

### What expansions does the scenario require?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [x] Fatal Alchemy (FA) - Also Suppressed Memories
- [x] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [x] Streets of Arkham (SoA)
- [x] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### What expansions can the scenario optionally use?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

https://github.com/RealPolux/LosVestigiosdelOdio

**Comment by vidimus** [comment]
Great! The premise is quite interesting!

@scrubbless or @antontimmermans, could you add it to Valkyrie?

**Comment by scrubbless** [comment]
I've added this to the scenario manifest.

@antontimmermans could you add this to the stat sheets when you get a chance please :)

**Comment by RealPolux** [comment]
Uploaded

**Comment by antontimmermans** [comment]
added to statics files
