### ISSUE TITLE
[Scenario] Midsommar

### ISSUE THREAD

**Issue by pilzhead** [NPBruce/valkyrie#1536]
https://github.com/pilzhead/Midsommar

### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [x] Mansions of Madness
- [ ] Descent

### What expansions does the scenario require?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [x] Streets of Arkham (SoA)
- [x] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### What expansions can the scenario optionally use?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [x] Call of the Wild (CotW) - Also Suppressed Memories
- [x] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [x] Horrific Journeys (HJ)
- [x] Path of the Serpent (PotS)

### Please enter the GitHub Url to your scenario here
https://github.com/pilzhead/Midsommar

**Comment by vidimus** [comment]
Great, a new scenario!
@scrubbless or @antontimmermans

**Comment by antontimmermans** [comment]
Added to the Manifest, should be available for download in about 1 hr.

**Comment by antontimmermans** [comment]
Added to scenario statistics sheets

**Comment by vidimus** [comment]
@pilzhead, the scenario is up, so could you close this issue?

By the way, I will watch the film because I want to play this scenario. It's sounds very promising! Thanks for creating it.

**Comment by pilzhead** [comment]
Thank you so much!
You can close this issue =)
