### ISSUE TITLE
[Scenario] The Curse of the Blind Stalker

### ISSUE THREAD

**Issue by vidimus** [NPBruce/valkyrie#1538]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

### What expansions does the scenario require?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [X] Streets of Arkham (SoA)
- [X] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### What expansions can the scenario optionally use?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### Please enter the GitHub Url to your scenario here
https://github.com/vidimus/DomeAcolyte/tree/main/Lost_chronicles_05

**Comment by vidimus** [comment]
Another scenario created by DomeAcolyte. Available in English and Spanish (translated by me).

_"After drawing the ire of the Silver Twilight Lodge, you find yourself hunted by some sinister, ancient creature, that cannot be killed._

The Lost Chronicles: Scenarios created by DomeAcolyte for his twitch channel (https://www.twitch.tv/domeacolyte)

**Comment by antontimmermans** [comment]
Added to manifest and to scenario statistics sheets
