### ISSUE TITLE
[Scenario] Sylvia Marsh contra el crepúsculo de plata

### ISSUE THREAD

**Issue by luiccin** [NPBruce/valkyrie#1539]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [ ] Mansions of Madness
- [ ] Descent

### What expansions does the scenario require?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### What expansions can the scenario optionally use?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### Please enter the GitHub Url to your scenario here
https://github.com/luiccin/Valkyre

**Comment by vidimus** [comment]
@scrubbless or @antontimmermans

**Comment by antontimmermans** [comment]
The scenario is added to manifest and to the analysis sheets. Should be downloadable in ~1 hr.

**Comment by vidimus** [comment]
It's online. Thanks, @antontimmermans 
@luiccin , you can close this issue. And thanks for creating the scenario.

**Comment by Quantumrunner** [comment]
Closed. @antontimmermans Please close these kind of threads using the close with comments button after adding the scenario to scenario list.

![grafik](https://user-images.githubusercontent.com/58113888/147419463-7344f610-1998-4091-a608-a168d97a4bdd.png)

**Comment by luiccin** [comment]
> It's online. Thanks, @antontimmermans @luiccin , you can close this issue. And thanks for creating the scenario.

I've had to reupload the scenario. I forgot to indicate that it needed an expansion.

**Comment by antontimmermans** [comment]
Added that info to the statistics sheet too ;-)
