### ISSUE TITLE
[Question] Split .Valkyrie file?

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#1545]
### Description of Problem or Question
Probably a question for @NPBruce @BenRQ or @mayjak 

I am having issues with publishing the latest version of a Strain on reality to GitHub, the file is getting rather large now and exceeds the 100mb limit for GitHub.

Is it possible to split the .valkyrie file into multiple zip's? If so how could I achieve this?

![image](https://user-images.githubusercontent.com/32058089/149918335-8b13f37c-b091-48f8-9733-815c884af322.png)

I want to avoid compressing the images, as it has caused the image to pixalate in Valkyrie (despite looking fine when viewed externally).

**Comment by NPBruce** [comment]
Valkyrie doesn't support this, however make sure you are using png and jpg compression matching the image type (must be png for transparency). Alternatively Valkyrie does support the files being hosted elsewhere, as long as you can link directly to the files.

**Comment by scrubbless** [comment]
I've tried to use git lfs, but I'm not sure if it is working.

How do I reference the file? I assume I need too add the link to the ini.

Also is this supported with the scenarios explorer @BenRQ ?

**Comment by scrubbless** [comment]
> Valkyrie doesn't support this, however make sure you are using png and jpg compression

I have compressed the images but it does not shave off enough (only about 5mb), the audio files are quite large but I don't believe I can compressed the .ogg files. Even so I need to make up ~40mb which I don't think I can do through compression.

The last resort would be to publish the scenario in a stand alone for the Spanish translation, but don't like the idea of listing the same scenario multiple times if I can help it.

**Comment by NPBruce** [comment]
ogg (vorbis) is compressed and there are a variety of compression levels. I am not sure if there is a good alternative to host the files.

**Comment by scrubbless** [comment]
I've dropped the scenario on GitLabs and BitBucket which both allow larger files, but the Scenario explorer scripts are erroring out when trying to read the new path, so a bit unsure whats going on there. 

I've reached out to @BenRQ on discord but i'll keep looking.

**Comment by scrubbless** [comment]
I've put one of my earlier working versions on BitBucket and GitLab and get the same JSON error, so it looks like the scripts are not parsing paths other than GitHub correctly.

**Comment by BenRQ** [comment]
I need to check that. It would probably be an evolution to implement in the
import script. However your test may be blocking the updates of other
scenarios as the script is not running, it stops as soon as there is an
error.

I really need to improve that script so it manages error in a better way.

**Comment by BenRQ** [comment]
Script is updated to hopefully handle external links better.
Update scenario date won't be available though for external links, as I'm getting this from github commit date.

**Comment by BenRQ** [comment]
Now fixed, to properly support the external links.

**Comment by scrubbless** [comment]
Thanks @BenRQ will it still show last updated dates for GitHub hosted scenarios? 

Also is there a way where we could manually enter some text in the scenario (meta data or something) to provide the last updated date to the app?
