### ISSUE TITLE
[Bug] Scenario Curse of Set (v2.12) no longer downloads automatically

### ISSUE THREAD

**Issue by NicolaZee** [NPBruce/valkyrie#1546]
### Issue
I updated my scenario Curse of Set to Version 2.12.   It has been successfully uploaded but the icon to download did not appear even after several hours.  I had to download the scenario by deleting the previous version and selecting download.  The title in the list of scenarios is still Curse of Set (v2.11) when it should be Curse of Set (v2.12).  Have I done something wrong or is this a bug? 

### Scenario
Curse of Set (v2.12)

### Steps to reproduce the behavior:
Look in the list of scenario names.
It is listed as Curse of Set (v2.11) when it should be Curse of Set (v2.12).

### Expected behavior
The correct name in the list of scenarios.
The option for automatic download to version 2.12 if version 2.11 is already installed.

**Comment by NicolaZee** [comment]
To help track this down, I have created a new version 2.13.

The big clue that the problem is on-line is that if the package is deleted (and so removed from the manifest.ini), the title of the scenario shown in the download list is Curse of Set (v2.11).  This name cannot exist locally.   So the problem must be online.

**Comment by antontimmermans** [comment]
This appears not only to be the case for CoS scenario but also other scenarios. Copied from Discord:

_malkavk [15:58] Some months ago II updated one of my scenarios. Aftet 2 days Valkyrie displeyd nothing about this.
Brotim [15:58] which one is that?
malkavk [15:58] Conversa de Bêbado
malkavk [15:59] Some other users got the update._

I also checked on my version (on windows 11.)
Initially it offered an update button, the title indicated V2.11. After hitting the update button, it displayed this:
![image](https://user-images.githubusercontent.com/42072372/150372885-e9229d79-04a6-49f8-b8f9-76a0f38bdd45.png)
when you hit the play scenario button, it shows this screen with v2.12:
![image](https://user-images.githubusercontent.com/42072372/150373282-55dd1bfd-10e7-4177-911c-ebaa708eb209.png)

Later Nicola reported that for a test, she updated it to version 2.13, but even after 2,5 hrs the update doesn't show on the scenario list overview.

**Comment by malkavk** [comment]
I am using Fedora Linux 35 and my Valkyrie version is 2.5.6

**Comment by NicolaZee** [comment]
So what's in the manifest.ini file online?   I suspect it has the title Curse Of Set (v2.12)

**Comment by BenRQ** [comment]
There are some issues at the moment for the script getting and checking the scenarios. I'm looking into this.

**Comment by antontimmermans** [comment]
20:42 CETI could properly update CoS

**Comment by BenRQ** [comment]
Scrubbless removed the change he made in the scenario list, and it's back and working now.
I would like to fix my script for the future though, because the issue was not with scrubbless update, but with my script.

**Comment by BenRQ** [comment]
Related to #1545 . Closing
