### ISSUE TITLE
[Scenario] Alhazred's Secret Ritual

### ISSUE THREAD

**Issue by CD0ug88** [NPBruce/valkyrie#1554]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [x] Mansions of Madness
- [ ] Descent

### What expansions does the scenario require?
- [x] Conversion Kit (CK)
- [x] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### What expansions can the scenario optionally use?
- [x] Conversion Kit (CK)
- [x] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

https://github.com/CD0ug88/ScenarioMoM

**Comment by vidimus** [comment]
@scrubbless , @antontimmermans , a new scenario is awaiting.

**Comment by antontimmermans** [comment]
Added scenario to manifest and to the analytics sheets. 
It should be available for download in ~1 hr
