### ISSUE TITLE
[Scenario] ¿Quiénes son? - Mansión Marberlard

### ISSUE THREAD

**Issue by vidimus** [NPBruce/valkyrie#1555]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

### What expansions does the scenario require?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### What expansions can the scenario optionally use?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### Please enter the GitHub Url to your scenario here

https://github.com/Sandra0797/MansionMarberlard
----------------------------------------
A reputable police detective becomes involved in a strange and seemingly paranormal case.
(The scenario is only in Spanish)
----------------------------------------------------------------
Un reputado detective de policía se ve envuelto en un extraño caso aparentemente paranormal.

**Comment by vidimus** [comment]
@scrubbless or @antontimmermans , could you add it to Valkyrie?

**Comment by antontimmermans** [comment]
added to manifest and to analytics sheets
