### ISSUE TITLE
[Scenario] A matter of blood / Una cuestión de sangre

### ISSUE THREAD

**Issue by vidimus** [NPBruce/valkyrie#1556]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

### What expansions does the scenario require?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [X] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [X] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [X] Path of the Serpent (PotS)

### What expansions can the scenario optionally use?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### Please enter the GitHub Url to your scenario here
https://github.com/vidimus/DomeAcolyte/tree/main/Lost_chronicles_06

A matter of blood is available in English and in Spanish. Another scenario created by DomeAcolyte (https://www.twitch.tv/domeacolyte) and adapted for Valkyrie. Spanish translation by Xavi and Vidimus.

@scrubbless or @antontimmermans , can you add this scenario to the manifest?

**Comment by antontimmermans** [comment]
added to manifest and to statistics sheets
