### ISSUE TITLE
[Scenario] (Descent) La fortaleza de la muerte

### ISSUE THREAD

**Issue by vidimus** [NPBruce/valkyrie#1561]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [ ] Mansions of Madness
- [X] Descent

### What expansions can the scenario optionally use?
- [X] Guardians of Deephall

### Please enter the GitHub Url to your scenario here

(https://github.com/vidimus/Aventuras.Descent/tree/main/LaFortalezaDeLaMuerte)

**Comment by vidimus** [comment]
@antontimmermans , would you mind to add this one to the manifest?

**Comment by antontimmermans** [comment]
added to manifetst and to statistics sheets
