### ISSUE TITLE
[Bug] Scrolling a list by using a mouse click results in scrolling upwards.

### ISSUE THREAD

**Issue by NicolaZee** [NPBruce/valkyrie#1562]
### Bug Description
After installing Valkyrie on my new Windows 11 PC the lists are working erratically.   Scrolling a list by moving the scroll box in the list by clicking on the scroll bar causes the list to scroll automatically upwards.  This affects all lists including in the main screen and in the editor.  

### More details
The bug does not happen running Windows 10 on my laptop.  So the bug is either specific to my pc or Windows 11.  This issue may be intermittent.  Please note, if the scroll wheel is used the list scrolls fine both up and down.  It only scrolls automatically upwards if the mouse pointer is used to click on the box in the scroll bar and moved up or down.  Then the list scrolls automatically upwards until the first page is displayed.

### Steps to reproduce the behavior:
Not known but it is probably is related to Windows 11.

### Valkyrie Version
Latest 2.5.6

**Comment by Hobbeslionheart** [comment]
I searched online to see if others had issues migrating Unity Projects/ Software to Windows 11, but nothing came up quickly. The only thing I could think of is that Windows 11 now uses round corners instead of sharp corners so would that affect calculations within the script? I don't have Windows 11 yet, but if someone else does, could you check if this happens to you too?

**Comment by NicolaZee** [comment]
The mystery thickens.

I can scroll all the way down to the bottom of a list using the mouse wheel.

But if I click on the vertical scroll var then the list scrolls automatically up to the first item even if using the mouse wheel to scroll down.

**Comment by antontimmermans** [comment]
I have Windows 11 in combination with valkyrie 2.5.6 and I cannot reproduce this behavior.

Are you sure it is not a problem with your mouse or its driver?

**Comment by NicolaZee** [comment]
It only happens with Valkyrie and the mouse is fine.  I checked it on my laptop and I tried a different mouse.  I might try a third.  In any case it seems to me time for me to focus on other projects but I do look forward to your next scenario. I'll just run if off my laptop!
: )

**Comment by NicolaZee** [comment]
The mystery thickens more.   I have not changed anything and the scrolling now works fine.  Very odd.  I'll try and spot when it stops working.  Currently it just seems random.  Valkyrie can be a bit quirky!  :)

**Comment by NicolaZee** [comment]
The mystery thickens once more as it is happening again.  Maybe it is connected to adding new scenarios to the manifest?  In any case, I'm not too worried as I'm cutting back on the time I'm spending on Valkyrie and it seems only to be affecting my pc.

**Comment by NicolaZee** [comment]
The mystery thickens more. I have not changed anything and the scrolling now works fine. Very odd.  I'm guessing it may somehow be triggered by adding a new scenario to the online manifest.

**Comment by rat167** [comment]
Windows 10 here.
I have a 3d connection mouse - lots of buttons - maybe joystick axi defined are the problem.

After a single click into scroll bar it starts automatically scrolling up, if I click LMB into scenario selection area (like scenario name) it stops.

**Comment by NicolaZee** [comment]
Rudder bar was triggering it.  I just disconnect the rudder controlling before playing Valkyrie.
