### ISSUE TITLE
[New Scenario] Puerta Roja

### ISSUE THREAD

**Issue by DaniMassaro** [NPBruce/valkyrie#1568]
Hello!

I would like to publish my 4th scenario.

Thank you.

What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
[x ] Mansions of Madness
 Descent

What expansions does the scenario require?
 **Streets of Arkham (SoA) X**

What expansions can the scenario optionally use?

Please enter the GitHub Url to your scenario here
https://github.com/DaniMassaro/PuertaRoja

**Comment by scrubbless** [comment]
Hi @DaniMassaro 

I've added this to the manifest

**Comment by DaniMassaro** [comment]
Thank you!
