### ISSUE TITLE
Choosing more than 1 monster trait leads to crash.

### ISSUE THREAD

**Issue by Sadgit-HL** [NPBruce/valkyrie#157]

**Comment by NPBruce** [comment]
Do you mean in the editor or when running the quest?  The D2E example quest does this.  Please provide a log and if in the quest a save game before the crash.

**Comment by Sadgit-HL** [comment]
When I use e.g. the water and dark trait, both, Start Quest and Quest Editor lead to crash as soon as the quest is selected. This occurs only if no monster type is chosen. If one trait is chosen all is fine. Which log file would you like to have?

**Comment by NPBruce** [comment]
I still can't reproduce this.  Please provide either the quest or a save immediately before the crash.

**Comment by Sadgit-HL** [comment]
Looked into that again and narrowed the problem down to the trait "civilized". There is a typo in Valkyrie here: "civilised". This might cause the crash.

**Comment by NPBruce** [comment]
Ah crazy americans.  I have changed them, it is likely that your selection couldn't match anything.

It is very helpful to look in the log here: valkyrie_Data/output_log.txt.  Also to attach this to issue reports.

**Comment by eorahil** [comment]
In the multilanguage translation process I will convert all traits into keys. So this won't be a problem.

We could introduce 2 different languages: American and English ;P
