### ISSUE TITLE
[Translation] In Places Unseen (update Spanish translation and bug fixing).

### ISSUE THREAD

**Issue by vidimus** [NPBruce/valkyrie#1570]
### What kind of translation do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

I don't know how to contact with the author, @LordPyrex on their repositories. I'm thinking about reviewing the Spanish translation (created by another user, @Fr4n) to correct some typos and minor mistakes. Plus, after reading a lot of comments on this scenario, many users are having a poor game experience due to a game bug at the end of the scenario. The bug prevents players for finishing the scenario properly.

So, what do I want? Update the Spanish translation and have the bug fixed. I assume that the original creator is currently off of Valkyrie, so I could try to fix it or get some help to do it.

**Comment by LordPyrex** [comment]
Hello.  The original creator of this scenario was my husband passed away
last year.  Please feel free to do whatever you want with the scenario he
created.
Thank you,
Chris

**Comment by vidimus** [comment]
> Hello. The original creator of this scenario was my husband passed away last year. Please feel free to do whatever you want with the scenario he created. Thank you, Chris

Hello, Chris.

Really sorry to read that. My deepest condolences. 
I would like to repair a bug on the end of the scenario, that prevent some people to finish the scenario. I have a special feeling for that scenario. It was my first Valkyrie scenario and I really enjoy it and pushed me into Valkyrie and its community. So my intention is just to fix the bug so new players could enjoy the scenario as much as I did.
I will post here a message when done.
