### ISSUE TITLE
Unable to play scenario utilizing base game

### ISSUE THREAD

**Issue by shawnboygames** [NPBruce/valkyrie#1574]
### I am trying to play a scenario that look to only need the base game as indicated by the base game icon (see image) but it has a red like and will not allow me to play it.  What do I have set wrong? I have MoM 2nd ed and in valkyrie I have the "Boxed Expansions" selected. I should be able to run the Amnesia scenario from my uploaded image yeah?
<img width="1792" alt="Screen Shot 2022-07-26 at 10 55 29 AM" src="https://user-images.githubusercontent.com/110050073/181055495-32dc41af-cf0e-4c93-a477-fbf7b0d955f6.png">

**Comment by vidimus** [comment]
Amnesia uses the conversion kit (in this case, the unique item "Duke", the Ashcan Pete's dog). If you have the conversion kit, just mark it on your collection. 
If you don't have it, download and print it. It's available on ffg official page. Here are the files:

https://images-cdn.fantasyflightgames.com/filer_public/36/83/36839eb5-028a-4d57-883a-330effbbd60a/conversion_kit_unique_item_cards.pdf
https://images-cdn.fantasyflightgames.com/filer_public/df/ef/dfef9919-aff8-41fd-bbc2-c0c97e905ad3/conversion_kit_investigator_cards.pdf
https://images-cdn.fantasyflightgames.com/filer_public/35/ac/35aca0a7-197b-41a8-a7e9-73bdf1ac1d49/conversion_kit_monsters_tokens.pdf
