### ISSUE TITLE
[Translation] TheStand (Russian)

### ISSUE THREAD

**Issue by Krasavvec** [NPBruce/valkyrie#1577]
[Localization.Russian.txt](https://github.com/NPBruce/valkyrie/files/9214666/Localization.Russian.txt)

### What kind of translation do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

**Comment by vidimus** [comment]
Hello, @Krasavvec 
I have sent the author a message about this translation. In case I get any response, I will comment it here.

**Comment by vidimus** [comment]
@Krasavvec 
Russian translation has been added. You can close this issue.

![Screenshot_2022-08-03-11-55-51-83_21bd9e02371ed2328b4f345f7a47735e](https://user-images.githubusercontent.com/41538948/182581021-c0003b66-3e56-430e-a594-a1ac81d7ed17.jpg)
