### ISSUE TITLE
[Scenario] The Consuming Shadow

### ISSUE THREAD

**Issue by EwenDC** [NPBruce/valkyrie#1581]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [x] Mansions of Madness
- [ ] Descent

### What expansions does the scenario require?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### What expansions can the scenario optionally use?
- [x] Conversion Kit (CK)
- [x] First Edition (MoM1E) - Also Recurring Nightmares
- [x] Fatal Alchemy (FA) - Also Suppressed Memories
- [x] Call of the Wild (CotW) - Also Suppressed Memories
- [x] Beyond the Threshold (BtT)
- [x] Streets of Arkham (SoA)
- [x] Sunctum of Twilight (SoT)
- [x] Horrific Journeys (HJ)
- [x] Path of the Serpent (PotS)

### Please enter the GitHub Url to your scenario here
https://github.com/EwenDC/ValkyrieConsumingShadow

**Comment by vidimus** [comment]
@antontimmermans or @scrubbless , could you add this one to the manifest?

**Comment by antontimmermans** [comment]
Added to manifest and statistics sheet
