### ISSUE TITLE
[Scenario] La Maldición de Malory

### ISSUE THREAD

**Issue by Odindm1** [NPBruce/valkyrie#1590]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

### What expansions does the scenario require?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [X] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### What expansions can the scenario optionally use?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [X] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

(https://github.com/Odindm1/La-Maldicion-de-Malory)
 Por favor, ¿podríais añadir esta misión de mansiones de la locura?

Gracias.

**Comment by vidimus** [comment]
Hola, @Odindm1 
Ya he avisado a un administrador. Gracias por compartir tu escenario.

**Comment by Odindm1** [comment]
¡Gracias a vosotros!

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by antontimmermans** [comment]
I can add the scenario to the manifest for you, but please change the directory name.
Please don't use special characters like '-' or spaces in the name. Those characters typically generate issues.

**Comment by Odindm1** [comment]
Hi, this is the correct directory.
https://github.com/Odindm1/Lamaldiciondemalory

Thanks so much.

**Comment by antontimmermans** [comment]
Added to Manifest and statistics sheets
