### ISSUE TITLE
[Scenario] Descent Campaign: Chains of Bilehall

### ISSUE THREAD

**Issue by Quantumrunner** [NPBruce/valkyrie#1592]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [ ] Mansions of Madness
- [x] Descent

### Please enter the GitHub Url to your scenario here
https://github.com/ValkDes/ValkyrieCOB

@antontimmermans Please add this to **Descent** Scenario list. :)

**Comment by antontimmermans** [comment]
Added to manifest 
@vidimus you want to try and add these to the statistics sheets?

**Comment by vidimus** [comment]
Yes, sure. 

> Added to manifest @vidimus you want to try and add these to the statistics sheets?
Yes, sure.

**Comment by Quantumrunner** [comment]
Thank you both! Content is already showing in Valkyrie.
