### ISSUE TITLE
[Scenario] OCultoDasEstrelas

### ISSUE THREAD

**Issue by Rafilzisk** [NPBruce/valkyrie#1593]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [x] Mansions of Madness
- [ ] Descent

### What expansions does the scenario require?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### What expansions can the scenario optionally use?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### Please enter the GitHub Url to your scenario here
https://github.com/Rafilzisk/CultoDasEstrelas

**Comment by vidimus** [comment]
@Rafilzisk looks fantastic (short, 2-3 players and a nice story). Thanks for sharing it with the community (e bom Natal!).

@scrubbless or @antontimmermans , could you add this scenario to Valkyrie.

P.S. Merry Christmas!

**Comment by Rafilzisk** [comment]
Thanks @vidimus, I Just kmow the game and Valkyrie Last month,  but I love it. 
I want to make more scenario. And I"ll learn how to make files to translate to english to. I read, somewhere that we can translate The text files and app make all the work to put in the scenario. 

Hope the community like this. 
Marry Xmas, happy holidyas!

**Comment by antontimmermans** [comment]
The scenario is added to the Manifest and to the scenario statistics sheets.

PS: I can't wait to see it in English, if you need pointers to make translations easier, just reach out to me (Brotim) or Vidimus on Discord valkyrie channels. (https://discord.gg/PAabN5HZ)

An example of a translation support file is on (check the ReadMe page on how it works): https://docs.google.com/spreadsheets/d/1XlaQNjBI1Rzu_y7jvhHfStSrf4_yUVd5tv4D6_i9Qqo/edit#gid=278224675

**Comment by Rafilzisk** [comment]
Thanks @antontimmermans I'm so happy that my scenario was published on Valkyrie! :) The community is amazing. 
I'll study the link that you shared to translate to English and Spanish. 

I'll improve some UI images and I already an Idea to continue this Scenario.

**Comment by Rafilzisk** [comment]
Thanks @antontimmermans I'm so happy that my scenario was published on Valkyrie! :) The community is amazing. 
I'll study the link that you shared to translate to English and Spanish. 

I'll improve some UI images and I already an Idea to continue this Scenario.

**Comment by vidimus** [comment]
> Thanks @antontimmermans I'm so happy that my scenario was published on Valkyrie! :) The community is amazing. I'll study the link that you shared to translate to English and Spanish.
> 
> I'll improve some UI images and I already an Idea to continue this Scenario.

Hello, @Rafilzisk 
You can count on me for the Spanish translation. I've been checking your scenario and it's short, so it's not going to take me too much time to translate it. If you can speak Spanish, maybe you can help the community translation into Portuguese some of the Spanish scenarios.

About the English translation or any assistant creating, editing or adding the translation, just send me a message and I will help you. As @antontimmermans suggested, contact me using Discord.

P.S.: Congratulations for your scenario. If you are in Mansions for just one month, you (Rafael and Mariana) did a great job!

**Comment by Rafilzisk** [comment]
@vidimus My spanish is bad, even though I'm from south america hahaha, sometimes I don't understand why our schools don't teach spanish since our childhood. We are a Portuguese country isolated in a Spanish-speaking continent... .
But I will try some translations from Spanish and English.

When I start the translates, i'll certainly call you guys in Discord.

Thanks for the support!!
