### ISSUE TITLE
[Scenario] New Mansions of Madness Scenario

### ISSUE THREAD

**Issue by DarkVanf** [NPBruce/valkyrie#1596]
### Description of Problem or Question

I would like my first scenario to be added to valkyrie's listings.

Files can be found at:
https://github.com/DarkVanf/valkyrieseahide

### Attach Save, Quest or Scenario
Log File:
%LOCALAPPDATA%Low\NA\Valkyrie\output_log.txt
Saves:
%appdata%/Valkyrie/MoM/Save
%appdata%/Valkyrie/D2E/Save
Quest:
%appdata%/Valkyrie/D2E/Editor
Scenario:
%appdata%/Valkyrie/MoM/Editor

**Comment by vidimus** [comment]
Added to the manifest. It would be available within one hour.
@antontimmermans, could you add it to Valkyrie's statistics?

**Comment by antontimmermans** [comment]
added to Statistics sheets
