### ISSUE TITLE
Addind XP to a specific hero

### ISSUE THREAD

**Issue by relord17** [NPBruce/valkyrie#1598]
Hello everyone! Descent question.
Is there any possibility to change game code for adding XP not to all heroes at once, but to a specific hero? For example: I need add +2 xp for hero 1 (Widow Tarha), but the rest of heroes must remain the same amount of xp.
This fuction was working in the FFG (RTL) in some campaigns.

My thoughts: Create variables {$xpHero1}, {$xpHero2}, {$xpHero3}, {$xpHero4} and add them in game code.

**Comment by vidimus** [comment]
@Quantumrunner , could you help them? Maybe you know how to do it.

**Comment by Quantumrunner** [comment]
No this is not something that has been implemented yet. Doesn't mean that this is not something that can be implement by someone in the future.

The only downside I see here that this is not something that is valid in the normal Descent rules or the Road to Legend rules. All heroes always get the same amount of XP.

**Comment by relord17** [comment]
@Quantumrunner , hello there!
Sorry for such long time not answering this issue!
Returning to the subject. As I remember in RTL there was a campaign (Seeds of Corruption) in which it was possible to add 1xp to a specific hero for selling artifacts.
Looks like in RTL code each hero has it's own XP variables, and in Valkyrie they have 1 XP variable for all heroes at once.
