### ISSUE TITLE
[Scenario] The_Lost_Treasure_pt1

### ISSUE THREAD

**Issue by Neuntoter82** [NPBruce/valkyrie#1599]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [ ] Mansions of Madness
- [ X] Descent

**This scenario just uses the base game**

### What expansions does the scenario require?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### What expansions can the scenario optionally use?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### Please enter the GitHub Url to your scenario here
https://github.com/Neuntoter82/The_Lost_Treasure_pt1

**Comment by vidimus** [comment]
Great, @Neuntoter82 , I will add it to the manifest.

**Comment by vidimus** [comment]
Added to manifest and to Descent statistics.

By the way, @Neuntoter82, it would be great if you add a cover picture for this scenario. It makes it more appealing.

**Comment by Neuntoter82** [comment]
The cover picture is in the image folder in the package and the quest ini shows it being a thing. It has an image in the editor... Did I miss something??

Thanks again

Derek     On Friday, February 10, 2023, 12:37:55 PM EST, Vidimus ***@***.***> wrote:  
 
 


Added to manifest and to Descent statistics.

By the way, @Neuntoter82, it would be great if you add a cover picture for this scenario. It makes it more appealing.

**Comment by vidimus** [comment]
Hello, @Neuntoter82 , you nees to add the picture on the repository as well. Otherwise, the picture is not shown on the scenario list, even if you can see it when clicking on the scenario and watch the scenario briefing

**Comment by vidimus** [comment]
![Screenshot_2023-02-11-00-52-45-52](https://user-images.githubusercontent.com/41538948/218223508-af69a183-22c3-4c02-a945-86c0d0b6a5d4.jpg)
![Screenshot_2023-02-11-00-52-39-42_21bd9e02371ed2328b4f345f7a47735e](https://user-images.githubusercontent.com/41538948/218223512-98225d5f-6b9a-4540-af19-8c3f0b50080d.jpg)

**Comment by vidimus** [comment]
![Screenshot_2023-02-11-00-52-45-52](https://user-images.githubusercontent.com/41538948/218223601-c055e0e1-b477-4da3-b86e-2e08028cbef7.jpg)
![Screenshot_2023-02-11-00-52-28-81](https://user-images.githubusercontent.com/41538948/218223602-b03c7c8a-97c3-4e8e-89d0-eea890eaa745.jpg)

**Comment by vidimus** [comment]
Nice, could you close this issue, please?
