### ISSUE TITLE
PASS / FAIL Event: Pass no longer triggers an event.

### ISSUE THREAD

**Issue by Liquidlogic1** [NPBruce/valkyrie#16]
Valkyrie 0.30

Tested with quest created in 0.22 and in new quest in 0.30

Fail will trigger an event, but Pass will not.

**Comment by NPBruce** [comment]
Can you please attach quest.ini? Does the example quest have this problem?

**Comment by Liquidlogic1** [comment]
Ok, I found the problem (my fault): I needed to select a hero before it would pass. It would fail without selecting a hero. Sorry about that.

**Comment by NPBruce** [comment]
Actually there is an issue here: If you are using minhero, then fail shouldn't work either (but it does).

**Comment by NPBruce** [comment]
Fixed in 0.3.1
