### ISSUE TITLE
[Scenario] Black Bishop: Knee Deep In The Dead

### ISSUE THREAD

**Issue by Neuntoter82** [NPBruce/valkyrie#1600]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [ ] Mansions of Madness
- [X ] Descent

This is a scenario designed for use with my Doom 2016 mod. I did ask in Discord if this was possible and did not get a response. So I figured I would try.

### What expansions does the scenario require?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### What expansions can the scenario optionally use?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### Please enter the GitHub Url to your scenario here
https://github.com/Neuntoter82/Doom-Mission-1

**Comment by Neuntoter82** [comment]
I included a warning that this level requires a special mod and a download link to get it in the description.

**Comment by vidimus** [comment]
Yes, sure. i will.

**Comment by vidimus** [comment]
Temporally removed from manifest until the issue with the custom content and the scenario selection screen becomes fixed.

**Comment by vidimus** [comment]
No that the app won't crash if the mod is not installed, I will add again the scenario to the manifest

**Comment by Neuntoter82** [comment]
Thank you for adding it to the manifest.
