### ISSUE TITLE
El reloj

### ISSUE THREAD

**Issue by Xavipalbu** [NPBruce/valkyrie#1604]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [x ] Mansions of Madness
- [ ] Descent

### What expansions does the scenario require?
- [x ] Conversion Kit (CK)
- [ x] First Edition (MoM1E) - Also Recurring Nightmares
- [x ] Fatal Alchemy (FA) - Also Suppressed Memories
- [x ] Call of the Wild (CotW) - Also Suppressed Memories
- [ x] Beyond the Threshold (BtT)
- [x ] Streets of Arkham (SoA)
- [x ] Sunctum of Twilight (SoT)
- [x ] Horrific Journeys (HJ)
- [x ] Path of the Serpent (PotS)

### What expansions can the scenario optionally use?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### Please enter the GitHub Url to your scenario here
https://github.com/Xavipalbu/ElReloj/tree/main/ElReloj

**Comment by vidimus** [comment]
@Xavipalbu, the directory is not reachable. Be sure you change repository permissions to public.

@Xavipalbu , el directorio no está disponible. Asegúrate de que cambias los permisos del repositorio y lo haces público.

**Comment by vidimus** [comment]
And don't forget to rename the files. Names like EditorEscenario2.valkyrie are not allowed. Keep in mind than special characters as ñ, -, ' ó, etc. are not supported.

------------------------

 No te olvides de renombrar los archivos y carpetas. Nombres como EditorEscenario2.valkyrie no están permitidos. Y recuerda que caracteres especiales como ñ, -, ' ó, etc. no son compatibles con la aplicación.

**Comment by vidimus** [comment]
@Xavipalbu This thread is outdated. Could you please close it?
