### ISSUE TITLE
[Bug] Can't open/locate Mansions of Madness version 1.9.2

### ISSUE THREAD

**Issue by fellipe-ribeiro** [NPBruce/valkyrie#1605]
Mansions of Madness updated today to version 1,9,2

BUG: Can't open/locate Mansions of Madness in version 1.9.2

OS: Windows

**Comment by Kiname** [comment]
Same issue after reimporting from 1.9.2 version, solved restoring backup copy from C:\Users\<USER>\AppData\Roaming\Valkyrie

**Comment by Kiname** [comment]
If someone with this problem need to go back to 1.8.8 version, its possible:
from a web navigator with Steam client open go to:
steam://nav/console
In the console type this command:
download_depot 47980 47981 3250284050137747605
Files will be downloaded on:
C:\Program Files (x86)\Steam\steamapps\content\app_478980\depot_478981
When download is complete, change the existing files in MoM installation directory by the downloaded ones.

**Comment by Arkawn** [comment]
Thank you for posting this solution. Replacing the entire MoM folder with the nav/console folder contents worked!

**Comment by kwidera** [comment]
Do you know the workaround for mac os? :(
I tried to open the steam console on mac with "/Applications/Steam.app/Contents/MacOS/steam_osx -console" but it is shutting down and steam is opening instead...

**Comment by kwidera** [comment]
For Mac OS:
download_depot 478980 478982 866862259843263412
Files will be here:
/Users/<user_name>/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/steamapps/content/app_478980/depot_478982

**Comment by rossbach-sascha** [comment]
This doesn`t work for me on MacOS. I still get the same error "Unable to locate Mansions of Madness Second Edition"

**Comment by VergilSkye** [comment]
> If someone with this problem need to go back to 1.8.8 version, its possible: from a web navigator with Steam client open go to: steam://nav/console In the console type this command: download_depot 478980 478981 3250284050137747605 Files will be downloaded on: C:\Program Files (x86)\Steam\steamapps\content\app_478980\depot_478981 When download is complete, change the existing files in MoM installation folder by the downloaded ones.


Thanks a lot, i try everything but this command was the only thing that help me on windows 10

**Comment by mya2003tq** [comment]
Hello, I get this error in the console: Depot download failed : missing license for depots 478981

**Comment by MRex21z** [comment]
Following:

I am having identical issues with Valkyrie 2.5.8 and MoM (Steam) 1.9.3.

A roll-back to MoM (Steam) 1.8.8 solved the issue, but I am hopeful this will be fixed for the current updated version of the MoM files.

**Comment by mal-w** [comment]
Reverting to 1.8.8 on linux also works using the same instructions as provided by Kiname

**Comment by seinsinnes** [comment]
Looks like these new updates to the Mansions of Madness app were compiled with much later unity:
2020.3.45f1

The code taken from unity studio to read the resources.assets contains a switch/case block:
`          fileGen = a_Stream.ReadInt32();
            int dataOffset = a_Stream.ReadInt32();
            sharedAssetsList[0].fileName = Path.GetFileName(fileName); //reference itself because sharedFileIDs start from 1
            switch (fileGen)
            {
                case 6://2.5.0 - 2.6.1
                    {
                        a_Stream.Position = (dataEnd - tableSize);
                        a_Stream.Position += 1;
                        break;
                    }
                case 7://3.0.0 beta
                    {
                        a_Stream.Position = (dataEnd - tableSize);
                        a_Stream.Position += 1;
                        m_Version = a_Stream.ReadStringToNull();
                        break;
                    }
                case 8://3.0.0 - 3.4.2
                    {
                        a_Stream.Position = (dataEnd - tableSize);
                        a_Stream.Position += 1;
                        m_Version = a_Stream.ReadStringToNull();
                        platform = a_Stream.ReadInt32();
                        break;
                    }
                case 9://3.5.0 - 4.6.x
                    {
                        a_Stream.Position += 4;//azero
                        m_Version = a_Stream.ReadStringToNull();
                        platform = a_Stream.ReadInt32();
                        break;
                    }
                case 14://5.0.0 beta and final
                case 15://5.0.1 and up
                case 16://5.5.0 and up
                case 17://5.5.0 and up
                    {
                        a_Stream.Position += 4;//azero
                        m_Version = a_Stream.ReadStringToNull();
                        platform = a_Stream.ReadInt32();
                        baseDefinitions = a_Stream.ReadBoolean();
                        break;
                    }
                default:
                    {
                        //MessageBox.Show("Unsupported Unity version!", "Unity Studio Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                        return;
                    }`

For MoM 1.9.3 fileGen is 22 so in order for Valkyrie to work with MoM 1.9.3 someone would have to put in code to handle the version 22 / 2020.3.45f1 file structure.

**Comment by UndutchableNL** [comment]
> For Mac OS: download_depot 478980 478982 866862259843263412
> 
> Downloaded file will be here: /Users/<user_name>/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/steamapps/content/app_478980/depot_478982 Replace the file in: /Users/<user_name>/Library/Application Support/Steam/steamapps/common/Mansions of Madness

This worked for me. You have to be patient for all the files to download (which I wasn't the first time)...

**Comment by Camsoh** [comment]
> If someone with this problem need to go back to 1.8.8 version, its possible: from a web navigator with Steam client open go to: steam://nav/console In the console type this command: download_depot 478980 478981 3250284050137747605 Files will be downloaded on: C:\Program Files (x86)\Steam\steamapps\content\app_478980\depot_478981 When download is complete, change the existing files in MoM installation folder by the downloaded ones.

**Comment by Quantumrunner** [comment]
Closed. Issue has been fixed in Release https://github.com/NPBruce/valkyrie/releases/tag/release%2F2.6%2F2.6.0a.
