### ISSUE TITLE
[Scenario] El Reloj

### ISSUE THREAD

**Issue by Xavipalbu** [NPBruce/valkyrie#1606]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [ x] Mansions of Madness
- [ ] Descent

### What expansions does the scenario require?
- [x ] Conversion Kit (CK)
- [x ] First Edition (MoM1E) - Also Recurring Nightmares
- [ x] Fatal Alchemy (FA) - Also Suppressed Memories
- [ x] Call of the Wild (CotW) - Also Suppressed Memories
- [x ] Beyond the Threshold (BtT)
- [ x] Streets of Arkham (SoA)
- [x ] Sunctum of Twilight (SoT)
- [x ] Horrific Journeys (HJ)
- [x ] Path of the Serpent (PotS)

### What expansions can the scenario optionally use?
- [x ] Conversion Kit (CK)
- [x ] First Edition (MoM1E) - Also Recurring Nightmares
- [x ] Fatal Alchemy (FA) - Also Suppressed Memories
- [x ] Call of the Wild (CotW) - Also Suppressed Memories
- [x ] Beyond the Threshold (BtT)
- [x ] Streets of Arkham (SoA)
- [x ] Sunctum of Twilight (SoT)
- [x ] Horrific Journeys (HJ)
- [x ] Path of the Serpent (PotS)

### Please enter the GitHub Url to your scenario here
https://github.com/Xavipalbu/ElReloj2/tree/main/ElReloj2

**Comment by vidimus** [comment]
Added to Valkyrie manifest.

@antontimmermans , could you please add this one to the statistics?

**Comment by antontimmermans** [comment]
Done
