### ISSUE TITLE
[Valkyrie cant find MOM] Can't import or choose MOM application within Valkyrie app

### ISSUE THREAD

**Issue by CoolNerdGames** [NPBruce/valkyrie#1607]
I have run through the other suggestions including updating the registry for file locations and cannot get Valkyrie to recognize MOM application in steam folder or (x86) steam folder. I've run as administrator. I've tried to pull the application up in Valkyrie and point it to the .exe. I've installed Valkyrie AND unpacked the .zip folder. I've uninstalled and reinstalled everything and rebooted the machine. Nothing works.

Descent shows up just fine, just not MOM.

Not sure what I'm doing wrong at this point, but really want to get this application working.

**Comment by vidimus** [comment]
@CoolNerdGames 
https://github.com/NPBruce/valkyrie/issues/1605

**Comment by CoolNerdGames** [comment]
This fixed it, thanks!
