### ISSUE TITLE
[Bug] MoM Scenario Editor Crashing on Test

### ISSUE THREAD

**Issue by CoolNerdGames** [NPBruce/valkyrie#1608]
I have my opening tile finished, and am adding the event to spawn a new tile. When testing the event to ensure it works everything is just fine until I use the "Add Components" to place the tile I want. When i go to test that this works as intended when the event launches, Valkyrie closes completely. I've tried making a new event. I've tried replacing the tile. I've tried it with a different tile, and it still crashes every time.

Any suggestions here?

**Comment by CoolNerdGames** [comment]
Edit* It only happens when placing a new tile. I am able to place a new token and the system wont crash when testing.

**Comment by vidimus** [comment]
@CoolNerdGames : Be sure you have selected on your collection all the expansions you are using on the editor. Using an element that is from an unselected expansions makes the editor crash. Tokens are common items, but monsters or tiles are associated to different expansions.

**Comment by CoolNerdGames** [comment]
I chose every expansion and it still crashes unfortunately.

**Comment by CoolNerdGames** [comment]
So, I have figured out the bug possibly. The Tile from Streets of Arkham (Office) is the tile that is buggy. For whatever reason when you select this tile and build it out. It crashes when being tested. Even if you change the tile from that tile AFTER selecting it originally. I had to rebuild the tile completely and use a different tile altogether to get it to work. The minute you change the tile to this one in the selector it bugs out the game regardless to the tile image you may choose in its place.

Weird.

**Comment by vidimus** [comment]
![Captura de pantalla (1458)](https://user-images.githubusercontent.com/41538948/223830919-0fa21fb5-5daa-4c9d-805c-cd725fb21c1c.png)
I can use that tile without any crashing. Is this tile you are referring to? I changed a previous tile with this and it worked like a charm.

If you want, I can test your scenario to see if I have the same problem with the editor.

**Comment by CoolNerdGames** [comment]
Yes, its that tile. I dont know how to share the scenario, but would be happy to send it your way. it's not extremely completed yet, but happy to share.

**Comment by CoolNerdGames** [comment]
*Edit I have the same issue with the Bedroom Tile from Streets of Arkham as well on a different Explore Token when I try to use it in the editor as well on a different section of the game board buildout..... :/

**Comment by vidimus** [comment]
Glad to read you manged to solve the problem, @CoolNerdGames . Now you can close this issue.
