### ISSUE TITLE
[Bug] Mythos events continue running, but how to limit, and prevent running out?

### ISSUE THREAD

**Issue by CoolNerdGames** [NPBruce/valkyrie#1609]
I may have just missed something but I've been trying to troubleshoot the problem for hours and cant figure out how to get around it. I've read the Valkyrie MoM tutorial, and the online NPBruce tutorial but just can't get passed the issue

**I have setup quest variables as such at EventStart:**

![Event_Start](https://user-images.githubusercontent.com/127016659/224481889-211bb774-6cb3-4778-a70a-3e8e61a1a781.JPG)

**I'm then testing the scenario currently with the following mythos events:**

![mythos_flavour](https://user-images.githubusercontent.com/127016659/224481980-310286fd-9c6e-49fb-b834-2b7d1440f2f7.JPG)

 **and this one**

![mythos_minor](https://user-images.githubusercontent.com/127016659/224482037-fad17dd3-7fc2-4319-b51a-c803e8aaf31b.JPG)

**When i go to test the scenario the events do not start until the desired timeframe , BUT i get these weird pop-ups after the event has run at least once before:**

![UI_error](https://user-images.githubusercontent.com/127016659/224482164-7fec12ba-920f-4123-9876-2824e5557229.JPG)

 **and this one**

![mythos_event_resolve_error](https://user-images.githubusercontent.com/127016659/224482182-875b6b34-24a7-42cb-b65c-f52a283eab1a.JPG)

**Afterwards, BOTH events continue to keep running back to back versus the mythos event only selecting the one event to run. I am fine with the repeating the events multiple times.**

 I saw i can set variables to categorize an event as "used" so it wont trigger again, but then i don't know what to do if i run out of mythos events to trigger. It pulled the same errors when there were no mythos events left.

Am I missing something? How do i prevent mythos events from doubling up, even if i want multiple events in the pool?

**Comment by CoolNerdGames** [comment]
I set the events to random as well and that doesn't seem to fix the issue either........

**Comment by CoolNerdGames** [comment]
Log is showing the following, but I don't really know what these mean.

![image](https://user-images.githubusercontent.com/127016659/224482656-81391fac-8609-4885-ad4c-9a2effd6e123.png)

**Comment by vidimus** [comment]
Try reimporting MoM official content. When you get code lines on button text usually is due to a problem finding official contents

**Comment by CoolNerdGames** [comment]
> Try reimporting MoM official content. When you get code lines on button text usually is due to a problem finding official contents

This did not fix the issue, unfortunately.

**Comment by CoolNerdGames** [comment]
I have fixed the loading issue but a new problem is running now. will close.
