### ISSUE TITLE
[Bug] Mythos events are generating randomly along with custom mythos events I'm specifying.

### ISSUE THREAD

**Issue by CoolNerdGames** [NPBruce/valkyrie#1610]
Is there a way to turn off the randomly generating mythos events? 

I'm trying to write all of my own custom into the scenario, but when I test the scenario, each mythos round is adding a randomly generated Mythos event as well as the mythos event I am building into the scenario.

How do I prevent the randomly generated Mythos event from  triggering with my custom event?

**Comment by antontimmermans** [comment]
You can have a look at these scenarios of how it works:
- 'Last train to Arkham' where I use my own mythos events during the train part, and standard myths for the rest.
- 'possessed' where I continuously mix homebrewed mythos with standard mythos.

**Comment by antontimmermans** [comment]
assuming that the question is answered, closing the issue
