### ISSUE TITLE
[Bug] Unlocalized strings and crash

### ISSUE THREAD

**Issue by DarthGandalf** [NPBruce/valkyrie#1615]
### Describe the bug
English locale is selected, however many strings looks like internal IDs rather than proper English. Then upon start the game crashes (this might have been a separate bug)

### Steps to reproduce the behavior:
1. Install the old version of MoM like described in #1605 (for Mac)
2. Run Valkyrie 2.5.8
3. Click Select content, see the screenshots; note that some content lists work correctly, and some do not
4. Try to start the game (I've started the first scenarion in the list - Strain on reality v2.4), select characters, see the screenshots
5. Finish start of the game, see the game crash

### Expected behavior
Should work perfectly :)

### LogFile
I can't find it, where is it on Mac?

### Screenshots
<img width="1728" alt="Снимок экрана 2023-04-01 в 11 42 53" src="https://user-images.githubusercontent.com/325092/229284635-5f92bc90-169f-4a29-8a11-ce3c97bc485c.png">
<img width="1728" alt="Снимок экрана 2023-04-01 в 11 43 03" src="https://user-images.githubusercontent.com/325092/229284640-ec02bd79-e9c3-46fc-a86c-9fa684ee7ea6.png">
<img width="1728" alt="Снимок экрана 2023-04-01 в 11 43 38" src="https://user-images.githubusercontent.com/325092/229284641-3dda1ca2-9232-4d04-8a4a-1acf65f3da9d.png">
<img width="1728" alt="Снимок экрана 2023-04-01 в 11 43 45" src="https://user-images.githubusercontent.com/325092/229284644-38c2d02a-0c82-4d13-9680-3152db6acebb.png">

The following screenshot is the last thing I see before the game disappears. It's shown only for a fraction of a second, so I had to capture video to be able to see this text at all.

<img width="1349" alt="Снимок экрана 2023-04-01 в 11 49 30" src="https://user-images.githubusercontent.com/325092/229284645-422f6169-8b0f-4fa0-a328-6d35ba750db8.png">

### Valkyrie Version
2.5.8

### Desktop
 - OS: Mac
 - Browser chrome, firefox (though I don't see how this is relevant)
 - Version Ventura 13.2.1 (22D68)

**Comment by EmericHochart** [comment]
Same Issue : French locale is selected, however many strings looks like internal IDs

**Comment by vidimus** [comment]
Try reimporting the official app files before starting Valkyrie.

**Comment by DarthGandalf** [comment]
@vidimus how do I do that?

I tried to go to `/Applications/Valkyrie.app/Contents/MacOS` in terminal and run `$ ./Valkyrie -import "$HOME/Library/Application Support/Steam/steamapps/common/Mansions of Madness/Mansions of Madness.app"` but it just shows the same window with resolution settings and starts as usual.

I also tried to click Reimport button when selecting between MoM and Descent, trying to give it that path, but it has no effect.

**Comment by DarthGandalf** [comment]
Importing data from non-steam version of MoM 1.8.8 didn't work either

**Comment by vidimus** [comment]
I can give you a link with the import folder contet, for you to try (just unzip the files and overwrite the ones already on your installation). Contact me on Discord because I don't know if I can share it here (due to IP restrictions). I'm on the official Valkyrie Discord, so reach me there, if you don't mind.

**Comment by DarthGandalf** [comment]
Thanks! With proper imported data, the strings are correct, and the game doesn't crash

**Comment by vidimus** [comment]
> Thanks! With proper imported data, the strings are correct, and the game doesn't crash

Glad to read that!
