### ISSUE TITLE
[Scenario] Fall Of Phobos - E1M1

### ISSUE THREAD

**Issue by Neuntoter82** [NPBruce/valkyrie#1617]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [ ] Mansions of Madness
- [ X] Descent

### What expansions does the scenario require?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

My custom Doom 2016 Mod - I added all warning about needing the mod and links to get it in the summary and the synopsis. I also did not add an expansion requirement in the editor itself to allow the scenario to not crash the Valkyrie app when loading the list of Quests.

### What expansions can the scenario optionally use?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### Please enter the GitHub Url to your scenario here

https://github.com/Neuntoter82/FOP-E1M1

**Comment by vidimus** [comment]
Added to the manifest. It will be available during the hour.

**Comment by Neuntoter82** [comment]
Thank you.
