### ISSUE TITLE
[Bug] Windows 10 - Valkyrie 2.5.8 unable to locate files for MoM 1.9.3 for reimport

### ISSUE THREAD

**Issue by MRex21z** [NPBruce/valkyrie#1619]
Recently attempted to reimport files from MoM (Steam) version 1.9.3.  Valkyrie app offers two red boxes at the bottom of screen "Install via Steam" and "Locate Game".

Neither work.  

Attempted reinstalling MoM files, and Valkyrie 2.5.8.  

Attempted to manually locate MoM files (the exe) and was able to click on them, but Valkyrie program did nothing.  Now, I am unable to use Valkyrie for Mansions of Madness.

Not sure how to proceed.  Not sure how to describe what is happening.

![Valkyrie opener](https://user-images.githubusercontent.com/132786978/236647190-1e3e3e6f-dc15-48b3-875d-a643e3fe1fc4.jpg)

![MoM file location](https://user-images.githubusercontent.com/132786978/236647193-e1cd7377-8038-49c6-b3f6-b5c18dc1b4b9.jpg)

**Comment by mal-w** [comment]
Check out https://github.com/NPBruce/valkyrie/issues/1605#issuecomment-1447982191

Basically you need to downgrade your Mansions of Madness install to 1.8.8 since there seem to be some issues with 1.9.2 and 1.9.3 from Valkyrie's side... The steps for how to downgrade are in the comment I linked.

**Comment by Quantumrunner** [comment]
Closed. Issue has been fixed in Release https://github.com/NPBruce/valkyrie/releases/tag/release%2F2.6%2F2.6.0a.
