### ISSUE TITLE
[Bug] Another issue with MoM (Steam) 1.9.3 - Tiles/Monsters/Actions

### ISSUE THREAD

**Issue by MRex21z** [NPBruce/valkyrie#1620]
Team,

I discovered another issue with Valkyrie 2.5.8 and MoM (Steam) 1.9.3.  In addition to the aforementioned inability to find the files, anytime Valkyrie runs, it displays an odd characteristic at certain points.  The lettering changes to ALL CAPS.

This occurs at the "choose investigators" page and at other points in the program.  This happens with Tiles, Objects, and Monster actions.  I have attached screenshots.

Additionally, when interacting with monsters, the attack function and evade function are unplayable, as can be seen in the screenshots.  I believe this has something to do with Valkyrie not recognizing the MoM 1.9.3 files.

Thank you.
![Odd lettering Valk](https://user-images.githubusercontent.com/132786978/236684486-9e65b8f8-db4e-4938-acea-a1e50d1e5381.jpg)

![Odd lettering Valk 02](https://user-images.githubusercontent.com/132786978/236684497-ba1b0e84-9e21-469e-a19b-2c369ae844a7.jpg)

![Odd lettering Valk 03](https://user-images.githubusercontent.com/132786978/236684509-79855856-2f8c-40c6-873b-4b568af7f03d.jpg)

![Odd lettering Valk 04](https://user-images.githubusercontent.com/132786978/236684521-d015457c-eddb-4e31-9365-c2a9ed78c319.jpg)

**Comment by vidimus** [comment]
@MRex21z , it looks like a typical problem with the import file. Try to reimport the files from the official app, if possible.

**Comment by MRex21z** [comment]
I don't know what that means.

Valkyrie won't reimport the data...at all.  When I click on "reimport data," a window opens up where I can navigate to the MoM (Steam) assets where I can click on the MoM executable.  When I do that, nothing happens.

**Comment by Quantumrunner** [comment]
Closed. Issue has been fixed in Release https://github.com/NPBruce/valkyrie/releases/tag/release%2F2.6%2F2.6.0a.
