### ISSUE TITLE
[Translation] The Truth - PL

### ISSUE THREAD

**Issue by sircohen** [NPBruce/valkyrie#1627]
[X] Mansions of Madness

[Translation] The Truth 

Hello!

As instructed on Discord, I am opening an issue related to the scenario called "The Truth". I have translated it into Polish. Enclosed you will find the .txt file with the translation. I have play-tested it offline on my computer and it should run smoothly without any major spelling mistakes on my part.

I would like the author of the scenario, @slycozzolino, to upload it as soon as he can :)

### Translation File
[Localization.Polish.txt](https://github.com/NPBruce/valkyrie/files/12117302/Localization.Polish.txt)

**Comment by vidimus** [comment]
@sircohen , there's a problem with your translation file. The first line should be in English (it's the language name and Valkyrie need it in English to successfully identify it). 

I've corrected that and also updated the Spanish version. So here it's the link with the Valkyrie package ready to be published.  @slycozzolino only need to replace the files on his repository with these:
https://github.com/vidimus/Valkyrie-Mom-scenarios-translations/tree/master/La%20verdad%20-%20The%20truth

**Comment by slycozzolino** [comment]
I'll try to get both of these updated to this evening.

**Comment by slycozzolino** [comment]
Sorry for the delay. Its been a while since I had to do this and my laptop I use to do it on has a new drive so I'm missing my old setup, but I think I got it. I pushed the new files and it appears they are showing up when I install the scenario. Please test and confirm your translation is working properly.

**Comment by vidimus** [comment]
> Sorry for the delay. Its been a while since I had to do this and my laptop I use to do it on has a new drive so I'm missing my old setup, but I think I got it. I pushed the new files and it appears they are showing up when I install the scenario. Please test and confirm your translation is working properly.

It's already online. @sircohen , you could now close this issue.

**Comment by sircohen** [comment]
Thank you! Closing the issue.
