### ISSUE TITLE
Random monster type from a list of traits (e.g. hot or dark or water) not possible 

### ISSUE THREAD

**Issue by Sadgit-HL** [NPBruce/valkyrie#163]
This would mirror the way a human overlord may choose monsters for a quest.

**Comment by NPBruce** [comment]
There are two problems:

1: Traits are all required rather than some.
2: If you have two open groups you want to make sure they are different.

This and #162 will require a bit of a rethink on monster selection.

**Comment by NPBruce** [comment]
The next release has an additional selection for 'traitpool' which is another list of traits where any one can be matched.

Also other monster events (renamed 'Spawn') can be added as exclusions.

**Comment by Sadgit-HL** [comment]
Perfect, thanks!
