### ISSUE TITLE
[Scenario] Historias de Arkham - Agatha Crane

### ISSUE THREAD

**Issue by DaniMassaro** [NPBruce/valkyrie#1634]
Hello!

I would like to publish the first scenario of the project "Historias de Arkham".

Thank you.

What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
x Mansions of Madness
 Descent
What expansions does the scenario require?
 Conversion Kit (CK)
 First Edition (MoM1E) - Also Recurring Nightmares
 Fatal Alchemy (FA) - Also Suppressed Memories
 Call of the Wild (CotW) - Also Suppressed Memories
 Beyond the Threshold (BtT)
 Streets of Arkham (SoA)
 Sunctum of Twilight (SoT)
 Horrific Journeys (HJ)
 Path of the Serpent (PotS)

What expansions can the scenario optionally use?
 Conversion Kit (CK)
 First Edition (MoM1E) - Also Recurring Nightmares
 Fatal Alchemy (FA) - Also Suppressed Memories
 Call of the Wild (CotW) - Also Suppressed Memories
 Beyond the Threshold (BtT)
 Streets of Arkham (SoA)
 Sunctum of Twilight (SoT)
 Horrific Journeys (HJ)
 Path of the Serpent (PotS)

Please enter the GitHub Url to your scenario here
https://github.com/DaniMassaro/AgathaCrane

**Comment by vidimus** [comment]
Added to the manifest.
@antontimmermans , would you mind to add it to the statistics?
