### ISSUE TITLE
[Scenario] The Abandoned Mansion 

### ISSUE THREAD

**Issue by vidimus** [NPBruce/valkyrie#1636]
"The Abandoned Mansion" is available in Chinese and Spanish. Only Core box is needed.

### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [ X ] Mansions of Madness
- [ ] Descent

### What expansions does the scenario require?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### What expansions can the scenario optionally use?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### Please enter the GitHub Url to your scenario here:
https://github.com/vidimus/Escenarios_para_Mansiones/tree/main/MansionAbandonada

**Comment by vidimus** [comment]
@antontimmermans , would you mind to add this to the statistics? Thanks!

**Comment by antontimmermans** [comment]
done
