### ISSUE TITLE
Release 2.6.0a feedback thread

### ISSUE THREAD

**Issue by Quantumrunner** [NPBruce/valkyrie#1641]
# Feedback for Release 2.6.0a
Please post any feedback for release 2.6.0a here.

Release notes for this release can be found here:
https://github.com/NPBruce/valkyrie/releases/tag/release%2F2.6%2F2.6.0a

We are especially interest in feedback if import on Android 13 works correctly now or still causes problems.

**Comment by rossbach-sascha** [comment]
I recently performed a fresh installation of "Mansions of Madness: Second Edition" along with downloading "Valkyrie for macOS (version 2.6.0a)" from https://github.com/NPBruce/valkyrie/releases/download/release%2F2.6%2F2.6.0a/valkyrie-macos-2.6.0a.tar.gz. After updating the app assets for Mansions of Madness, I transferred both the Valkyrie app and the Mansions of Madness app to my Applications folder. Despite this, I'm still encountering an error stating "unable to locate Mansions of Madness" whenever I try to launch the Valkyrie app. When I try to manually locate the Mansions of Madness app, nothing happens.

For reference, I'm operating on a MacBook Pro using MacOS Ventura 13.0.1, equipped with an Apple M1 Pro Chip.

**Comment by seinsinnes** [comment]
@rossbach-sascha
Is there also a link to the Mansions of Madness app on your desktop?
And if you remove the link on the desktop is Valkyrie able to find the MoM app?
I've seen this behaviour on MacOS where steam installs a desktop link and then Valkyrie tries to use the desktop link (instead of the actual app location) and fails.

**Comment by rossbach-sascha** [comment]
@seinsinnes i have removed the link of mansions of madness on the desktop but still get the same error "unable to locate Mansions of Madness".

**Comment by Quantumrunner** [comment]
@rossbach-sascha Did you follow the manual provided [here](https://github.com/NPBruce/valkyrie/wiki#mac-os). Especially this step:

> Also make sure, you have folder permissions. Move your Valkyrie download to the folder Applications inside the Finder app. Then run chmod +x /Applications/Valkyrie.app/Contents/MacOS/Valkyrie in the Terminal app.

**Comment by seinsinnes** [comment]
@rossbach-sascha
I suggest we look at the log:
```~/Library/Logs/Unity/Player.log```

And see if Valkyrie is looking in the right place. Success would have lines like:

```
Using location: /Applications/Mansions of Madness.app
Asset location: /Applications/Mansions of Madness.app/Contents/Resources/Data
Opening assets file/Applications/Mansions of Madness.app/Contents/Resources/Data/resources.assets
FFG MoM Version Found: 1.9.3
```

If it finds the App bundle but no resources.assets then:
```
Using location: /Applications/Mansions of Madness.app
Asset location: /Applications/Mansions of Madness.app/Contents/Resources/Data
Could not find main assets file: /Applications/Mansions of Madness.app/Contents/Resources/Data/resources.assets
FFG MoM not found.
```

Or whether it can't find the app bundle at all or some other failure mode.

**Comment by Quantumrunner** [comment]
Thread closed due to missing feedback.
