### ISSUE TITLE
[Bug] MoM - Black Screen middlegame and corrupted savefile - Perturbação nas Docas 2.1

### ISSUE THREAD

**Issue by vinylvini** [NPBruce/valkyrie#1642]
PC Windows 10 pro
Valkyrie Version 2.5.8

I played the scenario "Perturbação nas Docas 2.1" (portuguese translation) for about 3 hours. Towards to the ending (i think), the map went all black/blank. Everything else but "undo" works fine, i just can't see the map itself and the interactions within the map.

Everything on the menus is working, I can even end turns, interact with items, set fire, etc.

![image](https://github.com/NPBruce/valkyrie/assets/150918822/c994984b-20cf-417e-8c95-994f13a74673)

Loading screen (save files corrupted, thumbnail with black screen too)
![image](https://github.com/NPBruce/valkyrie/assets/150918822/33fb6095-8975-4d81-ba1a-70a7dd26c3f2)

[LIGHT SPOILER FROM THE SCENARIO BELOW]
Maybe a coincidence, but I think it happened at round 10 specifically after i interacted the first time with the bell and tried to insert the gems on it but i was missing some. Suddenly the map went black.

I tried saving and closing the app. Opening the app again and loading. There was 2 options for loading: autosave (several minutres earlier) and the manual save. I opened the manual save, it was still black. And then i came back to open the earlier autosave and it was replaced by a new recent save with black screen too. 
Now the autosave is ahead of the moment of the problem, because i kept trying to quickly advance some turns to check if it would fix.

I tried reinstalling the app in a new drive with more storage too (i backed up the save files). But didn't work.

I won't have a logfile because i removed and reinstalled the app.

Here are the save files [[LINK ON GOOGLE DRIVE]](https://drive.google.com/file/d/1DauNfpRYAqfV39b3ehooV2cwoZV2cRFw/view?usp=sharing). Can someone uncorrupt them? It was an amazing scenario, amazing and fun roleplay with my friends. We want to finish it.

**Comment by vidimus** [comment]
@antontimmermans , could you check this issue from one of your scenarios?

**Comment by vidimus** [comment]
Reinstalling the app won't fix this problem @vinylvini, because the save file is a complete copy of the scenario files, and the app will get them from the save zip, not from the download folder.

**Comment by antontimmermans** [comment]
hmm.. this is very very weird... when I load your save file I see the same behavior. But it gets weirder: if I load the scenario into the editor, also shows me the whole menu for editing, but the scenario playfield remains black too (not seeing the tiles and tokens).
After I restart the Valkyrie app, I can load the scenario into the editor and see everything as normal.

It looks like the scenario hit a bug in Valkyrie. I need some developer support to see what triggered it. And how to prevent that.
still investigating.

**Comment by antontimmermans** [comment]
PROBLEM SOLVED!!! @vinylvini 

In fact there is no problem, the map is still there but has moved out of your focus while you were playing with the bell. You probably had the mouse pointer pushed in a corner somewhere, which caused the camera position to move down.

If you zoom out a bit (scroll your mouse wheel back) and then look for the map you will find it is still there. The map has probably moved up. I had to move about 5-6 screen sizes up to find your map.

Sorry that it took me so long to figure this out. Good luck with completing the scenario :)

To compensate for the inconvenience, I give you one hint: "you might want to inspect the 'Missing Link' in your inventory a little closer

**Comment by vinylvini** [comment]
@antontimmermans amazing! thank you all so much for your efforts. Not only creating amazing maps but being accessible to help and support us.

Thanks for the hint too. Gonna finish this one up this weekend.

**Comment by antontimmermans** [comment]
Based on this feedback I added the use of Max and Min camera settings in this scenario. It will not help you with your saved game, but at least no other player will get the same surprise.

Can you confirm that your issue is solved by closing this ticket?
