### ISSUE TITLE
[Scenario] La Mansión de Gaizka 

### ISSUE THREAD

**Issue by JavierIceman12** [NPBruce/valkyrie#1643]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [x ] Mansions of Madness
- [ ] Descent

### What expansions does the scenario require?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [x ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [x ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [x ] Path of the Serpent (PotS)

### What expansions can the scenario optionally use?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [x ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [x ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [x ] Path of the Serpent (PotS)

### [Please enter the GitHub Url to your scenario here]

(https://github.com/JavierIceman12/LaMansionDeGaizka)

**Comment by vidimus** [comment]
Added to manifest.
@antontimmermans , would you mind to add it to the statistics?

**Comment by antontimmermans** [comment]
Added to the statistics sheets
