### ISSUE TITLE
[Translation] Consuming Shadow

### ISSUE THREAD

**Issue by sircohen** [NPBruce/valkyrie#1645]
### What kind of translation do you want to add (mark with an X, e.g. [X] Descent)?
- [x] Mansions of Madness
- [ ] Descent

### Translation File
[Localization.Polish.txt](https://github.com/NPBruce/valkyrie/files/13404616/Localization.Polish.txt)

**Comment by EwenDC** [comment]
I have pushed the translation on my end 🙂. This issue can be closed.

**Comment by sircohen** [comment]
Great! Thanks! Closing the issue.
