### ISSUE TITLE
[Scenario] Zaginięcie Emmy Evans

### ISSUE THREAD

**Issue by Pancernik90** [NPBruce/valkyrie#1650]
https://github.com/Pancernik90/Zagini-cie-Emmy-Evans

### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [ x ] Mansions of Madness
- [ ] Descent

### What expansions does the scenario require?
- [ x ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ x ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### What expansions can the scenario optionally use?
- [ x ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ x ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### [Please enter the GitHub Url to your scenario here]
(https://github.com/Pancernik90/Zagini-cie-Emmy-Evans)

**Comment by vidimus** [comment]
Hello, @Pancernik90 , thanks for creating a scenario and share it with the Valkyrie's community.

Could you edit the repository name to remove the special character "-" (hyphen), please. I will add the scenario to the manifest after that.

**Comment by Pancernik90** [comment]
Of course, it's done. 
If i want to make changes in scenario, or get some update from people, i can just delete files in repository and upload updated versions?
Just asking for the future.

**Comment by vidimus** [comment]
Great, thanks, @Pancernik90 

Yes, you can update the scenario directly. Be aware and do not change the path or the file names to prevent Valkyrie to link them. 

The scenario has beed added to the manifest. It should become available in an hour or less.

By the way, I would like to translate the scenario into Spanish as soon as you have a "stable" version.

@antontimmermans , would you mind to add it to the statistics, please?

**Comment by antontimmermans** [comment]
Added to statistics sheets
