### ISSUE TITLE
[Translation] The Fall of House Lynch

### ISSUE THREAD

**Issue by sircohen** [NPBruce/valkyrie#1651]
### What kind of translation do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

### Translation File

[Localization.Polish.txt](https://github.com/NPBruce/valkyrie/files/13839606/Localization.Polish.txt)

**Comment by NPBruce** [comment]
Done.

**Comment by sircohen** [comment]
Thanks! Closing issue.
