### ISSUE TITLE
Slightly misplaced writing and boxes within gameplay all scenarios

### ISSUE THREAD

**Issue by bpbpbpbpbp** [NPBruce/valkyrie#1652]
I am running the Windows version of the app and everything appears to be working fine except that some of the writing and boxes used for framing writing appears misplaced. I've randomly tried a few of the scenarios. Happens in all of them. Changing the window resolution at the beginning also does not affect this issue

<img width="465" alt="image" src="https://github.com/NPBruce/valkyrie/assets/39391481/4c2daeff-ecc7-4b47-a9ee-7ba0ad944bb0">

Misplaced writing in select scenario
<img width="1399" alt="image" src="https://github.com/NPBruce/valkyrie/assets/39391481/d569f813-33ac-4a13-ae82-04986a39d3e5">

Misplaced writing on landing page
<img width="1490" alt="image" src="https://github.com/NPBruce/valkyrie/assets/39391481/67b5732b-2e13-4b61-9a85-dc3f514f7f46">

Misplaced writing in gameplay
<img width="1492" alt="image" src="https://github.com/NPBruce/valkyrie/assets/39391481/ca6c8e26-4ff6-4713-a932-3054e6b8acfc">

[output_log.txt](https://github.com/NPBruce/valkyrie/files/13852542/output_log.txt)

2.6.0.

I am running this under Windows 11 in the emulator Parallels on a Mac. I've never had any issues running Windows programs in this way. Anyway, overall seems still playable even if this issue cannot be resolved. Just wondering about this part

<img width="164" alt="image" src="https://github.com/NPBruce/valkyrie/assets/39391481/fcf0c5ad-1e98-4240-8bef-474c329c3518">

That seems important. What is this supposed to say and do?

**Comment by Quantumrunner** [comment]
Why are you not using the official MAC version but instead running Windows version in an emulator?

It seems that Unity has problems identifying the resolution correctly while running this in the emulator. I checked the same resolution and scenario on my windows PC and could not find any issues.

**Comment by bpbpbpbpbp** [comment]
Thanks for having a look at this for me and, if you are part of the team behind Valkyrie, also thank you very much for making this app available to the rest of the world.
> Why are you not using the official MAC version but instead running Windows version in an emulator?
> 
Tried that first but no luck. Valkyrie installs but I cannot select the MoM app from within Valkyrie. In the first instance Valkyrie is looking for something with an .app extension which my copy of MoM does not appear to have. Adding the .app extension lets Valkyrie see MoM but then selecting does not do anything. Considered going via Steam again. However it appears that Steam has just ceased the support for the Mac version for the MoM app. Anyway, decided to cut my losses and install on a Windows machine instead. The first attempt there, on a real Windows computer gets everything going. However, no matter what scenario I load, Valkyrie crashes a few steps in. Installing within the emulated Windows environment was my third attempt at getting this to work :)

Anyway, what I’ve got is, hopefully, playable enough. It all looks pretty exciting. I’ve only got four scenarios of the 22 original ones left to play and am looking forward to trying some of these unofficial scenarios. 

All the best,






Burkard Polster 
School of Mathematics
Clayton Campus
9 Rainforest Walk, rm 307
Monash University, Vic 3800
Australia

Monash <https://research.monash.edu/en/persons/burkard-polster>, Maths Masters <http://www.qedcat.com/>, Mathologer <http://www.youtube.com/c/mathologer>

**Comment by Quantumrunner** [comment]
>  However it appears that Steam has just ceased the support for the Mac version for the MoM app. 

Ok I did not know that. :(

You can always check the log files for details but I don't think it will show much regarding those resolution issues:
https://github.com/NPBruce/valkyrie/wiki/Troubleshooting#find-log-files

**Comment by bpbpbpbpbp** [comment]
Thanks again for looking. In the meantime, I've succeeded in getting Valkyrie to work properly on an older Mac :)

**Comment by Quantumrunner** [comment]
Good that it works now with your setup. I wish you a lot of fun trying out the custom scenarios.
