### ISSUE TITLE
[Scenario] GuardiansofDeephall

### ISSUE THREAD

**Issue by afellowspelunker** [NPBruce/valkyrie#1654]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [ ] Mansions of Madness
- [X] Descent

### What expansions does the scenario require?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### What expansions can the scenario optionally use?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [ ] Beyond the Threshold (BtT)
- [ ] Streets of Arkham (SoA)
- [ ] Sunctum of Twilight (SoT)
- [ ] Horrific Journeys (HJ)
- [ ] Path of the Serpent (PotS)

### Please enter the GitHub Url to your scenario here

I have created a new Descent 2E scenario:

Name: Guardians of Deephall

https://github.com/afellowspelunker/GuardiansofDeephall

Could you please add it to the mission list?

**Comment by vidimus** [comment]
@afellowspelunker , could you close this issue, please?

**Comment by afellowspelunker** [comment]
Ah yes.  I see the Descent quest is up on the Valkyrie mission listing, looks good, thanks.

Closing this issue.
