### ISSUE TITLE
Silver Twilight Halloween

### ISSUE THREAD

**Issue by NicolaZee** [NPBruce/valkyrie#1655]
Mansions of Madness

Expansions needed:
    Streets of Arkham (SoA)
    Sanctum of Twilight (SoT)

### GitHub Url to your scenario here
https://github.com/NicolaZee/PublishedScenarios/tree/master/SilverTwilightHalloween

**Comment by vidimus** [comment]
What a delightful surprise, @NicolaZee. Thanks for creating a new scenario.

It has been added to the manifest. It should be available within an hour.

**Comment by vidimus** [comment]
@antontimmermans , could you add this scenario to the statistics, and close the issue, please?

**Comment by NicolaZee** [comment]
Thanks for adding it.

**Comment by antontimmermans** [comment]
added to the statistics sheets
