### ISSUE TITLE
[Bug] Can't start a scenario 

### ISSUE THREAD

**Issue by MaxDread** [NPBruce/valkyrie#1656]
Hey,
Android 13 user here. I hace installed the official app and the latest valkiryre app. The app works perfectly but when I start an scenario after the text is shown when I click continue the app closes automatically. What should I do?

**Comment by vidimus** [comment]
Try to reimport the files. It might take a few minutes to do it. Before doing it, go to the official app, select all the expansions in your collection, wait for any assets to download, restart the app, and ensure you have the last version.

**Comment by Tytanomachia** [comment]
> go to the official app,

I have exactly the same problem as above. When I start an scenario after the text is shown when I click continue the app closes automatically. I did what you wrote above, but it didn't help. Could anyone help with this problem? Android 10. Regards.

**Comment by Tytanomachia** [comment]
> Hey, Android 13 user here. I hace installed the official app and the latest valkiryre app. The app works perfectly but when I start an scenario after the text is shown when I click continue the app closes automatically. What should I do?

Did you able to fix this bug?

**Comment by Tytanomachia** [comment]
> I have exactly the same problem as above. When I start an scenario after the text is shown when I click continue the app closes automatically. I did what you wrote above, but it didn't help. Could anyone help with this problem? Android 10. Regards.

I have exactly the same problem as above. When I start an scenario after the text is shown when I click continue the app closes automatically. I did what you wrote above, but it didn't help. Could anyone help with this problem? Android 10. Regards.

**Comment by DanielNelHeck** [comment]
Hello guys, same problm here. Samsung TAB A+ running Android 14.
I can list scenarios, download content, hear/read the intro but when I click final continue to start setup it crashes.

**Comment by antontimmermans** [comment]
If the answer from Vidimus didn't solve your problem, please find us on Discord in the #support channel (see also link on the main GitHub page of Valkyrie https://github.com/NPBruce/valkyrie).
closing this issue
