### ISSUE TITLE
[Question] custom music

### ISSUE THREAD

**Issue by kozka** [NPBruce/valkyrie#1657]
Can you add custom music when you are creating a stage?
I have seen that you can add ogg, if you leave them in the folder, but.
If so, is there a variable inside to know the language and select different audio?  I wanted to add a narrator to the scenario I'm creating

**Comment by vidimus** [comment]
Hello, @kozka 
You could add music or sounds to your scenario. Just copy the files in the scenario folder (C:\Users\USERXXXX\AppData\Roaming\Valkyrie\MoM\Editor for Windows, it's a system folder, so it's hidden).

If you want to add different files for another language, just create a folder with the language name in English and copy there the files for that language. I.e., you have a voiceover in English (the scenario default language) but you have a Spanish translation too. In that case, you will add the voiceover to your scenario folder (editorscenario1); the Spanish voiceover will be in a folder called "Spanish", path \editor\Editorscenario1\Spanish

**Comment by kozka** [comment]
any way to add a timer until the audio ends so that you can press continue when the audio ends with some timer or something like that?

**Comment by antontimmermans** [comment]
Valkyrie does not support any timers, so you cannot automatically continue after the audio is finished or a timer has expired. 

However, you can stop the audio if a user clicks a button to go to the next event. This is useful if you want to stop the introduction audio file when a user continues to start the scenario and does not want to hear the full introduction audio.
In an event there are two fields to add audio to your event:
<img width="221" alt="image" src="https://github.com/user-attachments/assets/dd9674e7-f185-4d0f-8b05-32ef38b9cc75">
**Audio**: any audio selected in this event will be played until it is finished and cannot be stopped. Any other audio will be mixed with this sound until it is completed.
**Music**: any audio selected in this event will be played until it is finished **or is replaced with other audio in the next event.** The next event should then have another audio file in this field. For this purpose, I created a NOSOUND.OGG with 1 second silence. 
Alternatively, you can select a built-in sound:
<img width="232" alt="image" src="https://github.com/user-attachments/assets/c9be8f87-785a-4cd0-89e0-1f2f6cab4951">

**Comment by antontimmermans** [comment]
I assume that your question has been answered, so I am closing this issue.

If you have more questions, you should find us on Discord (find the link at the bottom of the main page of this repository https://github.com/NPBruce/valkyrie/wiki). You will get faster responses and more scenario-writing experts will support you.
