### ISSUE TITLE
[Bug] Blank Screen in online Quest Select Screen in Valkyrie (D2E)

### ISSUE THREAD

**Issue by afellowspelunker** [NPBruce/valkyrie#1659]
### Describe the bug
When selecting New Game in Valkyrie, it only shows a blank screen with no quests to select.  If I go offline, I can see and select the quests I have already downloaded.

### Scenario
All

### Steps to reproduce the behavior:
4. See error-->

### Expected behavior
I expected to see a list of available D2E quests to download and play.

### LogFile
[output_log.txt](https://github.com/NPBruce/valkyrie/files/14256067/output_log.txt)

### Valkyrie Version
2.6.0

### Additional context
This big block of text in the output_log file shows something about Google Drive Quota issue?

Thanks for checking on this.

**Comment by BUDY789** [comment]
Same issue, it must be a down server error

**Comment by afellowspelunker** [comment]
Looks like we're back up again.

Whether a server issue or you fixed it, thanks!

Closing this issue.
