### ISSUE TITLE
Unable to Start MoM in Valkyrie App

### ISSUE THREAD

**Issue by Smigi89** [NPBruce/valkyrie#1660]
Device
Samsung A Tab Android 11

After granting all needed permisons in settings like acces to Storage or uknow app. I start up the app and hit import , chose correct folder and hit import. The import process is running and take few minuses. After that the screen goes black and app gets to tab desktop. When Running it again I still got only import option. 

When checking Valkryie folder I see that files have been imported and look same like those on my phone with Android 13 which is running app smoothly. I even did same steps like for android 13 guide in troubleshoting guide with "files" app and total commader. 

Still cant make it run into Mansion of Madness content.

**Comment by vidimus** [comment]
@Smigi89 try with the 2.5.8 version. Be sure you have all the expansions marked in the official app and all the content updated (all the assets downloaded).

https://github.com/NPBruce/valkyrie/releases/download/release%2F2.5%2F2.5.8/Valkyrie-android-2.5.8.apk

**Comment by Smigi89** [comment]
Thank You for quick reply.

Unfortunately rolling back to 2.5.8 version didn't help. Valkyrie was unable to locate game directory. I have marked all expansions on MoM. After that I updated back to latest version. Valkyrie recognise the game directory, imported the files yet still was unable to run MoM content. I gave it all permissions both to 2.5.8 and latest version.

**Comment by vidimus** [comment]
@Smigi89 , have you tried to copy the whole folder from the android 13 device into the android 11? Strangely, you could do all the importation. Normally it's where others have the problem. How much RAM has your android 11 device?

**Comment by Smigi89** [comment]
@vidimus Hello. Yes I tried. I connected my phone with android 13 copied whole valkyrie folder on desktop and then to tablet with android 11. Still nothing, app want me to import files anyway. After import it quit to tablet desktop.

**Comment by vidimus** [comment]
> @vidimus Hello. Yes I tried. I connected my phone with android 13 copied whole valkyrie folder on desktop and then to tablet with android 11. Still nothing, app want me to import files anyway. After import it quit to tablet desktop.

That's weird. Download some scenarios with the working device, and then copy Valkyrie's download folder to the Android 11 device. Open the app, go to the scenario list, and select "offline". Try to open a scenario and see if this works.

**Comment by antontimmermans** [comment]
No reactions from the submitter anymore -> closing the issue. Please re-open if it persists
