### ISSUE TITLE
[Translation] The Curse of the Blind Stalker

### ISSUE THREAD

**Issue by sircohen** [NPBruce/valkyrie#1661]
### What kind of translation do you want to add (mark with an X, e.g. [X] Descent)?
- [x] Mansions of Madness
- [ ] Descent

### Translation File
[Localization.Polish.txt](https://github.com/NPBruce/valkyrie/files/14302061/Localization.Polish.txt)

**Comment by vidimus** [comment]
Great, It should be available within an hour. You could close this issue as soon as you check the update with the Polish translation is online.

**Comment by sircohen** [comment]
Thanks! Everything seems to be in order. Closing the issue.
