### ISSUE TITLE
[Question]D2e Map Tiles Missing

### ISSUE THREAD

**Issue by any2cards** [NPBruce/valkyrie#1664]
### Description of Problem or Question
After importing D2e into Valkyrie, I notice the following map tile images missing from C:\Users\any2c\AppData\Roaming\Valkyrie\D2E\import\img:

030b, 032a, 033b, 034a, 044b, 045a, 046a, 047a, 061b, 064a, 064b, 075a, 077a, 079b, 097b

### Valkyrie Version
Valkyrie 2.6.0 on Windows 11

**Comment by vidimus** [comment]
@any2cards be sure you marked all the expansions in the official app and download all the assets before doing the Valkyrie import.

**Comment by NPBruce** [comment]
These images are not used in any official scenarios. Valkyrie provides a low detail placeholder to allow their use in Valkyrie scenarios.

**Comment by any2cards** [comment]
Bruce ... I am curious if you happen to have high resolution versions of the map tiles mentioned above, in the format of all of the other ones within Valkyrie?

**Comment by NPBruce** [comment]
Sorry, I do not.
