### ISSUE TITLE
[Scenario] CD1 - Burning Harvest

### ISSUE THREAD

**Issue by afellowspelunker** [NPBruce/valkyrie#1669]
Greetings,
I have created a new Descent 2E quest for Valkyrie.  Can you please add it to the mission list?

Name: CD1 - Burning Harvest

### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [ ] Mansions of Madness
- [X] Descent

### Please enter the GitHub Url to your scenario here
Link: https://github.com/afellowspelunker/BurningHarvest

**Comment by vidimus** [comment]
Added to the manifest and to the statistics.
Thanks for creating this quest, @afellowspelunker 

You can now close this issue.

**Comment by afellowspelunker** [comment]
Looks good on the front end, thank you @vidimus for the quick response and encouragement.

Closing this issue.
