### ISSUE TITLE
[Scenario] CD2 - Crown of Destiny

### ISSUE THREAD

**Issue by afellowspelunker** [NPBruce/valkyrie#1670]
Greetings,
I have created a new Descent 2E quest for Valkyrie.  Can you please add it to the mission list?

Name: CD2 - Crown of Destiny

### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [ ] Mansions of Madness
- [X] Descent

### Please enter the GitHub Url to your scenario here
Link: https://github.com/afellowspelunker/CrownofDestiny

**Comment by vidimus** [comment]
Added to the manifest and to the statistics.
Thanks for creating this quest, @afellowspelunker 

You can now close this issue, too.

**Comment by afellowspelunker** [comment]
Looks good on the front end, thank you @vidimus for the quick response and encouragement.

Closing this issue, too.
