### ISSUE TITLE
[Scenario] The Telltale Curse

### ISSUE THREAD

**Issue by vidimus** [NPBruce/valkyrie#1671]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

### What expansions does the scenario require?
- [X] Streets of Arkham (SoA)
- [X] Horrific Journeys (HJ)

### Please enter the GitHub Url to your scenario here
https://github.com/vidimus/DomeAcolyte/tree/main/Lost_chronicles_10

Another scenario by DomeAcolyte.
"The Cult of Cthulhu roam the streets and your choices will determine if you stop them or die trying."

**Comment by vidimus** [comment]
@antontimmermans , could you add this scenario to the statistics, please?

**Comment by antontimmermans** [comment]
Scenario Added to statistics

**Comment by BuranUstinov** [comment]
Code??????????

**Comment by vidimus** [comment]
> Code??????????

Hello. Could you be more specific?
