### ISSUE TITLE
[Scenario] One Man's Trash and [Scenario] Bonds of the Wild

### ISSUE THREAD

**Issue by afellowspelunker** [NPBruce/valkyrie#1674]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [ ] Mansions of Madness
- [X] Descent

I have adapted two new Descent 2E quests.  Can these be added to the mission list?

### Please enter the GitHub Url to your scenario here
BW1 - One Man's Trash
https://github.com/afellowspelunker/OneMansTrash

BW2 - Bonds of the Wild
https://github.com/afellowspelunker/BondsoftheWild

**Comment by vidimus** [comment]
Both are now added to the manifest. Thanks a lot for your hard work, @afellowspelunker 
They should be available within an hour.

**Comment by afellowspelunker** [comment]
Looking good, on the mission list now.  Thanks @vidimus for your support and admin on these projects.
