### ISSUE TITLE
[Scenario] CF1 - Crusade of the Forgotten, CF2 - Shadowside Watch

### ISSUE THREAD

**Issue by afellowspelunker** [NPBruce/valkyrie#1676]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [ ] Mansions of Madness
- [X] Descent

I've uploaded two new quests for Descent 2E to GitHub.  Can these be added to the mission listing?
CF1 - Crusade of the Forgotten
CF2 - Shadowside Watch

Thanks.

### Please enter the GitHub Url to your scenario here
https://github.com/afellowspelunker/CrusadeoftheForgotten
https://github.com/afellowspelunker/ShadowsideWatch

**Comment by vidimus** [comment]
Added to the manifest. Thanks for your hard work, @afellowspelunker

**Comment by afellowspelunker** [comment]
I see them on the mission listing now.  Thanks @vidimus !
