### ISSUE TITLE
[Translation] Last train to Arkham 1.1 (Russian)

### ISSUE THREAD

**Issue by Krasavvec** [NPBruce/valkyrie#1677]
### What kind of translation do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

Last train to Arkham 1.1

[Localization.Russian.txt](https://github.com/user-attachments/files/15926206/Localization.Russian.txt)

**Comment by vidimus** [comment]
@antontimmermans

**Comment by antontimmermans** [comment]
This translation contains 200 fewer lines of text than the original text. Also, the order of the lines has changed so I cannot check what is missing. It may still be a playable translation and it would be a waste of good effort not to include it. Thank you for making it.

Could you keep an eye on the feedback? If any issues are reported I will disable this translation.
