### ISSUE TITLE
[Question] Remove save file to another device

### ISSUE THREAD

**Issue by Plachon** [NPBruce/valkyrie#1678]
My question is, how to remove save files to another device with Valkirie app.

**Comment by redwolf2** [comment]
In windows, the save files should be located in the directory:

C:\Users\user\AppData\Roaming\Valkyrie\MoM\Save

You can copy them from there to the other device using the same folder structure.

**Comment by vidimus** [comment]
Android:

Device\Valkyrie\MoM\Save

**Comment by antontimmermans** [comment]
@Plachon please confirm if this answers your question and close this issue if it does

**Comment by Plachon** [comment]
Thank you for a tip.
