### ISSUE TITLE
[Scenario] Lost of Exist (존재의 상실)

### ISSUE THREAD

**Issue by vidimus** [NPBruce/valkyrie#1683]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

### Please enter the GitHub Url to your scenario here
https://github.com/vidimus/Corea/tree/main/lostofexist

Another Korean scenario from 2019 but unpublished in the past due to the lack of Korean language support, with already 28 recorded plays in Valkyrie.

"6 hours before the wedding,the groom went missing from the bride's home..."

No expansions are needed.

**Comment by antontimmermans** [comment]
Added to the scenario sheets.
Renamed all 'lost of exist.valkyrie' entries to 'lostofexist.valkyrie' to include old ratings
