### ISSUE TITLE
[Scenario] El Horror de Aylesbury

### ISSUE THREAD

**Issue by DaniMassaro** [NPBruce/valkyrie#1684]
Hello!

I would like to publish my 7th scenario.

Thank you.

What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
x Mansions of Madness
 Descent

What expansions does the scenario require?
 Conversion Kit (CK)
 First Edition (MoM1E) - Also Recurring Nightmares
 Fatal Alchemy (FA) - Also Suppressed Memories
 Call of the Wild (CotW) - Also Suppressed Memories
 Beyond the Threshold (BtT)
 x Streets of Arkham (SoA)
 Sunctum of Twilight (SoT)
 Horrific Journeys (HJ)
 Path of the Serpent (PotS)

What expansions can the scenario optionally use?
 Conversion Kit (CK)
 First Edition (MoM1E) - Also Recurring Nightmares
 Fatal Alchemy (FA) - Also Suppressed Memories
 Call of the Wild (CotW) - Also Suppressed Memories
 Beyond the Threshold (BtT)
 Streets of Arkham (SoA)
 Sunctum of Twilight (SoT)
 Horrific Journeys (HJ)
 Path of the Serpent (PotS)

Please enter the GitHub Url to your scenario here
https://github.com/DaniMassaro/ElHorrorDeAylesbury

**Comment by vidimus** [comment]
Great news| Thanks for creating a new scenario, @DaniMassaro 

@antontimmermans , could you please add this one to the statistics?

**Comment by antontimmermans** [comment]
Done
