### ISSUE TITLE
[Scenario] LA BRUMA MALDITA PART-1

### ISSUE THREAD

**Issue by kozka** [NPBruce/valkyrie#1687]
I wanted to request that my scenario be added to Valkyrie

### Name:
LA BRUMA MALDITA PART1 

### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

### What expansions does the scenario require?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [X] Beyond the Threshold (BtT)
- [X] Streets of Arkham (SoA)
- [X] Sunctum of Twilight (SoT)
- [X] Horrific Journeys (HJ)
- [X] Path of the Serpent (PotS)

### What expansions can the scenario optionally use?
- [ ] Conversion Kit (CK)
- [ ] First Edition (MoM1E) - Also Recurring Nightmares
- [ ] Fatal Alchemy (FA) - Also Suppressed Memories
- [ ] Call of the Wild (CotW) - Also Suppressed Memories
- [X] Beyond the Threshold (BtT)
- [X] Streets of Arkham (SoA)
- [X] Sunctum of Twilight (SoT)
- [X] Horrific Journeys (HJ)
- [X] Path of the Serpent (PotS)

###I have left the files here:
https://github.com/kozka/mom_bruma/tree/main/bruma_maldita1

###translated 
Spanish, English, Italian, German

This is my first time making a scenario, if there is any problem, let me know.
I think they are quite well tested
I hope I can finish part 2 in a month, I'm pretty far along

I hope you like it, greetings :)

**Comment by vidimus** [comment]
Hello, @kozka 
The scenario has been added to Valkyrie. It should be available within an hour.

@antontimmermans , would you mind to add it to the statistics?

**Comment by vidimus** [comment]
@kozka , you can close this issue. The scenario is on and it has been added to the statistics.
