### ISSUE TITLE
[Scenario] Stewards of the Secret

### ISSUE THREAD

**Issue by afellowspelunker** [NPBruce/valkyrie#1688]
I have adapted a new quest for Descent 2nd Ed.  Can you please add it to the mission listing?

Name:
SS1 - Stewards of the Secret

### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [ ] Mansions of Madness
- [X] Descent

### What expansions does the scenario require?
None

### Please enter the GitHub Url to your scenario here
https://github.com/afellowspelunker/StewardsoftheSecret

**Comment by vidimus** [comment]
@afellowspelunker , thanks for creating it. Added to the manifest. It should be available within an hour.

**Comment by afellowspelunker** [comment]
Looks good, thank you.
