### ISSUE TITLE
[Scenario] Sindaea's Secret

### ISSUE THREAD

**Issue by afellowspelunker** [NPBruce/valkyrie#1694]
Greetings,
I have adapted a new Descent 2E scenario:

TC1 - Sindaea's Secret

Could you please add it to the mission listing?
Thanks

### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [ ] Mansions of Madness
- [X] Descent

### What expansions does the scenario require?
None
### What expansions can the scenario optionally use?
All
### Please enter the GitHub Url to your scenario here
https://github.com/afellowspelunker/SindaeasSecret

**Comment by vidimus** [comment]
Quest added to the manifest. It should be available within an hour. A big thanks for @afellowspelunker

**Comment by afellowspelunker** [comment]
Looks good, thanks!
