### ISSUE TITLE
Multiple triggered events: only the first in the list is actually triggered.

### ISSUE THREAD

**Issue by Liquidlogic1** [NPBruce/valkyrie#17]
Example: EventRevealTile triggers two events under Flags/Events -> Trigger Events: RevealTokenRed, and RevealTokenBlue. When EventRevealTile occurs, only the top event in the "Trigger Events" list is triggered (in this case Red).

Quest.ini (in txt)

[Quest.txt](https://github.com/NPBruce/valkyrie/files/458267/Quest.txt)

**Comment by NPBruce** [comment]
This is intentional. The list is so that you can have alternatives using flags. If you want to chain events add them in sequence.
