### ISSUE TITLE
[Scenario] VD1 - Trucebreaker

### ISSUE THREAD

**Issue by afellowspelunker** [NPBruce/valkyrie#1701]
Greetings,
I have adapted a new scenario for Descent 2E.  Can you add it to the mission listing please?

Name: VD1 - Trucebreaker

### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [ ] Mansions of Madness
- [X] Descent

### Please enter the GitHub Url to your scenario here
https://github.com/afellowspelunker/Trucebreaker

**Comment by vidimus** [comment]
Hello, @afellowspelunker .

Quest added to the manifest. It will be also added to Descent statistics.

**Comment by afellowspelunker** [comment]
Thank you @vidimus !

Looks good, closing issue.
