### ISSUE TITLE
[Scenario] The Four Day Broadcast

### ISSUE THREAD

**Issue by vidimus** [NPBruce/valkyrie#1706]
### What kind of mission do you want to add (mark with an X, e.g. [X] Descent)?
- [X] Mansions of Madness
- [ ] Descent

### Please enter the GitHub Url to your scenario here

https://github.com/vidimus/DomeAcolyte/tree/main/Lost_chronicles_11

A new scenario from Dome Acolyte. A murder mystery inspired by an old game called Four Days a Stranger, and its sequels.

**Comment by vidimus** [comment]
@antontimmermans , would you mind to add it to the statistics, please?

**Comment by antontimmermans** [comment]
added to statisitcs
