### ISSUE TITLE
Monster frames for 1x2 monsters are not correct.

### ISSUE THREAD

**Issue by Sadgit-HL** [NPBruce/valkyrie#171]
![bug3](https://cloud.githubusercontent.com/assets/26650531/24615115/ad9dbade-188d-11e7-8209-e4995764ac58.jpg)

**Comment by NPBruce** [comment]
I assume you mean the white/red background being circular rather than oval shape?

**Comment by Sadgit-HL** [comment]
Yes, that is what I meant.
