### ISSUE TITLE
App doesnt start on Mac

### ISSUE THREAD

**Issue by Ashgur** [NPBruce/valkyrie#178]
Hey there,

unfortunately i still cant open the app. Everytime i try an error is going to pop up:
"The application “Valkyrie” can’t be opened."
I already tried to open it without gatekeeper (ctrl+klick -> open) with the same result.
My osx version is el capitan 10.11.

Im thankful for any advice ;-) Have a nice evening!

**Comment by NPBruce** [comment]
If it exists please add ~/Library/Logs/Unity/Player.log

It sounds like you can't run it at all though, so hopefully someone with MacOS can help you on how to start it.

**Comment by Ashgur** [comment]
doesnt exist =/ y, hopefully ;-)

**Comment by asherdiamant** [comment]
Same problem, on Sierra. Disabling Gatekeeper didn't help (didn't think it would, it didn't look like a security warning). It is recognized as an app (judging by the error message), but can't start might indicate an issue with how the package is built?
Anyone had success running it on OS X recently?

**Comment by NPBruce** [comment]
Users in #49 had it working.  Haven't had confirmation on 0.8.3 or 0.8.4, but you can try the dev builds in #49 and see if you have the same problem.

**Comment by asherdiamant** [comment]
Tried the dev builds - same problem.

**Comment by asherdiamant** [comment]
ok, found the problem. I'm using a third party zip utility (keka). Using the system's 'archive utility' (by doing right-click/open with...) fixed the issue.

**Comment by jnierodzik** [comment]
Good call @asherdiamant 

What I'm assuming is happening is that the third party utility is mucking with the binary inside the application and making it not executable.  If you could would you extract the application again, using Keka, and then from the terminal run this command.

`sudo chmod +x /path/to/Valkyrie.app/Contents/MacOS/*`

Then try running it.

**Comment by asherdiamant** [comment]
Yup, that works, jnierodzik. Now to the next issue. It starts up, but can't locate the the Descent RTL files. Tells me to install it in Steam, but I have it already installed on Steam.
Looking at player.log, it looks like it's searching for \Descent Road to Legend.app, while the app name is just Road to Legend.app
[Player.log.zip](https://github.com/NPBruce/valkyrie/files/901369/Player.log.zip)

**Comment by NPBruce** [comment]
[valkyrie-macos-0.8.5b.zip](https://github.com/NPBruce/valkyrie/files/901402/valkyrie-macos-0.8.5b.zip)
Try this.

**Comment by asherdiamant** [comment]
Find the app and assets file, crashes unity when trying to import. From user point of view I'm clicking on import, get a black screen with "importing..." in the middle, and it gets stuck there.
[Player.log 2.zip](https://github.com/NPBruce/valkyrie/files/901410/Player.log.2.zip)

**Comment by NPBruce** [comment]
Looks like it can't write its content out, in windows it does this whereever you extract the zip.  This is not a simple fix. Interesting that others don't have this problem, so perhaps there is a work around?

**Comment by Ashgur** [comment]
Nice, this does work for me! App is starting, i can import the files and start a szenario! Nice!

**Comment by jnierodzik** [comment]
@asherdiamant does the import only hang for the Descent import or for the MoM import as well?  Are you running this from an admin user or standard?  Just trying to determine what might be different in our setups.

**Comment by asherdiamant** [comment]
Didn't try MoM, as I don't own the game. My user has admin rights, so shouldn't have a problem. Where are you running the app from? I'm just running it from the downloads directory, but I can try copying it to applications. 
Well, that works. Running it from the applications folder works, and I downloaded the quests, ran a quest and tried editing a quest, all work fine now.
Thanks for the support. If you need more Mac OS X testing, I'll be happy to help.

**Comment by eorahil** [comment]
A question for Mac users, 
In Windows, when you save or download an scenario, you can browse to its folder and see/edit its files by browsing to Drive:\Users\[Myuser]\AppData\Roaming\Valkyrie
Do you know what is the equivalent folder for a Mac computer?

**Comment by jnierodzik** [comment]
@eorahil try checking here

/Users/[username]/.config/Valkyrie

**Comment by eorahil** [comment]
Thanks!

**Comment by NPBruce** [comment]
CLosing as hopefully fixed in #504
