### ISSUE TITLE
Tiles not connecting flush with one another (list).

### ISSUE THREAD

**Issue by Liquidlogic1** [NPBruce/valkyrie#18]
0.3.1
These tiles do not connect flush with other tiles (some are closer than others). I think it has to do with the point around where they rotate (the star icon), but I'm not sure.  I went through all the tiles and tried to connect them to others that connect flush. I also checked 0.2.2 and 0.3.0 and the issue was there as well.

5A (see other naming bug), 15, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30. 

[Quest.txt](https://github.com/NPBruce/valkyrie/files/460743/Quest.txt)

**Comment by NPBruce** [comment]
5A seems OK, but the 6A tile pulling up the 5A image is fixed.

15A/B, 19A, 21A/B, 22A, 23A/B, 24A/B, 25A/B were all a bit out and will be fixed in the next release.

I couldn't see anything wrong with 26, 27, 28, 29 and 30, please reopen if I have missed something.
