### ISSUE TITLE
Wrong path for RtL assets on MacOS

### ISSUE THREAD

**Issue by dchapde** [NPBruce/valkyrie#181]
On MacOS Road To Legend assets data can't be found. The path is wrong at: [RtLFinder.cs:30](https://github.com/NPBruce/valkyrie/blob/b559c163af889ed354fe18f6df9907bba8ee37c4/Assets/Scripts/Content/AssetImport/RtLFinder.cs#L30) it should be: `return "/Contents/Resources/Data";`

From debug log:
```
Could not find main assets file: /Users/test/Library/Application Support/Steam/steamapps/common/Descent Road to Legend/Descent Road to Legend.app/Contents/Resources/resources.assets

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

FFG D2E not found.
```

thanks for your work!

**Comment by NPBruce** [comment]
Missed this one when the fix went into MoM.  Sorry I have no way of testing macos, so it is pretty much blind guess work!  Will fix soon.

**Comment by NPBruce** [comment]
[valkyrie-macos-0.8.3b.zip](https://github.com/NPBruce/valkyrie/files/895611/valkyrie-macos-0.8.3b.zip)
Please test this.

**Comment by dchapde** [comment]
Worked and was able to load the First blood quest.  thanks!
