### ISSUE TITLE
Placement of hero tokens

### ISSUE THREAD

**Issue by DelphiDie** [NPBruce/valkyrie#183]
Would it be possible to allow the placement of hero tokens on the map via editor?

**Comment by NPBruce** [comment]
Yep.  As RtL doesn't control these i'm not sure I want Valkyrie to.  I could have it place the hero image like monster placement though.  Perhaps explain what you are trying to do and I will consider options (same for #182 )

**Comment by DelphiDie** [comment]
Hello Bruce, I´m currently considering to adapt travel events from the travel event cards. Some of these events have events, that let the heroes keep the travel card for a one time effect. Example:

The heroes choose a healer and place this card in his play area. He may discard this card when reviving a hero. The revived hero recovers all damage.

My plan was to, if this travel event came up, let the heroes select the name of a hero and call an event that places his hero token beside the map. They could click on the token as a remindet about what the effect was, and have to option to mark it as used.

**Comment by NPBruce** [comment]
Travel will be handled as part of the campaign work post 1.0
