### ISSUE TITLE
Usage of vars in Nextevents

### ISSUE THREAD

**Issue by DelphiDie** [NPBruce/valkyrie#184]
Would it be possible to enable the usage of vars in NextEvents? I´ll follow with an example:

Current mechanic:

[Event0]
text="Test"
trigger=EventStart
event1=Event1 Event2 Event3 Event4 Event5
button1="Confirm"
operations=RandomNumber,=,#rand5

[Event1]
conditions=RandomNumber,==,1

[Event2]
conditions=RandomNumber,==,2

[Event3]
conditions=RandomNumber,==,3

[Event4]
conditions=RandomNumber,==,4

[Event5]
conditions=RandomNumber,==,5

Idea:

[Event0]
text="Test"
trigger=EventStart
event1=Event{var:RandomNumber}
button1="Confirm"
operations=RandomNumber,=,#rand5

[Event1]

[Event2]

[Event3]

[Event4]

[Event5]

**Comment by NPBruce** [comment]
<pre>[Event0]
text="Test"
trigger=EventStart
event1=Event1 Event2 Event3 Event4 Event5
button1="Confirm"
randomevents=true</pre>

^- that is what you want.

**Comment by NPBruce** [comment]
Your example idea wouldn't do that anyway, and the top method you provide sounds like a good way to control that ie:

<pre>[Event0]
text="Test"
trigger=EventStart
event1=Event1 Event2 Event3 Event4 Event5
button1="Confirm"
operations=RandomNumber,=,#rand100

[Event1]
conditions=RandomNumber,<,5

[Event2]
conditions=RandomNumber,>=,5
conditions=RandomNumber,<,20
...</pre>

**Comment by DelphiDie** [comment]
[travelini.txt](https://github.com/NPBruce/valkyrie/files/900926/travelini.txt)

Perhaps this file explains my request better.

**Comment by NPBruce** [comment]
Still looks to my like random events is exactly what you want, check out the d2e perils and MoM mythos.

Having said that, I recommend holding off on too much campaign work.  I will be developing campaign support, but it will differ to the existing quest data.  More information to come.
