### ISSUE TITLE
New var type for text

### ISSUE THREAD

**Issue by DelphiDie** [NPBruce/valkyrie#185]
Would it be possible to create a new var type that can consist of text (for the usage in text)?

Example: 

operations=Textvar,=,"Test"
text="This is a {var:Textvar}."

**Comment by NPBruce** [comment]
I thought about this when I did vars.  The only purpose would be to display something different in events and you can just have multiple events instead.  I'm not sure that the added complication is worth it unless there is a lot of text that needs to end up in a lot of different places (do you have an example?)

**Comment by DelphiDie** [comment]
I´m currently creating travel events for the system, and there is a lot of text that needs to end up in a lot of places. It would be pretty handy to have this option.

**Comment by NPBruce** [comment]
One of the big problems is translations.  Currently working on merging a localisation system, so I'll have a think about how to give you something.

**Comment by NPBruce** [comment]
Please have a look at this:
https://github.com/NPBruce/valkyrie/wiki/Campaign-Support

**Comment by NPBruce** [comment]
At this stage I think this will be more of a detriment than a help.  Note that with the new tranlation system events will be able to use common text with text lookup (but they won't be vars that you can test - testing for strings is a big level of complication).
