### ISSUE TITLE
Are there vars to get certain hero names?

### ISSUE THREAD

**Issue by DelphiDie** [NPBruce/valkyrie#186]
Currently {rnd:hero} can be used to get a random hero name. Would it be possible to create vars for each hero?

Example: #hero1, #hero2, #hero3, #hero4

**Comment by NPBruce** [comment]
To specify a particular hero by name?  It wouldn't be a var perhaps just {heroname:1}, but that probably isn't so useful as where does 1 come from?  Then you could do heroname:var, but I'm still not sure how this is useful.

The way RtL does specific hero selection is asking the user to select them, then highlighting them later (see hero selection in event.

**Comment by DelphiDie** [comment]
I´d like to select the hero names by orderon the left side. Top left = {heroname:1}, next {heroname:2}, next {heroname:3}, next {heroname:4}.

**Comment by NPBruce** [comment]
I don't see any reason to rely of the order of heroes, however it may be useful to save a random hero and then use that hero subsequently (like hero selection).  The obvious solution is that when you use rnd:hero the selected hero is highlighted and than even can then be used, perhaps with something like {event:hero}.

**Comment by NPBruce** [comment]
rnd:hero now highlights that hero and can be used in other events using the hero selection highlight.  Actual hero name still coming.

**Comment by NPBruce** [comment]
{c:\<event\>} can now be used to get a hero name from another event (either selected manually or with rnd:hero).
