### ISSUE TITLE
Monster Attacks

### ISSUE THREAD

**Issue by Ashgur** [NPBruce/valkyrie#192]
The app does now work on my mac! Fantastic!
You did a really good job so far! I'm impressed! Well done!

I did already try some things with "The fall of house Lynch" and the example szenario.
And (at least on my mac) there is an issue with the monster attacks:

If a monster appears somewhere (like the maniac in the second mythos phase of the lynch-szenario) the app is asking me if the monster is able to reach an investigator to attack him. So far so good.
But now i am unable to click on the "No investigator in range"-button. If i do so nothing happens.
If im going to choose the "Monster attacks" - button the next text appears to tell me which attack that is. But now im also unable to click on the "Finished" - button. What means i am now stuck and cant go on until i restart the app.
This does also happen with the cultists in the example szenario.

**Comment by NPBruce** [comment]
I can reproduce this, a bad bug!
