### ISSUE TITLE
Translate Valkyrie to nonEnglish nonSpanish languages

### ISSUE THREAD

**Issue by eorahil** [NPBruce/valkyrie#195]
Valkyrie APP now supports multilanguage. We need foreign colaborators to translate de App to:
* French (PARTIAL)
* German (PARTIAL)
* Italian (PARTIAL)
* Portuguese
* Polish
* Japanese 
* Chinese

The localization file is here: [link](https://github.com/NPBruce/valkyrie/blob/development/unity/Assets/Resources/Text/Localization.txt)
For acutes, east-asia characters or other special characters it is recommended to view the localization file with the MAD font, in order to be compatible with Valkyrie. [font](https://github.com/NPBruce/valkyrie/blob/development/Assets/Resources/Fonts/MADGaramondPro.ttf)

Instructions are easy. Edit the Localization file, translate each line in the language position. What is the language position? Look at the first line of the file and look what position corresponds to your language. IE: German translation should be bethween fourth and fifth comma. If the translated text includes commas wrap all message between double quotes ("). Some texts contains a {0} text. This is a replacement key for a variable word. The translation should have the {0} where corresponding.

Any doubt ask here. If you begin the translation comment here in order to not do it twice.

**Comment by redwolf2** [comment]
I created a pull request for the german translation

**Comment by Landar77** [comment]
I for italian translation.

**Comment by NPBruce** [comment]
Where are the updates?

**Comment by Landar77** [comment]
Sorry, I'm newbie.

I edited Localization.txt with italian traslated and after I sent the"Propose file change".

Did I do something wrong?




________________________________
Da: NPBruce <notifications@github.com>
Inviato: domenica 9 aprile 2017 23.14
A: NPBruce/valkyrie
Cc: Landar77; Comment
Oggetto: Re: [NPBruce/valkyrie] Translate Valkyrie to nonEnglish nonSpanish languages (#195)


Where are the updates?

**Comment by NPBruce** [comment]
It looks like you've forked the repo and created two branches (patch-1 and patch-2).  I think patch-1 is the correct one?

I have raised a 'pull request' here to move this into the main repo:

#223

Please check if this is correct.

I noticed a comment regarding testing, you need to build this in, if you like I can upload a dev build here after the pull request (you can always do more pull requests to fix mistakes).

**Comment by NPBruce** [comment]
Also note that you can just attach the file directly to this issue if that is easier.

**Comment by Landar77** [comment]
Correct!  This Github is a new world for me. XD
I begin to understand.

**Comment by NPBruce** [comment]
Italian added in 0.8.7.

**Comment by NPBruce** [comment]
Italian added in 0.8.7.

**Comment by eorahil** [comment]
Sorry. Did you enable in the options screen the language selection buttons? I disabled all but English and Spanish

**Comment by NPBruce** [comment]
Yep.

**Comment by s3nt3nz4** [comment]
I've just started the French translation.

**Comment by NPBruce** [comment]
Thanks, Added.

**Comment by s3nt3nz4** [comment]
Happy to give a little help on this great project 👍

**Comment by eorahil** [comment]
Added new localization elements: 
CONFIRM
FAIL
NONE
PASS

and all elements in Localization.txt file between 
//Items
and 
//Inherited from FFG localization files

Please complete your translations.

**Comment by NPBruce** [comment]
I have just removed CONFIRM, FAIL and PASS, they are not needed (only for legacy support and didn't work anyway).

**Comment by eorahil** [comment]
not only the NONE key must be translated. There are many traits to translate between the line //Items and the line //Inherited from FFG ...

**Comment by eorahil** [comment]
and EVENT_DOOR_DEFAULT_TEXT
sorry. I forgot... T_T

**Comment by redwolf2** [comment]
No prob. Already found it 😄

**Comment by s3nt3nz4** [comment]
French added. Pull request #279. Ignore #278.

**Comment by redwolf2** [comment]
There are some entries that in the Localization.txt, that appear multiple times like:
small, medium

**Comment by redwolf2** [comment]
I translated the example quest and The Fall Of House Lynch to german.

**Comment by redwolf2** [comment]
The buttons of default mythos events don't seem to be translated like: "Resolve Event", "No Effect" and "Continue".

**Comment by NPBruce** [comment]
This has been fixed, but not in a published version.

**Comment by redwolf2** [comment]
It is fixed in release 1.1.0a.

**Comment by NPBruce** [comment]
Should be fixed in 1.0.0 also.

**Comment by eorahil** [comment]
New translations required:
- QITEM (Quest Item or Special Item)
- KO
- SKILLS
- ITEMS
- GOLD
- NONE
- AUTOSAVE
- SELECT_SAVE
- SELECT_CLASS
- HIDDEN
- ACTIVE
- SELECT_SKILLS
- STARTING_ITEM
- UI
- UNITS
- HORIZONTAL
- VERTICAL
- ALIGN
- POSITION
- SIZE

**Comment by NPBruce** [comment]
This is still being worked on and changed, so don't get to eager.

**Comment by redwolf2** [comment]
@eorahil There are new entries in the development branch, that need more spanish ;)

**Comment by Sanscouer** [comment]
Hi Guys, I send the localization text for Portugues

**Comment by redwolf2** [comment]
If anyone is interested, heres is a good example of how to fork, change files and do a pull request. https://www.youtube.com/watch?v=_NrSWLQsDL4
It works for basic stuff without any tools. However, NPBruce is using https://www.sourcetreeapp.com/ to sync his lokal files with github. I use https://tortoisegit.org/ as it comes with windows explorer integration.

**Comment by Sanscouer** [comment]
Thanks @redwolf2 , gonna see this tutorial.

**Comment by redwolf2** [comment]
Here is a simple explaination:
1. Goto https://github.com/NPBruce/valkyrie press the "Fork" Button. Click on your user icon and goto "Your Profile". Click on your own "valkyrie" repository.
1. Navigate to: `https://github.com/<your username here>/valkyrie/blob/master/unity/Assets/Resources/Text/Localization.txt`
1. Change the file.
1. After that go from "Code" to "Pull Request" and create one there.

**Comment by NPBruce** [comment]
There is now a new file that needs translations:

https://github.com/NPBruce/valkyrie/blob/development/content/MoM/base/Localization.English.txt

This is because content packs can now have their own dictionaries.

**Comment by chmod555** [comment]
Hi. Im gonna handle Polish translation.

**Comment by NPBruce** [comment]
This system has changed a fair bit for 1.4, hopefully much easier now.

I have created new documentation here:

https://github.com/NPBruce/valkyrie/wiki/Translations
