### ISSUE TITLE
Interact with tokens

### ISSUE THREAD

**Issue by Ashgur** [NPBruce/valkyrie#196]
Im sorry if the following might be a dumb question:

How do i make the player able to interact with the tokens that i place on the board.
For example if i create a search token. I know how to spawn it and how i implement the "initial description". That works well. But now afterwards there wont happen anything when the player clicks on the token. What am i doing wrong?

**Comment by EtiCarasoft** [comment]
In placing the token you have to select event (evento in this case). 
![captura de pantalla 2017-04-06 a les 16 04 55](https://cloud.githubusercontent.com/assets/26690018/24759020/6b7fa384-1ae4-11e7-9c96-58e96192f9be.png)
Add the Dialog you want to see before performing the action. 
![captura de pantalla 2017-04-06 a les 16 05 53](https://cloud.githubusercontent.com/assets/26690018/24759030/705c6766-1ae4-11e7-876b-b2fbf552cbcc.png)
If it's and important search that maybe triggers something you can go to vars and an assignation to the var that maybe modifies some triggers like mythos.
![captura de pantalla 2017-04-06 a les 16 07 33](https://cloud.githubusercontent.com/assets/26690018/24759041/78c924ac-1ae4-11e7-9bbf-b6a2f98ab51a.png)
Next go to NextEvent (in this case Siguientes). Click on the green + to add a button. 
Change the button text.
![captura de pantalla 2017-04-06 a les 16 09 24](https://cloud.githubusercontent.com/assets/26690018/24759053/85f828a8-1ae4-11e7-8553-cc89cbdd94bb.png)
You will need another event as resolution. 
![captura de pantalla 2017-04-06 a les 16 14 53](https://cloud.githubusercontent.com/assets/26690018/24759071/96def6ec-1ae4-11e7-95d2-f98c8fce3351.png)
You call the event resolution by clicking tue button just added.
![captura de pantalla 2017-04-06 a les 16 18 23](https://cloud.githubusercontent.com/assets/26690018/24759111/af8135b6-1ae4-11e7-9050-81cb51ece184.png)

**Comment by Ashgur** [comment]
Thank you really much! Now i got how it works =)
