### ISSUE TITLE
characters

### ISSUE THREAD

**Issue by Ashgur** [NPBruce/valkyrie#197]
In case i missed it: Is there already a way to implement character tokens (people, that the players can interact with)?

**Comment by NPBruce** [comment]
Just have to add the assets to the token list.  Will do.

**Comment by Ashgur** [comment]
Nice! ;-)

**Comment by NPBruce** [comment]
I need help!  I am adding all the symbols, but I don't know who they all are.

The imported image is ffg/img/SpriteAtlasTexture-ATLAS_FEATURES_CORE (Group 0)-1024x1024-fmt12.dds if anyone can identify any of them please post here.

**Comment by NPBruce** [comment]
Generic tokens split to #213 for tracking purposes.

**Comment by Ashgur** [comment]
Do you still need help here?

**Comment by NPBruce** [comment]
Yes please, identify anyone you can from here:
![spriteatlastexture-atlas_features_core group 0 -1024x1024-fmt12](https://cloud.githubusercontent.com/assets/21050071/24849649/2e1ee142-1e10-11e7-986e-31226e0cb2cd.png)

**Comment by Ashgur** [comment]
Okay ;-)

So: Only these with a "real" picture also have a specified name. The rest of them just appears as "an old man", "a young woman", etc. So i just leave them out. Also some of the characters are from
the "Beyond the Threshold" - expansion, that i don not have. So i will just write "unknown" for everyone of these.
So here are all the names from the "unique" characters that i know:

1. line: Richard Bechman, Mildred Bechman, unknown, Agent Craven
2. line: Howard Bechman, unknown, Grace Bechman, Eugene Clemens, Joyce Little
3. line: Sylvia Marsh, unknown, Zebulon Whateley
4. line: unknown, , unknown, Bobby Foster, unknown, unknown
5. line: Victor Blake
6. line: Zadoc Allen
7. line: Othera Gilman, Edna Hughes

Players, that do own the "Supressed Memories, - expansion also have 3 other characters at home, that didnt find any use in the past scenarios: Ammi Pierce, Corinna Jones and Eric Colt.
They have the same pictures as you can find here:
https://www.fantasyflightgames.com/en/ffg_blog/22128/original_content

**Comment by NPBruce** [comment]
Great work!

**Comment by NPBruce** [comment]
Split BiT into #226, otherwise done.
