### ISSUE TITLE
Some Bugs on MoM2

### ISSUE THREAD

**Issue by EtiCarasoft** [NPBruce/valkyrie#198]
Hi, testing 0.8.5. on MAC i found some things: 
- It can find my previous scenarius and can edit them, but can't play it.
- In starting scenario, once I downloaded the example scenario I can't download the fall of the house Lych.
- When starting an scenario when selecting investigators if you unselect one investigator previlously on your team it remains in grey, you can select it again, but doesn't comes back to white.

**Comment by EtiCarasoft** [comment]
- Find something more of the first error. If the scenario needs some tiles from an expansion it doesn't let you play it if you previously added the expansion in needed matherial. If you use some tiles from an expansion and you don't add it as required it let's you launch it, but it makes the aplication crash.

**Comment by EtiCarasoft** [comment]
- Fix somethings by collection manager. If the collection name is in white and highlighted it means you own it, this is quite confusing because it work the other way round with the investigators selection. Now I can play all the scenarios previously created, but still can't download the House Lych.

**Comment by NPBruce** [comment]
> It can find my previous scenarius and can edit them, but can't play it.

Can you please tell me what happens?  Are they in the list?  Are they grey?  What happens when you select them?

> In starting scenario, once I downloaded the example scenario I can't download the fall of the house Lych.

What color is it?  What happens when you select it?

> When starting an scenario when selecting investigators if you unselect one investigator previlously on your team it remains in grey, you can select it again, but doesn't comes back to white.

Split as #203

> Find something more of the first error. If the scenario needs some tiles from an expansion it doesn't let you play it if you previously added the expansion in needed matherial. If you use some tiles from an expansion and you don't add it as required it let's you launch it, but it makes the aplication crash.

Letting you play is intentional, the scenario might have different tiles to use depending on what is available, so this is a scenario bug.  Having said that, could handle it better (#204)

> Fix somethings by collection manager. If the collection name is in white and highlighted it means you own it, this is quite confusing because it work the other way round with the investigators selection. Now I can play all the scenarios previously created, but still can't download the House Lych.

#205

> When trying to add a test for an event trigger, in the first spot where the example scenario calls Valkyrie Vars like #monsters it doesn't let you click it or even write it.

Yes, currently you need to remove and add a new one. #206

**Comment by EtiCarasoft** [comment]
> In starting scenario, once I downloaded the example scenario I can't download the fall of the house Lych.

> What  color is it? What happens when you select it?

it reamains almost invisible.

![captura de pantalla 2017-04-07 a les 10 08 00](https://cloud.githubusercontent.com/assets/26690018/24791429/575ea120-1b7a-11e7-8d05-d43f460ed09f.png)
Click on download ->
![captura de pantalla 2017-04-07 a les 10 08 13](https://cloud.githubusercontent.com/assets/26690018/24791431/5a2df9e6-1b7a-11e7-91cc-2889091e2ebc.png)

_The scenario copy it's because i made a copy in the editor to learn about monsters and vars._

**Comment by NPBruce** [comment]
They go grey like that when downloaded.  What is odd is that you can't play them.  My guess is the package isn't extracting to a temp directory properly... but example scenario is there.  Can you copy Fall of House Lynch in the editor?  Can you please attach a log?  Can you provide a file list of your quest location?

**Comment by EtiCarasoft** [comment]
Found the scenario in the folder delete it and download it again, now it works all perfect. Thx.

**Comment by NPBruce** [comment]
OK added #212 to make this easier.
