### ISSUE TITLE
Implementing a way to block certain monster choices by trait based spawning

### ISSUE THREAD

**Issue by DelphiDie** [NPBruce/valkyrie#201]
I´m currently facing the problem, that reinforcing an open group with certain traits sometimes causes a monster group to spawn that is a) either already on the map or b) might be planned for later reinforcements. Would it be possible to create a way to exclude certain monsters from being spawned.

Example:
traits:wilderness
exclude:MonsterMerriod

**Comment by NPBruce** [comment]
Is this the same as #162 and #163?  Can you please check if that does what you want.  Please check 'monster' 'trait' and 'traitpool' here:
https://github.com/NPBruce/valkyrie/wiki/QuestIniSpawn

**Comment by DelphiDie** [comment]
Sorry, I seem to have missed the last sentence for monster. That is exactly what I was looking for.
