### ISSUE TITLE
Removing monster groups from the tracker by event

### ISSUE THREAD

**Issue by DelphiDie** [NPBruce/valkyrie#202]
It would be useful to have a way to clear the monster tracker in case you design a quest with multiple encounters that requires you to remove the maptiles and tokens to setup a new map. Currently the monster have to be manually defeated after setting up the new map, which might lead to problems with new monster spawns. It would be ideal to have a way to clear all monsters since trait based spawns can´t be anticipated.

**Comment by NPBruce** [comment]
I am adding ```#monsters``` ```#boardcomponents``` and ```Spawn<name>``` as options to remove in events.  board components will remove all tiles/tokens/doors.  monsters will remove all monsters (will NOT trigger defeated).  Spawn will remove monsters of the same type of the spawn (which may or may not have been created by that spawn).

Is this acceptable?

**Comment by DelphiDie** [comment]
This sounds great.
