### ISSUE TITLE
Can't change var in operation or test

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#206]
The first var can't be edited, need to remove and readd.

**Comment by EtiCarasoft** [comment]
The main problem is that when trying to add a new var in the first square, this one can't be a Valkyrie one, like #round or #monsters at least in MAC.

**Comment by NPBruce** [comment]
That is intentional.  # vars need to be the second element and can't be changed by scenarios.

**Comment by NPBruce** [comment]
Actually now I realise that they can't be used in tests either (ie: #round == 2), that is a bug.
