### ISSUE TITLE
Add another MoM Scenario

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#207]
Would be nice for a 1.0 release.

**Comment by EtiCarasoft** [comment]
I'm working on a selfmade one, but i'm still learning some steps. But i'll try i message you if done at time.

**Comment by NPBruce** [comment]
More is better!  It would be good to have one playable without any expansions.

**Comment by EtiCarasoft** [comment]
perfect I'm working on it.

**Comment by NPBruce** [comment]
Done!

**Comment by eorahil** [comment]
I'm translating this new scenario to Spanish. 
I will translate The House Lynch too but I must travel to my hometown to get the MoM1E and get the original translation (this weekend). I supose you add your own texts but there should be a lot of original ones.

**Comment by NPBruce** [comment]
Great! Yes tfohl is 98% original text.

**Comment by eorahil** [comment]
Translation to Spanish of Exotic Material

[Localization.txt](https://github.com/NPBruce/valkyrie/files/956701/Localization.txt)


PD: What are the Hidden Buttons? I can't see it in the scenario

**Comment by NPBruce** [comment]
They are Buttons that are never displayed. That text is only used in the editor as a heading for an event list.

**Comment by NPBruce** [comment]
One more that I missed please:
\<i\>The group bursts into life.\</i\>\n\nInvestigators must now perform evade and horror checks as normal for this monster.  Use the monster panel to attack.

**Comment by eorahil** [comment]
<i>El grupo recupera la vitalidad.</i>\n\nA partir de ahora este monstruo requiere pruebas de evasión y de horror.  Utiliza el panel de monstruos para atacar.
