### ISSUE TITLE
Interact with items

### ISSUE THREAD

**Issue by Ashgur** [NPBruce/valkyrie#209]
Another thing that would really open things up for a lot of creativity would be the possibility to give the player items, that he can interact with like it is possible in the original app (for example in almost every szenario with the "Old journal" - evidence card where you are able to read the book if you spend an action).

But im not sure how hard it would be to implement that into valkyrie. Just something i had in mind while playing around with the app...

**Comment by NPBruce** [comment]
Yep, nice to have but this is post 1.0.

**Comment by Ashgur** [comment]
Alright ;-)

**Comment by LordPyrex** [comment]
This could be temporarily handled by spawning an interact token outside the play space, then if you have multiple interactions within the journal just have it spawn them in order as new events. It's at least a thought for now if you're looking to write those kind of scenarios.

**Comment by NPBruce** [comment]
FYI that is how Descent: Road to Legend does it.
