### ISSUE TITLE
Where does the scenario go?

### ISSUE THREAD

**Issue by EtiCarasoft** [NPBruce/valkyrie#210]
Simple question, don't know if it can be answered, Where do the scenarios get saved? Does it generate any file? Some thing that can be transfered between users?

**Comment by eorahil** [comment]
windows: %appData%/Valkyrie  (%appData% = DRIVE:\Users\[yourUser]\AppData\Roaming)
MAC: 
/Users/[username]/.config/Valkyrie
/Users/[username]/Library/Application Support/NA/Valkyrie

**Comment by Ashgur** [comment]
Cant find that one on my mac =/ There is no "NA" - folder in my "application support".
Mac OSX 10.11.

**Comment by eorahil** [comment]
Try these folders. Application name is Valkyrie :
/Library/Preferences/<application name>/
~/Library/Preferences/<application name>/
/Library/Application Support/<application name>/
~/Library/Application Support/<application name>/
/Library/<application name>/
~/Library/<application name/

**Comment by Ashgur** [comment]
None of them does exist. If i use the "search" - function for the whole mac looking for the word "Valkyrie" the app is the only thing that can be found.

**Comment by Ashgur** [comment]
Btw.: My "library" - folder is not located in the "users" - folder but "parallel" to it.
Like 
Macintosh HD/Users
Macintosh HD/Library.

**Comment by EtiCarasoft** [comment]
>None of them does exist. If i use the "search" - function for the whole mac looking for the word "Valkyrie" the app is the only thing that can be found.
Same for me

**Comment by eorahil** [comment]
Do you have access to the ~/Library/Logs/Unity/Player.log ? 
This is the log for the unity player. The App writes info on it while it's being executed.
If you have access to the file try this:
* Open valkyrie and Go to Edit Scenario. Select an edited game and after load don't do anymore.
* View the Player.log file and search in the last lines of the file if there is a text like this
**Loading quest from: "C:\Users\david.castro\AppData\Roaming/Valkyrie\Download\TheFallofHouseLynch/quest.ini"**
this should be the path of the saved scenarios and saved games

**Comment by NPBruce** [comment]
According to unity docs it should be /Users/yourname/.config/Valkyrie

**Comment by Ashgur** [comment]
Found it! Thanks. Yes, it was hidden ;-)

**Comment by EtiCarasoft** [comment]
Found it hidden ;)

**Comment by Ashgur** [comment]
So we should be able to "trade" szenarios now, right? wanna give it a try?

**Comment by EtiCarasoft** [comment]
Find the download folder but not my scenarios yet.

**Comment by NPBruce** [comment]
Note: if you rename the .zip to .valkyrie you can just place it in  /Users/yourname/.config/Valkyrie
