### ISSUE TITLE
Monster spawning issue

### ISSUE THREAD

**Issue by Ashgur** [NPBruce/valkyrie#211]
There is an issue with the spawning of some monster types (at least on my mac). Some of them are working perfect. I tried to use cultists and maniacs for example and all worked really fine!

But there are also some monster types that doesnt work so well. For example if i try to spawn a cult leader something really odd happens:
The player cant see the text of the spawn-event of the cult leader. But he still seems to be there because instantly after the spawn message should have popped up the app tells the player that the cult leader is attacking him. After you managed the attack the next odd things are happening:

1. the player cant interact with the cult leader (attacking, evading, dealing damage) because his picture is not going to show up on the right side.

2. i did spawn a maniac in the mythos phase one round later. Everything did work well with that before i was trying to spawn the cult leader. but now his spawn-text is also not going to show and the same problem (no interaction possible) appears here.

Same thing is happening with the Priest of Dagon instead of the cult leader. Didnt try many other monsters yet.

**Comment by eorahil** [comment]
These both are unique monsters (Leader and Priest), the bug can be there...

**Comment by NPBruce** [comment]
I will look into this when I can a chance.  Can you please provide a save game from before the issue?

**Comment by NPBruce** [comment]
All monsters with more than 1 word in their name had the wrong image address and would break.  Fixed.
