### ISSUE TITLE
Would it be possible to add some missing tokens and tiles to Valkyrie which are not included in RtL?

### ISSUE THREAD

**Issue by DelphiDie** [NPBruce/valkyrie#214]
Currently the following tiles are missing: S1A, S1B, S2A. Also the secret room entrance token is not included. Would it be possible to add these via scans?

**Comment by NPBruce** [comment]
The rooms should be there.  Yes I can add the token (please provide image).

**Comment by NPBruce** [comment]
Worth noting that my image for S2A isn't good.

**Comment by DelphiDie** [comment]
I scanned the tiles. What would be the prefered way for you to get them? The files are quite large.

**Comment by NPBruce** [comment]
The only tile that needs an upgrade is S2A.  Please provide as a 72dpi png, should be quite small (don't want to distribute high quality scans).  Same for the token (72dpi).  Ideally please have missing parts transparent, no space beyond the token or tile.  Can just drop the files here (or if you want to learn git/github you can do a pull request).

**Comment by DelphiDie** [comment]
Perhaps it´s easier for you to downscale the files to the correct size. I´ll send you a PM via geekmail with a DL Link. Note that S1A and S1B don´t show an image in the editor. They are not included in the RtL source files, just like S2A.

**Comment by NPBruce** [comment]
S1A/S2B is a bug! the images are here:
https://github.com/NPBruce/valkyrie/tree/master/content/D2E/boxed/lotw/img

**Comment by NPBruce** [comment]
Created #215

**Comment by NPBruce** [comment]
I have added the tokens.  Note that while I cleaned up the scans a bit they still don't look great.
