### ISSUE TITLE
Accounting for items during the game

### ISSUE THREAD

**Issue by Hobbeslionheart** [NPBruce/valkyrie#216]
Played through House of Lynch last night. Overall we enjoyed it, but encountered a few bugs. The issues to follow came from the game play. 

We were assigned an axe at the beginning then one of the items given from the search token was an axe. Starting items need to draw from items that can not possibly be given in the game or if random, then an item count needs to be done when the search token gives an item.

**Comment by NPBruce** [comment]
That shouldn't have happened, will investigate

**Comment by NPBruce** [comment]
Thanks for your reporting, will fix all of these up.  Hopefully the 1.0 release will be more reliable!

**Comment by NPBruce** [comment]
Fixed in scenario update.
