### ISSUE TITLE
"Mandatory" Mythos events don't need no effect option

### ISSUE THREAD

**Issue by Hobbeslionheart** [NPBruce/valkyrie#219]
Mythos events that will occur because it is not location dependent shouldn't have the no effect option. Example below. This threw us for a loop one time which necessitated us to check the log which we discovered we couldn't.

![image](https://cloud.githubusercontent.com/assets/26637617/24829090/786d9816-1c39-11e7-8963-03200bb74202.png)

**Comment by NPBruce** [comment]
Hopefully all sorted now.
