### ISSUE TITLE
Mansions of Madness Tiles Missing After Import

### ISSUE THREAD

**Issue by dlgreenwald** [NPBruce/valkyrie#22]
I noticed this when I attempted to add the mansions of madness tiles a week or so ago. I never got it finished so I never made a pull request.

Anyway, not all the .asset files are referenced in resources.assets.  In order to get the terrain tiles for MoM you'll have to import all files that match *.asset.

**Comment by NPBruce** [comment]
I am actually already matching *.asset.  At first I only added the base game tiles because I didn't have expansion support, so the 1st ed tiles wouldn't have shown up.
