### ISSUE TITLE
Zombie movement and actions confusing

### ISSUE THREAD

**Issue by Hobbeslionheart** [NPBruce/valkyrie#220]
![image](https://cloud.githubusercontent.com/assets/26637617/24829143/7c10b678-1c3a-11e7-93d7-64d27961131c.png)

The instructions are confusing. It is possible to move one space to an investigator in range and yet not attack, but there's no choice covering this possibility. If the intent is to get the zombie to move twice if it can "see" an investigator but cannot attack, then the second option should be no investigator in the space. Although this then becomes the problem that the first action could not be taken if there are no investigators in space which mean that zombie would move one space. The solution would be that zombies move to the closest investigator and if there are no investigator in the space, it move one space closer.

I could see this being an issue among other monsters that do not have ranged attacks.

**Comment by eorahil** [comment]
In these cases original FFG app has the third option. Can't attack.

**Comment by NPBruce** [comment]
Pretty sure the FFG button in this case says "No investigators in the space." I will fix the activations.

**Comment by NPBruce** [comment]
Fixed Zombies, Shoggoth and Crawling Ones.

**Comment by eorahil** [comment]
Ghosts are the same case

**Comment by NPBruce** [comment]
Ghosts should be already correct.
