### ISSUE TITLE
Is there a way to reset the round in Descent?

### ISSUE THREAD

**Issue by DelphiDie** [NPBruce/valkyrie#222]
A command to reset the round (mark all heroes as not activated) would be very handy, especially when designing multi encounter quests. 

In this way the heroes can start encounter 2 as a new round instead of being in the activation state they were when ending encounter 1.

**Comment by NPBruce** [comment]
My current thinking is that this is perhaps best as two quests, with an automatic progression to the next quest.  With the campaign system you will be able to carry over important vars and we could mark encounter 2 so that it doesn't show up in quest selection.  Thoughts?

**Comment by DelphiDie** [comment]
This sounds like a good solution.
