### ISSUE TITLE
When editing an scenario, its loaded twice

### ISSUE THREAD

**Issue by eorahil** [NPBruce/valkyrie#224]
Don't know if it's a need but it took my attention.
After donwloading the house lynch scenario, going to scenario edit and selecting it, The LOG shows 
**Loading quest from: "C:\Users\David\AppData\Roaming/Valkyrie\Download\TheFallofHouseLynch/quest.ini"** twice.
Im working on loading at this poing the quest localization file and its called twice. is it correct or its a bug?

**Comment by BenRQ** [comment]
@redwolf2 should be fixed in next Brynhildr version
