### ISSUE TITLE
Crashes when copying scenarios

### ISSUE THREAD

**Issue by Hobbeslionheart** [NPBruce/valkyrie#225]
I tried copying the House of Lynch scenario as you stated we could. It crashed within seconds of clicking the button. Other scenarios and quests even in D2E have the same issue as well.

**Comment by Hobbeslionheart** [comment]
Creating a new scenarios/quests also crashes. Editing existing scenarios open fine though.

**Comment by NPBruce** [comment]
Please attach log.

**Comment by Hobbeslionheart** [comment]
[output_log.txt](https://github.com/NPBruce/valkyrie/files/908643/output_log.txt)

**Comment by NPBruce** [comment]
Fixed.
