### ISSUE TITLE
MAD23 BtT character tokens

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#226]
Who are these people?

![tokens](https://cloud.githubusercontent.com/assets/21050071/24853865/cef153a2-1e1f-11e7-8917-c99db8c2a7e4.png)

If I know I can add them.  Also there are 7, so I am guessing 4 double sided tokens and one is missing, so who is missing?

**Comment by Ashgur** [comment]
No, they are not doublesided. on the backside of them is just the written name.

**Comment by NPBruce** [comment]
Ah.  Clearly I should have just looked at the others!

**Comment by jnierodzik** [comment]
![btt](https://cloud.githubusercontent.com/assets/1038621/24883851/5ff141e6-1e0c-11e7-93a8-9a6d74a9d8b6.jpg)

**Comment by NPBruce** [comment]
Great, thaks.

**Comment by jnierodzik** [comment]
your welcome

**Comment by eorahil** [comment]
A few days ago the House Lynch scenario changed its icons and where there was the red exploration tokens now there are the blue admiration ones. I downloaded again the scenario but nothing fixed. These new characters tokens should have shifted the other icons in the same image?
![2017-04-11](https://cloud.githubusercontent.com/assets/15666794/24884911/0ad55766-1e4c-11e7-906e-e02a39dbfb7b.png)

**Comment by NPBruce** [comment]
Raised as #232
