### ISSUE TITLE
"Random" Mythos Events

### ISSUE THREAD

**Issue by Ashgur** [NPBruce/valkyrie#227]
Just a quick question:

I didnt get yet how i can create a "random" mythos event, that is going to trigger each round, based on the characters that are ingame. What do i have to do?

**Comment by NPBruce** [comment]
I don't fully understand the question, so I'm going to give some examples:

To have a mythos event each round that has flavour but does nothing:

set mythosFlavor = 1

To have a mythos event that is minor or significant each round and may be specific to outdoor settings:

set mythosMinor = 1
set mythosMajor = 1
set mythosOutdoor = 1

To create your own mythos event:

Set all mythosMinor etc to 0, create an event that triggers on Mythos.

To create a number your own mythos events and pick one at random:

Set all mythosMinor etc to 0, create an event that triggers on Mythos.  Have all of the mythos events in the next event list and set event order to 'random'.

Full mythos var list is here:
https://github.com/NPBruce/valkyrie/wiki/ValkyrieVars

Does that answer your question?

**Comment by Ashgur** [comment]
Yes, it does! Thank you very much!
