### ISSUE TITLE
Questions about texts with multiple lines

### ISSUE THREAD

**Issue by eorahil** [NPBruce/valkyrie#231]
In the fall of the house lynch I see many multiline texts, but in the editor the new line ones are not shown. And inside textfield, the new lines becomes \r instead of \n.
Is this intentional? shouldn't be better a textbox with line feeds.
After, in the scenario play, it becomes multiline, but not in editor.

**Comment by NPBruce** [comment]
It is a bit of a mess.  The editor has two modes, display and editor (two different strings are used).  \r sounds like a bug (if in editor mode and an actual newline is inserted?  Probably also platform specific?

Ideally:
All text and data strored with \n.

Display in editor translates newlines, {symbols} and {var:} (will be 0)

Edit mode in editor translates newlines, nothing else.  In this case how do we add new lines?  Could still type \n.

**Comment by eorahil** [comment]
My intention was to create an textbox editor with small buttons upside right including Enter and all the special characters in game. so you dont have to know the {codes}, just clicking button will insert these special characters. But translations are taking me too long. T_T

**Comment by NPBruce** [comment]
I wouldn't lose sleep over the edit box at this point, I think for now most text editing will be done directly in the text file.  I have split the \r issue and will close this as there isn't an additional problem.
