### ISSUE TITLE
Bug in combination lock puzzle

### ISSUE THREAD

**Issue by Hobbeslionheart** [NPBruce/valkyrie#236]
In House of Lynch, numbers are not consistently displayed the right result. Second line in the first picture should have at least two magnifying glasses. Second picture: 4 3 2 don't agree with the results above which show that there should be at least three magnifying glasses

![bug 2](https://cloud.githubusercontent.com/assets/26637617/24887578/af9ed604-1e2a-11e7-8150-824cdc08f179.png)

![bug](https://cloud.githubusercontent.com/assets/26637617/24887580/b27f2900-1e2a-11e7-90c1-8b3282c016c3.png)

**Comment by Hobbeslionheart** [comment]
The right answer was 224. No obvious pattern can be detected from what I can see.

**Comment by NPBruce** [comment]
It is sometimes adding one extra clue symbol. I will investigate.

**Comment by NPBruce** [comment]
The 2 in the guess was matching both 2s in the pattern.  Fix in the works.
