### ISSUE TITLE
Button Mapping could be improved for full screen

### ISSUE THREAD

**Issue by Hobbeslionheart** [NPBruce/valkyrie#237]
While in full screen and playing, clicking on top half of the log, menu, set, and arrow buttons yields no results, it's the middle and bottom half that will work. To improve user friendliness, I suggest seeing if it is possible to expand the space of the click area.

Windowed appeared to work as normal.

**Comment by NPBruce** [comment]
Very odd, might be a unity bug?  I will have a look.

**Comment by NPBruce** [comment]
I can't reproduce this, could you be running some software that might be interfering with the mouse input?

**Comment by Hobbeslionheart** [comment]
Could be, but doubt it. Maybe it's resolution specific? 1360 x 768. 

I would hold off on this for now and see if more people report this.

**Comment by Hobbeslionheart** [comment]
Perhaps the problem is that the maximum resolution of Valkryie and the official app is 1360 x 768 and it's stretched to a 1600 x 900 display when in full screen. When windowed, it is smaller than my monitor.

**Comment by NPBruce** [comment]
That isn't the maximum resolution.  Unity probably doesn't support 1600x900, which by the way is a very unusual resolution.  Both Valkyrie and the official app should go all the way to 4K if the specific resolution is supported.

In your graphics settings you should be able to change non native resolution scaling to add letterboxing, can you try that and see if it helps?  Example:

![scaling](https://cloud.githubusercontent.com/assets/21050071/24937115/d889a646-1f71-11e7-9800-c3b1ba521334.png)

**Comment by Hobbeslionheart** [comment]
I scaled down my resolution to 1360 x 798 and it worked fine. I tried to find the letterbox option on my AMD Radeon software and it's not as clear as the option above. I think I could either play in windowed mode or downscale if needed. 

I'm closing this issue.
