### ISSUE TITLE
Rearrange library and unity builds to allow different git ignore rules

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#238]
git ignore for VS and unity are very incompatible, move unity project into subdir and have separate rules.

**Comment by eorahil** [comment]
merging development branch doesn't build. I think there is no dll files where it should be... there are the meta files but not the dlls itself.
https://github.com/NPBruce/valkyrie/tree/development/unity/Assets/Plugins

**Comment by NPBruce** [comment]
Fixed.  Should be able to build these anyway, but then we depend on Visual Studio, so I am OK with committing them.
