### ISSUE TITLE
Limited space on buttons

### ISSUE THREAD

**Issue by Ashgur** [NPBruce/valkyrie#241]
I just tried to create a button (for an event) with three words on it. But this seems to be to much because the app is going to show only the first two words to the players. Is there any way to increase that?

**Comment by NPBruce** [comment]
Buttons are bigger if you have more than 1.  Otherwise I can add a feature to automatically resize if they don't fit (within reason).

**Comment by Ashgur** [comment]
Thank you, that would be really nice. Im trying to add some nice dialogues with characters right now and i could really use bigger buttons for that =)
