### ISSUE TITLE
Testing for 0.9.0

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#244]
If anyone wants to help test, I will upload builds here. Note that quests saved in this build won't work on 0.8.7.

Release Notes:
Major Changes:
* Now supports quest localization (Update to [quest format 3](https://github.com/NPBruce/valkyrie/wiki/QuestFormat))
* Now supports Linux
* MoM: Fixed issue with code puzzle clues being incorrect

Additional Changes:
* Prevent download of quests/scenarios that are higher format than supported
* Prevent deletion of downloads from other game types
* Saving quests in editor now breaks into multiple ini files by type
* Fixed music volume ignored before entering settings page
* Changed button width to be dynamic based on content
* Buttons will centre if width is increased instead of based on the number of buttons
* Event button colours can be specified
* Quest writable vars that valkyie uses now start with '$'
* MoM:Fixed some tiles showing set trait twice in editor
* MoM:Fixed crash spawning Ghost orStar Spawn
* MoM:Removed non existant monster Hybrid Leader
* MoM:Add spells to available starting items
* MoM:Monster health can be set as factor of investigator count
* MoM:Monster health can be modifed with Spawn
* MoM:Additional slide puzzles added (goes up to 10 moves)
* MoM:Added character tokens for BtT
* D2E:Better image for secret room token
* D2E:Bonus health can be shown in monster list using Spawn and/or CustomMonster
* D2E:Add lieutenant packs (agents and heroes)

**Comment by EtiCarasoft** [comment]
In mac it imports correctly the content. What do you need us to test?

**Comment by EtiCarasoft** [comment]
Testing the combination puzzle seems to work better. testing on house lych scenario.
![captura de pantalla 2017-04-13 a les 11 16 47](https://cloud.githubusercontent.com/assets/26690018/24998533/b731a8bc-203a-11e7-8376-9273c55a39bd.png)

**Comment by NPBruce** [comment]
Just use it and see if anything comes up. I've tested the obvious parts of the changes. When the multi language for quests comes in I expect a number of strange issues to come up.

**Comment by NPBruce** [comment]
[valkyrie-win-0.8.8c.zip](https://github.com/NPBruce/valkyrie/files/924212/valkyrie-win-0.8.8c.zip)

[valkyrie-macos-0.8.8c.zip](https://github.com/NPBruce/valkyrie/files/924213/valkyrie-macos-0.8.8c.zip)

Annoyingly the Linux build is 33MB, which is more than the 25MB issue limit.

**Comment by NPBruce** [comment]
[valkyrie-macos-0.8.8d.zip](https://github.com/NPBruce/valkyrie/files/929244/valkyrie-macos-0.8.8d.zip)
[valkyrie-win-0.8.8d.zip](https://github.com/NPBruce/valkyrie/files/929243/valkyrie-win-0.8.8d.zip)
https://we.tl/0e5bMZTskn

**Comment by NPBruce** [comment]
[valkyrie-win-0.8.8e.zip](https://github.com/NPBruce/valkyrie/files/940964/valkyrie-win-0.8.8e.zip)
[valkyrie-macos-0.8.8e.zip](https://github.com/NPBruce/valkyrie/files/940963/valkyrie-macos-0.8.8e.zip)
https://we.tl/gGGesJiV8j
