### ISSUE TITLE
Search Token in Guest Bedroom does not disappear after searching

### ISSUE THREAD

**Issue by RudolphJ** [NPBruce/valkyrie#251]
Version: 0.8.8b
Scenario: The Fall of House Lynch

How to reproduce:
- Aquire Silver Key (for example in Laboratory)
- Enter Guest Bedroom
- Search Drawers

Expected behaviour:
- Search token should dissapear after Search Action

**Comment by Hobbeslionheart** [comment]
Had that issue as well.

**Comment by NPBruce** [comment]
Fixed in quest update.

**Comment by RudolphJ** [comment]
Thanks! I tested the updated quest and it works for me.
