### ISSUE TITLE
Sounds

### ISSUE THREAD

**Issue by Ashgur** [NPBruce/valkyrie#254]
Is there any easy possibility to add custom sounds to the game? Like some i recorded myself?

**Comment by NPBruce** [comment]
Yep, add an ogg file to the directory (or sub directory) and manually add a relative path or pick it in the editor.

**Comment by NPBruce** [comment]
It needs to go into where your quest/scenario is.

On MacOS this should be:
/Users/yourname/.config/Valkyrie/Your_Quest_Goes_Here

You can put them in a subdirectory such as:
/Users/yourname/.config/Valkyrie/Your_Quest_Goes_Here/Audio
If you like.

**Comment by Ashgur** [comment]
Thank you very much! Now its working! =)
