### ISSUE TITLE
Add way to import content under Linux

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#255]
If steam FFG apps are installed by wine we should be able to find them?

Split from #50

**Comment by jonathonf** [comment]
Yes please. :) Passing a search path via a command-line argument might work?

**Comment by NPBruce** [comment]
https://we.tl/iQyInPD8Kc

This one supports -import

Mustn't have a trailing '/' (for now).

**Comment by jonathonf** [comment]
"-import" works perfectly for me (for both RtL and MoM from Steam under WINE).

```
./valkyrie.x86_64 -import "$HOME/.wine/drive_c/Program Files (x86)/Steam/steamapps/common/Descent Road to Legend"
./valkyrie.x86_64 -import "$HOME/.wine/drive_c/Program Files (x86)/Steam/steamapps/common/Mansions of Madness"
```

**Comment by NPBruce** [comment]
I'd still like a log without using -import please.

**Comment by jonathonf** [comment]
Is there a flag to generate a log? The Linux version isn't creating `valkyrie_Data/output_log.txt` by default.

**Comment by NPBruce** [comment]
Unity docs say it is here:
~/.config/unity3d/CompanyName/ProductName/Player.log

**Comment by jonathonf** [comment]
Edited just as you posted... attached above.

**Comment by NPBruce** [comment]
I'm going to close this as good enough for version 1.
