### ISSUE TITLE
Is there a way to stop the playback of automated audio in quest (ambience)?

### ISSUE THREAD

**Issue by DelphiDie** [NPBruce/valkyrie#258]
When starting a quest there is an automated audio that plays. In events the audio command allows to start new sounds, but there is no way to halt the current ambience. This lead to multiple audio files playing above each other without any real control over the audio ambience of newly revealed tiles.

A "StopAudio" command would be very useful to set a certain mood when revealing new tiles.

**Comment by NPBruce** [comment]
Is what you want music control (#165)?  Or do you have a long audio sample on an event?

**Comment by DelphiDie** [comment]
Currently, as soon as the quest starts one of the ambience sound effects starts playing. When I start another ambience track, these 2 play over each other.

What I´d like to do is stop the current ambience sound and play a new one.

**Comment by NPBruce** [comment]
Yes, this is #165, I will close this one.
