### ISSUE TITLE
Quest text only moves into Localization.txt when edited

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#270]
Would be nicer to move all text on save.

**Comment by NPBruce** [comment]
I'll do this.

**Comment by eorahil** [comment]
Did you start? im on it too ..T_T

**Comment by eorahil** [comment]
I'm using same procedure as text changed
in every toString in every component, im checking the isKey of every translatable text. and if it is not a key means that it need to be localized by creating the corresponding key and inserting the text in the dictionary

**Comment by eorahil** [comment]
I will pause until you answer. I will do #283

**Comment by NPBruce** [comment]
I am loading everything into the dictionary on quest load.  the StringKeys in the quest data just become functions to pull out of the dictionary.
