### ISSUE TITLE
{rnd:hero} doesn't work

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#273]
Shows {rnd} reproduced on Minor Peril 13.

**Comment by NPBruce** [comment]
Confirmed to work in quest events, need to check {0} replace

**Comment by eorahil** [comment]
Can't reproduce it. What is the Minor Peril 13?

**Comment by NPBruce** [comment]
An event that has {ffg:key:{0}:{rnd:hero}}

What you get is the contents of the key with {0} replaced with {rnd}.

**Comment by eorahil** [comment]
Found and solved. pulling
