### ISSUE TITLE
Show additional message when quests are not available in the current language

### ISSUE THREAD

**Issue by eorahil** [NPBruce/valkyrie#283]
By searching in localization data , its easy to get the languages availables for an scenario
it can be included in quest.ini

**Comment by NPBruce** [comment]
I am not sure what the purpose of this is.  Do you want to prompt on the download page perhaps?  This could be done without any quest.ini changes by checking for a translated name.

**Comment by eorahil** [comment]
This was before the one file per language, now it can be done as you say checking the localization files in the quest.ini or in the folder.

**Comment by NPBruce** [comment]
Yes, but what did you want to do with this information?

**Comment by eorahil** [comment]
For 2 things:
- In the play scenario selector, like the original app, if there is no translation for current user lang there will be a red warning. "The Scenario is not in current language".
- In the future scenarios repository site. This info should be visible for people selecting scenarios even filtering by language.

**Comment by redwolf2** [comment]
The Valkyrie 2.2 Scenario Explorer does show the available languages as flags. It is also available in the scenario meta data.
