### ISSUE TITLE
Volunteer to look after documentation

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#287]
I am maintaining the manual editing documentation and other general docs, but it would be good to have someone maintaining the tutorials and graphical editor sections.

**Comment by NPBruce** [comment]
Related to #250 #249

**Comment by NPBruce** [comment]
Additionally, I think it would be nice to have mini tutorial examples ie:

* How to use a quota event
* How to randomize tokens (like D2E:AoW)
* How to create a pool of items allocated to a pool of tokens (like MoM:tFoHL)

**Comment by eorahil** [comment]
I propose to create a label for issues named "document" (or something similar) in order to know all issues that modifies the documentation somehow. For example if I introduce a EditableDialogBox with buttons, I must update the documentation images

**Comment by NPBruce** [comment]
Sure I can do that.  For everything except the editor I am updating as I merge changes.  I am using format levels to identify what is in 1.0 and 1.1.

**Comment by Hobbeslionheart** [comment]
I would suggest an FAQ for the documentation section to answer questions. The documentation is extensive and the tutorial for MOM provided is good, but simple but so far I haven't been able to find anything that would have told me how to generate random mythos event or how to create a test that can be tracked (a counter). 

Another thing is that if most answers are really already provided in the documentation then to merge all the documentation together onto one page or at least two pages separated by game. It has been very difficult for me to search through 30 sections for two different games to see which one provides the right answer (if it did exist). I'm not sure if GitHub supports that kind of wiki or whether we might need to have an external wiki to help provide that? Having it on one page allows me to use find to look for mythos or test and find all the instances where it pops up and potentially the answer.

I would also suggest best practices for creating scenarios. I have found that placing tiles, tokens, and ideas are rather easy if just tedious, it's the stuff in between that become difficult and would lead people to give up in designing scenarios. Being able to create simple, but fun scenarios with minimal amounts of need to refer to the documentation at least their first go around would lead them to further dig in to more complicated stuff.

**Comment by NPBruce** [comment]
I think creating a mini tutorials for all the problems and use cases would address most of that.

**Comment by LordPyrex** [comment]
I have written a tutorial on how to use Quotas if you would like to check it out. Please let me know if this is the kind of thing that you were talking about.
[QuotaTesting.docx](https://github.com/NPBruce/valkyrie/files/982085/QuotaTesting.docx)

**Comment by NPBruce** [comment]
I have given you an invite to get editor access directly to the wiki.  Happy for you to do the tutorials directly there:
https://github.com/NPBruce/valkyrie/wiki/QuestGuideTutorials

**Comment by NPBruce** [comment]
Probably the most common issue right now is understanding Mythos events, so a tutorial for that would be great.

**Comment by LordPyrex** [comment]
I'm actually working on that for my own scenario uses, I will take notes as I go and put together documentation for the wiki.

**Comment by LordPyrex** [comment]
I have a question regarding the mythos assignments, before I finish my testing. Are the variables all binary? Or does increasing a value cause it to have a higher probability of happening?

**Comment by NPBruce** [comment]
They are binary. For simplicity all vars are floats, so I test if the value has changed from 0.

**Comment by LordPyrex** [comment]
Got it. Also, is there somewhere I can look into the data so that I can grab some examples of different events without having to set it up the long way?

**Comment by NPBruce** [comment]
Not sure exactly what you are after.  All of the mythos events are in this file:

https://github.com/NPBruce/valkyrie/blob/master/content/MoM/base/mythos.ini

They work just like quest events.  The magic happens at the end of the file in PerilMythosPool which is triggered every mythos phase and will pick on in the last that meets the conditions at random.

**Comment by LordPyrex** [comment]
I went a different direction with it. I have the mythos wiki pretty much typed and will upload it tomorrow after I proofread it. Thanks for the link though. I might copy a few of the events as examples.

**Comment by LordPyrex** [comment]
I'm trying to upload the images in a suitable size. Did you do something to them after getting them from the document? Every iteration that I try comes back with the same dimensions.

**Comment by LordPyrex** [comment]
Mythos tutorial is live. I figured I could start trying to do something for item pools, unless there is something others are looking for.

**Comment by NPBruce** [comment]
That is great, thanks. If you are doing items I recommend using 1.1, as these have changed.

**Comment by LordPyrex** [comment]
Do you want me to add 1.1 any wikis before it's posted as the latest release?

**Comment by NPBruce** [comment]
I have already updated all of the manual editing sections to include information on format 3 and 4.  The only thing that will be out of date is the graphical editor sections, and they are already way out of date anyway.

Probably the best to do if you are up to it is the new QItem system, but I am not going to hold the release for it.

**Comment by LordPyrex** [comment]
I actually just finished the QItem tutorial, LOL, hence why I was asking.

**Comment by LordPyrex** [comment]
I'm going to start the UI next, if that sounds good

**Comment by NPBruce** [comment]
Great.  I recommend you check out the downloadable demo scenario if you haven't.

**Comment by LordPyrex** [comment]
That's been a useful tool in understand the new functions.

**Comment by LordPyrex** [comment]
I might have a question about QItems, I might need to make a change to the tutorial regarding. If you create a specified item, will that prevent a random trait set from calling that item?

**Comment by NPBruce** [comment]
Yes, all are unique, unless traits aren't used.

Also if one is used in an event or is a starting item and $restock is used items that have been used will not be picked.

**Comment by LordPyrex** [comment]
Thanks, just wanted to make sure that I was understanding what I was
working through. I'll add the $restock info to the tutorial as well.

**Comment by NPBruce** [comment]
I have just released 1.1.0d and new demos.  Can you please include the {c:QItemName} reference in your tutorial?

**Comment by LordPyrex** [comment]
Just added into the wiki

**Comment by NPBruce** [comment]
Thanks.

**Comment by redwolf2** [comment]
Can you give me editor acess to the wiki, too? I'd like to create a matix with all the tiles an the matching translation there.

**Comment by NPBruce** [comment]
Done.

**Comment by cbusbird** [comment]
I think the QItem wiki page is really great, it answered all of my questions that I had after viewing and examining the demo for 1.1.  However, I had some trouble getting to the bottom of how the Mythos variables work.  I think I've got it now but what I didn't understand is that at least one "Level" variable must be set for the others to have any effect.  Knowing how it works now the Wiki makes more sense but I had to do a lot of messing around/testing to figure it out.  In the future I should have some time to help update the Wiki, but right now I would really like to finish this scenario I'm working on before taking on anything else.  Maybe calling them "Intensity" instead of "Level" would help clear up some of the confusion that I had for others.

**Comment by redwolf2** [comment]
@cbusbird Done https://github.com/NPBruce/valkyrie/wiki/ValkyrieVars

**Comment by LordPyrex** [comment]
Just made the changes to the Mythos tutorial, I honestly had overlooked in my tinkering since I had already been running with the Minor mythos before adding in anything else. Hopefully the changes will help those that come behind.

**Comment by LordPyrex** [comment]
Do you know the directory path that iOS uses for scenario storage? I want to add it into the UI tutorial

**Comment by NPBruce** [comment]
I assume you mean MacOS:
~/.config/Valkyrie

**Comment by NPBruce** [comment]
Thanks for the UI tutorial!  I added a note about screen aspect.  It might also be good in your example to set an aspect for the continue button so the box isn't square.

**Comment by LordPyrex** [comment]
Thanks! The aspect was something I figured out later by accident after I
had made this. I had been using it to make more lines appear when they ran
out of the box. I will do some new screen grabs and replace them.

**Comment by redwolf2** [comment]
@Sanscouer 
Just found this. Seem to be portugese. https://www.youtube.com/watch?v=u5nkbid91gE
Could this be helpfull as a video tutorial for the portugese scenario creators? If so, we might add it to the wiki.

**Comment by Sanscouer** [comment]
@redwolf2 - Yes, it's helpfull. This has created by a user in other community from facebook, Mansions of Madness - Brasil. 

Just completed a little more than a month after the game's launch in Brazil and players are seeing that the FFG is not creating much new stuff, even one of the expansions has not even been released here yet, which is making everyone think that the new announcement for the end of the year will take at least another year to be released here. This tutorial helps a lot for those who have no sense of English to be able to start their MoM scenario.

**Comment by redwolf2** [comment]
Added it here: https://github.com/NPBruce/valkyrie/wiki/QuestGuideTutorials

**Comment by LordPyrex** [comment]
How should we handle alternate language tutorials? This came up over on the FFG boards, and while I was able to direct them to what we currently have posted there were offers to translate to another language.

**Comment by NPBruce** [comment]
I don't have a good answer.  The main problem is manpower, even if we had every tutorial translated to every language today, how do you handle updates and fixes without having regular updates from authors in all languages?  This only gets worse as the documentation base grows.

My position is to work on English documentation and add additional volunteers (such as yourself) who are willing to translate things, but I am only going to be concerned with having the english documentation correct.  I could implement a system of documenation versions and changelogs, but as it is the admin of this project vs ongoing development is sitting at around 40/60 at the moment, if I take on much more admin development will suffer.

**Comment by redwolf2** [comment]
I didn't add it, because I want to clutter the wiki with tutorials for other languages. I think it's best to keep it clean and in english. However having some references here and there might help someone who is not very fluent in english. I had a look on their facebook page. They even had the symbol descriptions translated to portuguese. So they build their own documentation here. The idea was just to supply some links.

Another problem I see is having Descent and Mom Tutorials on the same page. Sometimes it works out quite well, often enough it adds unnessessary context.

**Comment by LordPyrex** [comment]
That's more what I was talking about. I was more interested in where we could tell people to place things so we didn't clutter any further. I definitely don't want to pull any focus! You've done great work so far. I wish I understood the programming side of things so I could help. I understand things as far as basic C++, so I understand how the Events interact with each other, but that's about it!

**Comment by redwolf2** [comment]
Maybe we could add something like external projects or a link list with external sources. Like relevant threads on the ffg forum, boardgamegeek, heidelberger spieleverlag (the german publishers). Then we could place a section with links to tutorials in other languages.

**Comment by LordPyrex** [comment]
I know this tread is long snoozed. I was checking into some things where I could update and was going to add info to the Qitem wiki. I wanted to add info on what the Inspect function does, but I cannot find any system notes about it.

**Comment by NPBruce** [comment]
https://github.com/NPBruce/valkyrie/wiki/QuestIniQItem#inspect-format-5

Do you need more info?

**Comment by LordPyrex** [comment]
That clears it up, thanks. I'll play around with it some.

**Comment by NPBruce** [comment]
It would be good to add some of the content from #614

**Comment by LordPyrex** [comment]
I'll look at it this evening

**Comment by LordPyrex** [comment]
Wow, this is far more in depth than my previous musings. I don't know whether to just throw out my stuff and go with this, LOL

**Comment by redwolf2** [comment]
@LordPyrex 

I removed the portuguese tutorial links and added the page ExternalSites.
https://github.com/NPBruce/valkyrie/wiki/ExternalSites

**Comment by NPBruce** [comment]
I'm closing this for tracking purposes, feel free to continue to use it for discussion.
