### ISSUE TITLE
0.8.8d does not start

### ISSUE THREAD

**Issue by RudolphJ** [NPBruce/valkyrie#289]
How the problem manifests itself:

1. I start version [0.8.8d](https://github.com/NPBruce/valkyrie/issues/244#issuecomment-294807716) and choose a configuration (e.g. screen resolution)
2. I click "Play!" 
3. The "Made with Unity" animation can be seen 
4. and then the screen goes black.

Only happens on my Surface3Pro (works on another WIndows 10 Computer) and only with version 0.8.8d (0.8.7 and 0.8.8b work fine).

There is an error message in the output_log.txt of 0.8.8d:
```
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

NullReferenceException: Object reference not set to an instance of an object
  at FFGAppImport.AppFinder..ctor (Platform p) [0x00000] in <filename unknown>:0 
  at FFGAppImport.RtLFinder..ctor (Platform p) [0x00000] in <filename unknown>:0 
  at FFGAppImport.FetchContent..ctor (FFGAppImport.FFGImport import) [0x00000] in <filename unknown>:0 
  at FFGAppImport.FFGImport.Inspect () [0x00000] in <filename unknown>:0 
  at Assets.Scripts.UI.Screens.GameSelectionScreen..ctor () [0x00000] in <filename unknown>:0 
  at Game.Start () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)
```
Attached you can find the output_log.txt for version 0.8.8b and 0.8.8d:
[output_log_0.8.8b.txt](https://github.com/NPBruce/valkyrie/files/933320/output_log.txt)
[output_log_0.8.8d.txt](https://github.com/NPBruce/valkyrie/files/933324/output_log.txt)

**Comment by eorahil** [comment]
I fixed yesterday a bug. The problem is it crashes looking up RtL and MoM Steam apps. 
You can workarround installing both apps from steam.
In my particular case, I have only the MoM App in my laptop and it crashed looking for RtL.

**Comment by RudolphJ** [comment]
@eorahil , thanks, the workaround did the trick: 
0.8.8d now starts on my Surface3, which did not have RtL installed, whereas my other computer had both (MoM and RtL) installed.
