### ISSUE TITLE
Line wrap in dialogue boxes

### ISSUE THREAD

**Issue by LordPyrex** [NPBruce/valkyrie#293]
Is there a way to edit so that when typing in dialogue boxes on the Events editor. Sometimes it can be difficult to edit the text. Using the arrow keys to move over in the box also moves the map and after awhile you have to hunt your map to get it back on screen.

**Comment by NPBruce** [comment]
Yes editing text in the editor is terrible. For now I suggest you use a text editor. This will get overhauled in a later version.
