### ISSUE TITLE
Threat Support

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#3]
Currently Valkyrie doesn't support threat.  The official rules on this are vague, and I don't like the fact that doing 'something' on the map each round is very gamey (why is which round so important?).

My plan is:

Threat starts at 0 and goes up by 1 each round.

Events can modify threat (+/-) a float value (so opening doors, etc can decrease threat, failing something might increase it).

Thresholds for different threat levels are defined in [quest]

**Comment by Liquidlogic1** [comment]
I assume you will add Peril events to occur when a certain threat level is reached? Increasing threat each round without advancing (opening door or revealing new area) would eventually trigger a threat event.  Add minor and major peril events depending on threat level.

**Comment by NPBruce** [comment]
The idea is : Thresholds for different threat levels are defined in [quest]

That means that each quest sets when minor/major/deadly perils occur.  One thing I haven't worked out is  what to do at that level.  Random change or peril each round, or a peril every X rounds, or something else?

**Comment by NPBruce** [comment]
Done in 0.5.0
