### ISSUE TITLE
MoM monster health values not set

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#31]
MoM monsters do not have their health values set, this will need to be taken experimentally from the official MoM app.

**Comment by NPBruce** [comment]
Would appreciate some help here, this is one of the hold ups for releasing 1.0.

**Comment by Zranz** [comment]
Hi there! I tried to figure out monster health for the first scenario. Maybe more people can try a different scenario until we figure out every monster. All following values are from "Circle of Eternity":

5 characters game:
- Hunting Horror: 8
- Cultist: 6
- Priest of Dagon: 12
- Deep One: 6

4 characters game:
- Hunting Horror: 7
- Ghost: 5
- Cultist: 5
- Priest of Dagon: 10
- Deep One: 5

3 characters game:
- Hunting Horror: 6
- Cultist: 4
- Priest of Dagon: 8
- Deep One: 6

2 characters game:
- Hunting Horror: 5
- Deep One: 5
- Cultist: 3
- Priest of Dagon: 6
- Deep One: 3 (last two)

So, my guess is that everything is quite predictable, although some liberty is allowed. The number of monsters varied also between games, and also, as the game advances, more monsters appears if you take your time to reach the final task.

**Comment by NPBruce** [comment]
Priest of Dagon is a special case for that scenario, so I would expect the health to be custom.  Cultist and Hunting Horror makes sense, but Deep one is very strange.  What does "(last two)" mean for 2 investigator deep one?

**Comment by Zranz** [comment]
Yes, Priest of Dagon corresponds to custom character named Vanderbilt.

Deep One is indeed strange, but I repeated the 3 character game to verify and same health values appeared. Last two means that at the end of the game two more monsters appeared with health values set to 3. 

I would agree with you that 1+inv makes sense for these monsters allowing for some customization in quest creation for harder parts. And for Priest of Dagon (or chief monster) 2*(inv+1) maybe.

**Comment by NPBruce** [comment]
I am 90% convinced that all monsters are X+inv_count except for special scenario defined cases.  Just trying to get X as a default for the monsters, already support changing it with CustomMonster.

**Comment by Zranz** [comment]
I experimented with Rising Tide.

5 characters game:
- Deep One: 7
- Priest of Dagon (custom monster): 16
- Child of Dagon (custom monster): 14
- Deep One Hybrid: 7
- Riot: 20
- Star Spawn: 24

4 characters game:
- Deep One: 6
- Priest of Dagon: 13
- Child of Dagon: 12
- Deep One Hybrid: 6
- Riot: 17
- Star Spawn: 21

3 characters game:
- Priest of Dagon: 10
- Child of Dagon: 10
- Witch: 5
- Dark Druid: 5
- Deep One: 5
- Star Spawn: 18
- Deep One Hybrid: 5
- Riot: 14

2 characters game
- Priest of DAgon: 7
- Child of DAgon: 8
- Dark Druid: 4
- Deep One: 4
- Star Spawn: 15

So, linear rules would be:
deep one: 2 + inv
star spawn: 15+3*(inv-2)
riot: 11 + 3*(inv-2)
priest:  7+3*(inv-2)
child:  8+2*(inv-2)

I haven't played any other scenarios, so I would not like to test any more on different scenarios.

**Comment by NPBruce** [comment]
Definiately looks like health needs to be split into two numbers.  I will work something out.

**Comment by NPBruce** [comment]
I am using this data to put in reasonable defaults for the monsters.  Special cases can always be handled in the scenario.  I am currently missing:

## Base
* Child of Dagon
* Hybrid Leader

## MoM1E
* Zombie
* Cthonian
* Hound Of Tindalos
* Maniac
* Mi Go
* Cult Leader

## FA
* Byakhee
* Crawling One

## CotW
* Child of the Goat
* Dark Young
* Goat Spawn
* Night Gaunt
* DunwichHorror
* Wizard

## BtT
* Thrall

**Comment by Hobbeslionheart** [comment]
I'll try to get numbers for most of these, but due to the random nature of their appearances as well as the fact that some of them don't get used in the scenarios (or at least I haven't seen them in versions), It will be hard and some of these might have to be custom which given their rarity, should be anyway.

**Comment by NPBruce** [comment]
Yeah the angle I am taking on things like Priest of Dagon is just to include a reasonable default, based on one or more appearances (in this case 2+2i).

**Comment by Hobbeslionheart** [comment]
So this is going to seem random because I didn't complete scenarios if I found a map variant I hadn't played. We might play a game or two this weekend so I'll be happy to report as we go. 

Cult of Sentinel Hill

Two players

*Dark Druid - 5
Goat Spawn - 5
Bykahee - 5
Mi-Go 5
Dark Druid  - 3
Nightgaunt - 5
*Wizard - 6 
Child of Goat - 3
Dunwich Horror - 24

Three Players
*Dark Druid - 6
*Goat Spawn - 6


Shattered Bonds

Two players

Hound of Tindalos - 10 (seems rather high, but it is on the highest difficulty level)

**Comment by Hobbeslionheart** [comment]
Also what seems to me if that if you need to get this out of the way, I think you could assign 3 and 5 to most monsters as the base for two players and scale up from there.

According to MOM 1st edition wiki (http://mansionsofmadness.wikia.com/wiki/Monster ),

Cthonian had HP value of 10 and 12
Crawling one - 6 and 8
Hound of Tindalos - 9 and 7
Maniac - 5 and 6
Night Gaunt - 7 and 9 (contradicts the above)
Wizard - 6

Some others didn't have entries.

**Comment by NPBruce** [comment]
I have all the first edition content, so I will use that to extrapolate and fill in the gaps.

**Comment by NPBruce** [comment]
Deadly departed 2 investigators:

Zombies: 4
Dark druid: 3
Cult leader: 16

**Comment by NPBruce** [comment]
Splitting #322 and moving this to later.

**Comment by NPBruce** [comment]
I am going to close this as good enough for now.
