### ISSUE TITLE
Duplicate test sign on puzzles.

### ISSUE THREAD

**Issue by LordPyrex** [NPBruce/valkyrie#311]
I noticed that because the puzzles use the {*} call value and the icon value that they are double displaying in actual puzzle where it provides the Skill icon.
![skilldouble](https://cloud.githubusercontent.com/assets/27811809/25315070/1d2adb5e-281d-11e7-9dbf-de03ef22fd50.jpg)

**Comment by NPBruce** [comment]
Problem is with the editor. I will fix soon, but you can work around by manually removing one of them from the other.ini file.
