### ISSUE TITLE
A way to spawn monsters in activated state

### ISSUE THREAD

**Issue by DelphiDie** [NPBruce/valkyrie#318]
Would it be possible to integrate a feature that allows to spawn monsters in an already activated state, as it is done in some RtL Quests?

**Comment by NPBruce** [comment]
I have never seen this in RtL. If the monster spawns at the end round trigger it won't activate that round, but will not show as activated. This is consistent with RtL.

**Comment by DelphiDie** [comment]
This happens in multiple quests in RtL. The easiest example to point to is the first Quest of the "Kindred Fire" campaign.

See screenshots for a reproduceable example:

![wakeoffire1](https://cloud.githubusercontent.com/assets/26790002/25334252/2477452e-28ee-11e7-9ba5-0e6eb9a19aa8.jpg)
![wakeoffire2](https://cloud.githubusercontent.com/assets/26790002/25334253/247c1720-28ee-11e7-80e4-1baa9a08d0ec.jpg)
![wakeoffire3](https://cloud.githubusercontent.com/assets/26790002/25334254/247f348c-28ee-11e7-99e0-a421a43ff097.jpg)

**Comment by NPBruce** [comment]
I hadn't realised that.  I will think about a good way to do this.

**Comment by Xyphistor** [comment]
BUMP ¬_¬
