### ISSUE TITLE
Bug: Custom Monster activations of masters and minions are reversed

### ISSUE THREAD

**Issue by DelphiDie** [NPBruce/valkyrie#319]
In the V 0.9 release there seems to be a bug that reverses master and minion monster activations.

I´m using this code:

`[ActivationGoblinTerrain]
ability=All monsters ignore terrain effects.\n<i>Piggyback:</i> Attacks performed by a master Goblin Archer adjacent to Mauler ignore line of sight and gain +1 {heart} and +3 range.
master={action} Engage Mauler, moving to a space in line of sight of as few heroes as possible.\n{action} Attack the hero within 8 spaces with the least Health remaining.
minion={action} Attack a hero within 3 spaces.\n{action} Engage the Exit.`

But this is the result:

![mastergoblin](https://cloud.githubusercontent.com/assets/26790002/25329866/d1cf91b0-28dd-11e7-9c81-53f7e3c7102d.jpg)
![miniongoblin](https://cloud.githubusercontent.com/assets/26790002/25329867/d1d1df38-28dd-11e7-950d-d9326743f90d.jpg)

**Comment by NPBruce** [comment]
I will look into it but note that this is now legacy support, all text is now read into a localisation dictionary and going forward will be read from Localization.txt and not the ini data (format 3)

**Comment by NPBruce** [comment]
Fixed, but this bug has effected all published quests and scenarios.  I will update.

**Comment by NPBruce** [comment]
Pushed quest and scenario fixes for current version.
