### ISSUE TITLE
Button text in "Event"->"Next Events" is not saved

### ISSUE THREAD

**Issue by RudolphJ** [NPBruce/valkyrie#320]
Version: 0.9.0

**How to reproduce**

- Enter scenario editor and choose a scenario to edit (e.g. "The Fall of House Lynch")
- Choose an event (e.g. EventKitchenTile)
- Click "Next Events"
- Change button text (e.g. from "Continue" to "Next")
- Click "Back"
- Click "Next Events"

**Expected behaviour**

Button text should have new value.

**Comment by NPBruce** [comment]
That has been fixed in 0.9.1.
