### ISSUE TITLE
Add a way to backreference texts in localization files

### ISSUE THREAD

**Issue by redwolf2** [NPBruce/valkyrie#323]
Alot of the quest text apear multiple times. There could be a way to backreference quest texts like:

```
EventManiacSample1.text,<i>The maniac rips out some of your hair.</i>,,,,,,,,,
EventManiacSample2.text,{quest:EventManiacSample1.text},,,,,,,,,
```

It could be utilized to remove more clutter like:

`EventManiacSample3.text,{quest:EventManiacSample1.text}\n\nDraw two face up horror.,,,,,,,,,`

**Comment by NPBruce** [comment]
This already works!  the notation is {qst:\<key\>}, you can see it used in the new scenario Exotic Material.

Another advantage is text then only needs to be translated in one place.

Reopen if I have misunderstood or this doesn't work for you.
