### ISSUE TITLE
Tile Names in editor might not be pulling right

### ISSUE THREAD

**Issue by Hobbeslionheart** [NPBruce/valkyrie#329]
![image](https://cloud.githubusercontent.com/assets/26637617/25415620/d428396a-2a06-11e7-9307-c33e89162e70.png)

**Comment by NPBruce** [comment]
What is the problem in this case?  If you are refering to MAD23 it is because there are 3 Dining Rooms (Base 1E and BtT).

**Comment by Hobbeslionheart** [comment]
After playing more with the editor, I see that MAD23 and others are symbol reference. This wasn't evident in other tiles that I had used to date. Can close this.

**Comment by NPBruce** [comment]
Most names are unique and don't need it, where there are duplicates this is used.
