### ISSUE TITLE
Importing

### ISSUE THREAD

**Issue by visanz2** [NPBruce/valkyrie#330]
Hi,
I just install Valkyrie and I have installed Mansion of Madness 2nd edition on steam in my Macbook. When Valkyrie is importing the information from MoM, it never finishes. Is there any problem? Additionally, is there any way I can know how many time or the status of the import?

**Comment by NPBruce** [comment]
It takes around 1 minute to import, I don't have a progress display.

Cany you please provide your log from here:
/Users/[username]/.config/Valkyrie

**Comment by NPBruce** [comment]
Split UI improvement as #331

**Comment by visanz2** [comment]
There is only one file config.ini:

[UserConfig]
currentLang=English

I cannot find a log file.

**Comment by NPBruce** [comment]
Try ~/Library/Logs/Unity/Player.log

Note that 1min is on a modern systems, older systems may take longer.

**Comment by visanz2** [comment]
This is my Player.log file:

Initialize engine version: 5.5.1f1 (88d00a7498cd)
GfxDevice: creating device client; threaded=1
Renderer: NVIDIA GeForce GT 650M OpenGL Engine
Vendor:   NVIDIA Corporation
Version:  4.1 NVIDIA-10.16.34 355.10.05.35f05
GLES:     0
 GL_ARB_blend_func_extended GL_ARB_draw_buffers_blend GL_ARB_draw_indirect GL_ARB_ES2_compatibility GL_ARB_explicit_attrib_location GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader5 GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_occlusion_query2 GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_shader_subroutine GL_ARB_shading_language_include GL_ARB_tessellation_shader GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_cube_map_array GL_ARB_texture_gather GL_ARB_texture_query_lod GL_ARB_texture_rgb10_a2ui GL_ARB_texture_storage GL_ARB_texture_swizzle GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_vertex_attrib_64bit GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_depth_bounds_test GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_texture_compression_s3tc GL_EXT_texture_filter_anisotropic GL_EXT_texture_mirror_clamp GL_EXT_texture_sRGB_decode GL_APPLE_client_st
orage GL_APPLE_container_object_shareable GL_APPLE_flush_render GL_APPLE_object_purgeable GL_APPLE_rgb_422 GL_APPLE_row_bytes GL_APPLE_texture_range GL_ATI_texture_mirror_once GL_NV_texture_barrier
OPENGL LOG: Creating OpenGL 4.1 graphics device ; Context level  <OpenGL 4.1> ; Context handle 77064704
Begin MonoManager ReloadAssembly
Platform assembly: /private/var/folders/rg/rtk0_fhn5d5216y1c_1bqch80000gn/T/AppTranslocation/BE73BAB0-4E6A-44C5-A402-754CF3690D25/d/Valkyrie.app/Contents/Resources/Data/Managed/UnityEngine.dll (this message is harmless)
Loading /private/var/folders/rg/rtk0_fhn5d5216y1c_1bqch80000gn/T/AppTranslocation/BE73BAB0-4E6A-44C5-A402-754CF3690D25/d/Valkyrie.app/Contents/Resources/Data/Managed/UnityEngine.dll into Unity Child Domain
Platform assembly: /private/var/folders/rg/rtk0_fhn5d5216y1c_1bqch80000gn/T/AppTranslocation/BE73BAB0-4E6A-44C5-A402-754CF3690D25/d/Valkyrie.app/Contents/Resources/Data/Managed/Assembly-CSharp.dll (this message is harmless)
Loading /private/var/folders/rg/rtk0_fhn5d5216y1c_1bqch80000gn/T/AppTranslocation/BE73BAB0-4E6A-44C5-A402-754CF3690D25/d/Valkyrie.app/Contents/Resources/Data/Managed/Assembly-CSharp.dll into Unity Child Domain
Platform assembly: /private/var/folders/rg/rtk0_fhn5d5216y1c_1bqch80000gn/T/AppTranslocation/BE73BAB0-4E6A-44C5-A402-754CF3690D25/d/Valkyrie.app/Contents/Resources/Data/Managed/UnityEngine.UI.dll (this message is harmless)
Loading /private/var/folders/rg/rtk0_fhn5d5216y1c_1bqch80000gn/T/AppTranslocation/BE73BAB0-4E6A-44C5-A402-754CF3690D25/d/Valkyrie.app/Contents/Resources/Data/Managed/UnityEngine.UI.dll into Unity Child Domain
Platform assembly: /private/var/folders/rg/rtk0_fhn5d5216y1c_1bqch80000gn/T/AppTranslocation/BE73BAB0-4E6A-44C5-A402-754CF3690D25/d/Valkyrie.app/Contents/Resources/Data/Managed/UnityEngine.Networking.dll (this message is harmless)
Loading /private/var/folders/rg/rtk0_fhn5d5216y1c_1bqch80000gn/T/AppTranslocation/BE73BAB0-4E6A-44C5-A402-754CF3690D25/d/Valkyrie.app/Contents/Resources/Data/Managed/UnityEngine.Networking.dll into Unity Child Domain
Platform assembly: /private/var/folders/rg/rtk0_fhn5d5216y1c_1bqch80000gn/T/AppTranslocation/BE73BAB0-4E6A-44C5-A402-754CF3690D25/d/Valkyrie.app/Contents/Resources/Data/Managed/UnityEngine.PlaymodeTestsRunner.dll (this message is harmless)
Loading /private/var/folders/rg/rtk0_fhn5d5216y1c_1bqch80000gn/T/AppTranslocation/BE73BAB0-4E6A-44C5-A402-754CF3690D25/d/Valkyrie.app/Contents/Resources/Data/Managed/UnityEngine.PlaymodeTestsRunner.dll into Unity Child Domain
Platform assembly: /private/var/folders/rg/rtk0_fhn5d5216y1c_1bqch80000gn/T/AppTranslocation/BE73BAB0-4E6A-44C5-A402-754CF3690D25/d/Valkyrie.app/Contents/Resources/Data/Managed/FFGAppImport.dll (this message is harmless)
Loading /private/var/folders/rg/rtk0_fhn5d5216y1c_1bqch80000gn/T/AppTranslocation/BE73BAB0-4E6A-44C5-A402-754CF3690D25/d/Valkyrie.app/Contents/Resources/Data/Managed/FFGAppImport.dll into Unity Child Domain
Platform assembly: /private/var/folders/rg/rtk0_fhn5d5216y1c_1bqch80000gn/T/AppTranslocation/BE73BAB0-4E6A-44C5-A402-754CF3690D25/d/Valkyrie.app/Contents/Resources/Data/Managed/Ionic.Zip.Unity.dll (this message is harmless)
Loading /private/var/folders/rg/rtk0_fhn5d5216y1c_1bqch80000gn/T/AppTranslocation/BE73BAB0-4E6A-44C5-A402-754CF3690D25/d/Valkyrie.app/Contents/Resources/Data/Managed/Ionic.Zip.Unity.dll into Unity Child Domain
Platform assembly: /private/var/folders/rg/rtk0_fhn5d5216y1c_1bqch80000gn/T/AppTranslocation/BE73BAB0-4E6A-44C5-A402-754CF3690D25/d/Valkyrie.app/Contents/Resources/Data/Managed/ValkyrieTools.dll (this message is harmless)
Loading /private/var/folders/rg/rtk0_fhn5d5216y1c_1bqch80000gn/T/AppTranslocation/BE73BAB0-4E6A-44C5-A402-754CF3690D25/d/Valkyrie.app/Contents/Resources/Data/Managed/ValkyrieTools.dll into Unity Child Domain
Platform assembly: /private/var/folders/rg/rtk0_fhn5d5216y1c_1bqch80000gn/T/AppTranslocation/BE73BAB0-4E6A-44C5-A402-754CF3690D25/d/Valkyrie.app/Contents/Resources/Data/Managed/System.Core.dll (this message is harmless)
- Completed reload, in  0.017 seconds
Platform assembly: /private/var/folders/rg/rtk0_fhn5d5216y1c_1bqch80000gn/T/AppTranslocation/BE73BAB0-4E6A-44C5-A402-754CF3690D25/d/Valkyrie.app/Contents/Resources/Data/Managed/System.dll (this message is harmless)
UnloadTime: 1.290886 ms
Valkyrie Version: 0.9.2

 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Attempting to locate AppId 477200 on MacOS.
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Starting system_profiler.
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Looking for: /Road to Legend.app
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Asset location: /Contents/Resources/Data
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Could not find main assets file: /Contents/Resources/Data/resources.assets
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

FFG D2E not found.

 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Attempting to locate AppId 478980 on MacOS.
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Starting system_profiler.
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Looking for: /Mansions of Madness.app
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Name Index: 1198
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Start Index: 1105
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Using location: /Users/vicentsanzmarco/Library/Application Support/Steam/steamapps/common/Mansions of Madness/Mansions of Madness.app
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Asset location: /Users/vicentsanzmarco/Library/Application Support/Steam/steamapps/common/Mansions of Madness/Mansions of Madness.app/Contents/Resources/Data
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

FFG MoM Version Found: 1.3.3

 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Could not find a part of the path "/private/var/folders/rg/rtk0_fhn5d5216y1c_1bqch80000gn/T/AppTranslocation/BE73BAB0-4E6A-44C5-A402-754CF3690D25/d/Valkyrie.app/Contents/content/D2E/ffg/import.ini".
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Could not find a part of the path "/private/var/folders/rg/rtk0_fhn5d5216y1c_1bqch80000gn/T/AppTranslocation/BE73BAB0-4E6A-44C5-A402-754CF3690D25/d/Valkyrie.app/Contents/content/MoM/ffg/import.ini".
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Could not find a part of the path "/private/var/folders/rg/rtk0_fhn5d5216y1c_1bqch80000gn/T/AppTranslocation/BE73BAB0-4E6A-44C5-A402-754CF3690D25/d/Valkyrie.app/Contents/content/MoM/ffg/import.ini".
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Setting up 2 worker threads for Enlighten.
  Thread -> id: b1f2f000 -> priority: 1 
  Thread -> id: b23ef000 -> priority: 1 
Could not find a part of the path "/private/var/folders/rg/rtk0_fhn5d5216y1c_1bqch80000gn/T/AppTranslocation/BE73BAB0-4E6A-44C5-A402-754CF3690D25/d/Valkyrie.app/Contents/content/MoM/ffg/import.ini".
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

UnauthorizedAccessException: Access to the path "/private/var/folders/rg/rtk0_fhn5d5216y1c_1bqch80000gn/T/AppTranslocation/BE73BAB0-4E6A-44C5-A402-754CF3690D25/d/Valkyrie.app/Contents/content/" is denied.
  at System.IO.Directory.CreateDirectoriesInternal (System.String path) [0x00000] in <filename unknown>:0 
  at System.IO.Directory.CreateDirectory (System.String path) [0x00000] in <filename unknown>:0 
  at FFGAppImport.FetchContent.ExportTexture (Unity_Studio.AssetPreloadData asset) [0x00000] in <filename unknown>:0 
  at FFGAppImport.FetchContent.BuildAssetStrucutres () [0x00000] in <filename unknown>:0 
  at FFGAppImport.FetchContent.Import (System.String assetFile) [0x00000] in <filename unknown>:0 
  at FFGAppImport.FetchContent.Import () [0x00000] in <filename unknown>:0 
  at FFGAppImport.FFGImport.Import () [0x00000] in <filename unknown>:0 
  at Assets.Scripts.UI.Screens.GameSelectionScreen.PerformImport (System.String type) [0x00000] in <filename unknown>:0 
  at Assets.Scripts.UI.Screens.GameSelectionScreen+<Import>c__AnonStorey0.<>m__0 () [0x00000] in <filename unknown>:0 
  at Game+<CallAfterFrameDelay>c__Iterator0.MoveNext () [0x00000] in <filename unknown>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

**Comment by NPBruce** [comment]
Someone else has had this on MacOS as well.  I don't have macos so it is very hard to debug.

**Comment by Ashgur** [comment]
No, it just takes some time and it crashes if i move the mouse while importing.

**Comment by redwolf2** [comment]
I had the same problem on Windows, when i don't start the application as administrator.

**Comment by NPBruce** [comment]
Good information.

At some point I was going to move where it writes to,  I might step that up.

**Comment by snusmu** [comment]
also have this on macos, hangs indefinitely when importing (had app open whole day...). macbook air 2015, sierra (10.12.4).

**Comment by snusmu** [comment]
my Player.log contents:

Initialize engine version: 5.5.1f1 (88d00a7498cd)
GfxDevice: creating device client; threaded=1
Renderer: Intel(R) HD Graphics 6000
Vendor:   Intel Inc.
Version:  4.1 INTEL-10.24.45
GLES:     0
 GL_ARB_blend_func_extended GL_ARB_draw_buffers_blend GL_ARB_draw_indirect GL_ARB_ES2_compatibility GL_ARB_explicit_attrib_location GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader5 GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_occlusion_query2 GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_shader_subroutine GL_ARB_shading_language_include GL_ARB_tessellation_shader GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_cube_map_array GL_ARB_texture_gather GL_ARB_texture_query_lod GL_ARB_texture_rgb10_a2ui GL_ARB_texture_storage GL_ARB_texture_swizzle GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_vertex_attrib_64bit GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_texture_compression_s3tc GL_EXT_texture_filter_anisotropic GL_EXT_texture_sRGB_decode GL_APPLE_client_storage GL_APPLE_container_object_shareable GL_APPLE_fl
ush_render GL_APPLE_object_purgeable GL_APPLE_rgb_422 GL_APPLE_row_bytes GL_APPLE_texture_range GL_ATI_texture_mirror_once GL_NV_texture_barrier
OPENGL LOG: Creating OpenGL 4.1 graphics device ; Context level  <OpenGL 4.1> ; Context handle 51417088
Begin MonoManager ReloadAssembly
Platform assembly: /private/var/folders/f0/_1gn5p792mb8v_rwlz3wlvfw0000gn/T/AppTranslocation/1CAD9F12-76F1-4C7E-B07A-A53F8531E868/d/Valkyrie.app/Contents/Resources/Data/Managed/UnityEngine.dll (this message is harmless)
Loading /private/var/folders/f0/_1gn5p792mb8v_rwlz3wlvfw0000gn/T/AppTranslocation/1CAD9F12-76F1-4C7E-B07A-A53F8531E868/d/Valkyrie.app/Contents/Resources/Data/Managed/UnityEngine.dll into Unity Child Domain
Platform assembly: /private/var/folders/f0/_1gn5p792mb8v_rwlz3wlvfw0000gn/T/AppTranslocation/1CAD9F12-76F1-4C7E-B07A-A53F8531E868/d/Valkyrie.app/Contents/Resources/Data/Managed/Assembly-CSharp.dll (this message is harmless)
Loading /private/var/folders/f0/_1gn5p792mb8v_rwlz3wlvfw0000gn/T/AppTranslocation/1CAD9F12-76F1-4C7E-B07A-A53F8531E868/d/Valkyrie.app/Contents/Resources/Data/Managed/Assembly-CSharp.dll into Unity Child Domain
Platform assembly: /private/var/folders/f0/_1gn5p792mb8v_rwlz3wlvfw0000gn/T/AppTranslocation/1CAD9F12-76F1-4C7E-B07A-A53F8531E868/d/Valkyrie.app/Contents/Resources/Data/Managed/UnityEngine.UI.dll (this message is harmless)
Loading /private/var/folders/f0/_1gn5p792mb8v_rwlz3wlvfw0000gn/T/AppTranslocation/1CAD9F12-76F1-4C7E-B07A-A53F8531E868/d/Valkyrie.app/Contents/Resources/Data/Managed/UnityEngine.UI.dll into Unity Child Domain
Platform assembly: /private/var/folders/f0/_1gn5p792mb8v_rwlz3wlvfw0000gn/T/AppTranslocation/1CAD9F12-76F1-4C7E-B07A-A53F8531E868/d/Valkyrie.app/Contents/Resources/Data/Managed/UnityEngine.Networking.dll (this message is harmless)
Loading /private/var/folders/f0/_1gn5p792mb8v_rwlz3wlvfw0000gn/T/AppTranslocation/1CAD9F12-76F1-4C7E-B07A-A53F8531E868/d/Valkyrie.app/Contents/Resources/Data/Managed/UnityEngine.Networking.dll into Unity Child Domain
Platform assembly: /private/var/folders/f0/_1gn5p792mb8v_rwlz3wlvfw0000gn/T/AppTranslocation/1CAD9F12-76F1-4C7E-B07A-A53F8531E868/d/Valkyrie.app/Contents/Resources/Data/Managed/UnityEngine.PlaymodeTestsRunner.dll (this message is harmless)
Loading /private/var/folders/f0/_1gn5p792mb8v_rwlz3wlvfw0000gn/T/AppTranslocation/1CAD9F12-76F1-4C7E-B07A-A53F8531E868/d/Valkyrie.app/Contents/Resources/Data/Managed/UnityEngine.PlaymodeTestsRunner.dll into Unity Child Domain
Platform assembly: /private/var/folders/f0/_1gn5p792mb8v_rwlz3wlvfw0000gn/T/AppTranslocation/1CAD9F12-76F1-4C7E-B07A-A53F8531E868/d/Valkyrie.app/Contents/Resources/Data/Managed/FFGAppImport.dll (this message is harmless)
Loading /private/var/folders/f0/_1gn5p792mb8v_rwlz3wlvfw0000gn/T/AppTranslocation/1CAD9F12-76F1-4C7E-B07A-A53F8531E868/d/Valkyrie.app/Contents/Resources/Data/Managed/FFGAppImport.dll into Unity Child Domain
Platform assembly: /private/var/folders/f0/_1gn5p792mb8v_rwlz3wlvfw0000gn/T/AppTranslocation/1CAD9F12-76F1-4C7E-B07A-A53F8531E868/d/Valkyrie.app/Contents/Resources/Data/Managed/Ionic.Zip.Unity.dll (this message is harmless)
Loading /private/var/folders/f0/_1gn5p792mb8v_rwlz3wlvfw0000gn/T/AppTranslocation/1CAD9F12-76F1-4C7E-B07A-A53F8531E868/d/Valkyrie.app/Contents/Resources/Data/Managed/Ionic.Zip.Unity.dll into Unity Child Domain
Platform assembly: /private/var/folders/f0/_1gn5p792mb8v_rwlz3wlvfw0000gn/T/AppTranslocation/1CAD9F12-76F1-4C7E-B07A-A53F8531E868/d/Valkyrie.app/Contents/Resources/Data/Managed/ValkyrieTools.dll (this message is harmless)
Loading /private/var/folders/f0/_1gn5p792mb8v_rwlz3wlvfw0000gn/T/AppTranslocation/1CAD9F12-76F1-4C7E-B07A-A53F8531E868/d/Valkyrie.app/Contents/Resources/Data/Managed/ValkyrieTools.dll into Unity Child Domain
Platform assembly: /private/var/folders/f0/_1gn5p792mb8v_rwlz3wlvfw0000gn/T/AppTranslocation/1CAD9F12-76F1-4C7E-B07A-A53F8531E868/d/Valkyrie.app/Contents/Resources/Data/Managed/System.Core.dll (this message is harmless)
- Completed reload, in  0.127 seconds
Platform assembly: /private/var/folders/f0/_1gn5p792mb8v_rwlz3wlvfw0000gn/T/AppTranslocation/1CAD9F12-76F1-4C7E-B07A-A53F8531E868/d/Valkyrie.app/Contents/Resources/Data/Managed/System.dll (this message is harmless)
UnloadTime: 1.354179 ms
Valkyrie Version: 1.0.0

 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Attempting to locate AppId 477200 on MacOS.
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Starting system_profiler.
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Looking for: /Road to Legend.app
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Asset location: /Contents/Resources/Data
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Could not find main assets file: /Contents/Resources/Data/resources.assets
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

FFG D2E not found.

 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Attempting to locate AppId 478980 on MacOS.
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Starting system_profiler.
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Looking for: /Mansions of Madness.app
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Name Index: 1885
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Start Index: 1791
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Using location: /Users/pavelkrasnovskij/Library/Application Support/Steam/steamapps/common/Mansions of Madness/Mansions of Madness.app
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Asset location: /Users/pavelkrasnovskij/Library/Application Support/Steam/steamapps/common/Mansions of Madness/Mansions of Madness.app/Contents/Resources/Data
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

FFG MoM Version Found: 1.3.3

 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Could not find a part of the path "/private/var/folders/f0/_1gn5p792mb8v_rwlz3wlvfw0000gn/T/AppTranslocation/1CAD9F12-76F1-4C7E-B07A-A53F8531E868/d/Valkyrie.app/Contents/content/D2E/ffg/import.ini".
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Could not find a part of the path "/private/var/folders/f0/_1gn5p792mb8v_rwlz3wlvfw0000gn/T/AppTranslocation/1CAD9F12-76F1-4C7E-B07A-A53F8531E868/d/Valkyrie.app/Contents/content/MoM/ffg/import.ini".
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Could not find a part of the path "/private/var/folders/f0/_1gn5p792mb8v_rwlz3wlvfw0000gn/T/AppTranslocation/1CAD9F12-76F1-4C7E-B07A-A53F8531E868/d/Valkyrie.app/Contents/content/MoM/ffg/import.ini".
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Setting up 1 worker threads for Enlighten.
  Thread -> id: b0a7b000 -> priority: 1 
UnauthorizedAccessException: Access to the path "/private/var/folders/f0/_1gn5p792mb8v_rwlz3wlvfw0000gn/T/AppTranslocation/1CAD9F12-76F1-4C7E-B07A-A53F8531E868/d/Valkyrie.app/Contents/content/" is denied.
  at System.IO.Directory.CreateDirectoriesInternal (System.String path) [0x00000] in <filename unknown>:0 
  at System.IO.Directory.CreateDirectory (System.String path) [0x00000] in <filename unknown>:0 
  at FFGAppImport.FetchContent.ExportTexture (Unity_Studio.AssetPreloadData asset) [0x00000] in <filename unknown>:0 
  at FFGAppImport.FetchContent.BuildAssetStrucutres () [0x00000] in <filename unknown>:0 
  at FFGAppImport.FetchContent.Import (System.String assetFile) [0x00000] in <filename unknown>:0 
  at FFGAppImport.FetchContent.Import () [0x00000] in <filename unknown>:0 
  at FFGAppImport.FFGImport.Import () [0x00000] in <filename unknown>:0 
  at Assets.Scripts.UI.Screens.GameSelectionScreen.PerformImport (System.String type) [0x00000] in <filename unknown>:0 
  at Assets.Scripts.UI.Screens.GameSelectionScreen+<Import>c__AnonStorey0.<>m__0 () [0x00000] in <filename unknown>:0 
  at Game+<CallAfterFrameDelay>c__Iterator0.MoveNext () [0x00000] in <filename unknown>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

Default audio device was changed, but the audio system failed to initialize it (No errors.). Attempting to reset sound system.
 
(Filename:  Line: 69)

**Comment by NPBruce** [comment]
The reason it works for some people is most likely a permissions/user level thing.

I will restructure Valkyrie at some point which may fix this, but it won't be soon.

**Comment by snusmu** [comment]
thanks for the clue, and pretty sure you are right. i tried running:

`sudo ./Valkyrie.app/Contents/MacOS/Valkyrie`

and everything worked.

**Comment by visanz2** [comment]
Thanks snusmu and NPBruce. Snusmu your solution works for me ;-)
