### ISSUE TITLE
Allow Localization data to be split by language

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#345]
Currently it is very hard to version control the localization with all langauges on the same line.  Splitting to different files per language will make this easier.

**Comment by eorahil** [comment]
if we have a 3 languages scenario. The default language of the scenario is English.
there are also Spanish and German. with 3 single language localization files.
Localization.txt (default English), Localization.Spanish.txt and Localization.German.txt.
My Valkyrie has language selected to Spanish.
I edit the scenario and create a new event with new text. What should I do:
- Create new entry in the spanish language. create the entry for english but empty text. German localization won't be edited.
- Create new entry in the default language and spanish language dictionaries: Both will have my text in spanish. but german localization file won't be edited.
- Create new entry in the default language and spanish language dictionaries: Both will have my text in spanish. Create an empty entry for german language.

or same question with other view. When I open an scenario, should I load every localization files and work alltogether. When saving I will split again? or should I open only the default and actual editor language?

**Comment by NPBruce** [comment]
> Create new entry in the spanish language. create the entry for english but empty text. German localization won't be edited.

This sounds best to me.

> When I open an scenario, should I load every localization files and work alltogether. When saving I will split again? or should I open only the default and actual editor language?

This is internal so doesn't matter too much.  The easiest thing to do for now is just load everything and change the save to split it up again, because you don't have to change your code much to do so.  If you want to only load what is needed you can, but I think this is more work.
