### ISSUE TITLE
BtT spells in base content

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#357]
Need to move out so they aren't given if BtT isn't selected.

**Comment by LordPyrex** [comment]
Yeah, I've been trying to recreate the event after I looked closer at the post.  I cannot get it to populate in the starting items with just the base set selected.

**Comment by LordPyrex** [comment]
And then 30 seconds later this happened.
![wrack](https://cloud.githubusercontent.com/assets/27811809/25568008/9c01f458-2dc7-11e7-8d7f-9c6d9fbd6b44.png)

**Comment by NPBruce** [comment]
Wrack is in the base set.  There is a bug though, I have fixed it now and it will be in 1.0.1

**Comment by LordPyrex** [comment]
Yeah, not sure why I didn't just check the card. I think in my mind I saw the Officer and thought of it being linked to Officer Tetsuo

**Comment by NPBruce** [comment]
1.0.1 released
