### ISSUE TITLE
No Door?

### ISSUE THREAD

**Issue by KasperJansen** [NPBruce/valkyrie#358]
I tried following the tutorial, but there was no Door option in the Component Menu for MoM. There is no Item or MPlace either. How is this possible?

**Comment by NPBruce** [comment]
Are you following the quest tutorial for d2e or the scenario tutorial for MoM?

**Comment by KasperJansen** [comment]
Just found the Scenario Tutorial! Since the software just calls it all Quest, I got confused. Thanks a lot! For your response and for this entire project!

**Comment by NPBruce** [comment]
This isn't the first time this problem has occurred so I have moved MoM to above d2e. We have more MoM writers and this seems to throw them, so hopefully that will help?
