### ISSUE TITLE
Scrolling inside the choose investigator dialog is too slow

### ISSUE THREAD

**Issue by redwolf2** [NPBruce/valkyrie#360]
In the Choose Investigator Dialog, the user has to use the scroll wheel five times to move the list one item down.

**Comment by NPBruce** [comment]
I assume you are talking about the mouse wheel not dragging or using the scroll bar?

**Comment by redwolf2** [comment]
Yes, using the mouse wheel. The same happens inside the Choose Content Dialog.

**Comment by redwolf2** [comment]
Fixed it here https://github.com/NPBruce/valkyrie/pull/368
