### ISSUE TITLE
Standard Mythos events

### ISSUE THREAD

**Issue by KasperJansen** [NPBruce/valkyrie#363]
How can I overwrite the standard 'no immediate effect' Mythos events?

**Comment by KasperJansen** [comment]
I think I just figured it out. Is the solution to not make EventStart set $mythosFlavor to 1?

**Comment by NPBruce** [comment]
Yep. You can set different types of mythos as shown here:
https://github.com/NPBruce/valkyrie/wiki/ValkyrieVars

Or just write your​ own using Mythos as a trigger.
