### ISSUE TITLE
Investigator entry image

### ISSUE THREAD

**Issue by KasperJansen** [NPBruce/valkyrie#365]
How did you add the image of the investigator miniatures to the entry spot in your scenarios? Is that something you did manually? Or am I overlooking something?

**Comment by KasperJansen** [comment]
(I hope you don't mind all my questions.)

**Comment by NPBruce** [comment]
No problem, it is a token type. You have to add it and remove it again.

**Comment by NPBruce** [comment]
PS you can copy the other scenarios using the editor then have a look at how they work.
