### ISSUE TITLE
Spawning MiGo crashes app

### ISSUE THREAD

**Issue by KasperJansen** [NPBruce/valkyrie#367]
When I spawn a MiGo in the Mythos phase (Spawn with Type MiGo and trigger Mythos), the application crashes. If I change the Type of the Spawn to any other monster, everything is fine. (All contents are activated.)

**Comment by NPBruce** [comment]
I can't reproduce this, can you please upload your quest file?  You can find it in %AppData%/Valkyrie/

Also the log from valkyrie_Data\output_log.txt would be helpful.

**Comment by KasperJansen** [comment]
Of course!

[Probeerscenario.zip](https://github.com/NPBruce/valkyrie/files/967859/Probeerscenario.zip)
My quest

[output_log.txt](https://github.com/NPBruce/valkyrie/files/967861/output_log.txt)
Output Log

**Comment by KasperJansen** [comment]
If you just continue to the Mythos phase en keep clicking continue, it will crash. At least, it does with me.

**Comment by NPBruce** [comment]
Got it, thanks.  I didn't try activating the Mi Go.

**Comment by NPBruce** [comment]
Fixed for 1.0.1.

**Comment by NPBruce** [comment]
1.0.1 released
