### ISSUE TITLE
Text edit feilds reset to '...'

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#374]
Editing works, but display resets to '...' and editing again saves this.

**Comment by eorahil** [comment]
Sorry I dont understand this issue. Is related with new Icon butons or multiline EditableDialogBox?

**Comment by NPBruce** [comment]
The multiline changes. Text isn't displaying correctly.

**Comment by eorahil** [comment]
Sorry I cant reproduce it. can you guide me to make it fail?

**Comment by NPBruce** [comment]
I'll sort it out when I get a chance.

**Comment by eorahil** [comment]
I'm using the new UI component. 
It takes the scenario.description to fill the text. but after you change the text you force to redraw and redraw takes the scenario.description text. 
I think you should take only the scenario.description text if there is no scenario.uitext element. 
OR
changing the scenario.uitext also changes the scenario.description texts.

Could this be the issues. that you have ... in the scenario.description and you are trying to change the UI text?

**Comment by NPBruce** [comment]
Can no longer reproduce.

**Comment by eorahil** [comment]
Can be related with #424 
User lost all texts after item deletion
In the deletion, there are [empty] buttons that if you click on it all stringkeys starting with [empty] (all entries) will be deleted so the whole dictionary are deleted.
In one localization file, the file is overwritten with empty entries.
In multiple localization files, there are no languages so there are no files saved. and inside the quest.ini [questdata] list is empty.
