### ISSUE TITLE
Where does the scenario go in 1.1.0a?

### ISSUE THREAD

**Issue by EtiCarasoft** [NPBruce/valkyrie#377]
Simple question made again, Where do the scenarios get saved in version 1.1.0a for test? Does it generate any file? Some thing that can be edited in text editor, for translating and more test?
I'm almost done with a full adventure that uses only MOM second edition material, but I made it first in Spanish (easier to create for me), now I want to translate it but i don't find the file.

**Comment by KasperJansen** [comment]
It is saved in C:\users\[user name]\appdata\roaming\valkyrie.

**Comment by NPBruce** [comment]
1.1 is the same place as 1.0, but quests saved in 1.1 won't work in 1.0.  Note that for MoM there is little reason to be using the 1.1.0a prerelease for scenario development (other than testing).  1.1.0b will be out some time soon with some new MoM features, but 1.0.1 is still the stable release.
