### ISSUE TITLE
Missing MoM tiles

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#38]
These tiles are not used in MoM and as such we are missing them.  Would be good to get a scan to add in low quality for now.

TILE_ALLEY_END_MAD20
TILE_FLEA_MARKET_MAD20
TILE_LIBRARY_MAD20

TILE_CAVE_1_MAD01
TILE_CAVE_2_MAD01
TILE_CHASM_MAD01
TILE_CORNER_HALLWAY_1_MAD01
TILE_FRONT_YARD_MAD01
TILE_HALLWAY_1_MAD01
TILE_LABORATORY_MAD01
TILE_SECRET_PASSAGE_MAD01

TILE_CAVE_3_MAD06
TILE_OBSERVATION_ROOM_MAD06
TILE_OPERATING_THEATER_MAD06

TILE_CAMPSITE_MAD09
TILE_CAVE_BEND_MAD09
TILE_OUTHOUSE_MAD09
TILE_PIGPEN_MAD09
TILE_RIVER_BEND_1_MAD09

The app also lists: TILE_SMALL_CHASM_MAD01, but I think this is a mistake and doesn't exist.

**Comment by NPBruce** [comment]
I have noticed that Supressed Memories states it includes 15 tiles, yet FA + CotW is 17 tiles (11+6).  Can anyone tell me what tiles are missing in SM?

**Comment by eorahil** [comment]
Hello. Sorry I'm new in GitHub world but I want to contribute. How should I commit? Create my own branch? fork the project? I'm used to work in SVN but not Git

**Comment by BruceLGL** [comment]
Typically you will create your own branch, do whatever you want to do, then raise a 'pull request' for me to accept your changes.

If it is all to hard and you are working on things like this issue, which is adding images you can just send changes to me, but if you are working on code it would be great if you could use pull requests.

Here is an overview:
https://gist.github.com/Chaser324/ce0505fbed06b947d962

That uses command line instructions, but sourcetree is a popular windows client you can use if you like.

**Comment by NPBruce** [comment]
PS: Please branch off/target the 'development' branch, it is where I put things together prior to merging to master.

**Comment by eorahil** [comment]
I want to contribute even coding, but everything is new for me, Git, Unity. so I planned to start with little tasks like this.

**Comment by eorahil** [comment]
Few questions:
- DDS editor? 
- Unity version to build and run the app?
- I think I must put the missing tiles in the ../ffg/.... Where the importer gets the tiles from que Steam App? or should I put it in other place because importer will overwrite it?

Thanks. I'm starting to understand all an I'ts a great job!

**Comment by NPBruce** [comment]
1: I use gimp (https://www.gimp.org/) with a plug in (http://registry.gimp.org/node/70), however you shouldn't need this anyway.  The DDS files are exported from RtL/MoM, none of the assets from Valkyrie use DDS (though they could).  I prefer all assets to be png.

2: I have Unity 5.4.0f3  Probably best to stick with a 5.4 version for now (https://unity3d.com/get-unity/download/archive?_ga=1.213481687.2115938008.1486551284), haven't checked what the changes are.  I am using the personal (free) licence.

3: The 'ffg' directory is as you suggest controlled by the importer and not version controlled, so they shouldn't go there.  Examples of extra tiles in D2E can be seen here:
https://github.com/NPBruce/valkyrie/blob/master/content/D2E/boxed/lotw/tiles.ini
https://github.com/NPBruce/valkyrie/blob/master/content/D2E/boxed/lotw/img/032A.png
The MoM tiles would go here:
https://github.com/NPBruce/valkyrie/blob/master/content/MoM/base/tiles.ini
https://github.com/NPBruce/valkyrie/blob/master/content/MoM/cotw/tiles.ini
https://github.com/NPBruce/valkyrie/blob/master/content/MoM/fa/tiles.ini
https://github.com/NPBruce/valkyrie/blob/master/content/MoM/mom1e/tiles.ini

**Comment by eorahil** [comment]
Ok I will use png files then.

After installing Unity. The build shows an error for the Ionic import. Looks like que library wasn't correctly imported to the project. 
Do you work only with the Unity editor or you use Visual Studio?

**Comment by NPBruce** [comment]
I use visual studio.  When I get a chance I will do a clean clone and check that the project builds correctly.  Can you tell me the exact error?

Note that for the tiles you can use the built version if you like, just edit the content.

**Comment by eorahil** [comment]
Assets/Scripts/Content/QuestLoader.cs(5,7): error CS0246: The type or namespace name `Ionic' could not be found. Are you missing a using directive or an assembly reference?

The problem can be that the assembly reference to the Iconic lib is in a gitignore file? (the project files that you don't commit to git)

**Comment by NPBruce** [comment]
Everything should be in assets/plugins.  May need to readd the plug in, I will test when I get a chance.

**Comment by eorahil** [comment]
These are the files in Assets/Plugins folder
- Ionic.Zip.Unity.XML
- Ionic.Zip.Unity.XML.meta
- Ionic.Zip.Unity.dll.mdb
- Ionic.Zip.Unity.dll.mdb.meta
- Ionic.Zip.Unity.dll.meta
- Ionic.Zip.Unity.pdb.meta

As soon as I open Unity, it removes the last 2 meta files because there isn't the nonMeta ones.
Shouldn't it be an Ionic.Zip.Unity.dll and Ionic.Zip.Unity.pdb files?

**Comment by NPBruce** [comment]
Good catch, added files now

**Comment by NPBruce** [comment]
Confirmed now works on the dev branch.  You once you have the open you will project open you will have to open the scene (assets/scenes/game.unity), then just press play.

**Comment by eorahil** [comment]
Now works perfectly. I'm in!!!

Last Night I found all missing tiles and I'm looking for a decent resolution images. I will have to take same photographs in order to get MAD20 tiles, for the rest I found midres images.
The TILE_LIBRARY_MAD20 exists, I supose it was included in the Beyond the Threshold expansion, others still missing.

**Comment by NPBruce** [comment]
I would prefer not too high res, to avoid unwanted copyright attention.  I have been using 72 dpi.  TILE_LIBRARY_MAD20 should be in the base set, I have all the MAD23 tiles.

**Comment by eorahil** [comment]
Yesterday I commited new tiles but didn't "pull request". I will try this night. 
But I think the png files are too big. I used the size and dpi from fgg dds ones, but d2e ones are 100/200 kb size and mines are 1/2 Mb. I will try to lower the sizes somehow. 
Also, for some tiles I used the original draws and didn't realise that there is no "spaces limit" lines.

**Comment by NPBruce** [comment]
In git a commit is local only, you have to 'push' to put it on the server.  Then a pull request is for someone else to look at and merge the branch.

You should be able to use jpg for MoM tiles, I can't for D2E because I need transparency.

**Comment by eorahil** [comment]
Sorry but I'm unable to push neither pull.
Commited locally but unable to pull, don't have permissions
created a branch missing_tiles but I could only create it locally. cant submit my branch.

**Comment by NPBruce** [comment]
You should be able to create a private repo for the branch rather than push to the main one and do a pull request from there.

To simplify things though I have made you a contributor to this repo which should give you permission to do either.

**Comment by eorahil** [comment]
Trying... one question. Should I fork this project first and make changes to my forked proyect and after that make pull requests for changes in my fork to be included in original one? or should I create local branches from development (ie. missing_tiles branch) and try to push mi new branch and after that pull request missing_tiles branch to be merged to development one?

**Comment by NPBruce** [comment]
The first way is how you should be able to submit changes to any project.  On this you should also be able to do the second now as I made you a contributor.  The first way is still clearer on who has done what, but as long as you don't change master/development directly I don't mind.

**Comment by eorahil** [comment]
Ok I forked. I prefer you to remove my contributor permissions to your branch. I'm too novice and I dont want to destroy accidentally your repository.
I prefer forking. I didn't it in first way because fork meant to me that I would create a different app based on yours and that is not my intention.
Pull request created, take a look, and a second look :D, it's my first pull request.

**Comment by NPBruce** [comment]
Pull request here:
https://github.com/NPBruce/valkyrie/pull/41

**Comment by NPBruce** [comment]
Fixed in development, waiting for release.

**Comment by NPBruce** [comment]
Released in 0.6.0
