### ISSUE TITLE
line break in text

### ISSUE THREAD

**Issue by EtiCarasoft** [NPBruce/valkyrie#385]
Sorry for such a simple issue. 
Is there any code for line break in text editor such as <i> for italic to create new lines? 
thanks

**Comment by eorahil** [comment]
Do you have multiline editableTextBoxes? we added it in the last builds.
What field are you trying to insert new line?

**Comment by NPBruce** [comment]
The stable release of valkyrie doesn't do multi line in the editor well.  I suggest editing your text in a text editor.  "\n" is used to insert a new line.

You can also use anything here:
https://docs.unity3d.com/Manual/StyledText.html

**Comment by EtiCarasoft** [comment]
Ok thanks, One more thing. 
I edit the txt with the text editor, the problem shows if i use a comma (,) it cuts the rest of the text, the solution i'm using is to change the commas to semicolon.

**Comment by eorahil** [comment]
texts will commas must have double quote " at the begining and at the end of the text
if your text is 
,one, two, three and four,
you must type
,"one, two, three and four",

if you want double quotes in your text you must write it twice so
,one, two, "three" and four,
should be
,"one, two, ""three"" and four",

you can also do the oposite, write in the valkyrie editor a commas separated text with double quoutes, then save and edit the file, you will see it as I told you.

**Comment by EtiCarasoft** [comment]
Perfect the text gets more visual an easier to read. Thanks
