### ISSUE TITLE
Custom Variables

### ISSUE THREAD

**Issue by LordPyrex** [NPBruce/valkyrie#386]
Hello NPBruce,
I had a question regarding variables and how to use custom ones. I've read the ValkyrieVars Wiki and I think I have an idea of how they work. I just didn't know if it was possible to write a custom variable and have Events interact like an incremental function. Or would this need to be written directly into the code of the scenario.
Thanks,
LP

**Comment by NPBruce** [comment]
This is the type of thing they are for.  Any variable starting with a letter is 'custom', just add a new variable and give it a name.  To increment use variable + 1 as an operation in an event.

**Comment by LordPyrex** [comment]
I guess I just don't understand where to initialize it. The image is broken on the Quest Wiki

**Comment by NPBruce** [comment]
https://github.com/NPBruce/valkyrie/wiki/ValkyrieVars
https://github.com/NPBruce/valkyrie/wiki/QuestIniEvent#conditions
https://github.com/NPBruce/valkyrie/wiki/QuestIniEvent#operations

"Vars do not need to be declared, all are initialised to 0."

The manual documentation section is much better than the editor section which has not been kept up to date.  Which image is broken, can you please provide a link?

**Comment by LordPyrex** [comment]
https://github.com/NPBruce/valkyrie/wiki/QuestEditorGuideEventVars
The picture under the Event Flags Selection

**Comment by NPBruce** [comment]
OK, care to help on #287?

**Comment by LordPyrex** [comment]
I can try to do that. I'll see what I can come up with and submit something your way.
