### ISSUE TITLE
Single investigator

### ISSUE THREAD

**Issue by KasperJansen** [NPBruce/valkyrie#387]
I have always wondered why the official MoM app does not allow playing with a single Investigator. Perhaps in Valkyrie this could be scenario dependent? If a scenario requires a minimum number of Investigators, then you cannot continue until you have selected at least that number. If the scenario doesn't specify this, the minimum is 1. (The same goes for the maximum number by the way. Why can't the maximum number of Investigators be determined by the scenario?)

**Comment by LordPyrex** [comment]
This is probably because even in the original 2 player game, when it was player vs keeper, the player always controlled 2 investigators. It probably has to do with calculations of difficulty when it comes to monsters, mythos events, and task completion in enough rounds.

**Comment by redwolf2** [comment]
You could use houserules and allow single investigator to do 4 actions.

**Comment by KasperJansen** [comment]
I understand. And of course you can bypass the minimum by selecting two investigators and playing with one. Still, I see no reason why minimum and maximum couldn't be determined by the scenario -- at least in Valkyrie.

**Comment by redwolf2** [comment]
I agree
