### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#39]
The quest editor documentation is a bit out of date and written with only D2E in mind.  It could use some love.
https://github.com/NPBruce/valkyrie/wiki/QuestGuide

**Comment by eorahil** [comment]
I'm on it.
* Creating a MoM guide.
* Translating both guides to spanish.

**Comment by NPBruce** [comment]
FYI I have updated this a lot, the manual section is now quite good and I have written a MoM tutorial.

**Comment by NPBruce** [comment]
This will never really be 'done' but I think the documentation is good enough for now, ongoing work required.
