### ISSUE TITLE
Include creators and translators names in the scenarios

### ISSUE THREAD

**Issue by eorahil** [NPBruce/valkyrie#391]
Everyone should have the chance to put his name/nickname in the scenario and when someone sees a scenario can see who created it and who translated some language.
I suggest to add a authors element in the quest properties screen. 
In the translation file, originalLanguage will have the creators names and in the foreign languages will be the translators names.
ie
//Lynch
quest.authors,NPBruce,Eorahil,,[GermanTranslator],,,,,,

**Comment by NPBruce** [comment]
I envisaged this being meta data on the quest hosting system that doesn't exist yet.  Either way something should be done.
