### ISSUE TITLE
Ability to reorganize events, tiles, tokens in the editor

### ISSUE THREAD

**Issue by Hobbeslionheart** [NPBruce/valkyrie#392]
The only way to have a sense of a timeline is to create everything in order which is most likely next to impossible unless you map everything out on paper beforehand. Allowing reorganizing of events, tiles, tokens will help.

Another option would be to set folders or groups of events, tiles, tokens so if you could contain tiles, tokens, events, puzzle by room or however you want to do, that would also help.

**Comment by NPBruce** [comment]
The plan is #342 which is to have the sorting by type as the default place they go but let you change which file any component is saved to, which allows for common files between quests and works to group components.  Still doesn't give you sorting in the editor, though you can rearrange them in the file if you want to.  Does that meet your need?

**Comment by Hobbeslionheart** [comment]
I would think that it would depend on how advanced you want/expect your users to be. I would imagine many individuals might just work in the editor alone and not mess with the file which would be my case. Another thing to consider is whether it would be convenient to resort in the file every time you edit the scenario especially when it's a work in progress which is when you need events, tiles, and tokens sorted and resorted.

**Comment by NPBruce** [comment]
To clarify, you can use this to group things without looking at the files at all.  I don't expect everyone to edit the files, but for some corner tasks I consider it OK.  For example in 1.1 you can have multiple quests/scenarios chained together (maybe each different layout is a different scenario and the first is just a launcher, or it can be used for campaigns).  This feature is only available by editing the files to create the link.

As an FYI I do my editing with a text editor, valkyrie and sourcetree (version control) all open at the same time.  I constantly swap between the text editor and valkyrie using sourcetree to validate an stage the changes on each swap and save/reload in valkyrie.  Some things (like creating 10 similar but different components) will always be easier in a text editor.

Another option that wouldn't be too hard is to have a function to sort alphabetically.  That way you can always name things like AThisEventIsEarly DThisHappensLater ZTheEnd.

**Comment by Hobbeslionheart** [comment]
The ability to sort alphabetically or numerically would probably be sufficient. Then if I label my first tile 01Roof, then all events, tokens, spawns, puzzles on or associated with that tile would have the prefix of 01 with other tiles having a different prefix.
