### ISSUE TITLE
Capability to examine items further in MoM.

### ISSUE THREAD

**Issue by cbusbird** [NPBruce/valkyrie#400]
Hopefully I haven't missed this capability existing somewhere already.  I'm working on a scenario and I would like to be able to have investigators further examine an item in their inventory.  In some of the FFG scenarios you gain an item (like the old journal) and are told that investigators can examine it further in the inventory screen.  The players are then able to view the item in further detail and get more info/story.

**Comment by LordPyrex** [comment]
#209 Deals with this same thing.

**Comment by cbusbird** [comment]
Thank you.  New to this and didn't do a good enough job of looking at previous issues.  I will attempt the work around you suggested in #209

**Comment by LordPyrex** [comment]
At least for now, maybe a later enhancement will take care of this.

**Comment by NPBruce** [comment]
I am closing this, feature development will be tracked in #209, I will get there but there is still a lot to do.
