### ISSUE TITLE
Add a way to check present heroes and classes in events.

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#409]

**Comment by eorahil** [comment]
I created valkyrie Vars for selected Heroes and Classes.
* There will be a variable #Class{className} equal to 1 for every selected class, IE #ClassKnight
* There will be a variable #Hero{heroNameUpperCamelCase} equal to 1 for every selected hero. IE #HeroGloriaGoldbert

pull requested the changes, take a look and proceed if it's a good solution.

**Comment by NPBruce** [comment]
Merged, documentation required.
