### ISSUE TITLE
Scenario saved with 1.1.0b cannot be loaded with 1.0.2

### ISSUE THREAD

**Issue by RudolphJ** [NPBruce/valkyrie#426]
I edited and saved a scenario with version 1.1.0b (as well as 1.1.0c) of valkyrie. 
When I want to load it in version 1.0.2 it does not appear in the list of available scenarios (neither "Start Scenario" nor "Scenario Editor").

[EditorScenario5.zip](https://github.com/NPBruce/valkyrie/files/998670/EditorScenario5.zip)
[output_log.txt](https://github.com/NPBruce/valkyrie/files/998671/output_log.txt)

**Comment by eorahil** [comment]
I opened and edited correctly with 1.1.0d version (the last development version). I will try to get the 1.0.2 version to know the reason it doesn't appear in the list.

**Comment by eorahil** [comment]
Ok. with 1.0.2 I can't see it. I will take a look..

**Comment by eorahil** [comment]
I think there is a bug in release 1.0.2 because it only accepts formats from 1 to 3 and should acept formats from 3 to 4. 
You can workarroud by editing quest.ini file and change the format field from 4 to 3. After this it will be visible.

**Comment by NPBruce** [comment]
This is not a bug. Please do not just change the version number. Information on format changes are here:

https://github.com/NPBruce/valkyrie/wiki/QuestFormat

1.1.0 should be released soon if you want to wait. Saving in the prerelease version results in many changes that are not back compatible and may also have bugs.

**Comment by RudolphJ** [comment]
Ok, I just realized, that although 1.1.0b is older than 1.0.2, it is in fact the "higher" version. Sorry about the confusion.

**Comment by NPBruce** [comment]
If it were up to me prereleases would have an entirely different page, but that isn't how github works unfortunately.  The link from the main wiki page will always get you the latest stable release.
