### ISSUE TITLE
How exactly does QItem works?

### ISSUE THREAD

**Issue by eorahil** [NPBruce/valkyrie#427]
I'm not sure how it works. It's like Monster Spawn where you can put a list of possible elements or a trait. 
In the middle of a game (play not edit), is there a way to know what item from the list were decided?

**Comment by NPBruce** [comment]
From a scenario developers PoV you can add the QItem like other quest components to place it on the board or next to the event (and soon use the text reference in an event).

Internally this is stored in game.quest.itemSelect[\<QItem Name\>].  This is determined at the start of the quest but can be changed with $restock ($restock - If set to 1 will cause all items to reroll a new random item, will then reset to 0 any open stores must be closed)

**Comment by eorahil** [comment]
Am perfect!! so I can show it when referencing the {q:questItem}. but in the HouseLynch Scenario there are 5 QItems:
```
[QItemStartLight]
itemname=ItemCommonAxe ItemCommonElderSignPendant ItemCommonFireExtinguisher ItemCommonKeroseneLantern ItemCommonSedatives ItemCommonShotgun ItemCommonWhiskey
starting=True
traits=lightsource
```
All 5 items has the same itemName list and changes the traits. But the starting items are none of the list. Is it an exclusion list or something like that?

**Comment by LordPyrex** [comment]
I just uploaded a Tutorial to the wiki on this

**Comment by NPBruce** [comment]
Yes in that context it is an exclusion, see here:
https://github.com/NPBruce/valkyrie/wiki/QuestIniQItem

**Comment by eorahil** [comment]
Ok. Thanks
