### ISSUE TITLE
Undo bug

### ISSUE THREAD

**Issue by LordPyrex** [NPBruce/valkyrie#429]
I've noticed that when you use the Undo button to back things up will render the Undone token unusable. This has happened with both explore and search events. As it is this can lead to being unable to complete scenarios.

**Comment by NPBruce** [comment]
I will look into it, it would be great if you can provide a save game of the issue.

**Comment by NPBruce** [comment]
Nevermind, I can reproduce it.

**Comment by LordPyrex** [comment]
Also found that after you Undo it halts any progression. Nothing can be interacted with, including saving.
