### ISSUE TITLE
Animation on phases

### ISSUE THREAD

**Issue by EtiCarasoft** [NPBruce/valkyrie#430]
Just for enhancement, I would recomend a screen animation between investigators and mythos phase.

**Comment by redwolf2** [comment]
Also add an option to disable it.

**Comment by BenRQ** [comment]
I have worked on this, and I have something working.
The result is quite good and add to the ambiance.

The 2 screens are fixed (no animation), and last for 3 seconds.
I don't think we really need a skip button, as 3 seconds is a very short time but feel free to try it out and tell me :)

Please note that there are no additional actions required by the players, the screens just come and go at the right time.

See screenshots below, feel free to comment on this, and ask for improvement.:

![image](https://user-images.githubusercontent.com/40794717/43218578-14bfe068-9045-11e8-83fa-f0f5d00c6d57.png)

![image](https://user-images.githubusercontent.com/40794717/43218590-1ddf37ac-9045-11e8-9d7c-2b61939545be.png)


Commit was done in my branch  mom_ui_update_clean, which already has a pull request.
I can't really start it from a new branch, as I'm working one files that have taken many other changes for ui improvement.

**Comment by BenRQ** [comment]
Hi @FASTNAVi , ok,  I will do that no problem.

**Comment by BenRQ** [comment]
Beta test version available with implementation of this issue:
https://github.com/BenRQ/valkyrie/releases/tag/release%2F2.1%2FBrynhildr_2.1.0b

Please close this issue, if you are happy with this fix.
