### ISSUE TITLE
Move portable code to Portable Class Library

### ISSUE THREAD

**Issue by redwolf2** [NPBruce/valkyrie#432]
There are many classes in the path `/unity/Assets/Scripts` that could be moved in a [PCL project](https://msdn.microsoft.com/en-us/library/gg597391(v=vs.100).aspx). This PCL project can be referenced in the unity project. This would be beneficial for extern tools like a text to speech translator or extern importer used in an installer or the approach to move to the Mono Game Engine https://github.com/NPBruce/valkyrie/issues/248 later on. It also restricts the use of streams over files and will encourage are more pure c# code base that can be used on different environments.
Maybe that is already planned here? https://github.com/NPBruce/valkyrie-libraries

**Comment by NPBruce** [comment]
I have already moved out the import functions, but the unity work flow is such that things that are changing a lot are easier to keep in scripts.  There is a good discussion here:

http://www.what-could-possibly-go-wrong.com/unity-and-dlls/

As more parts of Valkyrie become closer to 'final' I will move more of it into libraries.

**Comment by NPBruce** [comment]
PS: see here:
https://github.com/NPBruce/valkyrie/tree/master/libraries

**Comment by redwolf2** [comment]
Fair enough :)
