### ISSUE TITLE
Activation Bug

### ISSUE THREAD

**Issue by LordPyrex** [NPBruce/valkyrie#435]
I noticed while creating some activation commands that there is currently no way to change the unable button text as it's been replaced with the attribute buttons. Attached a screenshot below.
![activation](https://cloud.githubusercontent.com/assets/27811809/26133049/70b184be-3a72-11e7-93f1-d686bbca7c0a.png)

**Comment by NPBruce** [comment]
You can work around by editing \<sectionname\>.movebutton in the Localization file.

**Comment by LordPyrex** [comment]
Okay, I'll try that for now
