### ISSUE TITLE
Dunwich horror crash

### ISSUE THREAD

**Issue by niederman** [NPBruce/valkyrie#437]
When spawning a dunwich horror in the mansions side o' things, the evade button has no response and the following mythos phase, where the monster should have an action, Valkyrie crashes

**Comment by NPBruce** [comment]
Annoyingly the activations, evades and horror checks are only in Cult of Sentinel Hill, so I need to get them from there rather than base MoM data.

**Comment by NPBruce** [comment]
I have released placeholder data, full Dunwich Horror data will come in a later release (#438)
