### ISSUE TITLE
Custom Mythos without FFG event.

### ISSUE THREAD

**Issue by cbusbird** [NPBruce/valkyrie#439]
I have been creating some custom Mythos events and I have them to the point where they are working and happening when I want them to.  However, the custom Mythos events always have a FFG Mythos event happen first.  Is there a way to have only a custom Mythos event trigger during a Mythos phase without the FFG event?

**Comment by NPBruce** [comment]
Yep, just turn off the mythos level vars and the ffg event won't happen. When your don't have a custom event you can turn it back on.

**Comment by cbusbird** [comment]
I think you did it in FOHL, but I haven't been able to find the event.  Do you know which event starts that sequence?

**Comment by redwolf2** [comment]
Should be EventTimer1

**Comment by NPBruce** [comment]
Note that FoHL is pretty clunky because I didn't have the current var system when I wrote it, so it works but is tricky.

**Comment by cbusbird** [comment]
@NPBruce I see that, but your initial tip is all that I needed.  I just created events that trigger at at EndRound and StartRound to toggle the Intensity Mythos vars and this is working as intended.  I almost tried that before asking the question but every time I turned all of the Intensity vars off before the game would just exit.  I understand the reason why now :100:
