### ISSUE TITLE
What do monsters do when they can't attack?

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#44]
In MoM some monsters move, some do nothing, I think hounds are the only one with a random action.

We need to check the rest and note what they actually do.

**Comment by eorahil** [comment]
It is my theory, as soon as we get statistics we can confirm, but: 
* There are 3 monsters with MOVE_00 actions. Ghost, Hound of Tindalos and Hunting Horror. 
* I think after a monster cant move because of the text of his movement includes the "in range" or "in X spaces" text, there is a random roll between the MOVE_00 set and the MONSTER_COMMON_MOVE_0X where X is the standard spaces movement of this monster (every monster has a default number of spaces to move). There is too some WANDER monsters who moves towards an specific investigator instead of nearest one.

**Comment by NPBruce** [comment]
My very quick testing showed that (hounds aside) it was always the same result for a monster not random.  Could be wrong though.

**Comment by eorahil** [comment]
After some testing. In the first scenario faced hunting horror and even appeared a ghost, both has the MOVE_00 options. Every time I select "cant atack" it triggers the same MOVE_00 action. So I'm sure that after a monster cant atack, if if has a MOVE_00 action, it's triggered, allways. The hound has many MOVE_00 actions so I think a random one is triggered.
For the non MOVE_00 monsters, there triggers the MOVE_X to the nearest investigator. Some times "cant atack" doesn't trigger anything. In my test it was allways with a "the monster atack a investigator in his spsce" but I must confirm it.
The Shoggoth is a WANDER monster. his "not atack" action is "the monster moves X spaces to [location]" not nearest investigator. And the location is totally random. Even disapeared tiles.

So

- Hunting Horror moves 3 spaces.when cant atack triggers his MOVE_00 action.
- Witch moves 2 spaces. When cant atack moves 2 spaces to nearest investigator sometimes. Others nothing.
- Dark Druid moves 2 spaces. When cant atack moves 2 spaces to nearest investigator sometimes. Others nothing.
- Unique Dagon worshiper moves 2 spaces. When cant atack moves 2 spaces to nearest investigator sometimes. Others nothing.
- Star Spawn moves 1 spaces. When cant atack moves 1 space to nearest investigator sometimes. Others nothing.
- Ghost moves 2 spaces.when cant atack triggers his MOVE_00 action.
- Shoggoth moves 2 spaces. When cant atack triggers Wander movement. moves 2 spaces to [random location]
- Dark Young moves 1 space. When cant atack moves 1 space to nearest investigator sometimes. Others nothing.

**Comment by NPBruce** [comment]
Something else to think about here: do the conditional moves depend on if the activation is ranged? (or the wording of the movement in the first case, such that it may not move).

**Comment by NPBruce** [comment]
I've made some educated guesses based around the ideas that movement rate is standard and a monster will always move once.

Currently MONSTER_HOUND_OF_TINDALOS_MOVE_00a is the only supported hound move, I will make that a new issue.
