### ISSUE TITLE
Custom Images

### ISSUE THREAD

**Issue by LordPyrex** [NPBruce/valkyrie#445]
Is there a plan for the UI to support custom art? I didn't know if this was something that could be packaged with uploaded scenarios and placed in the appropriate directory with some kind of installer. I know that this seems more like something 2.0 than anything soon.

**Comment by redwolf2** [comment]
Have you checked out the lastest release with the latest scenarios? There are images in the intro.

**Comment by LordPyrex** [comment]
Yes, and they work for what's there, but they are all from existing scenarios. I was thinking more along the lines of custom art that could be added to the prologue or epilogue of the story being written.

**Comment by NPBruce** [comment]
Check Exotic Materials for an example with custom images.  Any UI element can use one, just add it to the directory and pick it in the editor (png and jpg supported).

**Comment by LordPyrex** [comment]
I will look for that, thank you! I hadn't realized that the capability was there. I will add the info into the Tutorial in progress.
