### ISSUE TITLE
Activation vars

### ISSUE THREAD

**Issue by cbusbird** [NPBruce/valkyrie#446]
I would like to set a var on a custom monster activation.  Is that possible?

**Comment by cbusbird** [comment]
or chain an event to a custom monster activation?  I would like one of my custom monster activations to summon some minion monsters.

**Comment by NPBruce** [comment]
Are we talking D2E or MoM?

**Comment by NPBruce** [comment]
OK so you want to add additional monsters in the monster phase, would they then activate in the same phase or not till next round?  I assume you only want to do this on a particular activation not any activation?  You can do something similar with a mythos event that triggers randomly and spawns another monster in the same space (or end round event if you don't want the new monster to activate).

**Comment by cbusbird** [comment]
Ideally I could set a var on a monster activation.  Then have an event that triggers at EndRound or StartRound that places the monsters.  It would go something like this.  

Activation:
CustomMonster chants a summoning spell, the ground rumbles but there doesn't seem to be any immediate danger.
assign summonvar,=,1

Event
trigger  StartRound
condition  summonvar,=,1
The earth rumbles again louder, this time cracking open.  Two Zombies crawl out of the crevice....triggers events that spawn two zombies
assign summonvar,=,0


Not a big deal but something I thought would be cool to weave into my story.

**Comment by NPBruce** [comment]
Another way to implement this is to force a monster activation based on a var.  So you can decide that this round monsters will spawn and force that activation.  I feel that this solution is more generically useful as you can turn activations on and off based on various conditions.  This will mean adding a var conditions section to the activation.

Does that sound OK?

**Comment by cbusbird** [comment]
Yes, that's great.  I've been thinking the conditions and vars for activations would allow you to basically set an order for activations.  Which would be cool as well.  For Example the custom monster I'm working on now I want to be a big target, like we have to kill this thing now or we are all going to die (no running).  I can push the game in that direction by making activations increase in intenstity.  You could also do the opposite.

**Comment by NPBruce** [comment]
One hack work around would be to have a number of custom monsters and silently remove and readd the monster with different activations.

**Comment by cbusbird** [comment]
Ok, got it.

Another question.  Pretty sure you must have done this in FoHL with the maniacs but how do I assign a var for when a custom monster is defeated, or better yet would be to trigger an event.

**Comment by NPBruce** [comment]
https://github.com/NPBruce/valkyrie/wiki/EventTriggers

**Comment by cbusbird** [comment]
sorry forgot about that.
