### ISSUE TITLE
No longer able to access scenario (MoM)

### ISSUE THREAD

**Issue by Ocirus** [NPBruce/valkyrie#449]
Have been working on a custom scenario for days. Went to change one thing (added Beast, Humanoid, and Spirit to the REQ section of a spawn, since I couldn't get attack prompts to work) and I can no longer access the scenario via the scenario editor OR by starting the scenario. I was working from a single save. Searched the issue logs and couldn't find anything that helped.

**Comment by NPBruce** [comment]
Can you please start my telling me:

 - Version you are running
- OS you are using (Windows/MacOS/Linux).
 - Attach a log after going to the quest editor selection page (Valkyrie_Data/output_log.txt on Windows).

Have a look in %AppData%\Valkyrie (on Windows) and look for your scenario there.  If there is anything there that isn't showing up in Valkyrie please zip it and attach it here.

**Comment by Ocirus** [comment]
Thanks for pointing me toward the file directory. I was able to save my scenario by going into the 1 monster I added the Humanoid, Beast, Spirit traits to and simply delete that line. I must have done something wrong when trying to add investigator attack support to the monster (for choosing your attack type against an enemy since it doesn't show anything now. I'll look into it further.)

In terms of the bug: Looks like I'm running 1.0.2, and I'm on Windows. Everything was running with zero problems until very very late last night/this morning.

Here's the output log. The last activity I did was:
-Open Valkyrie, select MoM
-Chose Scenario Editor, then my scenario (the broken copy) - this returns me to the main MoM menu
-Choose Start Scenario, then my scenario (again, the broken copy) - this, again, returned me to the main MoM menu
-Chose Scenario Editor, then my broken scenario (which returned to the main MoM menu).

As I said I have since fixed my error and was able to recover my file, from entering the Spawn file and manually removing the Traits section. Sorry for any bother, but thank you SO much for pointing me in the right direction!
[output_log.txt](https://github.com/NPBruce/valkyrie/files/1016329/output_log.txt)

**Comment by NPBruce** [comment]
I couldn't reproduce this bug. Can you please attach your scenario so I can check the same thing?

Also note that only one of beast/humanoid/spirit should be used.

**Comment by Ocirus** [comment]
Sure. Just zip the "EditorScenario" folder contents and attach the zip?

**Comment by NPBruce** [comment]
Yep. Ideally put it back how it was when it didn't work.

**Comment by Ocirus** [comment]
No problem. I've attached both a working and not working zip file - the only difference is the broken file having the added Humanoid, Beast, and Spirit traits added to a spawn. The zip titled "EditorScenario1" is a working version, while "EditorScenario2" is the broken one. Hopefully the issue can, at least, be reproduced with the file.
[EditorScenario1.zip](https://github.com/NPBruce/valkyrie/files/1016565/EditorScenario1.zip)
[EditorScenario2.zip](https://github.com/NPBruce/valkyrie/files/1016566/EditorScenario2.zip)

**Comment by NPBruce** [comment]
OK a few things:

1: The Humanoid, Beast, and Spirit (and soon horror) traits are used to determine how attacks against them work.  Only one should be used for any monster.

2: The issue is that even though you have a custom monster with all of these traits you are attempting to use a trait match to get that monster, which isn't supported for custom monsters.  Added as feature (#451).

3: Unable to select a monster makes the scenario unplayable, but currently we don't handle editing such invalid scenarios (improvement #204).

3: I don't think this is what you want to do anyway. This:

```[SpawnSPAWNGreyZombie]
xposition=-29.68013
yposition=23.49241
buttons=1
event1=
add=TokenDOORDining
remove=TokenPERSONGreyMan TokenDOOR_DiningVER2
audio=AudioCreatureMoves
monster=CustomMonsterZombieDoor
traits=humanoid beast spirit
```

Will try to find any monster that has humanoid, beast and spirit traits that is NOT CustomMonsterZombieDoor.  I think you want to remove all traits and just specify the monster you are after.
