### ISSUE TITLE
Update all old UI elements to the new system

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#457]
It is faster and cleaner, but there is a lot of old stuff.  Will change things as I get to them.

**Comment by LordPyrex** [comment]
Is there anything I need to tweak on the Wiki with the upcoming changes?

**Comment by NPBruce** [comment]
This will affect the tutorials a bit and the quest editor section a lot.  I'll release 1.2.0a soon so you can see.

**Comment by NPBruce** [comment]
PS: This specific issue relates to an internal system change, which won't be any different to the users (other than being quicker), but there have been many user facing changes to the editor in 1.2.

**Comment by LordPyrex** [comment]
Okay, thanks for the info. I'll watch for the release.

**Comment by NPBruce** [comment]
1.2.0a released: https://github.com/NPBruce/valkyrie/releases/tag/prerelease%2F1.2%2Fv1.2.0a

**Comment by LordPyrex** [comment]
Wow, that's close to a complete overhaul! LOL. Nice work though

**Comment by cbusbird** [comment]
I really like how the Events have the variables and next events on the same page.  Also being able to click on the next events to load them is really convenient.  It would be great if that could be done for tokens as well.

**Comment by NPBruce** [comment]
What do you mean by for tokens? Tokens and events use the same dialogue.

**Comment by LordPyrex** [comment]
I'm pretty sure he meant the display icon that is used during spawning.
Having access to that as a token to display on the board as a component.

**Comment by cbusbird** [comment]
I mean that in a given event you can click on an event (in the list of next events) and this click will then load that next event for editing.  Meaning that when working in the editor on chained events it is much easier to navigate between all the events.  It would be cool if this applied to the tokens as well.  By that I mean that in a given event if you click on a token name (in the add or remove components section of the event) that the token editing screen would load.  

Just makes navigating between components/events that you are working on in the editor much easier.  At least to my knowledge being able to click on the next events (and load that event for editing) is a new feature in 1.2.0a.

I think it's great and helps speed editing up, I just think it would even better if the idea was applied to other parts of the editor as well.

**Comment by NPBruce** [comment]
The feature was partly in 1.1, but works better now.  I will add it to add/remove components (which includes UI, Tokens, Tile, Spawn, etc).

**Comment by NPBruce** [comment]
#468
