### ISSUE TITLE
Sample Audio before committing to it

### ISSUE THREAD

**Issue by LordPyrex** [NPBruce/valkyrie#464]
With the new menu is it possible to allow a  sound effect to be sampled before selecting it so you don't have to keep reopening the window?

**Comment by NPBruce** [comment]
I can look into it.  FYI what I do is just use content/MoM/ffg/audio and pick the file I want first.

**Comment by LordPyrex** [comment]
That makes sense. I never thought about just sampling the audio from the directory.
