### ISSUE TITLE
Monster icons as token type.

### ISSUE THREAD

**Issue by cbusbird** [NPBruce/valkyrie#467]
I've got a couple of ideas that I would like to be able to implement in my scenario.  To do so I would need monster icons available as token types.

This might sound a little crazy at first but I think it opens some potential for new game mechanics.

You could have investigators interact with a monster before it "spawns".

I've also got another idea for my scenario that I would rather not divulge at this time that would utilize this.

I'm able to do a workaround currently but what I'm trying to accomplish would come off much more smoothly to someone playing the game if monster icons were available as token types.

I could be completely wrong here but it also seems like adding this feature wouldn't require a ton of changes.

**Comment by redwolf2** [comment]
The scenario Exotic Material already have something similar. Instead of a monster token, it uses an interact token. But I agree, that is a valid suggestion and not crazy. The original app also has that mechanic in the scenario Rising Tide, where a monster token is used as a NPC.

**Comment by cbusbird** [comment]
I want to try to incorporate some sanity meta-game effects.  Kinda like the way Eternal Darkness did on the Gamecube.  If you never played that game, there are some sanity effects meant to scare the player.  Like a fake fly would appear on the screen making you think that there was a fly on the TV, or it would make it seem like the game turned the volume on your TV down and a lot of other little things like that.  

I thought it would be cool to pysch the players out by having a "fake out" mythos event.  Something like "spawn 6 zombies in your space" then the next event would be "you come to senses and the realize the zombies aren't really there".

Being able to use monsters as tokens would make it possible to do this without actually spawning a monster.  

I could accomplish the same thing if there was a way to remove an active spawn (is there)?
But I would rather do it in one "fake out" event then to have six separate spawn events.  Seems like having to go through a bunch of events would ruin the effect of the "fake out"

Anyway, certainly not necessary for my scenario but I think it would be fun to try out.

**Comment by cbusbird** [comment]
Also I did know about the method that Exotic Materials uses but I don't think in this case that displaying six Interact tokens would have the same effect.

**Comment by cbusbird** [comment]
I want Zombies!

**Comment by LordPyrex** [comment]
You can create a series of 'Spawns' in order from 1-6 and they will appear in their locations one at a time. Then just create a 'Next Event' pointing to an event that does a 'Remove Component' for the spawns

**Comment by cbusbird** [comment]
Ok thanks, I didn't realize you could remove a Spawn like that.  It still would be much cooler to accomplish it with one event and adding 6 tokens vs chaining 6 spawn events.

**Comment by redwolf2** [comment]
When you add 6 zombies for a dramatic effect you should also consider gameplay and playability. IMO no one wants to cram around and add figures to the board, just to remove them in the next event. In your example, it would be better to do it in the text dialog and explain what happens.
If the zombies just stay for some rounds before beeing removed, thats a different story.

**Comment by cbusbird** [comment]
You do have a point there but I think telling someone to get 6 Zombies at once is much better than telling someone to get 1 Zombie 6 different times.  Plus I still need the monster icons available as tokens for your option to work.

**Comment by NPBruce** [comment]
1: adding the tokens is easy, will do.

2: As mentioned you can remove spawns, but be careful as this was implemented for monsters groups not individuals, so this will either remove any zombie (maybe not *the* zombie) or all zombies, can't tell you which on the top of my head.

3: you can't add more than 1 real monster at once because of the unique tokens.  You can do it if you don't specify a location by having 6 spawns with no text and then one event that describes where to put them (ie: in x investigator space). Note that the token approach will also have the unique token issue.

4: I agree that asking player's to add and immediately remove monsters is annoying.

5: not planning ui altering effects.

**Comment by cbusbird** [comment]
I love how the token type selection screen looks now.  Selecting the image instead of component name is awesome.  Thanks for adding the monster icons!
