### ISSUE TITLE
Var Creation issue in 1.2.0a

### ISSUE THREAD

**Issue by cbusbird** [NPBruce/valkyrie#471]
I've had this happen twice now so I figured I would document and post about it, but it is by no means a big deal.  

While editing an event I went to add a condition for the event.  I created a new variable and created the condition  InspectStone,==,0

I then clicked on the assign var (+) button (same event) and attempted to set the same var InspectStone,=,1 However, the new var InspectStone was not on list of available vars to choose from. 
I also tried saving the game and then trying to add the assignment again but still got the same result, the var wasn't listed on the page of available vars.  

I have included 3 screenshots to illustrate what happened, on screenshots 2 & 3 you can see that InspectStone is not on the list of available vars but you can see it listed in the condition section of the event behind the var selection screen.

I have done this same sequence of editing probably a couple dozen times and have not had issues until 1.2.0a.  I said earlier that this has happened twice now, but I have definitely done the same thing in 1.2.0a and not had the problem.

For the most recent instance of the issue (documented above) all I had to do was click to another event and then click back to the event I had the issue on and I was able to add the variable assignment as expected.

The first time it happened I had some more trouble and even exiting and reopening the editor did not get the new var to show up on the list of vars.  In this case I just removed the troublesome var and created a different var with a similar name and moved on.   

![varissue1](https://cloud.githubusercontent.com/assets/28448698/26478377/d44d7540-4199-11e7-83fd-bb66dd735764.jpg)

![varissue2](https://cloud.githubusercontent.com/assets/28448698/26478383/e78b90e2-4199-11e7-9519-cd165110a891.jpg)

![varissue3](https://cloud.githubusercontent.com/assets/28448698/26478386/ea76f3d2-4199-11e7-9929-d8620ca761d9.jpg)

Scenario files
[EditorScenario1.zip](https://github.com/NPBruce/valkyrie/files/1030666/EditorScenario1.zip)

Output.log
[output_log.txt](https://github.com/NPBruce/valkyrie/files/1030669/output_log.txt)

**Comment by NPBruce** [comment]
I'm not having any luck reproducing this problem, nor could I find the issue in the code.  FYI you can just add a new one with the same name, this will also work.

**Comment by cbusbird** [comment]
After posting this I had another small issue related to this come up.  The event in question InspectGrotesqueStone2 is called by InspectGrotesqueStone1.  For some reason it wasn't working when I was testing it.  I had to go back into the editor and remove InspectGrotesqueStone2 as a next event for InspectGrotesqueStone1 and then re-add InspectGrotesqueStone2 to get it to work.  Again not a huge a deal but a little buggy, seems like it may have more to do with the event then the var.

I also created the event InspectGrotesqueStone2 by clicking on the (+) next event button and selecting NEW EVENT.  This is a little different method of creating a new event that wasn't available in earlier versions.  Not sure if it's related or not but thought it was worth mentioning.

**Comment by cbusbird** [comment]
I keep running into this bug and just end up wasting time trying to work around it.  It definitely starts when I create a var and then go to the var selection screen and it is not there.  Again, this doesn't happen most of the time, just sometimes.  

Anyway, when this happens something gets screwy with the event that I had issues with creating the var on.  

The latest issue is that the event in question Remove_Earl triggers but the text won't display.  I can tell the event goes off because the camera moves and the token is removed, but the text box isn't displayed.  

![valkyriebug](https://user-images.githubusercontent.com/28448698/26849611-efe8aa94-4ad2-11e7-8ca6-5224064b612b.gif)

![valkyriebug](https://user-images.githubusercontent.com/28448698/26849611-efe8aa94-4ad2-11e7-8ca6-5224064b612b.gif)

From past experience I know that if I delete and recreate the event I should be able to get past the bug.  However this is at least the sixth time I have run into it and this particular event is called by about 5 other events and re-doing the work on stuff like that is really frustrating.

**Comment by cbusbird** [comment]
I just noticed the event has the display=false
How does this get added?  I'm betting that removing it will fix the text issue, but why is it there?

[EventRemove_Earl]
xposition=14.89642
yposition=-3.538008
display=false
buttons=0
remove=TokenEarlSawyer
operations=EarlSawyer,=,0
conditions=EarlSawyer,==,1

**Comment by cbusbird** [comment]
![valkyriebug1](https://user-images.githubusercontent.com/28448698/26850342-28020dce-4ad5-11e7-907c-04348fbdef64.PNG)
![valkyriebug2](https://user-images.githubusercontent.com/28448698/26850345-297efa7c-4ad5-11e7-8b9d-588819f4bef0.PNG)

**Comment by cbusbird** [comment]
Relevant text from Localization.English.txt

EventRemove_Earl.text,Remove the white man token from the board.

**Comment by NPBruce** [comment]
It is added on new events and should be removed when you add text.  It is readded if you delete the text.  Editing the text should also make it go away.  I still don't know what is going on, but I'm guessing something is getting out of place internally prior to these issues which is the root cause.  Thanks for the additional information, I will investigate how hidden may have been not removed or incorrectly added.

**Comment by cbusbird** [comment]
Great, I really appreciate you looking into it.  FYI I have attempted to delete the text, save, then re-add it but it didn't make a difference.

**Comment by cbusbird** [comment]
Deleting the display=false from the events.ini manually did fix it.

**Comment by cbusbird** [comment]
more info:  I've had this happen on a couple more events that didn't have vars at all.  So maybe the var issue is just a result of the event being screwed up, or not related.  Anyway seems like when an event gets screwy it has the display=false attribute.  If I go into the event and edit it (in this case added Continue button and remove component) I then would save.  If I would navigate to a completely different event and then back again the changes still show.  But if I exit the scenario editor session and go back in those changes are removed.  weird.  anyway I have already fixed these events manually by removing the display=false from events.ini.  Next time I see it I'll backup the scenario with the event still broken so you can test it if you want.

**Comment by NPBruce** [comment]
Thanks for the additional information, hopefully I will work it out.

**Comment by cbusbird** [comment]
I'm running 1.3.0a, have been for a few days now.

I don't know what's going on.  Maybe it's just something screwed up with my scenario.  I got the screenshot below today while doing some testing.  I assume this is a Store from Descent but I'm not sure how it was called in my MoM scenario.  I had been having trouble with this token->event chain working and it was being glitchy.  By that I mean that I created a token and the event chain (at least very close to perfect), saved it then started the scenario to test.  Only part of it worked, like the token was placed but clicking on it shows no next event just a cancel button.  I think, I probably made a mistake and go back into the editor to fix it.  I pull up the token and event and everything looks like it should.  So I remove the next event and re-add it again.  I load up the scenario to test and it works as it should, I've had this happen before, no biggie.   Then later, after doing some work on other parts of the scenario I tried token->events again and got this:

![wtf](https://user-images.githubusercontent.com/28448698/27017707-727460e2-4ef8-11e7-9edb-f368291820e4.jpg)

It should work like this.  TokenSearchBedroomB -> EventSearch_BedroomB -> Search_BedroomB2

When I got the above "Descent Store" it went like this: 
TokenSearchBedroomB -> EventSearch_BedroomB -> Descent Store

[TokenSearch_BedroomB]
xposition=-3.948258
yposition=2.882144
buttons=1
event1=EventSearch_BedroomB
type=TokenSearch

[EventSearch_BedroomB]
buttons=1
event1=EventSearch_BedroomB2
quota=3

[EventSearch_BedroomB2]
buttons=1
event1=
add=QItemMedicalTextbook QItemElderWard
remove=TokenSearch_BedroomB

[EditorScenario1.zip](https://github.com/NPBruce/valkyrie/files/1067018/EditorScenario1.zip)


I have been able to reproduce this at least 3 times.  I believe that it will do the same for you if you load up the scenario. Here is where the token is located.

![token](https://user-images.githubusercontent.com/28448698/27018210-87642d58-4efc-11e7-90a1-aa470f6d37c4.jpg)


I don't know what is going on and it may just be something with my scenario or setup but I've spent close to 80 hours using the editor now and these problems just seem to be getting worse.  I literally save twice now every time I change something.  I'm seeing issues with changes saving but haven't been able to narrow down a cause or pattern.  It just takes too much time to report every problem I have, so I'm only posting about the really frustrating ones that are reproducible.  I have no clue whether all the different issues in this thread are related or not.  Sorry, I know that's a lot.

**Comment by NPBruce** [comment]
> add=QItemMedicalTextbook QItemElderWard

This is the problem, you are adding multiple QItems.  If you add more than 1 it treats them as a store listing.  For MoM it doesn't make sense to add more than one at a time (can only display 1).  If you want to add items to the inventory silently for some reason you can have events with no text chained together.

**Comment by cbusbird** [comment]
I think it would be cool to be able to have two QItems displayed.  The 2nd could go on the other side of the  text box.  I assumed it had to do with the issues I've been having but that makes sense.

**Comment by NPBruce** [comment]
Then it might get in the way on the monster icons.  I prefer to keep this limit in place.

**Comment by NPBruce** [comment]
Haven't seen original issue in a while, reopen if it occurs again.
