### ISSUE TITLE
Difficulty values?

### ISSUE THREAD

**Issue by LordPyrex** [NPBruce/valkyrie#478]
I was trying out some of the new options in 1.2 to see where I need to add things. Would the difficulty value be better as a 1-5 selection than a 0-1? You could still use the 2.5 stars instead of .5 . Or I can just add that to the Quest screen wiki that I was putting together.

**Comment by NPBruce** [comment]
I wanted it to be generic, so that you could display as out of 10 or stars or something else.  This also makes it clear that you can do finer fractions if you like.

**Comment by LordPyrex** [comment]
Okay, I'll add in something that the value is reflected via percentage.
