### ISSUE TITLE
1.3.0 Changelog

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#479]
1.3.0:
# Major Changes:
Players:
* Added initial Portuguese support
* Fixed issues with text not displaying correctly
* MoM: Fixed duplicate monsters lost when loading save

Developers:
* Right click in editor to select components
* Test button added to editor

# Other Changes:
* Moved import into appdata
* Changed editor new/copy dir
* Fixed long logs not displaying
* Fixed music volume not applied until restart
* Fixed title music still playing after loading game
* Fixed crash on missing quest localization
* QItems can now be removed in Events
* Conditions no longer available in Tokens
* Fixed event text cut off at some resolutions
* D2E: Fixed tile 20B alignment
* D2E: Fixed random numbers in perils
* MoM: Fixed duplicate event on inspection
* MoM: Fixed item text space in inventory
* MoM: Conversion kit split into monsters/tiles/investigators
* MoM: Fixed hunting horror horror check

**Comment by redwolf2** [comment]
Log file might be moved, too

**Comment by NPBruce** [comment]
This is a list of changes made rather than things that want to be done, which should be new issues.  Unfortunately moving the log doesn't seem possible with unity.

**Comment by NPBruce** [comment]
1.3.0a:
Moved import into appdata
Changed editor new/copy dir
Added Portuguese translations
right click in editor to select components
MoM: Fixed duplicate event on inspection
MoM: Fixed item text space in inventory

**Comment by NPBruce** [comment]
1.3.0b:
* QItems can be removed in Events
* Conditions no longer available in Tokens
* Test button added to editor

**Comment by NPBruce** [comment]
1.3.0c:
* MoM: Fixed conversion kit title mistake

**Comment by NPBruce** [comment]
1.3.0c is up:
https://github.com/NPBruce/valkyrie/releases

This is the RC for 1.3.0, would be great if others could test it.

**Comment by redwolf2** [comment]
I tested it on Windows. No problem so far.

**Comment by NPBruce** [comment]
1.3.0d
* MoM: Added german CK translations
