### ISSUE TITLE
Add all MoM Mythos events

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#48]
Currently I have just added one event, need to go through and add others.

**Comment by eorahil** [comment]
Analysing Localization.txt file. There is 2 mythos events types
- **MYTHOS_EVENT_X_01 + MYTHOS_EVENT_X_02**: MYTHOS_EVENT_X_01 describes what player will be affected by the event. There should be a dialog box bethween COMMON_MYTHOS_EVENT_RESOLVE or COMMON_MYTHOS_EVENT_NO_TARGET. If resolve is selected there will be MYTHOS_EVENT_X_02.
- MYTHOS_EVENT_X + MYTHOS_EVENT_X_ALT: Events targeting a random player selected by the app. like "Bob Jenkins feel pain...".

These events resolution allways are a dice roll, a sanity or stamina loss, or new status. Never triggers a monster appearance, never triggers a tile appears/disapears. So we only need the text itsself.

Souldn't it be better to import directly reading from the Localization.txt MYTHOS events without the mythos.ini file?

I'm figuring out a Quest.ini file with a [Mythos] tag like that:
>[MythosPool]
>pool=[ffg:MYTHOS_EVENT_ACTION_HERO_ROLL] [ffg:MYTHOS_EVENT_ALONE_WITH_YOUR_THOUGHTS] [this:OWN_MYTHOS_EVENT_FOR_POOL] [ffg:MYTHOS_EVENT_ANCIENT_KNOWLEDGE]

* Note there is ffg: mythos ffg events and this: mythos events. ffg should get reading from Localization.txt and this: should get reading from own scenario (locali<ation tag, see the Multilanguage Isuue)

Appart from this random mythos pool, there should be fixed mythos events, defined in quest.ini, an event concept which fits with Valkyrie Event concept, triggered in certain mythos phase turns (depending on number of players) (IE: A monster appears in turn 5 with 5 investigators, but will appear in turn 10 with 3 investigators).
If a fixed mythos event triggers, a random mythos event won't be triggered.

**Comment by NPBruce** [comment]
Souldn't it be better to import directly reading from the Localization.txt MYTHOS events without the mythos.ini file?

I don't like this for two reasons:

1: It means that we are relying on consistent non-changing structure from FFG.  There are a LOT of typos in tag names and file names and such, doing it manually (with a helper export that I use) means I can fix these mistakes, and handle strange corner cases.  I do have a script to help me set this up (check out ExtractDataTool).

2: In theory Valkyrie should work without any FFG data if you create your own game data (I model I am working to).

I agree in general with adding to a pool and fixed events, still working on details.

**Comment by NPBruce** [comment]
Some further consideration:

1: Thinking more I really don't like FFG tags in scenarios/quests, because we can't control this.  Needs to be:

```
pool=HeroRoll AloneWithYourThoughts CustomMythos
```

2: If we are having a [Pool] then we don't need to use a space separated list, you can just do:

[MythosPool]
HeroRoll
AloneWithYourThoughts
AlwaysMoneyInTheSnackShack
CustomMythos

3: Many mythos depend on things (ie: is the snack stack currently displayed?).  This can't be on all the time, even if your map will eventually have this.  We have two options:

A: Have a set of conditions on a Mythos such as if a specific tileside is visible.  There could be a lot of different conditions, and there are other corner cases such as if the tile is visable but not accessible.  Also, perhaps in the snack stand case (for example) this should only happen on the turn it is revealed in the hope that an investigator is still nearby?

B: Add a mythos trigger to the existing event system.  This is my prefered option.

How this might work:

```
; Note: This example does not need a [MythosPool]

; Event can be called anything
[EventMythos]
; Using descent notation instead of mythos because it is already there
; and I want this to work for both.
trigger=#perilminor
event1=EventStand EventAlone EventMyCustom
button1=
randomevents=true

; Just a standard event (can name EventMythosStand if you like)
[EventStand]
; This event falls through and starts the included content event
event1=PerilAlwaysMoneyInTheSnackShack01
button1=
; flags required to be in pool
flags=notround3 standvis

[EventAlone]
event1=PerilAloneWithYourThoughts01
button1=
flags=notround3

[EventMyCustom]
text="I can do anything I like here (could also be a monster event)"
flags=round3
```

You could also do this (which I like better):

```
[EventMythos]
trigger=#perilminor
event1=EventRound3Mythos EventPool
button1=EventStand

[EventPool]
event1=EventStand EventAlone
button1=
randomevents=true

[EventStand]
event1=PerilAlwaysMoneyInTheSnackShack01
button1=
flags=standvis

[EventAlone]
event1=PerilAloneWithYourThoughts01
button1=

[EventRound3Mythos]
text="I can do anything I like here (could also be a monster event)"
flags=round3
```

**Comment by eorahil** [comment]
Ok. Agree with all.

**Comment by NPBruce** [comment]
Re-rethinking this:

I want to create a standard 'peril' event which is triggered as mythos and includes ALL mythos events as random options.

Then add flags to all mythos events so that you can turn them on/off in groups.  You can still create your own mythos by turning all the standard groups off.

The only tricky bits are:

1: Defining the mythos flags.

2: Assigning flags to events.

For 1 it has to be good up front, as this will be written into the scenario and is hard to change after the fact.  I am considering the following:

All mythos will be one of these:

mythosFlavor - Events that do not have any game effect
mythosMinor - Events that do not have a large impact
mythosMajor - Events that have a large impact
mythosDeadly - Events that will mess you up

You can turn any of these groups on/off to control the difficulty and scenario progression.  A lot of events have only these flags, but some events may also have:

mythosIndoors - Events that affect investigators indoors
mythosOutdoors - Events that affect investigators outdoors

Then by type of room:
mythosHallway - Events that happen to investigators in a hallway
mythosStreet - Events that happen to investigators in a street or alley
mythosGrave - Events that happen to investigators in a crypt, graveyard or morgue
mythosLibrary - Events that happen to investigators in a library
mythosKitchen - Events that happen to investigators in a kitchen
...

Then there are special cases that may have a scenario balancing effect.  Not sure if these should be in the pool at all:

mythosLoseClues - Event that can cause investigators to discard clues
mythosLoseItems - Event that can cause investigators to discard common items
...

I am after two things at this stage:

1: Does this system sound good?  What would you change?

2: How would you decide what level a mythos event should be assigned to?

**Comment by eorahil** [comment]
I like the the system. I think we need fixed mithos events too. Events in concrete turn order, but depending on number of players, in order to balance the game. The X monster appearance should be delayed to turn Y if there is only 2 investigators, for example.
The level of a myhos should be based on the potential lost, without looking at the dificulty. Example: a Strenght:1 roll losing 3 stamina if fails is dangerer than a Strenght:3 roll losing 1 stamina.
I supose the deadly events will be always in a concrete turn, mostly based on the scenario story itself.

**Comment by NPBruce** [comment]
You can still do round specific events by just turning all the standard events off and adding your own.  You own events can also be depending on investigator count, that is already there.

The idea of mythos rankings is simple enough, but when you add tests to avoid, tests to negate, modifiers for tests, face up/down damage/horror, turning existing cards face up, conditions and other effects it becomes hard to objectively rank them.  I might just do a quick pass and have them subject to review.

My idea with deadly events is that you turn them on at the end to force the investigators to finish or lose (you aren't going to survive a deadly every round for long).  Having said that it would be entirely up to the scenario how they are used.

**Comment by NPBruce** [comment]
All the mythos is now added and this is a classification job, so I'm closing this and creating a new ticket for that (#82)
