### ISSUE TITLE
#heroes var seems to be initialized wrong

### ISSUE THREAD

**Issue by DelphiDie** [NPBruce/valkyrie#481]
I´m currently trying to create a Descent campaign with 1.2.0. 

After starting the first quest, the game seems to initialize the var #heroes wrong. It does not matter how many heroes I select, they are always initialized as 0.

![heroes](https://cloud.githubusercontent.com/assets/26790002/26546817/2e7301b4-446c-11e7-9a03-13e82f67f765.jpg)

**Comment by NPBruce** [comment]
Appears to be a problem on changing quest, it is correct on the first quest but not after a change, does this match what you are seeing?

**Comment by NPBruce** [comment]
A work around for now would be%cheroes = #heroes in the first quest, then use %cheroes.

**Comment by DelphiDie** [comment]
Hi Bruce, yes it seems to happen while the quest is changing. Thanks for the workaround.

**Comment by NPBruce** [comment]
The workaround works for me, so I am not sure why it doesn't for you.  I will release 1.2.1 with a fix anyway.
