### ISSUE TITLE
New UI components panel Issues

### ISSUE THREAD

**Issue by eorahil** [NPBruce/valkyrie#483]
* {NEW XX} Buttons doesn't work in foreign languages because use fixed english words to trigger. Should use keys.
* In foreign languages, Traits list are duplicated because new elements use english words instead of its keys and each trait appears whice.

**Comment by NPBruce** [comment]
To clarify, the I think the issue is that {NEW text isn't translated, but still works, is that correct, or do they not work at all? (unable to test right now)
