### ISSUE TITLE
Request for test mode flag added to scenario page to skip selecting investigators and so on

### ISSUE THREAD

**Issue by NicolaZee** [NPBruce/valkyrie#487]
I don't know if this enhancement has been asked for and sorry for being a nuisance.

Is it possible to have a checkbox added to the Scenario page for MoM called Test Mode?

If it's ticked, the page describing the scenario is skipped and the first two investigators are automatically selected.

This would make testing quicker as three continue buttons would no longer have to be clicked before the first event is triggered.

**Comment by redwolf2** [comment]
https://github.com/NPBruce/valkyrie/issues/290

**Comment by NicolaZee** [comment]
Thanks for the link and informing me something similar is already planned.

I think my enhancement might be easier to code than a button as it just consists of adding a tickbox (checkbox) to the UI page and then checking if the tickbox is ticked on the initial three pages.

**Comment by redwolf2** [comment]
https://github.com/NPBruce/valkyrie/issues/488

**Comment by NPBruce** [comment]
This would be done in the editor as per #290 as I don't want to clutter things for players.  Perhaps it will just pick random investigators unless you have specified as per #488.  Closing as duplicate.
