### ISSUE TITLE
Message window cuts off text

### ISSUE THREAD

**Issue by slycozzolino** [NPBruce/valkyrie#489]
Specific text cuts off in the message window. The following text was not displaying properly:

_The monster reaches for anything in sight that might cause damage to you. It hurls glass and heavy objects at you hoping to fend you off ({agility}; 2). If you pass, you manage to dodge the items as they fly by your head. If you fail, you try to dodge the incoming projectiles as they fly towards you. A glass bottle hits you in the face drawing blood. Suffer 2 Damage and become Stunned._

It would cut off the last sentence. I did some testing and found it would display this text properly if i added 3 characters to the end of the message.

Added 2 characters
![1](https://cloud.githubusercontent.com/assets/27984327/26610536/1fc6ccee-4576-11e7-8cdb-4b5fa700de23.png)

It still displays wrong
![2](https://cloud.githubusercontent.com/assets/27984327/26610587/83d72328-4576-11e7-9929-9706f7cfb95a.png)

The log however is correct
![3](https://cloud.githubusercontent.com/assets/27984327/26610608/979fee1c-4576-11e7-98ef-7faef2649f32.png)

Added a 3rd character to the end
![4](https://cloud.githubusercontent.com/assets/27984327/26610618/a4471b72-4576-11e7-8855-de4a2ef786f3.png)

It now displays correctly
![5](https://cloud.githubusercontent.com/assets/27984327/26610624/afb453bc-4576-11e7-9e68-4260191bd0ab.png)

**Comment by cbusbird** [comment]
I'm running 1.2.2 and I'm still seeing a lot of text being cut off.  Am I missing anything?  I can provide examples if needed.

**Comment by NPBruce** [comment]
A way to reproduce the issue (either a save or instructions for a published scenario) would be great.

**Comment by cbusbird** [comment]
I'm not sure if this makes a difference but this event was probably created in Valkyrie 1.0.  I did some editing on the event so it has been modified in 1.2.2

![textcutoff1](https://user-images.githubusercontent.com/28448698/26861405-8aba9a4e-4b11-11e7-9e14-779d01f3748c.PNG)
![textcutoff2](https://user-images.githubusercontent.com/28448698/26861406-8c68fb06-4b11-11e7-8b26-b47cd920032d.PNG)

**Comment by cbusbird** [comment]
not the best screen shot on the 2nd one but there are 2 whole lines cut off.

**Comment by cbusbird** [comment]
[EditorScenario1.zip](https://github.com/NPBruce/valkyrie/files/1056837/EditorScenario1.zip)

**Comment by cbusbird** [comment]
If I change the event to have no blank spaces it displays everything.  Looks very similar to what @slycozzolino was reporting.


![textcutoff3](https://user-images.githubusercontent.com/28448698/26861651-38bfd73e-4b13-11e7-96ce-12bbb07ef6fe.PNG)
![textcutoff4](https://user-images.githubusercontent.com/28448698/26861654-3b9af7fe-4b13-11e7-822f-b3956848858e.PNG)

**Comment by NPBruce** [comment]
![image](https://user-images.githubusercontent.com/21050071/26907705-d58e0e02-4c38-11e7-91b0-0b74f44b2c95.png)
Mine looks like this.... I have no idea why yours is different.

**Comment by NPBruce** [comment]
What resolution are you running?  There may be something strange going on there.

**Comment by cbusbird** [comment]
1280 x 720

**Comment by NPBruce** [comment]
I can reproduce it at that resolution and not others.  Will work out what is going on and fix.

**Comment by NPBruce** [comment]
I have fixed this case, and hopefully all others, let me know if this appears again.
