### ISSUE TITLE
Add mac build

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#49]
In theory it should be simple to support MacOS.  The main thing that needs to be done is have an alternate way to find the FFG apps (currently uses the windows registry).

Other things to check (could be OK without change):
 - User quest location
 - Temp file location

The biggest issue is just that I don't have a mac, so I can't test any of this.

**Comment by EtiCarasoft** [comment]
Hi Bruce. How can I help you?, i'm a mac user interested in helping you but i know very little about programming. I can test if need.

**Comment by foskon** [comment]
Hi Bruce. Similar here. I am an iOS programmer (no idea about Unity) but i would like to help. What do you need from an osx installation?

**Comment by NPBruce** [comment]
Great, I will add a mac build soon for both of you to test.

foskon:  Can you please work out on MacOS how I tell where the FFG app is installed?  On windows Steam uses a registry key for each steam app with its path, so I use that.

**Comment by foskon** [comment]
Hi Bruce,

The MoM app is at:
path: /Users/<username>/Library/Application Support/Steam/steamapps/common/Mansions of Madness/Mansions of Madness.app

All games are stored at /Users/<username>/Library/Application Support/Steam/steamapps/common/<game folder>/<game name>.app

There is a file (appmanifest_478980.acf) that corresponds with format appmanifest_<appid>.acf. The appid of a game can be found at https://steamdb.info. The .acf files are stored at /Users/<username>/Library/Application Support/Steam/steamapps/

**Comment by foskon** [comment]
On terminal, you can run "system_profiler SPApplicationsDataType" and it will show all applications installed. With a "-xml" parameter, it will output on xml format.

[http://apple.stackexchange.com/a/129854](url)

![screen shot 2017-03-27 at 00 23 52](https://cloud.githubusercontent.com/assets/2240982/24335754/b7e7244a-1283-11e7-9a44-dd98b51e9553.png)

**Comment by NPBruce** [comment]
Thanks for that, can you please attach a complete XML output for me to test?

I can use /Users/<username>/Library/Application Support/Steam/steamapps/, but steam has the ability to setup multiple game locations, this would be the default and won't work in all cases.

Also, can you please show me what the file structure in the install directory looks like?

**Comment by foskon** [comment]
Here you have a cleaned [example_xml.txt](https://github.com/NPBruce/valkyrie/files/873466/example_xml.txt).
Also a tree output of /Users/\<username>/Library/Application Support/Steam/steamapps [output.txt](https://github.com/NPBruce/valkyrie/files/873479/output.txt)

**Comment by NPBruce** [comment]
Great, thanks.

**Comment by NPBruce** [comment]
[valkyrie-macos-0.7.2b.zip](https://github.com/NPBruce/valkyrie/files/875270/valkyrie-macos-0.7.2b.zip)

Try this.  Note this is a dev build and will have bugs, I am interested in if it runs and the import works.  It would also be good to test Road to Legend import (if it fails please provide XML output for this).

There should be a log file somewhere if it goes wrong but I don't know where!

**Comment by EtiCarasoft** [comment]
It Starts, I can choose the resolution, I launch it and comes to a black window with Valyrie White Logo where says:
Unable lo locate Mansions of Madness isntall via Steam, same for Road to Legend. Only clicking exit works.
![captura de pantalla 2017-03-28 a les 12 31 57](https://cloud.githubusercontent.com/assets/26690018/24400954/b18e4dfa-13b2-11e7-9742-dec16778336c.png)
![captura de pantalla 2017-03-28 a les 12 32 21](https://cloud.githubusercontent.com/assets/26690018/24400956/b1924fc2-13b2-11e7-9244-48777c198bf6.png)

**Comment by foskon** [comment]
Same for me. We need to read de logs, but i don't know where they are.

**Comment by foskon** [comment]
It seems that you are looking for a folder named ffg inside the package, but it does not exist.

**Comment by NPBruce** [comment]
> It seems that you are looking for a folder named ffg inside the package, but it does not exist.

That is fine, it is checking if the import already exists.  The problem is "FFG MoM not found."  I will have to add more diagnostics in there when I get a chance.

**Comment by NPBruce** [comment]
I have found a problem and added a lot of diagnostics.  Not in a place where I can rebuild right now, but I am writing up the tests I would like performed (even if it works):

* Start Valkyrie to import screen, exit, save log
* delete macos.app/Contents/apps.xml
* Start Valkyrie to import screen, exit, save log
* Start Valkyrie, attempt to import -> go to content selection -> select an expansion -> exit
* Start Valkyrie -> go to content selection -> check that selection still matches
* In new quest/scenario -> Download -> Download something
* Start quest/scenario

Thanks, will build when I get a chance.

**Comment by NPBruce** [comment]
[valkyrie-macos-0.7.3b.zip](https://github.com/NPBruce/valkyrie/files/878151/valkyrie-macos-0.7.3b.zip)

Uploaded again, please follow steps above.

Note: this build is probably quite broken to use, lots of changes and little testing.

**Comment by EtiCarasoft** [comment]
Test it, I run it, i open the package and delete de apps.xml. Restart valkyre, click on play but it doesnt go further than a black screen post Unity Logo.

**Comment by NPBruce** [comment]
Can you please provide ~/Library/Logs/Unity
Player.log.txt?

**Comment by EtiCarasoft** [comment]
Sorry, How do I get it?

**Comment by Diontsoumas** [comment]
Have the same behaviour, here is my player log file in case it helps :)

[Player.log.zip](https://github.com/NPBruce/valkyrie/files/878352/Player.log.zip)

**Comment by NPBruce** [comment]
I have found and fixed the crash, but it is after it failed to get the XML data correctly.  I will have to rework a bit and try again (not right now, no time).

**Comment by Diontsoumas** [comment]
No worries, great job so far!

**Comment by EtiCarasoft** [comment]
Just when you can i'm here to help in what I can. Amazing work of you!

**Comment by jnierodzik** [comment]
Jumping on here as well.  Happy to help test this or contribute however I can.  Former developer, but no Unity experience.

**Comment by NPBruce** [comment]
The problem is here:

https://github.com/NPBruce/valkyrie/blob/development/Assets/Scripts/Content/AssetImport/AppFinder.cs

Line 88 returns only 1 (should be many).  You could test this function in mono (or install Unity Editor and run the whole project).

PS: The crash is line 109 because location isn't initialised.

**Comment by foskon** [comment]
There is also a problem that i have solved here relative to resources path:  https://github.com/foskon/valkyrie/commit/305d6cb3f0b27f23f13b803885a2b98a293c8143

I have also put my app path here: https://github.com/foskon/valkyrie/commit/d2c9930cadcdf0e552c6f892ead3e98dd82ba848

I can import data of mom and reach the next screen. All menu buttons except About crashes.

I'm going to send you a pull request for the first change.

**Comment by NPBruce** [comment]
Merged (#144).

**Comment by NPBruce** [comment]
[valkyrie-macos-0.8.0.zip](https://github.com/NPBruce/valkyrie/files/880923/valkyrie-macos-0.8.0.zip)
Try this (Please provide log).

**Comment by Ashgur** [comment]
Im also really interested in this!

I did download the last file and i tried to open the application.
But it says "The application “Valkyrie” can’t be opened."
Am i doing something wrong?

**Comment by jnierodzik** [comment]
Tried running version 0.8.0 and it was unable to locate the Mansions of Madness application which was installed via Steam. 
[Player.txt](https://github.com/NPBruce/valkyrie/files/883843/Player.txt)

**Comment by NPBruce** [comment]
Good news, the problem is shown in this log.  Will make a new version when I get a chance.

PS: What is best, zip tar.gz or something else?

**Comment by NPBruce** [comment]
Also, can anyone help Ashgur?  I don't know what the process is.  Also is the directory structure OK?  I think I'll move the licence info up one level.

**Comment by jnierodzik** [comment]
Zip format is fine for distribution. 

@Ashgur your problem is you have Gatekeeper turned on.  To run the application do the following:

1. In the Finder, locate the app you want to open. 
Don’t use Launchpad to do this. Launchpad doesn’t allow you to access the shortcut menu.

2. Press the Control key and click the app icon, then choose Open from the shortcut menu.

3. Click Open.
The app is saved as an exception to your security settings, and you can open it in the future by double-clicking it just as you can any registered app.

**Comment by jnierodzik** [comment]
@NPBruce I would make the License and Notify files txt files.  On a Mac those are showing up as unix executable files

**Comment by NPBruce** [comment]
That is because they don't have an extention and zip can't do executable permissions properly.  I will do something.

**Comment by NPBruce** [comment]
I have added your instructions to here:
https://github.com/NPBruce/valkyrie/wiki

**Comment by jnierodzik** [comment]
While I agree with using system_profiler to locate Mansions of Madness if you wanted to eliminate having to parse through the entire xml output you can run it like this

`system_profiler SPApplicationsDataType -xml | grep "Mansions of Madness.app"`

You'll get this as the output then

> 				<string>/Users/jnierodzik/Library/Application Support/Steam/steamapps/common/Mansions of Madness/Mansions of Madness.app</string>

**Comment by NPBruce** [comment]
Yeah that makes sense, but strangely I am not getting new lines in the returned value.  I have something that I think will work now in C#, so I will leave it for now.

**Comment by jnierodzik** [comment]
Actually parsed that out a little more to this.  It returns just the value so no additional parsing would be required

`system_profiler SPApplicationsDataType -xml | grep "Mansions of Madness.app" | sed -e 's,.*<string>\([^<]*\)</string>.*,\1,g'`

Returns

> /Users/jnierodzik/Library/Application Support/Steam/steamapps/common/Mansions of Madness/Mansions of Madness.app

If you have it working in C# though now even better

**Comment by NPBruce** [comment]
Try this.
[valkyrie-macos-0.8.2b.zip](https://github.com/NPBruce/valkyrie/files/884859/valkyrie-macos-0.8.2b.zip)

**Comment by jnierodzik** [comment]
After the made with unity splash page I get a black window and nothing more.  Attached is the entire log, but here seems to be the error

> ArgumentOutOfRangeException: Cannot be negative.
Parameter name: length
  at System.String.Substring (Int32 startIndex, Int32 length) [0x00000] in <filename unknown>:0 
  at AppFinder..ctor () [0x00000] in <filename unknown>:0 
  at MoMFinder..ctor () [0x00000] in <filename unknown>:0 
  at FetchContent..ctor (System.String type) [0x00000] in <filename unknown>:0 
  at Assets.Scripts.UI.Screens.GameSelectionScreen..ctor () [0x00000] in <filename unknown>:0 
  at Game.Start () [0x00000] in <filename unknown>:0 

[Player.txt](https://github.com/NPBruce/valkyrie/files/885746/Player.txt)

**Comment by Ashgur** [comment]
@jnierodzik : Thanks for your advice. Unfortunately it still doesnt work. I get the same error when i try top open the app with str - open =/

**Comment by NPBruce** [comment]
[valkyrie-macos-0.8.2c.zip](https://github.com/NPBruce/valkyrie/files/888696/valkyrie-macos-0.8.2c.zip)
Another attempt.

**Comment by jnierodzik** [comment]
@Ashgur what version of OS X are you running?

**Comment by jnierodzik** [comment]
@NPBruce okay this time I am able to get to the import content screen, but the application never finishes the import.  Looks like it's looking for a path that does not exist.
[Player.txt](https://github.com/NPBruce/valkyrie/files/888794/Player.txt)

**Comment by NPBruce** [comment]
Looks like unity behaves differently enough on macos that this isn't a great way to go about things.

Given fokson appears to be working on it (#161) I will give this a rest for now.

**Comment by EtiCarasoft** [comment]
I have loaded correctly the mansions of madness content, I can entry in the editor and perform some actions. I can also select correctly the content. And start scenario button also works to find scenarios. "About" also shows information.

![captura de pantalla 2017-04-03 a les 9 45 44](https://cloud.githubusercontent.com/assets/26690018/24600352/830f8e5c-1854-11e7-9998-58e27993978c.png)

![captura de pantalla 2017-04-03 a les 9 53 51](https://cloud.githubusercontent.com/assets/26690018/24600362/8a81c8f8-1854-11e7-8ce1-9839ffd5d01a.png)

![captura de pantalla 2017-04-03 a les 10 00 38](https://cloud.githubusercontent.com/assets/26690018/24600369/943347dc-1854-11e7-861c-b2f5db041ced.png)

Great Work !!

**Comment by Ashgur** [comment]
@jnierodzik 10.11

**Comment by NPBruce** [comment]
jnierodzik are you perhaps running inside the zip? Extract first and try again?

**Comment by NPBruce** [comment]
Ashgur: can you please confirm downloading scenario and save games?

**Comment by eorahil** [comment]
That's a great announcement!!! So the valkyrie-macos-0.8.2c works on Mac?

**Comment by EtiCarasoft** [comment]
In my particular case, yes !!! I'm now testing some scenario edition.

**Comment by jnierodzik** [comment]
@NPBruce : Very much running after extraction unfortunately.  I did try running Valkyrie from a different location though and now I'm getting different results, but it's still not working.

After the splash page it's telling me to "Reimport Content" and after importing it drops back to the main page telling me to reimport again.

![screen shot 2017-04-03 at 8 46 33 am](https://cloud.githubusercontent.com/assets/1038621/24612257/59f94a12-184a-11e7-89e3-29468c201e6a.png)

Is there a cache/tmp files I should be clearing somewhere you're aware of?

**Comment by jnierodzik** [comment]
Just looked in the log and it's trying to find this file which does not exist on my machine

`~/Library/Application Support/Steam/steamapps/common/Mansions of Madness/Mansions of Madness.app/Contents/Resources/`

**Comment by EtiCarasoft** [comment]
I'v got the same message down but if i click on mansions of madness it works pretty well, i've ruun some escenario editor features already and all work well.

**Comment by EtiCarasoft** [comment]
![captura de pantalla 2017-04-03 a les 16 10 02](https://cloud.githubusercontent.com/assets/26690018/24613247/0aa63c48-1888-11e7-9a8a-b63ca1343011.png)
 Some test on tokens and events.

**Comment by NPBruce** [comment]
EtiCarasoft: Some notes while you are there:
The token probably shou;dn't remove itself, it will go as soon as you click it
The 'selection' event is for highlighting heroes which aren't displayed in MoM so it only works in D2E (and doesn't make a lot of sense on a token anyway).

**Comment by jnierodzik** [comment]
For what it's worth I installed Steam, Mansions of Madness and Valkyrie on my better half's Mac and encountered the exact same issue. 

`Could not find main assets file: ~/Library/Application Support/Steam/steamapps/common/Mansions of Madness/Mansions of Madness.app/Contents/Resources/resources.assets`

Out of curiosity, for those of you have that file on a Mac, did you install the MoM application prior to the latest version?  I'm wondering if maybe during some update they got rid of that file.  I had never installed it prior to a few days ago.

**Comment by NPBruce** [comment]
jnierodzik: Just to clarify, after importing did you press 'Mansions of Madness'?

**Comment by NPBruce** [comment]
I am going to release and close this, please open a new issue anyone who still has trouble.

**Comment by jnierodzik** [comment]
@NPBruce honestly, I didn't click 'Mansions of Madness Second Edition'.  After the import I expected something _more?_. Then seeing the re-import button I assumed it failed.  Sorry for the confusion.
