### ISSUE TITLE
Internet Quest Distibution

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#5]
Currently other than quests packaged with Valkyrie there isn't any way to spread these.  It would be great to have a system to publish and update quests/campaigns, perhaps with community ratings and ideally a web interface.

This would be great if it was an existing system that we can use and just do a query/download within Valkyrie.  Open to suggestions?

**Comment by redwolf2** [comment]
Github?

**Comment by NPBruce** [comment]
How would you handle the meta data such as comments/ratings?  Could have them as 'issues' I guess  Also might be a bit tricky for most users to work out how to publish content.

Still, could work.  If the data is hosted here, can always create a web interface somewhere else at a later date.

**Comment by redwolf2** [comment]
I never tried it, but have a look at http://github.io
If you want it in your Game, maybe you could utilize something like the Tabletop Simulator does (also made with unity). It can show a webbrowser ingame. Example: https://m.youtube.com/watch?v=iy4xU5L2T4g

**Comment by NPBruce** [comment]
Yep, I could do all that but my problem is developing/configuring/maintaining a web deployment which would take hundreds of hours.  Something existing like http://www.moddb.com/ springs to mind as to what is required.

Of course I am happy for someone else to develop something.

**Comment by redwolf2** [comment]
On sites like Wikipedia, whenever there is a voting, every user that wants to vote adds an entry in a page and commits it. This simple mechanism is plain and stupid and could be used, if there is a need for a voting system for scenarios.

**Comment by eorahil** [comment]
I was browsing http://www.moddb.com/ , it looks good. You can register a new game (Valkyrie) and then anyone (registered) could upload scenarios, look for new ones and rate them.

**Comment by NPBruce** [comment]
I have half implemented a system which just gets off github for now, with a view to moving it to something else later.  Main thing would be if you can download the files directly from Valkyrie without having to log in.
