### ISSUE TITLE
Add linux build

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#50]
Shouldn't be hard to add a linux build, however FFG doesn't support their apps on Linux, so import would have to be manual (copy from another platform).

This would be solved by:

https://github.com/NPBruce/valkyrie/issues/13

**Comment by jonathonf** [comment]
Getting content from a Windows install is not onerous for most Linux users. If it's an easy thing please do it soon. :)

**Comment by NPBruce** [comment]
ok

**Comment by NPBruce** [comment]
Will be in the next release.  I'd upload a dev build here but it is too big for an issue attachment.  Suggestions on somewhere to drop it and link?

**Comment by jonathonf** [comment]
Awesome. You should be able to add it as a "release" but tag it as a dev/alpha/pre-release version.

**Comment by NPBruce** [comment]
Not ready for that just yet, still changing a few things.

**Comment by Zranz** [comment]
you could upload here [wetransfer.com](https://wetransfer.com/) and we could test how it works.

The link will last a week, but no need to register.

**Comment by NPBruce** [comment]
https://we.tl/OkAwUPs0ez

**Comment by jonathonf** [comment]
It runs fine but it's "unable to locate" RtL or MoM (though I do have them installed in Steam under WINE). Do we need to set a search path or ignore that and copy content over?

**Comment by Zranz** [comment]
Ok, it didn't run for me. I attached log found under `~/.config/unity3d/NA/Valkyrie`

My OpenGL version is the following:
`$ glxinfo | grep "OpenGL version"`
`OpenGL version string: 2.1 Mesa 17.0.2`

Actually, I updated my Mesa drivers quite recently... Can the requirements be lowered?
[Player.log.txt](https://github.com/NPBruce/valkyrie/files/924240/Player.log.txt)

**Comment by jonathonf** [comment]
@Zranz  Not a fix, but you could try e.g. `LIBGL_ALWAYS_SOFTWARE=1 ./valyrie.x86_64`. Not sure which distro/driver you're using but most should support OGL3 now...

**Comment by NPBruce** [comment]
jonathonf: Yeah at the moment you need to copy the content/MoM/ffg or content/D2E/ffg dir from a Windows or MacOS import (using wine should also work).

**Comment by NPBruce** [comment]
Zranz: worked for me on a very not up to date Ubuntu.  I will investigate.

**Comment by Zranz** [comment]
Ok, it runs using @jonathonf suggestion (correcting the valkyrie typo). Thanks. Any idea why this happens?

I will try later to import a windows folder, don't have it at the moment.

**Comment by NPBruce** [comment]
That isn't a solution it is a work around, it will do all rendering on your CPU.

try:
valkyrie -force-opengl

What do you get?

**Comment by NPBruce** [comment]
From unity:
"OpenGL Core is the new back-end capable of supporting the latest OpenGL features on Windows, MacOS X and Linux. This scales from OpenGL 3.2 to OpenGL 4.5 depending on the OpenGL driver support.

The new OpenGL Core is used by default on MacOSX and Linux."

**Comment by Zranz** [comment]
It does not run with -force-opengl, same log file as before.

OK, it may be I do not have a correct graphics installation. My computer has an old nvidia drivers card and intel chipset too. I installed bumblebee but I believe it is not set correctly, I usually cannot run games from steam. It could be related.

If my installation is faulty, I dare not mess it up at the moment. So keep on, and when I have time I will bring this up again if I have trouble.

Selecting custom folder would be a nice way to add content, for those who have dual boot...

**Comment by NPBruce** [comment]
I am reading the registry to look for the install location.  Can you provide a log of running under wine?  Does wine isolate registry sections from other apps?

**Comment by NPBruce** [comment]
https://we.tl/iQyInPD8Kc

This one supports -import <dir>

Mustn't have a trailing '/' (for now).

**Comment by jonathonf** [comment]
> Does wine isolate registry sections from other apps?

Not as far as I know (and not according to a quick web search). Checking the registry files and I can see Steam entries. Which are you checking?

> Can you provide a log of running under wine? 

There's nothing obvious in there... 

```lines=10
fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
fixme:system:SetProcessDPIAware stub!
fixme:win:EnumDisplayDevicesW ((null),0,0x33f414,0x00000000), stub!
fixme:win:EnumDisplayDevicesW (L"\\\\.\\DISPLAY1",0,0x33f414,0x00000000), stub!
fixme:win:EnumDisplayDevicesW ((null),1,0x33f414,0x00000000), stub!
fixme:imm:ImmReleaseContext (0x10050, 0x161c00): stub
fixme:win:EnumDisplayDevicesW ((null),0,0x33f594,0x00000000), stub!
fixme:dxgi:DXGID3D10CreateDevice Ignoring flags 0x1.
fixme:dxgi:dxgi_check_feature_level_support Ignoring adapter type.
fixme:winediag:dxgi_check_feature_level_support None of the requested D3D feature levels is supported on this GPU with the current shader backend.
fixme:win:EnumDisplayDevicesW ((null),0,0x33f704,0x00000000), stub!
fixme:d3d:wined3d_check_device_format_conversion wined3d 0x166488, adapter_idx 0, device_type WINED3D_DEVICE_TYPE_HAL, src_format WINED3DFMT_B8G8R8X8_UNORM, dst_format WINED3DFMT_B8G8R8X8_UNORM stub!
fixme:d3d:wined3d_check_device_format_conversion wined3d 0x166488, adapter_idx 0, device_type WINED3D_DEVICE_TYPE_HAL, src_format WINED3DFMT_B8G8R8A8_UNORM, dst_format WINED3DFMT_B8G8R8X8_UNORM stub!
fixme:d3d:wined3d_check_device_format_conversion wined3d 0x166488, adapter_idx 0, device_type WINED3D_DEVICE_TYPE_HAL, src_format WINED3DFMT_B8G8R8X8_UNORM, dst_format WINED3DFMT_B8G8R8X8_UNORM stub!
fixme:d3d:wined3d_check_device_format_conversion wined3d 0x166488, adapter_idx 0, device_type WINED3D_DEVICE_TYPE_HAL, src_format WINED3DFMT_B10G10R10A2_UNORM, dst_format WINED3DFMT_B8G8R8X8_UNORM stub!
fixme:d3d:wined3d_check_device_format_conversion wined3d 0x166488, adapter_idx 0, device_type WINED3D_DEVICE_TYPE_HAL, src_format WINED3DFMT_B5G6R5_UNORM, dst_format WINED3DFMT_B8G8R8X8_UNORM stub!
fixme:d3d:wined3d_check_device_format_conversion wined3d 0x166488, adapter_idx 0, device_type WINED3D_DEVICE_TYPE_HAL, src_format WINED3DFMT_B5G5R5A1_UNORM, dst_format WINED3DFMT_B8G8R8X8_UNORM stub!
fixme:d3d:wined3d_check_device_format_conversion wined3d 0x166488, adapter_idx 0, device_type WINED3D_DEVICE_TYPE_HAL, src_format WINED3DFMT_B5G5R5X1_UNORM, dst_format WINED3DFMT_B8G8R8X8_UNORM stub!
fixme:d3d:wined3d_check_device_format_conversion wined3d 0x166488, adapter_idx 0, device_type WINED3D_DEVICE_TYPE_HAL, src_format WINED3DFMT_B8G8R8A8_UNORM, dst_format WINED3DFMT_B5G6R5_UNORM stub!
fixme:d3d:wined3d_check_device_format_conversion wined3d 0x166488, adapter_idx 0, device_type WINED3D_DEVICE_TYPE_HAL, src_format WINED3DFMT_B8G8R8X8_UNORM, dst_format WINED3DFMT_B5G6R5_UNORM stub!
fixme:d3d:wined3d_check_device_format_conversion wined3d 0x166488, adapter_idx 0, device_type WINED3D_DEVICE_TYPE_HAL, src_format WINED3DFMT_B10G10R10A2_UNORM, dst_format WINED3DFMT_B5G6R5_UNORM stub!
fixme:d3d:wined3d_check_device_format_conversion wined3d 0x166488, adapter_idx 0, device_type WINED3D_DEVICE_TYPE_HAL, src_format WINED3DFMT_B5G6R5_UNORM, dst_format WINED3DFMT_B5G6R5_UNORM stub!
fixme:d3d:wined3d_check_device_format_conversion wined3d 0x166488, adapter_idx 0, device_type WINED3D_DEVICE_TYPE_HAL, src_format WINED3DFMT_B5G5R5A1_UNORM, dst_format WINED3DFMT_B5G6R5_UNORM stub!
fixme:d3d:wined3d_check_device_format_conversion wined3d 0x166488, adapter_idx 0, device_type WINED3D_DEVICE_TYPE_HAL, src_format WINED3DFMT_B5G5R5X1_UNORM, dst_format WINED3DFMT_B5G6R5_UNORM stub!
fixme:win:EnumDisplayDevicesW ((null),0,0x33f084,0x00000000), stub!
fixme:d3d9:wined3dformat_from_d3dformat Unhandled D3DFORMAT 0xffffffff.
fixme:d3d9:wined3dformat_from_d3dformat Unhandled D3DFORMAT 0xffffffff.
fixme:d3d9:wined3dformat_from_d3dformat Unhandled D3DFORMAT 0xffffffff.
fixme:d3d9:wined3dformat_from_d3dformat Unhandled D3DFORMAT 0xffffffff.
fixme:d3d9:wined3dformat_from_d3dformat Unhandled D3DFORMAT 0xffffffff.
fixme:d3d9:wined3dformat_from_d3dformat Unhandled D3DFORMAT 0xffffffff.
fixme:d3d:debug_d3dformat Unrecognized 0x36314644 (as fourcc: DF16) WINED3DFORMAT!
fixme:d3d:wined3d_get_format Can't find format unrecognized (0x36314644) in the format lookup table.
fixme:d3d:debug_d3dformat Unrecognized 0x434f5441 (as fourcc: ATOC) WINED3DFORMAT!
fixme:d3d:wined3d_get_format Can't find format unrecognized (0x434f5441) in the format lookup table.
fixme:avrt:AvSetMmThreadCharacteristicsW (L"Audio",0x6f3e978): stub
fixme:win:RegisterRawInputDevices Unhandled flags 0x100 for device 0.
fixme:win:RegisterDeviceNotificationW (hwnd=0x40060, filter=0x33eed8,flags=0x00000004) returns a fake device notification handle!
fixme:win:RegisterRawInputDevices Unhandled flags 0x100 for device 0.
fixme:win:RegisterRawInputDevices Unhandled flags 0x100 for device 0.
fixme:win:UnregisterDeviceNotification (handle=0xcafeaffe), STUB!
fixme:win:RegisterDeviceNotificationW (hwnd=0x10050, filter=0x33fc24,flags=0x00000004) returns a fake device notification handle!
fixme:win:RegisterTouchWindow (0x10050 00000000): stub
fixme:win:UnregisterDeviceNotification (handle=0xcafeaffe), STUB!
```

**Comment by NPBruce** [comment]
Try valkyrie_Data/output_log.txt, that doesn't look like the right log.

**Comment by jonathonf** [comment]
Oh, lol. That's the WINE log. :) Here's the Valkyrie log: [output_log.txt](https://github.com/NPBruce/valkyrie/files/924278/output_log.txt) . I suspect it might be down to handling of spaces in paths.

Not that it matter too much now we have a native build. :D

**Comment by Zranz** [comment]
Ok, I figured why it doesn't run on my computer. My Intel [chipset](http://www.phoronix.com/scan.php?page=news_item&px=MTMxMDQ) is too old  xD. It turns out that even though Ironlake is from 2010, it does not have support for OpenGL later than 2.1.

After correctly configuring Bumblebee, I was able to run valkyrie in the Nvidia card. Import from a Windows NTFS parition worked also fine:
`$ optirun ./valkyrie.x86_64 -import "[path]"`

I attach log file. It shows many errors though.

[Player.log.txt](https://github.com/NPBruce/valkyrie/files/946511/Player.log.txt)

**Comment by Zranz** [comment]
Yes, normally have to run games in Windows. Will see if running in Nvidia card helps with this after I fixed bumblebee. Thanks for checking.
