### ISSUE TITLE
Strings in variables

### ISSUE THREAD

**Issue by Ltserb** [NPBruce/valkyrie#500]
enhancement:

Allowing strings to be stored in vars can, among other things, be used to increase randomness.

In my case it would allow me to simplify my custom monster from 112 activations to just 2.

**Comment by NPBruce** [comment]
Can you please explain how you want to use this?

I really don't want to do strings in variables due to issues with defining operations on strings and handling localisation, but there may be another way.

**Comment by Ltserb** [comment]
This specific instance I wan to fill in randomly "{c:Monster} moves 1/2/3 space/spaces toward the nearest/farthest investigator. Then it attacks the investigator in its space /(or an adjacent space) with the lowest/highest {strength}/{agility}/{observation}/{lore}/{influence}/{will}".

I get that this is more than a little redundant, and it isn't _difficult_ to copy paste the activation events. I just feel like it is easier to modify in the future if it is done programatically.

**Comment by Ltserb** [comment]
Doing this also enables more flexibility in assigning damage for an attack. You could have ranges of damage (separate from negates) or changing requirements for ability checks for certain things. Again, all possible by copy paste (which is how I've done it so far) but more flexible/easy if I could just assign a variable.

**Comment by NPBruce** [comment]
For damage ranges you can do that now with {var:#rand3}.   Please provide some worked examples for other situations so I can develop a solution.

**Comment by Ltserb** [comment]
What about just calling a localization directly? in the form Variable.VariableName.Value."String" 
Say, Var.MyVarMovement.1."String"

**Comment by NPBruce** [comment]
OK to break this down:

* {c:Monster} moves 1/2/3 space/spaces

1/2/3 is simple with var.  Note that in general monsters have a fixed speed on only for special activations 'The monster has a burst of speed' does this vary.  I'm not sure how useful this is.

*  space/spaces

The plural is tricky, it would have to be separate entries for 1 space vs more than 1.  As above though I think changing speed to 1 will almost always be a special case.

* toward the nearest/farthest investigator.

This is going to have significantly different sentence structure on languages changes, I think this would stay manual.  Note that towards farthest is probably also a special case, as the attack action would almost certain not be an investigator in it's space in this situation.

* Then it attacks the investigator in its space /(or an adjacent space) with the lowest/highest 

This has translation issues again.

* {strength}/{agility}/{observation}/{lore}/{influence}/{will}".

This is the easy one.  You can reference other translations with parameters, so you can add TEST,"this tests {0}" to the localisation file and use "{qst:TEST:{will}}" to insert it.  Haven't tested this {0} notation in quest but it should work.  Note that in all of the standard activation there is some kind of flavour justification for the skill shown, it is never random, so again I am not sure that this is useful.

* What about just calling a localization directly? in the form Variable.VariableName.Value."String"
Say, Var.MyVarMovement.1."String"

I didn't really understand this or the explanation, but you can reference other localization strings with {qst:<key>}, and you can add extra keys, just edit the localization file.

**Comment by Ltserb** [comment]
I was unaware of the {qst:} function, is it possible to do that recursively? i.e something like {qst:CustomMonsterHound{var:#rand4}.monstername} to get the localization for a random Hounds name?

**Comment by NPBruce** [comment]
You can have one key reference another, and so on, but you can't have the key itself come from another element.

**Comment by NPBruce** [comment]
I am going to close this because at this stage I don't think the complication is justified.
