### ISSUE TITLE
Auto Updater

### ISSUE THREAD

**Issue by Hobbeslionheart** [NPBruce/valkyrie#501]
I would love to have an auto updater instead of downloading an reinstalling a new application unless I've been doing it wrong. Definitely something down the road.

**Comment by redwolf2** [comment]
As a first step it could only show a notification, that there is a new version.

**Comment by rafbel** [comment]
A notification would indeed be helpful. Here's some official GitHub documentation for checking the latest release: https://developer.github.com/v3/repos/releases/

**Comment by NPBruce** [comment]
Easier just to use this:
https://raw.githubusercontent.com/NPBruce/valkyrie/master/unity/Assets/Resources/version.txt

**Comment by NPBruce** [comment]
The notification should be on the game select screen, as old versions may not be able to import.

**Comment by BenRQ** [comment]
Here is the new button look and placement.

![image](https://user-images.githubusercontent.com/40794717/45326819-4ccab200-b555-11e8-830a-571f84432934.png)

**Comment by BenRQ** [comment]
Available in next release
