### ISSUE TITLE
Missing option for New Activations

### ISSUE THREAD

**Issue by LordPyrex** [NPBruce/valkyrie#502]
While using 1.2.2 couldn't find a button for 'New Activation'. I'm currently working around it by directly editing the monsters.ini and localization files.
![noactivation](https://cloud.githubusercontent.com/assets/27811809/26755203/a546448e-4856-11e7-9364-2b48bba92695.png)
![noactivation2](https://cloud.githubusercontent.com/assets/27811809/26755204/ad45b9da-4856-11e7-950f-27cfefe70c94.png)

**Comment by cbusbird** [comment]
Activations have been depreciated.  You just use a series of events.

**Comment by cbusbird** [comment]
If you create a new custom monster you should be able set a single event for activations.  I used a blank event to randomly call the move then attack events.

**Comment by LordPyrex** [comment]
I guess this was one of the few things I hadn't worked with yet since switching into the new version.

**Comment by NPBruce** [comment]
Don't need to create a new version, after removing the old activations the UI format will change to the new style.  Events are a lot more flexible and powerful, so Activations are being removed.

**Comment by LordPyrex** [comment]
I agree, many more potential uses with the random event selections.
