### ISSUE TITLE
Test new import location on MacOS

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#504]
It would be great if someone of MacOS could test a 1.3 build for the new import location.  Mostly I want to know that it works at all, but also it may fix requiring sudo to import, so if someone had that problem please try this without sudo.

https://github.com/NPBruce/valkyrie/releases

**Comment by Mattstones** [comment]
Just installed it on my MacBook Pro 2016 running OS 10.12.5 and it works fine!

**Comment by NPBruce** [comment]
Great!
