### ISSUE TITLE
Problem whit Unique Monster (MoM2nd)

### ISSUE THREAD

**Issue by rimmok** [NPBruce/valkyrie#509]
Hi, i'm a new user. Yesterday i try to make a new custom scenario of Mansions of Madness second edition, but i didn't find the option to make a monster Unique. I red the guide but i suppose it is an older version. Is it a bug or did i miss it? thank you!

**Comment by NPBruce** [comment]
'Unique' Monsters are a Descent concept.  What you probably want is a 'Custom' Monster, that allows you to set custom activations, evades and horror checks.  Create a new CustomMonster Component, select the base monster type then replace the parts you want to change.  Then use a Spawn component to add one to the scenario.

Hope that helps.
