### ISSUE TITLE
Add android build

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#51]
The main difficulty with an android build would be extracting data from FFG apps.  Not sure what isolation android has in place between apps, but as file manager apps can generate APKs of other installed apps I don't see why this couldn't work.

**Comment by NPBruce** [comment]
See issue #13 regarding importing android build.

**Comment by NPBruce** [comment]
Also worth noting that valkyrie currently includes a lot of manual content data and requires the import to be in the same place.  Might need to break these up so the included is in the APK and the import is somewhere else.

**Comment by redwolf2** [comment]
Android allows all applications to access data the sdcard. The data could simply be copied over from the pc installation. Another Idea is to utilize ADB to install and export the data from the pc installation to a usb connected device.

**Comment by NPBruce** [comment]
I can do one of those for now, but would really like it to be self sufficient.  I don't think it will be that hard to get to the android built unity asset files, They are probably just split files or something similar.

**Comment by NPBruce** [comment]
Most of the structural work is done, still need to bug fix, work out what to do with the included 'content' directory and sort out the build chain.

**Comment by brunoelpereira** [comment]
There´s a hope for Valkyrie app for Android?

**Comment by NPBruce** [comment]
Yes, was targeting 1.3, but I've bumped it to 1.4 as I need to get a few more things in place.

**Comment by NPBruce** [comment]
Bumping because MoM 1.3.6 is broken so I'm rushing out 1.4.

**Comment by NPBruce** [comment]
Content loading is done, current issue is working out how to implement WRITE_EXTERNAL_STORAGE permissions.

**Comment by NPBruce** [comment]
Unfortunately I don'e have the capacity to learn/implement this.  Indefinitely postponed, but I welcome pull requests on this.

**Comment by redwolf2** [comment]
https://docs.unity3d.com/Manual/android-manifest.html

Default Android apps do this via the AndroidManifest.xml file.
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="org.valkyrie">
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
</manifest>
```

**Comment by redwolf2** [comment]
https://github.com/redwolf2/valkyrie/tree/Android

Splash Screen is showing. The problem was not the external storage, but the StreamingAssets, thats can't be accessed like a file system. It's sometimes a good approach to use URL like objects and streams over File objects.

![screenshot_20171007-074021](https://user-images.githubusercontent.com/4141621/31305206-287f17fa-ab34-11e7-85c7-e3d0372e58c9.png)

**Comment by NPBruce** [comment]
That is another problem, shouldn't be hard to fix, I was concentrating on the import first.

**Comment by redwolf2** [comment]
I fixed the windows build and implemented the custom manifest. Storage card access should work now.

**Comment by redwolf2** [comment]
Created pull request:
https://github.com/NPBruce/valkyrie/pull/627

**Comment by NPBruce** [comment]
The assets we need are in bin/Data.  They are split into a bunch of smaller files. "ExtractObb" function in FFGAppImport in libraries should do the work (I had this working under windows).

1.3.6 does move the language files out though, so that may need to be looked at again, but it shouldn't be hard.

**Comment by redwolf2** [comment]
I added https://github.com/NPBruce/valkyrie/pull/631

For now the extraction process is running and the import fails at:

```
10-19 05:08:02.407: E/mono(16447): Unhandled Exception: System.IO.IsolatedStorage.IsolatedStorageException: Could not find a part of the path "/storage/emulated/0/Valkyrie/Obb/assets/bin/Data/sharedassets10.assets".
10-19 05:08:02.407: E/mono(16447):   at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean anonymous, FileOptions options) [0x00000] in <filename unknown>:0 
10-19 05:08:02.407: E/mono(16447):   at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share) [0x00000] in <filename unknown>:0 
10-19 05:08:02.407: E/mono(16447):   at System.IO.File.OpenRead (System.String path) [0x00000] in <filename unknown>:0 
10-19 05:08:02.407: E/mono(16447):   at FFGAppImport.FetchContent.Import (System.String assetFile) [0x00000] in <filename unknown>:0 
10-19 05:08:02.407: E/mono(16447):   at FFGAppImport.FetchContent.Import () [0x00000] in <filename unknown>:0 
10-19 05:08:02.407: E/mono(16447):   at FFGAppImport.FFGImport.Import () [0x00000] in <filename unknown>:0 
10-19 05:08:02.407: E/mono(16447):   at Assets.Scripts.UI.Screens.GameSelectionScreen.<Import>m__5 () [0x00000] in <filename unknown>:0 
```

**Comment by redwolf2** [comment]
https://github.com/NPBruce/valkyrie/pull/658

Text asset don't get imported though. When I add the files manually, I am able to get to the main menu.

![screenshot_20171110-005350](https://user-images.githubusercontent.com/4141621/32636664-179dddda-c5b6-11e7-98d4-f3e55450be43.png)
![screenshot_20171110-005519](https://user-images.githubusercontent.com/4141621
![screenshot_20171110-005617](https://user-images.githubusercontent.com/4141621/32636747-5f25e210-c5b6-11e7-8199-15d725faef06.png)
/32636721-4ed8c5bc-c5b6-11e7-8917-7acbf95291fa.png)
![screenshot_20171110-005608](https://user-images.githubusercontent.com/4141621/32636724-534fa58e-c5b6-11e7-94d9-1919d3209abb.png)

**Comment by NPBruce** [comment]
FYI, the langauge files probably aren't in the OBBs.  These are downloaded on run as 'steamingassets', see:

            // Find any streaming asset files
            string[] streamFiles = Directory.GetFiles(finder.location + "/StreamingAssets", "*", SearchOption.AllDirectories);
            ImportStreamAssets(streamFiles);

Need to find out where these are saved on Android.  When I started this work the language files were in the main build, but they were moved out.

**Comment by NPBruce** [comment]
Note that it should be possible to download these streaming assets directly, the server details are in another text asset.  Unlikely that there are protections on this like the OBB itself, but you will have to download all the audio again.  First preference is to get read access to where ever they are locally.

**Comment by redwolf2** [comment]
I added the StreamingAsset import. They were in a different location and had to be moved over to assets/bin/Data to be able to import.

**Comment by redwolf2** [comment]
Next step is getting the version finder to work. We can use the sub dir name from the obb for that. 
The exported images are in tex and pvr format, that have to be converted somehow to dds. 

I copied the import/img dir from the windows import over and did some url fixing and we got game:

![Uploading Screenshot_20171112-075319.png…]()

**Comment by NPBruce** [comment]
We don't have to get the version at all. Extracting the obb every start is overkill.

Looks exciting. I'll have to back up a rig to get the image formats out to play with unless you can upload them somewhere.

**Comment by redwolf2** [comment]
Here is the current export:
https://mega.nz/#!orQzTDqS!3gulDwTvGassRG1_wliMphhUNDetZGHmsPz4qlZXkBo

We don't have to extract the full obb, just open it and look at the file stucture infos. A dir named like the version is located in `assets/AssetBundles`.

**Comment by NPBruce** [comment]
That sounds good, still a nice to have rather than critical.

I'll have a look at the images when I can find time.

**Comment by NPBruce** [comment]
OK so data dump on textures and Unity:

Unity stores the compressed data for textures in it's asset files.  There is also some meta data so it knows have to use it.  The existing import code will wrap this in a container so that the raw data is useful (rather than just writing to disc).  For DXT1/5 compression we use DDS, just because DDS supports this so you can open them as-is with other tools.  In Valkyrie itself we side load the compressed data, so we pull apart the DDS we created to get the meta data and encoded raw data again.

We have to side load because Unity only officially supports PNG/JPEG at runtime.

For MoM Android build there are 2 encoding types: ETC2 RGB and ????.   The ETC2 RGB is being packaged into a .pvr file (by our import code) because that is a container which can support ETC2.  You can use PVRTextTool to view them, but it isn't very useful.  We could write the other end of the PVR interpreter into Valkyrie, or we could just save it as DDS in the first place (but this wouldn't work for any sane DDS viewer - ETC2 is not supported).

In theory we should be able to side load ETC2 just like we do DXT.  We *could* decode ETC2 into something else, however:

1: We would need to write a decoder.  It is an open standard, but I don't like this.
2: We would need to write/include an encoder.  Whatever we encode to would probably not be as efficient as ETC2 on mobiles, and may not be supported by all GPU drivers.  staying with ETC2 means that it should work everywhere MoM works (assuming the side load plan works).

Next we come to ???

This is an encoding that isn't specifically supported by the importer, so we just dump the raw data (no container).  It would be good to log m_Texture2D.m_TextureFormat and try to work it out from there.  At any rate it will need a container and can presumably be side loaded the same as anything else (it came from Unity in the first place).

Lastly there is the matter of file names.  I see a few options:

* Only use DDS as a container.  As mentioned above those with non-dds standard encodes will be broken, but this is only internal to android and pvr is really not very useful anyway.
* Always name the file .dds, regardless of container.  Similar pro/con to above.
* Hack the texture load to also look for .pvr as an alternative to .dds
* Remove extension from ini data for all imported images and have loader try all supported extensions
* Extend ini data to support wild cards or alternative options

All except the last are easy to do.

**Comment by NPBruce** [comment]
PS: Thanks heaps for your work on this.  A lot of the time at the moment I am not at a computer with a development environment, so I am working semi-blind.

**Comment by redwolf2** [comment]
https://github.com/NPBruce/valkyrie/issues/51

* Version is now extracted from obb.
* Road to Legend importer included.
* Small texture load fix for JPG/PNG files.

![screenshot_20171113-231312](https://user-images.githubusercontent.com/4141621/32752564-ebce57a4-c8c9-11e7-9094-fa012201011b.png)
![screenshot_20171113-231222](https://user-images.githubusercontent.com/4141621/32752560-e8d643b8-c8c9-11e7-9d5a-8dd47f52f18d.png)

**Comment by NPBruce** [comment]
Some information on audio:

I haven't debugged this, but this is probably what is happening.  On Windows/MacOS/Linux audio is encoded as Vorbis and then packaged into an FSB container (and then packaged into the assets file).  We extract the FSB, then the Vorbis data, then build an ogg container, and write the ogg vorbis to disk.

Ogg Vorbis is because:
1: It is royalty free.
2: Most players will support Vorbis in an ogg container
3: (Importantly) Ogg is the one of the few supported run time import format in unity on Windows/Linux/MacOS (Vorbis is implied I think)

On mobile builds unity builds to MP3 encoding rather than Vorbis.  They claim this is for performance, but this is disputed, leaving some confusion.  Because of this MP3 decoding is licensed in the Android build, so it can load MP3s from disk.  It should also be able to load ogg/vorbis (though documentation is vague).

I assume the MP3 encoding is stored in an FSB container still.  The only FSB container I have written support for is FSB5/Vorbis, so this will need to be supported (after check that this is the case).

Once out of FSB the MP3 encoding will have some options:

1: Transcode to vorbis (and then stored in ogg - existing code).  I have a (hacked up) ogg encoder already included, but will also need something like this: https://github.com/ZaneDubya/MP3Sharp .

2: Store the MP3 to disk in an ogg container.  This is technically valid, and Unity should support both ogg and mp3, but supporting them together may be unexpected and fail for annoying reasons.  It will also require work to store the mp3 data in ogg, I suggest validating that Unity can load such a file in Android before doing this work.

3: Store the MP3 to disk in an MP3 container.  This requires writing/including an MP3 container code.  May have licensing issues.  Has the problem from images regarding file names.

4: Side load the MP3.  Haven't looked at this, but maybe we can side load the MP3 data into memory.  Will still need some sort of container, so this could either be a work around if ogg/mp3 doesn't work or we could use a much simpler meta data header and use our own custom file format.

**Comment by redwolf2** [comment]
![files](https://user-images.githubusercontent.com/4141621/32975477-bd071a14-cc07-11e7-80f7-a4d2d077372f.png)

I found out those dubious .tex files seem to be ETC2 RGB 8 and those you put into the pvr are ETC2 RGB 4 (the image above shows the wrong image type ETC RGB 4). Which makes sense, when I open up a ETC2 RGB 8 image i got:

![hex](https://user-images.githubusercontent.com/4141621/32975576-e50bce82-cc08-11e7-833b-b68e698072b2.PNG)

I already got the image loading template code in and will go for the tex files now. I will put them in an pvr, too and get them to load.

**Comment by redwolf2** [comment]
Got it:

https://github.com/NPBruce/valkyrie/pull/675

![screenshot_20171118-061610](https://user-images.githubusercontent.com/4141621/32977222-50481f50-cc29-11e7-8eda-46c0e7f41942.png)

TODO: Get the tiles to stretch
TODO: Some images in the importer are missing. Probably an import problem. I've seen some warning in the log, have to investigate.

**Comment by NPBruce** [comment]
Default tile scale is here:
https://github.com/NPBruce/valkyrie/blob/master/unity/Assets/Scripts/GameType.cs
see TilePixelPerSquare().

**Comment by redwolf2** [comment]
That did the trick. I added it in.

**Comment by redwolf2** [comment]
I added the requested image resolver.

**Comment by redwolf2** [comment]
I think I have all import files now. However, the import crashes at:

```
11-21 02:12:36.658: E/Parcel(19057): dup() failed in Parcel::read, i is 0, fds[i] is -1, fd_count is 2, error: Too many open files
11-21 02:12:36.658: E/Surface(19057): dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: -22
```

I think this is due to this line in FetchContent:

```
unityFiles.ForEach(s => assetFiles.Add(new AssetsFile(s, new EndianStream(File.OpenRead(s), EndianType.BigEndian))));
```

The culprit is also Texture2D, which is reliant on the stream, we can't just close it. I will work something out.

Good News: The sound worked out of the box. Sry for the false alarm. There was only the background music resource missing.

**Comment by redwolf2** [comment]
Got it: https://github.com/NPBruce/valkyrie/pull/680

* Import works for all files.
* Way Faster import on Android (Windows should profit, too).
* File handles are disposed on import.
* Audio URLs conform to all OS's.

All the Investigators are displayiing:
![screenshot_20171121-031541](https://user-images.githubusercontent.com/4141621/33053665-13a67aee-ce75-11e7-81d5-27b7b073f5bb.png)

![screenshot_20171121-032517](https://user-images.githubusercontent.com/4141621/33053681-260e56ac-ce75-11e7-944b-810ad95ac8b5.png)

![screenshot_20171121-031541](https://user-images.githubusercontent.com/4141621/33053682-28d333e4-ce75-11e7-9bde-b022ca6927d9.png)

**Comment by redwolf2** [comment]
Added install info at:

https://github.com/NPBruce/valkyrie/wiki

Added a dev guide at:

https://github.com/NPBruce/valkyrie/wiki/DeveloperGuideAndroid

**Comment by redwolf2** [comment]
Those where merged:

3x2 tile problems gone
https://github.com/NPBruce/valkyrie/pull/687

Streets of Arkham compatible
https://github.com/NPBruce/valkyrie/pull/688

I already got the code for the pinch to zoom going. It works but the min and max zoom values are not checked for. Also scrolling and zooming works at the same time. Have to do more work on it.

**Comment by NPBruce** [comment]
Great work.  I am going to close this issue now, we can create new issues for additional problems/features.
