### ISSUE TITLE
valkyrie files on onedrive

### ISSUE THREAD

**Issue by Rass1968** [NPBruce/valkyrie#510]
First, many thanks for the great app and the work you invest ;)
I´m absolut new to Valkyrie and before I start over I installed it on OneDrive that I can use it on my tablet and PC.
I´ve created a new Scenario on my PC and, after the synchronization with OneDrive it isn´t in my Tablet version. Does Valkyrie save the files in a different location?
Another question, there are two versions of Valkyrie 1.1 Feature Demo and Valkyrie 1.2 Feature Demo under copy - scenario, is that right?

**Comment by NPBruce** [comment]
The scenarios are in %appdata%/Valkyrie.  If you have synced accounts this might automatically move across, or you can do it yourself.

The demo is made up of different scenarios, you can copy them individually.
