### ISSUE TITLE
Making an event start triggering after a specific event happens and make it stop triggering after another

### ISSUE THREAD

**Issue by DakonBlackblade** [NPBruce/valkyrie#512]
Im not sure if this is the right place to ask this but I wanted to stop using the thread on boardgamegeek wich definetly was not meant for questions about how to use the software. So heres the question:

Is it possible, and if it is, how can I make an event that activates at the end of each turn but only starts activating after a certain specific event happens and that stops activating after another different event happens. Let me exemplify this

Event A happens > Event B starts to trigger at the end of every turn
Event C happnes > Event B stops triggering

Thank you

**Comment by cbusbird** [comment]
Definitely the place to ask the question.

You have event A assign a variable.  Like (EventAHappened == 1)

You then set a condition on Event B of (EventAHappend = 1)
Set the Trigger option of Event B for End of Round

Event C set an assign variable of (EventAHappened == 0)

If I understand you correctly, this should accomplish what you are looking for.

**Comment by DakonBlackblade** [comment]
Worked like a charm thanks a bunch. For setting up multiple events that work this way all I have to do is use different variables right ? And I can call the trigger variable whatever I like correct ?

**Comment by cbusbird** [comment]
Yep, exactly. 

You apply the same concept to custom Mythos events, but you also have to turn off and then back on the Mythos Intensity levels.
