### ISSUE TITLE
Remove #UI

### ISSUE THREAD

**Issue by LordPyrex** [NPBruce/valkyrie#514]
This is more of an enhancement request. Is it possible to do a #UI for the remove function? Something like for monsters and board components?

**Comment by NPBruce** [comment]
#boardcomponents should work for this also.

**Comment by LordPyrex** [comment]
Yes, but wouldn't that also pull Tiles and Tokens too?

**Comment by NPBruce** [comment]
Yes.  If you want to be selective you can remove the specific elements.  Is the request to have #boardcomponents not remove UI?  I am not sure how useful changes are in this area at this point.

**Comment by LordPyrex** [comment]
Gotcha, overall it's not a big problem.
