### ISSUE TITLE
Content Creation Kit

### ISSUE THREAD

**Issue by redwolf2** [NPBruce/valkyrie#516]
Im working on a Content Creation Kit for Mom. It contains a recreated HD version template of investigator sheets (similar to [Strange Eons](http://cgjennings.ca/eons/) (integration might come later)), item cards and unique item cards.

There should also be a map tileset with wall tiles, tile naming plate, space separators, etc. for custom tile packs. This might help map tile creators.

Also this ;): ![Mountains Of Madness Sample](https://github.com/redwolf2/valkyrie_contentpack_mom/blob/master/mom2_mountains_of_madness_tile_dig_site.jpg)

**Comment by NPBruce** [comment]
What you need is #519

**Comment by redwolf2** [comment]
[Time will tell](https://www.youtube.com/watch?v=Eg_ghkwt5cs)

First [preview](https://github.com/redwolf2/valkyrie_content_creation_kit_mom/blob/master/investigatorsheet.png) (Dont worry, work in process. I hate that tentacle background, will probably change that).

**Comment by redwolf2** [comment]
![investigatorsheet](https://user-images.githubusercontent.com/4141621/27110757-cff5fa64-50ab-11e7-9ef0-136aaa95c586.png)

First release is done. You may also want to check out the [ENGLISH](https://github.com/redwolf2/valkyrie_content_creation_kit_mom/blob/master/investigatorsheet_template_ENGLISH.png) and [GERMAN](https://github.com/redwolf2/valkyrie_content_creation_kit_mom/blob/master/investigatorsheet_template_GERMAN.png) templates.

**Comment by cbusbird** [comment]
Super cool

**Comment by redwolf2** [comment]
I added the [tile sheet](https://github.com/redwolf2/valkyrie_content_creation_kit_mom/blob/master/investigatorsheet_tiles.png).
![investigatorsheet_tiles](https://user-images.githubusercontent.com/4141621/27112264-3b4375d0-50b6-11e7-88e3-d67f808e372c.png)
)

**Comment by redwolf2** [comment]
Backside is up 
![investigatorsheet_backside_template_english](https://user-images.githubusercontent.com/4141621/27210660-32d621fa-5254-11e7-9027-b0802f0e0182.png)

**Comment by redwolf2** [comment]
![damage_backside](https://user-images.githubusercontent.com/4141621/27364242-ab993026-5639-11e7-9b58-60d1a0eed18d.png)
Added first version of the damage card.

**Comment by NPBruce** [comment]
I am going to close this so it doesn't show up as an open issue with Valkyrie.  You can keep using it to post things if you want.

**Comment by redwolf2** [comment]
Ok, no problem, will do.

**Comment by redwolf2** [comment]
![damage](https://user-images.githubusercontent.com/4141621/27487423-fef09f6a-5833-11e7-958a-1f6bee722b63.png)
I added the front of the damage card.

**Comment by redwolf2** [comment]
![horror_backside](https://user-images.githubusercontent.com/4141621/27716849-8346866e-5d41-11e7-9861-576b63b2bf9e.png)
I added a first version of the horror card.
