### ISSUE TITLE
Add Odd and Even Values

### ISSUE THREAD

**Issue by Hobbeslionheart** [NPBruce/valkyrie#520]
I wonder if it would be possible to add Odd and Even as values. Such as if Round# == Odd Assign xxxxx. It could allow for alternating events without having to specify the numbers especially if rounds go on significantly longer than you anticipated.

This could also be used in number of investigators and/or heroes if you want to create a event that affects an odd number of investigators differently than an even number numbers (say if you're trying to break them up evenly or assign even number of damage).

**Comment by NPBruce** [comment]
I would probably do this with a modulus operator.

**Comment by redwolf2** [comment]
So in Hobbeslionhear's example:
`Round# % 2 == 0` for even

`Round# % 2 != 0` for odd
