### ISSUE TITLE
Title Music persists after loading scenario from save (to play)

### ISSUE THREAD

**Issue by TheDoc37** [NPBruce/valkyrie#523]
Just what the topic says; I can't find a way around it. And since sliding the music bar in Options doesn't affect the title menu's music, I can't turn it off. Sorry if this has already been reported; I didn't see anything like it.

**Comment by NPBruce** [comment]
This is 2 bugs, the slider should control title music.

**Comment by TheDoc37** [comment]
Interestingly enough, if I turn the music all the way down, quit out of the app, and then restart it, the title music does the opposite: it's completely silent on the title menu (and by extension when I load a save) even if I put the music back up to full. Perhaps it's only loading the music volume from when you first boot up the game?

**Comment by NPBruce** [comment]
The slider wasn't taking effect until a restart.  That has been fixed, now working on title music still playing on load.

**Comment by NPBruce** [comment]
It will now start scenario music on load, but not custom music if it was playing before the save.  This has been split as #535
