### ISSUE TITLE
Choosing Perils

### ISSUE THREAD

**Issue by DakonBlackblade** [NPBruce/valkyrie#526]
Is there a way to choose witch Peril you want to trigger on D2E. For example, if a MinorPeril occurs, you want it to be an specific MinorPeril rather than a random one from the database. If there isn't is this something that could be added in the future ?

Also the DeadlyPeril "Tendrils of Darkess", the one that forces your team of heroes to colective take a certain amount of damage, displays as: "The heroes must colective suffer {rnd7:7} _heart icon_ damage". Im not sure if this is a bug or if its like this cause I need to imput something I didn't.

**Comment by LordPyrex** [comment]
The Peril function itself is random, so there's no way to tell it to call a specific line. It's done that way to eliminate the repetition of replays. That said, there is a way to work around this, albeit a little bit of work will go into it.

If there is a specific moment that you want to do something like this, I would suggest an event that turns off any current Peril, sets a variable that an EndRound event would look for to activate and display your custom written or copied Peril, and then turns your prior Peril level back on.

It is doable, you just have to think it through for execution. Your DeadlyPeril incident does sound like it might be a bug...

**Comment by DakonBlackblade** [comment]
Ye I did what you describe, it works perfectly, i just tought that since each peril is named that thered be a way to call for an specifi one. It would be specialy handy for DeadlyPerils, seing as there are realy only 2 and one of them has to happen liek 3 or 4 times in a row (Tendrils of Darkness) in order for the players to definetly loose, and when you have Deadly Perils happening randomly Tendrils of Darkness alternate with the other Deadly Peril wich makes for a wonky situation. Also since the other Deadly Peril states that the "heroes loose the game after 2 turns" it only needs to happen once, but since you don't know if this Peril or the Tendrils of Darkness one will trigger you have to set the scenario to continuously trigger Deadly Perils after a certain treshold of threat.

I realize this might be very hard to program into Valkiry, but it would be super handy, maybe itd be possible to even allow for custom perils to be created and fired via the already existing peril mechanism without us having to ressort to workarounds. Anyway just an idea.

**Comment by LordPyrex** [comment]
I understand that, maybe NPBruce can provide insight on that aspect. I've
never set a scenario with only Deadly turned on. It's usually just in the
stack with other levels to throw things a bit harder.

**Comment by NPBruce** [comment]
There is currently no way to do this, and I am not planning on doing so.  The standard perils may change (in name and function) if you want a specific effect you should use your own event.

Specific peril issue raised as #527
