### ISSUE TITLE
I have a quest I want to share with the comunity, what should I do ?

### ISSUE THREAD

**Issue by DakonBlackblade** [NPBruce/valkyrie#529]
I have finished implementing a modified version of Castle Daerion, the quest uses the same tile setup and egenral idea but its heavilly modified to fit the Road to legend feel. Ive not playtested it (yet) and I was aiming for something more on the hard side. Id like to share it with the comunity so ppl could download it and play/discet it if they so want to. What should I do ?

**Comment by NPBruce** [comment]
If you want it to be available manually for testing, zip the directory with the quest.ini file and rename the ".zip" file to ".valkyrie".  You can then send this to people to place in their %appdata%/Valkyrie directory.

If you want it to be available for download in Valkyrie you can fork this repo:
https://github.com/NPBruce/valkyrie-questdata
Add it and make a pull request.  If none of these words make sense just zip it and attach it here and I'll add it.  It is is still in test I recommend making that clear in the title.

**Comment by LordPyrex** [comment]
@NPBruce, did you want me to add a wiki for this?

**Comment by NPBruce** [comment]
Like this?

https://github.com/NPBruce/valkyrie/wiki/QuestPublish

**Comment by LordPyrex** [comment]
Yeah, I guess like that one... lol

**Comment by DakonBlackblade** [comment]
I think I did the whole pull request thing correctly.

**Comment by NPBruce** [comment]
The pull request wasn't right, but you did attach the zip so I have it (can just add it here).

I notice that it was saved with 1.3.0a development release.  This means that it won't work with 1.2.2 stable release.  It is possible to back port it, or you can wait for the 1.3.0 stable release.

**Comment by DakonBlackblade** [comment]
Its saved with 1.2.2 now.

[Castle Daerion 1.2.2.zip](https://github.com/NPBruce/valkyrie/files/1083114/Castle.Daerion.1.2.2.zip)

About the pull request when I click "New Pull Request" on the Valkiry quest data branch it always sends me to that place where I made my first pull request. Should I just click on add a file ?

**Comment by NPBruce** [comment]
You are creating a pull request from my repository and branch.  First you need to create a fork and add your files into the fork, then create the pull request from your fork into my repo/branch.

**Comment by NPBruce** [comment]
Done.

**Comment by Hobbeslionheart** [comment]
Absent a proper forum to discuss and provide feedback for quests and scenarios, I would recommend using this thread as a way to provide the sought feedback for this particular quest.

I had not played the quest, but the first thing I noticed when I downloaded it was that i couldn't play it because I didn't have the expansions. Given that this quest came from the base game Shadow Rune campaign, additional expansions shouldn't be necessary IMO. So I would fix that in the quest page. I fixed it for myself and play it this week.

**Comment by NPBruce** [comment]
I have no problem with that, so long as I can leave it 'closed'.  If an author wants to use the ticket meta data they can use their own github page (a fork of valkyrie-questdata is an obvious place to do it).

**Comment by DakonBlackblade** [comment]
@Hobbeslionheart ye I didn't consider the xpac at first when I was making the quest. After uploading it I tought the same as you did and Im thinking on a version that won't need the xpacs, cause the only reason it needs the xpacs are for some specific monsters.
