### ISSUE TITLE
Log Cuts off (Exotic Material Spoilers? Kinda?)

### ISSUE THREAD

**Issue by TheDoc37** [NPBruce/valkyrie#531]
In Mansions of Madness, roughly 90% of the way through a scenario, the log cuts off. For Exotic Material, the last line was "This appears to be a dark rock, though it is difficult to see for some unknown reason."

I counted a little under 200 line breaks before the log stopped.

**Comment by NPBruce** [comment]
Please provide a save game and the version and resolution you are running.  As a work around try running a different resolution.  This might be fixed in 1.3.0b (still in testing).

**Comment by TheDoc37** [comment]
Unfortunately, I _just_ finished the game before I read your comment on #532 and this. I went back and did some random amount of Mythos, Horror Checks, etc. so even though the effect is the same, the text is not. 
Version is 1.2.2 and resolution is 1280x720, GrQuality "Fantastic". How do I find the save and do you want me to e-mail it, upload it to a fileshare (mediafire is what I've used before), or directly to github?

In the meantime, here's a screenshot of it: https://puu.sh/wp5Kx.png.

**Comment by NPBruce** [comment]
You should be able to find an autosave file in %appdata%/mom/save.  Direct upload here would be great (they are small).

If you have started a new game it might be replaced.

Try running a different resolution and loading the game and see if you get the same problem.

**Comment by NPBruce** [comment]
You could also try the prerelease here:
https://github.com/NPBruce/valkyrie/releases

**Comment by TheDoc37** [comment]
I didn't start a new game yet, so the save I mentioned above is still there (not the original, but the one where I started from 75% of the way through the game and filled it through random event text)

With higher resolution (1366x768 is the highest my comp has): uncovers a little bit more of the log, showing that it was indeed recording all the events, but didn't show all of it. Same results regarding #532 .
With 1.3.0b: reloaded my save in 1.3.0b and the log is completely blank; just a white canvas. I attacked the Riot to try and fill the log but it's still completely blank. The text that was cut off in #532 is now completely shown, however. Should I try starting a new game with 1.3.0b to see if that fixes the blank log?

**Comment by TheDoc37** [comment]
[save1.zip](https://github.com/NPBruce/valkyrie/files/1090309/save1.zip)

**Comment by NPBruce** [comment]
Thanks for the save, I will investigate the blank log, which I think is a different issue (it is a prerelease).  I think the original issue is fixed in 1.3.0b.

**Comment by NPBruce** [comment]
The bug exists when the log exceeds 65500 characters due to a unity limitation, will have to create a work around.
