### ISSUE TITLE
Exotic Material Typo (Spoilers again)

### ISSUE THREAD

**Issue by TheDoc37** [NPBruce/valkyrie#532]
I'm not sure if it's just cut off or the rest was forgotten, but the last line on the Exotic Material ending text says, "Finding a secluded spot you bury the object and hope that it remains hidden for the", and that's all

**Comment by NPBruce** [comment]
As per #531 please provide save, version number and resolution.

**Comment by TheDoc37** [comment]
Since the issue in #531 seems to overlap with this one, should this issue be closed/deleted?
