### ISSUE TITLE
New Adventure Finished but in Spanish

### ISSUE THREAD

**Issue by EtiCarasoft** [NPBruce/valkyrie#533]
Hi it's not an issue at all.
With my partners help, we have made an adventure, which uses only MoM 2 core box material. The problem is our english level... We've made it in spanish. We want to offer you our adventure if you find it interesting enough, but maybe it will need to be translated to english first, and of course to other languages as well.

**Comment by redwolf2** [comment]
I think it would be ok to make a rough english translation and let a native english speaker clean it out.

**Comment by LordPyrex** [comment]
I'm going to add some photos showing some of the steps too.

**Comment by redwolf2** [comment]
@EtiCarasoft Everything ok? You didn't reply for a while. Any problem I could help you with?

**Comment by EtiCarasoft** [comment]
hi no problem. just checking out all the text boxes to perform correctly. It will be done soon ;)

**Comment by EtiCarasoft** [comment]
How do I create a sub folder?

**Comment by redwolf2** [comment]
Press on "Create new file" and input the name and add a `/` at the end.

![687474703a2f2f692e737461636b2e696d6775722e636f6d2f3949666d6a2e676966](https://user-images.githubusercontent.com/4141621/27555214-59fe5594-5ab1-11e7-9ae6-8addc4f80d09.gif)

**Comment by EtiCarasoft** [comment]
Ok, I think i've done all the steps. I see the pull request done and also the files uploaded.

**Comment by EtiCarasoft** [comment]
If any file needs an update how do we do it?

**Comment by NPBruce** [comment]
You can do as many pull requests as you like

**Comment by EtiCarasoft** [comment]
ok i've uploaded it again, with the quest items issue solved.

**Comment by eorahil** [comment]
The uploaded adventure is only in Spanish but there are 2 more localization files. English and French with some different keys. These files are symptoms of some commas added without quotes. 
Please EtiCaraSoft could you take a look at the English and French localizaiton files and see if these texts should be inside other Spanish texts. In my experience, the French texts should be appended to the spanish texts, with a comma (,) and wrapped in double quotes.
If you consider everything is ok, you should remove the French and English localization files (until translated)

**Comment by EtiCarasoft** [comment]
Maybe deteling them is the best way to go until translations are done. Also a kind of low levell english versión can be done but without all the flavor.

**Comment by Indoy** [comment]
@EtiCarasoft 
Hi !
I would do a translation in french with pleasure... but i don't speak spanish at all... Did you find a way or someone to translate it english with flavor?
Regards!

**Comment by EtiCarasoft** [comment]
Not at all. Maybe we can open an enhancement issue to find someone.
