### ISSUE TITLE
Add tower of hanoi

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#534]

**Comment by LordPyrex** [comment]
LOL, not even giving it time to simmer there Bruce!

**Comment by NPBruce** [comment]
Well it isn't hard to add.  The main quest is, do we think that the puzzle enforces size rules for every move?  Clearly it doesn't for the initial setup.  I also assume that the solution can use any of the 3 spaces as none of them are specially marked.

**Comment by NPBruce** [comment]
I also wonder how they alter difficulty, if at all.  The example shown doesn't have any more room to add more blocks, though you could remove them.  You could have preset layouts, but they specifically say it is random.  You can get clever and have a random layout that is solvable in a set number of turns (as I have done with the slide puzzle) but I doubt they have done this.

**Comment by LordPyrex** [comment]
Yes, I was surprised to see that it broke the general rules of Hanoi. Maybe
it works more like a stack puzzle where you move as many tiles in a stack
to sort it out in as few moves as possible. Hanoi would eat a lot of moves
up. Just a simple three layer tier requires 7 moves...

**Comment by NPBruce** [comment]
My system:

Layout is completely random, with restriction of a number of turns to solve puzzle.  All user moves must obey size rules.  Blocks can be stacked in any of the three areas to complete.  Blocks can be moved to either tower (not just adjacted).  My guess is this is close to theirs, but I'm not so sure about the random part.

**Comment by LordPyrex** [comment]
How is the functionality of this? I'm interested to see how to implement this in a scenario. My best guess would be something along the lines of stacking boxes to clear a path, or china in a cabinet to open a secret passage.

**Comment by NPBruce** [comment]
The class is set to 'tower' and level set to the mimimum number of moves, and the blocks are automatically generated.  Looks like the image from the FFG preview, a block on top of a tower can be moved to any empty tower, or a tower with a larger block on top.  When all blocks are in size order in one tower it is completed.

This is working in the development branch for 1.4 (no prerelease build up yet).

**Comment by NPBruce** [comment]
If anyone plays the official scenarios, I would be interested in how the rules compare with my version.
