### ISSUE TITLE
Add Streets of Arkham, when available

### ISSUE THREAD

**Issue by redwolf2** [NPBruce/valkyrie#539]
https://www.fantasyflightgames.com/en/news/3000/1/21/streets-of-arkham/
https://boardgamegeek.com/thread/1800140/new-expansion-streets-arkham

> Look for Streets of Arkham (MAD25) at your local retailer in Q4 of 2017!

[Tower puzzle](https://github.com/NPBruce/valkyrie/issues/534) seems to be already implemented ^^, coincidence?

**Comment by NPBruce** [comment]
Not implemented, but I can do that before the app update.  Basically everything else will have to wait.

**Comment by NPBruce** [comment]
I started a new issue, #654 , closing this.
