### ISSUE TITLE
Missing confirmation prompt when switching phases

### ISSUE THREAD

**Issue by ChadMcCallum** [NPBruce/valkyrie#543]
As I've appreciated several times in the official app, it'd be nice to have a prompt when switching between Investigator and Mythos phases, just in case you missed someone / a horror check and don't realize it, or hit the button by accident.

**Comment by redwolf2** [comment]
https://github.com/NPBruce/valkyrie/issues/430

**Comment by ChadMcCallum** [comment]
It looks like that's just an animation between phases; I was suggesting an actual "Are you sure you're done the investigator/mythos phase?" yes/no prompt.

**Comment by redwolf2** [comment]
Ah, ok. My suggestion to it would be to allow for the undo button to undo the phase. That way you don't have to confirm every time and be able to undo it, if it was pressed by mistake.

**Comment by ChadMcCallum** [comment]
I assume a simple prompt would be easier to implement than a state rollback, but whatever floats your boat :)  I'm no Unity dev but I'm pretty familiar with C#, I may take a stab at this when I get a chance.

**Comment by NPBruce** [comment]
Undo already does this.  As per #136 no plan to add additional dialogs.
