### ISSUE TITLE
Use two strings to translate "Items"

### ISSUE THREAD

**Issue by redwolf2** [NPBruce/valkyrie#544]
![inventory_issue](https://user-images.githubusercontent.com/4141621/27493927-f3a9ee1e-584b-11e7-8d20-88a8a42e01b2.png)

It would be great to have two strings. One that is displayed in the bottom bar and one that is displayed in the dialog title. That way I could make it fit for the german translation.

**Comment by NPBruce** [comment]
Spilt as ITEMS_SMALL:
https://github.com/NPBruce/valkyrie/blob/development/unity/Assets/Resources/Text/Localization.txt
