### ISSUE TITLE
Make the download requirement clearer

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#55]
It surprises me just how often people struggle with hitting  the import screen and not having installed RtL/MoM think it is broken.

What is the best way to make this requirement clear?

**Comment by eorahil** [comment]
When the game executes try to find the REGEDIT register where you locate the installed Apps for importing. If you cant find it, replace the Import button with a "Valkiries Requires Steam App...."

**Comment by NPBruce** [comment]
Yeah it does that check already, but just says import unavailable.

The more I think on this the more I want to solve it with this:

https://github.com/NPBruce/valkyrie/issues/13

**Comment by NPBruce** [comment]
![noimport](https://cloud.githubusercontent.com/assets/21050071/23323922/037864f2-fb3f-11e6-8079-9c7039d081d7.png)

Done with this for now.
