### ISSUE TITLE
Using QItems in the format syntax does not work. 

### ISSUE THREAD

**Issue by redwolf2** [NPBruce/valkyrie#550]
```
GETITEM,Get the item: {0}.
EventTest1.text,{qst:GETITEM:{c:QItemRope}}
```

If `EventTest1.text` is displayed, it will show as `Get the item: {0}.`

![get_item](https://user-images.githubusercontent.com/4141621/27565138-9df95192-5adc-11e7-8a7b-95aab23bfbc4.png)

**Comment by eorahil** [comment]
This changed a lost from my last changes but I think the parameter replacement must include the parameter itself, so

GETITEM,Get the item: {0}.
EventTest1.text,{qst:GETITEM:{c:QItemRope}}

should be:

GETITEM,Get the item: {0}.
EventTest1.text,{qst:GETITEM:{0}:{c:QItemRope}}

or another example:

GETITEM,Get the items: {0} and {1}.
EventTest1.text,{qst:GETITEM:{0}:{c:QItemRope}:{1}:{c:QItemGun}}

**Comment by redwolf2** [comment]
Ok, I will test it

**Comment by redwolf2** [comment]
It works as eorahil pointed out since version 1.3.0
