### ISSUE TITLE
custom awareness/horror in monsters

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#557]
Now that we are displaying these, need a way to set them to custom values.

**Comment by LordPyrex** [comment]
Maybe only have numbers appear on the monster box image if they are put in on the CustomMonster screen. Otherwise they don't appear and are treated as normal variant spawns.

**Comment by NPBruce** [comment]
As per #498 they are currently always showing awareness in the investigator phose and horror rating in the horror phase.

**Comment by LordPyrex** [comment]
Yeah, I guess I should have taken that into consideration... but that being said, does it need to be treated differently? Maybe add a star in the 4th corner to mark that it has different than normal variables.
