### ISSUE TITLE
The Truth: German Translation

### ISSUE THREAD

**Issue by slycozzolino** [NPBruce/valkyrie#560]
Hey RedWolf2,
I put in a minor update adding UI endings and was able to move over the German translations from the event. I did however add one more UI ending for an investigator dying. Please see details here.
https://github.com/NPBruce/valkyrie-questdata/pull/29

Thanks

**Comment by redwolf2** [comment]
@slycozzolino 

Hi Sly,

thanks for the reminder, I will check it out.

**Comment by redwolf2** [comment]
Bruce merged it. https://github.com/NPBruce/valkyrie-questdata/commit/c67e9b3fcf40f797165ec715b16d19f6e78f90a1

**Comment by NPBruce** [comment]
@slycozzolino please have a look at the French translation in #671.

**Comment by slycozzolino** [comment]
Seems fine. Do you need me to add it and push or do you want to take care of it?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by NPBruce** [comment]
I would like the scenario to be moved to the new publishing system here:
https://github.com/NPBruce/valkyrie/wiki/QuestPublish

Then you can make any changes you like without my involvement.
