### ISSUE TITLE
Unsaved changes are lost when pressing test button

### ISSUE THREAD

**Issue by RudolphJ** [NPBruce/valkyrie#561]
First of all: Thanks for the test button! It is really a great feature for developing new scenarios.

Here is an enhancement that would be brilliant: When pressing the test button after changing stuff in the editor, I would expect that I can test the changes. However, if I haven't saved my changes first before pressing the test button, the changes are lost. To avoid loosing any changes it would be a nice enhancement, if the scenario is saved automatically when pressing the test button.

**Comment by NPBruce** [comment]
There are a few options here, open for discussion:

1: Leave it as it is.  Work could be lost by mistake.

2: Auto save on each test.  Changes could be unexpectedly saved (currently nothing is saved without manual confirmation).

3: Prompt for save/reload on test.  Additional UI/clicks which is apparently already causing RSI (https://boardgamegeek.com/article/26147200#26147200).

4: As above but only prompt if changes have been made.  Small improvement, but requires tracking changes which we don't currently do.

5: Test changes without saving to original scenario.  Most work but perhaps the best?  May result in people forgetting to save at all though.

What does everyone think?

**Comment by LordPyrex** [comment]
Well, seeing as the changes that are being made are probably what the Test button is being used for... I would think it best for those changes to at least stay in memory for the sake of testing. I don;t know about everyone else, but I think I save after every couple changes, sometimes even as I'm just editing dialog to prevent forgetting to come back. 

That being said maybe the a prompt that asks if you would like to save on the way back from testing so that if you aren't happy with the way it worked, then you don't have to commit the changes that were made.

**Comment by NicolaZee** [comment]
As the person developing RSI : ) my vote is:
2: Auto save on each test. Changes could be unexpectedly saved (currently nothing is saved without manual confirmation).

Chances are (if I'm testing something) I'm testing something that is not yet done and if it does not work I'm going to change it again and then again and so on until it does.  I don't often test stuff that is already working. : )

If I have a stable version,  I can store it with the save button or zip and store the ini files.

**Comment by RudolphJ** [comment]
Well, since I'm more of an “Undo Button and Auto Save“ kind of guy I vote for

2: Auto save on each test. Changes could be unexpectedly saved (currently nothing is saved without manual confirmation).

5 would be the next best option, however it looks like a lot of work just to be consistent with the manual save concept.

**Comment by NPBruce** [comment]
Ok I might do 2 and change the button to 'save and test'.

**Comment by NicolaZee** [comment]
Thanks.

Good idea to change the text to 'Save and Test'
