### ISSUE TITLE
The Robbery Of The Kadakian Idol: English Translation

### ISSUE THREAD

**Issue by redwolf2** [NPBruce/valkyrie#562]
Now, that my rough english translation is merged, some native speaker might take the task and correct my mistakes:

https://github.com/NPBruce/valkyrie-questdata/blob/master/source/MoM/TheRobberyOfTheKadakianIdol/Localization.English.txt

@prilogon

**Comment by rafbel** [comment]
I made some corrections and replaced some words. I think the text is a little bit more clear now.

**Comment by redwolf2** [comment]
Nice work, thank you. I will close this for now.
