### ISSUE TITLE
Include unofficial Spanish translations for D2E

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#569]
It would be great if a spanish speaker could help communicate with this project:

http://www.fantasyflightgames.es/ir_al_mensaje/126270-road_to_legend_traduccion_por_fans-133255

To allow inclusion of their translations in Valkyrie.

**Comment by eorahil** [comment]
I'm on it

**Comment by eorahil** [comment]
[Localization.Spanish.txt](https://github.com/NPBruce/valkyrie/files/1161967/Localization.Spanish.txt)

They provided me the Localization.txt file with all texts translated. The file replaced the English One. So it isn't multilanguage. Y renamed it with "Spanish" and removed the Languages list in the first line to leave only the spanish one.

So. The import process should get the Localization.txt file as the Localization.English.txt file and put this one as the Localization.Spanish.txt file.

**Comment by NPBruce** [comment]
Don't need to rename on import.  I was going to include this in the Valkyrie content and load it into the same dictionary but from a different source.  I would rather keep the import clean.

**Comment by NPBruce** [comment]
Official translations now supported, no longer required.
