### ISSUE TITLE
Add reverse data to tilesides

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#57]
I am adding checks for duplicate tile use.  To do this I need to know what tilesides are on the back of what other tilesides.  I have added the 'reverse' attribute, it is used like this:

```
[TileSide1B]
top=197
left=105
image="../ffg/img/001B.dds"
traits=throne inside
reverse=TileSide1A
```

This needs to be added to all tilesides.

**Comment by eorahil** [comment]
I'm on it. I will add traits too:
- inside outside
- small medium big
- hallway, restroom, attic, ...

**Comment by NPBruce** [comment]
D2E is really easy, almost all are numbered with A/B.

Adding traits isn't used at the moment.  We could have it pick a random 'small' 'hallway' for example, but at the door locations vary I don't think this is useful.

**Comment by eorahil** [comment]
pulled the MOM part.
I thouth about traits in order to , for example, using a tile filter to search for a tile when you are designing an scenario.

**Comment by eorahil** [comment]
if you wait I pull the D2E part...

**Comment by eorahil** [comment]
Added D2E reverses too

**Comment by NPBruce** [comment]
https://github.com/NPBruce/valkyrie/pull/58

**Comment by NPBruce** [comment]
Merged for next release.
