### ISSUE TITLE
Calling in the buttons

### ISSUE THREAD

**Issue by Hobbeslionheart** [NPBruce/valkyrie#570]
It does not appear to me that we can call within the buttons. See the image below. Ideally, we would use the call so that random monsters or items can be in the button without having to specify them. Maybe qItems are callable in the buttons as I haven't tried it, but monsters don't seem to be.

![image](https://user-images.githubusercontent.com/26637617/28247641-8a0b15aa-6a02-11e7-8507-a40c6e0903be.png)

**Comment by NPBruce** [comment]
Currently not supported.

**Comment by PeterF-D2E** [comment]
Similarly, it would be nice if we could use e.g. {c:QItem0} in the quest.description.

**Comment by NPBruce** [comment]
I am not going to to quest.description because the quest isn't loaded when that is displayed, and required expansions may not be also.  It would also make a web interface harder.
