### ISSUE TITLE
Secondary Spawns Points or Duplicate Spawns

### ISSUE THREAD

**Issue by Hobbeslionheart** [NPBruce/valkyrie#571]
This is a problem that can have two approaches (or more) and I realize that this is probably not consistent with RtL. So, I want to spawn a monster group at the start of the quest, but then add reinforcements as the rounds go on. I could do that manually by picking the monster group in advance and creating two spawns for the same monster group, but let's say that I want to randomize the group, then I'm not sure how I can. 

Either we could have an initial spawn, then a secondary spawn point(s) callable by an event, trigger, or test. 
Or we could have two (or more) spawns with the second spawn similar to the first spawn group. With more spawn groups or points, the app could randomize where they might appear as well as who should spawn.

**Comment by NPBruce** [comment]
The reinforce spawn should have the monster type set to the first spawn event.  I think this does what you want.  If you need to have multiple first spawn events you will also need multiple reinforce events.

Let me know if have have misunderstood.
