### ISSUE TITLE
Down the Attic Hole Scenario

### ISSUE THREAD

**Issue by Hobbeslionheart** [NPBruce/valkyrie#572]
Please upload a new scenario for MoM located here: https://github.com/Hobbeslionheart/DowntheAtticHole

Also use this page for comments and feedback. This was my first scenario when I created it and I wanted to use tiles that wasn't really used in the official app so it requires all of the expansions (sorry for those who don't have them). I also became silly along the way as I was experimenting and learning Valkyrie so it's a very silly scenario and may be woefully unbalanced, but that's besides the point of the scenario. Just have fun!

**Comment by NPBruce** [comment]
Done.  Closing this for tracking reasons, but discussion can continue.

**Comment by Indoy** [comment]
@Hobbeslionheart
Hi
Very funny moment i had when translating your scenario in French!!
However, i've no particular issue, except one!
During myhtos phase, some text warning you that you take to much time. I last a bit in cliking successiv several mythos phase, but nothing happens.
It could be nice and in the mood of the scenario that something happens (like an enraged Alice or whatever :D)
Or didn't I click enough?
I'll post the file after your reply
Congrats for the great originality of your scenario!

**Comment by Hobbeslionheart** [comment]
Hi @Indoy ,

Thank you for translating the scenario and I'm glad you enjoyed it. I had wondered if you would translate this since there are some cultural reference that might not translate well. I'll be curious to see what you did with them. I can read French pretty well.

As for the Enraged Alice idea, that's actually not a bad idea. I think the deadly Mythos that would follow would be enough. This was also my first experiment with Valkyrie and a lot of the ideas were to challenge some of the gameplay and narrative elements that we take for granted in the game. I would like to continue to do that as time permits with other scenarios. So I think I'm good with the scenario.

Please post the file so that I can review it and I'll add it to the hub. Thanks again for translating it.

**Comment by Indoy** [comment]
Hi Here's
[Localization.French.txt](https://github.com/NPBruce/valkyrie/files/1545882/Localization.French.txt)

**Comment by Indoy** [comment]
@Hobbeslionheart
Hi
Do you have the time to read it? And do you have some returns?

**Comment by Indoy** [comment]
@Hobbeslionheart 
Hi here's some reminder =) Do you have some time to read my translation and add it ?

**Comment by Hobbeslionheart** [comment]
@Indoy I went ahead and added it in. I also edited the version number and added your name as a translator. I did the French edits too so check the description page to see if it's right and if not, just let me know or send me the corrected translation and I'll repackage it.

Thank you for your help.

**Comment by Indoy** [comment]
@Hobbeslionheart 
Hi! everything's fine!
I'll tell you if i make some later enhancements in the translation!
Thx!
