### ISSUE TITLE
Quotation Marks are removed at the beginning and end of a dialog box

### ISSUE THREAD

**Issue by Hobbeslionheart** [NPBruce/valkyrie#575]
In D2E editor, events don't seem to like quotation marks at the beginning and the end of the dialog box. When I add it and save, it deletes them.

**Comment by NPBruce** [comment]
As a work around you can use 3 quotes at the start and end and 2 in the middle if required.  Or just use a space as the first character.  I will fix for 1.5

**Comment by Hobbeslionheart** [comment]
Looks like the same thing for periods too. I have used the workaround in my latest update to the quest.

**Comment by NPBruce** [comment]
I want to get Valkyrie 1.5 out to support RtL 1.4, this is going to require a bit more work, so changing target.

**Comment by scrubbless** [comment]
Just to add to this, I have seen it cropping other characters off the end of dialogues too (not just quotation marks)

Was funny, made one of my dialogues say "she begins to wee" instead of "She begins to weep".

I have been adding an additional space to the end of all dialogues just in case since.

**Comment by NPBruce** [comment]
This is fixed for newly entered text, existing text should be unchanged.
