### ISSUE TITLE
The Cardinal's Plight

### ISSUE THREAD

**Issue by Hobbeslionheart** [NPBruce/valkyrie#576]
A D2E quest available for upload: https://github.com/Hobbeslionheart/CardinalsPlight

Any feedback, edits, and suggestions are always welcome. This does admittedly not really adhere to RtL rules. Also quotation marks are missing per the bug I described so once that's fixed, I can update this quest. It also does not break the encounters into separate quests so there's the need to reset the round manually. I didn't know of a easy way to do that. I will also say that people state that the quest favors the Overlord so it will be hard. I lost in the game I tested it with and it will come down to dice rolls.

I'm working on the Shadow Rune Interlude quest so if we create three Act II quests and a Finale, we have a campaign that we can try to coordinate variables together.

**Comment by NPBruce** [comment]
Sub quests is the intended way to do encounters.  It shouldn't be too hard to set up, let me know if you have specific issues.

I have added this to the download list.

**Comment by NPBruce** [comment]
Also for the zombies escaping, you might want to consider using a quota event.  You can set the quota to a variable and only one button.  The user will be prompted to enter a number which will be stored in the variable.  You can also preset the number by writing to the variable first.

**Comment by Hobbeslionheart** [comment]
Quota event makes sense. I'll change that.

I saw the suggestion of breaking the quests apart in a previous issue, but I had already made the two encounters in the same place. In order to be consistent with the format and other quests, I'll break apart the quests, but do you have any suggestions on how to easily separate out the data? Tiles, Tokens, Events, and Spawns should be easy, but extracting data from the localization files might be a bit of a pain. I'll have to review the Wiki and tutorial on how to link quests.

**Comment by NPBruce** [comment]
You can copy all of the quest files into a subdirectory.  Then just delete the bits you don't need in each encounter (or leave them there).

**Comment by Hobbeslionheart** [comment]
Updated the scenario incorporating the suggestions of NPBruce including workarounds for the quotation marks, splitting the encounters into separate quests, and using the quota system for the Zombies Escaped. Package has been uploaded and will be available the next time you download quests.
