### ISSUE TITLE
Does the feature #rand work with Mansions?

### ISSUE THREAD

**Issue by NicolaZee** [NPBruce/valkyrie#578]
I believe #rand2 enables a variable to be set to a random number between 1 to 2 

I've tried the following - to cover the all the bases:
operations=WarlockHasDagger,#Rand2,#Rand2
operations=WarlockHasDagger,#Rand2,0
operations=WarlockHasDagger,0,#Rand2

I know that this can be done using Events but (as I believe the feature exists and assuming it does exist) I would like to use it.
Please can someone explain how to use #rand?

**Comment by NPBruce** [comment]
operations are <var>,<operator>,<value>

In this case you are wanting to set ("=") a var ("WarlockHasDagger") to a random value ("Rand2").

So it should be WarlockHasDagger,=,Rand2

Let me know if I have misunderstood the issue.

**Comment by NicolaZee** [comment]
Thanks for the quick response.
I did try this one as well and it did not seem to work - but at least I now know what I should be doing!
