### ISSUE TITLE
The End in UI

### ISSUE THREAD

**Issue by LordPyrex** [NPBruce/valkyrie#580]
Maybe I'm overlooking something as I'm attempting it, but is there currently a way to trigger the 'The End' function with a UI button? If so I can't seem to make the command work.

**Comment by NPBruce** [comment]
You have to have the ui element call an event which causes the end. Hopefully that makes sense.

**Comment by NicolaZee** [comment]
Sorry to be a nuisance but I am working on the 'The End' events.
Please can you explain how to trigger 'The End' function.
I thought it might be in the list of Triggers.

**Comment by NPBruce** [comment]
Trigger works the otherway, it starts events.  All you need to do is have an event called EventEndReason

Reason can be anything, so you can have EventEndWin, or EventEndTipTable.

Then just add this event to the next even list on your UI component.

**Comment by NicolaZee** [comment]
Thanks
But what I'm not getting is how the event EventEndWin ends the game.

**Comment by NPBruce** [comment]
Because the name starts with EventEnd.

**Comment by NPBruce** [comment]
In hindsight this should be a $var to end the game, but this system existed before vars did.

**Comment by LordPyrex** [comment]
Thanks for the pointer, I think this was the last hangup in my current work.
