### ISSUE TITLE
Change quest ending to use a var

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#581]
Relying on event names is hacky, set a var to end the quest.

#580

**Comment by NicolaZee** [comment]
Thank you for this enhancement.

**Comment by NicolaZee** [comment]
Thinking about it a bit more and I think it would be a very good idea to do this enhancement.

If a new event called EventEndRound is added to handle the EndRound trigger the result is I believe the scenario ends. 
Resulting in a hard to track down and obscure issue.
