### ISSUE TITLE
Where to store MoM files in linux version

### ISSUE THREAD

**Issue by LynchBro** [NPBruce/valkyrie#584]
Hi guys-

Linux user here. I managed to get the windows files for MoM and I'm trying to set up the app.

It's not clear to me where I need to put the MoM files and if there are any extra steps I need to follow.

Anyone care to point me in the right direction?

**Comment by NPBruce** [comment]
If you have the FFG MoM files you can put them anywhere and run with "-import <location>".  Once you have imported you don't need this any more.

If you have an import from Valkyrie on another machine (Windows or MacOS) copy it to ~/.config/Valkyrie/MoM/import

**Comment by LynchBro** [comment]
So ./valkyrie.x86 -import [location] ? 

Will I get some kind of feedback that its worked? Because as of right now Valkyrie stops working once I click ok in the first window.

Thanks for the reply!

**Comment by LynchBro** [comment]
...and I could add. It doesn't give me any feedback that anything actually happened.

**Comment by NPBruce** [comment]
> Valkyrie stops working once I click ok in the first window.

What do you mean by the first window?  There is no OK button.  What does stops working mean?

> ...and I could add. It doesn't give me any feedback that anything actually happened.

by add it do you mean import?  After the import you should be taken back to the game selection screen and you should be able to select Mansions of Madness.

What version of Valkyrie and Mansions of Madness are you using?

**Comment by LynchBro** [comment]
Okay - now I think I must be an idiot :)

The executable I'm running is valkyrie.x86. It loads a window that is labelled as "Valkyrie Configuration". This window lets me change graphic settings and controls. It has an "okay" button and a "cancel" button. Clicking "okay" closes the app.

To answer your second question - I wrote that poorly. Sorry. I meant that, when I write, "./valkyrie.x86 -import" at the command line I get no feedback that anything has actually happened.

I am using Valkyrie 1.4.2 and MoM 1.3.6.

I am assuming I'm using the wrong executable but I haven't found anymore in the release.

**Comment by NPBruce** [comment]
Ah that is the Unity launcher.  If you can't get past that you have bigger problems (nothing to do with the import).  Do you get anything back on the command line?  Look for a log file in Valkyrie_data and have a look inside and attach it here.

**Comment by LynchBro** [comment]
No log files found. Here is what I get at the command line:

$ ./valkyrie.x86
Set current directory to /home/sivak/games/valkyrie-linux-1.4.2
Found path: /home/sivak/games/valkyrie-linux-1.4.2/valkyrie.x86
Mono path[0] = '/home/sivak/games/valkyrie-linux-1.4.2/valkyrie_Data/Managed'
Mono path[1] = '/home/sivak/games/valkyrie-linux-1.4.2/valkyrie_Data/Mono'
Mono config path = '/home/sivak/games/valkyrie-linux-1.4.2/valkyrie_Data/Mono/etc'
Preloaded 'ScreenSelector.so'
Player data archive not found at `/home/sivak/games/valkyrie-linux-1.4.2/valkyrie_Data/data.unity3d`, using local filesystemsivak@SillyHatChamberFour:~/games/valkyrie-linux-1.4.2$

**Comment by LynchBro** [comment]
Does the import function build data.unity3d? Or is that something I need to get separately?

**Comment by NPBruce** [comment]
It doesn't and you shouldn't need it at all.  This issue is still on my list, but I haven't had the time to look into it, sorry.

**Comment by LynchBro** [comment]
All good! You're the boss :)

**Comment by movilla** [comment]
Thank you for your work. I confirm this bug :[

**Comment by movilla** [comment]
I've been trying valkyrie. Valkyrie.x86 doesn't start and Valkyrie.x86_64 can't find the location FFG MoM files.

I uploaded the import files https://mega.nz/#!RpxXiDaT!uuy2FGiO_XcQdtnsSb7WIDfDBL1r5frBOym7DVe4YUs

You need to unzip the files in ~/.config/Valkyrie (the result would be: home/YOUR_USER/.config/Valkyrie/MoM/import/xxxxx)

**Comment by LynchBro** [comment]
Thanks for doing this - but I haven't been able to get Valkyrie's behaviour to change. I tried copying the import files to a few places in the directory structure (After following your instructions of course) and didn't make any progress.

**Comment by Mokiton** [comment]
Tried to import the Road to Legends content from my RtL steam installation on Ubuntu 18.04 to Valkyrie Brynhildr 2.1.0b and initially it did not work. I pointed to the "Road to Legend_Data" folder that contains the "ressources.assets" file. 
You need to point to the parents folder instead. So my console command to start and import was `sudo ./valkyrie.x86_64 -import "/home/username/.local/share/Steam/steamapps/common/Descent Road to Legend"`. To figure out why the import fails, have a look at the Player.log file located at `/home/username/.config/unity3d/NA/Valkyrie/Player.log`.

**Comment by BenRQ** [comment]
Thanks @Mokiton for the update !
@redwolf2 Do you think we should close this issue ?
It seems to work fine in Mokiton environment for "Descent" at least.
