### ISSUE TITLE
La Chute de la Maison Lynch

### ISSUE THREAD

**Issue by gravaillon** [NPBruce/valkyrie#590]
[houselynchgrav.zip](https://github.com/NPBruce/valkyrie/files/1225244/houselynchgrav.zip)
Adaptation du premier scénario des Demeures de l'Epouvante, Première Edition.
Cette adaptation conserve les choix d'histoire de manière aléatoire ce qui garantie une rejouabilité, l'issue et le déroulement du scénario étant toujours incertains.

**Comment by redwolf2** [comment]
Google Translate: Adaptation of the first script of the Demeures de l'Epouvante, First Edition.
This adaptation preserves the choice of history in a random manner which guarantees a replayability, the outcome and the unfolding of the scenario being always uncertain.

**Comment by NPBruce** [comment]
To add this the files need to be hosted in a repository (or somewhere else), I rather than in a zip as an issue attachment.  You can create your own github repository and add the files, then add a link here.  You can then update the files if you need to change anything.

**Comment by NPBruce** [comment]
@gravaillon do you still want this published?  Do you need some help with adding to to a repository?

**Comment by NPBruce** [comment]
I am closing this due to the lack of a responce, but will work through how to add the scenario if requested.

**Comment by gravaillon** [comment]
Hi and sorry for giving you no answer...

I don't understand :

1°) How to add some sounds and images to a scenario.

2°) How to upload on servor a scenario to make it public.


On the other hand, I have a big bug on the new version of valkyrie : for mansions of madness, the search token are replaced by a pnj token (a green generic), all explore token are also replaced by a pnj token (one man with a mustache), and all "see" token are replaced by another pnj token (one woman)... This bug is present on the scenario editor, but also in the "in-game" app.


I have time now, so I will attempt to adapt all scenario from V1 to V2, but with this bug I just can't do it... Can you fix that please ?

Your work on valkyrie is just amazing ! Be thankful for that.


Is it also possible to make the interface more "graphical", like the official app ? I can make buttons and graphics elements for you if you're interested ?

There is also some bug on text organisation (text not in the text bloc), certainly due to the french translation that is longer than the original text in english. Is it also possible to fix that ?


Anyway, thanks for answers.

________________________________
De : NPBruce <notifications@github.com>
Envoyé : dimanche 22 avril 2018 14:34
À : NPBruce/valkyrie
Cc : gravaillon; Mention
Objet : Re: [NPBruce/valkyrie] La Chute de la Maison Lynch (#590)


Closed #590<https://github.com/NPBruce/valkyrie/issues/590>.

**Comment by NPBruce** [comment]
You problems are because FFG released MoM 1.5, and Valkyrie needs to be updated to work with it.  1.7.0d prerelease will work, and there should be a stable release out soon.

Questions:

1) Just add the image or sound to the scenario directory, it will appear in the editor.

2) See here:
https://github.com/NPBruce/valkyrie/wiki/QuestPublish

**Comment by gravaillon** [comment]
Ooooh ! Great !

Thanks a lot and keep us the good work.

I go back to work : lot of scenario to adapt !


________________________________
De : NPBruce <notifications@github.com>
Envoyé : dimanche 22 avril 2018 23:27
À : NPBruce/valkyrie
Cc : gravaillon; Mention
Objet : Re: [NPBruce/valkyrie] La Chute de la Maison Lynch (#590)


You problems are because FFG released MoM 1.5, and Valkyrie needs to be updated to work with it. 1.7.0d prerelease will work, and there should be a stable release out soon.

Questions:

  1.  Just add the image or sound to the scenario directory, it will appear in the editor.

  2.  See here:
https://github.com/NPBruce/valkyrie/wiki/QuestPublish

[https://avatars2.githubusercontent.com/u/21050071?s=400&v=4]<https://github.com/NPBruce/valkyrie/wiki/QuestPublish>

QuestPublish · NPBruce/valkyrie Wiki · GitHub<https://github.com/NPBruce/valkyrie/wiki/QuestPublish>
github.com
GitHub is where people build software. More than 27 million people use GitHub to discover, fork, and contribute to over 80 million projects.
