### ISSUE TITLE
old versions

### ISSUE THREAD

**Issue by Ashgur** [NPBruce/valkyrie#592]
A quick question:

My mac book crashed a month ago, so i cant continue to work on my scenario right now. I did make a backup but it will take a while until i can use it, because its in another town. 
My question: Are you going to delete the downloadlinks for older versions of valkyrie anytime soon or do i not have to worry about that? Im a little bit in fear of some compatibility-issues, because my last save will be on much older valkyrie-version.

**Comment by NPBruce** [comment]
Firstly:
Have a look here:
https://github.com/NPBruce/valkyrie/wiki/QuestFormat

For supported versions.  Unless you are using a version from before 1.1.0 the current release will still support your files.  Just resave to update your scenario, while there is a chance of bugs you will need to do this at anyway to update for release.

Secondly:
The only builds I have removed are very old (before 0.5.7).  If I do remove any others it will only be prereleases and/or builds with known serious bugs.  The labelling system before 1.0.0 is a bit messy, so I might remove more of those old builds to clean things up, but I really hope you aren't using a pre-stable build anyway.

Hope this helps.

**Comment by Ashgur** [comment]
it does! thank you!
