### ISSUE TITLE
Cannot access the scenario at the bottom in copying scenario

### ISSUE THREAD

**Issue by Hobbeslionheart** [NPBruce/valkyrie#595]
I wanted to copy the Robbery scenario to see how it was constructed, but I can't access the absolute bottom if the screen overflows.

[valkyrie 2017-08-24 22-41-13-99](https://user-images.githubusercontent.com/26637617/29697509-9c93aafe-891d-11e7-925c-c8b6eed965f1.jpg)

It looks like The Truth and the Robbery are hidden below. I couldn't access it in Windowed mode or full screen mode.

**Comment by NPBruce** [comment]
Files attached as a work around.
[TheRobberyOfTheKadakianIdol.zip](https://github.com/NPBruce/valkyrie/files/1250744/TheRobberyOfTheKadakianIdol.zip)

**Comment by NPBruce** [comment]
Bug also applies to the delete screen.
