### ISSUE TITLE
No Items

### ISSUE THREAD

**Issue by cinnabum7** [NPBruce/valkyrie#596]
I'm trying to run the tutorial scenario, but after I choose investigators, the system does not assign any items. Am I missing something?

**Comment by Hobbeslionheart** [comment]
I am assuming that you're speaking of the Tutorial Scenario that exists in MOM. The tutorial does not assign items unless you choose Ashcan in which you will automatically get Duke as a starting item. It is up to the scenario designers to determine what, if any, items you get at the start. 

The Tutorial Scenario is probably not the best way to learn how to design scenarios as it was designed to point out new features for existing designers. I suggest starting here: https://github.com/NPBruce/valkyrie/wiki/TutorialScenarioCreation

If you're trying to add starting items to the scenario you created (following the instructions above), then you need to add QItems and click starting. A good tutorial is here (although the interface is outdated) https://github.com/NPBruce/valkyrie/wiki/TutorialQItemUsage
