### ISSUE TITLE
1.4.2 Stop running

### ISSUE THREAD

**Issue by EtiCarasoft** [NPBruce/valkyrie#598]
Hello, I have installed again many times the 1.4.2 version due to the fact that when I start the application, go to the start scenario button I only get a black window with no button or nothing to do just to close the application. Also the scenario editor button doesn't work.

**Comment by NPBruce** [comment]
Is this always the same scenario?  Most likely the scenario is broken, try another one?  If so please attach the bad scenario here.

**Comment by EtiCarasoft** [comment]
the problem is that i cant run any scenario or download. just keeps a black window

**Comment by NPBruce** [comment]
Can you try installing to somewhere that your user can write to (desktop/documents) then provide the log file from valkyrie_data\output_log.txt?

**Comment by EtiCarasoft** [comment]
i'm searching the path but i don't find it in mac

**Comment by EtiCarasoft** [comment]
[Player.log.txt](https://github.com/NPBruce/valkyrie/files/1274797/Player.log.txt)
[Searching ](https://docs.unity3d.com/Manual/LogFiles.html)I've found this. It's what you need?

**Comment by NPBruce** [comment]
Nothing there... anyone else with MacOS having problems?  Do earlier versions work?

**Comment by EtiCarasoft** [comment]
I've deleted all the package in the valkyrie .config non visible folder and relaunched the application. After importing all the package it works as normal. seems solved. I leave this comment as a posible solution.
