### ISSUE TITLE
New Scenario - The Lair of Rlim Shaikorth

### ISSUE THREAD

**Issue by sodapaps** [NPBruce/valkyrie#600]
Here is where the files are located.

https://github.com/sodapaps/TheLairofRlimShaikorth

**Comment by NPBruce** [comment]
Done.

**Comment by Hobbeslionheart** [comment]
I really liked this scenario. I thought it was a good mixture of tiles and characters. The original artwork was simply amazing. Well done.

Some minor feedback for polishing if you're interested. Am trying not to spoil it for anyone who happens to be reading this.

The dialog box when you obtain the Wrack Spell has the will symbol ahead of the -1.
Might want to check the text log for consistency with the capitalization of Explore and Search tokens. Not a big deal, but could be quickly fixed.
The event after where the search token is place should have a move camera action assigned. 
Sylvia is misspelled towards the end. 

I'm not sure how people organize their people token, but you might want to stick with a set as opposed to drawing from multiple sets. It was hard for me to remember how to put it back as I sort them out by the original scenarios. It was nice to see some of those people tokens used again though.

Maybe more dramatic flourish for the Mythos phase as it moves across intensity. We could see it getting harder and harder, but there was no marker so to say. Maybe even have a timeline or something? One of my investigators got trapped fighting and couldn't move the plot forward for a while.

Hope this feedback helps as we enjoyed it a lot.

**Comment by sodapaps** [comment]
Thanks! Great feedback, and I'm glad you all enjoyed it.
