### ISSUE TITLE
How to move a tile

### ISSUE THREAD

**Issue by Mechanmy** [NPBruce/valkyrie#601]
Hi, i don't know how to move a tile, i only know how to turn it (0 / 90 / 180 / 270)  
But the buttons "< >" and "E" in the tutorial doesn't work. 
I see the double white circle in the corner of tile, wich i suppose we could change the place, but i dont' know how to change the target corner.  

What's the buttons "Snap" and "Free" are suppose to do  ? They just move tiles and token in the corner up-left. 

Thanks for your help
My version is 1.4.2
SOrry for my english

**Comment by redwolf2** [comment]
You can use the arrow keys to position the tile.

Snap = Snap the tile to the grid. This allowes you to position the tile exactly at the edge of another tile
Free = Move the tile freely. This allowes you to overlap the tile on another tile.

**Comment by Mechanmy** [comment]
Thanks for the quick answer, but when i try with arrows it just move my camera. 
Same, the button "E" does nothing when i press it to rename, i have to push the button on the screen to rename a tile.

**Comment by NPBruce** [comment]
Click on 'snap' then click on a space in the map.

**Comment by Mechanmy** [comment]
Thanks, it works fine :)
