### ISSUE TITLE
Latest translations not updated

### ISSUE THREAD

**Issue by eorahil** [NPBruce/valkyrie#602]
A few weeks ago, the spanish version of the Beyond the Threshold expansion had a lot of text untranslated in the original MoM App. Creators fixed it and updated the texts. But I install valkirie from scratch but these texts are not translated. (you can check it by exploring %AppData%\Roaming\Valkyrie\MoM\import\text\Localization_es.txt and searching for the text of the key COMMON_ITEM_25_AUTOMATIC, every BtT items are not translated).
I think Valkirie is not updating these text changes because te MoM App already fixed it, as I opened the app I shown me the latest updates info with the version 1.3.7 (700).

Is it possible that valkyrie can't refresh these stream texts? the app updates from the MoM original rource? or valkyrie stores it in some Github repo?

**Comment by NPBruce** [comment]
To clarify, did you do a reimport?

**Comment by eorahil** [comment]
Yes I did. and deleted evereything from %appData% and restarted from scratch

**Comment by NPBruce** [comment]
I can reproduce this, but I don't know where the updates are coming from if Valkyrie isn't getting them.

**Comment by NPBruce** [comment]
I can't reproduce this in MoM 1.4.1/Valkyrie 1.6.0d.  If the problem comes back please reopen.
