### ISSUE TITLE
App crash, import issue?

### ISSUE THREAD

**Issue by mokujin90** [NPBruce/valkyrie#604]
Install valkyrie for the first time. Import MoM. But it looks like import is not working properly. All downloaded scenarios freez on load screen in valkyrie. When i try to create new scenario, all elements have no textures in "select image" popup. On add "new tile" btn app is crashing ...

**Comment by NPBruce** [comment]
What OS? What Valkyrie version?

#602 discusses missing translations, how does that connect with your issues?

**Comment by mokujin90** [comment]
Win 7, Latest ver 1.4.2. How to check import successed? I looked into import dir, there are a lot of data, but no tiles dds files, and app crushes on adding tile btn.

**Comment by mokujin90** [comment]
![crash](https://user-images.githubusercontent.com/8236073/30566269-04379188-9cd4-11e7-94cc-2c501de39573.jpg)

**Comment by mokujin90** [comment]
Also I tried it on my other pc, have an error 'Can't find MoM Files, install via Steam', reinstall game, but it won't help. ):

**Comment by mokujin90** [comment]
Reinstall the game & app, import successed. Problem solved.

**Comment by NPBruce** [comment]
Odd, I dont' know what the issue was.
