### ISSUE TITLE
UI Elements with buttons cause board camera to move

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#606]
Hi, 

I am having an issue with the camera. The default position of the camera has moved off far to the left of where the tiles were placed (it was in the middle of them originally when I first started adding tiles).

When I splash up a UI element during "StartRound" and click, it triggers an event to remove those UI elements, the camera flies off to the starting position to the left.

Re-create - Hit "End Phase" ok the mythos event and click when it says "Start investigator phase".

I've attached my Scenario (so far) below.
[Stressandstrain.zip](https://github.com/NPBruce/valkyrie/files/1310322/Stressandstrain.zip)

**Comment by NPBruce** [comment]
Yep, found the bug.  Any UI components which have buttons will take the camera to the UI location, which doesn't make sense because it is a screen position not a board position.  This normally isn't a problem because I haven't used UI components with board components.

As a side note, you should consider encoding parchment.png to a jpg, it is huge.

**Comment by redwolf2** [comment]
I agree. For smalller png images, it is a good idea to run them through "PngOptimizer". It shrinks them lossless.
https://psydk.org/pngoptimizer
https://github.com/hadrien-psydk/pngoptimizer

**Comment by scrubbless** [comment]
You know what... I cropped the original and added it late one night. Then hated in app and decided not to use it. I will 100% use png optimizer on the images I will use. Good call. But parchment.png will probably die in a fire ;).

Thanks for finding the bug, glad its not just me going mad. Look forward to a fix, for now i;'ll anchor disable the event, its cosmetic anyway (and a place holder). If it works I will probably do it with an image, similar to the app.

**Comment by NPBruce** [comment]
Check out the prerelease here, let me know if you find any bugs:

https://github.com/NPBruce/valkyrie/releases/tag/prerelease%2F1.5%2Fv1.5.0a
