### ISSUE TITLE
Custom Monster Image not loading

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#607]
The custom monster image is not loading. It is an 200x200px - 81kb .PNG image created in GIMP.
It comes up as a red ? on a white background at present, which i've noticed is the default holding image when the image can't be found.

I have attached my Scenario, I have added a shortcut (Secret Door tile) to the first tile which will skip to the monster spawn event.

[Stressandstrain.zip](https://github.com/NPBruce/valkyrie/files/1324415/Stressandstrain.zip)

**Comment by NPBruce** [comment]
Yep, found the bug.  It doesn't add the relative path, so it can't find the image.

**Comment by NPBruce** [comment]
I recommend using the base monster type of a picture that is close enough as a work around for now. (and don't set a custom image).

**Comment by scrubbless** [comment]
Thanks Bruce, I will do. Looking forward to the fix. Had fun making the custom images :D

**Comment by NPBruce** [comment]
Check out the prerelease here, let me know if you find any bugs:

https://github.com/NPBruce/valkyrie/releases/tag/prerelease%2F1.5%2Fv1.5.0a
