### ISSUE TITLE
QItem - random common is selecting items the player has

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#608]
Hi, 
Another problem i've noticed.

I have created an event to give a specific item early in my Scenario. Later on I have created an event that gives a random common item.

In one of my random play throughs I picked up that "specific item" and then opened the later search token and was given the same item a second time. 

Not the end of the world, but I assumed the "greyed out" items would not drop from random "category" drops.

**Comment by LordPyrex** [comment]
Hey scrubbless, 
the reason this happens is you have to make the item exclusionary for all future QItems if you plan on giving it to the Investigators. If you check out the Wiki sections we have some info on how to do this. [QItem Tutorial](https://github.com/NPBruce/valkyrie/wiki/TutorialQItemUsage). If you have any other questions about, post here.

**Comment by NPBruce** [comment]
As mentioned, it must be specifically excluded.  Grey items are just a helper to show that it has been used somewhere else.  This is to allow different paths working differently (for example in MoM1E often there will be a randomly assigned item in one setup which is specifically placed in another variant of the same scenario).

**Comment by scrubbless** [comment]
That explains it. My bad, thanks for taking the time to answer.
