### ISSUE TITLE
Missing Content

### ISSUE THREAD

**Issue by Warhippo** [NPBruce/valkyrie#611]
Hi, I'm having problems with Valkyrie. I'm using a Mac running OS 10.12.6 with Valkyrie 1.4.2 and I have the "Descent Road To Legend" app installed . I start Valkyrie. The instructions state that I should click the "Import Road To Legend Content" but I don't have that option - I only have "Descent : Journeys in the Dark Second Edition" and "Reimport Content". Perhaps the Reimport button used to say Road to Legend but I missed it.... In any case, I then click the "Descent : Journeys in the Dark 2nd Edition", click "Start Quest" and am presented with a window saying "Select Quest" which is empty. I click "Download" and a message appears saying "Downloading Package List". After about 20 seconds, Valkyrie bombs (app quits). Happens every time.

Any ideas?

**Comment by NPBruce** [comment]
Unfortunately I don't have macos so it is very hard to diagnose problems.  Can anyone who does help?

**Comment by alvaromunoz** [comment]
1.7.0b on mac 10.13.2 works OK with both D2E and MoM 👍

**Comment by Warhippo** [comment]
It does indeed! That's brilliant - well done guys :)

**Comment by NPBruce** [comment]
I am assuming this is no longer an issue until informed otherwise.
