### ISSUE TITLE
Eliminated Trigger not working?

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#612]
Hi guys,

I assume that the Eliminated trigger should happen as soon as you **Set - Player Eliminated**. But it doesn't seem to do anything in game, or it does after I hit **End turn** a couple of times.

Am I using this function wrong or is this a bug?

My process is to create an Event and Set the trigger to Eliminated. Then add some UI elements for Images and Text.

However when I set the players to eliminated nothing happens. If I then click end turn a couple of times the event triggers the UI elements to pop up.

**Comment by NPBruce** [comment]
It will end at the end of the next round.  This was considered to be a better UI than the official app, but is inconsistent, so perhaps that is worse?

**Comment by scrubbless** [comment]
I think it might be best to leave this as is. 
Based on the rules, you should have one turn to attempt to complete before the game ends. Having it trigger at the next turn end might mean that no player has actually acted.
