### ISSUE TITLE
Bug when creating a {New Event} from a Monster activation

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#618]
In a custom monster, if you click "Activations" and click {New Event} it will create Event0
![image](https://user-images.githubusercontent.com/32058089/31224189-dab4ff1e-a9c4-11e7-9b04-2841fd44a85f.png)

If you then click the -> to open it and change the name:
![image](https://user-images.githubusercontent.com/32058089/31224204-e4aeffe2-a9c4-11e7-9ea1-313787416573.png)

When you click back (or open the monster from components) it gives you this error:
![image](https://user-images.githubusercontent.com/32058089/31224225-f6052ad2-a9c4-11e7-84f1-4d31aa6e399d.png)

Events and spawns all work fine this way, just custom monsters that don't seem to link to the new name.

**Comment by NPBruce** [comment]
This bug is more board than this.  Any horror/evade/activation events that are renamed will not update correctly.

**Comment by NPBruce** [comment]
Check out the prerelease here, let me know if you find any bugs:

https://github.com/NPBruce/valkyrie/releases/tag/prerelease%2F1.5%2Fv1.5.0a
