### ISSUE TITLE
Run House Lynch with Suppressed Memories and Recurring Nightmares?

### ISSUE THREAD

**Issue by Titeman** [NPBruce/valkyrie#619]
It won't let me launch this scenario. Does one need 1e to run it, even thought he expansions come with all tiles and monsters?...

**Comment by NPBruce** [comment]
Have you selected Suppressed Memories and Recurring Nightmares on the Content Selection page?

**Comment by Titeman** [comment]
Yup. I can play the expansion related scenarios in the FFG app. Is there a place in Valkyrie where you have to enter them?...

**Comment by NPBruce** [comment]
The Content Selection page in Valkyrie (from the main menu).

**Comment by Titeman** [comment]
That was it. Thanks!
