### ISSUE TITLE
D2E Class/Skill/Hero/Monster names to use FFG language data

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#620]
Changing to use an ffg: lookup will mean we can support all FFG supported languages (currently these will always be in english).

**Comment by BenRQ** [comment]
Cherry-picking the commit from Bruce in dev branch

@redwolf2 how I can know the original FFG name for the missing translations ?

I see that a few lines are still missing in the following file:

content\D2E\base\content_pack.ini    
content\D2E\ck\aod\content_pack.ini  
content\D2E\ck\d1e\content_pack.ini  
content\D2E\ck\dq\content_pack.ini   
content\D2E\ck\promo\content_pack.ini
content\D2E\ck\toi\content_pack.ini  
content\D2E\ck\wod\content_pack.ini  

content\D2E\base\classes.ini      
content\D2E\boxed\lotw\classes.ini
content\D2E\boxed\mor\classes.ini 
content\D2E\boxed\son\classes.ini 
content\D2E\boxed\tctr\classes.ini
content\D2E\boxed\tt\classes.ini  

content\D2E\ck\d1e\heroes.ini     
content\D2E\ck\dq\heroes.ini      
content\D2E\ck\promo\heroes.ini   
content\D2E\ck\wod\heroes.ini

**Comment by BenRQ** [comment]
I found the translations here : $USER\AppData\Roaming\Valkyrie\D2E\import\text\Localization_*.txt
and added the missing translation.
