### ISSUE TITLE
In the Dark Scenario request for Publication

### ISSUE THREAD

**Issue by NicolaZee** [NPBruce/valkyrie#621]
Please can the package for the scenario 'In the Dark' be included for publication?
The package is located in the following folder:
https://github.com/RudolphJ/InTheDark/tree/master/InTheDark.

The scenario requires the Suppressed Memories Expansion.

The scenario was designed by Nicola Zealey with support, playtesting and many excellent ideas provided by Assistant Designer and Chief Play Tester Jürgen Rudolph.
Without Jürgen's continual feedback and total commitment to quality, the scenario would not have ended up as good.

The German Translation is now in development by Jürgen Rudolph.

The scenario has been thoroughly play-tested by more than 10 players and (so far) the reception of all play-testers has been very positive - even by one play-tester who does not like Mansions 2nd edition.

The scenario contains a mystery which is partly random but there are always hints to the solution of the mystery - if players take notes and carefully consider the clues.

**Comment by NPBruce** [comment]
Done!
