### ISSUE TITLE
Brigther Components when none are selected

### ISSUE THREAD

**Issue by eorahil** [NPBruce/valkyrie#625]
I'm creating a new scenario from scratch and I'm to use the Valkyrie App itself to desing de adventure.
After placing every tiles and tokens in the board I want to see the hole board, zooming and seeing details alternating with global peeks. 
In order to achieve that, I see a problem the fact that there is no way of seeying all board without being dark.
I propose that browsing to the Quest properties (Description, creator, expansions required, ...) automatically unselect last selected board component and show a global view of board, without being dark.

**Comment by NPBruce** [comment]
The issue is overlapping components.  The reason they are dark is that all components are transparent, and you see through to the background.  Many  boards and/or tokens could be on top of one another and this is to show you that.

I can try to do something to make them not dark but keep the transparency between items.

**Comment by redwolf2** [comment]
Suggestion: Assign tiles to a group and have an option to show/hide the group. By default all tiles are in the group "default". That way, all tiles can be non transparent.

**Comment by NPBruce** [comment]
Grouping already exists by files.  Could enable display by group.  The problem is worse for tokens though, there are often overlapping tokens.

**Comment by antontimmermans** [comment]
Is this still an issue now the transparency is adjustable in the options of version 2.2?

**Comment by redwolf2** [comment]
No, but still could add groups or use layers of some sort for that. But thanks I will close that for now.
