### ISSUE TITLE
Zoom Cancel

### ISSUE THREAD

**Issue by eorahil** [NPBruce/valkyrie#626]
In editor mode, 
When I select a component it automatically zooms in an center on it. But if I'm working fast and I use the mouse wheel to unzoom, the zoom insists and and we go to an infinite loop.
It's frustrating the zoom in/out movement. 
I propose that, in editor mode, the recently selected component be centered but not zoomed.

**Comment by redwolf2** [comment]
https://github.com/NPBruce/valkyrie/issues/466

**Comment by NPBruce** [comment]
The loop problem should be fixed in the editor and the player.  Not changing zoom in the editor is fair enough also.

**Comment by eorahil** [comment]
* Solved loop problem. While strafe/zoom, if you move screen or change zoom (mouse wheel), the strafe/zoom is canceled.
* holding left or right shift automatically avoid/cancel strafe/zoom.
* in edit mode, selecting a component only strafes, never zoom. game mode still zooms.

Pull request sent
