### ISSUE TITLE
Randomisation

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#629]
So i found myself wanting to generate some random numbers in variables to use to trigger events.

For example say I want an event to happen randomly between round 1 and 5.

Is there a way to do this in Valkyrie? Has anyone divised a clever way of doing this?

All i can think of is having events add numbers to a variable then at round end, divide it and multiply it by a number. But it  will either have wild results or very predictable ones.

**Comment by redwolf2** [comment]
The var #rand99 gives you a number between 1 to 99.

See also "Trigger Vars":
https://github.com/NPBruce/valkyrie/wiki/ValkyrieVars

**Comment by LordPyrex** [comment]
Set an event at the start of the scenario to set a random value, such as 1-5, then have another event set a set number such as 6. Then at either EndRound or StartRound have your first variable increment by one until it equals your set variable. When the 2 variables are equal, launch your special event.

**Comment by scrubbless** [comment]
Cheers guys, I missed that in the Variables section somehow!

**Comment by scrubbless** [comment]
SOrry to re-open this, how do I set the variable #rand ?

When I create a new variable, there is no #rand on the list:

![image](https://user-images.githubusercontent.com/32058089/31820750-95ed546c-b59a-11e7-90cc-24a4daf2daff.png)

**Comment by eorahil** [comment]
Create a quest variable named as you like and set it to #rand99 if you want a your variable has a random numeric value from1 to 99

**Comment by scrubbless** [comment]
Can you explain it step by step, I can't find a "#rand" anywhere in the 1.5 app. 

I create an event
Hit Green + next to "Assign" and create a new variable
![image](https://user-images.githubusercontent.com/32058089/31842882-31bfd868-b5e8-11e7-90bd-50cf12b01487.png)

Then click the "0" to select a value and there is no option for "#rand"
![image](https://user-images.githubusercontent.com/32058089/31842911-4ded63de-b5e8-11e7-96c6-7b0596929b3f.png)

If I set the value as a number and type in "#rand99" it just comes up at "0" then sets the variable to "0" when I run the event.

**Comment by LordPyrex** [comment]
Yeah, I just realized this too. It feels like something has changed here.  I tried creating a variable and it drops the # in the clean up. I know that it can be done in the event coding, but Valkyrie won't allow it to be input for some reason...

**Comment by eorahil** [comment]
Yes.. you're right. you must find the event.ini file and change it manually. I will try to fix it.

**Comment by eorahil** [comment]
Ok. I changed the asignment of the variable. if you choose number you can insert a float number or #randXX where XX is an integer number greater than 0.
It sill upload it but don't know when will be a new version to include this change.

**Comment by scrubbless** [comment]
Cheers guys, glad im not going mad!

**Comment by NPBruce** [comment]
eorahil's fix will go into 1.6, in the mean time you can edit the ini directly.
