### ISSUE TITLE
Items in events

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#63]
It would be good to have items in events, both to place on the board and give to a player.  Currently can do this with text, but showing the item image would be better.

**Comment by NPBruce** [comment]
I have marked this as MoM, but could also apply to D2E (just less useful).

**Comment by LordPyrex** [comment]
I was thinking the same. Maybe even something like an item Spawn to show where it goes, then vanishes like monster figures do. The only difference being that you do have to have a drawer for them.
