### ISSUE TITLE
Make visible only Expansion component's Filters included in requirements

### ISSUE THREAD

**Issue by eorahil** [NPBruce/valkyrie#630]
In order to increase coherence of an scenario. There should be only the expansion filters included in the scenario requirements.
Ie: If my scenario requires base game and Forbiden Alchemy. All component filters should include only the Base and Forbidden Alchemy filters.

**Comment by NPBruce** [comment]
The reason not to do this is that you can have expansion components that aren't required.  For example a tile might be used if available, but won't be placed if the expansion isn't selected.

Also you might want to exclude Thralls (for example) regardless of if the expansion is required to prevent them appearing for those who have the expansion selected.

**Comment by redwolf2** [comment]
You could add something like ⚠ to indicate that the component selected is not in the list of required components.

**Comment by NPBruce** [comment]
Implementing under #651 .
