### ISSUE TITLE
StartRound - two events (with tests) at the same time, don't work

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#635]
I've noticed that if two events that trigger at the same time and have a Test (check if a variable is something), only one will run but components will add for both, its very odd.

If I run the same events without the tests, they run one after the other.

I've recreated this issue in the following test Scenario:
[EditorScenario1.zip](https://github.com/NPBruce/valkyrie/files/1405379/EditorScenario1.zip)

Clicking the token sets a variable to 1, end the round and the next StartRound will try to run two events that have tests to see if the variable is set to 1.

One event places its token and prints its text, the other event prints no text but places its token. The second event, if it has follow on events they will never run (because you're never given the option to click the continue button.

**Comment by NPBruce** [comment]
Nothing obvious from a code review, will have to investigate.

**Comment by NicolaZee** [comment]
I noticed this bug as well.

**Comment by NPBruce** [comment]
Fixed for 1.6

**Comment by NicolaZee** [comment]
I glad this bug is fixed as it really messes up my scenario 'In The Dark' when the number of investigators is 5.  Unfortunately the spawn of a monster occurs in the first round but this prevents the setting of MinorMythosEvents to 1.  Resulting in only Flavour Mythos events until the major kicks in.
Which is a bit unfortunate.

Is version 1.6 going to be released soon? : )
If not I'll release a new version of my scenario to work around it.

**Comment by NPBruce** [comment]
Here is the list of things I want to look at for 1.6:
https://github.com/NPBruce/valkyrie/milestone/22

I have a lot going on right now, so I don't have the time.  Short answer is probably not.

**Comment by scrubbless** [comment]
Sorry not sure how I managed that.

**Comment by NicolaZee** [comment]
I just did a quick test for this issue for 1.6.0b and it worked OK.
So it seems to be fixed.
If so, a big thanks for the quick work.  It was a nasty 'feature'.

**Comment by NPBruce** [comment]
Because 1.5 is broken I will rush out 1.6 in the next day or two if I can.
