### ISSUE TITLE
A way of detecting what investigators are selected

### ISSUE THREAD

**Issue by eorahil** [NPBruce/valkyrie#636]
In order to introduce some lore to my adventures. I would like to introduce some events only visible if an specific investigator is on it.
For example I want to introduce some easter egg event only unlockable by AshCan Pete. I want to,if ashcan is in the group show something different. but if there is no Ashcan Pete in group, show some kind of "ashcan pete could have done this". so you will get the clue to use him if you want to replay in order to unlock everything.  You will get partial victory without him, but the true total victory with the best story end will be only if an investigator is ashcan pete and he does what is suposed to do.

Is there a way of checking what investigators are ingame? Introducing new fixed triggers is needed or It could be done in other way?

**Comment by NPBruce** [comment]
Duplicates #409, no solution at present.
