### ISSUE TITLE
Content Selection

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#638]
So I am a bit confused about the content selection with First edition and the Recurring Nightmares expansions.

First edition contains the tiles and figures from Recurring Nightmares, therefore you don't need both.
So what Expansions should I select the the Scenario main page if I use these tiles?

I personally have 1st Edition, so had no need to purchase Recurring Nightmares. I could say that MoM1ET is required, but then people that don't own it and own RM instead will not see the Scenario (and visa versa).

Is there any way to link the two into one entry, since they are the same content?

**Comment by NPBruce** [comment]
Selecting both does nothing, they are separate for two reasons:

1: The official app does it this way and it should be less confusing for those with SM/RN to look in that section.

2: The conversion kit option allows you to select components, so those that want to play without minis can use the included monsters and investigators.

Internally they are linked to the same.  For your scenario you should require the conversion kit components you need (MoM1ET in this case).  If RN is selected the scenario will work.

**Comment by scrubbless** [comment]
Ohh ok, that makes sense. 
I wasn't sure so I put MoMET1 and RM, and was confused when it said I required RM (when I have all the MoMET1 items.
