### ISSUE TITLE
Limit to the number of inspect-able items 

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#640]
Is there a limit to the number of Items with the "Inspect" option, that the group can have?

If there are more than 5, any items collected thereafter will not appear in the "Items" menu. Not sure if this intended or a bug.

I have decided to work around this problem anyway as I think 6 inspect-able items is too many, however it might be limiting for some people.

**Comment by NPBruce** [comment]
There isn't a specific limit, so this is a bug.

**Comment by Hobbeslionheart** [comment]
I think there is no horizontal scroll bar so they appear, but you can't see it. One other scenario had four or five and the last one was partially obscured with no choice of a scroll bar.

**Comment by scrubbless** [comment]
There is a horizontal slide bar, I've been writing my scenario on a low resolution so 4+ come up with a scroll bar. The 6th item just doesn't appear at all.

It doesn't discriminate either, if I pick the items up in a different order its always the 6th one picked up that's missing :).

**Comment by NPBruce** [comment]
The scroll size was wrong, fixed (no limit now).
