### ISSUE TITLE
The "Equipment" Trait or Pool gives me duplicate random items

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#641]
I have found if I create a QItem with the  all other traits (Firearms, common, etc) trait or pool with randomized items, I will not get duplicate items.

However the "Equipment" trait/pool trait I have observed is giving out duplicate items.

I have starting QItems that generate from the "Common" trait/pool. The other items that generate random items from the other categories (firearms, tomes, etc) do not give me duplicate items. However the QItem that gives a random item from the "Equipment" trait/pool will frequently give out items that were given out as starting items.

I had first assumed that all randomised items were rolled up at the start of an event and could not be duplicates, but the Equipment doesn't seem to work this way.

**Comment by NPBruce** [comment]
I'll look into it.  Perhaps it is the same specific item(s) that are duplicated somewhere?  What packs do you have enabled when you see this problem?

**Comment by scrubbless** [comment]
MoMET1, MoMEM1(?), SM, BoT

**Comment by NPBruce** [comment]
FYI better not to use SM here, just use the FA/CotW elements you need.  If the user has SM enabled it will still work.

**Comment by NPBruce** [comment]
I'm having trouble reproducing this, it would be great if you could attach an example that can produce the problem if you still have one.

**Comment by scrubbless** [comment]
I can't reproduce this either anymore. I will re-open the case if I run into the issue again.
