### ISSUE TITLE
Valkyrie 1.6.0A wasn't able to find MOM or Descent

### ISSUE THREAD

**Issue by Hobbeslionheart** [NPBruce/valkyrie#642]
I installed 1.6.0A and it wasn't able to find MOM or Descent on my computer. All other versions have not had that problem. I ran 1.5 fine without any problems instead.

I'm running it on my Microsoft Surface Windows, but will test my PC shortly.

**Comment by NPBruce** [comment]
Bug feature merge, reverted.
