### ISSUE TITLE
Unable to discard items that have "Inspect"

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#644]
If an item has an "Inspect" action, if you remove the QItem, it still shows in the Items menu.

I swear using "Remove Components" and putting in the QITems, used to remove the item from this menu, or maybe I was mistaken.

Regardless, is there a way to remove a QItem from the Items menu after all dialogs have been exhausted?

**Comment by NPBruce** [comment]
Sounds like a bug, it should work.
