### ISSUE TITLE
Windows version 1.5.0 (latest version) can't locate MoM app

### ISSUE THREAD

**Issue by GermanTodd** [NPBruce/valkyrie#648]
I just can't seem to get Valkyrie 1.5.0 (latest available version) to run on my computer. It always says I need to install the Steam Mansions of Madness app even though it's already installed. I've tried running both programs at the same time but I still get the same error message. Am I doing something wrong?

**Comment by Ashgur** [comment]
Same problem here with the 1.5.0 mac version =/

**Comment by NPBruce** [comment]
Can you please try installing to somewhere your user has permissions (like the desktop) and looking for a log file in Valkyrie_Data after running?

**Comment by GermanTodd** [comment]
Okay, thanks. I just did that. What should I do with the log file?

**Comment by NPBruce** [comment]
Add it here.

**Comment by redwolf2** [comment]
... for example by dragging the file to the text box I used to type this comment. Like so...
[test.txt](https://github.com/NPBruce/valkyrie/files/1452108/test.txt)

**Comment by GermanTodd** [comment]
Okay, I hope this is what you're looking for:
[output_log.txt](https://github.com/NPBruce/valkyrie/files/1453496/output_log.txt)

**Comment by NPBruce** [comment]
This is interesting:
Could not find main assets file: C:\Users\Todd\Desktop\Games\steamapps\common\Mansions of Madness/Mansions of Madness_Data/resources.assets

It found that MoM was installed but couldn't find that file.  Does it exist?

**Comment by GermanTodd** [comment]
Well, it's not installed to the desktop, no. It's installed with the Steam apps folder.

**Comment by NPBruce** [comment]
Looks like something is going on funny with steam.  Steam registry key is telling Valkyrie that MoM is installed there.

Try running Valkyrie on the command line with:
Valkyrie -import \<location\>

Where location is where it can actually find MoM.

**Comment by GermanTodd** [comment]
How do I do that? Run the command line, etc?

**Comment by badsjames** [comment]
in windows search for  "run" it's an app. then type in "cmd" in the run program.  Use Valkyrie -import <location> where location is the steam MoM location.

**Comment by GermanTodd** [comment]
No luck. I'm about to give up.

**Comment by Hobbeslionheart** [comment]
Try downloading 1.6.0b and running that. I had problems in 1.6.0a and 1.6.0b fixed the issue.

I never had problems running the prerelease versions so I wouldn't worry about it corrupting your computer.

**Comment by redwolf2** [comment]
Uninstall "Mansions of Madness" in Steam and reinstall it again. 
It may be, that the registry key couldn't be found.

**Comment by Ashgur** [comment]
This still doesnt work on my MacBook (OSX 10.11.6). I tried to reinstall mom with steam but it didnt help.
This is strange because it did work without a problem with the version that i had before (but that was a much older version, i think it was Valk 1.2.2).

Any idea how i could fix this issue?

**Comment by redwolf2** [comment]
The current MacOS build may be broken. See:
https://github.com/NPBruce/valkyrie/issues/611

**Comment by NPBruce** [comment]
I'm going to close this and track with #611. Will try to have a look for the next release, but any MacOS developers that can have a look would be very useful.
