### ISSUE TITLE
Enhancement Request - Content selection

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#651]
Would it be possible to control the content menu's (source)
![image](https://user-images.githubusercontent.com/32058089/32499278-1206f5de-c3ca-11e7-894a-d092232afcb8.png)

Based on which Expansions you select on the main scenario page:
![image](https://user-images.githubusercontent.com/32058089/32499317-26bcf7a8-c3ca-11e7-94c2-89a35f7ad0ec.png)

So if you don't add any expansions the only the base will be White (the rest being red, or grey or whatever), on first select.

If Say RM (and Base) was the only expansions selected then the content for only these two boxes will show as white (and be listed in the right hand window) and the others would be red/grey/whatever.

Since I have all of the expansions personally, I found myself picking tiles by scrolling down the list and getting hit by inspiration (ohh the new library, I could do this and this!). So I end up with tiles of all expansions and limit my scenario's potential player base, when I may have been able to use another tile from another set.

Having an option to hide tiles for a specific expansion by default (but having the option to browse them with a few clicks) will stop me from accidentally picking tokens, monsters and tiles from other expansions, then having to retro fit them later to refine the number of expansions required.

**Comment by NPBruce** [comment]
The issue is that this isn't how the selection works.  If both 'base' and 'RN' where white then there would be nothing available because nothing is in base and RN.  For D2E there are cases where there are components in multiple sets, but this isn't what is wanted anyway.  Perhaps first there could be an alternate way of selecting traits that is an exclusion such as:

[X][   RN   ]

And selecting the X will exclude RN?

**Comment by NPBruce** [comment]
I first thought this would be simple, but redoing the selection system will take some time, so I'll bump this till later.

**Comment by scrubbless** [comment]
Sounds fair.

Just a quick not related question.

Are comments meant to not allow break lines:
![image](https://user-images.githubusercontent.com/32058089/32522390-07927fd4-c40f-11e7-8524-69ae3e323faa.png)

**Comment by NPBruce** [comment]
Please submit as another issue, will look into it.  Either it is a bug or a feature request, I agree it would be better if it did.
