### ISSUE TITLE
About scenarios in french translation

### ISSUE THREAD

**Issue by Indoy** [NPBruce/valkyrie#652]
Hi everyone, 
I'm trying to translate In Places Unseen in french. It doesn't seem have been done (hope so).
Let's see if i've done right:
- Unzip InPlacesUnseen.valkyrie
- Found, open and edit Localization.txt
- Made all translation  (trying to be as close as the author's idea)

+ Main 1st problem : 
When opening Localization.English.txt, i find many lines that don't appear in Locatilization.txt
Do i have to translate also this file (and rename in Localization.French.txt), whereas some lines are redundant?
+ Second problem:
Sometimes, it's pretty hard to completly catch the idea of the author. May I post here the different lines with the risk of spoil some questlines?
+ Third:
Have tried to test my translation, but it doesn't work... Which are the correct steps?

In the same way, i've also translated Exotic Materials and first test were ok. In this case i took inspiration from the german and the english ones. Whom specifically do i have to send the file?

I've tried to look around in the differents issues to solve all my problems but my english was probably not good enough to understand potential answers.

Thx for your replies
And of course great job for Valkyrie app

**Comment by NPBruce** [comment]
Localization.txt is an old file that can be removed from the package. It isn't used any more and can be ignored.

I'd say it is OK to post sploilers here, as long as you start the issue by saying that the following contains spoilers for a particular scenario.

How to Translate 101:

* Download the scenario in Valkyrie
* Copy the scenario in the editor
* Set your language in Valkyrie to the target language
* Open the new copy in the editor
* Edit any text and save the scenario

From here you should get a Localization.\<Language\>.txt for your chosen language.  You can add entries to here and they will be used instead of the default language when available.  You can either edit this file manually or using the Valkyrie editor.

Once you are done you will need to send this file to the original author for approval/inclusion.  I recommend getting in touch with them before you start just in case.

In Places Unseen is by LordPyrex:
https://github.com/LordPyrex

Exotic Materials is mine, I would be happy in include a french translation.

**Comment by Indoy** [comment]
Hi!
Ok i'll check all of this ASAP
Many thx

**Comment by redwolf2** [comment]
@NPBruce 
Maybe we should recommend, that scenario creators also place the source files in the same repo as the scenario. That way changes can be tracked better and pull requests make clear what has been changed.

**Comment by NPBruce** [comment]
I would like to leave that up to the creators, even github and version control at all isn't a requirement.  It could certainly be a best practice though.  Mine are under source control, but they source repo isn't the same as the packaged/published repo, because that is my preferred work flow.

**Comment by redwolf2** [comment]
@NPBruce @LordPyrex 

OK, I added it in.

> If you go for github, it is a good idea, to place the extracted package files somewhere in the same repository. That way changes to the source files can be tracked better and other users might supply fixes, collaborative changes or translations of your scenario (only if you wish).

**Comment by redwolf2** [comment]
@Indoy In next to all scenarios the English file is the master file. For example all text that is not translated in the German translation file  (child file) will be taken from the master file. That is the reason the child files are much smaller. In most of the cases all lines, which value start with `{qst:` don't have to be copied to the child file. Also all lines that don't need to be translated, don't need to be copied over. Also make sure to add your language file to the `quest.ini`:


```
...

[QuestText]
Localization.English.txt
Localization.Spanish.txt
Localization.German.txt
Localization.French.txt

...
```

**Comment by LordPyrex** [comment]
I'd be glad to include a translation. Please let me know what lines I can provide information for.

When complete I'll be glad to add it into my master directory.

**Comment by Indoy** [comment]
@LordPyrex 
Hi 
Translation done! but i still missing something:
- Line "EventStatuePullFail.button1,Continuer" has no "EventStatuePullFail.text"
- Line "EventBodySlump.text", the sentence seems incomplete (The spirit of Bobby...)

I've got some trouble to understand the meaning of :
- EventStatuePullPass.text : "You will yourself to move and using as much momentum as you can muster fling yourself out of the energy"
- EventInterHorrorCheck6.text : "you see through the cheap glamour for what it is"

Thx you very much!
Regards

**Comment by Indoy** [comment]
@NPBruce 
Here's one! I'll check IG to see if everything was ok. Hope it will!

Matière Exotique
[Localization.French.txt](https://github.com/NPBruce/valkyrie/files/1457321/Localization.French.txt)

**Comment by NPBruce** [comment]
I have added, it is available on the download page.  I did remove the quest.description entry, because the translation was just the title again which isn't useful, so you will see the english description.

**Comment by Indoy** [comment]
Oh sorry...my fault
Quick repair
[Localization.French.txt](https://github.com/NPBruce/valkyrie/files/1457425/Localization.French.txt)

**Comment by LordPyrex** [comment]
@Indoy Nice catch on those missing lines. I'm guessing when I was working on the files to do an update I somehow removed those lines. If you do an update on the file you will now have the intended text.

EventStatuePullPass.text - This can be summed up as 'finding the strength to through yourself out of the energy'
EventInterHorrorCheck6.text - The cheap glamour refers to the transformation into bugs being a spell that you are able to see through, so that it doesn't terrify you.

If you have any other lines, please let me know!

**Comment by Indoy** [comment]
@LordPyrex 
Hi thx a lot!
Done! Hope everything will be fine!
I'll do some extra correction if i see anything in playing deeper the scenario!
I didn't take the lead to put my name as translators, i let you do it as approval! =)
Thx andgreat job for your scenario
... et si des Français voient des erreurs, n'hésitez pas à me le dire!
In Places Unseen
[Localization.French.txt](https://github.com/NPBruce/valkyrie/files/1460597/Localization.French.txt)

**Comment by LordPyrex** [comment]
@Indoy I have added your translation into the scenario master. Of course I intend to give you credit as translator and appreciate you taking the time to do that! It's really an awesome feeling when someone wants to help get your work out to more people.

That being said, I am closing this issue as I believe that it is resolved. You can still use this thread to discuss or provide updates to these scenarios as you see fit. Thank you again!

**Comment by Indoy** [comment]
Hi!
@LordPyrex 
But may I post here others french translation, or am I supposed to open an issue for each one?

In Sly Cozz's scenario there's this line I find : 
Line : TokenBalconyDoor.button1,TokenBalconyDoor.button1.
Does someone know if something wrong? I don't know if Sly Cozz will be able to see that (i didn't find his tag with @...)
Translation is ready after that!

Regards

**Comment by slycozzolino** [comment]
@Indy 
the Line: TokenBalconyDoor.button1,TokenBalconyDoor.button1. is from a button defaulting to a door. It does nothing. You can leave it.

It is not possible to attack through the barricade. The player would have to move the barricade using their strength based on the normal rules for barricades. The investigator would also have to move into the closet as its separated from the bedroom by a door.

Thanks for you work translating this.

**Comment by Indoy** [comment]
Hi , thx for replying
Here's the file 
[Localization.French.txt](https://github.com/NPBruce/valkyrie/files/1464888/Localization.French.txt)
As I said to LordPyrex, If anything IG seem to be corrected i'll tell you.
Regards
