### ISSUE TITLE
Unable to enter break lines in comments

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#653]
At present it appears that comments cannot have break lines in them, instead they come up as \n

![image](https://user-images.githubusercontent.com/32058089/32522795-a6b8849a-c410-11e7-8118-f2cb4475d73b.png)

This is the case in 1.5 and 1.60a.

**Comment by NPBruce** [comment]
Too much in the 1.6 list and pressing issues to release.
