### ISSUE TITLE
Enhancement Request: Alphabetical sorting of item types

### ISSUE THREAD

**Issue by Hobbeslionheart** [NPBruce/valkyrie#655]
Wondered if the starting items could be alphabetically organized by type. So common items in alphabetical order, then unique items, then spells. A bubble sort based on the item name and type or if needed, to go into each asset and assign a value that can be sorted. Problem with the latter is that when new expansions come out, numbers have to be adjusted, but it wouldn't be that too hard if using existing names and types would not be possible.

Not at all urgent, but something that come up when playing recently.

**Comment by NPBruce** [comment]
Simple to do, but going to fix the 1.4 white screen issue first...
