### ISSUE TITLE
How do I read the debug error messages?

### ISSUE THREAD

**Issue by NicolaZee** [NPBruce/valkyrie#661]
With the Valkyrie Scenario Editor there is a very useful button labelled 'Save & Test' which saves and runs the scenario in debug mode.  Lots of useful debug messages are added to the log.

How do I get these types of debug messages to be added to the log outside of the Scenario Editor?
When running a standard scenario I tried clicking 'alt+d' key combo and there was no special messages added to the log.

In addition, if I am loading a MoM scenario and it has an issue, please can someone tell me where is the log located where I can check if it has loaded in OK?

**Comment by NPBruce** [comment]
Did you use alt+d while the log window was displayed?  What version are you running?  Do you see the variable list?

The full log is in save games, so save and you can extract the save as a zip (or attach here).  If you can't get that far (not sure what you mean by 'loaded') the Valkyrie log should have some info, but also please upload the scenario here so I can see what is breaking.

**Comment by NicolaZee** [comment]
I have now tried alt-d with the log window displayed and it does display the variable list.
So thanks for the reply as this is very useful info.

The reason I raised the issue was not because my scenario was broken but because I could not get the saved scenario to work correctly because of a bug in Valkyrie.

When Valkyrie has a bug, what is the quickest and dimpliest way to view any error messages generated.

**Comment by NPBruce** [comment]
Game breaking bugs will likely end up in the Valkyrie log (in valkyrie_data), but no promises you will get anything useful there.  If it is a bug it is because we didn't expect it, so we can't tell you want went wrong.

Logging in general could be improved.

**Comment by NicolaZee** [comment]
Thanks that is useful information.  At least I know where to look and the messages may take a bit of searching in that file to find.

I think we can all agree 'Logging in general could be improved.'

I'm currently in the middle of developing a couple of scenarios but once (or if) I ever manage to finish them - with your permission - I might have a go at improving the logging.
e.g. Adding things like error codes for the usual suspects.
Your offer to check each scenario with issues shows great dedication but (as Valkyrie becomes more popular) you may find it becomes less practical to do this.

**Comment by NPBruce** [comment]
There are two reasons I do this.  One is that I have the development environment, which makes it much easier to see what is happening.  Two is that I want to know about and diagnose the bugs so that they can be fixed in Valkyrie, not just work around the current user's problem.

**Comment by NPBruce** [comment]
A side note on logging improvements - one of the main limitations is the Unity log system we are using, which is pretty bad.  An important first step would be to stop using this and have a separate Valkyrie log (I was suprised that there is no good included way in Unity, but apparently that's how it is).
