### ISSUE TITLE
Sylvia Marsh Token is not correct

### ISSUE THREAD

**Issue by Hobbeslionheart** [NPBruce/valkyrie#664]
The person in the sight token should be Sylvia Marsh. I'm pretty sure it was correct before as one of the scenarios (Lair of Rlim Shaikorth) used her token.

![image](https://user-images.githubusercontent.com/26637617/32704238-e8cfbcaa-c7cf-11e7-8aea-38d55da3cc97.png)

**Comment by NPBruce** [comment]
There were all redone for MoM 1.5 (Valkyrie 1.6), so the bug will be new.

**Comment by NPBruce** [comment]
Othera Gilman is also wrong (has the Sylvia Marsh image)
