### ISSUE TITLE
Please Publish my Scenario - Stress and Strain when Valkyrie 1.6 is released

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#665]
Hello,

I have completed my Scenario - Stress and Strain.

I have uploaded it to GitHub at the following location:
https://github.com/scrubbless/PublishedScenarios/tree/master/Stressandstrain

Can you please publish this when the 1.6 version of Valkyrie is released (as it requires the multiple EventStart's bug to be fixed).

If anyone wants to download it and play it prior to 1.6, make sure you use the 1.6.0a pre-release of the Valkyrie application.

Enjoy!

P.s. If anyone would be kind enough to translate this, please create an issue with the Scenario's name in my repository (https://github.com/scrubbless/PublishedScenarios/issues) and drop your translation there. Also if you notice any errors or bugs in the scenario please also post them there.

**Comment by NPBruce** [comment]
Hi,

Can you please resave your scenario in 1.6.0b or 1.6.0c?  The reason is that these have the format bumped which will prevent your scenario from being playable in 1.5 and 1.4.  Once this is done I can add it to the download list now, and anyone with 1.6.0b or later will be able to play it.

For more on format forward/backwards compatability see here:
https://github.com/NPBruce/valkyrie/wiki/QuestFormat

Thanks.

**Comment by scrubbless** [comment]
Thanks Bruce, all done - saved in 1.6.0c

**Comment by NPBruce** [comment]
Your thumbnail is Splash.png but the quest refers to splash.png.  Under windows this doesn't matter, but on the internet (and other platforms) it does.  I have listed it, but it doesn't show because of the broken image reference, fix this and it should work.

**Comment by scrubbless** [comment]
Thats odd, its showing as lower case in the scenario and my repo:
![image](https://user-images.githubusercontent.com/32058089/32751662-975696e2-c8be-11e7-9ec1-eddc63957de6.png)

![image](https://user-images.githubusercontent.com/32058089/32751577-58d6ff42-c8be-11e7-9af2-714d07ec0fd5.png)

**Comment by scrubbless** [comment]
It hasn't shown up in the download list (using 1.6.0d).
(moved my editor copy so it wouldn't show, then hit download and its not there).

Cheers for looking at this, no worries about the time frame - whenever you get the time.

**Comment by NPBruce** [comment]
Fixed!
