### ISSUE TITLE
Is there a way to sort events?

### ISSUE THREAD

**Issue by Crispy66** [NPBruce/valkyrie#667]
I looked through the issues and have not seen this asked.  Sorry if it has, or if there is already a way to do this that I have not found.

As a scenario becomes larger and larger, I spend more and more time looking for the right event to link to, as the list keeps growing.  It appears that the list is generated top-down as each event is created, so finding the right event means remembering when it was created.  If events could be sorted alphabetically, finding them would be much easier.  I figure I can do this by messing with the .ini files, but I'm relatively inexperienced as a programmer and fear I would screw something up.  Also, it would have to be done every time I finished working on a given scenario, or at least frequently, or it becomes useless.
Alternately, could the program list the events with the most recent event at the top?  Then we don't have to scroll to the bottom of the list every time we are looking for the most recent events.
This applies to other lists as well, but the events list is the longest.

**Comment by Hobbeslionheart** [comment]
If you click on tools, you'll see reorder components

![image](https://user-images.githubusercontent.com/26637617/32707260-8b30c686-c7f0-11e7-8691-3165ee424b04.png)

Click on the events.ini

![image](https://user-images.githubusercontent.com/26637617/32707274-a41a2c5a-c7f0-11e7-9ab8-477267fe7ea0.png)

This provides a way in the editor. I do see the advantages of the most recent at the top, but on the other hand, doing it in descending order allows for a clearer picture of the first event to the potential last event.

One way of organizing events is to isolate them by tile. So I number my tiles 1-10, then I associate each token, event, and item that is found in that tile with the prefix 1. That way, when it gets out of sorts like when I add events after the fact, I can easily resort them.

**Comment by NPBruce** [comment]
There also also the file feature which is intended to be used to organise large numbers of components.  For example, by default events will be placed in events.ini, but you can move them to foyer.ini.  You can then include all events, tiles, tokens, spawns, puzzles related to the foyer in this file.

Files can be called anything so you can organise however you want.

**Comment by NPBruce** [comment]
Seperate to the way these are stored on disc, the GUI could have sorting added.  I have created issue #668 for this, and will close this issue.
