### ISSUE TITLE
Stress and Strain : Translations Requests

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#672]
Hi Guys, 

I have completed a Scenario and would be awesome if someone (who is able) could translate it to other languages.

How do you deal with translations? Are people expected to just link their translated localisation files as an issue or should we be requesting them?

I have a repository for my Completed Scenarios and invite people to post issues on any bugs, issues or translation offers:
https://github.com/scrubbless/PublishedScenarios/issues

**Comment by redwolf2** [comment]
I might translate it to German, when I have more time at hand.

See the translation guide here (The seciton "Scenarios/Quests"): https://github.com/NPBruce/valkyrie/wiki/Translations

**Comment by scrubbless** [comment]
Appreciate the offer Redwolf2, if you get time it will be most welcome.

**Comment by Indoy** [comment]
I'll do also translation in french ASAP

**Comment by scrubbless** [comment]
Thank you Indoy! Much appreciated.

**Comment by Indoy** [comment]
@scrubbless 
Hi, 
Am I missing something ? I created as usual a Localization.French.txt and add the line in Quest.ini. But impossible to see any changes once IG. French isn't here...

**Comment by redwolf2** [comment]
Is the first entry in your localization file `.,French`?

**Comment by Indoy** [comment]
Yes, everything was fine as i did others translations this way... don't understand...

**Comment by redwolf2** [comment]
If all fails, zip it up and post it here.

**Comment by redwolf2** [comment]
There is a bug in the scenario text at this line:

```
EventGreenVialInspect.text,The solution in this vial is Green, the label reads "7334".
The solution in this vial is Green, the label reads "7334".
```

**Comment by redwolf2** [comment]
Here are some problems of the original translation:

```
WARN: key with spaces in it on line 26
WARN: key with spaces in it on line 27
WARN: key with spaces in it on line 29
WARN: key with spaces in it on line 30
WARN: key with spaces in it on line 117
WARN: key with spaces in it on line 263
WARN: key with spaces in it on line 300
WARN: key with spaces in it on line 303
WARN: key with spaces in it on line 305
WARN: key with spaces in it on line 389
WARN: key with spaces in it on line 390
WARN: key with spaces in it on line 505
WARN: key with spaces in it on line 506
WARN: key with spaces in it on line 507
WARN: key with spaces in it on line 508
WARN: key with spaces in it on line 509
WARN: key with spaces in it on line 510
WARN: key with spaces in it on line 514
WARN: key with spaces in it on line 515
WARN: key with spaces in it on line 516
WARN: key with spaces in it on line 517
WARN: key with spaces in it on line 518
WARN: key with spaces in it on line 522
WARN: key with spaces in it on line 523
WARN: key with spaces in it on line 524
WARN: key with spaces in it on line 525
WARN: key with spaces in it on line 985
```

**Comment by Indoy** [comment]
Ok your solution works redwolf2.
Here's i guess my fault : because i prefer doing translation on Ooo Excel, I separated the beginning of each questline after the "," by a space with TAB. Doing so i have two distinct columns which i find more useful for translate faster. May it be come from that? (Hope my english is clear...)

**Comment by scrubbless** [comment]
@redwolf2 
His redwolf, I am not sure what these errors even mean. Can you point me in the right direction to fix these errors?

**Comment by redwolf2** [comment]
Yes, that's what i meant. There is text, without a key infront of it (like the text in red).

**Comment by scrubbless** [comment]
> Yes, that's what i meant. There is abbandoned text, without a key infront of it (the text in red). I don't know the cause, but it may be (like you suggested) the space infront of the line break. This may be an yet unknown issue. Normally this would only be a minor formatting issue.

I wonder if its something with Unity, when I googled the errors I saw a log of issues from GitHub repo's using Unity. Is it linux based? Probably just a syntax error. I use break lines, to separate dialog from insturctions, which I know the main game doesn't do. I have also been known to write dialog on the train (on my phone) so it may also be a copy paste issue from Google Keep.

I noticed some random issues in 1.5 when I would enter text and click out of the dialog, only to find it had disappeared (it was about the time when I first started writing this Scenario) maybe it was a bug in 1.5 thats since been worked out?

> Offtopic: I use Notepad++ with the spellchecker addon, too ^^
Haha! Its handy! (and free, I like free)

Thanks for the help guys, great community. Wish I could contribute a bit more with translations and the like... But not much call for English to English translations ^^

**Comment by redwolf2** [comment]
https://github.com/NPBruce/valkyrie/issues/700

**Comment by StevenP94** [comment]
Hi Guys, I can made an italian translation if you want.
I've already translated 'The Truth' ()just to make practice) and made a couple of Arkham Horror LGC campagnain translation too.
Just let me know if I can help.
Cheers.

**Comment by scrubbless** [comment]
That would be really appreciated! Thanks :)

**Comment by redwolf2** [comment]
I will close this for now. Y'all can always continue the discussion even on closed requests, create a new issue or ask for reopen.

**Comment by scrubbless** [comment]
Thanks @redwolf2

No need to leave lingering threads open
