### ISSUE TITLE
The Lair of Rlim Shaikorth : French translation

### ISSUE THREAD

**Issue by Indoy** [NPBruce/valkyrie#676]
@sodapaps
Hi, 
Translation done but some question remain:
- TokenAmmi2.text,Ammi Pierce (something's missing to complete the phrase?)
- Tokens.png during introduction can't be translated, may it be possible to create un questline to show a windows instead with translated speech inside?
- Dog's token isn't correct in the beginning of investigation.
- {c:QItemPaperItem03} (appears like that IG) doesn't match correctly to photographic evidence text.
- In the dinig room, during the dessert, some event mention Sylvia Marsh in front the cellar's door, but there's no tokens for her.

Intense scenario and well written! Congrats
Waiting for your reply to post the translated file.

Regards

**Comment by sodapaps** [comment]
I am on a business trip, but when I get back I look into this. Thanks for
the translation!

**Comment by Indoy** [comment]
@sodapaps 
Hi did u have some time to have a look ? =)

**Comment by sodapaps** [comment]
Sorry. I haven't. I will this weekend. Thank you for the reminder.

**Comment by Indoy** [comment]
@sodapaps 
Hi do you have some time? If not maybe could I post the file however? tell me =)

**Comment by sodapaps** [comment]
Yes. Please do. I apologize. Haven't had much free time.

**Comment by Indoy** [comment]
[Localization.French.txt](https://github.com/NPBruce/valkyrie/files/1609054/Localization.French.txt)

**Comment by Indoy** [comment]
@sodapaps 
Hi! I've posted the file, you add it =)
Thx!

**Comment by Indoy** [comment]
@sodapaps
Hi! I've posted the file, you add it =)
Thx!

**Comment by sodapaps** [comment]
I am so thankful for the work you put into this. I'm sure it's frustrating
that I haven't held up my end. Truth is, the last four months I haven't had
access to my computer because of my living situation. I have been in
treatment for mental illness and addiction. I was embarrassed to say
anything. I know. Heavy stuff to share with a stranger. I just wanted you
to know it's not because I don't appreciate the effort you put into this.

The good news--i graduate today!!! So, I'm going to look at this soon. I'm
excited to finally see it and add it. AND I'm excited to be able to use my
computer again instead of only being allowed to check my email from time to
time on old, institutional computers! Can't wait to start creating again.

**Comment by Indoy** [comment]
Hi!
Of course it's a very comprehensive situation, and I appreciate you've shared some personnal situation. I wish you a speedy recovery!
However if you want to check my former questions later, I will add corrections in the time. If you want add the file as it, feel free also to do it!
Best regards!

**Comment by sodapaps** [comment]
Ok. Done. I'm not sure what to do next. Am I supposed to let people know
there is a new translation?

**Comment by Indoy** [comment]
Hi! 
Don't know what to do next sorry... You should probably look at the wiki or ask for help...
At the moment your scenario doesn't appear in french when downloading it.

**Comment by sodapaps** [comment]
Ok. Try it now. I think I got it figured out. It's working on mine, at
least, and when you go to download scenarios it is listed as an "update".

Thanks for your hard work. It looks great.

Now, I'll go back to your original suggestions and see what I can do.

Peace,
Howie

**Comment by Indoy** [comment]
Hi!

It works fine to! But I can't see any contribution. May it be possible in order to mainly permit french people to contact me for a better enhancement of my translation (don't know if it's clear... it's late) ? If not, that's not a problem!

I'm still on work if you consider my original suggestions! I don't let you down :p!

**Comment by sodapaps** [comment]
Argh. I tagged you the first time I tried it. I'll add it back. Forgot the
second time.

**Comment by redwolf2** [comment]
I will close this for now. Y'all can always continue the discussion even on closed requests, create a new issue or ask for reopen.
