### ISSUE TITLE
Token Catagories

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#677]
I have noticed that there are only three catagories for Tokens:

Base
BtT
SoA

![image](https://user-images.githubusercontent.com/32058089/32996588-7f003518-cd7c-11e7-8207-0cb88cc8cf93.png)

However some of the tokens are from Reoccurring nightmares (MoME1*), for example Eric Colt shows as a "Base" token, but he is actually from the aforementioned expansion.

**Comment by NPBruce** [comment]
I think I had it in my head these were in the conversion kit, but I was probably confused?

Maybe they should just be removed, provided no existing scenarios use them?

**Comment by Hobbeslionheart** [comment]
I think keeping those tokens is not an issue. If we have them, why don't we use them? 

It just goes back to the need for better classification which I suggested earlier. Once I finish my scenario, I will work on the classification for tokens unless Scrubless wants to help?

**Comment by NPBruce** [comment]
Ref #666

**Comment by scrubbless** [comment]
Ok so it took me 5 un-boxing videos but I found it.
Yes those tokens are in the Conversion kit, 100% base game content. 
![image](https://user-images.githubusercontent.com/32058089/33014199-6a5d1f38-cdde-11e7-9e4f-adfbdc80f315.png)


Sorry I completely forgot about the conversion kit.
