### ISSUE TITLE
Bug in a Mythos event

### ISSUE THREAD

**Issue by Hobbeslionheart** [NPBruce/valkyrie#678]
![image](https://user-images.githubusercontent.com/26637617/33002113-05b5606c-cd80-11e7-8361-d95656a5f6f2.png)

[save2 - Copy.zip](https://github.com/NPBruce/valkyrie/files/1486436/save2.-.Copy.zip)

**Comment by scrubbless** [comment]
I have seen a similar error but the dialog just says:

{0}

I think its in deadly Mythos.

**Comment by NPBruce** [comment]
This specific event is:

PerilYouDidThis

And the bug is when text that has an ALT query for females contains a ':' character.

(Not sure about scrubbless' case, could be the same thing)
