### ISSUE TITLE
Request for Attack and Defence to be added as Traits for Spells

### ISSUE THREAD

**Issue by NicolaZee** [NPBruce/valkyrie#681]
This is very much a non-urgent minor enhancement request.

My scenario 'In the Dark' contains two random Spell Items, one an attack spell and the other a defence spell.

[QItemAttackSpell]
itemname=ItemSpellFeedTheMind ItemSpellInstillBravery ItemSpellArcaneInsight
starting=False
traits=spell

[QItemDefenceSpell]
itemname=ItemSpellShriveling ItemSpellWither ItemSpellWrack 
starting=False
traits=spell

Whenever FFG releases an expansion that includes a new spell, I have to update the two lists.
Please can a new trait be added to spells to separate the attack spells from the defence spells?
Then the code for the event could be changed to something like the following:

[QItemAttackSpell]
starting=False
traits=spell attack

Aternatively, is it possible for an Item to have an option to specify which of the list of items the random item could be - as opposed to the ones the item cannot be.  

e..g Something like the following

[QItemDefenceSpell]
 itemname=ItemSpellFeedTheMind ItemSpellInstillBravery ItemSpellArcaneInsight
 starting=False
 traits=spell
 fromitemlist=true   <- New

**Comment by NPBruce** [comment]
Happy to add the traits, please make changes as appropriate to here:

https://github.com/NPBruce/valkyrie/blob/master/unity/Assets/StreamingAssets/content/MoM/base/items.ini
https://github.com/NPBruce/valkyrie/blob/master/unity/Assets/StreamingAssets/content/MoM/btt/items.ini
https://github.com/NPBruce/valkyrie/blob/master/unity/Assets/StreamingAssets/content/MoM/soa/items.ini

**Comment by NicolaZee** [comment]
Thank you for your quick response.
So just to confirm I understand Traits correctly (and so I don't break anything) I can just add the new trait spelldefence and spellattack to each spell?

e..g.
[ItemSpellWrack] 
name={ffg:SPELL_WRACK} 
image={import}/img/Spell_Wrack.dds 
traits=spell spellattack

**Comment by NPBruce** [comment]
Yep.

**Comment by NicolaZee** [comment]
I have created 3 pull requests.
Please can you have a check and merge them and I'm happy for my issue to be closed.

**Comment by NPBruce** [comment]
I have manually merged and closed the pull requests.  FYI you can create 1 pull request with multiple files.  Also most changes merge into the 'development' branch, 'master' is used for released version.

**Comment by redwolf2** [comment]
@NicolaZee Sry again, for the confusion.
