### ISSUE TITLE
Trigger on variable reaching a certain number?

### ISSUE THREAD

**Issue by arrwzy** [NPBruce/valkyrie#693]
Building a scenario now where the investigators run around the house trying to find 4 of an item. When they reach 2 and 3, I want to spawn monsters. Is there a way to trigger an event when a variable reaches a certain number? I've currently implemented an "ugly" fix where the check occurs at the "end" of turn, but I'd like it if it could potentially spawn the monster "mid-turn" if theres a way to do it?

**Comment by NicolaZee** [comment]
Valkyrie is event driven and every event needs some kind of trigger.
Having a StartRound trigger is no more an "ugly" fix as using any other trigger.

If you want the spawn to be triggered mid-turn, you will need a trigger that can be detected mid-turn.
For me - and this is just my opinion - the trigger that is most obvious is that of finding the 2nd (or 3rd)item.
So add a call to your spawn event to each of the 4 places where the items are found.
In the spawn event add a condition check for number of items found.

 I hope you find this advise helpful.

**Comment by scrubbless** [comment]
I would personally trigger the monster spawns after you collect any of the quest items. Then on that events(s) that are being triggered test to see if the variable == 2 (and a second event for) == 3. This will spawn it instantly and avoid any loops. Also having it trigger on every quest item collection (even if it won't run on the first or fourth) means it doesn't matter what order the players pick them up in.

**Comment by NicolaZee** [comment]
That's OK.   No apologies needed.  I'm very easy going.  :  )

Your explanation is much clearer and more explicit.
I tend to give a broad explanation because (I believe) that way people find their own solution.
But it's always nice to have the work done by somebody else.

**Comment by arrwzy** [comment]
Whoah, did not expect responses this fast, this repo is more active than I thought. Thanks for the advice, I think I'm gonna go with the variable test on pickup solution you guys mentioned. Still getting a bit used to Valkyrie, feels like programming using only goto or something.
