### ISSUE TITLE
Enhancement Request - Write to variable and Print Variable

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#694]
I found myself in a scenario wanting to pick an investigator and call them out at several times in the scenario. However I don't believe its possible.

The way I think it could be achieved is two fold.

1. Allow the {rnd:hero} to be entered as a variable (not sure if there are character limitations in variables)
2. Allow a variable to be printed in dialog (aka {c:VariableName}.

The second part would also be helpful with an idea I had about a scoring system. If I could tally a score in a variable (+ and - based on the events chosen), then I could print the variable at the end of the Scenario.

The print option will also be required in the buttons, as I have noticed that some things cannot be referenced in buttons, for example QItems:
![image](https://user-images.githubusercontent.com/32058089/33329348-3d7c84d2-d454-11e7-8fde-bd16be982881.png)

**Comment by NPBruce** [comment]
This can be done:

https://github.com/NPBruce/valkyrie/wiki/QuestIniEvent#sectionnametext :

> {var:<Var>} can be used to fill in a Var value.

> {c:<EventComponent>} can be used to the selected hero (through manual selection or rnd:hero), only shows first hero.

Unless I am not understanding something?

**Comment by NicolaZee** [comment]
Sorry but I am confused about how the solution works.  On the other hand confusion is my normal default state.  : )

I don't see how {var:<Var>}  can help fill in the name of the investigator.  As far as I know variables cannot contain strings.

rnd:hero would fill in the name of the investigator but repeated calls may return different names?

{c:<EventComponent>}  might work for investigators.   I don't know much about how to use this to return a name of an investigator.

**Comment by NPBruce** [comment]
Event1: use {rnd:hero}

Event2: use {c:Event1}

**Comment by NicolaZee** [comment]
OK got it now.
Very clever.
Thanks. : )

**Comment by scrubbless** [comment]
Ok cool, so I have it working, but with one oddity.

If I fill the variable in an event using {var:<Var>}, it comes up with "0" when the event runs:
![image](https://user-images.githubusercontent.com/32058089/33368845-b18bdd78-d4ea-11e7-9451-fce838d26861.png)

After this event if called it shows the correct investigator (I did two events calling it to be sure).
![image](https://user-images.githubusercontent.com/32058089/33369021-39cb44f8-d4eb-11e7-961b-cdba1c68e0e3.png)


Is there a way of doing this without the first event spitting out "0"

**Comment by NPBruce** [comment]
I'm confused, why are you using var?  Perhaps attach an example scenario?

**Comment by scrubbless** [comment]
Yeh im confused too! haha

I used {var:{rnd:hero} sorry was lazy typing. I don't think i'm quite getting this concept!
[EXAMPLE.zip](https://github.com/NPBruce/valkyrie/files/1513627/EXAMPLE.zip)

**Comment by scrubbless** [comment]
Ok I am compeltely getting this mixed up, I think I understand now.

So I create an event and call {rnd:hero}, to select the hero in dialog. then I call that event and it will always use the random hero from that event?

![image](https://user-images.githubusercontent.com/32058089/33373431-c9e4ecca-d4f9-11e7-9843-f7ce3bae603a.png)

![image](https://user-images.githubusercontent.com/32058089/33373443-d5f1c254-d4f9-11e7-9b43-f4c9913938e1.png)

**Comment by NicolaZee** [comment]
Correct
The {var: was a red herring.

**Comment by scrubbless** [comment]
Now the question is, but do I do hero manual selection? :D

> {c:<EventComponent>} can be used to the selected hero (through manual selection or rnd:hero), only shows first hero.

**Comment by NPBruce** [comment]
You can't in MoM. In D2E there are hero icons on the screen you can select. In MoM there isn't a way to do this.

**Comment by scrubbless** [comment]
Ok no worries, happy to program around that. All the ideas i've had so far use random character selections anyway.

**Comment by scrubbless** [comment]
Closing this off then. 
Thanks for the help @NicolaZee and @NPBruce ! 
As every an amazingly helpful community :)

**Comment by scrubbless** [comment]
Sorry to re-open, I have just seen that {c:Event1} doesn't work in UI elements, is there any way to enable it?

For example, I can add a random hero:
![image](https://user-images.githubusercontent.com/32058089/33389044-973ad408-d529-11e7-889f-64e3ba8634e4.png)
![image](https://user-images.githubusercontent.com/32058089/33389120-c1b7be4e-d529-11e7-915f-77e97dc6cc62.png)

Then call the variable in an Event, no worries:
![image](https://user-images.githubusercontent.com/32058089/33389072-a6c5fa2e-d529-11e7-8f8d-0095d9dc504b.png)

But I can't use the same call in a UI element:
![image](https://user-images.githubusercontent.com/32058089/33389096-b8f2a72e-d529-11e7-87dc-929a212564f3.png)

![image](https://user-images.githubusercontent.com/32058089/33389137-ce5b93fa-d529-11e7-880e-97709ff085b0.png)

**Comment by NPBruce** [comment]
Done for next build.
