### ISSUE TITLE
What does the "investigator attacks" section in the custom monster screen do?

### ISSUE THREAD

**Issue by Crispy66** [NPBruce/valkyrie#698]
That is the question.

Also, is this the best place for questions like this?  I don't want to clutter this up with simple questions as opposed to real issues, but I don't know where else to ask.

Chris

**Comment by NPBruce** [comment]
https://github.com/NPBruce/valkyrie/wiki/QuestIniCustomMonster#attacks-format-9-mom-only

For when you want to change what happens when the investigators attack the monster.

Clutter is fine, I can categorise and close things.

**Comment by Crispy66** [comment]
I can't get anything to happen when I press the '+' sign.  Do I need to edit this manually in the .ini file?

**Comment by redwolf2** [comment]
https://github.com/NPBruce/valkyrie/issues/741
