### ISSUE TITLE
Is there a tutorial for custom images?

### ISSUE THREAD

**Issue by Crispy66** [NPBruce/valkyrie#705]
I have inserted an image (200x200) to represent a custom monster.

I need to insert an image for a custom item, both for common items (cards) and for QItems (to interact with in the Items menu).  I have been tinkering with the .ini files, and looking at other people's work, but can't find any examples.

**Comment by NPBruce** [comment]
Items are included in content packs, so others won't have access to any custom items you create.

See #519 for support for custom content packs that will allow extra custom content.
