### ISSUE TITLE
How to add a Translation

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#707]
Hi Guys, 

Indoy has kindly translated my scenario into French, however I am not sure of the process to get this added into my master copy.

I have added the localisation file to the scenario folder, opened it in editor, saved it (added some acknowledgement text) and created a package, then updated this. The update reflects the text I have added, but I can get the French translation to show up (if I change language to french).

What is the full process to add a translation to a scenario, I can't seem to find a mention on the Wiki

**Comment by LordPyrex** [comment]
So, once you've added the Localization.French file to your scenario folder you will have to manually edit you Quest.ini file. Under Quest Text add Localization.French.txt. This tells Valkyrie that if French is selected as the language use this file. 

All you have to do from there is create a new package from the tools section of the scenario editor and upload it over top of your previous scenario. Anyone who chooses to update will get the new information and will be able to select what ever is available. If they chouse a language that is not included then it will use the default language.

**Comment by LordPyrex** [comment]
There is a little bit of information in the wiki under. [Translations](https://github.com/NPBruce/valkyrie/wiki/Translations)

**Comment by scrubbless** [comment]
Thanks for the assistance @LordPyrex, i've done that now French has been added!

I'll add a section in my Tutorial
