### ISSUE TITLE
The Robbery Of The Kadakian Idol : French translation

### ISSUE THREAD

**Issue by Indoy** [NPBruce/valkyrie#727]
@prilogon
Hi !
Translation will be ended after a couple of things:
- EventMito18B.text, aren't the effect of success and fail inverted?

- When you try to escape the mansion (with the Idol) and click on the interact token (main entry):
U can make a testagility
	If u succeed, => ok no problem
	If u failed, you have a second test (EventFailAgilidadeP.text)
		If u failed, the butler hits you, => that's ok
		BUT If u succeed, the effect is EventPassForcaP.text, and it refers to a monster which escapes but is not on the board. what did I miss?

- I think there's a problem when you have been caught by the butler. If u loose back the Idol, there are several Research token that appear.
But when you click on them and there's nothing, it refers to REMOVEWALLTOKEN,"Retirez le jeton Mur." whereas it should be REMOVESEARCHTOKEN no? 

- When trying to escape from the library, you can force South door, but if succeed {qst:EventPassAbrirLeitura.text} appears.

Thx for replies!

**Comment by redwolf2** [comment]
@Indoy 

You may reach him in the portugese translation group
https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2Fgroups%2F178924655968738%2F#_=

**Comment by prilogon** [comment]
I dont know english enough to answer this questions, but I will try:

- No, it's correct... It's a joke, you just notice if you pass (if you have good observation, so, you see that is your mother and soffer the horror, if you dont have good observation you dont see that is your mother)

-This event just say to remove YOUR miniature of the board (because you are out of the house)

- The text to remove all tokens just appears when you find the idol... when not find, just say "remove THIS token search"  (in portuguese, I dont know how is in english version)

-I didnt understand

**Comment by redwolf2** [comment]
@prilogon 
> I didnt understand

Try:

https://translate.googleusercontent.com/translate_c?act=url&depth=1&hl=de&ie=UTF8&prev=_t&rurl=translate.google.com&sl=en&sp=nmt4&tl=pt-BR&u=https://github.com/NPBruce/valkyrie/issues/727&usg=ALkJrhiQ9v4pOos9c-rvXhD3tVxK2vHxqg

**Comment by Indoy** [comment]
Ok so, after discussing with prilogon
- No problem for EventMito18B.text
- EventPassForcaP.text has probably be mistranslated. In the English version, it refers to monster but there's not. It's linked to the investigator trying to escape. It could be something like "For a moment you feel totally dazed. However you take the advantage and flee. Remove your figurine from the board"

For the both following issues, they have maybe to be fixed (i mean for further translation)
- REMOVEWALLTOKEN command concerns, in game, Research token. If people translate, a prompt text appear with "Remove the wall token". Of course, it can be directly correct by the translator but he has know it. It could be a detail but prefer to notify.
- About {qst:EventPassAbrirLeitura.text} that appears in a window text
I find that several lines were missing in the english version (i used to translate in french)
EventPassAbrirLeitura.text,{qst:EventPassAbrirEsc.text}
EventPassAbrirLeitura.button1,{qst:CONTINUE}
EventPassAbrirEsc.button1,{qst:CONTINUE}
However i've tested it and found that the error comes from
{qst:EventPassAbrirLeitura.text} that should be {qst:EventPassAbrirEsc.text}
However, EventPassAbrirEsc.txt appears clearly in all version.

Prilogon told me (@prilogon correct me if i'm wrong) that it's seem for her difficult to fix all of this.
Can someone have a look and bring some fixes?
Thx!

**Comment by Indoy** [comment]
Anyone?
If not, could I post the file however?

**Comment by Indoy** [comment]
Hi! Could someone add my translation plz?
Thx !
[Localization.French.txt](https://github.com/NPBruce/valkyrie/files/1631000/Localization.French.txt)

**Comment by redwolf2** [comment]
@Indoy That has to be done by Bruce, AFAIK it is still linked to Bruces repository, see:
https://github.com/NPBruce/valkyrie-store/blob/master/MoM/manifest.ini

Here is a review to the scenario:
https://boardgamegeek.com/article/28020900#28020900

**Comment by NPBruce** [comment]
Sorry I didn't get to this earlier, although that is in my repository I don't want to go changing other people's scenarios, it should go via the original author.

**Comment by BenRQ** [comment]
Hello @prilogon,  

would you have some time to extract your scenario in your own github fork?
The method to publish is described here :
https://github.com/NPBruce/valkyrie/wiki/QuestPublish

That way you would be able to manage all the updates and translations, without going through the Valkyrie team.

It would be a pity if Indoy work was done for nothing :(

**Comment by BenRQ** [comment]
@scrubbless Maybe you can help on this?
It's a pity that we can't use that French translation.from @indoy.

I also see that the $end variable is not set, no rating has been provided.

**Comment by scrubbless** [comment]
I have access to this repo I think, let me check when I am home later.

**Comment by scrubbless** [comment]
I think a week is enough, I'll take a look at this in the next few days hopefully.

**Comment by vidimus** [comment]
Added French translation (some sentences were untranslated but they were easy to translate. I have permission from @prilogon to maintain the scenario. Apart from fixing some bugs, I added the Spanish translation and the $end tag. Now the scenario will be, finally, in French.

This issue could be closed, @scrubbless
