### ISSUE TITLE
Support Sanctum of Twilight

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#728]
Can't believe I'm writing this, but slow down FFG!  I can't keep up.

https://www.fantasyflightgames.com/en/news/2017/12/6/sanctum-of-twilight/

**Comment by redwolf2** [comment]
The german Streets of Arkham isn't even out yet. ^^

**Comment by RhOmicron** [comment]
I'll be getting it if you need items and things again. (Hopefully I remember)

**Comment by LordPyrex** [comment]
Wow, at least there will probably have a few months to work on IA before this hits the ground.

**Comment by redwolf2** [comment]
Floating tiles as a new feature...

**Comment by NPBruce** [comment]
Just sounds like a remove/add to me, no new features required at this stage.

**Comment by rafbel** [comment]
It is satisfying to know at least they have high hopes for MoM 2E. Thank you guys for also allowing the community to create extra content from the base game and expansions!

**Comment by NPBruce** [comment]
Tokens done, need:

INVESTIGATOR_CHARLIE_KANE,Charlie Kane
INVESTIGATOR_LILY_CHEN,Lily Chen

COMMON_ITEM_PAINKILLERS,Painkiller
COMMON_ITEM_BINDING_POWDER,Binding Powder
COMMON_ITEM_CONVINCING_DUMMY,Convincing Dummy
COMMON_ITEM_LUCKY_RING,Lucky Ring
COMMON_ITEM_RIOT_WHISTLE,Riot Whistle
COMMON_ITEM_SENSIBLE_SHOES,Sensible Shoes
COMMON_ITEM_SILVER_TWILIGHT_DAGGER,Silver Twilight Dagger
COMMON_ITEM_SWORD_CANE,Sword Cane
COMMON_ITEM_TOTE_BAG,Tote Bag
COMMON_ITEM_TRACK_SHOES,Track Shoes

UNIQUE_ITEM_MEMBERSHIP_RING,Membership Ring
UNIQUE_ITEM_TWILIGHT_DIADEM,Twilight Diadem

SPELL_BINDING,Binding
SPELL_SPECTRAL_RAZOR,Spectral Razor

CONDITION_STRESSED,Stressed

TILE_CAFE_MAD26,Café 
TILE_DUNGEON_HALL_MAD26,Dungeon Hall 
TILE_CEREMONY_ROOM_MAD26,Ceremony Room 
TILE_INNER_SANCTUM_MAD26,Inner Sanctum 
TILE_LOUNGE_MAD26,Lounge 
TILE_PARADE_FLOAT_1_MAD26,Parade Float 1 
TILE_PARADE_FLOAT_2_MAD26,Parade Float 2 
TILE_PHARMACY_MAD26,Pharmacy 
TILE_STORAGE_ROOM_MAD26,Storage Room 
TILE_VAULT_MAD26,Vault 

MONSTER_WRAITH,Wraith

MONSTER_WRAITH_MOVE_01,The {0} moves 2 spaces toward the nearest investigator. Then it attacks each investigator in its space.
MONSTER_WRAITH_ATTACK_01,"The apparition rages toward you as if blown by a hurricane, splitting into shadowy images like a gust of dried leaves and tearing at you with fingers like talons (; 2)! If you pass, you hold on to your belief that it has no physical form and the creature's blows pass harmlessly through you. If you fail, your flesh parts and pain sears in the wake of the spirit's touch; suffer 1 Damage."
MONSTER_WRAITH_MOVE_02,The {0} moves 2 spaces toward the nearest investigator. Then it attacks the investigator in its space who has suffered the least Damage.
MONSTER_WRAITH_ATTACK_02,"Face distorting into a parody of the human form, the spirit begins to chant, then shriek, then roar in a forgotten tongue (; 3). If you pass, you recognize it as a traditional death curse from antiquity and intone the proper apology. If you fail, the apparition's tirade ends with a sudden slash from a spectral sword, ethereal but more than capable of cutting your flesh; suffer 2 Damage."
MONSTER_WRAITH_MOVE_03,The {0} moves 2 spaces toward the nearest investigator. Then it attacks the investigator in its space with the lowest .
MONSTER_WRAITH_ATTACK_03,"The spirit howls, then reaches out and begins hurling heavy objects at you with nothing more than gestures (; 1)! If you pass, you scramble for cover but drop something important as you go; drop 1 random Item. If you fail, you dodge the first attack only to blunder into the second; suffer 2 Damage."
MONSTER_WRAITH_MOVE_04,The {0} moves 2 spaces toward the nearest investigator. Then it attacks the investigator in its space with the highest .
MONSTER_WRAITH_ATTACK_04,"The spirit moans and sinks into the ground as if it were not there (; 2). If you pass, you see hints of the spirit's passage around you and step smartly away. If you fail, the horrible sound of nails screeching on a chalkboard is your only warning before ice-cold hands grab your ankles and drag you screaming across the floor; suffer 2 facedown Damage and become Stressed."
MONSTER_WRAITH_MOVE_05,The {0} moves 2 spaces toward the nearest investigator. Then it attacks the investigator in its space who has suffered the most Horror.
MONSTER_WRAITH_ATTACK_05,"Plunging through an ocean of broken glass, you find yourself trapped in a labyrinth (; 2). If you pass, you find your way back out of the prison of your mind. If you fail, your blunderings in the labyrinth are mirrored in the real world; suffer 2 facedown Damage, then flip 1 Damage faceup."
MONSTER_WRAITH_MOVE_06,The {0} moves 2 spaces toward the nearest investigator. Then it attacks the investigator in its space who has suffered the least Damage.
MONSTER_WRAITH_ATTACK_06,"The apparition flickers and takes on a tangible, almost skeletal form. With a shriek, it reaches for your face with fingers like knives; you grab its wrists and do your best to stop it. Suffer 3 Damage (+1 negates)."
MONSTER_WRAITH_MOVE_07,The {0} moves up to 2 spaces to be within range of as many investigators as possible. Then it attacks the investigator within range who has the highest .
MONSTER_WRAITH_ATTACK_07,"You flail desperately as the specter surrounds you, attacking from all sides. Too late, you realize that it is your own wild blows, against yourself and against your surroundings, that are the true danger. Suffer 4 facedown Damage ( negates)."
MONSTER_WRAITH_MOVE_08,The {0} moves 2 spaces toward the nearest investigator. Then it attacks the investigator in its space with the highest .
MONSTER_WRAITH_ATTACK_08,"The spirit vanishes, but you can feel its menace around you and see threats glinting in the shadows. Suddenly, with fingers like knives, it strikes! Suffer 2 Damage ( negates)."
MONSTER_WRAITH_MOVE_09,The {0} moves 2 spaces toward the nearest investigator. Then it attacks the investigator in its space who has suffered the least Damage.
MONSTER_WRAITH_ATTACK_09,"The apparition rages forward, shrieking accusations and laying crime after crime on your head (; 3). If you pass, your quick patter as you defend yourself seems to slow the spirit down. If you fail, the creature screams one final time and then plunges straight through you, almost stopping your heart; suffer 2 facedown Damage and become Stunned."
MONSTER_WRAITH_MOVE_10,The {0} moves up to 2 spaces to be within range of as many investigators as possible. Then it attacks the investigator within range who has suffered the most Horror.
MONSTER_WRAITH_ATTACK_10,"The apparition screeches and rushes toward you, drawing a spectral blade from within its tattered form (; 3). If you pass, you speak a prayer in a forgotten tongue which drives the spirit back; become Focused. If you fail, the creature slashes with its blade at empty air and matching wounds appear on your body; suffer 2 Damage."
MONSTER_WRAITH_MOVE_11,The {0} moves up to 2 spaces to be adjacent to as many investigators as possible. Then it attacks the investigator in an adjacent space who has the highest .
MONSTER_WRAITH_ATTACK_11,"The glowing eyes of the apparition paralyze your feet as the phantom splinters toward you, sharpened nails whistling through the cold silence. The being's jagged fingers rake through the air, giving you little time to dodge their strikes. Suffer 1 Damage and 1 Horror ( negates)."
MONSTER_WRAITH_MOVE_12,The {0} moves up to 2 spaces to be within range of as many investigators as possible. Then it attacks the investigator within range with the lowest .
MONSTER_WRAITH_ATTACK_12,"The stench of rotting flesh and rancid meat fills the air as the spirit materializes (; 2). If you pass, you recognize the incantation of transfiguration being performed and you whisper the appropriate counterspell. If you fail, your attempt to halt the incarnation only deflects the phantom's curse toward yourself, draining your body of living cells; suffer 2 Damage."
MONSTER_WRAITH_MOVE_13,The {0} moves 2 spaces toward the nearest investigator. Then it attacks the investigator in its space with the most Items.
MONSTER_WRAITH_ATTACK_13,"Your vision goes dark as the air chills around you (; 2). If you pass, you sense the specter's frosty aura in the darkness and duck out of its way as it rushes over your head. If you fail, it catches you off guard as it hurtles into your chest, jarring your body backward and loosening your grasp of your belongings; suffer 1 Damage and drop 1 random Item."
MONSTER_WRAITH_MOVE_14,The {0} moves 2 spaces toward the nearest investigator. Then it attacks the investigator in its space with the highest .
MONSTER_WRAITH_ATTACK_14,"The specter's large, spindly hands latch around your shoulders, lifting you high in the air. From its glowing mouth the fiend unleashes a nightmarish howl as it drops you to the ground below. With just a second to angle your body, you must think quickly to avoid a jarring collision with the ground. Suffer 2 Damage (+1 negates). If you suffer 1 or more Damage, become Dazed."
MONSTER_WRAITH_MOVE_15,The {0} moves 2 spaces toward the nearest investigator. Then it attacks the investigator in its space with the lowest .
MONSTER_WRAITH_ATTACK_15,"The specter cackles and disappears into a fog. You confront the shrouded darkness, commanding any presence to leave at once (; 2)! If you pass, you feel the air grow warmer as the fog dissipates. If you fail, your bold attempt only infuriates the being more, causing it to bind you with an ethereal curse; become Restrained, then flip 2 Damage faceup."
MONSTER_WRAITH_MOVE_16,The {0} moves 2 spaces toward the nearest investigator. Then it attacks the investigator in its space who has suffered the least Horror.
MONSTER_WRAITH_ATTACK_16,"The enraged haunter accelerates noiselessly through your chest, subsuming your whole being (; 3). If you pass, your internal constitution fights off the apparition's icy aura, casting the spirit out of you. If you fail, your mind goes numb as the phantom commands your body to move against your will; suffer 2 facedown Damage, then you and the monster move 1 space away from the {0}."
MONSTER_WRAITH_MOVE_17,The {0} moves 2 spaces toward the nearest investigator. Then it attacks the investigator in its space with the highest .
MONSTER_WRAITH_ATTACK_17,"The specter shatters the space around it into dimensionless granules, melting all matter in its path into the infinitesimal. Needing both hands to cast a reunifying enchantment, you set loose your possessions, mustering all your concentration to rectify your dimensional plane before you are disintegrated next. Suffer 3 facedown Damage ( negates). If you suffer 1 or more Damage, drop 1 random Item."
MONSTER_WRAITH_MOVE_18,The {0} moves up to 2 spaces to be in a space with as many investigators as possible. Then it attacks each investigator in its space.
MONSTER_WRAITH_ATTACK_18,"The spirit dances around you, swiping its claws in calculated motions while hissing arcane phrases. As the ritual reaches a close, you frantically search your memory for a way to stop such an incantation as your body slowly begins to dematerialize. Suffer 2 facedown Damage ( negates)."
MONSTER_WRAITH_MOVE_19,The {0} moves 2 spaces toward the nearest investigator. Then it attacks the investigator in its space with the lowest .
MONSTER_WRAITH_ATTACK_19,"Striding to outpace the spirit's screams, you sprint for a safehaven while clutching your ears (; 3). If you pass, you make it out of earshot, leaving the ghoulish howls behind for now; you may move 1 space. If you fail, the shrieking pierces your mind as the phantom clutches your skull and throws you back; suffer 1 Damage and become Stunned."
MONSTER_WRAITH_MOVE_20,The {0} moves 2 spaces toward the nearest investigator. Then it attacks the investigator in its space with the lowest .
MONSTER_WRAITH_ATTACK_20,"You see the flash of an emaciated apparition materialize at the edge of your vision before quickly flitting out of sight. Turning your head to escape the fright, you see the same haunting apparition, this time appearing a few steps closer. Turning once more, your eyes are now blinded by the dazzling glow of the specter's open mouth, emitting cosmic rays that wrack every bone of your body. Suffer 2 Damage ( negates)."
MONSTER_WRAITH_MOVE_21,The {0} moves up to 2 spaces to be within range of as many investigators as possible. Then it attacks the investigator within range who has the most Clues.
MONSTER_WRAITH_ATTACK_21,"Sensing that you know too much, the spirit sails into your mind, taking control of your thoughts (; 2). If you pass, your mystical fortitude casts the phantom out, draining it of its lifeforce; the monster suffers 1 damage. If you fail, the monster electrifies your mind from within, leaving cerebral circuitry irreparably fried; suffer 1 facedown Damage, then flip all your Horror faceup."
MONSTER_WRAITH_MOVE_22,The {0} moves up to 2 spaces to be in a space with as many investigators as possible. Then it attacks each investigator in its space.
MONSTER_WRAITH_ATTACK_22,"With its gangly reach the phantasm pins you to the ground, its glowing mouth hanging open above you (; 2). If you pass, you wrestle yourself away from the creature's grip. If you fail, your brute force is not enough to escape its clutches as the creature sinks its teeth into your neck, then tosses your body carelessly to the side; suffer 1 Damage and become Dazed."
MONSTER_WRAITH_MOVE_23,The {0} moves 2 spaces toward the nearest investigator. Then it attacks the investigator in its space with the lowest .
MONSTER_WRAITH_ATTACK_23,"Illusion and reality become one as the spirit plays tricks with your vision. The phantom peels back the curtain of being, casting you endlessly adrift through the void which remains. Suffer 1 Damage and become Dazed."
MONSTER_WRAITH_MOVE_24,The {0} moves 2 spaces toward the nearest investigator. Then it attacks the investigator in its space with the most Items.
MONSTER_WRAITH_ATTACK_24,"Your possessions weigh you down as you run from the poltergeist barrelling madly after you (; 1). If you pass, you remember a spell that lightens your travel, allowing you to escape freely. If you fail, nothing of aid comes to mind as your gear causes you to trip and tumble, leaving you easy prey for the spectral predator; suffer 2 Damage and drop 1 random Item."

MONSTER_WRAITH_EVADE_01,"The specter locks eyes with you as it begins to mirror your exact movements (; 2). If you pass, you avoid its gaze, no longer entranced by the foe's stare. If you fail, the phantasm floats down through the ground as your body collapses to attempt the same, thwacking your head against the ground's hard surface; become Dazed."
MONSTER_WRAITH_EVADE_02,"The poltergeist barrels after you on all fours, breaking into a sprint. The being pounces on you, teeth glistening against the bright light emanating from the spirit's throat. Out of desperation you conjure one of the only incantations you can remember to save yourself. Suffer 3 facedown Damage (+1 negates)."
MONSTER_WRAITH_EVADE_03,"You try to sneak away while the agitated spirit ravages its surroundings (; 2). If you pass, you proceed unbothered. If you fail, the apparition turns from its ruckus to hurl a bundle of debris in your direction; suffer 1 Damage."
MONSTER_WRAITH_EVADE_04,"The spirit picks up a rusty nail and drives it through its own forehead (; 2). If you pass, you remind yourself that the phantom is already dead. If you fail, a searing pain pulsates within your skull; suffer 1 facedown Damage."
MONSTER_WRAITH_EVADE_05,"The phantom disappears, preferring to stalk its prey from the fourth dimension. Suddenly, you recall a fresh memory of the spirit encircling your baby crib, muttering cursed incantations. You quickly search your mind for enchantments to stop the creature before your memory runs its course. Suffer 2 facedown Damage and 2 facedown Horror (+1 negates)."
MONSTER_WRAITH_EVADE_06,"The spirit screams in a spiteful fit. Fed up with its cries, you scream back (; 1). If you pass, the startled apparition recoils. If you fail, it takes your cry as a challenge, baring its glistening fangs to unleash a bloodcurdling screech inches from your face; suffer 1 facedown Horror, then flip 1 Horror faceup."
MONSTER_WRAITH_EVADE_07,"The spectral being bends time and space around you (; 2). If you pass, you pause to let your momentary vertigo fade before going on your way. If you fail, lifting your leg in the air to take your first step, you experience yourself stepping simultaneously in every direction and trip hard over your own feet; suffer 2 Damage."
MONSTER_WRAITH_EVADE_08,"The spirit becomes simultaneously colorless and infinitely colorful (; 1). If you pass, you take a deep breath and rationalize the apparent contradiction. If you fail, the paradox is too much for any finite being to comprehend; forfeit your action."
MONSTER_WRAITH_EVADE_09,"You attempt to calm the wailing spirit by calling out its earthly name (; 2). If you pass, the phantom's drive for vengeance is satiated momentarily and you scurry on your way. If you fail, you get its name wrong, stoking it into an even fiercer rage and holding you still captive; forfeit your action."
MONSTER_WRAITH_EVADE_10,"You watch as the creature's enormous hands lower slowly from above until your vision goes dark. Clawing at the cold hands obstructing your sight, you eventually wrench them off of you. Recalibrating your vision, you find yourself inexplicably hovering upside down in the air, the phantom cackling maniacally from the ground now beneath you. As soon as you orient yourself, the hex is lifted, sending you tumbling harshly downwards. Suffer 2 Damage (+1 negates)."
MONSTER_WRAITH_EVADE_11,"Understanding the anger and pain the specter must feel, you softly console the weeping wretch (; 2). If you pass, the creature's wails fade to whimpers as it considers its unfortunate lot. If you fail, your empathy falls on deaf ears as the spirit slams its spectral frame down onto you in a tantrum, leaving you disappointed by the rejection of your kindness; suffer 1 Damage unless you become Stressed."
MONSTER_WRAITH_EVADE_12,"Feeling clever, you confidently shout occult utterances at the phantom, the meanings of which are unbeknownst to you (; 2). If you pass, your arcane phrases surprisingly form a ward of protection, allowing you to go along your way as the spectral predator cowers. If you fail, the wraith knows your floridity is nonsense, revealing how clueless you truly are; discard 2 Clues."

MONSTER_WRAITH_HORROR_01,"The apparition draws its hands to its temples, and you are overwhelmed by a feeling of vertigo (; 2). If you pass, your mind holds steadfast and you mentally block out the intruder. If you fail, the spirit shows you a vision of your tombstone engraved with today's date; suffer 3 Horror."
MONSTER_WRAITH_HORROR_02,"The spirit proclaims arcane phrases and conjures three duplicates of itself. The group circles you while wailing loudly in dissonant unison, and you have difficulty discerning one apparition from another. As their howls crescendo, you have only one opportunity to target the original with a destructive hex before the noise drowns out your mental clarity. Suffer 3 Horror ( negates). If you suffer 1 or more Horror, discard 1 Clue."
MONSTER_WRAITH_HORROR_03,"The phantasm's wavering skin undulates, resonating against this earthly dimension (; 2). If you pass, you avert your mind from the eldritch figure and focus on the investigation at hand. If you fail, your curiosity piques and the incomprehensibility of the paranormal rots your mind; suffer 2 Horror and become Stressed."
MONSTER_WRAITH_HORROR_04,"The apparition conjures a music box from the interdimensional void. Cranking the mechanism slowly, otherworldly cries fill the air and you barely pick out your own. Suffer 2 Horror ( negates). If you suffer 1 or more Horror, become Stressed."
MONSTER_WRAITH_HORROR_05,"The wallowing specter screeches with fury as it pulls out its hair, translucent locks cascading down from the phantom's perch. As one strand of ethereal hair passes through your head, you immediately forget a fond childhood memory; discard 1 Clue. In an attempt to soothe the wailing spirit, you hum it a song from your childhood whose words escape you. Suffer 3 facedown Horror (–1 negates)."
MONSTER_WRAITH_HORROR_06,"""Want to dance?"" the specter beckons with a crooked smile (; 3). If you pass, you see through the phantom's sly tricks and keep your guard up. If you fail, you foolishly accept the offer, only for the spirit to take control of your legs; suffer 2 Horror and move 2 spaces toward the {0}."
MONSTER_WRAITH_HORROR_07,"You remember that spirits usually take the form of the recently deceased. Why does this one look so much like you, then (; 1)? If you pass, you assure yourself that everyone has at least a few look-alikes. If you fail, you look toward the spirit and can see only your soulless self staring back; suffer 2 facedown Horror, then flip all of your Horror faceup."
MONSTER_WRAITH_HORROR_08,"The light behind the spirit's eyes consumes your vision, burning holes in your perception (; 2). If you pass, you tear your head aside, blinking away the residual light in your vision. If you fail, you look away, only to catch a glimpse of your reflection in which your own eyes now glow as brightly as the specter's; suffer 2 Horror and discard 1 Clue."
MONSTER_WRAITH_HORROR_09,"The phantasm contorts its features to become a hollow doppelgänger of yourself. Staring into your eyes, the spirit peals back the ephemeral skin from its face, revealing nothing but inky blackness within. Suffer 2 Horror ( negates). If you suffer 1 or more Horror, become Stressed."
MONSTER_WRAITH_HORROR_10,"""This will only hurt a bit,"" the spirit hisses in your ear, raising its spectral claw (; 2). If you pass, you convince yourself the unearthly fingernail is immaterial and you gain confidence knowing it cannot hurt you; flip 1 Horror facedown. If you fail, with one swift prick your back seizes in a sharp pain until your spine goes numb; suffer 2 Horror and become Restrained."
MONSTER_WRAITH_HORROR_11,"The events around you begin to rewind. Played in reverse, you can make out the cries of the ghostly being repeating ""Help me {0}. Help me {0}."" in a shrill, pleading tone. Suffer 3 Horror ( negates)."
MONSTER_WRAITH_HORROR_11_ALT,"The events around you begin to rewind. Played in reverse, you can make out the cries of the ghostly being repeating ""Help me {0}. Help me {0}."" in a shrill, pleading tone. Suffer 3 Horror ( negates)."
MONSTER_WRAITH_HORROR_12,"The spirit opens its mouth wide, sharp teeth parting to reveal a shining light blotted out from hundreds of squirming legs. Spiders spill out of its gaping mouth as the being cackles at your frantic retreat. Suffer 2 Horror (–1 negates). If you suffer 1 or more Horror, move 1 space away from the {0}."

MONSTER_WRAITH_MOVE_00,"The spirit bares its sharp fangs, searching for prey. Drawn to the warmth and light of your living essence, the specter blinks out of existence only to rematerialize again, closer. The {0} moves to the nearest space within range of an investigator."

SOCRATIC_BURDEN_01,The stars change formation overhead. This mythos event affects the investigator in an outdoor space with the highest .
SOCRATIC_BURDEN_02,"The stars weave into intricate patterns against the night sky, as though they were communicating with you (; 2). If you pass, you comprehend the celestial meaning broadcast from above. Some of its contents may be useful to your investigation. Gain 1 Clue. If you fail, you are exposed to the secrets of the cosmos, yet they are too much to bear; flip 1 Horror facedown and become Stressed."

TALKING_IS_HARD_01,"From off the street, a news reporter from the local gazette picks you out to share your experience of the strange occurrences in town recently. This mythos event affects the investigator with the lowest ."
TALKING_IS_HARD_02,"“Give a compelling story and you’ll be the talk of the town,” the reporter insists (; 2). If you pass, you respond eloquently with bold words of communal support. The reporter thanks you for your comment and your positive impact on the community; become Focused. If you fail, you stumble over your words, unable to complete a coherent thought; become Stressed."

THAT'S_BETTER_01,An odd sensation washes over you. This mythos event affects the investigator in an outdoor space who has suffered the most Horror.
THAT'S_BETTER_02,"Something compels you to grab a nearby sharp rock and drive it into your forearm. You feel relieved as blood drains out of you, as if an itch you were previously unaware of has dissipated. Suffer 1 facedown Damage and discard 2 facedown Horror."

FOLLOW_THE_GREEN_FOOT_ROAD_01,Glowing emerald footsteps illuminate the ground ahead of you. This mythos event affects the investigator with the highest .
FOLLOW_THE_GREEN_FOOT_ROAD_02,"You are inexplicably drawn forward, marching perfectly in the grooves of the shimmering radiance. The footsteps lead you to a fresh corpse lying on the ground. Looking closer, you recognize it as a doppelgänger of yourself, its feet glistening the same hue of green yours are now. You hear your own voice from the lifeless body coax, “Join me.” Suffer 2 Horror ( negates). Then move 1 space toward the {0}."

AND_BEYOND_01,You are suddenly drawn to the painting over the desk. This mythos event affects the investigator in the study with the highest .
AND_BEYOND_02,"You remove it from the wall to find a liquid portal pulsating with colors you’ve never seen before. Reaching your arm through the glutinous void, your fingers stretch onward to infinity. The experience leaves you feeling feeble and hollow. Suffer 1 facedown Horror."

GIMME_01,"The belongings of other investigators begin to glow bright red, drawing you toward them. This mythos event affects the investigator with the highest  in a space with at least 1 other investigator."
GIMME_02,"The enchanted items call to you, sparking a deep desire from within (; 2). If you pass, you fight the immediate urge to strip others of their possessions, but stifling the compulsion drains your energy; flip 1 Horror faceup. If you fail, you cave to your possessive appetite, slyly swiping those precious items for yourself.; take 2 random Possessions from each other investigator in your space."

SWARM_01,"A swarm of insects amasses into a thick, whirring cloud. This mythos event affects the investigator in an outdoor space with the lowest ."
SWARM_02,"You feel your body lift off the ground, pulled by the sheer mass of bugs clinging to your skin. The buzzing of a thousand sets of wings vibrates your body. Suffer 1 Horror and 1 Damage ( negates)."

DRAGGED_UNDER_01,The dust and scattered belongings on the nightstand spark your curiosity. This mythos event affects the investigator in a bedroom with the highest .
DRAGGED_UNDER_02,"As you inspect the nightstand, long slithering tentacles unfurl from beneath the bed. The tentacles wrap around your ankles, knocking you off your feet as they pull you under (; 2). If you pass, you desperately wriggle yourself out of the writhing tentacles’ clutches, terrified they might return; suffer 1 facedown Horror. If you fail, you dig your nails into the splintering wood as you’re dragged further underneath the bed; suffer 2 facedown Damage and 1 Horror."

OTHER_MOTHER,"An older woman in a billowing sweater appears from out of nowhere by {0}’s side. {0} greets her warmly as a familiar kin, extending his arms. The woman shuffles forward uncomfortably to accept his embrace, as if her feet were suctioned to the ground. She puts her sweatered arms around him, revealing tentacles that she plants firmly along {0}’s spine. She releases her grasp and scuttles off, leaving {0} with swollen red marks down his back and a confused look on his face. {0} suffers 2 facedown Damage and becomes Dazed."
OTHER_MOTHER_ALT,"An older woman in a billowing sweater appears from out of nowhere by {0}’s side. {0} greets her warmly as a familiar kin, extending her arms. The woman shuffles forward uncomfortably to accept her embrace, as if her feet were suctioned to the ground. She puts her sweatered arms around her, revealing tentacles that she plants firmly along {0}’s spine. She releases her grasp and scuttles off, leaving {0} with swollen red marks down her back and a confused look on her face. {0} suffers 2 facedown Damage and becomes Dazed."

ASHES_ASHES_01,"Suddenly, the piano starts playing a familiar tune from the corner of the room, its keys pressed with no one controlling it. This mythos event affects the investigator in the ballroom with the highest ."
ASHES_ASHES_02,"You recognize the melody as the lullaby your mother sang to you as a child, but in a chilling minor key. A muffled cackling reverberates from inside the piano as the tune fades away. Suffer 3 Horror ( negates)."

NIGHTY_NIGHT_01,The weather suddenly calms for the first time in hours. This mythos event affects the investigator in an outdoor space with the lowest .
NIGHTY_NIGHT_02,"A calming wind makes you feel drowsy. As you drift off to sleep, you see a murky, stooped figure appear out of the corner of your vision. You suddenly fear that if you fall asleep, you will never wake up. Suffer 2 Horror ( negates). If you suffer 1 or more Horror, become Stressed."

RUMPLED_SNAKE_SKIN_01,"From behind a nearby rock you see the head of a coiled snake, stretched as if awaking from its slumber. As you look closer, you can see its muscles rippling from beneath human-like flesh. This mythos event affects the investigator in an outdoor space with the highest ."
RUMPLED_SNAKE_SKIN_02,"The snake locks its glowing green eyes upon yours and, with one swift movement, launches its body toward you (; 2)! If you pass, you dodge the incoming mass and escape before the snake reorients itself. If you fail, the snake sinks its fangs into your neck and you stagger backward; suffer 2 Damage and become Restrained."

IDENTITY_CRISIS_01,A flash of blinding light sears your vision. This mythos event affects the investigator with the lowest .
IDENTITY_CRISIS_02,"You clench your eyelids in an attempt to make it stop. When you open them, you do not recognize your surroundings. You look down at unfamiliar hands attached to what can only be your body. Scouring your mind for any trace of memory, you find no recollection of your identity. Flip all Horror faceup and become Stressed."

CLOUD_APPRECIATION_01,"The clouds above you ripple and bulge as if a colossal, otherworldly being is slithering its way atop the clouded fabric. Each investigator in an outdoor space suffers 1 Horror and becomes Stressed."

DOUBLE_DREAM_01,"Waking up, you find yourself in a familiar bed, a cold sweat dripping from your forehead. A flood of relief fills you as you reason the eldritch monstrosities you experienced must have all been a dream. That is, until the walls begin to drip with thick slime. In a flash, you wake up once more with no memory of falling asleep. Each investigator suffers 2 facedown Horror faceup."

WHAT_SCRATCHES,"{0} stares down at his aching fingernails as blood oozes out from underneath them. Panning across a nearby wall, he sees deep gouges scratched into the wood paneling. As he glances back again, the clawed grooves have disappeared. {0} suffers 2 facedown Damage and 1 facedown Horror."
WHAT_SCRATCHES_ALT,"{0} stares down at her aching fingernails as blood oozes out from underneath them. Panning across a nearby wall, she sees deep gouges scratched into the wood paneling. As she glances back again, the clawed grooves have disappeared. {0} suffers 2 facedown Damage and 1 facedown Horror."

IT_WAS_YOU_ALL_ALONG_01,How useless your actions seem compared to the daunting task ahead of you. You are filled with a draining self-doubt. This mythos event affects the investigator who has suffered the most Horror.
IT_WAS_YOU_ALL_ALONG_02,"A sudden vision envelops your mind. From an estranged perspective, you see yourself gasping for breath, rough hands gripped firmly around your throat. As you look to the assailant, you recognize them as none other than yourself. Suffer 3 Horror (–1 negates). If you suffer 1 or more Horror, become Stressed."

BEES,"A vase precariously perched atop a shelf begins to vibrate violently. {0} bumps it as he walks by, tipping over its contents. A hundred thousand bees pour out, densely packing the room as they attack everyone in sight. Each investigator in {0}'s room suffers 3 facedown Damage ( negates)."
BEES_ALT,"A vase precariously perched atop a shelf begins to vibrate violently. {0} bumps it as she walks by, tipping over its contents. A hundred thousand bees pour out, densely packing the room as they attack everyone in sight. Each investigator in {0}'s room suffers 3 facedown Damage ( negates)."

DOUBT_CONFIRMED_01,Your perseverance is waning. What hope do you have of succeeding? This mythos event affects each investigator.
DOUBT_CONFIRMED_02,"You are turning into the failure you have always feared you would become (; 2). If you pass, you push away the doubt for now but still feel its lurking presence waiting to strike again. If you fail, you realize you will never amount to anything. Nothing you do is ever good enough; flip all of your Horror faceup and become Stressed."

MMM_MMMM_MMPH_01,It is better to stick together. This mythos event affects the investigator with the lowest  in a space with at least one other investigator.
MMM_MMMM_MMPH_02,"The sudden sound of nearby scurrying startles one of your companions, and you instinctively reach your hand out to silence their screams. Their skin bubbles and contorts beneath your fingers. Out of disgust you tear your hand away, revealing a layer of smooth skin stretched taut over what used to be their mouth. Unable to speak, a terrified shriek gurgles in the back of their throat. You and each other investigator in your space suffer 3 facedown Horror."

YOU_CAN_DO_IT,Everything is beginning to come together. {0} and {1} each gain 1 Clue.
YOU_CAN_DO_IT_ALT,Everything is beginning to come together. {0} and {1} each gain 1 Clue.

THUMP_THUMP,"Your heartbeat slows, and you can feel your blood pump through your veins. No immediate effect."

MONOCHROMATIC_OMEN,"For a moment, everything goes dark. Light returns, but you are only able to view your surroundings in black and white. The only spark of color is a deep crimson that pulses from other people's chests, but looking down to your own, you see nothing but a pitch-black void. Each investigator within range of a Person token or another investigator suffers 3 facedown Horror ( negates). If you suffer 1 or more Horror, become Stressed."

SPIDERPERSON_01,"A cloud of flies buzzes about, and you are overtaken with an urge to devour them. This mythos event affects the investigator who has suffered the least Horror."
SPIDERPERSON_02,"Your vision fractures, and you feel your bones shifting within your body. Suddenly, two human arms sprout from each side of your ribcage, ripping through previously undisturbed flesh. Unleashing a pained howl, your voice transforms into a foreign chittering. You clench every muscle in your body to fight the metamorphosis in fear that you might lose touch with your humanity forever. Suffer 2 Damage and 3 Horror (+1 negates). Then become Stressed."

FIRE_AND_BONES_01,"The earth begins to open up, and a flaming skeleton crawls up from the depths. This mythos event affects the investigator with the lowest ."
FIRE_AND_BONES_02,"You sprint away from the creature, turning your head back just in time to see it tear off its burning arm and pitch it at you (; 2). If you pass, splintered bone narrowly avoids your head and the being collapses into a pile as you escape unharmed; you may move 1 space. If you fail, the disembodied arm smacks into the back of your head, toppling you to the ground, where the last image you see is the appendage slowly crawling back to its firey owner before the skeleton burns to ash; suffer 2 Horror and place Fire in your space."

PANIC_ATTACK_01,You cannot keep your fears bottled up forever. This mythos event affects the investigator who has the lowest Sanity.
PANIC_ATTACK_02,"A cold sweat coats your forehead as suddenly every nagging worry floods your mind (; 2). If you pass, you repeat a calming mantra to yourself and your anxiety passes. If you fail, you are unable to find the words to soothe yourself and your troubles send your heart pounding; become Stressed."

**Comment by NPBruce** [comment]
Images:
Monster, investigators, tiles, items, spells
MAD26, Scenario_BCD, Scenario_BCD2, Scenario_TD

**Comment by NPBruce** [comment]
Releasing Investigators, Images, Mythos, Tiles and Wraith in 2.0.  Tokens (#764), Items (#795) and Wraith Brawn (#803) can come later.
