### ISSUE TITLE
Android rotate

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#732]
I fixed the android rotation in the 'standard' way, but there have been more than one comment now this it is wrong for their device/usage.  Not sure if we can autorotate but only at 180 degrees not 90, I think this would be best.

**Comment by redwolf2** [comment]
The UI might not be optimized for it. I saw some problems scaling the width of the scene in the unity preview window. But ce can try to optimize it.

**Comment by NPBruce** [comment]
This is why not 90. We don't support under 720 width well, and don't support on the fly resize.

**Comment by redwolf2** [comment]
I'd say support portrait for all UIs, but keep it landscape in the Scenario Editor, since that would be quite alot of work to change.

**Comment by redwolf2** [comment]
> Not sure if we can autorotate but only at 180 degrees not 90, I think this would be best.

Ahh, ok now I understand, you mean like flipping the screen 180°.

**Comment by redwolf2** [comment]
Merged
