### ISSUE TITLE
Descent campaign phase city screen issue

### ISSUE THREAD

**Issue by DelphiDie** [NPBruce/valkyrie#733]
I need some help to debug the attached Descent quest, which was working fine with Valkyrie Version 1.2.2.

Newer versions of Valkyrie have the issue, that leaving the city screen is impossible. The "Leave" button should call a leave event, but this is not executed properly.

Expected behavior: The Event "EventLeave" from \CampaignPhase\events.ini should be called when clicking on the "Leave" button on the city screen. At this point something is not working as expected. Through the use of the debug variable "DebugCityScreen" I'm able to verify, that the last step before this event should be called is working correctly.

Steps to reproduce the error: 
Start the quest
choose 2 heroes with 2 classes
click start
click skip quest
click campaign phase
travel to Arhynn
click on leave - this is where the problem occurs.

Things I already tried: 
copying the events from the demo quest
changing event names
clearing all non essential entries for this event
renaming the buttons
implementing multiple buttons on the city screen

In the attached .zip file is the original working version of this quest (in the 1.2.2 format), as well as a version converted into the 1.6.1 format (one major release at a time). Both have not been working since at least Valkyrie 1.4. The 1.6.1. version has the debug variables enabled.

[Valkyrie.zip](https://github.com/NPBruce/valkyrie/files/1540773/Valkyrie.zip)

**Comment by NPBruce** [comment]
Sounds like this isn't to do with quest version level, and just a bug that was introduced in Valkyrie.  I will investigate.

**Comment by NPBruce** [comment]
Found the bug.  Rather than triggering the correct event it was triggering quest/round start, which happened to work in my demo/test case but was clearly wrong.  Fixed for next version.
