### ISSUE TITLE
Polish translation issues

### ISSUE THREAD

**Issue by piter77** [NPBruce/valkyrie#739]
There are some issues about polish translation - some concern just translation being wrong or not natural and some not fitting into text boxes.

I attach also some pictures of things that cannot be simply shortened or changed. If there is any possibility of doing something with this would be great.

![zrzut ekranu 2017-12-08 23 14 39](https://user-images.githubusercontent.com/10213424/33856341-21775be4-dec8-11e7-8686-58968608495c.png)

![zrzut ekranu 2017-12-08 23 16 07](https://user-images.githubusercontent.com/10213424/33856344-252eac24-dec8-11e7-93d7-59ac013bc966.png)

**Comment by NPBruce** [comment]
Merged, thanks.
