### ISSUE TITLE
Can't get the 'Investigator attacks' to work in custom monster.

### ISSUE THREAD

**Issue by Crispy66** [NPBruce/valkyrie#741]
Sorry to bring this up again, but I can't figure out how to make a custom attack against a custom monster.  There is a '+' box on the Custom Monster page, but it does not seem to work.  I'm willing to manually do this by editing the .ini file, but need some guidance.
I tried entering "attackevent=" and "investigatorattackevent=" but no joy.
I looked for an example among the available scenarios, but no one appears to have done this.

any ideas?

**Comment by NicolaZee** [comment]
I'm glad you've posted this as usually I do this kind of thing by manually editing the .ini file but it would be nice to know if the UI can support it.

**Comment by Crispy66** [comment]
What is the command that you use in the .ini file?  I'm not familiar with the protocol for this, so I am swinging blindly and missing.

**Comment by NPBruce** [comment]
What version are you using?  You need to be using prerelease 1.7.0b, this is not a released feature.  This is also why nothing uses it yet.  If you still have problems please attach your scenario.

If you are going to do it manually it should look like this:

> attack=unarmed:2 bladed:1 firearm:3

**Comment by Crispy66** [comment]
I've got 1.7.0a.

Ok, I get the line for the .ini file.  Is there anywhere that explains what that means?  2,1,and 3 probably just reference attacks that are already in the game, right?  I thought I could link to an event, like I have done for custom attacks BY the monster.

I have a custom monster that is a pack of rats, and I want to have specific descriptions of what happens when you attempt to attack this creature that is so different from anything else in the game.

**Comment by NPBruce** [comment]
https://github.com/NPBruce/valkyrie/wiki/QuestIniCustomMonster#attacks-format-9-mom-only

https://github.com/NPBruce/valkyrie/wiki/QuestIniCustomMonster#sectionnameattack_type_num

I recommend updating to 1.7.0b and using the editor.
