### ISSUE TITLE
Saved Scenario in 1.7.0b - can't open in 1.6.1

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#744]
Hi guys, 

I assume there is new functionality in 1.7.0b, I saved a scenario in this client by accident (thought I was in 1.6.1) and now can't see it in the 1.6.1 release client.

Is there a way to convert it back to being compatible with 1.6.1? If not will this 1.7.0b scenario be compatible with 2.0 when it is released?

**Comment by redwolf2** [comment]
https://github.com/NPBruce/valkyrie/wiki/QuestIniQuest

Try to set `format=8` inside the `quest.ini`. Be aware of the changes in quest format 9 https://github.com/NPBruce/valkyrie/wiki/QuestFormat

**Comment by NPBruce** [comment]
If you are using the added traits or investigator attacks it won't work.

Otherwise you will have to remove all references to $end (you can do this in the editor or manually) and then manually edit quest.ini and change the format to 8.

**Comment by scrubbless** [comment]
I had saved it previoulsly in 1.7.0b and it was still visible. I think I saved it after playing around with the sorting functions. 

I am not using the added traits or investigator attacks.

I am not near finishing this, so not worried if it will work in the next release? Am I right in thinking a 1.7.0b scenario will work in the next release of Valkyrie (2.0 now I believe)?

**Comment by NPBruce** [comment]
Yes it will work in future versions.
