### ISSUE TITLE
Texts in Horror check, Evade and Attack (MoM)

### ISSUE THREAD

**Issue by FASTNAVi** [NPBruce/valkyrie#745]
Hello,

maybe I am totally stupid, but I need to ask. I am new in Valkyria and I have an issue with texts around monsters.

When I am trying play some scenarios, everytime I try some Evade, Attack or Horror check texts, I see just general text. For example: "MONSTER_HUNTING_HORROR_EVADE_04". I found out this text in evade.ini file in my computer. Right now I see only one solution to resolve this. Just change all texts in this ini and all others too. I search for this ini file on internet but without success.

Thank you for your answers!

**Comment by NicolaZee** [comment]
The text is not in evade.ini but in the language file in the app data folder:
e.g.
Localization_en.txt for English

%AppData%\Roaming\Valkyrie\MoM\import\text
e.g.
C:\Users\Me\AppData\Roaming\Valkyrie\MoM\import\text

Please can you check if the text file exists in the import folder.  What is your language set to?

**Comment by NicolaZee** [comment]
The app data folder may be hidden.
The following link describes how to access it on Windows 10.

https://answers.microsoft.com/en-us/insider/forum/insider_wintp-insider_files-insiderplat_pc/windows-10-roaming-folder/6c99ffdc-90d5-4d1d-8ab1-b4f448ecc8ee?auth=1

If you are using a tablet or smart phone then I can't help but I'm sure others here can.

**Comment by FASTNAVi** [comment]
NicolaZee: I look at the folder you metioned. It was there, but almost no files inside (just 4 of them and others than "localization").

I try to run Valkyria one more time and run "reimport content". After that I checked the folder one more time in appdata and voila.. resolved. I have all files there and all scenarios in Valkyria are working. Thank you for your advice!
