### ISSUE TITLE
Tutorial to create multiple encounter/quest campaigns

### ISSUE THREAD

**Issue by ren6175** [NPBruce/valkyrie#746]
Hello,
I apologize because I'm really not a programmer, but I'm enjoying my time playing with Valkyrie to create customer D2E quests. I know that Valkyrie supports campaigns, but I can't figure out how to do it. I've downloaded the demo quest so I see that on the last Event the editor creates a button to go to the next encounter (for example q1e2/quest.ini). However, in my quest I don't have an option to create that outcome. Thanks in advance if anyone can explain this to me. Thanks.

**Comment by NPBruce** [comment]
There isn't a way to do this in the editor, you have to manually edit the ini files.  Find the event section and set the next event to a quest.ini file:

https://github.com/NPBruce/valkyrie/wiki/QuestIniEvent#eventnum

https://github.com/NPBruce/valkyrie-questdata/blob/master/source/D2E/campaign/events.ini#L70

**Comment by ren6175** [comment]
Thanks
