### ISSUE TITLE
Save & Test - Broke Scenario

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#749]
Hi Guys, 

I was working on a scenario, and hit Save & Test.

Instead of loading normally it just turned all the tiles and tokens (that are faded in the editor) into their solid versions and a small white box has appeared in the lower left corner.

Now every time I open the scenario it shows like this.
![image](https://user-images.githubusercontent.com/32058089/34674971-dbbe6ec6-f47f-11e7-9496-c40f87baa8f9.png)

Is there a way to recover this without going back to my previous commit? Its frustrating as I spent about 2 hours on events and I would prefer not to have to re-write them.

I am using the 1.7.0b client, but other scenarios load Ok.

I can't produce you a Valkyrie file, but here is a zip of the contents of "MoM\Editor" so you can take a look.
[ScenarioInError.zip](https://github.com/NPBruce/valkyrie/files/1611860/ScenarioInError.zip)

**Comment by StevenP94** [comment]
Just a suggestion: Try to make a diff with previous version to see what can be wrong.
Save the current version
Recover to your latest commit
Reapply changes one by one from the diff file to see what is the problem
hope that this can help - excuse me if is obvious and I misunderstand the problem

**Comment by scrubbless** [comment]
Hi @StevenP94 thanks for the comment.

I am not sure what you are referring to, do you mean revert my GitHub to the last commited change before the error? I have done this and it was 8 hours ago (lowing this mornings 2 hours+ of work).

If so I have already identified the changes made, with the following process:

> I copied the localisation file and renamed the copy. Then committed the change to my Repo. 
> 
> I then renamed the corrupt localisation file to the same name as the copy made above and dropped it into my reverted scenario. This shows me all of the changes that I made to the text. 
> 
I have just finished re-creating all of the events and am testing them now (but that was another 45+ mins that I could have spent adding new content :( ).

Mainly I was just wondering if there was an easy fix, like resetting a flag or something.

I probably won't re-use the corrupt files linked, now that I have re-created the events again in a new version. But its a frustrating bug and it would be useful if it could be fixed, to avoid this happening again to someone else.

**Comment by StevenP94** [comment]
hi @scrubbless I'm sorry for the time you wasted. I'm new into this project and started just making translations of content provided from other people (like you 👍).
For what can I understand you used the git repository to have a diff (a file with the differences between your local copy and the latest you committed).
Have you found the problem origin? There is something that can be made in code to avoid it?

Btw I have just a suggestion from the translation side: I can see a lot of repetitions inside the Language text. Maybe using a sintax like
```
CONTINUE,Continue
...button1,{qst:CONTINUE}
```
can help to have a shorter translation.
I use this as I can for each repeated text.

P.S. I totally agree your point of view about the interface that in my opinion should be like the retail one. I hope to have time and knowledge to make something for that.

**Comment by scrubbless** [comment]
> For what can I understand you used the git repository to have a diff (a file with the differences between your local copy and the latest you committed).
> Have you found the problem origin? There is something that can be made in code to avoid it?

Yes that's what I have done. It doesn't appear to be a code issue and I have recreated the events using the differential and the save issue didn't occur.

Valkyrie seemed to "freeze" after I click "Save & Test", so I suspect it was Valkyrie code that corrupted something, rather than my content being at fault. 

When  I tried to go back into it the scenario using the editor, it opened up without any editor options and all of the tiles and tokens displayed.

> Btw I have just a suggestion from the translation side: I can see a lot of repetitions inside the Language text

As for the repetition I am not sure what you mean? I am using the editor. The "Continue" is auto populated, are you suggesting I change every instance of these frequently repeated words (like continue) with a variable? 

If it can't be done in the editor, I won't do it. I am not confident manipulating code on the file level as it could have unexpected consiquences.

**Comment by NPBruce** [comment]
Unfortunately I haven't had much time for Valkyrie lately.  When I can I will have a look and see what is wrong with the files.  If I can determine how it could have occured I will update Valkyrie to prevent the problem.

**Comment by scrubbless** [comment]
Cheers Bruce, hope all is OK. Appreciate you getting back to me.

**Comment by NPBruce** [comment]
Great work figuring it out.  Shouldn't be hard to fix when I get back to bug fixes.

**Comment by Aazzlaaroth** [comment]
Hello ! 

I post here to avoid multiple threads. I have the same issue than Scrubbless, hit the Save&Test button, and now i can't acces my scenario anymore. It seems like i can create a new one, but when i try to load/play/edit the one i was working, i'm bounce on the title screen of Valkyrie.
I have no idea about fixing this by myself.

**Comment by scrubbless** [comment]
Zip your scenario data in the folder in
%appdata%\valkyrie\mom\editor

Then drag it into a comment here and I'll try to look. Also others can have a look too this way.

 What was the last thing you did before saving and getting the error? Did you delete any images? If so what was the name of the deleted file (if you know).

**Comment by Aazzlaaroth** [comment]
Here it is.
The last thing i have done was spawning a monster and practicing with vars. I'm not sur but maybe i did a mistake with them, crashing the test.
[EditorScenario1.zip](https://github.com/NPBruce/valkyrie/files/1636380/EditorScenario1.zip)

**Comment by scrubbless** [comment]
I'll take a look tomorrow when I'll have more time. 

Do you use github or anything else to track your changes or back up your scenarios?

It might be useful to compare a working version to the broken one.

**Comment by Aazzlaaroth** [comment]
I'm a complete newbie, i just arrived 2 days ago ^^ but that'll be useful for me, thanks for the advice! =)

**Comment by scrubbless** [comment]
There is a section on how to use github in the scenario creation guide:

https://docs.google.com/document/d/1Gi5gTwKkw84Px0Lvk-bJ3Aml_vF3ZoljjB6a8FjWGt8/

It's for published scenarios but will work for normal backup, change and issue tracking.

Let me know if you want more info on this.

**Comment by Aazzlaaroth** [comment]
I found what broke my scenario. It was the spawn event. I made a confusion due to a misreading : i thought a spawn WAS the monster itself, whereas the spawn is basically just a node where a monster can appear on the board. I removed the "spawn" manually by editing the file and it works again ^^

**Comment by scrubbless** [comment]
Nicely done!

Would you mind explaining what you did in the editor, that broke your scenario? Then what you did to fix it.

If something done inside the editor can break a scenario - it's better that we get a bug raised and have it fixed (or prevented) so others don't get the same problem.

**Comment by Aazzlaaroth** [comment]
No prob ! Since i thought a spawn monster WAS the monster token and not the "monster entry", i set a var to spawn it once and configured it as if it was the monster itself. I think i set wrong vars (unadapted vars for  unadapted event) resulting in a crash.

FIX : Nothing worked, the only thing to do is to search the SPAWN file, edit it and delete the badly configured spawnmonster.And now i can continue to create my scenario^^

**Comment by NPBruce** [comment]
I found the image bug and it was a bad one.  When you save a scenario it is reloaded, but to keep the component history data I don't reload that.  It was actually keeping a separate copy for all previously opened components and very bad stuff could happen.  Hopefully this fix will see a big decrease in corrupted scenarios.
