### ISSUE TITLE
Tokens with certain heroes count + HoB

### ISSUE THREAD

**Issue by mickkn** [NPBruce/valkyrie#753]
Hi first of all. Do anyone work on the Heirs of Blood quests for this application? 

I started the intro quest and need a way to add specific Search tokens for certain number of Heroes.  Is there anyway to apply a flag for this or something like that :) thanks

**Comment by NPBruce** [comment]
No one is working on Heirs of Blood to my knowledge.

As for adding tokens based on number of heroes, you can check the #heroes var and trigger any event conditionally.

**Comment by Hobbeslionheart** [comment]
You can look at my quest, The Cardinal's Plight for examples of setting up tokens based on the number of players.

**Comment by mickkn** [comment]
Okay, cool. 

Where is Quest files located on Mac OSX ?

**Comment by mickkn** [comment]
On the desktop it seems :D the only placed I didn't look

**Comment by mickkn** [comment]
Started the quest here: https://github.com/mickkn/HeirsOfBlood
and the raw files here: https://github.com/mickkn/HeirsOfBlood_Editor
