### ISSUE TITLE
File location on Mac for Repos

### ISSUE THREAD

**Issue by mickkn** [NPBruce/valkyrie#754]
Do I need to use "Create Package" to get the files for my repo, or can I update the files and upload to repos on mac ?

**Comment by NPBruce** [comment]
Not sure that I understand the question.

The quests are stored in ~/.config/Valyrie.  The packages here can be played but not edited.  Copies or new quests are stored as directories with all associated files.

Create Package creates a package and meta data for your quest on the desktop.

I recommend using a source control repo inside ~/.config/Valyrie to manage changes.

To publish the pacakge file, ini file and thumbnail (if present) need to be put on the internet.  The simplest way to do this is to add them to a git repo on github.

Does this help?

**Comment by mickkn** [comment]
Exactly what I needed. You should add this info to https://github.com/NPBruce/valkyrie/wiki/QuestPublish
Under data location :)

**Comment by NPBruce** [comment]
I have added the MacOS path, I think everything else is already there.
