### ISSUE TITLE
1.7.0b - Stable Release?

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#755]
Hi guys,

I've been writing my scenario in 1.7.0b for quite some time and I can't fault it. I have also played using the pre-release and its solid from what I can see.

Is there anything holding it back from being promoted to stable release?

It's just that some of the features (sorting and expansion exclusion) make it hard to want to go back and write in 1.6.1!

**Comment by NPBruce** [comment]
These are all the things I want to do for a stable release:

https://github.com/NPBruce/valkyrie/milestone/23

Hopefully things will change soon and I can get back to some development.
