### ISSUE TITLE
Copy and Paste

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#757]
I have a weird issue, but sometimes when I paste in text from another file and save the scenario it deletes half of the text.

I notice it quite frequently using Google keep (I use it on the train to write snippets of dialogue).

When I copy the text, and paste it into Valkyrie it seems fine. I can continue editing events and scrolling back to find it. But when I hit "Save" portions of the text dissappear.

I sometimes find this "phantom text" in the localisation file, disconnected from the original event.

**Comment by scrubbless** [comment]
On further investigation it seems to be when copying text that contains spaces. I wonder if the space character on some text editors (or web tools) is not compatible with the characters in Valkyrie.

**Comment by scrubbless** [comment]
The work around for this is to remove all "carriage returns" (enter, break line). From text and copy it in as one single line of text (spaces and characters are fine of course)

**Comment by redwolf2** [comment]
Fixed it https://github.com/NPBruce/valkyrie/pull/789

**Comment by NPBruce** [comment]
@scrubbless please confirm the (soon to be published) 1.7.0d works for you.

**Comment by NPBruce** [comment]
My testing suggest this is fixed, reopen if you still have issues.
