### ISSUE TITLE
Valkyrie Ver 1.7  Lost Menu

### ISSUE THREAD

**Issue by EMILIPULIDO** [NPBruce/valkyrie#759]
In Windows. Sometimes when save and reload a scenario I've lost menu, all menu options.
Then we can't exit aplication, just interact whith tokens o map. not continue.
We may close window aplication and load a New scenario for retriev menu, and then try to load saved scenario... often it's ok, sometimes not, then repeat several times...

ThankU

**Comment by slycozzolino** [comment]
I ran into this issue last night as well. This is also an issue in the previous official release.

**Comment by NPBruce** [comment]
Please provide the save game data so that the bug can be found.

**Comment by De4ser** [comment]
Hello
i ran into the same issue
How do i provide the save game data?

**Comment by NPBruce** [comment]
It will be in %AppData%\Roaming\Valkyrie\MoM\Save

**Comment by NPBruce** [comment]
Closing due to lack of information.
