### ISSUE TITLE
Mythos Event NEVER_LOOK_BACK_ALT Displays {0}

### ISSUE THREAD

**Issue by NicolaZee** [NPBruce/valkyrie#760]
For the current release (1.6) the Mythos Event for NEVER_LOOK_BACK_ALT  displays the following because the {0} place holder is not filled in.

"A specter from {0}'s past rises from the ground to drag on her limbs."

I have a picture if you want it.
Apologies if this has already been fixed in the pre-release.

[Added]
It is part of the SoA Mythos Events.

**Comment by NPBruce** [comment]
I haven't changed anything here, but can't reproduce the problem.  If you see this again, please reopen (with a save would be great).
