### ISSUE TITLE
Request for improvment "list of components"

### ISSUE THREAD

**Issue by FASTNAVi** [NPBruce/valkyrie#762]
Hello,

I am working with version 1.7.0 c and I am very happy about the new things. I have just one request. When I open "Components", I usually (about 95% of cases) need something from last few components, so I need to klick in right up corner to sort it right.. I would like to klick on Components and I saw the list not from the old ones, but from the fresh ones.. or at least, the menu Components can remember last configuration of sorting. Right now I really must do one more click almost everytime. I know, it will be saving just about 1 second per one opening Components, but for me is about the saving thousends of seconds in sum.

So if you can do something about that, I will be very happy. Thank you for reading ;-)

**Comment by scrubbless** [comment]
If you press the 1 symbol (next to the A for alphabetical sort) it will sort it in reverse (newest first), and the number changes to 9. That's how I do what you are asking!

**Comment by FASTNAVi** [comment]
Yes, I know that. And this is "one more click" everytime for me.. I would like to have a chance set this as default..

**Comment by NPBruce** [comment]
I'm hesitant to just change the default and possibly annoy someone else, but I will consider options.

**Comment by scrubbless** [comment]
I agree there are use cases for both. Some may sort common events manually using the reorder function. Or create the scenario in a sequential order and prefer having a clean sequence of events as apposed to a reversed sequence.

**Comment by NPBruce** [comment]
Does leaving it at the last selected order sound OK to people?

**Comment by scrubbless** [comment]
Sounds like a good comprise to me.

**Comment by FASTNAVi** [comment]
Yes, this was exactly my wish. Thanks! =)

**Comment by NPBruce** [comment]
Reopenning, because I haven't actual done the change yet!  Planned for 2.1.

**Comment by BenRQ** [comment]
Hi, 
I did the change described here, at the same time as the change in #873

**Comment by BenRQ** [comment]
Beta test version is now available with implementation of this issue:
https://github.com/BenRQ/valkyrie/releases/tag/release%2F2.1%2FBrynhildr_2.1.0b

Please close this issue if you are happy with the fix.
