### ISSUE TITLE
Memory of remaining live for monsters

### ISSUE THREAD

**Issue by FASTNAVi** [NPBruce/valkyrie#764]
Hi,

I am just wonder. It is possible to make a monstrum, move him away from board and later summon that same monstrum with the same number of remaining lives? Exactly the same thing is in original scenario Escape from Innsmouth. I hope you understand me.

Please, every single advice or idea will be welcome.

**Comment by NicolaZee** [comment]
I believe this functionality is already scheduled for Later
https://github.com/NPBruce/valkyrie/issues/594

**Comment by NicolaZee** [comment]
You might want to have a look at my scenario 'In the Dark'.
A big monster is removed from the board but (because Valkyrie does support keeping the lives) I have to leave it visible in the monster tray.
Most players don't mind as they just ignore it in the Horror Check stage.

**Comment by FASTNAVi** [comment]
Great! Thank you very much. The idea about ignoring monster by player is the most easy way. It is not perfect but the most of players using Valkyria will have no problem with that. In my next scenario I will need it ;-)
