### ISSUE TITLE
Create a Carousel UI component

### ISSUE THREAD

**Issue by eorahil** [NPBruce/valkyrie#765]
Like these
[Examples](https://www.google.es/search?q=ui+carousel&client=firefox-b-ab&dcr=0&source=lnms&tbm=isch&sa=X&ved=0ahUKEwj68ebqo9zZAhWN3KQKHRyqB2AQ_AUICigB&biw=1408&bih=642)

in order to replace:
* Game selection: Instead of showing every time you open Valkyrie the 3 (now, but will be more) available games and their Import option. There should be a carousel showing the game (better an image) and its import option and strafing left of right there should be the next game. In user options there should be saved the last game played an selecting it by default.
* Adventure selection: Like the official MoM APP: You dont see a list of available games but the first scenario "in full screen" and strafing left and right you can browse available adventures.

**Comment by scrubbless** [comment]
This would involve downloading the scenario text and image automatically I assume?

Then there would be a "download" option, for people to download each scenario as they choose?

 Otherwise it's going to get pretty bandwidth intensive to fire up Valkyrie.

I've got a scenario in the works that is nearly 40mb. For someone on a 4g connection (on a tablet for example) that won't be great.

Like the idea though!

**Comment by redwolf2** [comment]
For game selection, that's a good idea. 

But for scenario selection, it would take too much time to shuffle though all scenarios. I think the scenario selection at this point is quite ok. Maybe it could be replace by a [gallery grid](https://www.google.es/search?client=firefox-b-ab&dcr=0&biw=1920&bih=923&tbm=isch&sa=1&ei=aY-hWp_gDIrdgAaxpK-gAQ&q=gallery+grid&oq=gallery+grid&gs_l=psy-ab.3..0j0i5i30k1l2j0i8i30k1l3.2295.2762.0.2929.4.4.0.0.0.0.117.435.0j4.4.0....0...1c.1.64.psy-ab..0.4.432...0i30k1.0.XkrzCrFL8dM), but IMO a nice to have.

**Comment by scrubbless** [comment]
The official app does it this way and it has 13 scenarios at present.

Emulating the feel of the official app will make it easier for people to navigate.

**Comment by NPBruce** [comment]
I also don't like this for scenario selection, but perhaps elsewhere.

**Comment by redwolf2** [comment]
Scenario Explorer fills this need, so I'm gonna close this.
