### ISSUE TITLE
Quota Variable isn't working properly

### ISSUE THREAD

**Issue by slycozzolino** [NPBruce/valkyrie#766]
When using a variable for an event quota the event sets that total once the event is triggered instead of adding up the success to meet the threshold as it normally does with a static value.
For instance I have a static value of 7. This event will continue to trigger until I meet that quota. However if I set a variable based on the users(and the total should be 7) it doesn't work properly. See pic below
![image](https://user-images.githubusercontent.com/27984327/37418671-243662d0-2789-11e8-9491-1864f2e68f5f.png)

When the event is triggered the value set via the variable is put into the successes field and no matter how many success I put in the event will succeed.
![image](https://user-images.githubusercontent.com/27984327/37418641-13e9261a-2789-11e8-95e9-d0b42eacc194.png)

**Comment by NPBruce** [comment]
From the wiki https://github.com/NPBruce/valkyrie/wiki/QuestIniEvent :

> If quota is set to a var name that variable will be used for the initial number setting and will be written to on completion. In this situation event1 will always trigger (Format 5+).

https://github.com/NPBruce/valkyrie/wiki/QuestIniEvent

This is correct and used for more complicated outcomes, where different numbers will result in different things, and the total can be tracked and modified (ie: number of monsters who have left the board).

Let me know if this doesn't make sense or I have misunderstood the problem.

**Comment by slycozzolino** [comment]
That's the info I was looking for and not able to find. I was using it wrong.
I don't believe there is a way to set the quota as a variable like I would like. I can instead use multiple events that trigger based on the hero count.
Thanks.

**Comment by NPBruce** [comment]
Note that you can test the quota var in the following event.  The problem with using a number is that only two outcomes are possible, if you use a var you can add any number of events under the first button and test for appropriate var conditions.
