### ISSUE TITLE
created door

### ISSUE THREAD

**Issue by dagniel79** [NPBruce/valkyrie#768]
the option "door" was not in the editor content do i miss a import asset ?
from the start of the tutorial im locked with this issue because i can not place doors

**Comment by Hobbeslionheart** [comment]
Is this for D2E or MOM? 

D2E does have a door. MOM do not have doors and you use explore tokens as "doors"

**Comment by dagniel79** [comment]
OH! thank you. i will give it a try right now

**Comment by scrubbless** [comment]
The are door tokens in MoM so you can add doors to tiles that don't have them (just like you'd add a wall to block a door).

Just add a token the select the token you want to use.

**Comment by dagniel79** [comment]
the doors work well now. so my next question is what's the roots for UI jpeg files? and where is the parameter for the starting item? the loading mission importe only one object and at ramdom pace

thank for your help

**Comment by scrubbless** [comment]
I wrote a guide for the MoM side of the Scenario editor, it has the answers to all of these questions (your question specifically is here in the guide):
https://docs.google.com/document/d/1Gi5gTwKkw84Px0Lvk-bJ3Aml_vF3ZoljjB6a8FjWGt8/edit#heading=h.re5y4hytqpyv

To answer directly, you need to copy your .JPEG and .PNG files to this directory and they will then show up at the top of the list.

%appdata%\Valkyrie\MoM\Editor\Scenario1
Scenario1 is the default name of a Scenario when it’s created, you can rename this at any time.

**Comment by scrubbless** [comment]
Hi @dagniel79, 

Staring items are also in the guide, but for quick reference you need to create a Qitem as you would any other item, then set the " starting item" field to "true".

Did this fix your issue? If so can you close the issue.

**Comment by dagniel79** [comment]
yes all yours answer was perfect

**Comment by scrubbless** [comment]
No worries happy to help :)
