### ISSUE TITLE
Minor update to The Truth scenario. Need French and German Translation

### ISSUE THREAD

**Issue by slycozzolino** [NPBruce/valkyrie#771]
The following events were added to clarify rules in this scenario. I need translations for the following. If you can please just add the translations in the comments I add it to the respective localization files.

- TokenBarricade.button1,{action} Break down the door

- EventPlaceBarricadeInteract.text,The creature is barricaded in the closet. You will have to bust through it.  Place an Interact token as indicated.

- EventBustBarricade.text,You ram your shoulder into the door over and over. Test your {strength}.

- EventBustBarricadeFail.text,Your shoulder starts to hurt as you continue to slam it against the door. It just doesn't appear to budge.

- EventBustBarricadePass.text,You slam against the door busting it open. Remove this token and move your investigator into the Bedroom Storage {MAD23}.

**Comment by redwolf2** [comment]
GERMAN:

- TokenBarricade.button1,{action} Ramme die Tür ein

- EventPlaceBarricadeInteract.text,Die Kreatur hat sich im Schrank eingeschlossen. Du ihn aufbrechen müssen, um zu ihr zu gelangen. Platziere einen Interaktionsmarker, wie gezeigt.

- EventBustBarricade.text,Wieder und wieder rammst du deine Schulter gegen die Tür. Teste deine  {strength}.

- EventBustBarricadeFail.text,"Du spürst wie Schmerzen deine Schulter hinaufkriechen, als du dich wiederholt gegen die Tür wirfst. Sie scheint sich jedoch nicht nachzugeben."

- EventBustBarricadePass.text,Du schmeißt dich gegen die Tür und stößt sie auf. Entferne diesen Marker und platziere deinen Ermittler auf das Feld des Schlafzimmerschranks {MAD23}.

**Comment by slycozzolino** [comment]
Thanks so much @redwolf2

**Comment by slycozzolino** [comment]
@Indoy,
Would you be able to help with the French translation?

**Comment by Indoy** [comment]
Hi !
For sure!
    TokenBarricade.button1,{action} Enfoncer la porte
    EventPlaceBarricadeInteract.text,La créature s'est barricadée. Vous allez devoir fracasser la porte pour l'atteindre. Placez un jeton Interaction comme indiqué.
    EventBustBarricade.text,Vous vous jetez l'épaule en avant encore et encore. Testez votre {strength}.
    EventBustBarricadeFail.text,Votre épaule commence à vous faire mal à mesure que vous tapez la porte. Elle ne semble pas bouger d'un pouce.
    EventBustBarricadePass.text,Vous tapez sur la porte jusqu'à l'ouvrir. Retirez le jeton et déplacez votre investigateur dans le Rangement de la Chambre {MAD23}.

**Comment by slycozzolino** [comment]
Thanks @Indoy
