### ISSUE TITLE
Wrong Tile - Application Crash

### ISSUE THREAD

**Issue by mamantins** [NPBruce/valkyrie#772]
Hello all,

During my short scenario creation, I was facing an issue.
Running the scenario in editor mode ==> No problem.
Running the scenario in regular mode ==> on an event, the app crash systematically.

After digging a bit, I was running the scenario whitout including the correct extension.
Means:
- In regular mode, I could start it, even I do not have the extension.
- The application crash/close without message.

Maybe it could be interesting to add the extension "check" also in editor mode.

I hope this can help for the app evolution.

Mam's

**Comment by NPBruce** [comment]
I think you are saying you are using content from an expansion, and if the expansion isn't selected it will fail.  The editor always loads all content so it will work.

You have to set your expansion requirements for your scenario to prevent this.  It is possible to use components that are not from requirements, because they could be optional features, but it is up to the developer to ensure they are only used when available.

Controlling which expansions are selected in test mode is something to do later.

**Comment by scrubbless** [comment]
Its also interesting to note, that when you run the scenario from "Save and test" in the editor, it automatically enables all expansions. You can see this by opening the log (it will say BtT = 1, SoA = 1 etc).

Run th same scenario without content selected in Valkyrie and all of those variables will be 0 (or just won't be there). To get to the debug log when playing a normal game, you need to press "alt" + d.

So if you want to check that a scenario works with limited or no expansions, you will have to run it like a normal players (from the scenarios section, not the editor).

**Comment by NicolaZee** [comment]
Good spot on test mode.  That is useful to know.  I've been testing content selected using the test mode!

I think would be better if the app did not crash if content is used for an expansion which has not been selected.

**Comment by mamantins** [comment]
It's tooks me hours to understand why the app crash.
I use a BtT tile, but I do not own it.
And, when I use a regular way to load my scenario, it was possible for me.

**Comment by NicolaZee** [comment]
In the folder where the Valkyrie executable is, you will find a subfolder called 'valkyrie_Data'
Inside there is the text file 'output_log.txt'

It sometimes contains relevant error messages hidden amoung the messages about assets.

**Comment by mamantins** [comment]
That will be usefull.
Thank's

**Comment by scrubbless** [comment]
Tiles are easy to spot. You can just file the tiles by expansion (left menu when picking them). Any used will be blue.

Not sure if it crashed of you last a token or monster from an expansion not owned though. That might be trickier to find.

**Comment by mamantins** [comment]
Closed also.
If this happen, make sure to have activated the appropriate set of tiles in the application.
