### ISSUE TITLE
Make a monster flee a tile

### ISSUE THREAD

**Issue by mamantins** [NPBruce/valkyrie#773]
Hello all,

I know that is not a "issue".
I need to make my monster flee a tile.

For the moment I proceed as follow:
- During the attack phase of the monster, a special event trigger to allow to the monster to flee the zone.
- A test is requesting to the player to catch him.
         - if success the combat will continue and the player earn a investigation token. (lucky him)
         - if fail the combat ends and the monster flee. 
Here is the question how to remove it at that time, without asking the player to "kill" it.

Thank you for your help.

Mam's

**Comment by scrubbless** [comment]
Make a custom monster and give it a name. Then set the bar to the monster you want. Leave the other fields blank, this was it will default all evade/horror/etc to that of the base monster.

Then in the spawn event select your custom monster, so instead of say "a zombie" you spawn "my custome zomibe".

In the event where you want the monster to flee, just got "remove component" and select your custom monster.

It has to be a custome monster, otherwise if you use "remove components" to remove just a normal zombie it will remove all zombies in play.

I hope that helps! I'll add it to the guide. There is a section on custom monsters, but it mainly focuses on triggers that run events after  monsters are defeated.

**Comment by mamantins** [comment]
That's help a lot! (^_^)

From this I have now a improvement proposition for the app.
In my scenario I have identical monster, spawning at the same time.
So I used the same customMonster for my 3 spawns.
Those will have the same comportement.

Could be insteresting to have a "Duplicate" option for Event, Monsters or any items of the game.

Hope this help.

Thanks again Scrubbles

**Comment by mamantins** [comment]
Arg!
My problem evolving.
As I said I have several monsters on the same tiles.
I want to remove the "active monster".
Indeed the test for running away is done during the ennemy phase.
Is there any way to flag the active monster and remove it as Scrubbles suggest?
Or in case of several monster on the board, does the activation respect some "order"? In such case I coukd try to catch the monster name.

Thaks for your help.
Mam's

**Comment by scrubbless** [comment]
You could do that in its activation. 

So for example you could create an event for the monster (that only triggers if a variable is set - "monster will flee = 1"). When the event triggers you could have two options appear "Investigator not in space" (which if clicked will trigger the flee event, removing the monster). The second button could be "Investigator in space" (where it does something else).

**Comment by scrubbless** [comment]
I think there is a feature request for "copying components" which couls be expanded to monsters I suspect.

You will want each monster to be its own customer monster, so you can interact with them individually (and give them their own individual activations).

**Comment by mamantins** [comment]
Ok. Thanks again.
I guess the feature copying component will be really usefull.

In my case all monsters will have the same comportement but because I need to remove the "active" monster I need to create one specific event for each of them. (>_<)

**Comment by mamantins** [comment]
Ha! Stypid me.
I can flag the active on with a variable in Activation!

**Comment by scrubbless** [comment]
Boom! You've got it!

**Comment by mamantins** [comment]
For info.
To remove a monster, you need to remove the Spawn event. (^_^;)
A CustomMonster/RegularMonster cannot be "remove".

I hope this help.
Mam's

**Comment by scrubbless** [comment]
Yeh that's correct, my bad was doing it from memory. So no need for a custom monster each, just their own spawns.

Not had time it sit infront of the editor in a while.

**Comment by mamantins** [comment]
I will not forgive you. ;)
Thanks a lot.
I will finish my first "tutorial" scenario in the next comming days. (in English and French)

The next one will be far bigger, from Cthulhu RPG.
One of my favorite scenario

Mam's

**Comment by scrubbless** [comment]
Not being able to get time to finish my current scenario IS unforgivable! 

If your ticket is resolved can you close the issue. :)

**Comment by mamantins** [comment]
Closed! :)
