### ISSUE TITLE
1.3.0 Won't Start

### ISSUE THREAD

**Issue by Maverick4jc** [NPBruce/valkyrie#777]
I downloaded 1.3.0 to convert some older quests to update them to format 6 so they can be edited on 1.6.0.  Unfortunately after importing data I click on Descent and nothing happens.  It stays on the same screen and does not take me to the menu.  I've tried downloading again, running as administrator, deleting everything and downloading again including %appdata%..  1.6.0 still works fine.
[output_log.txt](https://github.com/NPBruce/valkyrie/files/1862847/output_log.txt)

**Comment by NPBruce** [comment]
I believe the problem is that 1.3 won't work with the current Road to Legend.  It is possible (but annoyingly hard) to roll back in steam.  What might be easiest is if you post the files and I will update them for you.

**Comment by Maverick4jc** [comment]
Thank you for the help!
[quest (1).zip](https://github.com/NPBruce/valkyrie/files/1862994/quest.1.zip)
[Valkyrie.zip](https://github.com/NPBruce/valkyrie/files/1862998/Valkyrie.zip)

**Comment by Maverick4jc** [comment]
One more.
[02_AFatGoblin.zip](https://github.com/NPBruce/valkyrie/files/1863008/02_AFatGoblin.zip)

**Comment by NPBruce** [comment]
[Update.zip](https://github.com/NPBruce/valkyrie/files/1863118/Update.zip)
Done, with some notes:

Death of the Wing quests were empty, have not been included.

Egg Thieves was from a very early version, before the quest format was tracked.  I have updated it, but there are no promises here.

The others were also quite old and required a two stage update - Once in Version 1.0.1 and again in 1.3.0.  In theory this should Just Work(tm), but they will definitely need to be tested (assuming they were working in the first place).

Lastly they are all saved at 1.3 (format 6), this should work fine in all current version, saving will update the format.

**Comment by Maverick4jc** [comment]
Thank you so much! Super helpful!
