### ISSUE TITLE
Spanish translation In the places Unseen

### ISSUE THREAD

**Issue by FAB81** [NPBruce/valkyrie#778]
Hello,

I have translated into spanish In the Places Unseen adventure for MOM2. Here you can find the document with the translation.
 I hope it will be useful.

Fran
[Localization.Spanish.txt](https://github.com/NPBruce/valkyrie/files/1864932/Localization.Spanish.txt)

**Comment by NPBruce** [comment]
@LordPyrex is the Author, so handing this over to him.

**Comment by LordPyrex** [comment]
Thank you for the translation! I have added the file to the directory and updated it in my branch. New downloads and updates will include the file. I'm closing this issue to remove it, but if there are any changes that need to be made please post in this thread and I can make changes as needed.
