### ISSUE TITLE
Valkyrie apk for Kindle Fire 10 HD 2017?

### ISSUE THREAD

**Issue by dalembraun** [NPBruce/valkyrie#779]
Any chance the android apk might be made compatible with Kindle Fire 10 HDs?  I can sideload it onto my Kindle Fire 10 HD 2017 (2nd Gen), and it launches.  It shows the Unity splash screen, then gets to the first menu (choose which game you want to use), but none of the items are active because Valkyrie can't find the install directory.  Since this tablet allows the use of both SD card storage and internal storage, I've tried having Mansions of Madness installed on the SD card and on the internal storage, but neither install method helps.  MoM launches just fine; Valkyrie also launches, but cannot find install files.

**Comment by dalembraun** [comment]
if this helps, it appears that the MoM install area might be in /sdcard/Android/data/com.fantasyflightgames.mom  (/sdcard being the internal storage area of the tablet, which is a redirect from /storage/sdcard0), and /storage/sdcard1/Android/data/com.fantasyflightgames.mom for the plugin SD Card.

**Comment by NPBruce** [comment]
Valkyrie is looking for a file ending in ".com.fantasyflightgames.mom.obb" which is located in <storage>"/Android/obb/com.fantasyflightgames.mom".

However I am not sure if the Kindle version even uses obb files as these are a play store thing.  Do you have any obb files on your device?  If not are there any single large (hundreds of MB) files you have associated with an FFG app?

**Comment by redwolf2** [comment]
https://developer.amazon.com/de/docs/app-submission/understanding-submission.html

>  Binary blobs (.obb) are not supported by the Amazon Appstore, so it is up to the developer to install external resources in the proper path after downloading them at runtime, and to submit an APK compiled without .obb files.

Try this: https://www.apk4fun.com/apk-obb/181219/

**Comment by redwolf2** [comment]
I added a guide here: https://github.com/NPBruce/valkyrie/wiki#fire-os

**Comment by dalembraun** [comment]
Had a chance to play with my Fire.  Works great with the above info (copying obb to correct location).  I think that some of the issues I had with certain MoM Scenarios are probably related to the scenarios themselves.  Things like some buttons having long menu names, or empty buttons/text windows, or flipping between english and french.  It could also be due to not actually playing the scenarios, but just clicking through all the explores, searches, etc., just to see if it'd crash.

I also tried the option of having MoM installed on my SD Card by using the Fire Storage option to move the App to the SD card, and it still ran with the obb on the internal storage.

From what I've seen, you provided the solution!  I'm willing to call this closed.

**Comment by NPBruce** [comment]
If any developers want to find a better solution for FireOS, I am open to pull requests.

**Comment by dalembraun** [comment]
Thanks again for the fast response. I plan on hosting three MoM games at a local convention and I wanted to highlight the user-made scenarios.
