### ISSUE TITLE
#monsters variable not working outside of testing.

### ISSUE THREAD

**Issue by Maverick4jc** [NPBruce/valkyrie#780]
Using D2E.  I created 3 monster spawns. First one has #monsters == 1, second has #monsters == 2, third has #monsters == 3. Basically I needed each round to spawn an open group but didn't want to repeat the same group. 1 monsters is constantly on the map (respawns immediately if it dies.)
[EditorQuest3.zip](https://github.com/NPBruce/valkyrie/files/1873486/EditorQuest3.zip)
.  It works great in testing and does exactly what I intended but when I run it through the main menu it continues to spawn the same group over and over.  I don't think it's recognizing the variable.  Suggestions?  Am I missing something?

[SpawnOpenGroupEntrance1]
xposition=18
yposition=-21
buttons=1
event1=EventButton
conditions=#monsters,==,1
audio=AudioButton1
traitpool=cave water wilderness dark cursed

[SpawnOpenGroupEntrance2]
xposition=18
yposition=-21
buttons=1
event1=EventButton
conditions=#monsters,==,2
audio=AudioButton1
traitpool=cursed cave wilderness dark water

[SpawnOpenGroupEntrance3]
xposition=18
yposition=-21
buttons=1
event1=EventButton
conditions=#monsters,==,3
audio=AudioButton1
traitpool=cursed cave wilderness dark water

**Comment by NPBruce** [comment]
With a quick look:

 - If "Spawn From New Open Group" is selected and there are no monsters, then nothing will happen, all following events require #monsters to be 1, 2, 3 or 4.

 - If "Spawn From New Open Group" is selected and there are any non open groups in play the numbers will be wrong.

 - If Group 1 and two are present and 1 is defeated this will try to respawn 2.

I am not really sure what you are trying to do, but I think you are going about it the wrong way.  For a start, add each unique spawn as a monster type for each other unique, this will prevent them for randomly selecting the same monster type:

https://github.com/NPBruce/valkyrie/wiki/QuestIniSpawn#monster

**Comment by Maverick4jc** [comment]
I see my problem.  Thanks!
I added each unique spawn as a monster type for each other unique so they would not spawn duplicates. I am still trying to figure out how to get the three spawns to spawn separately though. So the event triggers, a "Spawn From New Open Group" is selected which randomly spawns one of the three groups, then when the event triggers again at the start of the next round, and "Spawn From New Open Group" is selected it will spawn one of the two remaining if the 1st is not defeated, then when the event triggers again at the start of the next round, will spawn the last if the previous two are not defeated. So basically the spawn passes over if it is already active. Hope that makes sense.

**Comment by NPBruce** [comment]
Currently this done be done (easily)

What you are after is the #Defeated event trigger.  This can be used to trigger events when a monster is defeated so you can track what is around (rather than just a number).

The bad part is that you have to know the monster type to use defeated, so it can't be used for random groups.

A painful work around is:

* Track all non-random groups, using spawn to set a present var and #Defeated to clear.
* Check #monsters for total count and subtract 1 for each known non-random monster

This still won't tell you which random groups are out though.

Feature request to do this is here:
https://github.com/NPBruce/valkyrie/issues/579

**Comment by Maverick4jc** [comment]
Thanks so much for always responding so quickly!

I sat at my computer screen for a while trying to think of a clever way to get this done.  In the end I went about it in a not so clever but effective way.  For each specific open group I assigned it a color. Red, green, and purple and created a matching variable. If they are spawned it instructs the player to put an objective token on that monster card (red, green, or purple). At the start of a round it asks the player if they defeated a "token" group (it's what I'm calling them). If yes they are prompted to select a color. Then that variable is reset to allow that group to spawn once again.

I noticed that once an open group spawns a certain monster it sticks with that monster every time it is spawned again. So I created 3 red groups, 3 green groups, and 3 purple groups. This gives the illusion for what I want. It's a little more tedious for the player but I think it works fine.

Thanks again!  I really am loving this program. It's been a great project!

**Comment by Maverick4jc** [comment]
Update: I scrapped the colored token idea.  What a mess and hassle for the player.  I made it much more simpler and it works just fine. It should be a viable option for those trying to solve this problem. I have used it on two separate quests with success on both.

[EventReinforcements]
display=false
buttons=1
event1=SpawnReinforcementOpenGroup1 SpawnReinforcementOpenGroup2 SpawnOpenGroup3
trigger=EndRound
randomevents=true

[SpawnOpenGroup1]
xposition=2
yposition=-7
buttons=1
event1=EventCaveObjective
audio=AudioButton1
monster=SpawnOpenGroup2 SpawnOpenGroup3
traitpool=cursed dark wilderness water cave

[SpawnOpenGroup2]
xposition=8
yposition=-15
buttons=1
event1=EventButton
operations=RiversEdgeOpenGroup,=,1
conditions=RiversEdgeOpenGroup,==,0
audio=AudioButton1
monster=SpawnOpenGroup1 SpawnOpenGroup3
traitpool=cursed dark wilderness water cave

[SpawnOpenGroup3]
xposition=18
yposition=-21
buttons=2
event1=EventGroupLimitReset
event2=SpawnReinforcementOpenGroup1 SpawnReinforcementOpenGroup2 SpawnOpenGroup3 EventGroupLimitReached
operations=GroupLimitReached,+,1 OpenGroup3,=,1
conditions=GroupLimitReached,<=,2 OpenGroup3,==,0
randomevents=true
audio=AudioButton1
monster=SpawnOpenGroup2 SpawnOpenGroup1
traitpool=cave water wilderness dark cursed

[SpawnReinforcementOpenGroup2]
xposition=18
yposition=-21
buttons=2
event1=EventGroupLimitReset
event2=SpawnReinforcementOpenGroup1 SpawnReinforcementOpenGroup2 SpawnOpenGroup3 EventGroupLimitReached
operations=GroupLimitReached,+,1 OpenGroup2,=,1
conditions=GroupLimitReached,<=,2 OpenGroup2,==,0
randomevents=true
audio=AudioButton1
monster=SpawnOpenGroup2

[SpawnReinforcementOpenGroup1]
xposition=18
yposition=-21
buttons=2
event1=EventGroupLimitReset
event2=SpawnReinforcementOpenGroup1 SpawnReinforcementOpenGroup2 SpawnOpenGroup3 EventGroupLimitReached
operations=GroupLimitReached,+,1 OpenGroup1,=,1
conditions=GroupLimitReached,<=,2 OpenGroup1,==,0
audio=AudioButton1
monster=SpawnOpenGroup1

[EventGroupLimitReset]
display=false
buttons=0
operations=GroupLimitReached,=,0 OpenGroup1,=,0 OpenGroup2,=,0 OpenGroup3,=,0
audio=AudioButton1

[EventGroupLimitReached]
buttons=1
event1=EventButton
operations=GroupLimitReached,=,0 OpenGroup1,=,0 OpenGroup2,=,0 OpenGroup3,=,0
conditions=GroupLimitReached,==,3
audio=AudioButton1

[06_TheShadowVault.zip](https://github.com/NPBruce/valkyrie/files/1888498/06_TheShadowVault.zip)
