### ISSUE TITLE
Custom Images using the Editor on a Mac

### ISSUE THREAD

**Issue by escoses100** [NPBruce/valkyrie#784]
I have been really happy with the results of the editor on a Mac so far.  I've come to a point where an online tutorial ( https://docs.google.com/document/d/1Gi5gTwKkw84Px0Lvk-bJ3Aml_vF3ZoljjB6a8FjWGt8/edit# ) talks about custom images and custom audio with windows app data folders as the reference to include those images.  I have also noticed that some of the scenarios have custom images.  Where is the folder on a Mac that I could put custom images and then reference them in the scenario editor.  I looked a the contents of the app package as well as in the library folder on the Mac and could not find where I could put the images.  For example, if I wanted to add a UI with a custom image using the editor running on a Mac - how would I do that? (and I assume custom audio would work the same)

**Comment by escoses100** [comment]
Worked like a charm.  This entire project is amazing!

**Comment by scrubbless** [comment]
I've added the Mac location to the tutorial. :) 

Cheers Bruce.

**Comment by scrubbless** [comment]
Hey #escoses100 is this resolved? If so can you close the issue?

**Comment by redwolf2** [comment]
I will close. We can reopen it, if there are more questions.

**Comment by escoses100** [comment]
Thanks,
Sorry about the delay.
