### ISSUE TITLE
How to force investigators choice.

### ISSUE THREAD

**Issue by mamantins** [NPBruce/valkyrie#785]
Hello all,

How to force players to choose their investigators amongst those?
Michael McGlen 
Jenny Barnes
bob jenkins
Ritta young
Predston Fairmont
Vincent Lee

I know that I can just ask the user to play by the rules... but is there a way to force it?

Thanks for your help.
Mam's

**Comment by redwolf2** [comment]
There is no such implementation to do that. But this would be a nice enhancement and would allow more character story driven scenarios.

**Comment by mamantins** [comment]
I will ask the player to choose the appropriate one.
On the other hand, how to force someone to pick another character? 
Mark the investigator eliminated I see how to do but include a new one...? How to do that?

**Comment by redwolf2** [comment]
> On the other hand, how to force someone to pick another character?

Via narration ;). You tell them "Remove the investigator X from the game and introduce Y as the new investigator"

**Comment by LordPyrex** [comment]
Well, there really is no way to mark an investigator as eliminated. The eliminated investigator is how you trigger the game over sequence, mainly for a scenario to be marked as a loss. I think @redwolf2 had the best idea by saying that you should mention them in your scenario's description.

**Comment by LordPyrex** [comment]
> Via narration ;). You tell them "Remove the investigator X from the game and introduce Y as the new investigator"

The only problem with this is that Valkyrie will still call the Investigator that was originally selected. There isn't currently a way to handle this kind of replacement.

**Comment by redwolf2** [comment]
Only if random encounters and default mythos phases are used
https://github.com/NPBruce/valkyrie/issues/439

**Comment by scrubbless** [comment]
You can use the #hero<name> variable in events to single out investigators.

For example, you can create an event that tests #heroashcanpete = 1.

If that Investigator is selected then it will trigger.

You could then right an event that checks that the investigators are present before allowing the scenario to start.


Your start event has an event loop that loops a number of times equal to the #heroes variable. Each time it loops it checks for the existence of the investigators you have specified. If at the end of the chain (runs limited by #heroes) it has not detected #heroes number of you "chosen" investigators. It ends the scenario with a message telling the players to pick X investigators.

For example:

 In this example I'll use 3 investigators.
Jenny Barnes
Bob jenkins
Ritta young

1. Create an event that triggers from Startevent (EventStart). In this event set up some variables using "assign"

    LoopEnd = #heroes

This variable will be used to control the number of times the "Loop" will run.

2. Create an event to act as the start of your "loop" (Event like). In this event create a test that checks for the loop end condition.

Test:
CheckLoop ! LoopEnd

(This variable will act as a counter)

3. Under the "Loop" (EventLoop), set the event order to "ordered" (default). Then create an event for each "valid" investigators.

EventJennyBarnes
EventBobJenkins
EventRittaYoung

In each of these events set a test checking if the investigators in question has been selected. And add a section test to stop the event from triggering a second time.

Tests:
EventJennyBarnes
   #herojennybarnes = 1
   JennyBarnesChecked ! 1

Then create an assign variable to add one to "CheckLoop" and a second one to fill in the investigators "checked" variable .(stopping it running more than once). Finally add an event to add one to a variable called  "ValidInvestigator".

Assign":

CheckLoop + 1
JennyBarnesChecked = 1
ValidInvestigator + 1

At the end of each of these events set the next event to  the loop event (EventCheckLoop).

Add a "catch all" event under the  loop event (EventLoop), under the other investigators events. This event will have no test and simply add one to the CheckLoop variable.

Event catch all
Assign:
CheckLoop + 1.

At the end of this event point it back to the loop event (EventLoop).

5. Go back to your start event (Event start) and add another event under the loop event (EventLoop). This will be your validation event (EventValidation).

In this a set test to check that the "ValidInvestigator" variable is not equal to #heroes.

If it triggers set the dialogue text to tell the players that they have not selected valid investigators and end the scenario.

7. In the start event (EventStart) add a final event under the validation event. Which is your normal scenario chain (place tiles etc).

This series of events will act as a check to make sure players are abiding by the specific rule you've added.

I will add some screenshots and an example scenario when I get to a pc!

**Comment by mamantins** [comment]
That will completely solve my issue.
Thanks!
I proceed with something like this.

**Comment by scrubbless** [comment]
I've updated the mail comment with a step by step. Sky is the limit on this one! Have fun :)

**Comment by NPBruce** [comment]
I have a simplified suggestion:

operations=ValidInvestigators,+,#HeroJennyBarnes ValidInvestigators,+,#HeroNext ValidatInvestigators,+,#HeroEtc

Next event:
conditions=ValidInvestidators,==,#Heroes

**Comment by scrubbless** [comment]
Where would you put that? Some where in the event.ini I assume.

**Comment by NPBruce** [comment]
You can do it all in the editor, I was just trying to make your solution easier, the result is the same.  Rather than having an event for each investigator that adds 1 to the valid count, just add up all the #Hero vars that you are interested in.

**Comment by scrubbless** [comment]
You're completely right! I've made that extremely complex. 

Sorry took thinking it over in the shower to understand the concept.

**Comment by mamantins** [comment]
Thanks!
