### ISSUE TITLE
Created starting intri like ffg

### ISSUE THREAD

**Issue by dagniel79** [NPBruce/valkyrie#786]
How can we created a fade in intro. And how can we insert the flavor text into the original ffg frame. Last one. The clue token intro must be in text box or i missing something. Thank for answers

**Comment by redwolf2** [comment]
> How can we created a fade in intro. 
No way to do it ATM. But you can show multiple images after another using events and UI Elements. No animation though. You chain them using events.

> And how can we insert the flavor text into the original ffg frame.
https://github.com/NPBruce/valkyrie/wiki/TutorialUIElements

> The clue token intro must be in text box or i missing something. Thank for answers

Yes, currently there is no mechanic to tell the user how many clue token each player get. So this has to be done via events.

**Comment by dagniel79** [comment]
Thank you All
