### ISSUE TITLE
RootCellar MoM1E gets RootCellar MoM2E

### ISSUE THREAD

**Issue by eorahil** [NPBruce/valkyrie#79]
In the editor, if you select the TileSideRootCellar MoM1E, it gets the second edition one. I think the bug is on the tiles.ini file inside mom1e folder. tiles.ini should have [TileSideRootCellar1E] instead of [TileSideRootCellar]. The reverse for [TileSideCornerHallway] should be TileSideRootCellar1E.

**Comment by eorahil** [comment]
Solved locally. Corrections will be included in my next localization pull request

**Comment by NPBruce** [comment]
Cherry picked to separate issue from pull request.
