### ISSUE TITLE
Question on Open Monster Actions - D2E

### ISSUE THREAD

**Issue by Maverick4jc** [NPBruce/valkyrie#790]
My understanding is that if you want custom actions (telling the player what monsters should do in what order) you need to create a custom monster and then create those activations and assign them to the custom monster. I do not see a place to add actions to existing monsters or a spawn event. Is that in the works at all?

I am fine to do that for any specific group of monsters but D2E uses a lot of open groups.  Is there any way to assign actions to an open group (maybe a spawn event) without re-creating every monster group and adding activations to each of them to then use those as options for an open group? Thanks Bruce.

**Comment by NPBruce** [comment]
This is tricky.  While I could do something it almost certainly won't work how you want it to.  There are a lot of different monster types and having an activation that works for all is very difficult.  There are 3 base categories of monster (ranged, skirmish, brawl) that each have 3 standard activations but even these have exceptions and exclusions all over the place.

Another reason it shouldn't be in the spawn, is what happens when you have two spawn events, with conflicting activation setup and the same monster type?

Perhaps give a detailed example of what you are trying to achieve and I'll think about options?

**Comment by Maverick4jc** [comment]
Death on the Wing - Encounter II is a good example.  Some monsters should be attacking heroes and some should be attacking guards.  Belthir is not a problem because I can just create a custom monster for him and given him details.  The open group is on the waterfall and should attack guards , not heroes.  The Elementals can attack heroes as normal.  

The Masquerade Ball - Encounter I is another good example.  The monsters can attack heroes but also need to unmask guests and then escort them off the map.  

Any thoughts?  I can put actions on spawning but they only list once and the player most likely won't remember what's first and then second and so forth.  Do you think the solution to Open Groups (as they cause so many problems) is just to not have them if they need specific actions other than attacking heroes?  Maybe have random spawns instead?  Just not sure how to make sure the player isn't having to do the thinking for the monsters.

**Comment by NPBruce** [comment]
Having a standard activation for a random monster type is likely to go wrong anyway though.  More broadly than this, take for example an Ironbound group vs Goblins.  There are some Quests were to pick one is to give up on the scenario, and others where the choice is reversed.  I think you are going to have to either have a short list of accepted monsters where they have non combat roles, or have a bigger rethink on how the conversion functions (like having plot-only scurrying goblins going around unmasking quests, which are not represented on the board).

**Comment by Maverick4jc** [comment]
You're absolutely right.  I think I have been trying to stay too loyal to the quest book. I need to allow myself some liberty while staying true to the theme and spirit of the story.  Thanks for the reminder and I will adjust my thinking.

**Comment by NPBruce** [comment]
Closing as no plan to implement at this stage.
