### ISSUE TITLE
Scenario can't be loaded

### ISSUE THREAD

**Issue by dagniel79** [NPBruce/valkyrie#791]
Hi all,
for the very fist time today i try to play my scenario with the START SCENARIO, So It is on the menu selection but after the presentation the clic button (start) resend me on the START SCENARIO menu?  the game doesn't load at all.??? Everything was ok in the past... so what's happening this time? i have transfer on my cell phone all file and nothing work on the phone too.  I will to cry my life if everything is gone....

**Comment by LordPyrex** [comment]
Hey dagneil, the most common reason for this is that you used an asset that is in an expansion. If you haven't activated this specific expansion from the main menu under 'Select Content' then the scenario will crash back out to the main menu. The reason you were able to see it in the test options is that when testing in the editor Valkyrie automatically turns them all on.

So start there and let us know if this isn't a solution to your problem.

**Comment by LordPyrex** [comment]
See #772 for more info

**Comment by dagniel79** [comment]
Right on!!! My mistake was on creature type. I did not notice the aspect UNDEAD was activated with my Phantom selection from the basic box. I have remove undead and everything work well.... By the way do you know if  a FIX was release for cut and paste issue? Everytime when i doing it all the text after a ENTER his erased from the "INSTRING".. ??

AGAIN THANK A LOT FOR YOUR HELP!!!

**Comment by scrubbless** [comment]
If this fixed please feel free to close the issue.
