### ISSUE TITLE
New Scenario - Believe or Die 1

### ISSUE THREAD

**Issue by FASTNAVi** [NPBruce/valkyrie#792]
Hi,

please add my scenario to Valkyrie system. I have just one question. I made my scenario in version 1.7.0c, so in the quest.ini is version 9. Is it necessary to change it to 8?

Thanks for answer and enjoy!

https://github.com/FASTNAVi/Believe_or_Die_1/tree/master/Believe_or_Die_1

**Comment by NPBruce** [comment]
Added.

**Comment by FASTNAVi** [comment]
ok, changed to version 8

**Comment by scrubbless** [comment]
Just test it in 1.6.1 a bit, just to be sure!

**Comment by NPBruce** [comment]
https://github.com/NPBruce/valkyrie/wiki/QuestFormat#format-9-prerelease

Make sure that your ending events are named EventEndSomething, and you can't use custom attacks or spelldefence/spellattack.

**Comment by scrubbless** [comment]
Good call. I've used EventEnd[name] to donate events that happen with the EventEnd trigger, as a way of sorting them together. That might have become confusing.

Thanks for the information, until now I did not realise you could actually quit out of a scenario. Must have missed the Wiki on it!
