### ISSUE TITLE
D2E Question Regarding Monster Actions

### ISSUE THREAD

**Issue by Maverick4jc** [NPBruce/valkyrie#793]
It seems like in the Road To Legends app, the monsters actions list 2 or 3 things for the player to follow.  In Valkyrie it's usually just 1.  For instance, in RTL for an Ettin you'll see "Engage a hero, Attack a hero, Use throw. In Valkyrie it's usually just 1 of those. Thanks.

**Comment by NPBruce** [comment]
What version are you running?  This is a bug that was fixed in 1.7.0c, and from the top of my head wasn't a problem in 1.6

**Comment by Maverick4jc** [comment]
I'm running 1.6.  I have been creating content so I haven't been using 1.7.0c.  Glad it's been fixed!  That's great news. Thank you!
