### ISSUE TITLE
Custom Monsters that share models

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#796]
Hi,

I have an issue with custom monsters not being identified with a symbol when there are multiple.

For example I have a custom monster that uses the "MonsterBase" catagory, and a "Zombie" monster, however when they both spawn at the same time, neither has an identifier to tell them apart:
![image](https://user-images.githubusercontent.com/32058089/38866362-94110bc2-4238-11e8-8b9f-9813de2ef8cd.png)

Have I missed something here, or is it a bug?

**Comment by NPBruce** [comment]
This is a bug, need to think about this one.

**Comment by BenRQ** [comment]
Hi @scrubbless,
can you please provide a small scenario to reproduce that problem ?

**Comment by scrubbless** [comment]
Example Scenario Attached.
[ExampleCustomM.zip](https://github.com/NPBruce/valkyrie/files/2470378/ExampleCustomM.zip)

**Comment by BenRQ** [comment]
Thank you for the example, it is now fixed.

**Comment by BenRQ** [comment]
Will be available in release 2.1
