### ISSUE TITLE
Importing Data from lastest MoM Official App

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#798]
It looks like they have jumbled up the images in the latest version of the MoM App. I renamed my Valkyrie directory in %Appdata% and reinstalled 1.6.1, then did the import again. But all of the tokens are incorrect.

This is going to cause problems for people downloading 1.6.1 and importing content.

All of the tokens have the wrong images as of this update:
![image](https://user-images.githubusercontent.com/32058089/39001315-ee1000ea-43ed-11e8-9119-d2e2fe01a09a.png)

1.7.0d works correctly, but it is in Pre-release I am not sure on the timeline for release.

My hand has kinda been forced to continue developing my scenario in 1.7.0d. I have taken a couple of full backups of what I have so far!

**Comment by NPBruce** [comment]
Duplicates #797 . Next release is waiting on #758 and ideally #728 .
