### ISSUE TITLE
Issue displaying titles/name, language dependent

### ISSUE THREAD

**Issue by montseel** [NPBruce/valkyrie#799]
English language selected:
![screen shot 2018-04-21 at 20 54 35](https://user-images.githubusercontent.com/38591534/39087802-a3cf83a6-45a6-11e8-87d8-444da2d278d6.png)

Spanish:
![screen shot 2018-04-21 at 20 55 09](https://user-images.githubusercontent.com/38591534/39087809-b7ca69a2-45a6-11e8-8a9b-4b0ce96c0c81.png)

It also happened with the downloaded scenarios which are not playable due to the fact that I'm missing the necessary expansions. 

Saw it as well when selecting the available expanions, but couldn't reproduce it.

**Comment by NPBruce** [comment]
This is a known problem when importing MoM 1.5 (the latest version from a few days ago) in all versions of Valkyrie other than 1.7.0d.  If you are using an older import, or already using 1.7.0d then this is a problem, otherwise it is not. (#797)

**Comment by montseel** [comment]
Just for reference, it was Valkyrie 1.6.1 on a Mac.

**Comment by NPBruce** [comment]
OK closing this as a known, resolved issue.  1.7.0d can be used for now, a new stable will be out Soon.
