### ISSUE TITLE
Documentation for quest editor

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#8]
Quest editor usage is not obvious, need to add instructions to the wiki

**Comment by NPBruce** [comment]
Instructions added.  Tutorial that was written as a document pasted in, need formatting and fixes.

**Comment by Liquidlogic1** [comment]
I formatted the Quest editor tutorial that you pasted in.  I also altered the tutorial slightly to change the use of MPlace for monster groups. I added in a unique monster to demonstrate how to use MPlace.

I kept my method for creating a locked/unlocked door, but I will revisit this in the future (or you can edit if you'd like).

**Comment by NPBruce** [comment]
Done, thanks.
