### ISSUE TITLE
Hallway1 crashes the app

### ISSUE THREAD

**Issue by eorahil** [NPBruce/valkyrie#80]
If you try to add the Hallway1 tile to the map editor, it becomes blank and an exception is generated inside the debug log file.
The cause is that, inside Mom\mom1e\tiles.ini the tag
[TileSideHallway1]
image="img/Tile_Hallway_1_MAD01.dds"
traits=inside small hallway
reverse=TileSideCrypt
is incorrect because the image should be a jpg file. so replacing .dds with .jpg should solve the problem

additionally the PPS should be set so
pps=72
is needed too.

**Comment by eorahil** [comment]
Solved locally. Corrections will be included in my next localization pull request

**Comment by NPBruce** [comment]
Cherry picked to separate issue from pull request.
