### ISSUE TITLE
Image issues on Mac

### ISSUE THREAD

**Issue by slycozzolino** [NPBruce/valkyrie#800]
See items 2 and 3 here - (https://github.com/NPBruce/valkyrie/issues/770#issuecomment-383319699)

**Comment by NPBruce** [comment]
Duplicates #797 if you are importing from MoM 1.5 and using a Valkyrie version before 1.7.0d

**Comment by NPBruce** [comment]
I am going to close this on the assumption that this is a duplicate, reopen if I am wrong.
