### ISSUE TITLE
Descent Shop item duplicates

### ISSUE THREAD

**Issue by DelphiDie** [NPBruce/valkyrie#805]
### Description of Problem or Question
I noticed that there is still a problem with Descent shop items in the Valkyrie Shop interface. The game often creates duplicates of items which should not exist.

There are only 2 items that could be legitimate duplicates: The Leather Armor and the Iron Shield.
(of course only if the heroes don't already own one of these items). See the attached screenshots for examples.

### Valkyrie Version
2.0

![valkyrie shop item error](https://user-images.githubusercontent.com/26790002/39234009-4a2cf99a-4872-11e8-8455-9b16ae905a1e.png)
![valkyrie shop item error2](https://user-images.githubusercontent.com/26790002/39234127-af85428e-4872-11e8-841f-21b398e6ec38.png)

**Comment by NPBruce** [comment]
I will investigate.

**Comment by BenRQ** [comment]
This is definitely a bug.
Also I'm surprised nobody reported the white text on yellow background for the price :P

**Comment by BenRQ** [comment]
@DelphiDie what would be the maximum number of  Leather Armor and Iron Shield ?
I will try to support that.

Also I'm pretty sure you can have a new leather armor or iron shield in the shop, even if one hero has it in his inventory.

**Comment by BenRQ** [comment]
Potential fix available, just waiting for your feedback regarding the quantity

**Comment by DelphiDie** [comment]
The quantity for the leather armor and the iron shield is 2.

Another exception might be the "Lucky Charm" item. The thief class has this one as starting gear, but there is also one in the shop item deck.

**Comment by BenRQ** [comment]
Fixed.
For lucky charm, it's already working as class and act item are two different items.

I have also changed the background color for class/act and price.
![image](https://user-images.githubusercontent.com/40794717/46585830-40fbde00-ca76-11e8-9d2f-8fe889668d73.png)
