### ISSUE TITLE
Cant complete import with version 2.0 and mom 1.5

### ISSUE THREAD

**Issue by aatriff** [NPBruce/valkyrie#806]
Cant complete import with version 2.0 and mom 1.5
both on macos and windows.

1. Valkyrie starts
2. About 3 seconds pass
3. App is freezed
4. "Try to reimport"

On windos i've try to run as admin, on macos i've try to "sudo open /Applictaion/Valkyrire.app"

I can provide any logs, but i'm not sure where to find them

**Comment by NPBruce** [comment]
Try ~/Library/Logs/Unity/Player.log

I am not sure I understand your list though.  Do you reach the game select screen?  Does the freeze happen before or after importing?  Perhaps try deleting ~/.config/Valkyrie and trying again (back up any saves or scenarios first).

**Comment by redwolf2** [comment]
Valkyrie 2.0 works quite well with mom 1.5 on my machine.

During the import there should be the animated valkyrie logo. After the import there is an 3 up to 10 second freeze, during which the bundles getting imported `%appdata%\Valkyrie\MoM\import\bundles.txt`. This is normal, just wait a bit.

**Comment by aatriff** [comment]
> During the import there should be the animated valkyrie logo. After the import there is an 3 up to 10 second freeze (the logo animation suddenly stops), during which the bundles getting imported %appdata%\Valkyrie\MoM\import\bundles.txt

Okey, so just after logo stops, import is interrupted and i'm get back to the first screen with welcome message (reimport ..)

> Do you reach the game select screen?
No

> Try ~/Library/Logs/Unity/Player.log
[Player.log](https://github.com/NPBruce/valkyrie/files/1949919/Player.log)

**Comment by NPBruce** [comment]
The log all looks fine.  What happens when you press the MoM button?  Nothing or a crash?

**Comment by aatriff** [comment]
Suddenly, i reinstalled MoM app and it fixes my problem.

> What happens when you press the MoM button? Nothing or a crash?

Nothing, but now it's ok.

Thanks for help =) I'll close, cause it's fixed
