### ISSUE TITLE
where to upload translations for scenarios?

### ISSUE THREAD

**Issue by zcaalock** [NPBruce/valkyrie#808]
### Description of Problem or Question

I have polish translation for Exotic Material scenario.
[Localization.Polish.txt](https://github.com/NPBruce/valkyrie/files/1951340/Localization.Polish.txt)

### Attach Save, Quest or Scenario
Saves:  
%appdata%/Valkyrie/MoM/Save  
%appdata%/Valkyrie/D2E/Save  
Quest:  
%appdata%/Valkyrie/D2E/Editor  
Scenario:  
%appdata%/Valkyrie/MoM/Editor

**Comment by NPBruce** [comment]
Exotic Material is mine, so I will add it.  In general you should contact the author of the scenario and ask them for inclusion.

**Comment by NPBruce** [comment]
Done.
