### ISSUE TITLE
Polish version for Believe or Die - A Search for ""Ashcan"" Pete

### ISSUE THREAD

**Issue by zcaalock** [NPBruce/valkyrie#810]
### Description of Problem or Question

here is my translation. If someone can add it to the game it would be nice.
[Localization.Polish.txt](https://github.com/NPBruce/valkyrie/files/1959292/Localization.Polish.txt)

### Attach Save, Quest or Scenario
Saves:  
%appdata%/Valkyrie/MoM/Save  
%appdata%/Valkyrie/D2E/Save  
Quest:  
%appdata%/Valkyrie/D2E/Editor  
Scenario:  
%appdata%/Valkyrie/MoM/Editor

**Comment by NPBruce** [comment]
Have you contacted FASTNAVi?  This is their scenario and they will need to add this.

**Comment by scrubbless** [comment]
He put an email in his Scenario Description. Might be the best way to contact him.

**Comment by FASTNAVi** [comment]
Scrubbless, zcaalock: Thanks you two for help. I am on vacation and I will check the translation in second part of the week. The same for feedback from scrubbless =)

**Comment by redwolf2** [comment]
I will close. We can reopen it, if there are more questions. Discussion can continue, even on closed issues.
