### ISSUE TITLE
how can i find tiles? 

### ISSUE THREAD

**Issue by zcaalock** [NPBruce/valkyrie#812]
### Description of Problem or Question
So i made few tiles saved and started test and i can see only black background. I found that the window is out of position so i have to scroll it untill i find tiles. After comming back to editor is same case, cannot see tiles i have to look for it allover. 

The first tile is set at position 0,0. I checked that in tiles.ini

any help?

### Attach Save, Quest or Scenario
Saves:  
%appdata%/Valkyrie/MoM/Save  
%appdata%/Valkyrie/D2E/Save  
Quest:  
%appdata%/Valkyrie/D2E/Editor  
Scenario:  
%appdata%/Valkyrie/MoM/Editor

**Comment by NPBruce** [comment]
I take it you have added the tiles just that they aren't under the camera?

Try setting the event that adds the tiles to a camera position above the tiles.  Alternatively you can move the tiles to be near the default camera position.

You can also set min and max camera positions to stop the camera from being able to leave the tiles.

**Comment by NPBruce** [comment]
In an event press the last box after position until it says "min cam" and select a position.  Then do the same in another even for max cam.  You have to run both events to take effect.

**Comment by zcaalock** [comment]
still cannot see anything :(

[Event01_camera]
buttons=1
event1=
trigger=StartRound
mincam=true
xposition=1.75
yposition=0

[Event1]
buttons=1
event1=

[Event01_test]
buttons=1
event1=
maxcam=true
xposition=1.75
yposition=7

==================

[Tile01_test]
xposition=0
yposition=0
side=TileSideCaveEntrance
rotation=90

[Tile02_test_01]
xposition=0
yposition=10.5
side=TileSideCaveBend

**Comment by scrubbless** [comment]
The Wiki has some helpful guides:
https://github.com/NPBruce/valkyrie/wiki

I also wrote a step by step guide for MoM scenario creation, it may be of help.
https://docs.google.com/document/d/1Gi5gTwKkw84Px0Lvk-bJ3Aml_vF3ZoljjB6a8FjWGt8/edit

**Comment by scrubbless** [comment]
Did this fix your issue @zcaalock ?

If so could you close the issue. :)

**Comment by zcaalock** [comment]
yes, you can close it:)

**Comment by scrubbless** [comment]
You should be able to comment and close.

I'd not @redwolf2 or @npbruce will close it off when they get round to it.

Glad you found what you needed, shout if you need any more help.
