### ISSUE TITLE
Add Quest to Valkyrie

### ISSUE THREAD

**Issue by DelphiDie** [NPBruce/valkyrie#813]
### Description of Problem or Question
Please add the following quest to Valkyrie:

https://github.com/DelphiDie/TheShadowRune/blob/master/Intro.jpg
https://github.com/DelphiDie/TheShadowRune/blob/master/TSR.ini
https://github.com/DelphiDie/TheShadowRune/blob/master/TSR.valkyrie

### Valkyrie Version
2.0

**Comment by NPBruce** [comment]
Done.
