### ISSUE TITLE
Tome of Horrors

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#815]
### Description of Problem or Question
The Tome of Horrors is not listed under the "Tomes" Sub menu. Is there a reason for this?

Its in the game, can be found under equipment, but I would expect it to be in tomes also.

### Valkyrie Version
2.0

### Attach Save, Quest or Scenario
N/A

**Comment by NPBruce** [comment]
It is classified as:
traits=equipment common

Does it have the keyword "tome" on the card?

**Comment by scrubbless** [comment]
You are completely right, it has an equipment tab. How very odd. I'll close this off!
