### ISSUE TITLE
Pre-Conditional Button texts

### ISSUE THREAD

**Issue by DelphiDie** [NPBruce/valkyrie#817]
### Description of Problem or Question
I'd like to request the addition of pre conditional button labels in a future version of Valkyrie.

Here is an example of what I have in mind:

Event.ini
[EventDialogue]
buttons=5
event1=EventGainEntryBribe
event2=EventGainEntryHero
event3=EventGainEntryClass
event4=EventGainEntryRelic
event5=EventGainEntryConvince

Localization.txt
EventDialogue.text,You approach the academy of Greyhaven, but a guard denies you entry.
EventDialogue.button1,[25 Gold] Bribe the guard {condition:$%Gold,>=,25}
EventDialogue.button2,[Leoric] Demand entry {condition:%HeroLeoricoftheBook,==,1}
EventDialogue.button3,[Runemaster] Demand entry {condition:%HeroClassRunemaster,==,1}
EventDialogue.button4,[Shadow Rune] Demand entry {condition:%RelicTheShadowRune,==,1}
EventDialogue.button5,Try to convince the guard

The idea is to have all buttons greyed out and unselectable if the specified condition isn't met.

This would allow for more complex Dialogues and mimic the system which is used in Road to Legend.

Edit: To get this working Valkyrie should also automatically write a % variable for each selected hero class at the start of the game. Example %HeroClassWildlander,==,1

**Comment by NPBruce** [comment]
You can do this the long way, by having different events and some of them set the button colour.  I've only ever seen one conditional option in RtL, so that wouldn't be hard, but yours would be a lot more involved.

I'll add this as a feature request.

**Comment by DelphiDie** [comment]
Thanks for considering this Bruce.

I think it would be possible to grey out entries by creating complex dialogues with multiple condition checks, but I'm not aware that there is a way to prevent the buttons from being clicked.

Btw. there are lots of these choices in Road to Legend. Here are just some examples:

![choice1s](https://user-images.githubusercontent.com/26790002/39473120-82d102c0-4d4d-11e8-830e-625ab96d4dab.jpg)
![choice2s](https://user-images.githubusercontent.com/26790002/39473121-82ea2624-4d4d-11e8-9099-c90460967ac8.jpg)
![choice3s](https://user-images.githubusercontent.com/26790002/39473122-8302cf3a-4d4d-11e8-8a28-dbecba39b6f0.jpg)
![choice4s](https://user-images.githubusercontent.com/26790002/39473123-831d4b26-4d4d-11e8-88f3-877bcc5d00c4.jpg)
![choice5s](https://user-images.githubusercontent.com/26790002/39473124-83366854-4d4d-11e8-8227-838ea40e5a6a.jpg)
![choice6s](https://user-images.githubusercontent.com/26790002/39473125-83501c4a-4d4d-11e8-97a3-8ff74679751f.jpg)
![choice7s](https://user-images.githubusercontent.com/26790002/39473126-8366cd28-4d4d-11e8-8e32-3a71df19af06.jpg)
![choice8s](https://user-images.githubusercontent.com/26790002/39473127-837efe98-4d4d-11e8-8307-4bdd2e2c0c57.jpg)
![choice9s](https://user-images.githubusercontent.com/26790002/39473129-83b609ba-4d4d-11e8-9cbe-221ebbb1c2c9.jpg)

**Comment by NPBruce** [comment]
> but I'm not aware that there is a way to prevent the buttons from being clicked.

A work around is to have the button lead to the same event.

**Comment by BenRQ** [comment]
Maybe there is an easy way to do it without any code change.
@scrubbless don't you have dynamic choices for text in your scenario?

**Comment by NicolaZee** [comment]
There is no easy way to do dynamic choices with more than 3 choices without a code change.
To code dynamic choices it is currently necessary to code separate events for each separate combination of choices.
So if there are 3 choices there needs to be 
Choice 3, Choice 2, Choice 1
Choice 3, Choice 1
Choice 3, Choice 2
Choice 2, Choice 1
etc.

In the example screenshot, there are 4 choices.  Coding every combo of 4 choices is possible but not really practical.  With 5 it becomes completely impractical.

In my scenario 'In the Dark' I get around this issue by just having the choices call up an event with the text; 'You've already asked me that question.'.  This is clearly a bodge and there have been complaints about it.

Having the functionality to disable choices would be very useful for 'In the Dark'.

**Comment by NicolaZee** [comment]
@scrubbless has a good description of how to implement dynamic choices in his very well put together guide in the section: Person Token with Several questions.
There are 7 events to cope with 3 choices which works out as 3!+1
With 4 events, the events would be 4*3*2*1 + 1 = 25
With 5 events, the events would be 5*4*3*2*1 + 1 = 121
etc

https://docs.google.com/document/d/1Gi5gTwKkw84Px0Lvk-bJ3Aml_vF3ZoljjB6a8FjWGt8/edit

So in your example we need events for every possibility of:
Talk - How are you?
Cost - What is the cost?
Time - What is the time?

These are (forgive me if I get it wrong, its late!) 7 permutations, then we need another "catch all".
1 - Talk, Cost, Time
2 - Talk, Time
3 - Cost, Time
4- Talk, Cost
5 - Talk
6 - Cost
7 - Time
8 - No questions - catch all.

**Comment by DelphiDie** [comment]
I recently thought about this again, and tried to come up with a better system which will cover all possible purposes to easily create choices in event options (mostly important for decisions and dialogues).

As NicolaZee pointed out the current way to handle complex dialogue trees quickly reaches it's limit if there are more than 3 options. So for the sake of an example of the current system let's keep a it at three.

[EventDialogueExample]
buttons=3
event1=EventDialogueChoice1
event2=EventDialogueChoice2
event3=EventDialogueChoice3

![Dialogue3](https://user-images.githubusercontent.com/26790002/57178415-dc6bfa80-6e6f-11e9-93e4-40e8b938c043.jpg)

This event will allow to create an entry point into a dialogue. I won't repeat NicolaZees description about the needed choices to create followup events which do not repeat previously selected events. Instead I want to propose a better (and more scalable way) to handle this by adding 2 new options:

[EventDialogueExampleNew]
buttons=3
event1=EventDialogueChoice1
event1conditions=
event1interaction=Enabled
event2=EventDialogueChoice2
event2conditions=Variable1,==,1
event2interaction=Disabled
event3=EventDialogueChoice3
event3conditions=Variable2,==,1
event3interaction=Invisible

Using this one event, the dialouge options could be dynamically altered to completely eliminate the need for permutated callback events.

The option "eventXconditions" would contain regular conditions, which have to be tested before the respective button is created. The default value of this would be empty (no test needed) in case this option is not specified.

When the "EventXconditions" option is specified, there are 2 possible outcomes:

a) If the condition is met, the button is created in the usual way, and the following option is ignored or defaults.
b) If however the condition is not met, the button is modified by looking at the following option.

The next option is "eventXinteraction" and would have 3 possible values:

Enabled: The event button is always shown and clickable. This would be the default value if the option is not specified or "EventXconditions" are met.
Disabled: The event buttion is visible but the font color is altered (I'd recommend the color grey), and it is unclickable.
Invisible: The event button is invisible and thus unclickable.

This is how the buttons would look if you take the variables I created in the above example into consideration:

Variable1 = 0, Variable2 = 0:

![Dialogue00](https://user-images.githubusercontent.com/26790002/57178607-6b2e4680-6e73-11e9-80b0-eadea64e3f78.jpg)

Variable1 = 1, Variable2 = 0:

![dialogue10](https://user-images.githubusercontent.com/26790002/57178622-b47e9600-6e73-11e9-9384-39d1842fd535.png)

Variable1 = 0, Variable2 = 1:

![Dialogue01](https://user-images.githubusercontent.com/26790002/57178631-e0018080-6e73-11e9-8f93-5ac67c547816.jpg)

Variable1 = 1, Variable2 = 1:

![dialogue11](https://user-images.githubusercontent.com/26790002/57178642-01626c80-6e74-11e9-8cde-f5cf8aa36d1d.png)

Being able to use these options would reduce the complexity of branching dialogues massively, as all choices could point back to the previous root event and could be dynamically altered by the use of variables.

**Comment by scrubbless** [comment]
I have been thinking a bit about what Bruce has said. 

I've started to use a lot of events where every option sets a variable then links to the same follow on event. This may be a way to do it.

While we wont be able to get out buttons it could make button presses 'null'.

For example:

Pick an optuon:
B1 》 set b1=1
B2 》set b2=1
B3 》set b3=1

All button press chains lead to the same event:

I  this event we have tests for all options

eventB1 - test b1==1 & b1available==1
eventB2 - test b2==1 & b2available==1
eventB3 - test b3==1 & b3available==1
EventRtrn - catch all, set all 'B' vars to 0 and return to pick event.

If a button is clicked but not 'available' (as set by var) the button press leads to the catch all loop back to the original question.

If the buttons are available it will t trigger the event.

**Comment by NicolaZee** [comment]
or example:

EventPick - Pick an option:
Button1 》 set b1=1
Button2 》set b2=1
Button3 》set b3=1

All button press chains lead to the same event:

In this event we have tests for all avaiable button events.

No text in event.

'Continue'
eventB1 - test b1==1 & b1available==1
eventB2 - test b2==1 & b2available==1
eventB3 - test b3==1 & b3available==1
EventRtrn - catch all, set all 'B' vars to 0 and return to pick event.

Instead of variables b1, b2. b3 and so on, I'd recommend one variable.
EventPick - Pick an option:
Button1 》 set button=1
Button2 》set button=2
Button3 》set button=3

I may have overlooked something but if the text on the button is along the lines of
{action} Button1
{action} Button2
etc
want you have to give the player back their action if the button is clicked and not available?
So the instruction to spend an action would need to be added to the active events?

**Comment by scrubbless** [comment]
You're right, it was hasty. A single button variable  makes more sense and yes the catch all would need to say something like.

'You already asked this question, do not spend an action {action}, you may ask a different question.'

A lot of the time it may be better to only use it to stop players asking the same questions. I'd probably still use a separate event with it's own unlocked buttons for 'disabled' questions as otherwise it would spoil the clue to have the leading question just telling you it's not available. However you could use the same follow on event so it would cut down time building the following chains.

As a work around it would limit the number of question permutation events youd need to create.

I still like Delphi's idea, its a lot more elegant.

**Comment by NicolaZee** [comment]
When all is said and done we still come back to the need to disable a dialogue button.

**Comment by scrubbless** [comment]
Yeh I agree, just giving out work around while we wait for those developments.

**Comment by DelphiDie** [comment]
Hi everyone. Just wanted to ask whether someone might take a look at implementing the proposed system at some point. It would really improve the way dialogues are handled significantly.

**Comment by mayjak** [comment]
@DelphiDie I'm looking into a few issues that are related to the variables themselves. Once I get more familiar with the related codebase I am planning to tackle this ticket.

**Comment by mayjak** [comment]
@DelphiDie I would like to save it in the .ini, not the localization file. The localization file should ideally not be used for driving scenario logic.
Format like this:
event1=<EventName>[,<Variable>,<Operator>,<Constant>[,<Secret>]]

[] are optional parts so you can either have
event1=<EventName>
event1=<EventName>,<Variable>,<Operator>,<Constant>
event1=<EventName>,<Variable>,<Operator>,<Constant>,<Secret>

Operators:
=
!=
>
>=
<
<=

Secret:
disabled (default): The button is visible, but disabled if the condition is not met.
hidden: The button is not visible if the condition is not met.

So in your example:

Event.ini
[EventDialogue]
buttons=5
event1=EventGainEntryBribe,%Gold,>=,25
event2=EventGainEntryHero,#HeroLeoricoftheBook,=,1,hidden
event3=EventGainEntryClass,#HeroClassRunemaster,=,1,hidden
event4=EventGainEntryRelic,#RelicTheShadowRune,=,1,hidden
event5=EventGainEntryConvince

Localization.txt
EventDialogue.text,You approach the academy of Greyhaven, but a guard denies you entry.
EventDialogue.button1,[25 Gold] Bribe the guard
EventDialogue.button2,[Leoric] Demand entry
EventDialogue.button3,[Runemaster] Demand entry
EventDialogue.button4,[Shadow Rune] Demand entry
EventDialogue.button5,Try to convince the guard

**Comment by Quantumrunner** [comment]
@mayjak 

I like this approach. As you already mentioned this lets the localization files stay true to their purpose.

Formatting looks nice and is build on the already existing grammar that Valkyrie uses.

**Comment by mayjak** [comment]
Changed a few things in the original description:
- Changed `=` to `==` to match the original test on VarManager.
- Replaced `Visibility` with `FailAction`, and the values from `disabled` to `disable` and `hidden` to `hide`
