### ISSUE TITLE
Fix Random.Range calls that assume maximum cannot be returned

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#818]
### Description of Problem or Question
In a number of places Random.Range is used to get an index to an array or list, however there is a small change that this will return a float equal to the maximum, which will return an out of bounds error.

A new IntRange function should be created and all usage that requires an int converted.

### Valkyrie Version
2.0

**Comment by BenRQ** [comment]
Hi @redwolf2 , does this issue makes sense to you ?

**Comment by redwolf2** [comment]
Most random method in frameworks return a value that is 0 or somewhere between 1. Like 0.8399493 but not 1, never 1 but that might cause some problems. There is the slight chance that unitys Random.Range function will return max value, which would lead to problems there.
We should replace:
https://docs.unity3d.com/ScriptReference/Random.Range.html
with
https://docs.unity3d.com/ScriptReference/RangeInt.html
in those situations.

But chances for this problem to arise are probably astonomical. That is not dead which can eternal lie. And with strange aeons even floats may overflow,

**Comment by BenRQ** [comment]
Thanks for the explanation, it makes sense now.
I see in the doc that the float function is inclusive but the int function is exclusive.

Good news is : we are already using int function for every random calls, as we always have an int as input.

![image](https://user-images.githubusercontent.com/40794717/46556090-dc117e00-c8e5-11e8-84f7-65181604b4ec.png)

![image](https://user-images.githubusercontent.com/40794717/46556111-f186a800-c8e5-11e8-99cd-fa27d88a4e58.png)

So I think we can close this ticket.

**Comment by redwolf2** [comment]
Haha, just found that overload, too.

**Comment by BenRQ** [comment]
Nice HP citation by the way :)
