### ISSUE TITLE
Problem when using UI elements in consecutive quests

### ISSUE THREAD

**Issue by DelphiDie** [NPBruce/valkyrie#820]
### Description of Problem or Question
We recently noticed a strange behavior of Valykrie when using UI elements in 2 consecutive quests. 

If UI Elements are used in 1 quest and an event calls a second quest.ini that also contains UI elements in it's quest, the second quest will not work.

If the second quest does not contain UI elements everything works fine, and the following quest can contain UI elements again.

I attached a demo to illustrate the problem.
Instructions: Start campaign, skip quest, visit city, leave city, start quest.

Here is a choice to start a quest with UI elements and another to start the same quest without UI elements.

After starting the quest KO 1 hero until the quest fails. The quest without UI elements leads back to the campaign phase, the one with UI elements will be stuck at the end.

### Valkyrie Version
2.0.1

### Attach Save, Quest or Scenario
[Demo.zip](https://github.com/NPBruce/valkyrie/files/1970124/Demo.zip)

**Comment by NPBruce** [comment]
I will investigate.

**Comment by BenRQ** [comment]
Fixed!
It will be available in next official release.

Thanks for the detailed explanation and example, it helped me a lot.

**Comment by DelphiDie** [comment]
Thank you very much for fixing this @BenRQ
