### ISSUE TITLE
Spawn Instruction exclusions not working

### ISSUE THREAD

**Issue by DelphiDie** [NPBruce/valkyrie#821]
### Description of Problem or Question
I recently noticed, that declaring one or more monster types in a spawn event doesn't prevent this type of monster from being spawned, when also using the traitpool option. 

Example:

[SpawnSetupOpenGroup1]
monster=MonsterShadowDragon MonsterCryptDragon MonsterIceWyrm
traitpool=dark cursed cave building

Using this spawn instruction I had multiple instances of ShadowDragons, Ice Wyrms and CryptDragons being spawned.

### Valkyrie Version
2.0.1

**Comment by BenRQ** [comment]
I would need more explanations to help on this, as I'm not an expert of the editor.

With your example, and from I can read in the wiki, I don't see anything that would forbid the app from spawning duplicate.
See here monster and traitpool : https://github.com/NPBruce/valkyrie/wiki/QuestIniSpawn

So this issue is not a bug, but more of a feature request ?

**Comment by BenRQ** [comment]
@scrubbless you are an expert with the editor so your feedback is welcome here :)

**Comment by BenRQ** [comment]
Just to be clear, in Descent, you should be able to generate a group of monsters even if it already exists.
I'm just starting in Descent as I have done 2 games so far, but I had a quest where it happened (spider spawning again).

You need an appropriate text to do it, but some scenario are doing it.

Or do you mean that you had multiple instances of groups on the right side of the screen?
This is not possible of course, I agree.

A demo scenario, or a screen capture would be nice to better understand the issue.

**Comment by BenRQ** [comment]
We have now understood that monsterlist with traitpool should be excluded.
I will investigate in a few days with the demo quest that @redwolf2 has done for this.

[Uploading EditorQuest1.zip…]()

**Comment by DelphiDie** [comment]
Sorry I didn't make this clearer. If you need any additional information I'm happy to provide a demo quest.

**Comment by BenRQ** [comment]
Hi @DelphiDie ,
I was not able to reproduce the problem in more than 50 monsters spawns.
Can you please provide a test scenario and try it in valkyrie beta 2.0.2 ?

**Comment by DelphiDie** [comment]
Hello @BenRQ ,

I modified a quest where I had the issues.

Instructions:
- For best results deactivate all Descent expansions (to reduce the amount of possible monster groups)
- Start the quest
- The first monster group is a randomly chosen dragon group, but since only the base game is available these will be shadow dragons.
- The following 4 spawns use the traits dark and cave, which would allow 5 monster groups: Goblin Archers, Ettins, Cave Spiders, Barghests and Shadow Dragons. Note that Shadow Dragons should not be chosen under any circumstances, since they are defined as monster in the spawn instruction. This is due to the use of the option monster in combination with the option traitpool. Example:

```
[SpawnSetupOpenGroup1]
xposition=-9
yposition=1
buttons=1
event1=SpawnSetupOpenGroup2
audio=AudioButton1
**monster=MonsterShadowDragon**
traitpool=dark cave
```

- You will notice that the 4 spawns can include shadow dragons as well as duplicates previously spawned random groups. Both should not happen.
- It might be necessary to restart the quest a few times, due to the random selection of the spawns.

[SpawnDemo.zip](https://github.com/NPBruce/valkyrie/files/2455434/SpawnDemo.zip)

**Comment by DelphiDie** [comment]
I created a second version of the quest which was intended to be a bit more convenient by allowing to restart the setup process ingame. There I noticed, that the randomizer always chooses the same random monster if the same spawn instruction is called at a later time.

This in itself at least allows to reinforce the same random monster at a later point, but it unfortunately breaks down once you need to spawn the same group from a different location, as this requires another spawn instruction with different coordinates. Nonetheless this is nice to know.

[SpawnDemo_v2.zip](https://github.com/NPBruce/valkyrie/files/2455580/SpawnDemo_v2.zip)

**Comment by DelphiDie** [comment]
I was able to reset the randomizer by recalling the quest.ini instead of just manually restarting the running quest. With this version you will be able to test the behavior in an easy way. 

[SpawnDemo_v3.zip](https://github.com/NPBruce/valkyrie/files/2455614/SpawnDemo_v3.zip)

**Comment by BenRQ** [comment]
Thanks to the demo you provided, I've spotted the issue.

When you exclude a monster, you only exclude the base type.
So if you want to be sure to exclude all the monster of this base type, you also need to exclude the custom Monster of this same type.

In your example, you need to replace : 
monster=MonsterShadowDragon
by :  
monster=CustomMonsterShadowDragons MonsterShadowDragon

There is still the issue with the monsters being spawned if they already exist.
I can easily check that and exclude the existing monsters, but how would you manage reinforcements in that case ?

**Comment by BenRQ** [comment]
In current implementation, the list of selected monster is created at scenario creation.
If during the game you spawn a base or customer monster of type "zombie" for example, the selection won't change.
So you could very well have zombies "selected" and trying to spawn in your random selection.
This needs to change I think if you confirm we don't want to spawn the same monster twice.

**Comment by DelphiDie** [comment]
Hello BenRQ,

thanks for taking the time to analyze this, this explains a lot.

To answer your questions: We definitively do not want to have the same monster spawning twice.

If you imagine the monster pool from which random spawns are selected as a cup and each monster group as a token with a number (let's say 1 to 9 to simulate the base game monster groups). If you manually use monster number 3 in your quest, this token has to be removed from the cup for the whole quest. Also, if I understand you correctly, creating a custom monster currently adds another token into the cup (for example 3Custom). This should never happen, as it will mess up the whole system even more. In this example monster traits could function in a way to select a sub group of the available groups in the cup. For example a spawn with the trait uneven would only be able to select 1, 3, 5, 7 or 9.

Managing reinforcements is one of the things I think we need a new parameter for. When spawning a random group I think we should be able to assign a name to them, let's say red. In my above example, once monster number 3 has been spawned, I'd assign the parameter red for later reference. With this reference I should be able to do things like spawn reinforcements (which could be needed at different locations than the initial spawn), activate triggers (like defeated) and custom monster activations (for instance if the red group would have to follow a certain goal).

I hope my example isn't too abstract, but it was easisert analogy I could come up with without knowing the code.

Regards,
Delphi

**Comment by BenRQ** [comment]
I think it's clear, thanks Delphi.
It will require a major change, as random monster should be generated during gameplay, and not at quest startup like it is today.

I will postpone this to 2.2.

For 2.1, I have done a temporary fix, so you don't get the same monster twice  in the list of spawn monsters.

**Comment by DelphiDie** [comment]
Thanks a lot, this sounds promissing :)

**Comment by DelphiDie** [comment]
Just to inform you:

I tested spawning a bit with Valkyrie 2.1.0 and the new system works a lot better :)

But when I added all expansions again, I sometimes got duplicate spawns with MoM2 markers. This shouldn't happen, but I guess it might be due to your temporary fix?

Screenshot:
![spawns](https://user-images.githubusercontent.com/26790002/46902962-7ff2bf00-cece-11e8-830e-dd4b431c4976.jpg)

**Comment by DelphiDie** [comment]
Thanks for your explanation, I think I was able to grasp the issue.

**Comment by BenRQ** [comment]
I have done a potential fix, but it needs to be heavily tested
