### ISSUE TITLE
Feature Request: Adding conditions to Monster activations

### ISSUE THREAD

**Issue by DelphiDie** [NPBruce/valkyrie#822]
### Description of Problem or Question
Would it be possible to add the condition option to custom monster activations?

Example:

[CustomMonsterShadowDragons]
base=MonsterShadowDragon
activation=CustomDragonActivation1 CustomDragonActivation2

[CustomDragonActivation1]
conditions=EventXHasHappened,==,0

[CustomDragonActivation2]
conditions=EventXHasHappened,==,1

**Comment by BenRQ** [comment]
So after some investigation, I think the best way to do it is to have the condition you want in an event, and this event will then add a component "Monster" if test is valid.

Current version of the editor does not allow to do that: you can add any component except monsters.
(As a side note you can actually remove anything, including monsters.)

I'm not sure I understand why this limitation is here, but it was done on purpose.

My proposal for a fix would be to authorize monster in the "addComponent" of an event.

@DelphiDie would that suit your need ?

**Comment by DelphiDie** [comment]
Hello @BenRQ 
Thanks for your effort. Unfortunately I think this is not exactly what we need, since the idea is to change the activations of already existing monsters. I'll try to describe it a bit more thoroughly:

Descent Monster activations currently work in the following way:

When a player finished his turn, one of the unactivated monster groups (randomly chosen) gets activated. The monster then picks one of the (already included) possible monster activation instructions, and well activates.

Now there is also the possibility to create custom monsters, which can also be assigned custom monster activation instructions. What we need is a way to influence the process, that picks these activations.

An example: I will spawn a group of Shadow Dragons, but since I want them to do certain things in my quest, I will assign them custom activations. In the first part of the adventure this monster might need to open a certain door, but can only do so after it picked up a key. Then it has to flee the map through the exit. Currently this is very cumbersome, since the activation would have to look like this:

[CustomActivation]
Action: If possible, engage the exit.
Action: If possible open an adjacent closed door.
Action: If carrying the key engage the closest door.
Action: If possible pick up the key token.
Action: Engage the Key token.

What we would like to use are multiple custom activations, that can become active/inactive by reacting to variables, to add a certain intelligence to monster activations. A way to do this would be [not actually correct monster activation code ]:

[CustomActivation1]
conditions=KeyPickedUp,==,0 DoorOpened,==,0
Action: Engage the Key token.
Action: Pick up the key token.

[CustomActivation2]
conditions=KeyPickedUp,==,1 DoorOpened,==,0
Action: Engage the closest closed door.
Action: Open an adjacent closed door.

[CustomActivation3]
conditions=DoorOpened,==,1
Action: Engage the exit.

I hope this explains it a bit better.

**Comment by BenRQ** [comment]
Thanks Delphi, it makes more sense to me.

In Valkyrie, the tests are part of events, they are only used at some point in the event state machine.
So using them for this is not something obvious, I will need to do quite a lot of investigation.

Not saying I won't do it, but maybe that I won't push this as my first priority :)

**Comment by DelphiDie** [comment]
Thanks @BenRQ 
You are right, this isn't a high priority feature, and I can fully understand if you want to put this on the backlog, until other things have been done. Still, thanks for considering this :)

**Comment by BenRQ** [comment]
Hi @DelphiDie 

I've refactored the code for issue #609, and this makes this issues a lot easier.
And this feature is now implemented.

One thing I don't understand is how you will be able to make sure your activation is used, and not something else.
I mean the activation is selected randomly, so it can always be a standard activation popping instead of your customer, couldn't it ?

I can share a version if you want to test (if think it is necessary to test with my level of understanding on this ....)

**Comment by DelphiDie** [comment]
Hi @BenRQ 
thanks for adding this feature. I'll gladly test this.

Making sure the right activations are called will be done by assigning values to variables and using these to check for the conditions on custom activations.

And since custom monster do not use the standard activations, they will have to use one of the custom ones.

**Comment by BenRQ** [comment]
Hi @DelphiDie, here is a technical version for your tests.
Tell me if this is working as expected.

https://we.tl/t-yZVk5h5l66

**Comment by DelphiDie** [comment]
I tested the conditional activations and they work great :)

If anyone is curios, that's how you use them:

```
[CustomMonsterShadowDragons]
base=MonsterShadowDragon
activation=ShadowDragon1 ShadowDragon2 ShadowDragon3

[ActivationShadowDragon1]
conditions=Activation,==,1

[ActivationShadowDragon2]
conditions=Activation,==,2

[ActivationShadowDragon3]

```
Activation 1 can only appear if the variable Activation is set to 1.
Activation 2 can only appear if the variable Activation is set to 2.
Activation 3 can always appear.
