### ISSUE TITLE
request for scenario testers - polish language

### ISSUE THREAD

**Issue by zcaalock** [NPBruce/valkyrie#825]
sorry if this is now the right place. Looking for testers for my scenario. For now scenario is in polish language.

Szukam testerów do mojego scenariusza. Proszę o kontakt na maila zcaalock@gmail.com

**Comment by BenRQ** [comment]
Hi @zcaalock, did you find any testers ?
You can also do a first translation in english and ask for help from a native speaker.
You may find more testers that way.

Please tell me if we can close this issue depending on what you prefer.

**Comment by zcaalock** [comment]
you can close this
