### ISSUE TITLE
BUG: Event repeated twice when using Trigger: StartRound - D2E

### ISSUE THREAD

**Issue by Maverick4jc** [NPBruce/valkyrie#826]
### Description of Problem or Question
When encounter 1 is failed it triggers variable %FailedEncounter1 == 1. When encounter 2 starts, EventReinforcements triggers twice. This only happens when the variable %FailedEncounter1 == 1 is involved and the event is triggered by StartRound.  This also only happens on the first round and not on any subsequent rounds.  I have tried many other variations of the event and it is definitely the combination of the variable and the Trigger: StartRound. 

### Valkyrie Version
2.0

### Attach Save, Quest or Scenario
Quest:  
[08_TMH.zip](https://github.com/NPBruce/valkyrie/files/1998123/08_TMH.zip)

**Comment by BenRQ** [comment]
Thank you for the demo quest, I was able to fix the issue thanks to that.

The roundCountroller was not resetted after starting a new quest.

**Comment by BenRQ** [comment]
Fix will be available in next release 2.1, planned in the next few days.
