### ISSUE TITLE
accented letters not showing properly

### ISSUE THREAD

**Issue by Stregabbo** [NPBruce/valkyrie#829]
Made an italian translation for a quest in the shadow rune project, everything works fine except the accented letters. While playing all the accented letters are replaced by a question mark.

Valkyrie Version: 2.0.1

**Comment by redwolf2** [comment]
Which accented letters did you try? Letters like: âûôäöüéÈ?

**Comment by redwolf2** [comment]
What platform do you use. I tested on Android and accented letter were just fine for both Mom and Descent. 
My guess is, that this problem relates to the text encoding. You need to use a more advanced text editor like [Notepad++](https://notepad-plus-plus.org/download) and save your text as UTF-8 (without BOM; BOM = Byte Order Mask).

**Comment by Stregabbo** [comment]
I use a windows Vista pc.
In the next couple of days I'll try to convert my files. I'll let you know as soon as I can if anything changes!
Thanks.

**Comment by Stregabbo** [comment]
Just converted my files and everything works fine, no more question marks.
Thanks a lot!

**Comment by redwolf2** [comment]
Glad to help you
