### ISSUE TITLE
Triggering Mythos for outdoor tile investigators only

### ISSUE THREAD

**Issue by cowistree** [NPBruce/valkyrie#831]
Not sure if this is the right place to ask
How do i make mythos only effect investigators on outside tiles
I set MythosOutdoors==1 but my mythos events are still generalized

Do i have to manually say this will only affect investigators outside?

I feel like ive tried everything

Cheers

**Comment by scrubbless** [comment]
Imagine mythos events as a category of similar events, a bucket of events that can be randomly selected from if set to active (=1). 

Each category can be turned on and off using the "Assign" function and setting them to =1.

Mythos events are binary, 
0 = off
1 = on

When a mythos group is turned on, it gets added to the pool of available events and one is randomly selected at the end of each turn.

If no mythos events are set to 1, you get no mythos events at the end of your turn, as there are no events to randomly selected from active.

So if you want to guarentee an outdoor event to run, then you need to set all other mythos events to off (assign = 0) and then turn the $MythosOutdoors on (= 1).

Example:

$MythosMinor =1
$MythosOutdoors = 1
$MythosLibrary = 1

Each mythos phase the app randomly picks a category from the 3 above, then randomly picks an event to run. 

Next mythos turn we open the kitchen and want to force a kitchen event. So as part of the "Open kitchen" event we can assign all of the above events to off (0) and turn on the kitchen mythos:

$MythosMinor =0
$MythosOutdoors = 0
$MythosLibrary = 0
$MythisKitchen = 1

The next myhow event will be one for the kitchen (randomly selected from that catagroy).

The tricky part is to capture the mythos events current state and set them back to what they were. There are ways to do this (i.e write the status of a mythos event to a quest variable before setting it to 0, then use that variable to write back the status to the mythos variable when you want to set them back).

**Comment by cowistree** [comment]
I have read through this and have a much clearer understanding now. The bucket analogy was helpful.

I have tried just enabling $MythosOutdoors = 1 
I checked the log and everything else is set to 0 except mythos outdoors
When i end the investigator step no Mythos step activates?
I have attached a screenshot below of what I have done

![image](https://user-images.githubusercontent.com/39614516/40533595-60e59bae-6057-11e8-99bf-61b041be5d29.png)

**Comment by scrubbless** [comment]
Thats odd, if you make that only set $MythosMinor = 1, what happens when you end the turn?

**Comment by LordPyrex** [comment]
You still have to have a danger level active, and unfortunately that means that you still have the potential of drawing one of the random general events. When using a location based Mythos you're still required to have one of the 5 basic groups activated so that it knows which difficult to use. [Mythos Tutorial](https://github.com/NPBruce/valkyrie/wiki/TutorialMythosEvents) covers how some of this works. @scrubbless is right about how to get them to run as a custom mythos event that activate at the end of a round. I think this might be the only way to get a guaranteed Outdoor to happen when you want it to.

**Comment by cowistree** [comment]
@scrubbless When I set it to MythosMinor = 1 then a mythos minor event happens. 

@LordPyrex  I will have to try a custom event and see if this can force an outdoor only event. Having both MythosMinor =1 and MythosOutdoor =1  gives me a chance to have either event and I'm really trying to force an outdoor only

Thank you for your help guys :-)

**Comment by scrubbless** [comment]
Have you considered writing your own mythos event? Even if you copy the text, you can then set the parameters exactly as you wish

**Comment by redwolf2** [comment]
As @scrubbless suggested, this approach also allows more thematic mythos events. The default ones are very uspecific and lore unfriendly IMO.
