### ISSUE TITLE
Request: Filter when downloading scenarios

### ISSUE THREAD

**Issue by Shockolino** [NPBruce/valkyrie#832]
I think it would be nice to have filters that allow us to select language, author or other things.

And maybe add a feature that allows us to rate the scenarios.

**Comment by scrubbless** [comment]
There is a request in #111 regarding a better quest distribution and ratings system. I think this would also allow for better sorting and filtering functions.

**Comment by BenRQ** [comment]
This feature is now fully implemented and merged in 2.2. Test version coming soon.
Please open a new ticket if you find an issue in the test version provided.
