### ISSUE TITLE
MoM Sanctum of Twilight : Floating Tiles

### ISSUE THREAD

**Issue by ChesterBlackMoM** [NPBruce/valkyrie#833]
For Mansions of Madness, the floats tiles are supposed to overlap street tiles without covering spaces of the board entirely, but it is impossible to do in Valkyrie due to the grid in which the tiles snap.

Is there a way to do it, or is it a feature that is yet to be added in Valkyrie?

I couldn't find an other post related to that issue.

Valkyrie 2.0.1

**Comment by redwolf2** [comment]
Don't use the grid, use free positioning. Look to the "Position" button.

**Comment by ChesterBlackMoM** [comment]
I cannot find any free positioning button for tiles, unlike tokens.

![untitled-1](https://user-images.githubusercontent.com/39702214/40618705-5643a4d8-6260-11e8-9058-84596bed2c25.jpg)

**Comment by NPBruce** [comment]
I can add a free place button to tiles. To do this without the editor you can open the .ini file and directly edit the X and Y positions.

**Comment by redwolf2** [comment]
I added it in https://github.com/NPBruce/valkyrie/pull/835

**Comment by redwolf2** [comment]
Pull request for development branch https://github.com/NPBruce/valkyrie/pull/837

**Comment by NPBruce** [comment]
Thanks @redwolf2 .
