### ISSUE TITLE
Horror Test Bug

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#841]
### Description of Problem or Question
I have a custom monster, with a custom horror check.

If you chose the custom monster to perform your horror check, when the event resolves and you click "continue" it ends the Horror Phase. This means that no other investigators can take Horror Checks (for example, if they are out of range of the custom monster or closer to something of higher threat).

I've attached an example scenario that walks you through the problem. Notice after the horror check the phase goes from Horror phase to Investigator phase automatically.

### Valkyrie Version
2.0.1

### Attach Save, Quest or Scenario
[HorrorBugExample.zip](https://github.com/NPBruce/valkyrie/files/2088149/HorrorBugExample.zip)

**Comment by scrubbless** [comment]
Hi @NPBruce , 

I have noticed something else with this, the custom Horror activation's on Custom Monsters also skip "EndRound" trigger events.

**Comment by scrubbless** [comment]
Another oddity that seems to be linked to this. If you have an item with an inspection event. Should you use that during the horror phase, it will end the phase also.

**Comment by BenRQ** [comment]
Fixed!

I have also authorized interaction with items while in horror phase.
Otherwise, items would be displayed but you would not be able to click any UI button.

Only tokens can't be accessed while in horror phase.

This is the default behaviour in the official app.
