### ISSUE TITLE
New scenario

### ISSUE THREAD

**Issue by Agerno** [NPBruce/valkyrie#844]
New Scenario: "Las mujeres desaparecidas", for now only available in Spanish. It would be nice to have this scenario available for many people to play it, so I also request someone to translate it to English or other languages.
Valkyrie Version 2.0.1.    
**Scenario:**  
[LasMujeresDesaparecidas.zip](https://github.com/NPBruce/valkyrie/files/2113207/LasMujeresDesaparecidas.zip)

**Comment by NPBruce** [comment]
Hi @Agerno , thanks for your work. Can you please follow the instructions here to get your scenario added:

https://github.com/NPBruce/valkyrie/wiki/QuestPublish

Let me know if you ahve any questions.

**Comment by Agerno** [comment]
So I must make another issue just requesting my scenario to be added. And I must put a link to my repository including the package, like this https://github.com/Agerno/Valkirye-Las-mujeres-desaparecidas
and it's done, isn't it? 

Or are there any problems with the package that I must fix?

**Comment by NPBruce** [comment]
You can use this request, but the Valkyrie package be uploaded directly so it can be read in the application.

Please do not zip before adding to your repository. Note that it is already compressed, it does not need to be zipped again.

**Comment by NPBruce** [comment]
As an asside, this is a frequent problem, I am open to suggestions on how to improve the instructions.

**Comment by Agerno** [comment]
Ok, here it is the link to the package (not a Zip)
https://github.com/Agerno/Valkirye-Las-mujeres-desaparecidas/tree/master/LasMujeresDesaparecidas

**Comment by Agerno** [comment]
Suggestions:
-Specify in the instructions that the package must not be a zip. I thought it must, since I tried to upload it in these issues and it didn't allow me, unless it was in some formats like a .zip or a docx, etc.

**Comment by NPBruce** [comment]
Added.
