### ISSUE TITLE
Valkyrie hangs at "EndRound"

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#846]
### Description of Problem or Question
My scenario has a lot of components and overlapping events.
It also makes quite extensive use of end/start rounds and Mythos triggers.

When play testing ending the round can be very slow, sometimes it can take up to 5 seconds to load and start the next phase. 

While this isn't a problem when there are no monsters on the board, as the freeze happens after the Mythos event. However when you end the Horror step when monsters are present and it hangs, it's easy to think you have miss clicked the end turn and when Valkyrie catches up it will then remember your second press and end the next investor phase.

I suspect that it's due to the number of events using the 'End Round's trigger.
I've tried to name all of these events as A_EndR_*.

My other scenario Stress and Strain does it to a smaller extent, as it has fewer end round events.

### Valkyrie Version
2.01

### Attach Save, Quest or Scenario
https://github.com/scrubbless/ScenariosInProgress

Scenario is called 'A Strain on Reality'

**Comment by LordPyrex** [comment]
Sounds more like a strain on Valkyrie! Is it possible to nest some of your events? Or is it possible that they could all take place at the end of the round? I guess what I'm imagining is something like an index pointer that runs at the end of the round and can have branches out after doing some test checks. Then if it runs an event, that event can change the variable and feed it back to the tree making an in-cursive loop to run multiple events.

**Comment by scrubbless** [comment]
Haha yeah I have been flogging poor Valkyrie with this one.

I did think of that, I use incursive loops alot throughout the scenario. Some of the EndRound events are loops within themselves. I'll have a think of the best way to do it, but I think you're right.

Cheers for the assist.

**Comment by scrubbless** [comment]
I've consolidated those events into one end round event, but it hasn't really helped.

I suspect there is a rogue EndRound event that I've kiss labelled and forgotten about. Is there an easy way to find events with EndRound in the ini files? I assume it'll be in events.ini, would it be as simple as searching for "EndRound"?

**Comment by scrubbless** [comment]
Ok I am officially at a loss. I completely disabled my massive EndRound event, thinking it might be that. But no luck.

I turned off all of my StartRound, EndRound and Mythos triggered events, searched the .ini for all "Triggers" and all that are there are "Eliminated" and some "DefeatXXX".

Now when I End Turn, the normal Mythos Event pops up and then it takes 5-10 seconds to proceed to the Investigator phase.

Is my scenario just too big? 
I think its ~67mb at present with all the music sound and image files. 
The localisation file is nearly 5000 lines and the events.ini is 13600 lines of code.

Any help on this would be greatly appriciated. I am Stumped.

**Comment by NPBruce** [comment]
Not likely to be based on file size. More likely to do with the number of elements that are displayed (tiles, tokens, UI). Hopefully some of the speed improvements will fix this. Sorry I haven't had much time lately, I will investigate when I can.

**Comment by scrubbless** [comment]
No need to apologise @NPbruce.

**Comment by BenRQ** [comment]
To be tested with the changes I did on #842.
Automatic savegames do not save the full archive, so if it was the issue, it should be MUCH faster.

**Comment by scrubbless** [comment]
It's rapid! Well done
