### ISSUE TITLE
Razon - English Translation

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#848]
Hello, I am attempting to translate "RAZON!!" into English.

Does anyone know who the author so, I can reach out and give them the Localisation file when it is complete?

**Comment by NPBruce** [comment]
https://github.com/EtiCarasoft

**Comment by scrubbless** [comment]
Hey Bruce, thanks for that. Is the quest data in your report? If so how do I go about forking it and adding the file?

@EtiCarasoft just wanted to tag you in on this. I will attach a localisation.english file once I have completed the translation.

**Comment by EtiCarasoft** [comment]
Perfect, thanks a lot for your work !!!

**Comment by EtiCarasoft** [comment]
The original tittle is:  At 22.30 at the birds shop.

**Comment by NPBruce** [comment]
This scenario was originally added before I had support for user controlled packages. I'd prefer not to update the existing one, other than to change it to the new system:
https://github.com/NPBruce/valkyrie/wiki/QuestPublish

**Comment by scrubbless** [comment]
I do not speak Spanish,and I am translating using google translate and then cleaning it up. There a few bits that will probably not translate well, i'll do my best and ask here if I am not sure on something.

**Comment by scrubbless** [comment]
Hi @EtiCarasoft ,

I am having trouble translating this line:

> El niño te abraza con fuerza y te susurra al oído: 
> Yo soy tu y tu eres yo, ahora lo verás.
> 
> Te ves a ti mismo tumbado, pareces dormido y debería haber alguien llorando a tu lado, pero estas solo, en medio de la nada, todo es oscuridad y te falta el aire. Te diriges hacia un punto de luz que no quieres alcanzar y ves la cara de ese hombre, con los ojos rasgados, te agarra la cabeza con sus enormes y frías manos para arrastrarte hacia la luz. Te señala la cortina roja y una bandada de pájaros de colores la atraviesa dirigiéndose directo hacia ti. 
> Cierras los ojos y oyes la voz de un niño pequeño: 
> -Bienvenido a casa, Pajarito. 
> 
> Ganas el hechizo <b>Alimentar la mente</b>. 
> El investigador descarta todas sus cartas de Horror boca abajo y coge una carta de Locura, pasa a estar <b>LOCO</b>.
> Si el investigador ya estaba loco, este es retirado de la partida y los investigadores disponen de un turno adicional para completar la investigación.




Here is my first attempt, but I am not sure I have the context correct.

> The child hugs you tightly and whispers in your ear: <i>
> I am you and you are me, now you will see it </i>.
> 
> You see yourself lying down, you appear to be asleep and where you would expect someone to be crying at your side, you realise that you are alone, in the middle of nowhere. Everything is dark and you don't seem to be breathing. You go towards a pinprick of light, though youfeel a great sense of forboding as you approach. You see the face of a man with scared and torn eyes, he grabs your head with giant, cold hands and drags you towards the light. It shows you a red curtain and a flock of colorful birds bursts into flight coming straight towards you.
> You close your eyes and hear the voice of a small child:
> - <i> Welcome home, Pajarito .- </i>.
> 
> You gain the spell <b> Feeding the mind </b>.
> The Investigator discards all his facedown Horror cards and becomes <b> Insane </b>.
> If the Investigator was already insane, he is defeated and the Investigators have one additional turn to complete the investigation.
> 

Is Pajarito a name?

**Comment by EtiCarasoft** [comment]
I see it pretty cool! 

Pajarito is little bird

**Comment by scrubbless** [comment]
I tried to add a bit of poetic licence I hope you don't mind:

The line translated to:
I am you and you are me, now you will see it.

I made it:
I am you and you are me, now you will see what we both can see.

I felt the creepy child would work well with a creepy poem! Haha.

When it's done I'd appreciate if you would read it over to make sure I've got the correct context for events. Google translate is amazing and I'm translating event my event as they would unfolds in game to learn the story, but in some instances it's quite hard to maintain your writing style (which I can tell it's very elequent) through the rough Google translation!

**Comment by BenRQ** [comment]
@scrubbless don't know if you have seen it, but I just realized there are some pending changes here for this scenario : https://github.com/NPBruce/valkyrie-questdata/pull/34/files

And BTW, I'd like to have a look at your translations too, if you don't mind.
It could help me improve my version in French and I may have some comments as I may have a different understanding on some part.

**Comment by BenRQ** [comment]
A quick suggestion for your translation:
"you appear to be asleep and where you would expect someone to be crying at your side, you realise that you are alone, in the middle of nowhere."
I would suggest:
"you appear to be asleep and you think you hear someone crying by your side, but you are alone, in the middle of nowhere."

I'm not fluent in english but I know the first version did not sound so good in French, so I used something similar to this.

**Comment by scrubbless** [comment]
Thanks for the tip, I agree with you there. I'm not sure if it was intentional orif it has just translated strange.

The dialogue appears to suggest that in your 'consciousness' mind you expect to be next to the child, but whatever phychosis you are experiencing now depicts you alone.

**Comment by scrubbless** [comment]
> @scrubbless don't know if you have seen it, but I just realized there are some pending changes for this scenario : > https://github.com/NPBruce/valkyrie-questdata/pull/34/files

  And BTW, I'd like to have a look at your translations too when you are done, if you don't mind.
It could help me improve my version in French and I may have some comments as I may have a different understanding on some parts.

Absolutely, I'd appreciate that!

**Comment by scrubbless** [comment]
Sorry for the delay, I would usually make quicker progress. However I am trying to push my latest scenario to a near final polish before my last major play test. 

Assuming that goes well I'll probably be releasing it and will have more time to work on this translation.

I also plan to take another parse on the tutorial once this translation is done, as I have some really cool techniques s I'd like to share. You'll see them in "A Strain on Reality" once it is released.

**Comment by EtiCarasoft** [comment]
Have anyone of your test been succesful on getting trhow the scenario? I mean winning? @scrubbless, @BenRQ ? This weekend my partner and I made a few ideas for the second one. We'll be writting the script this august to program it as son as posible. We also think on downgrading the difficulty of the scenario. The events are very narrative, but are not so random so having to repeat it much will make it less interesting. We want to try it this week-weekend, if we adjunt anything we will tell you here which mythos have been modified and the values, not much change but some adjusting.

**Comment by BenRQ** [comment]
Hi @EtiCarasoft

I did not successfully finish it yet, but I'm planning to try it again with some friends this Thursday.
I agree it is very difficult as it is, but I did expect a least one investigator to get 'LOCO' (mad) before the end of the game

Also I'm wondering if the difficulty depends a lot on the number of players.
I tried it with 2 investigators, and will try it with 4 next time.
I guess this will make this scenario easier.

Regarding replaying it, it can be improve for sure, but I like the fact that every choice really has two viable option. So you can replay it and still find some new things to try.
Maybe only once it is a bit to extreme as 'all other investigator are dead'.
It could be changed to 'all investigator get X horrors', as it would made everyone mad, but the game would not be ended by one bad decision.

As you are having a look at the scenario, here some minor points I have spotted:

TokenFantasmaNaranja1.button3, 
{action} Rezar (Pray) 
This action does nothing, it makes sense but feels a bit strange.
Maybe a small text 'nothing happens' would be good

EventMythosCocina.text,
 cuchil 'calvado' or 'clavado'
Probably a mistype here

EventMythosSoft03.text, 
Should the object be lose randomly or can the investigator choose ?

EventMythosSoft08.text, 
Are you sure this is the right tile name ?
From what I've seen, it should be "la Esquina de calle 1" instead of "Parcela"

TokenPuertaAzulLuzON.text,
 There are no option to open the door, and no text to explain why.
Maybe just saying it is closed is enough.

EventMythosHABOUT02.text,
  You take a punch in the head, but get horror and no damage.


And by the way, I'm looking forward to test your next scenario 👍 👍

**Comment by EtiCarasoft** [comment]
It does a hide action i'll look to make it appear as nothing happens makes sense. 

... Cocina is a mistype i've fixed it. Changed.

Soft03 should be random I add it in spanish. Changed

I don't know why it changed the tile it should be SideYard2. Changed.

HABOUT Should Be Damage instead of Horror. Changed.

EventRezaryLlorar = "Parece que no sucede nada, però te sientes aliviado." - 

Translation "It seems that nothing happens, but you feel relieved."

[Localization.Spanish.txt](https://github.com/NPBruce/valkyrie/files/2202034/Localization.Spanish.txt)

This is the file uploaded and quite balanced it's still hard but not so.

Events Changed:
- EventMythosHard03A
- EventMythosHard03B
- EventMythosHard01
- EventMythosSotano01
- EventMythosFlavor04
- EventMythosSoft01
- EventMythosSoft03
- EventMythosSoft04
- EventMythosSoft06T
- EventMythosSoft07
- EventMythosSoft08
- EventMythosSoft09
- EventMythosCocina
- EventMythosHypnosBad
- EventSustoBiblioteca
- EventRes2MarcadorFake4
- EventResMarcadorFake5
- EventPuertaFake2
- EventMostrarPuertaOculta1
- EventAbrirPuertaCampanario

**Comment by EtiCarasoft** [comment]
Maybe only once it is a bit to extreme as 'all other investigator are dead'.
It could be changed to 'all investigator get X horrors', as it would made everyone mad, but the game would not be ended by one bad decision.

This is the previous to last mythos phase this adventure doesn't let you stay in random events, it also makes sense when your taking the last talk. Just don't worry much about this event this decision just makes the game 1-2 turns shorter.

**Comment by BenRQ** [comment]
> This is the previous to last mythos phase this adventure doesn't let you stay in random events, it also makes sense when your taking the last talk. Just don't worry much about this event this decision just makes the game 1-2 turns shorter. Also enables one alternative ending but that's a spoiler XD

OK makes sense then :) :)

**Comment by scrubbless** [comment]
@eticarasoft 

Did you know you can use {c:TileTheTilesNAME} to display the tile, the game will enter the tiles name and icon for you.

E.g

The tiles name is Tile001 is the study.

You'd use {c:Tile001} in the text and it would display (in the correct language) the tiles name.

You can do the same with items:
{c:QItemTheitemsName}

**Comment by BenRQ** [comment]
@EtiCarasoft I'm planning to play it tomorrow evening, so would be interesting to have the latest version.
Can you please share your latest version here so that I could test?
A zip or the package is good enough for me for this test.

And if you agree, I will try to apply the change proposed by Scrubbless regarding tile names, it should look nicer.

**Comment by EtiCarasoft** [comment]
shure no problem @BenRQ . 
@scrubbless That script i didn't know it existed when i created the scenario first time.

[EditorEscenario1.zip](https://github.com/NPBruce/valkyrie/files/2206118/EditorEscenario1.zip) 

This is the lattest version. I'm working on a bug i think i've found with some vars with the blue light door. I've solved one of the problems, but i have to research a little how to solve the other one. Sorry. The colour buttons are the most difficult part for me to program correctly. 

@BenRQ for your test porpouse use the new mythos difficult used in spanish I would make the scenario  much less hopeless. I listed the mythos before, just get the values and the type of damage.

**Comment by scrubbless** [comment]
> @scrubbless That script i didn't know it existed when i created the scenario first time.

There's a good chance that it didn't when you created yours, the earlier versions of Valkyrie didn't have as many features! Ive seen Razon on my list ever since I started using Valkyrie!

**Comment by BenRQ** [comment]
Thanks @EtiCarasoft, I've now integrated your changes on difficulty in the French translation.
I will play with these changes.

**Comment by scrubbless** [comment]
The secrets doors do not snap the same was as doors so have to be manually placed, which is a nightmare!

**Comment by EtiCarasoft** [comment]
**HUGE SPOILER**
There are only 5 mythos Hard it ends after those.

I've fixed the free position of the wall, thanks @scrubbless It's been difficult to align.

_TokenPuertaVerde01.text,Una puerta con la luz verde debajo explicat bé
I can't translate 'explicat bé'. Is it a typo ?_ 
> Sorry it's a mistake from the previous text I will fix it and post here the correct text. (explica't bé) means well explained in Catalan 

_With the last question from the cat, to provide an object, there is an option to "recapitular" ( TokenBastEntrega01.button5). This button does nothing.
What did you mean by 'recapitular' ?_
> Recapitular is the same as cancel, but nicely writing to say you have to think about what to give.

_We went anyway to the last question with the cat, and they were all a bit lost with the question.
They did two bad choices. Is it pure luck or is there is a tip somewhere to know what is the object you should provide?_
> Same problem as token puerta verde, it's a concept problem we have with the second escenario that was discarded. We will add this week some hard way to figure it out from the beggining making players to open fake clue tokens to find the correct item.

The **** doors are the worst part of the scenario, there's no way to make it work properly XD. I have to rework on it to solve all the variable solutions and options.

Thanks @BenRQ for all your work and that extense review we really apreciate it. It's really really difficult to all players to leave the house together even knowing what to do and the correct steps to follow that's why I left the option It's just me who survived, to leave a friend behind 🗡 ...

**Comment by BenRQ** [comment]
>Thanks @BenRQ for all your work and that extense review we really apreciate it. It's really really difficult to all players to leave the house together even knowing what to do and the correct steps to follow that's why I left the option It's just me who survived, to leave a friend behind 🗡 ...

You are welcome @EtiCarasoft.
I like that you have this choice available 👍 

> The **** doors are the worst part of the scenario, there's no way to make it work properly XD. I have to rework on it to solve all the variable solutions and options.

Looks like it works in the editor, and not in the game, doesn't it ?
Maybe we can help you fix this.
(Also an easy way to fix this would be to just open each door after each button is pressed, and never close it again, but that's maybe not what you want).

Also I've seen one small improvement:
The skill symbol for the puzzle in the library [PuzzlePuertaBIBLIO], appears twice. Probably a bug of a previous editor.
Selecting the skill 'influence' again in the editor fix this.

**Comment by EtiCarasoft** [comment]
I think I've solved all the bugs ^^!! The doors solution is not super elegant but i think it works.
We have also come across with an idea to fix the ending and lapsing to the next scenario.

Forget about TokenPuertaVerde01.text this token is deleted. 
My partner is working on 2 new text to improve the scenario. We are thinking on adding a Qitem with interaction and a QUI to explain the idea. I'll posthere the texts also with the file. I want to have it all finished for this week. I'll post also the list of events/tokens/puzzles that will need to be translated. Sorry for the delay and extra work.

Info for @BenRQ & @scrubbless

**Comment by BenRQ** [comment]
@EtiCarasoft very good news  👍 
I'm ready to translate !  :)

**Comment by EtiCarasoft** [comment]
It's been a while, sorry we made a few changes to improve the scenario. We set a $mythosMajor between basement Event and the Greenhouse making the greenhouse the end triggerer.
Fixed Some bug based on this changes and make a new search token which gives a Qitem with precious information to conclude the mision ;).

List of events and text changes:

TokenzzINFO
EventResolucionPuzzleBast
EventDesarrolloPasillo1A
ResObjetoEsquina
TextoPruebaVez01
TextoPruebaVez02
EventInspeccionarNota01
EventInspeccionarNota02

Some buttons atached to this events and one UI element as a button. I think that's all. 

We're drawing the image of the puzzle I hope we can have it finished soon. I'll do a package as soon as It's done. 

I attach the latest text file:

[Localization.Spanish.txt](https://github.com/NPBruce/valkyrie/files/2267478/Localization.Spanish.txt)

**Comment by BenRQ** [comment]
Hi @eticarasoft,
Nice ! We will have a unique drawing for this scenario :)

Do you think you are done with all the other changes you wanted to make?
I will work on the translation when I'm back home in two weeks.

**Comment by EtiCarasoft** [comment]
I think I'm done with the chages with this last one I attach HERE:
[Localization.Spanish.txt](https://github.com/NPBruce/valkyrie/files/2273838/Localization.Spanish.txt)
On Qitem was changed.

We have tested some critical points with no bugs detected ;)

**Comment by scrubbless** [comment]
I've not forgotten about this, I am working on the mythos events and will check I have the latest version before I start error checking.

Works been manic and the small amount of time I've had has been tied up with A Strain on Reality!

**Comment by scrubbless** [comment]
Hi @EtiCarasoft, i've nearly finished the english translation, however I can't work out what the following line is:

-Pensaba que estaría enrollado entro. Esto no es lo que estoy buscando, no me hagas perder el tiempo. 

It translates to:

<i> -I thought it would be coiled in. This is not what I'm looking for, do not waste my time .- </i>

**Comment by scrubbless** [comment]
Ok here is the first draft, I need to play it through a bit to make sure it flows (and to add that translation above)

[Localization.English.txt](https://github.com/NPBruce/valkyrie/files/2387104/Localization.English.txt)

**Comment by EtiCarasoft** [comment]
downloaded it. changed the Quest.ini
We have the black of the illustration missing, my partner is inking it i hope it's done soon. As soon as it's done i'll change the file, do the package and update the adventure.

info also for @BenRQ

**Comment by scrubbless** [comment]
Hi @EtiCarasoft 
Can you help with the translation above my last message. I have done some proof reading and corrected some parts. But I will need that translation to finish it off.

If you have a repo could I pull(?) That and do much changes on your scenario? Will mean I'm working on your latest version.

**Comment by EtiCarasoft** [comment]
The translation is correct, coiled in or coiled inside i found both to be correct i will also correct the spanish one a D letter is missing.

thx @scrubbless

**Comment by scrubbless** [comment]
I thought it (the item the cats after) would be coiled _inside_.. Now I understand!

**Comment by scrubbless** [comment]
Hi @EtiCarasoft 

Here is the latest translated file:
[Localization.English.txt](https://github.com/NPBruce/valkyrie/files/2409240/Localization.English.txt)

**Comment by BenRQ** [comment]
Hello @EtiCarasoft 
would you have some time to copy your scenario with English and French update in your own repo ?

Valkyrie Release 2.1 is coming out very soon, and I was thinking about sharing the info with the French community. As your scenario is a very nice, I wanted to list it in my "commercial for Valkyrie" on forums :)

**Comment by EtiCarasoft** [comment]
Hi I've been quite busy on work, This night i'll pass here the package to uploaded  I think it will be the fastest way to get it to work properly.

**Comment by EtiCarasoft** [comment]
[escenario package.zip](https://github.com/NPBruce/valkyrie/files/2527200/escenario.package.zip)
[Escenario full info.zip](https://github.com/NPBruce/valkyrie/files/2527201/Escenario.full.info.zip)

@BenRQ I upload here the package and the full folder with all the scenario information just in case you need it to solve any problem with it.

Thks for the patience.

**Comment by EtiCarasoft** [comment]
@NPBruce or @BenRQ I don't have the desktop application and the scenario was created before some major changes. How do we can upload all this new files? 
Maybe the best way is to delete the old one and upload it again.

**Comment by BenRQ** [comment]
Hi @EtiCarasoft

thanks for sharing the files.
We can take it from here but if you could just create a repo, and share access with us it would be perfect.
Look here on how to do it: #924 
That way, you can modify your scenario in the future if required.

**Comment by EtiCarasoft** [comment]
I've done a repo with the tutorial:

https://github.com/EtiCarasoft/22.30-Birds-Shop

**Comment by BenRQ** [comment]
Thanks @EtiCarasoft we are almost ready to publish the update of your scenario with translation.

Can you please share the repo access with me and @scrubbless  so we can do a bit of renaming for the directory ? We should not use the name "EditorEscenario" as it can conflict with other scenarios.

Access rights can be shared from the settings, collaborators, add collaborator :

![image](https://user-images.githubusercontent.com/40794717/48098089-ff4c8780-e21b-11e8-938e-422075bb234a.png)

You can also rename it directly of course.

**Comment by scrubbless** [comment]
https://raw.githubusercontent.com/EtiCarasoft/**22.30**-Birds-Shop/master/

This doesn't link in the Valkyrie manifest. I suspect the . is causing issues.

 @EtiCarasoft  or @BenRQ any chance one of you can remove that . ?

**Comment by scrubbless** [comment]
Ok that looks good. Looks like I've missed some translated events, I may have translated an older version. I'll take a look when I get the chance and update the translation.

**Comment by BenRQ** [comment]
I also have a small update on French translation, with this latest version : 
[Localization.French.txt](https://github.com/NPBruce/valkyrie/files/2573982/Localization.French.txt)

@scrubbless, can you take it with your update of translations ?

Also @scrubbless , maybe you should delete the old scenario from the Manifest.ini : [2230hAtTheBirdsPetShop]
external=https://raw.githubusercontent.com/NPBruce/valkyrie-store/master/MoM/2230hAtTheBirdsPetShop/

I have rename the existing ratings to the new scenario name.

**Comment by BenRQ** [comment]
French translation updated.

**Comment by EtiCarasoft** [comment]
can we delete the old scenario some way?

**Comment by BenRQ** [comment]
Old scenario has been removed from the list.
Closing this issue.

**Comment by scrubbless** [comment]
Hi Joan (@EtiCarasoft )
I have fixed a bunch of syntax errors with the {rnd:hero} code that google translate messed up (it added a space making it {rnd: hero} which is next to impossible to see in the editor!

Could you add this to your scenario and republish when you get the chance. There are a lot of complaints in the feedbacks sheet about it.
https://goo.gl/xgxdMb

Sorry for this!

**Comment by scrubbless** [comment]
Hi @EtiCarasoft 

What issue are you having? The scenario is in your repo now, so you just need to commit to it:
https://github.com/EtiCarasoft/22-30-Birds-Shop.


Here is the manifest entry:
> [BirdsShop]
> external=https://raw.githubusercontent.com/EtiCarasoft/22-30-Birds-Shop/master/

I have contribute to your repository so should be able to help.

**Comment by EtiCarasoft** [comment]
I updated the english file but in the app it doesn't appear to update.

**Comment by scrubbless** [comment]
Did you commit the change and push it to your repo?

**Comment by scrubbless** [comment]
![image](https://user-images.githubusercontent.com/32058089/56123795-1e8ad600-5f6d-11e9-85ef-8677b2622f66.png)

**Comment by EtiCarasoft** [comment]
I updated via desktop app:
<img width="960" alt="Captura de pantalla 2019-04-15 a les 11 58 11" src="https://user-images.githubusercontent.com/26690018/56123919-c6a49d00-5f75-11e9-8925-8154e14215d8.png">


https://github.com/EtiCarasoft/22-30-Birds-Shop/tree/master/BirdsShop 
I see here the changes.

I updated .DS_Store also

**Comment by scrubbless** [comment]
Hi @EtiCarasoft 

You need to create your scenario package and upload that.
![image](https://user-images.githubusercontent.com/32058089/56124572-dcfb2a80-5f6e-11e9-85c1-fe5fe6ee4557.png)

The manifest references the .ini file and .valkyrie package file. The folder you have updated is the unpacked scenario that is used in the editor.

**Comment by scrubbless** [comment]
In Valkyrie load the scenario up in the editor, then hit tools and create package. It will create a folder on the desktop, copy those files into your repo in the root and commit the changes.

The update will show in the scenario screen (the round arrow), however if you added Synopsis or author metadata it will not show up on the scenario lists main screen for up to an hour. This is just cosmetic, if anyone downloads the scenario they will be playing your latest version.

**Comment by BenRQ** [comment]
Hi guys, please note that you have to wait one hour before you can see the update in the app.
Refresh of scenario list is done once per hour.

**Comment by EtiCarasoft** [comment]
<img width="987" alt="Captura de pantalla 2019-04-15 a les 12 21 40" src="https://user-images.githubusercontent.com/26690018/56125359-0ae56c80-5f79-11e9-917a-082cdd105829.png">

I updated the scenario adding you english file, created a package updated in the repo. Updated DS. 
now we have to wait 1hour to download it correct?

**Comment by EtiCarasoft** [comment]
I'll check it in an hour. Thx all

**Comment by scrubbless** [comment]
> Hi guys, please note that you have to wait one hour before you can see the update in the app.
> Refresh of scenario list is done once per hour.

The "updated" icon actually shows up right away. Its just the banner that is created that takes an hour from what I've observed.

You can open the scenario, then click the Grey "delete" and redownload it, and will get the new version.

**Comment by BenRQ** [comment]
I've launched the refresh process manually, so you should see it now.

**Comment by scrubbless** [comment]
There is nothing obvious to see if it has updated. I would recommend adding a version number to one of your sections (I put it in author) so that you can checksum updates like this easily.

**Comment by EtiCarasoft** [comment]
How can we add the version in the title? via editin scenario and change title in each .txt?

**Comment by scrubbless** [comment]
You can just edit the scenario in Valkyrie, change the scenario title in the quest section.

![image](https://user-images.githubusercontent.com/32058089/56126329-d969a280-5f72-11e9-9a98-521b3e6fc450.png)

I also put a more granular version in the Authors but thats personal preference.
![image](https://user-images.githubusercontent.com/32058089/56126373-f0a89000-5f72-11e9-9d74-71f550d1ee9d.png)

**Comment by EtiCarasoft** [comment]
Updating files:

<img width="987" alt="Captura de pantalla 2019-04-15 a les 12 21 40" src="https://user-images.githubusercontent.com/26690018/56126531-b1cb0800-5f7b-11e9-98ce-9e81f9b060fa.png">

<img width="960" alt="Captura de pantalla 2019-04-15 a les 11 58 11" src="https://user-images.githubusercontent.com/26690018/56126557-b55e8f00-5f7b-11e9-8d0f-c27ab1d1249f.png">

**Comment by EtiCarasoft** [comment]
@scrubbless We're working on the next scenario and made some improvements on the Birdshop one, better event presentation and gameplay, also some little narrative improvements. Are you interested in updating it in english? Thanks
