### ISSUE TITLE
Is there a way to Copy Events etc?

### ISSUE THREAD

**Issue by UberGooberGames** [NPBruce/valkyrie#849]
Basically I'm looking for a way to repeat events with slight variations, and would like to copy them and make small edits v. retyping them from scratch every time.  Am I missing something very easy and obvious?

**Comment by redwolf2** [comment]
No yet. I'm closing it, because it is a dublicate of https://github.com/NPBruce/valkyrie/issues/522

**Comment by redwolf2** [comment]
Not a big deal. If you are unsure, just open an issue.
