### ISSUE TITLE
New Scenario

### ISSUE THREAD

**Issue by drinkinguranus** [NPBruce/valkyrie#851]
### Description of Problem or Question
https://github.com/drinkinguranus/LostMemories

### Valkyrie Version
https://github.com/drinkinguranus/LostMemories

### Attach Save, Quest or Scenario
Saves:  
%appdata%/Valkyrie/MoM/Save  
%appdata%/Valkyrie/D2E/Save  
Quest:  
%appdata%/Valkyrie/D2E/Editor  
Scenario:  
%appdata%/Valkyrie/MoM/Editor

**Comment by scrubbless** [comment]
Awesome, announce your scenario on the BBG thread, this will allow people to rate the scenarios and give feedback.
https://boardgamegeek.com/thread/1916430/fan-made-scenarios-reviews-valkyrie

I will create a poll for new scenarios when a couple more have been released (I want to avoid individual polls for individual scenarios!).

**Comment by NPBruce** [comment]
Added.
