### ISSUE TITLE
Add and Improve Valkyrie French translations

### ISSUE THREAD

**Issue by BenRQ** [NPBruce/valkyrie#852]
Hello,

I have spotted some missing French translations, mainly related to MoM Packs.

My commit is almost ready, but I can't find the location of the translations for the boxed expansions "streets of Arkham" and "sanctum of twilight".

I looked for text "twilight" in the whole repo, and for MAD26 which seems to be the tag for the Sanctum of Twilight expansion but without any success.

Some guidance on this would be welcome.

### Valkyrie Version
I'm testing with Valkyrie 2.0.1

Fix will soon be available in my fork, I will do a pull request.
I'm new with Github though, but I should be able to do it right :)

**Comment by redwolf2** [comment]
I guess the text of "Sanctum of Twilight"  and "Streets of Arkham" is taken from the texts, imported from the main app (PRODUCT_TITLE_MAD25 for example).

https://github.com/NPBruce/valkyrie/blob/master/unity/Assets/StreamingAssets/content/MoM/soa/content_pack.ini

So there should be no need to translate those.

**Comment by BenRQ** [comment]
Thanks for the feedback !

Maybe the import is not taking into account the language selection then.
I have the MoM official app configured in French, and the title of the expansions are available in French too (at least one is : street of Arkham)
![image](https://user-images.githubusercontent.com/40794717/42284032-91934c38-7fab-11e8-9414-4ae8909bf1f5.png)

But I still have the text in English in Valkyrie, even after a new import.
![image](https://user-images.githubusercontent.com/40794717/42284056-a6cf8d96-7fab-11e8-9330-46b4051b7a22.png)

It's not a big issue, but the titles of the expansions can be really different in French.

**Comment by BenRQ** [comment]
Maybe the issue is only for streets of Arkham.

The other one "Par-delà le seuil" (Beyond the threshold) is properly translated.

And Sanctum of twilight is not yet available in French :'(

I will commit my changes then.

**Comment by BenRQ** [comment]
Commit and pull request is done.

**Comment by redwolf2** [comment]
https://github.com/NPBruce/valkyrie/pull/853

**Comment by redwolf2** [comment]
Pull request was replaced by this here: https://github.com/NPBruce/valkyrie/pull/856

**Comment by BenRQ** [comment]
Pull request #865

**Comment by BenRQ** [comment]
Beta test version is now available with implementation of this issue:
https://github.com/BenRQ/valkyrie/releases/tag/release%2F2.1%2FBrynhildr_2.1.0b

**Comment by redwolf2** [comment]
Reopen, because it is fixed in Brynhildr, but not in Valkyrie. I created the label "Brynhildr" to track, what is covered by it.
