### ISSUE TITLE
At 22.30 at the birds shop : French translation 

### ISSUE THREAD

**Issue by BenRQ** [NPBruce/valkyrie#855]
Hello

I have started the translation of "At 22.30 at the birds shop." in French.

20% is done, I expect the rest to be done in the next days.

@EtiCarasoft I may have a few questions, as I'm not fluent in Spanish.
I will post them here.

@indoy, I saw you did a lot of French translations for other quests.
It would be great if you can have a look at my translation before it is published.
Or even better, if you can try it out :)
Feel free to contact me.

**Comment by BenRQ** [comment]
First of all, I have to say that this scenario is really really good.
Well done @EtiCarasoft !
I tried to keep the dark atmosphere, and the elegance of your writing, I hope I did an OK job :)

It is also quite difficult, which is good as you need to play it more than once to succeed.

So here is my first version of translation.
@Indoy, feel free to try it out
I think there are a lot of things that can still be improved, so do not hesitate to propose some changes.

[Localization.French.txt](https://github.com/NPBruce/valkyrie/files/2182395/Localization.French.txt)

@EtiCarasoft I have two small questions :  

_EventRegresoMythos6.text,_ 
  Where should you take the horror card from ? the discard pile ?

_TokenLibroBiblioteca.text,_ 
  What do you mean by a book 'decently' opened?
   "Un libro decorosamente abierto por la página 3, descansa en una de las butacas."

I have also encountered a few issues in the events, but maybe this is not the right thread to discuss it.
Should I open an issue on your repo, or here ?

And I just realized you have some pending changes here : https://github.com/NPBruce/valkyrie-questdata/pull/34/files
I will update my translations with those.

**Comment by scrubbless** [comment]
@EtiCarasoft
I would suggest that you publish your latest version to a new repo ans have Bruce publish the new location.

This will give you full control to push your own changes and add the localisation files.

**Comment by EtiCarasoft** [comment]
I'm translating the latest guide to spanish and getting myself back to Valkyrie and new sistem i will fix it and reload it let's see if the issues are solved this way. 
@BenRQ we have a problem with one mythos trigger we have to look back on variables to see how to fix it but it's kind of a bug.

EventRegresoMythos6.text
You get the first horror card that remains face up from the horror deck.

TokenLibroBiblioteca.text
Decorosamente means left gently and opened in one page with intention to be. I don't know how to translate it into english

**Comment by BenRQ** [comment]
@EtiCarasoft @Indoy 
My latest version for the translation in French.
[Localization.French.txt](https://github.com/NPBruce/valkyrie/files/2221180/Localization.French.txt)

**Comment by EtiCarasoft** [comment]
I have to do the package I can do it for spanish and french later on for english when @scrubbless is done.
After that i don't know exactly what is the next step if anything changed since last time i uploaded files for the mission.

**Comment by BenRQ** [comment]
Once the package is done, it needs to be uploaded to internet.
Your own Github repository is probably the best place to upload, and to manage the version of your scenario easily.
You should then provide the link to your package, so @scrubbless can add it in the list of scenarios (and remove the old one).
After this, if you have an update, you can just update the package on your github when you want.

You can find more info on the wiki here : https://github.com/NPBruce/valkyrie/wiki/QuestPublish

Github desktop is probably the easiest tool to do this.

**Comment by EtiCarasoft** [comment]
Hi @BenRQ We are working on the next scenario and have made some improves on the Birdsshop, narrative information and better event and game presentation, are you interested in the frecnh translation?

Thanks

**Comment by BenRQ** [comment]
Hi @EtiCarasoft sure I can help :)

**Comment by EtiCarasoft** [comment]
[Localization.French.txt](https://github.com/NPBruce/valkyrie/files/4659470/Localization.French.txt)
[Localization.Spanish.txt](https://github.com/NPBruce/valkyrie/files/4659471/Localization.Spanish.txt)
[Localization.English.txt](https://github.com/NPBruce/valkyrie/files/4659475/Localization.English.txt)

I leave here the updated txt files. 
I will upload in spanish for these weekend to get some feedback in posible errors.
Let's see if I can get help in english

**Comment by scrubbless** [comment]
I can take a look at the English when I get a chance :)

Does it just need a proof read or do you need new event text translated?

**Comment by EtiCarasoft** [comment]
Hi Scrubbles, It need major translation, we have rewritten major part of the events, sorry guys.

**Comment by EtiCarasoft** [comment]
[Localization.English.txt](https://github.com/NPBruce/valkyrie/files/4661620/Localization.English.txt)

we have gone from 545 code lines to 745 ... sorry

**Comment by scrubbless** [comment]
Ok that's fine, will take longer I'd expect as would need to do it on the editor. I'll add it to my punch list and let you know when I start it.
