### ISSUE TITLE
D2e- Individual Hero Exp points

### ISSUE THREAD

**Issue by Bakajao** [NPBruce/valkyrie#857]
### Description of Problem or Question
Hi all!! 

Awesome work Bruce.
I`d like to know if its posible to give individual experience points to certain heroes. I cant see any individual exp var into the pool var.
I remenber seen that in RTL campaing its posible.

Thanks a lot for the answers..

### Valkyrie Version
2.0.1

### Attach Save, Quest or Scenario
Saves:  
%appdata%/Valkyrie/MoM/Save  
%appdata%/Valkyrie/D2E/Save  
Quest:  
%appdata%/Valkyrie/D2E/Editor  
Scenario:  
%appdata%/Valkyrie/MoM/Editor

**Comment by NPBruce** [comment]
Currently no way to do this, feature is being tracked here:

https://github.com/NPBruce/valkyrie/issues/375
