### ISSUE TITLE
Improve placement and look of button bar

### ISSUE THREAD

**Issue by BenRQ** [NPBruce/valkyrie#859]
Hi,

This is a proposal for some small evolutions of the button bar displayed while playing a game.

I have spotted some points that could be easily improved regarding these buttons / texts :  
 - the arrow for 'next phase' is not so pretty '->', and you have to guess the purpose
 - buttons are very small, makes it almost impossible to translate properly
 - no difference between phase description, and a button
 - it takes some room in the middle of the screen where you may want to see the tiles better

My proposals : 
 - replace '->' by a unicode arrow, and place it on the lower right corner
 - make button size dynamic depending on text, and change placements to leave room in the middle of the screen
 - change the text style of 'phase name' and remove borders
 
I have done a first implementation.
Please have a look !
Feel free to suggest some changes, improvements.

![image](https://user-images.githubusercontent.com/40794717/42719149-af7addac-8711-11e8-903a-7cc90ef4d9ad.png)

![image](https://user-images.githubusercontent.com/40794717/42719161-d8e3a96c-8711-11e8-83a9-00cdd5baa5f1.png)

**Comment by BenRQ** [comment]
Hi @NPBruce, do not hesitate to tell me if you are not fine with this kind of design changes.
And I'm trying to test as much as possible but I may miss something.

**Comment by BenRQ** [comment]
I've done one additional change: removing this button bar while we are on the prologue.
It looks quite nice I think.

![image](https://user-images.githubusercontent.com/40794717/42772514-fc12cd4e-892a-11e8-981f-9c5a12e60913.png)

![image](https://user-images.githubusercontent.com/40794717/42772522-013fbae8-892b-11e8-9acc-63e81f70dc32.png)

I wait for the first tile to be displayed to display the status bar.

![image](https://user-images.githubusercontent.com/40794717/42772552-153e36fa-892b-11e8-89e6-29ae77adddc0.png)

**Comment by scrubbless** [comment]
This is quite cool, did you code this in Unity or mock it up with an editing tool?

**Comment by BenRQ** [comment]
I did this in visual studio. Moving buttons is in my level of expertise   :P 

Next ticket I plan to work on may prove to be more difficult :  #430

**Comment by redwolf2** [comment]
I like it. Maybe use an arrow that is not so thick, like ➔ or →

https://unicode-table.com/de/sets/arrows-symbols/

**Comment by BenRQ** [comment]
I agree the arrow can be improved.

And the vertical alignment was not perfect either.
It actually depends on the character displayed.

Here are a few arrows with the different alignement, which one do you prefer : 

![image](https://user-images.githubusercontent.com/40794717/42845958-ca87589c-8a17-11e8-85fb-9cbf04bc2d04.png)

**Comment by BenRQ** [comment]
A few more:
![image](https://user-images.githubusercontent.com/40794717/42846131-59d5bcd2-8a18-11e8-9b53-b545a667897f.png)

I like the two with the shadow, but alignement would be a problem here.

**Comment by scrubbless** [comment]
The only one not effected by alignment issues is:
![image](https://user-images.githubusercontent.com/32058089/42847521-2fe6dedc-8a14-11e8-9bf0-892ddaa2ed30.png)


If you can fix alighnment - then I personally prefer 
![image](https://user-images.githubusercontent.com/32058089/42847532-41749e3c-8a14-11e8-909c-1d0acea7bc76.png)

**Comment by redwolf2** [comment]
That "paper plane arrow", that @scrubbless preferes looks nice. There could be some padding or a margin involved, that fucks up the alignment.

**Comment by BenRQ** [comment]
Pull request #867 
work still ongoing

**Comment by BenRQ** [comment]
OK this is done.
I had to tweak the border and button size a bit, it's dirty, but it works.

![image](https://user-images.githubusercontent.com/40794717/42913309-92c52960-8af4-11e8-91d1-ebb0a16a4757.png)

**Comment by scrubbless** [comment]
Looks clean, I like it

**Comment by BenRQ** [comment]
Thanks @scrubbless, it is all available now in my pull request.

Waiting for code review, comments if there are any :)

**Comment by BenRQ** [comment]
One bug detected following this dev: there is an overlap when too many monsters are present:

![image](https://user-images.githubusercontent.com/40794717/44488454-10dcb500-a659-11e8-90a7-802906ce3d41.png)

Would be nice to improve the arrow  characters here too.

**Comment by BenRQ** [comment]
Beta test version available with implementation of this issue:
https://github.com/BenRQ/valkyrie/releases/tag/release%2F2.1%2FBrynhildr_2.1.0b

**Comment by redwolf2** [comment]
Reopen, because it is fixed in Brynhildr, but not in Valkyrie. I created the label "Brynhildr" to track, what is covered by it.
