### ISSUE TITLE
Discussion about future fix / feature : discord now available !

### ISSUE THREAD

**Issue by BenRQ** [NPBruce/valkyrie#860]
Hi @NPBruce, all,

Do you have a place where we can talk about new features, issues assignement, development questions and ideas to solve issues ( #111 for example)?
I would gladly help on a few topics on this nice project.

I'm thinking about a forum / channel in a place like Reddit or Discord.

It would also be nice for people to exchange tips when creating quests.

**Comment by scrubbless** [comment]
Discord is not a bad shout, I talk to a couple on IM within BGG but a forum for this might be handy.

Though I think a proper quest distribution and social platform is what's being discussed in #111.

I imagine somewhere where you can upload quests and then mods can approve to release them to the Valkyrie lists.

Also a place dedicated to rating and commenting on scenarios.

**Comment by NPBruce** [comment]
I personally am not in a position to engage in any real time communication (IM/audio/video). Happy for others to do so. I'm not against a forum/reddit, but I'm not sure that it will add a lot over the use of issues for discussion (like this one) and will fragment content between here and another place.

Perhaps scenario development specifically is a good case for discussion to live somewhere else.

**Comment by BenRQ** [comment]
A forum/reddit would be good for sure for players, and for content creators : those who do not want to create an account on a strange development website like 'github' :)

I agree it is not so good for developers as issues should be all listed on github.
A chat system like discord would be interesting for developers though.

BGG forum is good mostly to do some promotion of content, I guess, but difficult to use it as a centralized point.

**Comment by BenRQ** [comment]
I have created a discord : https://discord.gg/yrVeSVt
Please join :)

It would be great to share it on the README.md (GitHub first page).

Let's see if anyone comes and want to discuss :)

**Comment by NPBruce** [comment]
I added to the main wiki page (readme.md just links to it).

**Comment by BenRQ** [comment]
Thanks @NPBruce
