### ISSUE TITLE
Debug with Unity

### ISSUE THREAD

**Issue by BenRQ** [NPBruce/valkyrie#861]
Hi

I have one simple question on Unity development.

Is it possible to debug directly in Unity and/or Visual studio ?
I mean add breakpoints, go step by step, see logs in Console.

The only way I found to test my changes was to "build & run" from Unity.

**Comment by redwolf2** [comment]
1. Install Visual Studio 2017 Community Edition, make sure to add the unity Extension. 
1. In your valkyrie folder, open libraries\libraries.sln or double click on Game.cs inside unitys project explorer.
1. Press the play button (centered at the top inside the unity editor)
1. Inside Visual Studio press the play button "Attach to Unity"

If there is a problem, like break points that show a warning sign, rebuild solition inside VS and press File > build & run inside unity.

See also: https://github.com/NPBruce/valkyrie/wiki/DeveloperGuide

**Comment by BenRQ** [comment]
OK thanks a lot, I was able to make it work.
Maybe it is my unity version, but I can't open Game.cs from the Unity project explorer.

Selecting it manually from windows explorer does the job though.

**Comment by NPBruce** [comment]
I will add that break points in Unity+VS are super buggy. It will randomly get stuck forcing you to stop the unity execution and start again. This normally happens when stepping though code and is very annoying.
