### ISSUE TITLE
MoM: Integrate Horrific Journeys

### ISSUE THREAD

**Issue by redwolf2** [NPBruce/valkyrie#868]
https://www.fantasyflightgames.com/en/news/2018/7/2/horrific-journeys/

Manual:
https://images-cdn.fantasyflightgames.com/filer_public/f6/71/f671c831-b06a-40db-95d3-05b8f89b6262/mad27_rules.pdf

**Comment by BenRQ** [comment]
I guess it's time :)

Is there a process to do this ?

**Comment by redwolf2** [comment]
Check out the changes made for sot here: https://github.com/NPBruce/valkyrie/commits/master/unity/Assets/StreamingAssets/content/MoM/sot

**Comment by BenRQ** [comment]
I realized that without the extension itself, it may be a bit difficult to integrate.
I would need a lot of info like name of characters on token with the picture, monsters info, tile name ...

**Comment by redwolf2** [comment]
@RhOmicron could you help out with the components, like you did with Streets of Arkham? (https://github.com/NPBruce/valkyrie/issues/654)

**Comment by RhOmicron** [comment]
I'm unable to help out for a long time as I'm away from home. I hope someone else can help out.

//RhOmicron

**Comment by redwolf2** [comment]
**Tile Graphics**

TILE_PASSENGER_CAR_2_MAD27
Tile_Dining_Car_1_MAD27
Tile_Engine_MAD27
TILE_STATION_MAD27
TILE_LOUNGE_CAR_MAD27
TILE_PASSENGER_CAR_1_MAD27
Tile_Caboose_MAD27
TILE_POOL_MAD27
TILE_MEDICAL_OFFICE_MAD27
TILE_SHIP_DECK_6_MAD27
TILE_ENGINE_ROOM_MAD27
TILE_SHIP_DECK_5_MAD27
TILE_PROW_MAD27
TILE_SHIP_DECK_3_MAD27
TILE_SHIP_DECK_1_MAD27
TILE_SHIP_DECK_4_MAD27
TILE_SHIP_DECK_2_MAD27
TILE_TRACKS_MAD27
TILE_FREIGHT_CAR_1_MAD27
Tile_Viewing_Room_3_MAD27
Tile_Viewing_Room_1_MAD27
TILE_SPA_MAD27
TILE_DINING_ROOM_MAD27
TILE_CHART_ROOM_MAD27
TILE_CABIN_1_MAD27
Tile_Viewing_Room_2_MAD27
TILE_CABIN_3_MAD27
TILE_CREW_BEDROOM_MAD27
TILE_BRIDGE_MAD27
TILE_LIFE_BOAT_MAD27
TILE_STORAGE_HOLD_MAD27
TILE_FREIGHT_CAR_2_MAD27
TILE_BAGGAGE_CAR_MAD27
TILE_OBSERVATION_CAR_MAD27
TILE_SLEEPER_CAR_MAD27
Tile_Dining_Car_2_MAD27

**Expansion Graphic**

MAD27

**Comment by BenRQ** [comment]
I will integrate all character tokens and pictures, as I'm already working on this for the issue #964 
But I will need the name at some point.

**Comment by BenRQ** [comment]
Someone shared the content of Horrific Journeys with me through a few photos.
I think I have all I need to do the integration.

I can share it with you if you want to work on this too @redwolf2.
I'm just working on tokens for the moment.

The grey bearded man is not available in Horrific Journey, neither is the blue rift.

Also there is a new puzzle type : line

**Comment by redwolf2** [comment]
That's ok. Nice find those are probably the next expansion. Be aware, that the font may also contain new glyphs, so they might need an update, too.

**Comment by scrubbless** [comment]
> Also there is a new puzzle type : line

New to 2nd ED. Not to MoM ^.^ it's a puzzle from first edition.

**Comment by BenRQ** [comment]
Integrating HJ in 2.2 would delay the version too much so moving this to 2.3.

**Comment by scrubbless** [comment]
That's fine, but would love to see it added.

**Comment by redwolf2** [comment]
Rough Component Overview. https://docs.google.com/spreadsheets/d/18N1zt6MJYvpOe39FK3GKajME4-ixr5DbPJ3r0NSccC0/edit#gid=1766866456

**Comment by redwolf2** [comment]
@scrubbless I think the puzzle is new. Instead of swapping out tiles, you can rotate them.

https://youtu.be/9t9YeoxRWXI?t=209

**Comment by scrubbless** [comment]
There was a rotate puzzle in 1st edition. It wasn't pipes from what I remember

**Comment by redwolf2** [comment]
I need to know the flipside of each tile.

**Comment by scrubbless** [comment]
I can attach some pictures a little later

**Comment by redwolf2** [comment]
@scrubbless No worries. First time unboxing videos come in handy.
https://www.youtube.com/watch?v=_C8KNy4IKr4

**Comment by redwolf2** [comment]
Ready to merge: https://github.com/NPBruce/valkyrie/pull/1101

**Comment by BenRQ** [comment]
Merged in master
