### ISSUE TITLE
Portuguese Translation of The Scenario "Believe Or Die - A Search For Ashcan Pete"

### ISSUE THREAD

**Issue by andrex47** [NPBruce/valkyrie#871]
### Description of Problem or Question
I began to translate this scenario, if you would like to help you can acess the file here:
https://drive.google.com/drive/folders/1OVdutsxHP9omgDW4oSiJ-Ie0Rn0q6TRw?usp=sharing

### Attach Save, Quest or Scenario
Saves:  
%appdata%/Valkyrie/MoM/Save  
%appdata%/Valkyrie/D2E/Save  
Quest:  
%appdata%/Valkyrie/D2E/Editor  
Scenario:  
%appdata%/Valkyrie/MoM/Editor

**Comment by FASTNAVi** [comment]
Thank you very much! I will happy upload your translation when will be done. Also I will welcome improve of english version.

Second scenario is still under construction (and will be minimal to the end of the year) and I will also appreciate the translation. =)

**Comment by FASTNAVi** [comment]
@andrex47 Hi! Just for you information, i just recently changed and add several texts in this scenario. I hope that it is no problem for you. Thank you for your support! =)

**Comment by andrex47** [comment]
i was done half of the translation so far, i will check the scenario changes and see if i can make use of at least part of the old translation i was working on

**Comment by andrex47** [comment]
the translation is good, i have checked and the new lines were added to the end of the document, right now i have 20 out of 42 pages

**Comment by FASTNAVi** [comment]
@andrex47 great news! But beware, I also changed a few old texts. I will try to findout which ones and let you know ;-)

**Comment by FASTNAVi** [comment]
I hope that this list of changed texts will help you:

SpawnEugene_ulice.text
SpawnEugene_klub.text
Eventnalezeni_brokovnice.text
Eventvratitsosky1.text
Eventdvere_Ashcan2bezklice.button1
Eventdvere_Ashcan2bezklice.text
Eventdvere_Ashcan1bezklice.button1
Eventdvere_Ashcan1bezklice.text
EventdvereAshcan1_bezklice.button1
EventdvereAshcan1_bezklice.text
EventKlub_Eugene_cosedeje.text

I am not 100% sure, that it is all, but most probably yes.

**Comment by andrex47** [comment]
thanks a lot

**Comment by andrex47** [comment]
sorry for the delay but here it is
[Localization.Portuguese.txt](https://github.com/NPBruce/valkyrie/files/2473146/Localization.Portuguese.txt)

**Comment by andrex47** [comment]
[Localization.Portuguese.txt](https://github.com/NPBruce/valkyrie/files/2473697/Localization.Portuguese.txt)
finally done

**Comment by andrex47** [comment]
@FASTNAVi i just finished testing the scenario, everything ok here

**Comment by andrex47** [comment]
[Localization.Portuguese.txt](https://github.com/NPBruce/valkyrie/files/2473721/Localization.Portuguese.txt)

**Comment by andrex47** [comment]
The only problem i have seen is the introduction of the scenario, the text doesnt fit the screen

**Comment by andrex47** [comment]
[Localization.Portuguese.txt](https://github.com/NPBruce/valkyrie/files/2473786/Localization.Portuguese.txt)

**Comment by FASTNAVi** [comment]
Hi Andrex47. Thank you very much. I will check it in Sunday. I will try to do something with the introduction ;-)

**Comment by andrex47** [comment]
thanks a lot, the introduction i am talking about is the line
UIuvod_text.uitext
