### ISSUE TITLE
left-allign list of events and tokens

### ISSUE THREAD

**Issue by antontimmermans** [NPBruce/valkyrie#873]
### Description of Problem or Question
A small but for me very convenient change request would be to change the display of events and tokens a little. Currently the eventnames can be sorted but are centered but if would be great if they are left-alligned. Why?
I have named tokens + events systematically and  related to their location (tilename) to deal with a complex scenario. When you browse trhough them (sorted) and they are left-alligned, its way more easier to find the one you are looking for.
I know... it sounds like a minor inconvenience but I hope you can fix itbecause i really havd problems finding the next event. 
I have a lot more complicated scenario's I my head which i don't dare to create because of the effort of finding the right event,

PS. I absolutely LOVE the App.. thank you so much for making it.

### Valkyrie Version
2.0.1.

### Attach Save, Quest or Scenario
Saves:  
%appdata%/Valkyrie/MoM/Save  
not relevant

%appdata%/Valkyrie/D2E/Save  
Quest:  
%appdata%/Valkyrie/D2E/Editor  
Scenario:  
%appdata%/Valkyrie/MoM/Editor 
 not relevant

**Comment by BenRQ** [comment]
Hi @antontimmermans 

as I'm not a big scenario writer I prefer getting some other opinions before doing it.
It's quite easy to do, so I can include it in next release if everyone is OK with this.

@scrubbless,  or any other scenario author, what do you think ?

**Comment by antontimmermans** [comment]
Hi @BenRQ  

Thank you for considering this change. If you manage to hide this behind a sorting button like there is now for alfabetic sorting then it probably iks acceptable to all. since people then have an option to use it .. or not.
 @scrubbless , would that work? (or any other scenario author?)

**Comment by BenRQ** [comment]
I would rather do something simple.

When sorted by number: text is centered
![image](https://user-images.githubusercontent.com/40794717/44948669-0de48000-ae22-11e8-8146-bcf957561d53.png)


When sorted by name : text is left aligned
![image](https://user-images.githubusercontent.com/40794717/44948670-150b8e00-ae22-11e8-9d1d-99422cd5c342.png)

By default text will be centered (as it is today).
Please note this will change the behavior for all the list in the editor when sorted by name.
Here for example, puzzles: 
![image](https://user-images.githubusercontent.com/40794717/44948681-471cf000-ae22-11e8-881e-cc88bf31f49f.png)

**Comment by antontimmermans** [comment]
A perfectly acceptable solution for me, it looks realy good. I am looking forward to see the update.
@BenRQ, Muchas gracias. Thanks!

**Comment by BenRQ** [comment]
Beta test version is now available with implementation of this issue:
https://github.com/BenRQ/valkyrie/releases/tag/release%2F2.1%2FBrynhildr_2.1.0b

**Comment by redwolf2** [comment]
Reopen, because it is fixed in Brynhildr, but not in Valkyrie. I created the label "Brynhildr" to track, what is covered by it.

**Comment by antontimmermans** [comment]
I checked it on Brynhildr and I am a fan.

**Comment by NettleTea** [comment]
Me too
