### ISSUE TITLE
New Scenario - The Stand

### ISSUE THREAD

**Issue by GwanGwanish** [NPBruce/valkyrie#874]
### Valkyrie Version. 2.0.1.

**Comment by NPBruce** [comment]
We've hit a problem here, the directory name is used to uniquely identify the scenarios, and both this and Lost Memories use "EditorScenario3".

I'm afraid you'll have to rename the directory and repackage to get a unique name (I suggest using TheStand).

**Comment by GwanGwanish** [comment]
Will do. Thanks. Try to take care of that this evening.

**Comment by GwanGwanish** [comment]
Ok, I updated the folder to no longer be "EditorScenario3." There are now
two folder versions, one where just the folder name is changed to "The
Stand." The copy folder has all references to "EditorScenario3" changed to
"EditorScenarioTheStand."

https://github.com/GwanGwanish/Mansions2/tree/master/The%20Stand

Hopefully that fixes the unique identifier issue?

**Comment by NPBruce** [comment]
https://github.com/GwanGwanish/Mansions2/tree/master/The%20Stand%20-%20Copy

This what I need. However, unfortunately spaces have been added to the path which is a problem.

It sounds like you have manually edited the generated files, it will be easier to rename the directory in %appdata%\Valkyrie\MoM\Editor and then repackage.

**Comment by GwanGwanish** [comment]
Oy vey. Alright. I'll remedy this evening. Will title "TheStand" with no
spaces.

**Comment by GwanGwanish** [comment]
Ok. I re-uploaded with no spaces. No more "editorscenario3". Tried it
locally. It seems to work now and is recognized by Valkyrie when moving
into %appdata, etc.

Hopefully smooth sailing from here.

**Comment by NPBruce** [comment]
Thanks, sorry for the trouble. I will do this when I am home (unless @scrubbless wants to test their new power before I get there).

**Comment by scrubbless** [comment]
Ok I think I did it. Can you check I've not broken anything @NPBruce. Is there an easy way to get the "raw.githubusercontent.com link? I just used the other as exoles to build Gwans. But have noticed some have the branch (master) at the end. I assume those just have the initial in the root of the branch?

**Comment by NPBruce** [comment]
There is a "Raw" button when you are looking at the file ie:

https://github.com/GwanGwanish/Mansions2/blob/master/TheStand/EditorTheStand.ini

Next to "Blame" and "history".

You have an invite pending for permissions on this repo (note that it is different to the master file itself, because that is hosted on a different repo).

**Comment by scrubbless** [comment]
That's odd @npbruce. I only got an invite email for the Valkyrie-store.

Is there a way I can see pending invites in GitHub?

**Comment by NPBruce** [comment]
Try this?

https://github.com/NPBruce/valkyrie/invitations

**Comment by GwanGwanish** [comment]
The scenario appears to function normally. Just ran through the scenario a
couple times.

**Comment by scrubbless** [comment]
@NPBruce  that worked thanks!

**Comment by GwanGwanish** [comment]
Sorry to bother, but I made an important fix to the scenario and uploaded
it to Github as version 1.2. The file name is now "TheStand2." Could
"TheStand2" be swapped in for "TheStand" on Valkyrie? It seems you guys are
manually uploaded, so I apologize for the hassle. A player discovered that
one of the optional events has a bug, so I fixed it. Also made some edits
to the Scenario Description and other items.

https://github.com/GwanGwanish/Mansions2/tree/master/TheStand2

**Comment by NPBruce** [comment]
This isn't a great idea. Changing this in the download list will show up as a new scenario, with the old one removed rather than an update to the old one. If the user downloads it they will have 2 copies of The Stand in their scenario list.

The better way to handle this is to just update the files already referenced. If you use Valkyrie's package tool it will identify the change and the user's download list will mark the scenario as updated.

**Comment by GwanGwanish** [comment]
Hmm,

So I should have retitled the version number in the title of Valkyrie App,
repackaged win the edits, replaced the ini and Valkyrie file of my original
local folder ("TheStand") and then used GitHub to push out the update?

Apologies for all the hassle.

**Comment by scrubbless** [comment]
From inside the editor, click "Tools" and then "Create Package" it will then spit out the compressed scenario into a folder on the desktop.
