### ISSUE TITLE
New Scenario - A Strain on Reality

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#875]
Also known as - A Strain on Valkyrie ;)!
Can you please publish my latest scenario. The URL is as follows:

https://github.com/scrubbless/PublishedScenarios/tree/master/StrainOnReality

### Valkyrie Version
2.01

@NPBruce I know you're a busy man, but I would appriciate it if you could add this and the other Scenario in #874

**Comment by NPBruce** [comment]
Added. You have some large PNG files, most of them would be better off recompressed as JPG, something to consider.

**Comment by scrubbless** [comment]
I use a lot of transparency and have use PNG optimiser, but I'll see what o can convert. Cheers Bruce
