### ISSUE TITLE
MoM tutorial into spanish

### ISSUE THREAD

**Issue by EtiCarasoft** [NPBruce/valkyrie#876]
### Translation for Valkyrie MoM tutorial into Spanish

Hi @scrubbless
I've translated your MoM tutorial into spanish, for the user's maybe you want to share it here.

https://docs.google.com/document/d/1yogKLaSEFFZvnJ0VdVDMKzohv2k0XPsHlVxW30qha8g/edit?usp=sharing

Also one extra question : Do you give me permission to disseminate the translated file? Obviously without any lucrative intention, just so that more people can do scenarios.

Thank you!

¿How do you see it @eorahil ?

**Comment by scrubbless** [comment]
I absolutely give you permission, didn't write it for credit. Just as long as it's free to all share away.

**Comment by scrubbless** [comment]
Thanks for your kinds comments at the end @EtiCarasoft :) I had to Google translate it ;)

**Comment by redwolf2** [comment]
I added it to the wiki https://github.com/NPBruce/valkyrie/wiki/ExternalSites
