### ISSUE TITLE
Can you support the Chinese UI for Android version?

### ISSUE THREAD

**Issue by zifeixu85** [NPBruce/valkyrie#877]
First of all, I am very grateful to the author's tools. Secondly, my English is not very good, please forgive me.

Can the software interface support Chinese? I see that there is chinese in the menu option but I can't choose.
We have friends who translated Chinese scenario, but the UI and Mythos Phase are still in English.

Thanks!

**Comment by NPBruce** [comment]
Here is the file that needs to be translated:

https://raw.githubusercontent.com/NPBruce/valkyrie/master/unity/Assets/StreamingAssets/text/Localization.English.txt

If I can get that in chinese I can turn it on. Alternatively I can enable Chinese without this and it will use the FFG translations, but most of the menu items will be in English.

**Comment by zhengrx** [comment]
hello,
I have put this file into Chinese. Hope it can be useful to you.
you can use it and turn it on.

[https://pan.baidu.com/s/1cIMMgCZrZYBfWcrAnXdoFQ](url)
Thanks!

**Comment by redwolf2** [comment]
Integrated it an created a pull request: https://github.com/NPBruce/valkyrie/pull/881

**Comment by redwolf2** [comment]
@zifeixu85 @zhengrx You may want to check out the latest release of @BenRQ, which has the chinese translation in it. https://github.com/BenRQ/valkyrie/releases/tag/release%2F2.1%2FBrynhildr_2.1.0b
