### ISSUE TITLE
Valkyrie unable to locate MoM (Windows10)

### ISSUE THREAD

**Issue by Fataelis** [NPBruce/valkyrie#879]
Hello !
Just discovered Valkyrie and was eager to try it, but some issue appeared right up front : 
"Unable to locate Mansions of Madness, install via Steam"
![valkyrie problem](https://user-images.githubusercontent.com/42347398/44035675-4e36df2a-9f10-11e8-8594-12aa6da4cd15.png)

Though Mansions of Madness IS installed on Steam (and works just fine)

MoM version 1.5.1 (it's kept up to date by Steam)
Valkyrie 2.0.1 (latest I think)

I've tried to : 
Uninstall then reinstall MoM
Use Valkyrie from the .zip rather than from the .exe
Launch Valkyrie with  -import C:\Program Files (x86)\Steam\steamapps\common\Mansions of Madness

I'll join the output log as I saw it was often requested.

I hope we'll be able to find a solution to this problem!

Thanks for your time :)

Fataelis

[output_log.txt](https://github.com/NPBruce/valkyrie/files/2283207/output_log.txt)

P.S. : sorry if my english is a bit off, not my mother tongue...

**Comment by redwolf2** [comment]
Please run the valkyrie.exe as Administrator (right click → Run As administrator)

**Comment by redwolf2** [comment]
Yes, try to copy the dir over. Copy the content of 

`C:\Program Files (x86)\Steam\steamapps\common\Mansions of Madness\`

to

`C:\Program Files\Steam\steamapps\common\Mansions of Madness\`

Let me know what worked for you.

**Comment by Fataelis** [comment]
Re, 
Sorry for the slow answer from me (><)

So I did what you suggested, to no avail... When i looked at the new output_log, I saw it mentioned a D:\Program/Mansions of Madness_data folder, which didn't existed.
So I created also one, and copied again the content of the other "Mansion of Madness" folders, and re-launched Valkyrie, but nothing more (with or without the -import).

Here is the output_log, after launching without the -import 
(there is now a "Mansion of Madness" folder in C:\Program Files (x86)\Steam\...... ; C:\Program Files\Steam\...... ; and D:\Program\  )

[output_log.txt](https://github.com/NPBruce/valkyrie/files/2284212/output_log.txt)

Fataelis

**Comment by redwolf2** [comment]
Not a problem at all, if someone else will run into this trap, we have this case documented here.

**Comment by barrick09** [comment]
Can someone please help me with this. I am also using windows 10 and having the same issue. However, this does not solve the problem. I have tried uninstalling, reinstalled, run as admin, copied the directory, everything is up to date. But when I launch Valkyrie the only options are exit and no MoM found on steam.

What do you mean when you say  ""without the "-import""  where did write this????
Are you typing this? are you choosing this option inside stream? Valkyrie?

Its really not clear and the info out there for installing this is almost none existent. 

I have been at this for hours and cannot figure this out. 

Thanks.

**Comment by BenRQ** [comment]
Hi @barrick09 ,

I'm pretty sure that Fataelis was referring to the quotations for the path.

He was using 
> valkyrie.exe -import C:\toto
instead of 
> valkyrie.exe -import "C:\toto"

Please share with us the command line you are using if it's still not working.

Also I'd like to understand why MoM import files are not detected for you, so can you please tell us:
 1) when did you install MoM on steam ?
 2) Did you move steam directory at some point ?
 3) Did you reinstall windows at some point ?

Thanks

**Comment by coffeechico** [comment]
Hello
I have the same problem. The Valkyrie import the Descent files but it doesn't reconize the Mansions of Madness
![image](https://user-images.githubusercontent.com/129565242/229258582-1426a265-5f5a-44d2-bf24-6666770ee802.png)

**Comment by DRHoule** [comment]
@coffeechico Did you get this resolved?  Having the same issue.  Went through everything that was offered here.  Valkyrie still can't locate MoM.

**Comment by DRHoule** [comment]
That was exactly it.  Thanks, I can dabble with Valkyrie now.
