### ISSUE TITLE
Save Functionality is not working

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#880]
### Description of Problem or Question
Hi All, 

The save function does not appear to work on my latest scenario. If you save at any point in the scenario and then try to load it, it opens to a blank screen.

### Valkyrie Version
2.01

### Attach Save, Quest or Scenario
Strain on Reality (v1.3) - Start the scenario and run the intro sequence. Hit save, then exit to the main menu. Click Load and select a save, it opens to a blank screen.

Can anyone help troubleshoot this? Is there a program I can run in the background to help me try to debug this?

Is there a max file size or text limit that may be causing this?

**Comment by scrubbless** [comment]
Ohh thanks Ben.

I have a ton of music and sound effects in the scenario.

Where do I get the prerelease to test this?

**Comment by scrubbless** [comment]
Ohh great, I tested this on your version of Valkyrie and the save seems work.

I'll do some more testing at different stages of the scenario. Look forward to seeing this incorporated into the next release.
Can you do Valkyrie pre-releases or is that just Bruce?

**Comment by BenRQ** [comment]
I can do pre releases and releases from my branch ' Valkyrie Brynhildr '.
But that won't be 'official' Valkyrie releases.

Also please note that the issues listed in the official Valkyrie from Bruce are attached to a target version numbers, as a roadmap.
My versions is a separate branch so I'm not working specifically on those issues, even if I may fix some here and there :)

It is not the perfect situation, but at least it helps the project moving forward (I hope so).

I really hope that my branch will be merged in the official Valkyrie release though as I don't think having two branches make sense in the long term.
I'm ready to help on this if anything needs to be done for this merge of course.

**Comment by MrTantum** [comment]
@BenRQ could you maybe also check if the bug #842 also occurs because of the nullpointer error?

We had to [pause](https://boardgamegeek.com/article/29641694#29641694) our "Shadow Rune" project because of this bug. Would be fantastic if you could find a fix for this. I'll also try to check your branch version on the weekend.

**Comment by BenRQ** [comment]
@mrtantum I'm pretty sure it is not the same issue.
But I can have a look and try to fix it for next release if this is a blocker.

**Comment by scrubbless** [comment]
Fixed in bryhildr, thanks BenRQ.

Hi @NPBruce tagging you for visibility when you're back.

**Comment by BenRQ** [comment]
Hi @scrubbless, please do not close issues fixed in Brynhildr .

After discussion with @redwolf2 we decided to keep those open until they are fixed in the official release.

**Comment by scrubbless** [comment]
Oh, you asked for it to be closed. No worries though
