### ISSUE TITLE
Build issue for test release

### ISSUE THREAD

**Issue by BenRQ** [NPBruce/valkyrie#882]
Hi,

I'm trying to build an alpha release to share with a few testers.
I followed the wiki : https://github.com/NPBruce/valkyrie/wiki/DeveloperGuide#prerelease

But I've been going through some compiling issues.
First one is now fixed : steam path was hardcoded, and not valid in my computer.
I did some changes in the scripts, please see the commit.

Now I can build the windows release, but I still have issues with mac, android and Linux

Seems like the issue is on Unity side because the binaries are not being generated.
I may need to install something there.
Here are the logs attached if you can help me, otherwise I will keep digging.

[Editor.zip](https://github.com/NPBruce/valkyrie/files/2312277/Editor.zip)

**Comment by BenRQ** [comment]
Sorry for the useless commits, I'm getting crazy with git once more.......

**Comment by BenRQ** [comment]
OK for the build issue, it was not too complex: I did not install the right modules in Unity....
👎

**Comment by BenRQ** [comment]
Android, Linux build are now available.

Android build has to be switched to Internal, as Grade build system is failing due to this issue:  
https://answers.unity.com/questions/1480075/gradle-build-error-when-update-from-564p4-to-20173.html

Mac OS X build is still failing (working in Unity, but failing through the script).

**Comment by BenRQ** [comment]
Last issue with Mac build is solved. 
I had to change the build option from 
"%ProgramFiles%\Unity\Editor\Unity.exe" -batchmode -quit -projectPath %~dp0unity -buildOSXPlayer ..\build\macos\Valkyrie.app
to
"%ProgramFiles%\Unity\Editor\Unity.exe" -batchmode -quit -projectPath %~dp0unity **-buildTarget OSXUniversal -buildOSXUniversalPlayer** ..\build\macos\Valkyrie.app

**Comment by BenRQ** [comment]
Beta test version is now available with implementation of this issue:
https://github.com/BenRQ/valkyrie/releases/tag/release%2F2.1%2FBrynhildr_2.1.0b

**Comment by scrubbless** [comment]
Awesome, cheers @BenRQ.

I'll use this for testing scenarios and playing any if I get the opportunity!
