### ISSUE TITLE
MacOS: Wrong scenario name causes editor issues

### ISSUE THREAD

**Issue by Ashgur** [NPBruce/valkyrie#883]
I was working with the 1.6.1 - version on my MacBook up until today.
After reimporting my MoM - Game - Data i had a problem with all the markers in my scenario when i was opening it in the editor (wrong image was shown, for example all my exploration markers were shown as character markers).
So now i downloaded the actual version (2.0.1) and that solved the problem. But now something really strange is going on:
I am able to open my scenario in the editor but afterwards im not able to create new events/markers/etc. If im trying to do so, everything that is happening is that the component window is going to close.
Also: If im trying to save and test also nothing is happening.
If im going to edit an existing event and add a marker there (adding component --> new marker), this works .... at least almost: Im getting a new marker and im able to edit the text, name, image and the buttons. But for some reason i cant change the position.

Do you have any clue what is going on here?
All the best!
Ashgur

**Comment by BenRQ** [comment]
Hi Ashgur,

I tried to load your scenario in the editor, add an event, save&test.
It all works fine for me.

The directory name from your archive is a bit strange though, I don't know why, and you should probably change it.

I suggest you just rename your directory to a proper name, and remove (or move and save somewhere else) any other scenario you have in the same directory so you can be sure you are working in the right directory.

**Comment by Ashgur** [comment]
Thank you so much!! ;-)

I just renamed the folder and all over sudden everything is working fine again!
Thanks for your help, buddy! Really much appreciated!

All the best!
Ashgur

**Comment by BenRQ** [comment]
Cool, it was an easy fix :)

I see your scenario is already quite advanced.
Do you plan to translate your scenario in English too, or any other language ?

People here can help translate it, but having the English version would help a lot to translate it to other languages.

**Comment by Ashgur** [comment]
I guess i will need about three more weeks to finish the scenario.

Yes, i would love to do a translation afterwards! =)
But im not sure whether my english is good enough for a nice translation.
Maybe I could create an english version and hand it over to a native english speaker in this forum to make a revised version...
We will see ;-) I will first put my focus on finishing the scenario and i guess we will be able to find a solution for the translation!

**Comment by redwolf2** [comment]
>  Maybe I could create an english version and hand it over to a native english speaker in this forum to make a revised version...

That's what I did before. Just hand it over to a native speaker for prove reading.

**Comment by redwolf2** [comment]
I will close it for now, since this is a problem due to os restrictions and not Valyrie and it has been identified and solved.
