### ISSUE TITLE
Add a text notification, on first screen when a new Valkryie version is available

### ISSUE THREAD

**Issue by BenRQ** [NPBruce/valkyrie#889]
Hello,

It would be great to have a small text notification, or even better a link, to tell the users that a new Valkyrie version is available.
Something non intrusive, we already have enough "please update" popup as it is in all other applications :)

I'm thinking about putting this as a small red text, in the first screen (where you choose the type of game you want to play).

What do you think about this ?
Any suggestion on the way to do it ?

**Comment by redwolf2** [comment]
Good idea. 
Also have a look at this. https://github.com/NPBruce/valkyrie/issues/501

**Comment by BenRQ** [comment]
Thanks @redwolf2, I guess this is a duplicate then.
Closing it, and I will share my updates on the other issue.
