### ISSUE TITLE
New Scenario

### ISSUE THREAD

**Issue by GwanGwanish** [NPBruce/valkyrie#890]

**Comment by scrubbless** [comment]
Hi Gwan 

I'll get this added when I get to a PC (it's a pain to do on a phone!)

**Comment by scrubbless** [comment]
Scratch that, I did I :)

It's showing in the download list now.
![screenshot_20180910-085259_valkyrie](https://user-images.githubusercontent.com/32058089/45283905-0c2c5380-b4d7-11e8-95ec-451e6341a12c.jpg)
