### ISSUE TITLE
Monster breaks investigator phase

### ISSUE THREAD

**Issue by Mattias-G** [NPBruce/valkyrie#892]
While working on a MoM scenario I ran into a problem where the investigator phase would be skipped entirely. Apparently it happens if the monster can't perform its activation event (because its has a failing test). In other situations this just skips the event but here it breaks the game. Having a test on the activation event was a mistake on my part so the issue doesn't affect me, but is still not an obvious correlation.

![image](https://user-images.githubusercontent.com/6932158/45421279-d4ffa300-b68c-11e8-83e8-e77b940feef3.png)

Valkyrie Version: 2.0.1

**Comment by scrubbless** [comment]
Is this a custom monster? I found that custom events that run during mythos or horror phase end the round. Like if you look at a QItem that has an inspection event during the horror phase it ends the horror phase automatically

**Comment by Mattias-G** [comment]
Yes, it's a custom monster. You are likely right that it's a similar issue to the ones you described.

**Comment by BenRQ** [comment]
I have a fix available for issue #841 , and probably this issue too.
I would like to test it on this issue to make sure the fix is working.

Could you please share a test-scenario where I can reproduce the issue ?

**Comment by Mattias-G** [comment]
I've made a small test-scenario with a single custom monster that should trigger the bug. It looks like the issue might be a little different from #841 because the phase doesn't seem to end. Rather the problem is that it _doesn't_ end as it normally would when all monsters have performed their actions (I guess it's still waiting for the monster to do something, probably a flag that needs to be set).
[MonsterPhaseBugTest.zip](https://github.com/NPBruce/valkyrie/files/2387819/MonsterPhaseBugTest.zip)

**Comment by BenRQ** [comment]
Thanks a lot Mattias, it is now fixed.
It was a different issue, as you suspected.

The state machine of phases in Valkyrie is not so simple, it took me some time to find the fix for this one!
Should be quite robust now.

**Comment by Mattias-G** [comment]
Sweet. Thanks for looking into it!
