### ISSUE TITLE
[Android, Mac, Linux] Images/Sounds in Subfolders do not load

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#894]
### Description of Problem or Question
Images (and I assume sounds) do not load when they are nested in sub folders on Android. Works fine on Windows.
![image](https://user-images.githubusercontent.com/32058089/45681162-ba1daa80-bb34-11e8-8ee0-3690e81dd0a5.png)

Just get a blank UI load and then can't click anything.

### Valkyrie Version
2.01

**Comment by redwolf2** [comment]
I found it. The reason is the backslash in the image path.

```
; Saved by version: 2.1.0a
[Quest]
format=9
hidden=False
type=MoM
defaultlanguage=English
image=Images/fantasy.jpg


[QuestText]
Localization.English.txt

[QuestData]
```

Created a pull request with the fix: https://github.com/BenRQ/valkyrie/pull/21

**Comment by scrubbless** [comment]
Cheers Redwolf, I figured it was a Linux/Windows (or Linux\Windows) divide thing
