### ISSUE TITLE
Spanish Translation for "The Truth" Scenario

### ISSUE THREAD

**Issue by EtiCarasoft** [NPBruce/valkyrie#895]
### With the help of some other users we've translated the truth scenario into spanish.

I'm looking for the creator @SlyCozz or maybe @redwolf2 the first in translation order. 
We've cheched without seeing any problem.

[Localization.Spanish.txt](https://github.com/NPBruce/valkyrie/files/2395883/Localization.Spanish.txt)

I attach the file, for the translation text use the nick: Aruok it's a name of the group of people involved in the translation.

@NPBruce we're trying to translate all scenarios into spanish ;)

**Comment by redwolf2** [comment]
Only @slycozzolino can integrate it, but I am sure he will ;-)

**Comment by EtiCarasoft** [comment]
thank you i didn't find the correct user name

**Comment by redwolf2** [comment]
Be aware, that the scenarios by @NPBruce and "Robbery of the Kanakian Idol" are not maintained, so focussing on scenarios by other creators would be preferable.

**Comment by EtiCarasoft** [comment]
I'll take it into account, thanks again.

**Comment by slycozzolino** [comment]
Added
Thank you for translating.

**Comment by vidimus** [comment]
@slycozzolino 

Hi! I'm trying to contact Sly Cozz - the author of short and fun scenario called "The Truth". It has not been translated into Polish yet and I would like to help with that. Can anyone help me with getting in touch with Sly Cozz?
@sircohen

https://discord.com/channels/473584815166455808/521494546224250889/1020643780346511370
sircohen#5471

**Comment by slycozzolino** [comment]
Do you have the translation already done? If so go ahead and up load it here and I'll add it.
