### ISSUE TITLE
New Scenario - A Night In Wiltshire

### ISSUE THREAD

**Issue by Mattias-G** [NPBruce/valkyrie#896]
Hi all! Here is a new scenario for MoM 2nd editions. It'd be fantastic if you could add it to the listing. Thanks!

https://github.com/Mattias-G/MansionsOfMadness/tree/master/NightInWiltshire

P.S. Working with Valkyrie has been a great experience, it's a really neat engine!

**Comment by redwolf2** [comment]
@scrubbless Can you add it in?

**Comment by scrubbless** [comment]
Added!

**Comment by scrubbless** [comment]
It is worth posting an announcement in the following bgg thread. I'll get a new poll added with the newest scenarios soon.

https://boardgamegeek.com/thread/1916430/fan-made-scenarios-reviews-valkyrie

**Comment by Mattias-G** [comment]
Thanks for the tip, I'll do that right away.
