### ISSUE TITLE
New Scenario // Nuevo escenario

### ISSUE THREAD

**Issue by V0r1an** [NPBruce/valkyrie#897]
https://github.com/V0r1an/mansiones

Thanks for your job!

Edit the new name "https://github.com/V0r1an/La_Mascarada"

**Comment by redwolf2** [comment]
Please give your folder and files a unique name (like `LaMascarada` for the folder, `LaMascarada.ini`, `LaMascarada.valkyrie`) and provide a rectangular image for the scenario.

**Comment by V0r1an** [comment]
Now?

**Comment by V0r1an** [comment]
Nop :)… i Will try more late

**Comment by V0r1an** [comment]
I think that now it´s ok... 
Thanks RedWolf :)

**Comment by redwolf2** [comment]
The image https://github.com/V0r1an/La_Mascarada/blob/master/La_Mascarada/5285_view.jpg is still not rectangular ;). It must have the same width and height.

**Comment by V0r1an** [comment]
Red... sorry, what is the route for "put" images in valkyrie (i dont remenber it) 
Ty

**Comment by redwolf2** [comment]
@V0r1an 
You still may want to change it to a sqare image and remove the file  5285_view.jpg from the root of the repository.

@scrubbless 
Can you add it in? 
https://github.com/NPBruce/valkyrie-store/pull/4

**Comment by V0r1an** [comment]
The file 5285_view. Jpg is not regular (square)? Because i changed It yo
300*300 px (i think...). This is the unique imagen that my scenary need...
The problem can be in the other imagen🤣🤣🤣 that i should delete... And
maybe Change the name of 5285_view 😋
Ty red

**Comment by redwolf2** [comment]
Not a problem at all. Seems great now.

**Comment by V0r1an** [comment]
thank you very much! I just hope that there are not many failures and that
people enjoy playing, as I have enjoyed doing it.

**Comment by redwolf2** [comment]
No problem, @scrubbless will add it in, when he has time for it. I don't have the rights to do so.

**Comment by scrubbless** [comment]
Added :)
![image](https://user-images.githubusercontent.com/32058089/46040101-546a8900-c107-11e8-9d64-c4af7b4a1073.png)

**Comment by scrubbless** [comment]
It is worth posting an announcement in the following bgg thread. I'll get a new poll added with the newest scenarios soon.

https://boardgamegeek.com/thread/1916430/fan-made-scenarios-reviews-valkyrie
