### ISSUE TITLE
Promoting Brynhildr

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#899]
### Description of Problem or Question
BenRQ has fixed a lot of bugs in his version of Valkyrie. I've been using this (and the alpha) for a while and it seems stable, added cool features and fixes a lot of issues (importantly save/perf issue and adding the in game reviews).

I've seen some negitive comments from the community, due to the lack of progress.

I know you are busy with RL @npbruce (congrats btw!), so I am wondering if it would make sense to open up access for a group of people to pull content into the master branch and release new versions.

Here is @BenRQ 's beta if you're interesting in checking it out:
https://github.com/BenRQ/valkyrie/releases/tag/release%2F2.0%2Fv2.0.2b

**Comment by NPBruce** [comment]
I'm sorry I've dropped the ball on this. At this stage I don't see much changing until next year.

As I am not capable of even reviewing other people's work at this stage, I have an alternative proposal:

Would you @scrubbless or @BenRQ be interested in taking over the project?

I would be happy to leave it hosted under my user (as there are a lot of links to here) or provide links to the new home if it is moved?

Perhaps in the future I can be a contributor again.

**Comment by scrubbless** [comment]
No need to apologise, it's a personal project not a job! :D

I'm happy to maintain what I can and promote it to the community, but I have nowhere bear any skills with unity (or anything outside the editor to be honest).

I would not feel comfortable "taking it" over wholesale. But would more than happy to help maintain and administer it in your absence.  If you want to,  grant permissions to the repos for BenRQ and myself (but keep yourself as overall owner, for the time when you come back).

**Comment by BenRQ** [comment]
Hi @NPBruce, I'd be happy to 'take over' with the time I have.
I'm not yet familiar with everything you did for this wonderful project but I'm slowly getting there.

Also @redwolf2 has been of great help to get me started, and he still is today for a lot of topics.
There is definitely work for two or more people !
And I think he already got all the rights.

Thanks for the great job you did @NPBruce, we'll try not to mess it up too much while you are off and we will be happy to you see come back when you can ;)

**Comment by scrubbless** [comment]
Thanks guys, I'll close this issue. We can discuss on discord how to proceed with merging your beta BenRQ
