### ISSUE TITLE
Classify items from Beyond the Threshold

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#90]
Need to add the keywords from the items as traits.  I can't do this as I don't have BtT.

**Comment by eorahil** [comment]
I will get it as soon as it's published in spanish, but this will be later April at least.

**Comment by Hobbeslionheart** [comment]
I can help as I own BtT, but how would you want it in? Am not a coder, but could plug it into code if I know where it goes and there's samples.

**Comment by NPBruce** [comment]
Examples from the base game are here:
https://github.com/NPBruce/valkyrie/blob/master/content/MoM/base/items.ini

BtT content is here:
https://github.com/NPBruce/valkyrie/blob/master/content/MoM/btt/items.ini

**Comment by Hobbeslionheart** [comment]
Completed.

**Comment by NPBruce** [comment]
Can you upload here?

**Comment by NPBruce** [comment]
Just realised you forked, great!  Want to do a pull request (to development branch please) or should I just grab it?

**Comment by Hobbeslionheart** [comment]
You should do it. I'm afraid of messing up your work.

**Comment by NPBruce** [comment]
For your information, your fork is the only place you can change you don't have permission to change the original copy (a pull request is a request for me to accept your change).

I have moved it across.
