### ISSUE TITLE
Opening custom scenario bugged

### ISSUE THREAD

**Issue by Grieverouz** [NPBruce/valkyrie#904]
### Description of Problem or Question
Hi! I've been working on my own homebrew scenario for MONTHS now, and suddenly when i saved my progess, the editor closed and went to valkyrie main menu. I tried to open my scenario again and it keeps taking me to the main menu. Is the scenario gone? The other scenarios are working on the editor just fine but my main scenario which i've been working for months, seems to be gone... How do I save my beautiful scenario? Help..

**Comment by BenRQ** [comment]
Hi @Grieverouz, can you share the scenario here ? I will have a look.
I hope I can fix it for you !

**Comment by Grieverouz** [comment]
Hi! Thanks for the fast answer, but how do i share it. Can't drop the whole "EditorScenario"-file here...

**Comment by BenRQ** [comment]
You need to zip the directory, and share it here.
If it's too big, you can use https://wetransfer.com/ or any other filesharing system.

**Comment by BenRQ** [comment]
I have it. I'll try to start it in debug mode, and see if I see anything.

**Comment by Grieverouz** [comment]
Thanks alot mate. I'll wait for the results

**Comment by BenRQ** [comment]
You have two spawn events with "undead" and "Fleshless" required traits.
No monsters have those two traits, so the app cannot find any monster, and goes back too main menu.
To fix this in your scenario you should open the spawns.ini file, and fix this with a text editor.

Please note that app behaviour (going back to the main menu) is a bit extreme.
I will change that to just add a warning in the logs.

Also please note you need to change the directory name before submitting your scenario : it will be the unique name to identify your scenario, and it will also be used for ratings.

I hope I will have the occasion to try your scenario soon enough :)

**Comment by BenRQ** [comment]
Also don't forget to remove the .rar file in your scenario ;)

**Comment by Grieverouz** [comment]
Wow, thanks alot dude! You just saved my scenario :)

**Comment by BenRQ** [comment]
You're welcome 👍
