### ISSUE TITLE
Problem with dialogues in combination with the shop interface

### ISSUE THREAD

**Issue by DelphiDie** [NPBruce/valkyrie#911]
### Description of Problem or Question
I just noticed, that there is a problem with dialogues in combination with the shop interface. If you accidentaly buy or sell an item while a dialogue window is open this window gets set to a lower layer, and the buttons become unavailable. This leads to a situation where the game is no longer responding on other button clicks (like menu) and has to be closed by force.

### Valkyrie Version
2.1.0

**Screenshots:**
![1](https://user-images.githubusercontent.com/26790002/46902668-5be0af00-cec9-11e8-94ad-d3f38092dabe.jpg)
Clicking on on of the red marked items or any other item will lead to the issue.

![2](https://user-images.githubusercontent.com/26790002/46902669-5e430900-cec9-11e8-8ba5-ed2ca0b8b097.jpg)
The game no longer responds, as it seems to wait for an input on the dialogue which can no longer be made.

**Steps to reproduce:**
- Download the campaign "The shadow Rune"
- Start the campaign.
- Forfeit first quest.
- Travel to the city
- Click on either black market or other merchant
- While the text window is open buy or sell an item

**Suggestion:**
Make selling and buying items impossible if a text window is open or has the focus.

**Comment by BenRQ** [comment]
Hi @DelphiDie 
So I fixed the problem, but I'm pretty sure it was already there in 2.0.1.

**Comment by DelphiDie** [comment]
Yes, I'm also pretty sure that the problem was there before, but I simply never encountered it. Thanks for fixing this :)
