### ISSUE TITLE
End the game in monster phase

### ISSUE THREAD

**Issue by antontimmermans** [NPBruce/valkyrie#913]
### Description of Problem or Question
In my scenario investigators have a limited ammount of turns until a StarSapwn spawns. And when it spawns they have a limited amount of rounds until the monster reaches a certain location.
In the monster phase the investigatiosn have the usual option to attack or evade that monster but also the option to select that the Monster has reached the end location.
When this option is selected, the end-game tekst is displayed (invesigators losing) and $end is set to 1

However, the game stays in the Monster (horror phase) and the continue button in the end text cannot be clicked, Nor can the move turn to next phase (end-horror phase) button in the lower right corner be selected.
The only way to end the game now is to select the option from the menu in the top right corner.

So what I would like to request is a way to force the game out of its myhtos and horror phase so I can end the game nice and clean. 

NOTE : the other ways to end is when investigator dies, or when the scenario is completed succesfully but this all happens in the investigator phase
NOTE: The attached scenarion is NOT ready for publishing, it is stll being tested and finetuned. Although my friends already enjoyed playing it :).

### Valkyrie Version
Brynhildr_2.1.0b

### Attach Save, Quest or Scenario
Saves:  
%appdata%/Valkyrie/MoM/Save  
%appdata%/Valkyrie/D2E/Save  
Quest:  
%appdata%/Valkyrie/D2E/Editor  
Scenario:  
[DisturbanceAtTheDocks.zip](https://github.com/NPBruce/valkyrie/files/2476455/DisturbanceAtTheDocks.zip)

**Comment by scrubbless** [comment]
Not addressing the bug, but you could make the monster moves event trigger at End round or start round. This might fire a little better. Also you could even track the monsters movement with variables so you don't have to even ask the investigators where the monster is.

**Comment by BenRQ** [comment]
Hi @antontimmermans , I tried to reproduce the issue with your scenario but the scenario is quite big, and I've got stuck with the bell UI after a while, and the clear button doing nothing.
I've not reached the part you have described here in your issue.

And I'm not reading text too much, as the scenario looks quite good, and I don't want to spoil myself too much :)

Would you be able to do a mini scenario to reproduce the issue only ?

**Comment by antontimmermans** [comment]
Thank you,

I wasn't aware that the testsessions would be recorded too. I thought only the published version would be recorded. My apologies. I was not trying to fake good score.


________________________________
Van: BenRQ <notifications@github.com>
Verzonden: maandag 15 oktober 2018 00:20
Aan: NPBruce/valkyrie
CC: antontimmermans; Mention
Onderwerp: Re: [NPBruce/valkyrie] End the game in monster phase (#913)


BTW, I've deleted the ratings you created during your tests session of this scenario (the ratings with only a few minutes of gameplay). I kept the real play session you did of course :)

**Comment by antontimmermans** [comment]
> Not addressing the bug, but you could make the monster moves event trigger at End round or start round. This might fire a little better. Also you could even track the monsters movement with variables so you don't have to even ask the investigators where the monster is.

Thank you for your suggestion. The end round or start round trigger might work, I will look into it. Tracking the monsters movements with variables could have been a clean option if the end turns are really fixed. The problem is that the investigators have the option to slow down the progress of the monster (not stopping) by engaging it. Through some items (I believe the .45) they even have the option to push the monster back. This makes automatic tracking very difficult.

**Comment by antontimmermans** [comment]
> Hi @antontimmermans , I tried to reproduce the issue with your scenario but the scenario is quite big, and I've got stuck with the bell UI after a while, and the clear button doing nothing.
> I've not reached the part you have described here in your issue.
> 
> And I'm not reading text too much, as the scenario looks quite good, and I don't want to spoil myself too much :)
> 
> Would you be able to do a mini scenario to reproduce the issue only ?

In fact, I have a test button (a little hidden clue token just above the townsquare) to trigger/test end conditions. I have disabled it in the attached version but can easily be added during the EventTownSquarePlace tile sequence (first tile). 
The turn in which the StarSpawn Spawns is set in the EventQStart and depends on the number of investigators. So this issue can be reproduced by patiently clicking away turns .. but that will take a while.  In the testversion I will force this to turn 2.
Later today I will attach a version of this scenario to this ticket with both modifications. 


****SPOILER ALERT****
**** do not continue reading if you wish to play the scenario ****

As for getting stuck with the bell: you should be able to clear the Bell UI always. If you cannot, then I made a mistake in the scenario.
The bell UI checks 2 two things: 1. Enter the correct number of stones. (randomized) 2. Collect at least enough stones to match that number. I suspect that with your click-through you didn't collect enough gems.

**Comment by antontimmermans** [comment]
> > Hi @antontimmermans , I tried to reproduce the issue with your scenario but the scenario is quite big, and I've got stuck with the bell UI after a while, and the clear button doing nothing.
> > I've not reached the part you have described here in your issue.
> > And I'm not reading text too much, as the scenario looks quite good, and I don't want to spoil myself too much :)
> > Would you be able to do a mini scenario to reproduce the issue only ?
> 
> In fact, I have a test button (a little hidden clue token just above the townsquare) to trigger/test end conditions. I have disabled it in the attached version but can easily be added during the EventTownSquarePlace tile sequence (first tile).
> The turn in which the StarSpawn Spawns is set in the EventQStart and depends on the number of investigators. So this issue can be reproduced by patiently clicking away turns .. but that will take a while. In the testversion I will force this to turn 2.
> Later today I will attach a version of this scenario to this ticket with both modifications.
> 
> ****SPOILER ALERT****
> **** do not continue reading if you wish to play the scenario ****
> 
> As for getting stuck with the bell: you should be able to clear the Bell UI always. If you cannot, then I made a mistake in the scenario.
> The bell UI checks 2 two things: 1. Enter the correct number of stones. (randomized) 2. Collect at least enough stones to match that number. I suspect that with your click-through you didn't collect enough gems.

As promissed a test version. After you go through the intro you will notice a clue token north of the townsquare. That token allows you to select the option "spawn Big Bad". After you selected that, end the turn and you will get the monster dialogue where you select "monster reached the town square".
This will trigger the end-dialogue where you cannot click the end-turn button , or the continue button in the end UI
[DisturbanceAtTheDocksTest.zip](https://github.com/NPBruce/valkyrie/files/2479837/DisturbanceAtTheDocksTest.zip)

**Comment by BenRQ** [comment]
Hi @antontimmermans,
I'm testing with version 2.1.2 (fresh from today).

I don't see the issue, as you describe it: if I press continue I just see the end screen rating (if the quest is in a valkyrie package), or I go back to menu (if the quest is not packaged, and is played from a directory).

So from my point of view, it is the expected behaviour.

Can you please test again in 2.1.2 ?
Please tell me if you expect something else at this point.

PS: No problem for the test ratings, it's easy to filter out the ratings coming from short tests, as there is a "game duration" info for each rating.

**Comment by antontimmermans** [comment]
Tested on 2.1.2. It seems to work properly now.
Clicking the UI Continue button in the final graphics brings me back to the main menu as expected. 
Thanks.

**Comment by BenRQ** [comment]
Cool, I hope I can test it soon :)
