### ISSUE TITLE
Descent Quest Editor tile allignment problem

### ISSUE THREAD

**Issue by DelphiDie** [NPBruce/valkyrie#920]
### Description of Problem or Question
The value "xposition" of the snap indicator for tile "TileSide60A" is off by 0.5 in the Descent quest editor.

### Valkyrie Version
2.1.2

### Attach Save, Quest or Scenario
![indicator](https://user-images.githubusercontent.com/26790002/46978623-bf3c2e00-d0cf-11e8-9cf1-4b708634d2f1.jpg)

**Comment by NPBruce** [comment]
60A and 61B are also out. And 58B has an RtL image we should be using.

**Comment by NPBruce** [comment]
Fixed in 2.4
