### ISSUE TITLE
UI Button - Background

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#921]
UI Boxes (like text boxes) allow for a boarder to be added and the text and board colour ("colour" in screenshot) to be set, however it does not allow for a background colour. 

![image](https://user-images.githubusercontent.com/32058089/47082488-9a49d700-d205-11e8-9ffe-08671e9895f8.png)

Therefore all buttons have a transparent background.

![image](https://user-images.githubusercontent.com/32058089/47082516-ba799600-d205-11e8-8b76-75d73dc143f9.png)

It would be good to have the option of setting a background.

### Valkyrie Version ###
2.1.2

**Comment by scrubbless** [comment]
Hey @BenRQ  not sure if you saw this one.

**Comment by BenRQ** [comment]
Yes, I'm actually working on it. It's a good start for me to try to do some changes in the editor.

I wanted to do it quickly, but it's a bit more complex than I thought .....
I'm still working on it.

**Comment by scrubbless** [comment]
No worries @BenRQ I wasn't sure if you missed it (or assumed I was trying to fix it) when I added the enhancement label.

**Comment by BenRQ** [comment]
Done, will be available in release 2.2.

I lost quite a few points of sanity on this, thanks @redwolf2 for the help.
