### ISSUE TITLE
Continue Arrow doesn't show up on Android

### ISSUE THREAD

**Issue by redwolf2** [NPBruce/valkyrie#922]
### Description of Problem or Question
Arrow does not show up on a HTC m8 with Android 7.1.2.

### Valkyrie Version
2.1.2

![screenshot_20181017-211937](https://user-images.githubusercontent.com/4141621/47111029-b1fb7c80-d252-11e8-8e1e-168d9c3f2152.png)

**Comment by BenRQ** [comment]
The character may be missing from the font somehow ?
Is it your phone @redwolf2 or someone else ?

**Comment by redwolf2** [comment]
My phone

**Comment by BenRQ** [comment]
We have the font inside the app, so there shouldn't be any problem on that side.
You can try this in any case : https://docs.unity3d.com/ScriptReference/Font.HasCharacter.html

But I think the better solution would we use the font embedded in the app, instead of the system font.

**Comment by BenRQ** [comment]
or maybe ... it is just a matter of lower / upper case : 

Can you please replace "fonts" with  "Fonts" in GameType.cs ?

        return (Font)Resources.Load("Fonts/MADGaramondPro");

**Comment by redwolf2** [comment]
Will try, when I manage to update my unity version.

**Comment by scrubbless** [comment]
Shows up on my Samsung Edge 7

**Comment by redwolf2** [comment]
Got some problem with the build using the latest Unity Version 2018.3.13. IJava.Lang.ArrayOutOfBoundsException.

**Comment by redwolf2** [comment]
With the "Internal" build, instead of Gradle, it works just fine.

**Comment by redwolf2** [comment]
Made the fix: https://github.com/NPBruce/valkyrie/pull/928

**Comment by BenRQ** [comment]
Now merged, closing.
