### ISSUE TITLE
Upload scenarios

### ISSUE THREAD

**Issue by Samurai83ITA** [NPBruce/valkyrie#924]
### Description of Problem or Question
It's possible to upload a scenarios that i create? thanks... (I create a lot of scenarios)

### Attach Save, Quest or Scenario
Saves:  
%appdata%/Valkyrie/MoM/Save  
%appdata%/Valkyrie/D2E/Save  
Quest:  
%appdata%/Valkyrie/D2E/Editor  
Scenario:  
%appdata%/Valkyrie/MoM/Editor
[La Follia di Arkham.zip](https://github.com/NPBruce/valkyrie/files/2491662/La.Follia.di.Arkham.zip)
[Rapimento.zip](https://github.com/NPBruce/valkyrie/files/2491663/Rapimento.zip)

**Comment by scrubbless** [comment]
Hi @Samurai83ITA 

It is better if you create a repository for your own scenarios, I wrote a guide that has a section on using GitHub. This will be your best option, since you already have a GitHub account.

Once you have it on GitHub post the link and I can add it to the manifest for download.

The reason this is better, is that if you update your scenario you can automatically push those changes to your repository and update the live scenario. Meaning you don't have to log issues to update your own content.

https://docs.google.com/document/d/1Gi5gTwKkw84Px0Lvk-bJ3Aml_vF3ZoljjB6a8FjWGt8

Here is a direct link to the GitHub section:
https://docs.google.com/document/d/1Gi5gTwKkw84Px0Lvk-bJ3Aml_vF3ZoljjB6a8FjWGt8/edit#heading=h.5cpbiphzxju0

There is a spanish version available also:
https://docs.google.com/document/d/1yogKLaSEFFZvnJ0VdVDMKzohv2k0XPsHlVxW30qha8g

Here is the jump link to the GitHub section:
https://docs.google.com/document/d/1yogKLaSEFFZvnJ0VdVDMKzohv2k0XPsHlVxW30qha8g/edit#heading=h.5cpbiphzxju0

**Comment by Samurai83ITA** [comment]
https://github.com/Samurai83ITA/Scenari-Valkyrie
This is the repo, i use the desktop software...

**Comment by scrubbless** [comment]
![image](https://user-images.githubusercontent.com/32058089/47159417-be7ce500-d2e5-11e8-841a-0b3b26c3aaa7.png)


Did you commit and push the changes? I can't see the files.

**Comment by scrubbless** [comment]
I assume the repository is public?

**Comment by Samurai83ITA** [comment]
Yes it's public... try now

**Comment by scrubbless** [comment]
Wow you've done lots of them!

**Comment by BenRQ** [comment]
@Samurai83ITA you can also share the repo access with me and @scrubbless, so we can do this renaming.
Then you will be able to update the scenarios later if required.

Access rights can be shared from the settings, collaborators, add collaborator :

![image](https://user-images.githubusercontent.com/40794717/47243148-7a770680-d3f1-11e8-87c4-4073a7bb5fae.png)

**Comment by Samurai83ITA** [comment]
Ok, i renamed all scenarios now... sorry for late...
I add you like collaborators too

**Comment by scrubbless** [comment]
Thank you @samurai83ita.

I don't see the changes, did you commit the changes and push them to your online repo?

**Comment by BenRQ** [comment]
@scrubbless I see the changes in the repo of @Samurai83ITA : 
See the commit :
https://github.com/Samurai83ITA/Scenari-Valkyrie/commit/efe74d50d53e3777569c4208fa9e860df95cc8e5

**Comment by Samurai83ITA** [comment]
@scrubbless Yes I did it

**Comment by scrubbless** [comment]
For example, I need to take this path:
https://raw.githubusercontent.com/Samurai83ITA/Scenari-Valkyrie/master/Il%20Manufatto%20Conteso%20-%20Competitivo/Il%20Manufatto%20Conteso%20-%20Competitivo.ini

And Import it in. The Manifest will not allow any path with **%20** in it.

![image](https://user-images.githubusercontent.com/32058089/47645802-eda71800-db69-11e8-91b4-4b97a6993ff2.png)

**Comment by Samurai83ITA** [comment]
renamed all :)

**Comment by scrubbless** [comment]
Thanks @Samurai83ita

They have all been added to the manifest. You should see them in the download section of Valkyrie.

**Comment by Samurai83ITA** [comment]
Ok thanks

**Comment by Samurai83ITA** [comment]
> Hey @Samurai83ITA , I could translate your scenarios to english if you want (sono italiano), are they work in progress?
> would you be ok with it?
> if you give me your personal ranked list for your scenarios (from your most favorite to least favorite) i can just walk my way down through them so we can make them available for the rest of the community to enjoy!
> 
> I am not a native english speaker but i have been living/working outside of Italy for over 10yrs now; it would be great if we could get a native english speaker do a pass after i do the initial translation as well.

Per me non ci sono problemi nella traduzione. Purtroppo non ho molta dimestichezza con l'inglese da tradurlo perfettamente.
L'ordine che preferirei sarebbe:
Il Rapimento
La Follia di Arkham
La Maledizione di Cthulhu
Il Manufatto Conteso

Grazie

**Comment by Arioch82** [comment]
I have just finished a transltion for "The Kidnapping" (Il rapimento), it was my first translation it was fun :)

I have to go through and playtest it to make sure i didn't break anything and i also need to translate all tiles names with the proper english names.... it sucks that that part is not automated with some references :(

What's the best way to have a native english speaker proof read it/playtest it? Attach it here? send it to Samurai?

**Comment by redwolf2** [comment]
@Arioch82 I moved your post here: https://github.com/NPBruce/valkyrie/issues/944

**Comment by scrubbless** [comment]
Hello @Arioch82 

I know this is a bit of a necro, but did you translate this scenario? I have collaborate access to the repo so should be able to help getting this translation made live. 

I can also proof read.
