### ISSUE TITLE
Scenario ready for Publishing: Disturbance at the docks

### ISSUE THREAD

**Issue by antontimmermans** [NPBruce/valkyrie#925]
### Description of Problem or Question
The scenario "Disturbance at the Docks" is ready to be published. This scenario can be played with the game Mansions of Madness 2nd edition and does not require any expansions.

It is our first attempt at writing a MOM scenario. Your feedback is much appreciated. 

### Valkyrie Version
2.1.2

### Attach Save, Quest or Scenario
Saves:  
%appdata%/Valkyrie/MoM/Save  
%appdata%/Valkyrie/D2E/Save  
Quest:  
%appdata%/Valkyrie/D2E/Editor  
Scenario:  
%appdata%/Valkyrie/MoM/Editor  
https://github.com/antontimmermans/MOMDATD

**Comment by scrubbless** [comment]
Published, thank you!

**Comment by antontimmermans** [comment]
@scrubbless  or @BenRQ 

I just published an update of this scenario which include modifications based on the feedback i have received so far.  (minor bug fixed, spelling correction and improved hints)

1. do I need to do anything else (or different) to publish this update?
2. what do I have to do to enable other users to improve my text (since mine are too dutch-english) or to make translations into other languages.

**Comment by BenRQ** [comment]
1. 
Publishing the update is enough.
If you want to keep track of the version which has been played, you should add a version number in the quest.name

2. 
You can post a message here on GitHub.
You can also say in an intro message of your scenario, that you welcome help and add a reference to the ticket.
