### ISSUE TITLE
Sign the APK

### ISSUE THREAD

**Issue by redwolf2** [NPBruce/valkyrie#926]
### Description of Problem or Question
Between Version 2.0.1 and 2.1 the APK couldn't be updated without a manual deinstallation of the APK. The reason is, that the 2.0.1 release was build on the machine of @NPBruce and the 2.1.0 release on the machine of @BenRQ. In order to avoid having to uninstall the APK to update, we have to sign it and ship the keyfile with the project, so that every builder will create the same APK signature.

https://boardgamegeek.com/thread/2079275/valkyrie-21x-installation-problems

The default keystore should be under:

`C:\Users\<user>\.android\debug.keystore` (default password is `android`)

But we better add one ourselfs using https://keystore-explorer.org/downloads.html for example.

Update: Another problem is, that the verision and versioncode does not change. The build creates version 1.0 every time.

### Valkyrie Version
2.1.2

**Comment by BenRQ** [comment]
@redwolf2 merge is done, can I close this issue or do you still want to improve it ?

**Comment by redwolf2** [comment]
We can close it.
