### ISSUE TITLE
[Linux] Valkyrie -import fix : to be tested

### ISSUE THREAD

**Issue by redwolf2** [NPBruce/valkyrie#930]
### Description of Problem or Question

> [Remark from pi on Discord]: I notice that if I run it without the import command it complains it can't find the steam installation, however, it seems to run just fine, that said, might as well just always run it with the import

### Valkyrie Version
2.1.2

**Comment by BenRQ** [comment]
Closing this one as we are close to RC1 of 2.2, we will re open if an issue is encountered.
