### ISSUE TITLE
Scenario Editor: Copy allows to copy downloaded scenarios

### ISSUE THREAD

**Issue by redwolf2** [NPBruce/valkyrie#932]
### Description of Problem or Question
The Copy button of the Scenario Editor allows to copy any downloaded scenario, if you copy your own scenario via the button once and hit Copy again.

### Valkyrie Version
2.1.2

**Comment by BenRQ** [comment]
With fix in #929 we now support copying existing scenario for edition.
I guess we can close this one then, as we now support the copy of downloaded scenarios.

What do you think ?

**Comment by redwolf2** [comment]
Ok, we can close it as it is a dublicate. I found another issue that might be related and will create a seperate one for it.
