### ISSUE TITLE
Download quest optimizations

### ISSUE THREAD

**Issue by redwolf2** [NPBruce/valkyrie#938]
Our download process is using a master file that links to all scenario meta files. This requires for all meta files to be requested in a HTTP call for every scenario in order to show all available scenarios in a list. This is a slow process that will get even slower, when more scenarios are involved.

Instead of requesting each meta file, we could generate one masterfile or one zip archive with all meta files.

Ideally there would be a service that can be triggered and auto replaces the file, when a change in a meta file is detected.

**Comment by NPBruce** [comment]
FYI Valkyrie itself already supports this.

Also worth considering how large the thumbnail images are.

The files to download could be done all at the same time and the images could be displayed when they are ready.

**Comment by redwolf2** [comment]
Ok, I will have a look at the download mechanism. Images could be a lazy loaded, when the requests returns, much like the browser does it.

**Comment by BenRQ** [comment]
Hi @redwolf2, Please note I've created a new branch for the new Scenario explorer v2 development.
So we can keep on working on bugfix in the dev_2.2 if we need to.

**Comment by BenRQ** [comment]
@redwolf2 I've started working on this through google scripts.
My objective is to generate one single ini file every hour with all latest data per scenario.

In the future I may consider parsing some of the data to generate a JSON file.

**Comment by BenRQ** [comment]
First version of script is available.

See the result here : 
https://drive.google.com/open?id=1CIwwOOuuowYsWcpl4NHVD39olkPc-ThH

@redwolf2 Tell me if you think something is missing.

**Comment by redwolf2** [comment]
Maybe remove `.valkyrie` in the ini sections. The rest looks good to me.

**Comment by BenRQ** [comment]
This feature is now fully implemented and merged in 2.2. Test version coming soon.
Please open a new ticket if you find an issue in the test version provided.
