### ISSUE TITLE
Looking for spanish betatesters for scenario. 

### ISSUE THREAD

**Issue by newusergettingnuts** [NPBruce/valkyrie#939]
### Description of Problem or Question
Greetings everyone, i have finished my first scenario, betatested it a few times but prior to uploading it i would be pleased to share it with some spanish betatesters to get opinions and advice.

If anyone is interested contact me so i can share the scenario.

many thanks!
cheers

### Valkyrie Version
2.1.2

**Comment by EtiCarasoft** [comment]
Me apunto ;)

I put on the list

**Comment by newusergettingnuts** [comment]
> Me apunto ;)
> 
> I put myself on the list. Anything you need.

genial eti ahí vi que sos de barcelona, yo soy de argentina, el escenario esta completo y hemos testeado los tiempos y resultado con un par de partidas pero antes de subirlo me gustaría recibir feedback respecto de lo siguiente:

Turnos empleados para el escenario: 
Tiempo empleado de juego: En horas y minutos
Resultado de la partida: Ganaron perdieron?
Opinión general (disfrutaron...no disfrutaron): Escucho toda critica con mucho interes :) 
Descubrieron algún BUG??

te dejo mi facebook para posterior contacto y te mando por ese medio el link con los archivos.

facebook MIGUEL FEDERICI

**Comment by vendettarock** [comment]
yo me puedo apuntar tb

**Comment by BenRQ** [comment]
Hi @newusergettingnuts ,
I'm cleaning up, please tell me when we can close this issue :)

**Comment by newusergettingnuts** [comment]
sorry missed  this one, of course you can close Ben. many thanks

**Comment by BenRQ** [comment]
Thanks :) 
Closing
