### ISSUE TITLE
Tokens that appear only if "X" or more investigators are playing

### ISSUE THREAD

**Issue by newusergettingnuts** [NPBruce/valkyrie#940]
### Description of Problem or Question:

Question and Idea

First idea:

Just sharing this idea that maybe everyone already use.- 

In this way it is possible to increase somehow the difficulty of the scenario without touching the mythos.

I am thinking on adding custom tokens for the scenario and so far for what i tested i works well.

The idea is to have several tokens or events spread acrros the board "that only" appear into the game when for example 4 or 5 investigaros are playing the game.

The way to do this is adding an event and activating:

test: #heroes >=4

This way when spawning the tile with 3 or less players the tokens wont show but if 4 or 5 players are playing it will.-

Now question:  Anyone know another easy way to handle difficulty for different qntity of investigators?

Pardon my grammar english is not my native language.

### Valkyrie Version
2.1.2

### Attach Save, Quest or Scenario
![image](https://user-images.githubusercontent.com/44534194/47928556-6fb67a00-dea5-11e8-8b53-8b5521f5753c.png)

**Comment by scrubbless** [comment]
Hi @newusergettingnuts 

I do this in in Stress and Strain and A Strain on reality, feel free to copy and have a look at them in the editor.

You can also use tests to add option nap content for expansions in the same way.

Test
#SoA = 1

**Comment by BenRQ** [comment]
Hi @newusergettingnuts, closing this issue.

It can still be accessed by all people looking for it :)
