### ISSUE TITLE
Install sceneario manually

### ISSUE THREAD

**Issue by mk1lolo** [NPBruce/valkyrie#941]
### Description of Problem or Question

I did a scenario. I send by email to my friend. Where do he have to put the files? What directory? 
### Attach Save, Quest or Scenario
Saves:  
%appdata%/Valkyrie/MoM/Save  
%appdata%/Valkyrie/D2E/Save  
Quest:  
%appdata%/Valkyrie/D2E/Editor  
Scenario:  
%appdata%/Valkyrie/MoM/Editor

**Comment by newusergettingnuts** [comment]
Run a search in your pc seeking

Valkyrie\MoM\Editor\scenario1

**Comment by scrubbless** [comment]
Windows:
%apodata%\Valkyrie\MoM\Editor\

Android:
Sdcard/Valkyrie/MoM/Editor

Drop it there, you can use folders under this directory.

**Comment by BenRQ** [comment]
@mk1lolo Did you get your answer ? Can I close this ticket ?

**Comment by mk1lolo** [comment]
Yes! Close. All ok
