### ISSUE TITLE
Enhancement: Wonderign if a round track for actual gameplay is possible?

### ISSUE THREAD

**Issue by newusergettingnuts** [NPBruce/valkyrie#942]
### Description of Problem or Question

I was wondering if it would be possible to add a round tracker always visible during game play?

I guess that kind of track is very usable for scenario creators and possibly to something else.
 
### Valkyrie Version
2.1.2

**Comment by BenRQ** [comment]
Hi @newusergettingnuts ,
the UI needs to be as small as possible in my opinion.
The more we add 'technical' info, the more it breaks the narrative and immersion.

I'm interested in other opinion though.

**Comment by scrubbless** [comment]
Stick it on the options menu? 

However you can always get the developer log in game by pressing Alt + D (or was Ctrl + D, I always forget!)

**Comment by antontimmermans** [comment]
In my opinion, displaying the round nr. feels a bit like cheating. The power of the game is in the story telling and the sense of urgency that builds up as the scenario evolves. Not knowing how in which turn you are, or how many turns it will take before the time runs out or the "big-bad thing" will happen, is part of the fun of the game (for me). 
So if this gets implemented, please don't do it in a way that it is visible during normal game play. If people want to know, then 'hiding' it in the options menu is the better solution. 
Alternatively it could be in save game menu with some text like "Select the save game where to store progress of scenario "bla bla bla" in turn "nr'). That way it's even more hidden but as savegame info it could be additional information to find the right savegame.

**Comment by scrubbless** [comment]
That is a very good point, got caught up in the technicals and didn't think of how it could break game experience.

For now developers can open the log (if launched from editor) or open the log and hit alt+d to open the developer log in a normal game.

I don't think this would be a good feature to add. It will clutter the UI and ruin the emersion for some players.

**Comment by redwolf2** [comment]
For the test in editor a debug view with all the information about vars, rounds and so on would be great. Round tracker could be added via options to the normal game, but I don't see the benefit for the normal user? If there is high demand for it, we could add it to the option menu.
