### ISSUE TITLE
English translation for "The Kidnapping"

### ISSUE THREAD

**Issue by redwolf2** [NPBruce/valkyrie#944]
> I have to go through and playtest it to make sure i didn't break anything and i also need to translate all tiles names with the proper english names.... it sucks that that part is not automated with some references :(
> 
> What's the best way to have a native english speaker proof read it/playtest it? Attach it here? send it to Samurai?
> 

_Originally posted by @Arioch82 in https://github.com/NPBruce/valkyrie/issues/924#issuecomment-436166121_

**Comment by redwolf2** [comment]
@rafbel Helped me out once, proofreading my rough translation (here https://github.com/NPBruce/valkyrie/issues/562). But maybe someone else is also willing to help.

**Comment by BenRQ** [comment]
>  i also need to translate all tiles names with the proper english names.... it sucks that that part is not automated with some references :(
Originally posted by @Arioch82 in #924 (comment)

@arioch82, it is automated !
You can use {c:TileAttic} for example in the text (in the editor) to replace automatically with the translated name.

**Comment by redwolf2** [comment]
As I did the german installation, I also did replace the tile names as @BenRQ suggested in the english installation. You can also use {qst:eventNameHere} to reference the text of other events. That helps to remove doubled text. I did that first in the english orginal, before the translation. That way you only need to translate the actual text and all the {qst:eventNameHere} references can stay in the original file.

**Comment by Arioch82** [comment]
Hey guys,

here is the first pass on the translation, i will try to play it tonight or sometime this week and do a second pass but i thought i could attach it here as a reference in case someone else wants to give it a go as well; it would be great to get a native english give some comments on how to translate better some sentences.

I have also had to add a new item to the items.ini so that i didn't have to hardcode the item name, i had to add .txt to the extension to be able to attach it here

```
[QItem19]
itemname=ItemCommonMedicalTextbook 
starting=False
```

I am also attaching the original italian file with all tiles locations changed so that they use the {c:TileName} format instead of hardcoded names in case @Samurai83ITA wants to update the original.


[items.ini.txt](https://github.com/NPBruce/valkyrie/files/2555658/items.ini.txt)
[Localization.English.txt](https://github.com/NPBruce/valkyrie/files/2555655/Localization.English.txt)
[Localization.Italian.txt](https://github.com/NPBruce/valkyrie/files/2555656/Localization.Italian.txt)

Let me know what you think!

**Comment by Arioch82** [comment]
Alright, i have playtested it tonight and fixed it as much as i could, you can find the final file attached to this message (you will still need the new items.ini from the previous message bundled together).

I would like to point out one thing in this scenario tho: there is a "puzzle" with two images
"vintage-journal-background-4 - Copia.jpg" and "Old_paper1 - Copia.jpg" where the second image has a code that can be used to translate a message in the first image (both accessible in the journal through items); i did not personally translate that message (didn't want to close/open two different items a thousand times to crossreference symbols while playing) nor i found any reference to it anywhere in the scenario so i think it's just a non-required/additional lore piece, but i would guess the message deciphers to an italian phrase? maybe it would be better to handle it differently for translations?

@Samurai83ITA fammi sapere se hai qualche domanda. (let me know if you have any questions).

[Localization.English.txt](https://github.com/NPBruce/valkyrie/files/2556397/Localization.English.txt)

**Comment by Samurai83ITA** [comment]
> Alright, i have playtested it tonight and fixed it as much as i could, you can find the final file attached to this message (you will still need the new items.ini from the previous message bundled together).
> 
> I would like to point out one thing in this scenario tho: there is a "puzzle" with two images
> "vintage-journal-background-4 - Copia.jpg" and "Old_paper1 - Copia.jpg" where the second image has a code that can be used to translate a message in the first image (both accessible in the journal through items); i did not personally translate that message (didn't want to close/open two different items a thousand times to crossreference symbols while playing) nor i found any reference to it anywhere in the scenario so i think it's just a non-required/additional lore piece, but i would guess the message deciphers to an italian phrase? maybe it would be better to handle it differently for translations?
> 
> Another thing i would like to point out for @Samurai83ITA is that you are requiring 1st edition content in the scenario for some reason; I only have Recurring Nightmares (one of the two tiles collections) so sometimes i was gaining items/spells that i don't actually have, but it looks like that limitation could be removed easily? I had all tiles, only had problems with items/spells.
> 
> @Samurai83ITA fammi sapere se hai qualche domanda. (let me know if you have any questions).
> 
> [Localization.English.txt](https://github.com/NPBruce/valkyrie/files/2556397/Localization.English.txt)

Ho visto la traduzione, gran bel lavoro, complimenti. L’immagine di cui parli permette di scoprire una frase che ti serve se dovessi venire catturato. E’ una frase da scegliere tra quelle che ti vengono chieste in un dialogo, quindi potrebbe essere utile tradurlo...

Ho fatto un nuovo file immagine con la frase in inglese. (Non avevo pensato a questa cosa per la traduzione 🤣)

La prima edizione l’ho inserita come richiesta sia per la mappa, sia per il mostro finale. Gli oggetti/armi dovrebbero essere quelli delle espansioni richieste. 

[
![diario inglese](https://user-images.githubusercontent.com/44261937/48133007-a1f51c80-e295-11e8-9260-0f1d1b2cee1e.jpg)
](url)

**Comment by Arioch82** [comment]
Another thing, the TileSideInteriorHall also contains two more rooms, "Small Bedroom 1" and "Small Bedroom 2", but referring to the {c:ComponentName} always translates "Interior Hall"; in this scenario the important room is "Small Bedroom 1", is it possible to change what is it pointing to? I had to manually say something like "the lower bedroom in {c:Tilexxx}" instead of being able to target the specific room in the tile

**Comment by Arioch82** [comment]
@Samurai83ITA forse il problema e' che hai MoM1EI, MoM1EM, MoM1ET nella lista?

**Comment by Samurai83ITA** [comment]
> @Samurai83ITA forse il problema e' che hai MoM1EI, MoM1EM, MoM1ET nella lista?

Quello lo devo mettere comunque sennò chi ha la prima edizione solamente (che alla fine vale come incubi ricorrenti) non lo potrebbe giocare

**Comment by Arioch82** [comment]
> > @Samurai83ITA forse il problema e' che hai MoM1EI, MoM1EM, MoM1ET nella lista?
> 
> Quello lo devo mettere comunque sennò chi ha la prima edizione solamente (che alla fine vale come incubi ricorrenti) non lo potrebbe giocare

penso che il problema e' che la prima edizione ha anche oggetti/armi/magie che RN non ha

**Comment by Samurai83ITA** [comment]
> > > @Samurai83ITA forse il problema e' che hai MoM1EI, MoM1EM, MoM1ET nella lista?
> > 
> > 
> > Quello lo devo mettere comunque sennò chi ha la prima edizione solamente (che alla fine vale come incubi ricorrenti) non lo potrebbe giocare
> 
> penso che il problema e' che la prima edizione ha anche oggetti/armi/magie che RN non ha; o almeno uno di quei tre

Non credo sia quello il problema... anche perché incubi ricorrenti sono solo miniature e tessere. Le carte della prima edizione sono incluse nella seconda... non è che nelle impostazioni del contenuto hai selezionato qualche espansione di troppo?

**Comment by Arioch82** [comment]
> > > > @Samurai83ITA forse il problema e' che hai MoM1EI, MoM1EM, MoM1ET nella lista?
> > > 
> > > 
> > > Quello lo devo mettere comunque sennò chi ha la prima edizione solamente (che alla fine vale come incubi ricorrenti) non lo potrebbe giocare
> > 
> > 
> > penso che il problema e' che la prima edizione ha anche oggetti/armi/magie che RN non ha; o almeno uno di quei tre
> 
> Non credo sia quello il problema... anche perché incubi ricorrenti sono solo miniature e tessere. Le carte della prima edizione sono incluse nella seconda... non è che nelle impostazioni del contenuto hai selezionato qualche espansione di troppo?

non penso, sei sicuro che tutte le carte della prima edizione sono incluse nella seconda?

**Comment by Samurai83ITA** [comment]
Credo di sì, le espansioni “incubi ricorrenti” e “visioni dell’oblio” non hanno neanche una carta, ed essendo espansioni della prima edizione va da se che tutte le carte della prima edizione devono per forza essere incluse nella seconda. Discorso diverso è “oltre la soglia”, l’altra espansione che serve per lo scenario, che ha nuove carte oltre a mostri e tessere...

**Comment by scrubbless** [comment]
Hello @Arioch82

I know this is a bit of a necro, I did not see this post, but did you translate this scenario? I have collaborate access to the repo so should be able to help getting this translation made live.

I can also proof read.

**Comment by Arioch82** [comment]
Hey, yes I did.

The final version for just the English file was posted here
https://github.com/NPBruce/valkyrie/issues/944#issuecomment-436532681

But there are a couple of files that needed modifications, I posted them here

https://github.com/NPBruce/valkyrie/issues/944#issuecomment-436467932

**Comment by Arioch82** [comment]
hey @scrubbless did you find what you needed?
I would be up to translate the other italian scenarios as well, as long as someone will actually upload the english versions :)

**Comment by scrubbless** [comment]
Hi @arioch82

I'll try to do something tomorrow on this. I have to admit I'd lost track of a few of these so apologise for my forgetfulness!

**Comment by scrubbless** [comment]
Ok I have got the files and its working, however its going to require some proof reading.

**Comment by scrubbless** [comment]
@Arioch82 I have a question about the Piano.

Should I be translating these to the sounds "Doe, Ray, Me, Far, Sow, La, T
DO
RE
MI
FA
SOL
LA
SI

These are the musical names for the notes, like "The Sound of Music". However isn't the last note (SI above) actually Ti?
https://en.wikipedia.org/wiki/Solmization

```
Tokentavolorotondo.button1 | {action} Examine
-- | --
Eventpiano.text | What is the first key you want to press?
Eventpiano.button1 | DO
Eventpiano.button2 | RE
Eventpiano.button3 | MI
Eventpiano.button4 | FA
Eventpiano.button5 | SOL
Eventpiano.button6 | LA
Eventpiano.button7 | SI
Eventpiano0.text | What's the second key?
Eventpiano0.button1 | DO
Eventpiano1.text | What's the second key?
Eventpiano1.button1 | DO
Eventpiano1.button2 | RE
Eventpiano1.button3 | MI
Eventpiano1.button4 | FA
Eventpiano1.button5 | SOL
Eventpiano1.button6 | LA
Eventpiano1.button7 | SI
Eventpiano0.button2 | RE
Eventpiano0.button3 | MI
Eventpiano0.button4 | FA
Eventpiano0.button5 | SOL
Eventpiano0.button6 | LA
Eventpiano0.button7 | SI
Eventpiano3.text | Which one last?
Eventpiano3.button1 | DO
Eventpiano3.button2 | RE
Eventpiano3.button3 | MI
Eventpiano3.button4 | FA
Eventpiano3.button5 | SOL
Eventpiano3.button6 | LA
Eventpiano3.button7 | SI
Eventpiano2.text | Which one last?
Eventpiano2.button1 | DO
Eventpiano2.button2 | RE
Eventpiano2.button3 | MI
Eventpiano2.button4 | FA
Eventpiano2.button5 | SOL
Eventpiano2.button6 | LA
Eventpiano2.button7 | SI


```

**Comment by Arioch82** [comment]
@scrubbless you are right, I didn't know that in English the last note was different.

It might be better to convert it to the following list for English speakers:

C
D
E
F
G
A
B

**Comment by scrubbless** [comment]
@Arioch82  
I could do this, but it might mess up the code puzzle. What do you think?

I have published the changes with the list in your translation (Do, Re, Mi, etc). @BenRQ I added the $end variable so we should get a rating prompt. I've also added a Synopsis and filled in the Author Field

**Comment by scrubbless** [comment]
I've just tested this and the rating prompt now appears :)

**Comment by scrubbless** [comment]
I'll close this off for now, you can still reply to the ticket to continue this discussion. I'd like to hear opinions on piano key idea - 
C
D
E
F
G
A
B

**Comment by Samurai83ITA** [comment]
Ok. Great job... Olny one thing... I don't remember if the piano clue is combined with an image... If u change the music note you have to change the image too... 😉

**Comment by scrubbless** [comment]
That's exactly the reason why I didn't change it :grin:

I remember reading it in text form during a test run, but was not paying enough attention to the dialogue (don't want to spoil it completely!) to see if there were other hints in UI elements

**Comment by vidimus** [comment]
Hello, @scrubbless.

I've translated this scenario into Spanish. Could you please update the scenario with it?

Here are the files:
[https://github.com/vidimus/Valkyrie-Mom-scenarios-translations/files/4209074/Localization.Spanish.txt](url)
[https://user-images.githubusercontent.com/41538948/73986240-65531d80-493d-11ea-8583-737ec811161e.jpg](url)

By the way, do you have access also to the other Italian scenarios? Just in case I want someday translate them (I think they form some kind of campaign).

Thanks for your time!

**Comment by scrubbless** [comment]
Hi, 

I'll take a look, I didn't write this and have not played it! So not sure what the puzzle is or means.

I can add the Spanish translation.

I do have access to the other scenarios uploaded by @Samurai83ITA

**Comment by vidimus** [comment]
Hello, @scrubbless 

In the original files, the picture is named "vintage-journal-background-4". It's a page from the Old Journal that contains a secret code. I've seen in other scenarios that they add a folder with the language name and the translated pictures go there.

**Comment by vidimus** [comment]
> Hi,
> I'll take a look, I didn't write this and have not played it! So not sure what the puzzle is or means. I'll have to work it out :)
> I can add the Spanish translation.

Hello, @scrubbless 

Any progress with this issue?

**Comment by vidimus** [comment]
@scrubbless or @antontimmermans , could you close this issue? It was solved, I think.
