### ISSUE TITLE
New Scenario En algún lugar de Massachusetts (v1.0/Base + RN/Español/3 Investigadores) Parte 1

### ISSUE THREAD

**Issue by newusergettingnuts** [NPBruce/valkyrie#947]
### Description of Problem or Question

Repositorie

https://github.com/newusergettingnuts/Massachusetts

### Valkyrie Version
2.1.2

### Attach Save, Quest or Scenario
Saves:  
%appdata%/Valkyrie/MoM/Save  
%appdata%/Valkyrie/D2E/Save  
Quest:  
%appdata%/Valkyrie/D2E/Editor  
Scenario:  
%appdata%/Valkyrie/MoM/Editor

**Comment by newusergettingnuts** [comment]
https://github.com/newusergettingnuts/Massachusetts

**Comment by scrubbless** [comment]
Added, thanks for the quick response.

**Comment by newusergettingnuts** [comment]
> Added, thanks for the quick response.

Hi scrubbles i made some minor changes to the scenario because the ending review was not functioning.

https://github.com/newusergettingnuts/Massachusetts
