### ISSUE TITLE
Triggering events after a Hero Turn

### ISSUE THREAD

**Issue by vendettarock** [NPBruce/valkyrie#948]
Hi im a new user of this amazing tool. Thank you for this great job.

Im triying my firs scenario and i have a little question.

Is it possible to trigger an event after a hero activation? Just after the hero push "end turn"?

**Comment by newusergettingnuts** [comment]
I guess Trigger: mythos is what you need

**Comment by vendettarock** [comment]
"End Round" is after all Heroes activations. im looking for an option to trigger an event just before the first or second Hero activation.

**Comment by newusergettingnuts** [comment]
Ahhh ok no che que yo sepa no hay. Cuando apretas el boton de end round se entiende que todos los investigadores ya han actuado.

**Comment by vendettarock** [comment]
Manualmente sí se me ocurren varias formas. Como poner un token con un testigo de dialogo e instrucciones a realizar. Pero quería algo más limpio.

El problema en Descent es que no hay botón para finalizar la ronda, sino que cada héroe marca el final de su activación y cuando están todos activados acaba automáticamente.

Es una pena que no exista un trigger para el momento justo despues de una activación. Podría dar mucho juego. Y en principio la app reconoce esa ventana de tiempo, ya que activa automáticamente un grupo de monstruos tras una activación.

**Comment by newusergettingnuts** [comment]
si es para descent no estoy seguro, yo uso la app exclusivamente para MOM2, pero si en el desplegable de triggers no hay nada lo veo dificil.

**Comment by BenRQ** [comment]
Hi @vendettarock,

@delphidie is the Descent specialist maybe he can tell if you if this is supported.
(I don't think so though).

**Comment by vendettarock** [comment]
Thing is, Valkyrie keeps a record of the heroes that have already been activated, both for monster activation as well as for knowing when the round ends. Wouldn't it be possible to access that variable to modify it? I feel it would be an interesting option: to implement (in case it doesn't exist) a #varActivations that gets cleared each round.

ie:  
If you want trigger and event just after the second hero turn:

@Event1 = -1
@Event1 + #VarActivations

Trigger @Event1

**Comment by scrubbless** [comment]
How do custom monster activations work in descent? It's a lot to work around. But could you somehow use their 'activations' event? It would mean that every monster is a custom monster, but might give you the flexibility you need.

**Comment by antontimmermans** [comment]
@vendettarock I am not sure if it solves your problem but there IS a way to trigger your own created events based on conditions that you specify. Can you check the updated Valkyrie MOM Tutorial  the chapter Variable, @Variable?

**Comment by redwolf2** [comment]
Check out [Scubbless Quest Creation Tutorial](https://docs.google.com/document/d/1Gi5gTwKkw84Px0Lvk-bJ3Aml_vF3ZoljjB6a8FjWGt8/edit) and the [QuestGuide](https://github.com/NPBruce/valkyrie/wiki/QuestGuide) on the wiki.
