### ISSUE TITLE
A little brighter tile(s) display area

### ISSUE THREAD

**Issue by antontimmermans** [NPBruce/valkyrie#950]
### Description of Problem or Question
Minor request to change the graphical editor.

Currently the editor screen looks like this (used the screen capture from work in progress on ticket 934):
![image](https://user-images.githubusercontent.com/42072372/48543880-b69f6900-e8c2-11e8-8ce5-abe523d6d8ca.png)

The tile display area (marked with the purple rectangle) is showing the tile layout darkened and high-lights the tile or token when selected. Very useful feature but for me the dark mode is a bit to dark. Adjusting the contrast or gamma on my screen didn't help much.

Can you make it just a little brighter it would be easier to find and click the UI elements also when I am not working in a complete darkened room. 
Obviously not to bright since it is still very useful to get the visual high-light feedback on which item is actually selected.

**Comment by redwolf2** [comment]
We could add a grey/white chess pattern as a background inside the editor.

**Comment by antontimmermans** [comment]
> We could add a grey/white chess pattern as a background while inside the editor.

Do you mean as a back ground in the purple marked area? 
That could helpful as a positioning grid of tiles. If it is for a positioning grid then I would opt for thin dotted/grey-ish lines that you can put as an overlay on top, and an option in the Tools menu to toggle the display of the grid on/off. And maybe even an option inside each object to snap to grid. Not that I have found a need for this (yet) but I can imagine that maybe someone has.

But my original request is about that the Tiles and Tokens in the purple area that are darkened while not selected, to make them less darkened (a little brighter). The darkness could potentially be switched with a high/med/low option in the Tools Menu so people with a better graphical card&monitor can adjust to max Darkness if they want.

**Comment by vendettarock** [comment]
Sorry for my noob question. How have you put the OR condition?

**Comment by scrubbless** [comment]
I'd love to see photo shop like layers, but that just sounds like a lot of work and load on Valkyrie.

**Comment by scrubbless** [comment]
Another way around this would be to have a 'visible in editor' button that hides the token or tile if set to false. That might help with multiple overlayed tiles/tokens.

**Comment by BenRQ** [comment]
I can already change the transparency just a bit so it's easier to see.
What value do you prefer :

0.2 (current value) : 

![image](https://user-images.githubusercontent.com/40794717/48870998-407b9480-ede3-11e8-9b27-0c218250c1fe.png)


0.3:

![image](https://user-images.githubusercontent.com/40794717/48870953-132ee680-ede3-11e8-9c5a-ad16ac5c1745.png)


0.4 : 

![image](https://user-images.githubusercontent.com/40794717/48870896-d105a500-ede2-11e8-8f67-914adf0a82a3.png)

**Comment by redwolf2** [comment]
0.3 is good.

**Comment by antontimmermans** [comment]
Great to see that you are working on this.

If the original intent with transparency was to show underlying tokens&tiles it didn't work for me for me since everything is to dark anyway to notice if tokens where stacked. I simply clicked the token and selected the correct token are in that location. Therefor my preference would be **0.4** so for me its easier to find the token locations. 

But how difficult is it to add this to the tools or options menu? 
Where you could select: High/Medium/Low contrast?  Or using different naming; Low/Medium/High Brightness? Whatever you prefer.

**Comment by scrubbless** [comment]
All three from the menu

**Comment by redwolf2** [comment]
I am ok with a setting in the option menu, but don't name it "Gamma", as this would be confused with the graphic setting for gamma. Name it something specific, like Heading: "Editor" Item: "Unselected Component Transparency".

**Comment by BenRQ** [comment]
OK I can do a new option menu, it should not be too much work.
How do you see that in the menu though ?

Redwolf you were talking about Heading and item, there would also be through button like "very" "a little" "not so much".

I welcome any help on design and text proposal :)

**Comment by antontimmermans** [comment]
What about this:
![optionsmenu](https://user-images.githubusercontent.com/42072372/48934286-a3644d00-ef03-11e8-8518-b6ceb29aa647.png)
Used these snippets from your own pictures:
![transparency2](https://user-images.githubusercontent.com/42072372/48934651-394ca780-ef05-11e8-9ffd-c6b4bf28581f.JPG)
![transparency3](https://user-images.githubusercontent.com/42072372/48934658-3c479800-ef05-11e8-87c5-fbac6ed8ad50.JPG)
![transparency4](https://user-images.githubusercontent.com/42072372/48934666-3f428880-ef05-11e8-8029-3605da18a389.JPG)

**Comment by BenRQ** [comment]
It's done.
Please share your translation here if you want the text for "Editor transparency" in your own language.

![image](https://user-images.githubusercontent.com/40794717/49109739-c9834780-f28b-11e8-89d2-00433cec355c.png)

Also please tell me if you think the UI presentation is not good enough.

**Comment by antontimmermans** [comment]
Thumbs up!

Minor Remark: both words of "Choose Language" start with a **C**apital **L**etter. It looks better if you do the same for "Editor **T**ransparency".

As for translations. I never tried different language settings so I don't know how the menu behaves for the words "Options", "Choose Language", "Music" and "Effects". If they get translated, then do the same for "Editor Transparency" to make it more consistent.

**Comment by redwolf2** [comment]
Editor Transparency in german is "Editortransparenz"

**Comment by zcaalock** [comment]
Przeźroczystość edytora = Editor Transparency (polish language)

**Comment by antontimmermans** [comment]
I used Google translate for the remaining languages and had some of them confirmed by my colleagues.

Spanish: **Transparencia del Editor** <- confirmed by Spanish Colleague)
Portugese: **Transparência do Editor** <- me and my Spanish both agree this could be right :) 
Italian: Editor Trasparenza -> My italian Colleague felt uncomfortable with this google translation and suggested: **Modifica Trasparenza**
French:  **Transparence de l'éditeur** <- according to colleague who worked 3 yrs in France, it is not wrong
Chinese: **编辑透明度** <- confirmed by Taiwanese Colleague
Czech:  Transparentnost Editoru  -> but my Czech colleague said **Průhlednost Editora** was better

**Comment by BenRQ** [comment]
Hi @antontimmermans 

Thanks a lot for the translation!

[(sorry) I'm French](https://www.sorryweare.fr) by the way, so for French, "Transparence de l'éditeur" means that the whole editor is transparent which would be weird.
"Components Transparency in the editor" would be the right meaning, but that's too much text.
I would keep "Transparence éditeur" for French.

For the Italian, Spanish and Portugese (latin languages) it's probably the same thing, so I think we need to say Editor transparency without the pronouns.
Also for Italian proposal, as it is not obvious where this setting is applied, I think we need to keep "editor" in the title.

It's not so important anyway, but better do it right the first time :)

**Comment by BenRQ** [comment]
I'm closing this issue, as the feature is fully implemented and committed, and to keep track of progress.

But it's still possible to discuss translation improvements, so feel free to bring new proposal / remarks.
