### ISSUE TITLE
Repeated scenario?

### ISSUE THREAD

**Issue by newusergettingnuts** [NPBruce/valkyrie#951]
### Description of Problem or Question

En la pajareria is listed twice? Is that right?

![image](https://user-images.githubusercontent.com/44534194/48665618-c4a2e480-ea90-11e8-8587-68613ab28ae1.png)

### Attach Save, Quest or Scenario
Saves:  
%appdata%/Valkyrie/MoM/Save  
%appdata%/Valkyrie/D2E/Save  
Quest:  
%appdata%/Valkyrie/D2E/Editor  
Scenario:  
%appdata%/Valkyrie/MoM/Editor

**Comment by newusergettingnuts** [comment]
never mind close. it was duplicated somehow but is fixed now.

**Comment by scrubbless** [comment]
The scenario was an older version hosted on the Valkyrie repo. The author published it to his own repo and I added it. I forgot to remove the old one!
