### ISSUE TITLE
Anyone knows a way to obscure part of the tiles without using layers?

### ISSUE THREAD

**Issue by newusergettingnuts** [NPBruce/valkyrie#953]
### Description of Problem or Question

i was wondering if theres a way to obscure a tile or part of the tile to allow:

1- investigators entering removing the obscure tile with for example some kind of light?
2- Another example would be for the group investigating outside the mansion and upon entering remove the obscured part.

something like this? 

![image](https://user-images.githubusercontent.com/44534194/48800426-7daf2c00-ece8-11e8-9961-3b06cfefbb29.png)

### Attach Save, Quest or Scenario
Saves:  
%appdata%/Valkyrie/MoM/Save  
%appdata%/Valkyrie/D2E/Save  
Quest:  
%appdata%/Valkyrie/D2E/Editor  
Scenario:  
%appdata%/Valkyrie/MoM/Editor

**Comment by scrubbless** [comment]
Not that I know of natively.

It is possible to create your own tiles, but it's a very manual process.

**Comment by newusergettingnuts** [comment]
> Not that I know of natively.
> 
> It is possible to create your own tiles, but it's a very manual process.

hey thats a good idea! 

i have no problem at all with manual process, i guess you mean:

a) manually  obscuring tiles and saving them.-
b) Saving/Locating them in the same reservoir where the rest of the tiles are located?
c) Then i can pick the obscured tile and with and entry event locate the normal tile?

Still i have no idea where to find or put my special tiles? Its on my reservoir or valkyre official reservoir??

thanks in advance!

**Comment by BenRQ** [comment]
What you are describing @newusergettingnuts would not work, tiles are embedded in the app, not in the scenario.
So your scenario would try to load not existing tiles for other players.

Scrubbless is referring to UI element I guess, or something else that I don't know of.

**Comment by newusergettingnuts** [comment]
> > still i dont know if it shows this way just for me or for anybody that plays the scenario
> 
> Yes, only you would see the change.
> Other would just see the normal tile

how about obscuring all existing tiles and having both versions (obscured and unobscured) within the app for a new Valk version?? 

you think it is possible? that way maybe within the index we can put another index as obscured tiles for people to pick??

I see great potential with something like that but maybe its just me and its a waste of time.

**Comment by newusergettingnuts** [comment]
bahh nevermind...a thing like this will need also the physical tiles also obscured and that is impossible.

close

**Comment by BenRQ** [comment]
True !  :P 
Closing
