### ISSUE TITLE
Available languages in scenario selection? Enhancement

### ISSUE THREAD

**Issue by newusergettingnuts** [NPBruce/valkyrie#957]
### Description of Problem or Question

something like this??
![image](https://user-images.githubusercontent.com/44534194/48958515-5a7dba00-ef3e-11e8-9dc8-99b49cb9602b.png)

**Comment by BenRQ** [comment]
Yes, it's planned along with: 
 #938 
 #832

Target is 2.2 but we haven't started working on this yet.

**Comment by redwolf2** [comment]
How about: Fun with flags

**Comment by BenRQ** [comment]
@redwolf2 we will ask Sheldon Cooper :)
And I'm sure those guys play MoM with Valkyrie!

**Comment by BenRQ** [comment]
This feature is now fully implemented and merged in 2.2. Test version coming soon.
Please open a new ticket if you find an issue in the test version provided.
