### ISSUE TITLE
Add Expansion Indicator to Scenario Selection Screen

### ISSUE THREAD

**Issue by AdamGEmerson** [NPBruce/valkyrie#958]
### Description of Problem or Question
There should be a way to see which expansions each scenario in the downloader require.

### Valkyrie Version
2.1.3

### Body

I just found out about this awesome software (thanks Bruce!) and before I get into making my own scenarios I would like to try a few of the ones others have made.  I downloaded a few scenarios but then realized that I had expansions enabled in the options.  Since I only own the base game I'm now left wondering which of the downloaded scenarios require pieces I don't own.

I'm thinking this should be relatively straight forward to add as tiles are already sorted by expansion in the editor.

Forgive me if I am missing something.

**Comment by BenRQ** [comment]
Hi Adam,

As explained by Scrubbless the information for scenarios is already in the "select scenario" screen, but you need to download the scenario first.

I'd like to improve the download / selection scenario screens to have everything in one single screen: languages, expansions informations, updates ... and also to make download a lot faster.
So you would have all informations, even before download scenarios.

This is related to other ticket : #938  #832 #957

**Comment by BenRQ** [comment]
This feature is now fully implemented and merged in 2.2. Test version coming soon.
Please open a new ticket if you find an issue in the test version provided.
