### ISSUE TITLE
Name and class strings are off on Mac Os

### ISSUE THREAD

**Issue by J-Iszatt** [NPBruce/valkyrie#960]
Hello Devs,

And first of all thank you so much for this wonderful project.
I am writing to you, since Valkyrie in combination with Descent 2 acts strange on Mac OS High Sierra (10.13.6).

Upon starting a quest and selecting heroes, their names are all written with underscores instead of spaces eg. "AVRIC_ALBRIGHT" or "LEORIC_OF_THE_BOOK".
The same applies for the hero class selection, where "CLASS_KNIGHT_NAME", "CLASS_THIEF_NAME", etc. is displayed instead of the actual class-name (are the names and classes supposed to displayed in capital letters?).

I was using the 2.1.3.dmg installer for Mac OS and compared it with the 2.1.3 Windows .exe and the Android .apk of the same version. Both of them were able to display names and classes correctly, which makes me belief that this is just a oddity of MacOS's naming convention.

Regards

J

**Comment by BenRQ** [comment]
Hi J,

OK thanks for the feedback, I guess we have an issue with 'path' creation on Mac.
Unfortunately I don't have a mac to test, but maybe we can find a way to provide a fix.

Could you please share the path to your imported directory ?
I mean the path if you try to access from your file explorer.

For reference it is C:\Users\yourname\AppData\Roaming\Valkyrie\D2E\import\text\Localization_XX.txt on Windows.
It should be something like this for Mac :  /Users/yourname/.config/Valkyrie/...

**Comment by alvaromunoz** [comment]
Testing on:
MacOS Mojave (10.14.2)
MoM 1.7.0
Valkyrie 2.1.5

This error does not appear to happen any more:
<img width="1280" alt="captura de pantalla 2019-01-03 a la s 5 21 45 p m" src="https://user-images.githubusercontent.com/2722773/50659675-22758800-0f7c-11e9-96a7-b55154046ef8.png">

**Comment by redwolf2** [comment]
Probalby the problem is an old Valkyrie version in combinition with an old, not up-tp-date ffg game.

**Comment by J-Iszatt** [comment]
Hi devs and thanks for the quick reply!
Sorry that i didn't reply earlier, i was kind of stressed lately..

I can confirm that it's working for me now, too!

Today I updated Road to Legend and tried reimporting the assets into the Valkyrie verison i had (2.1.2 or 2.1.3 ). With this not working, i updated to Valkyrie 2.1.5, which did the import as well as propper displaying!

Only to let you know, i was running the lattest available versions of ffg and Valkyrie available at that time and was still facing these problems.

Anyways thanks again! Great project, I really appreciate the hard work
