### ISSUE TITLE
Design of scenario explorer v2

### ISSUE THREAD

**Issue by BenRQ** [NPBruce/valkyrie#961]
This issue should be used to discuss the new design for the new "scenario explorer" screen.
Root task is  #962

This design includes two parts: 
1) The graphical part : pictures, background, color thema, button graphics / color (all free of rights of course). 
2) The placement part : where to place all the requested information

**In more details :**
1) My initial idea is to have a dark background, ( dark wood for example), with quests listed on scrap of old scroll of paper.
Like this (please use your imagination):
![image](https://user-images.githubusercontent.com/40794717/49312724-4d843c00-f4e5-11e8-9149-f383bfd1ad35.png)

2) The new design should Display all the following:

 Info:
   - Picture, scenario title, duration, average duration, avg victory, difficulty, users rating
   - languages
   - author
   - expansions used / expansions missing
   - marker for scenario already played 

 Buttons:
   - Download/Play, Delete, Update

Feel free to add your proposal, or suggestions if you think anything is missing.
Any help on the design part, to provide image to integrate is very welcome.

**Comment by redwolf2** [comment]
Great idea. Maybe structure it in a way, that both game types can have different backgrounds.

**Comment by antontimmermans** [comment]
I am not good with graphical tools but i'll try to describe it:

In one of the corners you can put an 'settings' icon. That icon gives a pop-up menu that lets you choose the following:

- Scenario languages: with tickboxes for each language that the player can sellect; **Multiple boxes** can be selected. The effect of selecting a tick box(es) is that a scenario containing the language(s) will appear in the list.
- Sorting: Choose in which way the list is sorted. Select **only one option** out of:
  - A-Z; 
  - Difficulty (easy to difficult); 
  - Duration (short to long).
  - User rating 
  -  In case of sorting ends up with same primary sorting keys in the list: 
     - Difficulty level sorting;  then the second key to sort on would be duration, third key: A-Z
     - Duration level sorting;  then the second key to sort on would be difficulty, third key: A-Z
     - A-Z sorting; then the second key to sort on would be difficulty,third key: duration (<- default sorting)
Note: that I didn't include the reverse selection (z-a; long to short, .. etc). I personally think that would be overkill and too much detail.
Note: An additional switch could be added to selectwriters rating/user rating: witch results in:
scenario duration vs. average duration
scenario difficulty v.s. average win 

Further setting that affect the scenario overview list is the available expansions which are set elsewhere in the main menu. You can choose to apply this selection as an extra filter on the list to only display the scenarios that MUST have a specific expansion and scenarios that 'add variation'.  

Back to the scenario overview list:
List all available scenario's that match the sorting criteria downloaded or not. the list then has two parts that will be sorted according to the sorting setting in the options menu. Top half list contains all the downloaded titles (sorted). Bottom half shows all available (but not yet downloaded) titles, also sorted according to the setings.

Each 'title lable' looks roughly the same as current layout with Picute and Title. I personally would  not include the authors name because it (should not) be a selection or filter criterium. Also the author name (or multiple authors names) can be one or more lines text wich makes it very difficult to keep it displayed nicely in a structured way.
Below the title  you can put the Duration and the difficulty. 

The most right 15% of the lable is reserved for the following:
- Top right : a button that displays the one of the following text
  -  PLAY if the content is downloaded and no update is available 
  - UPDATE if the scenario is downloaded , but an update is available
  - DOWNLOAD If the scenario is not downloaded yet (which would typically be seen in the bottom part of the list with the not downloaded scenarios).
- Mid right: Delete (only visible if the content is downloaded (which means only in the top part of the list)
Bottom right: User feedback:
- rating
- average duration
- average win ratio 

An alternative to handle the expansions in the list is to not filter on the expansions but to add icons for the expansions on the bottom of a scenario and then use color to display its status:
- green icon: required (or adds variation) and available
- Red icon: required and NOT available
- Black icon: Not required but adds variation
- Grey icon: Not required, does not add variation

Does this help?

**Comment by BenRQ** [comment]
Hi @antontimmermans, thanks a lot for sharing your thoughts on this, a lot of great ideas :)
I will this mature a bit and get back to it in while with actual implementation.

@redwolf2 shared this on Discord, I put here so I can find it again later: 
![image](https://user-images.githubusercontent.com/40794717/49965334-2da93b00-ff1d-11e8-801b-c1ab715ea5a3.png)



I like the idea of using a maximum of the space on this screen.

And I know @scrubbless wants to share his thoughts on this too :)

**Comment by redwolf2** [comment]
All suppored languages don't need to be displayed on the item. Reserve a max space of 6 flags. Always show the first flag as the language set in the options, then English if available. Then up to 4 more languages. If there are still more languages, show a + symbol. If the user clicks on the plus symbol a details popup will show the rest of the scenario information, including all languages.

**Comment by BenRQ** [comment]
Here is the current status of implementation : 
 - all features are working: sort, filter, download, update, play
 - all the informations are now displayed 
 - delete button should be added somewhere but I don't want it too close to the play button (for those using android with big fingers)

Still some work on the graphical side:
 - play/download/update button to design
 - fix difficulty and rating
  
I've selected your solution 3 @antontimmermans for design, which was quite close to my original design.
Your other designs were difficult to implement because of the text size but I took some ideas.

For the buttons, I've spent some time on it, but can't work out something nice.
I thought of wood button, wax seal button, basic black button ... I didn't manage to make something good.
Please help if you can :)

![image](https://user-images.githubusercontent.com/40794717/50744194-2970f480-1221-11e9-8c15-5cf630fa0e4b.png)

**Comment by BenRQ** [comment]
Loading time for this screen is a bit more than 2 seconds on my PC.
I'm expecting more on Android of course, but remains to be tested.

And there are still a lot of bugs to fix I'm sure :)

**Comment by antontimmermans** [comment]
Looks good @BenRQ looking forward to test it.

As for button options I gues the wax seal button would match the paper contract style. 
I am not good a graphical designs but may have a go at it later this week. 

Alternatively it could also be made to look as if it is 'burned into the paper". That maybe more easy to make. That doesn't have to look as "organic" as wax. In this case it can be 'straightforward' buttons but black-ish/brown-ish borders.

**Comment by antontimmermans** [comment]
What about burning a hole in the paper and place button text in it? Example:
![paperbarburnholeexample](https://user-images.githubusercontent.com/42072372/50887450-799fb080-13f3-11e9-9528-f0c350502a03.PNG)

Used this image for it:
![burnedholenobg](https://user-images.githubusercontent.com/42072372/50887525-ad7ad600-13f3-11e9-9732-c2be9b3077f3.png)

**Comment by BenRQ** [comment]
I like this idea of burnt paper very much :) 
I'd rather use a picto rather than a text though, just to avoid the translation / size of text headache.

**Comment by antontimmermans** [comment]
If you want to go for a complete burnt paper theme then maybe this could serve as scenario background:
![burntpaper](https://user-images.githubusercontent.com/42072372/50975173-34f84000-14ed-11e9-9f9a-2bf10d1862d7.png)

And optionally this could serve as a border around the scenario image:
![bigburnedhole no bg](https://user-images.githubusercontent.com/42072372/50975308-87d1f780-14ed-11e9-948e-b31d44371a9d.png)
This probably would require some rework. Currently this last picture has no background color but the inside is (moslty) white. If you want to use this image then let me know and what requirements you have for it.

The combination of all of the above would look like this (yes, i am on fire ;-):
![image](https://user-images.githubusercontent.com/42072372/50975643-5e659b80-14ee-11e9-9186-79fbf8866f2b.png) **_### BTW I still think someone with better picture edit skills then me can make it look much better. So graphical designers , please stand up!_**

QUESTION:
Current Valkyrie download system also allows for deletion of a scenario from the local system. In the 3 examples I tried to add this function with the 'X' button. In your latest example I see no hint of a delete button. Do you intend to keep deletion of a scenario as an option in the scenario explorer ('selection-scenario-paper' pull the pin in the image for example), or are you going to put that in a separate menu (settings menu)?

**Comment by BenRQ** [comment]
I think I'll move the delete button in the quest details screen.
There is no need to have it in the quest selection screen, which is already having a lot of information.

**Comment by BenRQ** [comment]
Technical version is here if some of you want to test it : https://we.tl/t-ZSVyviSR23

Please note it is not synchronize with all the fix available with 2.2, so don't use it for anything else than for testing the new scenario explorer.

@NPBruce, I've been searching for this kind of things, but didn't manage to find a tutorial or anything to do this (yet).

I was going to try to do it with mask2D and two texts on top of each other, but it may be too complex to realize for such a simple thing.

**Comment by antontimmermans** [comment]
inital startup:
start scenario
---> scenario list visible
download scenario-> dowin loading-> back to scenario list
set fliter on show only english
select OK
-----> Filter applied to list
Select BACK
->Bug:
select start scenario
---> black screen
click filter
click OK
---> Scenario list vissible
after restarting the application the behavior repeats as mentioned above from ->bug

**Comment by redwolf2** [comment]
Maybe this is less complex to do:

1. Create Texture
2. Draw left part of this image to it
![tentacles](https://user-images.githubusercontent.com/4141621/51136898-dfe66200-183d-11e9-8f9f-f95be9fe7a3d.png)
2. Draw right part of this image to it (you can't see it because)

![tentacles_white](https://user-images.githubusercontent.com/4141621/51136900-e07ef880-183d-11e9-9878-ad7d33daab6f.png)

3. Apply to UIElement

**Comment by NPBruce** [comment]
If you have a texture with the font prerendered you don't have to do step 3.

**Comment by BenRQ** [comment]
I tried to use TextMesh but didn't manage to get something working.
So I used Mask2D and created a child of UIElement named UIElementCropped.

It now works like a charm :)

![image](https://user-images.githubusercontent.com/40794717/51270398-126e9700-19c5-11e9-9f64-f1a7c2fec129.png)


I've been testing Descent a bit, and see that everything is working also on that side.
Except for expansions icons, as I don't think they exist.
@redwolf2 @NPBruce Do you know if there is an equivalent to MoM symbols in Descent ?

![image](https://user-images.githubusercontent.com/40794717/51270190-95dbb880-19c4-11e9-883c-473abe2377b1.png)

If it does not exist, I may just replace symbol by a marker or a word "expansions" in red, to show that expansions are missing.

**Comment by redwolf2** [comment]
The default Gara_Scenario_Desc.ttf contains some symbols for it, but not all. I also extracted the font from the 1.7.0 assets, but it does not contain new symbols.

There is this: https://boardgamegeek.com/filepage/99055/font-containing-descent-symbols

http://tools.fantasyflightgames.com/static/fonts/Gara_Scenario_Desc.ttf
http://tools.fantasyflightgames.com/static/fonts/Windl.ttf

But it is probably not complete with all symbols.
Maybe we could use the shortcut names under content\D2E?1111

**Comment by BenRQ** [comment]
For reference :  
LoR = DJ04_LabyrinthOfRuin
LotW = DJ03_LairOfTheWyrm
MoB = DJ40_MistsOfBilehall
MoR = DJ21_ManorOfRavens
SoN = DJ07_ShadowOfNerekhall
TCTR = DJ44_ChainsThatRust
TT = DJ05_TheTrollfens
CKAoD = AoD
CKD1E = D1E
CKDQ = DQ
CKPromo = Promo
CKToI = ToI
CKWoD = WoD
BotW = DJ31_BondsOfTheWild
CoD = DJ27_CrownOfDestiny
CotF = DJ28_CrusadeOfTheForgotten
GoD = DJ29_GuardiansOfDeephall
OotO = DJ26-OathOfTheOutcast
SoE = DJ34_ShardsOfEverdark
SotS = DJ33_StewardsOfTheSecret
ToC = DJ32_TreatyOfChampions
VoD = DJ30-VisionsOfDawn
DJ12 = DJ12_AlricFarrow
DJ43 = DJ43_ArdusIxErebus
DJ18 = DJ18_Ariad
DJ10 = DJ10_Belthir
DJ20 = DJ20_BolGoreth
DJ14 = DJ14_ElizaFarrow
DJ41 = DJ41_Kyndrithul
DJ13 = DJ13_MerrickFarrow
DJ25 = DJ25_GarganMirklace
DJ19 = DJ19_QueenAriad
DJ16 = DJ16_Raythen
DJ22 = DJ22_RylanOlliven
DJ17 = DJ17_Serena
DJ35 = DJ35_Skarn
DJ09 = DJ09_Splig
DJ24 = DJ24_TristayneOlliven
DJ15 = DJ15_Valyndra
DJ23 = DJ23_Verminous
DJ11 = DJ11_Zachareth
DJ42 = DJ42_Zarihell

**Comment by BenRQ** [comment]
I found SVGs for the boxed expansions and hero and monsters pack: http://descent2e.wikia.com/wiki/Template:ValidateExpansionLogo
I created a font based on those SVG.

But for the Conversion kit, I could not found any SVG or fonts  even though symbols do exists:
https://boardgamegeek.com/thread/1103567/document-defining-2nd-edition-symbols-card-setsexp
Please help, if you know where I can find those.

For the rest of elements, all the DJXX are lieutenant packs, and they do not have specific symbols I think.
I can just ignore those I guess, they should not be a requirement for a scenario, could they ?

**Comment by BenRQ** [comment]
OK cool :) Do you create those SVG manually or do you have a tool to make a vector image from a bitmap?

**Comment by redwolf2** [comment]
Manually in inkscape. That process creates smaller SVG sizes.

**Comment by BenRQ** [comment]
I've moved the expansions symbols under the quest name.
Seeing the number of expansions on Descent, it's clear there was not enough space there.
And new expansions are still coming for MoM so it's future proof now :)

This gives more space for the picture, and less space for the synopsis (only one line instead of 2).

I think it looks better, I hope you think so too :)

![image](https://user-images.githubusercontent.com/40794717/51433453-a309d900-1c4a-11e9-9c9b-88986eb30dbe.png)

Still a lot of pictures missing in Descent quests list though, it's too bad, it does not give a good impression.

![image](https://user-images.githubusercontent.com/40794717/51433472-0eec4180-1c4b-11e9-93ed-ddbac2d16a21.png)

**Comment by redwolf2** [comment]
We could add a default image, where there is no image

**Comment by BenRQ** [comment]
Yes I could use the Valkyrie picture there, good idea.

**Comment by antontimmermans** [comment]
The logo is OK but the shadow doesn't match and the pin doesn't make much sense like this.
Maybe if you give it a solid background.

Where can I find the logo image? I'll try to play with it a little to make it look burned into wood,  stamped on paper, Sepia photograph with burned edges.. or something like that if that is OK with you.

**Comment by BenRQ** [comment]
Here you go : https://github.com/NPBruce/valkyrie/blob/scenario_explorer_v2/unity/Assets/Resources/Sprites/scenario_list/default_quest_picture.png

**Comment by antontimmermans** [comment]
Made one with Valkyrie logo:
![burnedinwoodvalkrie](https://user-images.githubusercontent.com/42072372/51524866-59c6ae80-1e2f-11e9-975e-dbd4c8caf565.PNG)

And with the elder sign i found earlier in this thread:
![burnedinwoodeldersign](https://user-images.githubusercontent.com/42072372/51524874-5d5a3580-1e2f-11e9-9aea-1ca7efb69efa.PNG)

**Comment by redwolf2** [comment]
Very nice

**Comment by BenRQ** [comment]
Very cool, you are way better than me at this! 
So ... which one should we use :)

**Comment by BenRQ** [comment]
If you want to try out some improvement at the other pictures, they are all here : https://github.com/NPBruce/valkyrie/tree/scenario_explorer_v2/unity/Assets/Resources/Sprites/scenario_list
You can even propose completely different pictures, you just need to keep the same aspect ratio.

**Comment by BenRQ** [comment]
![image](https://user-images.githubusercontent.com/40794717/51562254-a939c880-1e89-11e9-90b3-a35f8f98afec.png)

**Comment by antontimmermans** [comment]
With the power of... powerpoint :D. 
For me both images would be fine but I have a slight preference for the Valkyrie logo now I see it in the end result.

1. The elder sign is already used in this overview for the dificulty score.
2. I am guessing that in Decent some scenarios also don't have a picture. The logo can also be used there, elder sign probably not.
3. I would use any excuse to show of the logo of this great app. :)

**Comment by redwolf2** [comment]
We could use Howards original elder sign instead:

https://github.com/redwolf2/valkyrie_content_creation_kit_mom/blob/master/misc/elder_sign_original.svg

**Comment by BenRQ** [comment]
I don't know if we should count points, but my vote is for the Valkyrie sign. :)

Using the Valkyrie sign helps to understand that it is a replacement picture and it works for both Descent and MoM (and other if they come).


![image](https://user-images.githubusercontent.com/40794717/51571997-4570c900-1ea4-11e9-9809-1572976759d0.png)

**Comment by BenRQ** [comment]
This feature is now fully implemented and merged in 2.2. Test version coming soon.
Please open a new ticket if you find an issue in the test version provided.
Or if you want to propose additional change in design.
