### ISSUE TITLE
MoM 1.7.0 - broken import on Android

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#964]
### Description of Problem or Question

The latest version of the official app has broken the import function of Valkyrie.

I just ran the reimport on my Valkyrie and after "importing" it goes back as if the important was not run.
![screenshot_20181201-133244_valkyrie](https://user-images.githubusercontent.com/32058089/49328777-d9da4180-f56d-11e8-9ea7-5641454eed50.jpg)

### Valkyrie Version
2.2

**Comment by BenRQ** [comment]
Strange, it works for me in 2.2 and 2.1.3

I have v1.7.0 (740) on steam.

**Comment by BenRQ** [comment]
Can you please share the logs of Valkyrie ? : %USERPROFILE%\AppData\LocalLow\NA\Valkyrie

**Comment by scrubbless** [comment]
Android 1.7.0 (821)

**Comment by NicolaZee** [comment]
Well done on fixed the bug so quick and a big thanks  from me! :)

**Comment by scrubbless** [comment]
Yeh thanks BenRQ

**Comment by OPettz** [comment]
I can confirm that I also have the same importing issue on my Fire 7 - of course using the android file

**Comment by LordPyrex** [comment]
I wish I could. I'm not much of a coder. Back in the day I was doing wikis to assist with people jumping in to using Valkyrie. I can help with any new how-tos we might need.

**Comment by BenRQ** [comment]
I have confirmed my first assumption, something is wrong with the package extractor on Unity.

In \libraries\FFGAppImport\AssetImport\Unity_Studio\Font.cs:61
On Windows 10 the value is 0
On Android it's ‭0x3F800000‬

Maybe something related to size of object, compiler or endianness ...
I'm still investigating.

**Comment by BenRQ** [comment]
I have disabled the font export, and now the import is working just fine.

But unfortunately, the sprite placement is different on Android.
This is a very bad news as it means we need to update the sprite system to support a different placement mechanism between android and windows.
And of course we need to do the placement of sprites again.

Here is the old (first) and new token placement on the texture file for Android.

Old DDS texture
![image](https://user-images.githubusercontent.com/40794717/49552390-9ed06900-f8f3-11e8-9ee4-1ee9aedc94f0.png)

New PVR texture on Android for MoM 1.7.0
![image](https://user-images.githubusercontent.com/40794717/49552379-8ceec600-f8f3-11e8-96a6-dec565ed72a2.png)

**Comment by redwolf2** [comment]
The tokens have this image format ATM:

```
[TokenYellowWoman]
image="{import}/img/SpriteAtlasTexture-ATLAS_FEATURES_CORE (Group 0)-2048x1024-fmt12"
image2="{import}/img/SpriteAtlasTexture-ATLAS_FEATURES_CORE (Group 0)-2048x1024-fmt47"
x=130
y=520
height=130
width=130
```

We could introduce x2 and y2 in order to overwrite that parameter on the second resolved image if it is used.

```
[TokenYellowWoman]
image="{import}/img/SpriteAtlasTexture-ATLAS_FEATURES_CORE (Group 0)-2048x1024-fmt12"
image2="{import}/img/SpriteAtlasTexture-ATLAS_FEATURES_CORE (Group 0)-2048x1024-fmt47"
x=130
x2=758
y=520
y2=130
height=130
width=130
```

This this continues, I could create tokens in a similar design if necessary.

**Comment by BenRQ** [comment]
Version 2.1.5 is available with import and tile fix
