### ISSUE TITLE
HELP: my scenarion does not load in the editor anymore

### ISSUE THREAD

**Issue by antontimmermans** [NPBruce/valkyrie#965]
### Description of Problem or Question
My scenario does not load anymore in the editor of Valkyrie.

I creating my new scenarion with the latest test version that @BenRQ made available to be able to use the OR  in tests. Since there is a lot of editing involved, I edit some of the tests and events in a code editor (not in valkyrie). 
To make sure I get the syntaxt right, I  first create an event using the valkyrie editor, save it to event.ini and localisation.enlgish.txt. Then i look-up the event, copy it and change the name, text or values to make slight variations on that event, and I save those files again.

Then, when I reload the scenario in Valkyrie, I can use the newly created events.

This worked fine until now, I propably made some copy mistake introducing a syntaxt error using this manual editing (at least that is what i think is what happened. But i cannot find the bug. 
Is there i way yo debug/find the scenario when it is loaded?

### Valkyrie Version
Latest test version

### Attach Save, Quest or Scenario
Saves:  
%appdata%/Valkyrie/MoM/Save  
%appdata%/Valkyrie/D2E/Save  
Quest:  
%appdata%/Valkyrie/D2E/Editor  
Scenario:  
%appdata%/Valkyrie/MoM/Editor

**Comment by BenRQ** [comment]
The error is in: 
[EventGhostPlaceLadyLobbyA] and [EventGhostPlaceLadyLobbyB]
VarOperation:Story,==1  is missing a ','

dichotomy is your friend if this happens to you again :)

I will add a log there so it's easier to debug for you next time.

**Comment by antontimmermans** [comment]
Thx a lot @BenRQ  That was it! 
I owe you one.
