### ISSUE TITLE
MoM 1.7.0 - Broken image (sprites) on Windows

### ISSUE THREAD

**Issue by BenRQ** [NPBruce/valkyrie#966]
With the latest version of MoM on steam, I see that the sprites are not valid anymore.
I'm talking about the token and non playable characters pictures.

Can someone (who has not done the update), share with me the two following files ?

In directory %USERPROFILE%\AppData\Roaming\Valkyrie\MoM\import\img\

SpriteAtlasTexture-ATLAS_FEATURES_CORE (Group 0)-2048x1024-fmt12.dds
and Atlas_Main.dds

For the technical explanation, I think FFG changed the tile placement on the picture.
![image](https://user-images.githubusercontent.com/40794717/49334101-2acd5280-f5cd-11e8-85db-24181f566a60.png)

**Comment by BenRQ** [comment]
related to #868

**Comment by scrubbless** [comment]
Can't link them on GitHub doesn't like the file format.

I'll share a folder on google drive to you @BenRQ

**Comment by BenRQ** [comment]
Fix is now available, new hotfix version incoming
