### ISSUE TITLE
Bug: NULL pointer dereference because valkyrie will import Tokens with no images

### ISSUE THREAD

**Issue by asn-d6** [NPBruce/valkyrie#967]
### Description of Problem or Question

Hello people,

I'm just playing around with valkyrie for fun using a995c2ce from development-2.2 branch as my HEAD.

I noticed that when I tried to make a scenario and I was trying to add some tokens, some tokens did not have images (in particular darkness and fire). After I tried to select those (because why not), the scenario builder crashed with a NULL pointer dereference:
```
NullReferenceException: Object reference not set to an instance of an object
Quest + Token..ctor(.Token questToken, .Game gameObject)(at Assets / Scripts / Quest / Quest.cs:1522)
Quest.Add(System.String name, Boolean shop)(at Assets / Scripts / Quest / Quest.cs:1063)
```
which is basically because:
```
            Texture2D newTex = ContentData.FileToTexture(game.cd.tokens[tokenName].image, texPos, texSize);
```
returned NULL because `game.cd.tokens[tokenName].image` was NULL in the case of darkness and fire.

So I'm not entirely sure what happened there, but it seems like Valkyrie failed to import the darkness and fire images?

PS: Thanks a lot for Valkyrie! A very fun project!

**Comment by asn-d6** [comment]
Please see my PR for a patch that blocks the import of tokens without images: https://github.com/NPBruce/valkyrie/pull/969

IIUC, it's basically useless to import those tokens anyway since we cant use them, and they will also trigger a NULL ptr dereference if used....

BTW, any idea what happened during the import that made it fail?

**Comment by asn-d6** [comment]
Here is how the import dialog looked like FWIW.
![unitybug](https://user-images.githubusercontent.com/3611450/49348699-8d971a80-f6af-11e8-9121-dbd626086552.png)

**Comment by BenRQ** [comment]
Hi @asn-d6,
thanks for the PR, I'll merge into the dev branch, it's good to have a bit more stability 👍 

The problem you describe here is related to #966 MoM 1.7.0 - Broken image (sprites) on Windows
I've fixed it yesterday.

So if you have cloned the branch, you need to take this commit : https://github.com/NPBruce/valkyrie/commit/35842cfaf891b746ec473c8375ff795f8fb9c522

If you already have this patch, then you need to upgrade MoM version on steam.

**Comment by BenRQ** [comment]
If you feel like playing a bit more with Valkyrie code, I can suggest some more accessible change request that have been requested:

#959 Code puzzles question. Specific codes 
#943 add previous/next button on events,quest etc.

Now feel free to work on whatever you want, just tell us so we are sure not to work on it at the same time :)

I'm available to help mostly through discord.

**Comment by asn-d6** [comment]
Thanks for the ticket suggestions. That's really helpful :)

**Comment by BenRQ** [comment]
Fix is merged, closing.
Thanks @asn-d6
