### ISSUE TITLE
Saved games don't check against quest changes

### ISSUE THREAD

**Issue by NPBruce** [NPBruce/valkyrie#97]
If the quest/scenario has changed the save is no longer valid, but it will try to load anyway.  Perhaps save a hash of the quest with the save?

**Comment by eorahil** [comment]
the idea is that an scenario can be translated without editing the rest of it so a saved game can work for modified scenarios is the scenario changes are only translations. A scenario will have a localization file so the hash could be created from main file only.

**Comment by NPBruce** [comment]
Yep, I was think that (at least all ini data, as it is possible to have multiple).

**Comment by NPBruce** [comment]
New plan: include the whole quest in the save game (as zip).  Don't think we need to support changes mid quest and this way loading will always work.
