### ISSUE TITLE
Newbie Question

### ISSUE THREAD

**Issue by vendettarock** [NPBruce/valkyrie#972]
If you have multiple events with "StarRound" or "EndRound" trigger.
what is the order of execution?

Sorry for the noob question

**Comment by newusergettingnuts** [comment]
Hola vendeta. El orden es inicio del round y luego fin del round si colocas la variable test #round=numero de round podes ubicarlos en un round especifico.

**Comment by vendettarock** [comment]
Me refiero a que si tengo 3 eventos que se ejecutan al inicio de cada ronda, por ejemplo. ¿Cual es el orden en el que se ejecutan esos 3?

**Comment by newusergettingnuts** [comment]
Creo que van a  ocurrir todos los turnos del juego aleatoriamente. Llego a una compu y pruebo y te confirmo

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by newusergettingnuts** [comment]
La estructura por lo visto es 

Start round
Mythos
End round

Y los incluyen una primera ronda aleatoria y luego fijos, raro pero en mi caso se visualizan aleatoriamente y ya luego quedan fijos en esa primera selección. 

Prueba y error...que es lo que queres lograr a ver si hay alguna otra forma?

**Comment by vendettarock** [comment]
i mean
For example, If you have three events triggering at the end of the same round (with the Endround trigger). What of those events trigger first? 

Sorry for my english

**Comment by BenRQ** [comment]
I suppose it should be the same order as they appear in the event.ini file.

**Comment by vendettarock** [comment]
Thats it! but the execution begins from the bottom. The reorder tool works too, the bottom events goes first.
