### ISSUE TITLE
Import Content Descent 1.5.0 witk Valkyrie 2.1.4

### ISSUE THREAD

**Issue by vendettarock** [NPBruce/valkyrie#975]
Road to Legend is just updated with a entire new campaign, and now the import content option of valkyrie doesnt work anymore.

### Valkyrie Version
2.1.4 Windows

**Comment by BenRQ** [comment]
This is the same issue as #964

**Comment by BenRQ** [comment]
New version incoming soon

**Comment by BenRQ** [comment]
Issue fixed in version 2.1.5 (only tested on windows)
