### ISSUE TITLE
The Truth: portuguese translation

### ISSUE THREAD

**Issue by andrex47** [NPBruce/valkyrie#977]
### Description of Problem or Question
Here I go again on my own
Going down the only road I've ever known
Like a drifter, I was born to walk alone
But I've made up my mind
I ain't wasting no more time /o/

Morning gentlemen, i will begin translating the scenario The Truth, any help will be greatly appreciated, i will upload the files on google drive and it will be there for anyone to edit, you can access it on the link below.
https://drive.google.com/open?id=1OvPXqE4LDylVw2cq09JjYMJLlaUa7dHx

**Comment by andrex47** [comment]
[Localization.Portuguese.txt](https://github.com/NPBruce/valkyrie/files/2775817/Localization.Portuguese.txt)

**Comment by redwolf2** [comment]
@slycozzolino Can you integrate this?

**Comment by andrex47** [comment]
i made a mistake translating the conservatory word, now it is fixed
[Localization.Portuguese.txt](https://github.com/NPBruce/valkyrie/files/2819130/Localization.Portuguese.txt)

**Comment by slycozzolino** [comment]
Done
