### ISSUE TITLE
Issue/Bug: Aspect ratio problems / bug after changing a screen orientation causing a game breaking

### ISSUE THREAD

**Issue by chrismaliszewski** [NPBruce/valkyrie#980]
### Description of Problem or Question
I. The app is not suited for a vertical screen. The whole layout is destroyed. But it's not that big of a problem...
II. There is a major issue of the app which may prevent players from further playing their game if happens! 
I have a 2-in-1 notebook with a rotatable screen but the issue is replicable on a normal screen (read Scenario section). By mistake, I rotated my screen so instead of horizontal aspect ratio 16:9 I had a vertical width of the screen. After coming back to the horizontal view, the screen was cut and there was no way to change phases or go to Menu to create a save and reload the whole app.

### Valkyrie Version
2.15 (Windows 10 but presumably also other systems)

### Scenario to replicate:
-Start any scenario,
-Rotate your screen:
a) if you have a rotatable screen, change the orientation,
b) if you don't and you have Windows 10, click CTRL + ALT + arrows to change the orientation,
c) if you don't and you don't have Windows 10, use other technique to change the orientation.
-Go back to the original screen orientation.
-The screen will be cut.

### Suggestion
I. If possible, the game in a vertical orientation should be scaled to a specific resolution. If not, the orientation should be blocked and force a user to use a horizontal orientation, even on a desktop/laptop.
II. The issue could be resolved as suggested above: lock the orientation or scaling the window. The II. issue should be resolved as it may destroy someone's game as it was in my case.

**Comment by BenRQ** [comment]
Hi @chrismaliszewski ,

thanks for the bug report and sorry to hear your game got messed up.
If it's not too late, you can still leave the app and restart with your latest savegame.
Savegame is done automatically at every round.

For the issue : screen orientation is locked to portrait on Android, so it's not a problem on that platform.
I will check if we can lock it on Windows.

And I don't think it makes sense to support vertical orientation, it is a lot of work for no obvious benefit.

**Comment by chrismaliszewski** [comment]
You don't need to apologise; I started the scenario from the beginning and continued clicking tokens to reach my progress. 
I didn't know that the game is saved every round. It's nice to hear that!

I agree; supporting vertical orientation doesn't give players anything so if turning on a window scaling is not possible as a "one-click-thing", then locking the orientation will be the easiest and the best solution and it will be fine.

Have a good day!

**Comment by BenRQ** [comment]
If you have some time, I can share a test build with you, with a potential fix.
Can't test it myself as I don't have an ultrabook or a Windows PC with auto rotate.

Using Ctrl+Alt+ arrows seems to be something different, I won't be able to block that.

**Comment by chrismaliszewski** [comment]
Sure. I've never done it. How will you share it? Via email or a link?
Krzysztof Maliszewski
www:  http://www.krzysztof-maliszewski.pl/
e-mail: k.a.maliszewski@gmail.com


śr., 12 gru 2018 o 09:37 BenRQ <notifications@github.com> napisał(a):

**Comment by BenRQ** [comment]
By link, you don't need to share your email with all the spam bots :)

**Comment by chrismaliszewski** [comment]
Ok. I'll be waiting for the link.

What do you mean " Ctrl+Alt+ arrows seems to be something different"? You can't block it, is that right? 
I've just checked in the original MoM app, another Unity game GoHomeyoureDrunk and a game which is not made with the Unity engine. The issue may the the engine's problem as all but the last game have the same problem (even the original MoM). 
I think you could inform Unity developer's team about it and leave the CTRL+ALT+ARROWS issue as is. 

Still, let's try the fix of yours :).

**Comment by BenRQ** [comment]
Here is the link : 
https://we.tl/t-5hcwzD8saU

And yes the problems seems to be a Unity issue.

Solution was found here : https://stackoverflow.com/questions/34086474/enforce-landscape-orientation-on-windows-8-1-for-unity-project

It is referenced here : https://answers.unity.com/questions/1334691/windows-rotated-screen-and-resolution.html

**Comment by chrismaliszewski** [comment]
Fix works with the rotatable screen! The app stays horizontal no matter what I do (tested a few things to break the app).
The CTRL+ALT+arrows/changing screen rotation issue is still there but it isn't normal to change an orientation of a screen while playing so it isn't a big issue and it should be fixed by the Unity team, not you.

Thank you, BenRQ!

**Comment by BenRQ** [comment]
Thanks @chrismaliszewski, happy to hear that :)

I'll share this solution on the Unity post, it may help someone.
