### ISSUE TITLE
Custom Investigator Attacks

### ISSUE THREAD

**Issue by scrubbless** [NPBruce/valkyrie#981]
### Description of Problem or Question
I know this has been discussed before, the current implementation has some issues.

I can add Custom Investigator Attacks for a Custom Monster however if I click the + to add an event. There is no way to remove/delete it.

![image](https://user-images.githubusercontent.com/32058089/49814532-b8453b00-fd61-11e8-9ae8-b2ce618d3ed7.png)

Can we get a - button on those, at least in the short term until the system is revised?

### Valkyrie Version
2.1.5

**Comment by BenRQ** [comment]
Does it makes sense to have more than on attack of a type ?
Shouldn't we just remove the [+] button after the first investigator attack is created ?

**Comment by antontimmermans** [comment]
I had not thought of this before but it would be nice indeed if a scenario writer can have more influence of how the attack is done. I get a bit frustrated if you give an investigator with the highest strength the heavy weapon and then get instructed to test your lowest skill for example: {negotiation}.

A feature like this would allow the investigator to influence the fight using their 'better' skills. Example:
HEAVY WEAPON:
- {action} death from above: Raise the heavy weapon high above your head and bring it down with all your might--> test 3 {strength} -->success: weapon damage + test result
- {action} Hit: make a wild swing with your weapon --> test 2 {strength or agility} --> success: weapon damage
- {action} hit charge: charge forward, slamming your weapon into the monster--> test 2 {agility or strength or negotiation} --> success weapon damage and push back 1 space.
- {action} Bullseye: hit the monster right between the eyes--> test 2 {negotiation or will or observation} --> success weapon damage

This way there is still some randomness in the test, but it gets a bit more predictable from the chosen action what to expect.

I am not sure if this is what @scrubbless had in mind when requesting this, but this is how I would use it. So Yes: more than one attack of a type

**Comment by scrubbless** [comment]
The current monster attacks are imported from the official app.

The official attacks favour certain stats. For example a firearms check has a higher chance of using agility or observation. However some monster traits can effect that. For example if you use a physical attack on a ghost it will often make you test influence instead. That may be your experience.

Some extra functionality was added where scenario writers can create custom investigator attacks to attack custom monsters.

But I don't see why we shouldn't have the ability to add our own attacks to the generic pools. Though I'd suggest we submit it as a separate issue as an enhancement request.

**Comment by BenRQ** [comment]
Would this be good for you ?

![image](https://user-images.githubusercontent.com/40794717/52539931-199a8200-2d84-11e9-99c5-c2e8e38abb1c.png)

**Comment by scrubbless** [comment]
That would certainly fix the current bug (where we can't remove once added)!

Can you fit that in 2.2?

**Comment by BenRQ** [comment]
Yes, it's done.
