### ISSUE TITLE
Bug: Defeating a monster in Mythos Phase cancels other monsters' actions

### ISSUE THREAD

**Issue by chrismaliszewski** [NPBruce/valkyrie#982]
### Description of Problem or Question
Today I've received a new version from @BenRQ (2.2.20181209). I've found a major bug in the release which does not appear in the 2.15 version for some reason. The bug I found is major. It ends monsters' movement/attack event to progress even if there are more monsters to do their actions. 

### Valkyrie Version
@BenRQ's 2.2.20181209 (in 2.15 everything is ok)

### Scenario
1. Choose any scenario that spawns multiple numbers of monsters at the same time. I tried two: A Glimpse of the Past (go to the room at the top of the map and wait until multiple enemies arrive) and Exotic Material (go to the very far right of the map in a single Investigator's Phase and interact with one of the blue markers and pass the test to reveal enemies).
2. In Mythos Phase when the first monster attacks, deal a maximum damage and click Defeated.
As a result, after clicking Defeat button the mosters' movement/attacking phase is ended and Investigator's Phase Attack/Evade Menu appears instead of the Horror Check one although it's still a Mythos Phase (see the image: https://drive.google.com/open?id=1Ws8dXcElxksSjUoyyqYX3ErNBDxv4OMY). 

Something went very wrong here.

It'd be great to be able to deal a damage to a monster in here and be able to defeat it! Creators could create events that allow dealing damage to monsters here instead of in Investigator's Phase later on. It was like that in my case and that's why I defeated the monster. 
Don't remove the possibility, just repair the bug if possible.

**Comment by BenRQ** [comment]
Bug is now fixed in 2.2
