### ISSUE TITLE
Report scenario end-game feedback as 'issue' in originating repository.

### ISSUE THREAD

**Issue by antontimmermans** [NPBruce/valkyrie#983]
### Description of Problem or Question
I love fact that players can give their feedback and that the feedback is nicely captured in the google doc https://docs.google.com/spreadsheets/d/18V7lGE2JaYIuAFP_C6hbRRNKIid4oPqLBj3kcKtx64k/edit#gid=981738518

Enhancement request:
Can you send a copy of the end-game feedback is an 'issue' to the originating repository too, so that the scenario writer can more easilly keep track of the comments and feedback as he/she improves her scenario?

### Valkyrie Version
ANY

**Comment by BenRQ** [comment]
Hi @antontimmermans,

You request is not simple, I would have to share the credentials of a GitHub account in the app, support the login, keep the reference of all scenarios specific GitHub repo, and raise the issue itself.

I can propose an easier solution, available today : you can set notifications in the google sheet : https://support.google.com/docs/answer/91588?co=GENIE.Platform%3DDesktop&hl=en.

You can receive an email every time a new line is added in the file, or a daily email with all modifications.
It won't say if this is for your scenario, but you can check it at least.

**Comment by scrubbless** [comment]
I have imported the stats sheet into another sheet and shared it out.

I've just sorted them by scenario, but you could easily do the same yourself. Import range the data reference it in a second sheet the a create a filter on it. That way you can play with the filters to tune out everything but your own feedback.

Check the (appliers) Reviews tab in this sheet:
https://goo.gl/xgxdMb

**Comment by antontimmermans** [comment]
@scrubless @BenRQ 

Your solutions are not the same as my request but good enough. And since it is too complicated to implement, i'd rather spend time on other enhancements.

Thanks for your quick reply. closing the issue.
