### ISSUE TITLE
Enhancement: Long goading times

### ISSUE THREAD

**Issue by chrismaliszewski** [NPBruce/valkyrie#985]
I have a question. Why does the app take so much time to create lists of scenarios? 
After clicking Start Scenario, it takes 2 secs to just list 36 scenarios. That's a lot when you remember it's a local operation on files. 
Additionally, loading a list of downloadable scenarios takes... 35 seconds. I have ~23Mb/s download but it isn't a problem of the download but loading a list on the server; I am certain. 
What is even more annoying, all loadings happen every time you visit a list! Shouldn't they be loaded into the memory and updated when necessary? I.e. unless you download a new scenario to your computer, the list stays the same and the list on the server doesn't change all the time unless someone pushes a new version, right? 

Can someone describe how the data is created before being displayed? Am I right if I say, all files in a certain location are opened and a part of data from inside is taken? 

Couldn't you create a fast-accessible list with all information needed to make things load fast? A dictionary of some kind? It would contain all data which is needed to be displayed and other important pieces of information, i.e. version of the scenario and a checksum of scenario's file. The latter would be used to say that the list should be rebuilt and new data should be loaded from a new file. 

It'd be an enhancement. There must be two things done. 
1. Local machine changes: create a new function to create/rebuilt a dictionary, modify the function which now loads data from scenarios' files to return array/object which is used later, modify the function which displays final results so it loads them from the dictionary rather than scenarios' files. 
2. Server version: there should be a version of the list stored on both the server and a local machine. When a user accesses the server, the app first checks the version and if it's different than the current one, only then it downloads the whole list, otherwise, it should display a currently stored version from the machine (yes, it should be stored on a local machine). Think about it like a cookie/Local Storage. 

Loading times are crazy right now so I think a new way of loading data should be created.

**Comment by BenRQ** [comment]
Yes this clearly a major issue, with the amount of scenario getting more important.

This is something that has been identified before.

I have created a label for this task, as the amount of work to change the system is massive and it has been divided in different issues.
The top level issue is here :  #962.
It lists all tasks 
You will find all issues related to this under this label : "ScenarioExplorer"

Target is not only to improve performance but also to improve layout.

Please have a look at the list of issues and if you see anything missing, comment the issues related to the task.

I will close this one as it is a duplicate, but you can comment here if you think it should stay opened.
