### ISSUE TITLE
button issue - Only 1 button appears in event with quota - MoM

### ISSUE THREAD

**Issue by MatthieuLPro** [NPBruce/valkyrie#993]
### Problem
I have an issue when I add many buttons in a event with Quota : Variable. There is only the first button appears but not the 2 others. Someone has a solution for this issue ?
Thank you

### Valkyrie Version
Valkyrie 2.1.3

### Screenshot
![full_event](https://user-images.githubusercontent.com/43676470/50542944-0d3dd980-0bc9-11e9-823e-8c307d0f12dc.png)
![test_image](https://user-images.githubusercontent.com/43676470/50542947-129b2400-0bc9-11e9-8880-654b75114ba3.png)

**Comment by BenRQ** [comment]
Salut @MatthieuLPro :)

I've checked the code, and Quota will only display one button.
"        // Only one button, action depends on quota  "

Why are you using quota if you are not requesting a test to players in the text ?

Seeing your text I will suggest to first ask what is the action decided the player wants to do, then do request a test (quota) depending on that.

**Comment by MatthieuLPro** [comment]
Thank you for your swift answer !
Yeah I tried this solution to avoid to write text ^^''. What I was looking for it's to write 1 description for the all 3 possible actions instead of 3 descriptions for each actions.

J'ai commencé en mi-novembre et je pensais finir mon scénario pour fin décembre, mais je ne me rendais pas compte de la quantité de travail que sa demande ... Et je m'amuse à rajouter un maximum de liberté au joueur ce qui crée des fois des effets en cascade que je prévois mal ! Je dois en être à la moitié à peu près, je pense pouvoir le proposer pour fin février si j'arrive à le faire tester rapidement à l'entourage pour le debugging et les ajustements !

Merci pour la réponse, je vais utiliser ta solution pour la suite.

**Comment by BenRQ** [comment]
On a fait un groupe Facebook "Les demeures de l'épouvante - Fan club", si tu veux rejoindre et/ou si tu cherches des testeurs :)
