### ISSUE TITLE
include otherfiles in event.ini

### ISSUE THREAD

**Issue by antontimmermans** [NPBruce/valkyrie#994]
### Description of Problem or Question
Question:
My new scenario starts to grow rapidly in filesize  and number of events, Currently it is close to 300 events and growing and event.ini is over 2k lines. I am using a strict naming convention for my code to keep it organized but I start to feel the need to break-up the big event.ini in separate files.

Is there a way to break-up the event.ini file in to smaller parts and include them in the mainfile? Or is this Done in the quest.ini file? and if yes, how does it work?

If this feature does not exist yet would it be feasible to add something like this?

### Attach Save, Quest or Scenario
Saves:  
%appdata%/Valkyrie/MoM/Save  
%appdata%/Valkyrie/D2E/Save  
Quest:  
%appdata%/Valkyrie/D2E/Editor  
Scenario:  
%appdata%/Valkyrie/MoM/Editor

**Comment by scrubbless** [comment]
Yes it is possible, for example that would be how to do it in descent Descent for a campaign.
I believe its done in the events.ini, but have not got round to it yet myself (I focus on MoM).

Ask in the Descent channel on Discord, there are a couple good Descent scenario writers in there.
https://discord.gg/cB8Z9P

**Comment by NPBruce** [comment]
event.ini is just the default for events, it can be changed by selecting the event.ini button at the bottom of the event. You can combine events and other components into the same file and group them however you like (for example by room, or anything else).

You can then use file filters in the component selector to find the components from particular (or excluding particular) files.

To do it manually just add the ini file you want to use to quest.ini and add components.

**Comment by antontimmermans** [comment]
Closing the issue as it is not an issue anymore. 

If someone happens to know the answer to the "constants" question, feel free to answer it on this ticket since its still interrestig to know if it could be done. Nice to know... but no reason to keep this ticket open. 

Original question is answered --> ticket closed
