### ISSUE TITLE
Puzzle item not displaying UI when solved

### ISSUE THREAD

**Issue by antontimmermans** [NPBruce/valkyrie#995]
### Description of Problem or Question
An puzzle item that gets handed during gameplay can accessed via the inventory.:
- When it is selected in the inventory while the puzzle is not solved it wil display the puzzle. Solving the puzzle will display the result with additional text.
- When it is selected in the inventory while the puzzle is solved, it should display the result and the text. But it doesn't. I am not sure if it is a scenario bug or a valkyrie bug. 

**How to reproduce:**
The scenario starts with displaying a clue token which I use for test purposes.

1. Select from test clue select: **Place Lobby**. and click until all placed
2. Select from test clue token:  **Get Map**
3. Select from items the old map and solve the puzzle.
4. After solving the puzzle, select the old map again from the Items.

### Valkyrie Version
Valkyrie2.2.20181209  (<- NOTE TEST VERSION)

### Attach Save, Quest or Scenario
Scenario:  
https://github.com/antontimmermans/MOMCDM

Note this scenario is very much work in progress and not playable! It CANNOT be used with current public version of Valkyrie 2.1.5. Only with the listed test version (or higher)

**Comment by scrubbless** [comment]
You should not use a puzzle for an item inspect. I can't see a logical way for a puzzle to understand that it's complete but not trigger the completion event a second time (without using events with variables).

You should create an event for the inspect and put an event (in that event have a test for a variable like  'puzzledsolved == 1') and then the second puzzle event being sequencial  after it.

Once the puzzle is complete use the completion event to  assign a variable to say it's complete ('puzzlesolved = 1') this means when the item is inspected again it will trigger the puzzle complete event, not retrigger the puzzle.

The other option is to use 'remove components' to discard the item and give the players a new one (could even be the same item in a new qitem with a different inspect event).

**Comment by scrubbless** [comment]
Rereading that I understand it sounds complex but it's not. If you don't understand my meaning let me know and I'll create a test scenario to explain it better.

**Comment by antontimmermans** [comment]
> Hi @antontimmermans
> 
> 1. I will send you a PR so you can use the latest test version, with the proper naming for tests
> 2. there is a problem with the EventGhostPlaceLadyBedroomB : you have too many parenthesis
> 3. Seems like all events are called without displaying any button when accessing the map a second time.
>    I need to have a closer look at this.
> 

hi @BenRQ 
1. If you explain how they should be renamed once the new version comes, I will find&replace them in my code.
2. Thanks for detecting that, oddly enough it seemed to be working without problem :S. The problem however is not to much parenthesis, but not enough parenthesis. it is missing the last ')'.
3. The event has a 'Continue' button which clears the UI item when clicked. The 'without displaying' triggered remark triggered me to look again in the code. Notice the **display=false** which I think is the guilty part.
```
[EventQItemOldMapShowA]
display=false
buttons=1
event1=EventQOldMapClear
add=UIOldMapA
```

I will correct both issues tonight.

@scrubbless 
I think I get your point and I even think that it is how I programmed it. During the game a player gets this QItem. When inspecting this Qitem (puzzlesolved==0) it appears to be a scrambled piece of paper that can be unscrambled by solving a puzzle. Upon solving the puzzle a UIOldMap is displayed, including an explaining text and a clue token given to the player. Clicking Continue will then remove the UIOldMap.
When inspecting this Qitem (puzzlesolved!=0) it should display the UIOldMap including an explaining text. Clicking Continue will then remove the UIOldMap.

In events it looks like this:
```
[EventQItemOldMapInspect]
display=false
buttons=1
event1=EventQItemOldMapUnsolved EventQItemOldMapSolved

[EventQItemOldMapUnsolved]
vartests=VarOperation:OldMapSolved,==,0 
buttons=2
event1=PuzzleQItemOldMapA 
event2=

[EventQItemOldMapSolveA]
operations=OldMapSolved,=,1
buttons=1
event1=EventQOldMapClear
add=UIOldMapA

[EventQItemOldMapSolved]
vartests=VarOperation:OldMapSolved,!=,0 
display=false
buttons=1
event1=EventQItemOldMapShowA 
```

**Comment by antontimmermans** [comment]
hi @BenRQ , @scrubbless 

Thank you both for your quick response.  Both issues are repaired:
The lady in the bedroom was indeed missing a ')' (and some more but telling THAT would be a spoiler ;-))

The original non-displaying issue was indeed caused by "display=false". Propably caused by me wanting to go faster and copy and paste to much :s

Closing the issue.
