### ISSUE TITLE
 New Scenario

### ISSUE THREAD

**Issue by EMILIPULIDO** [NPBruce/valkyrie#996]
New Scenario in Spanish
[https://github.com/EMILIPULIDO/VuelveXNavidad/tree/Scenario](url)
[https://github.com/EMILIPULIDO/VuelveXNavidad](url)
Valkyrie Version   Ver 2.1.5
Pure Lovecraftian investigation. Or similar, ha ha.
Thanks a lot!!

**Comment by redwolf2** [comment]
Please use a scenario image with a equal width and height.

**Comment by EMILIPULIDO** [comment]
Ok. Image Resized. And Test Menu deleted (!)
If you've any new problem I'm here, please
Thanks

**Comment by redwolf2** [comment]
Looks good. @scrubbless might want to check and add it.

**Comment by scrubbless** [comment]
I'll sort it for you soon!

**Comment by EMILIPULIDO** [comment]
Thank you  @scrubbless  and @redwolf2

**Comment by scrubbless** [comment]
I'll get it added to the review stats spreadsheet when I get a chance.

**Comment by EMILIPULIDO** [comment]
Oh! sorry. I've landed a new patch version. Fixed error, thanks to a good user.

**Comment by BenRQ** [comment]
No problem @EMILIPULIDO, as soon as you update the package on your repo, it is updated for all players who want to download it.
If they have already downloaded it, an update will be proposed (in the download page).

So you can manage update and evolutions by yourself :)
