### ISSUE TITLE
Investigator dependant starting items

### ISSUE THREAD

**Issue by antontimmermans** [NPBruce/valkyrie#997]
When starting items are distibuted, special items are handed out as starting items when specific investigators are selected (see also #46):

- "Ashcan" Pete - Unique Item Duke (the dog);
- Kate Winthrop - Unique Item Flux Stabilizer.
- Tommy Muldoon -  Unique Item Becky  (gun)
- Agnes Barnes - Storm of Spirits (Spell)
- Jim Culver - Unique item Golden Trumpet (<- new in horrific journies, super power!)

Question:
Is there a way to conditionally hand out starting items? 

1. **Depending on specific investigator (s).** for example: when Tommy Muldoon is selected, you do NOT hand out another ranged weapon. And when Agnes Barnes is selected, you do not handout another spell.
2. **Depending on number of investigators** for example: hand out more items with less investigators (to balance the dificulty)? Or hand out more items with more players so everyone gets something.

**Comment by scrubbless** [comment]
I personally don't think special items should be considered in starting item distribution. Simply because those items often are the characters special abilities.

**Comment by antontimmermans** [comment]
I did not mean to NOT hand out the "duke" to Pete (etc..). Obviously the items linked to characters MUST be handed out as reported on the cards in the game.
My question is about conditionally handing out other start items (see two given examples).

To elaborate: when Tommy Muldoon is in game, he gets handed the unique item Becky. Wich means that  there is already a ranged weapon in the game at the start. I might not want to handout another ranged weapon.

**Comment by scrubbless** [comment]
That's my point. Tommy is given that weapon as his special ability. If you can assume that no other ranged weapon is given then why not bring another investigator with an ability because you might get a decent ranged weapon too.

It would be like saying,  Rita young is in the group, don't give the players the track shoes (+1 move).

Personally is exclude the damage 3 and higher weapons from the starting items. That's a decent way to balance out starting items imo.

**Comment by antontimmermans** [comment]
If required, this 'feature' can be built in the scenario with the currently available functionality in Valkyrie. Closing the issue.
