### ISSUE TITLE
shop system - MoM

### ISSUE THREAD

**Issue by MatthieuLPro** [NPBruce/valkyrie#998]
### Description of Problem or Question
Hello !
Is it possible to use the shop system from D2e in MoM ?
This is appearing when I add more than 1 qitem in the same event.

Thank you !

### Valkyrie Version
All

### Attach Save, Quest or Scenario
![buy_sell_item](https://user-images.githubusercontent.com/43676470/50735728-a82f4880-11b3-11e9-9acf-7c04958886ae.gif)

**Comment by BenRQ** [comment]
It's a bug.

**Comment by BenRQ** [comment]
Please note you should not use more than 1 QItem per event.
@MatthieuLPro what exactly did you want to do here ?

I can fix this behaviour by using only the first item and ignoring the additional items.

**Comment by MatthieuLPro** [comment]
I just tried to add 2 Qitems in the player's equipment ... So it's not difficult to avoid this problem. :) 
What do you mean by :

> I can fix this behaviour by using only the first item and ignoring the additional items.

**Comment by BenRQ** [comment]
> What do you mean by :
> 
> > I can fix this behaviour by using only the first item and ignoring the additional items.

Even if there is more than one item in an event, there can be only one item used.
I could just ignore the fact that we have additional item, and not display the shop.

But better solution would be to limit this in the editor.

**Comment by BenRQ** [comment]
I would need help to understand what is expected when two qitems are in an event, for MoM.

Would you agree that I use only the first item ?
I don't think it will be easy to implement a clear limitation in editor.

@scrubbless @redwolf2

**Comment by scrubbless** [comment]
You should only use one item per event in MoM. Camera will show show one item next to the description text. Highlight will show the item as an icon on the board (to indicate where on the board the item is placed).

There is no use case for adding two qitems in one event in MoM.

But in descent multiple items in an event I believe is the shop, so be wary of descent functionality if you change anything on this.

I am not sure how easy it will be to limit adding qitems in events without limiting components.

**Comment by BenRQ** [comment]
OK thanks.
So I will just ignore this in MoM and print a warning in the logs.

**Comment by BenRQ** [comment]
Done.
